### ISSUE TITLE
Make a list of features to be added between v0.14.x

### ISSUE THREAD

**Issue by tagomoris** [fluent/fluentd#1000]
1. add items as comments on this issue
2. make it as wiki page

**Comment by tagomoris** [comment]
Update forward protocol to add optional `size` to tell number of records included in transferred chunk

**Comment by tagomoris** [comment]
Merge authentication/authorization (secure-forward) protocol to forward plugin

**Comment by tagomoris** [comment]
[mixin] move RecordFilter mixin to `lib/fluent/compat` and make other plugin helpers to do it

**Comment by tagomoris** [comment]
[plugin helpers] Create Socket/Server plugin helpers

**Comment by tagomoris** [comment]
[system config] Root path for buffers / storages

**Comment by tagomoris** [comment]
Symmetric multi process support

**Comment by tagomoris** [comment]
[buffer plugin] Create compressed file buffer plugin

**Comment by tagomoris** [comment]
[forward] Compressed chunk transferring

**Comment by tagomoris** [comment]
Counter API over RPC

**Comment by tagomoris** [comment]
[system config] System wide buffer bytesize limit

**Comment by tagomoris** [comment]
Secondary plugin to dump buffer content to file (only for secondary) & rescue command line tool for it

**Comment by tagomoris** [comment]
Plugin generator command & template

**Comment by tagomoris** [comment]
[forward] TLS support

**Comment by tagomoris** [comment]
[output] Chunking a event stream into 2 or more smaller chunks with splitting

**Comment by tagomoris** [comment]
[forward] Update forward protocol to add optional id (or chunk_id, unique_id) to propagate chunk unique id from source to destination for tracing/auditing.

**Comment by repeatedly** [comment]
[log] Make ServerEngine log setting configurable.

**Comment by frsyuki** [comment]
rolling restart of worker processes so that always some worker processes accept new sockets from listening sockets managed by SocketManager

**Comment by frsyuki** [comment]
add limitation or add warning messages to too many number of <buffer CHUNK_KEYS> to prevent too many small buffer chunks due to  combination explosion

**Comment by tagomoris** [comment]
[filter optimization] pipelining `#filter` methods in `Fluent::EventRouter::Pipeline`

**Comment by tagomoris** [comment]
[plugin helper] New plugin helper to handle nested records and standard syntax for nested field keys (JSONPath?)

**Comment by tagomoris** [comment]
[output plugin optimization] optimize `#extract_placeholder` method

**Comment by tagomoris** [comment]
[output plugin optimization] optimize `Fluent::Plugin::Output#metadata` method

**Comment by tagomoris** [comment]
[event stream] introduce lazy deserialization on event stream object based on new msgpack feature
https://gist.github.com/frsyuki/956850ba7696810904225305c42e9379

**Comment by tagomoris** [comment]
[configuration] `<copy>` section as a sugar syntax of `<match>@type copy</match>`

**Comment by tagomoris** [comment]
I created a wiki page for these items: https://github.com/fluent/fluentd/wiki/Changes-proposed-for-v0.14.x

**Comment by tagomoris** [comment]
[plugin api] add a method to return `time` and `record`, and return something to drop that event explicitly.
Current `#format_stream` cannot be pipelined, but `#format` doesn't permit plugins to update time. Updating time is very common, and parser's API allows to return time.

**Comment by tagomoris** [comment]
For further features and improvements, edit wiki page directly.
