### ISSUE TITLE
Startup error with kinesis plugin after upgrading td-agent from 0.12 to 0.14

### ISSUE THREAD

**Issue by comtef** [fluent/fluentd#1011]
Upgraded from version 0.12 to version 0.14 and faced the following problem at startup (kinesis plugin) :

2016-05-31 09:48:46 +0000 [error]: unexpected error error="uninitialized constant Fluent::DetachMultiProcessMixin"

I wasn't able to stop td-agent after this point : "service td-agent stop" was not working anymore, had to kill the process

Environnement : Amazon EC2 instance (Amazon AMI).
kinesis plugin version 1.0.1
Upgraded all gems with td-agent-gem

The same configuration is working if 0.14 is installed on a brand new instance (no upgrade).

**Comment by tagomoris** [comment]
#1014 was merged into master.
@comtef Could you confirm whether this issue was solved or not by installing Fluentd from master branch?

**Comment by comtef** [comment]
Yes, the kinesis plugins works with your patch but I still can't stop td-agent.

> sudo service td-agent stop
> Stopping td-agent:                                         [  OK  ]

But no effect

> sudo service td-agent restart
> Restarting td-agent:                                       [FAILED]

And in logs
> 2016-06-02 09:33:21 +0000 [error]: dry run failed: Operation not permitted

**Comment by riywo** [comment]
I've fixed this problem on the plugin with requiring `fluent/process` explicitly. I'll release the new version of the plugin soon.
https://github.com/awslabs/aws-fluent-plugin-kinesis/issues/70

I'm not sure the stopping problem, though.
