### ISSUE TITLE
fluent-plugin-elasticsearch test fails with v0.14.0

### ISSUE THREAD

**Issue by okkez** [fluent/fluentd#1012]
### How to reproduce

```
$ git clone https://github.com/uken/fluent-plugin-elasticsearch.git
$ cd fluent-plugin-elasticsearch
$ git remote add okkez git@github.com:okkez/fluent-plugin-elasticsearch.git
$ git co okkez/fix-for-fluentd-v.14 fix-for-fluentd-v0.14
(I'm trying to fix fluent-plugin-elasticsearch test)
$ bundle install
$ bundle exec rake test
```

### Result

https://gist.github.com/okkez/473f59be4b6e65e144929efbc51920bd

1. Error: test_adds_logstash_timestamp_when_configured(ElasticsearchOutputDynamic): TypeError: no implicit conversion of nil into String
2. Failure: test_configure(ElasticsearchOutputDynamic)
3. ...snip

I think above errors and failures have same cause.
There are problems.

* `config_param` default value overwriting does not work properly
  * In this case, `Fluent::ElasticsearchOutputDynamic < Fluent::ElasticsearchOutput`
  * `logstash_format` is overwritten in `Fluent::ElasticsearchOutputDynamic#initialize` but re-overwritten in `Fluent::Configurable#configure`
* `type_lookup` is not overwriten, maybe (Failure: test_configure(ElasticsearchOutputDynamic))
* `merged_configure_proxy` has wrong name such as `Fluent::Plugin::Base` I expected real plugin name like `Fluent::ElasticSearchOutputDynamic`

**Comment by tagomoris** [comment]
IMO ElasticSearchOutputDynamic looks too hacky, and it seems to operate values from configurations after `configure`... it cannot be coverable from Fluentd core.
`name` overriding of `merged_configure_proxy` is another problem. @okkez could you open another issue for that?

**Comment by okkez** [comment]
OK, I see that Fluentd core cannot cover `ElasticsearchOutputDynamic`.

I will create another issue for `merged_configure_proxy`.
