### ISSUE TITLE
Unknown input plugin 'unix'

### ISSUE THREAD

**Issue by cbh34680** [fluent/fluentd#1016]
Install td-agent2 and faced the following problem at startup

- version: td-agent2 (td-agent-2.3.1-0.el6.x86_64)
- OS: centos 6.8
- Configuration (/etc/td-agent/td-agent.conf)

```
<source>
  @type unix
  path  /var/run/td-agent/td-agent.sock
</source>
```

- fluent startup log
```
2016-06-02 12:51:53 +0900 [error]: config error file="/etc/td-agent/td-agent.conf" error="Unknown input plugin 'unix'. Run 'gem search -rd fluent-plugin' to find plugins"
```

- step

1. Install td-agent with "install-redhat-td-agent2.sh"
2. Wrote "/etc/td-agent/td-agent.conf"
3. Update all gems "td-agent-gem update"
4. Start process "service td-agent start"

**Comment by repeatedly** [comment]
It seems a regression of v0.14.0.
v0.14.0 doesn't require all `fluent/plugin/*` files in the fluentd gem so in_unix doesn't found.

@tagomoris Please rename `in_stream` to  `in_unix`.

**Comment by tagomoris** [comment]
Oh, ok. will do.

**Comment by tagomoris** [comment]
Fixed on master.
