### ISSUE TITLE
Daemonize doesn't create pid file in 0.14.0

### ISSUE THREAD

**Issue by kakoni** [fluent/fluentd#1018]
Using 
- fluentd 0.14.0
- CentOS 6.7
- Empty fluent.conf

Running
` fluentd -c fluent.conf  --daemon /tmp/test.pid`

Expected result:
/tmp/test.pid with process id

Actual result:
No /tmp/test.pid file

**Comment by niallbrown** [comment]
+1

**Comment by repeatedly** [comment]
@tagomoris It seems urgent issue. Could you handle this?

**Comment by tagomoris** [comment]
OK.

**Comment by tagomoris** [comment]
The code to fix this issue was merged into master.

**Comment by kakoni** [comment]
Yes, thank you!
