### ISSUE TITLE
unable to connect to unix:///var/run/td-agent/td-agent.sock (Permission denied)

### ISSUE THREAD

**Issue by cbh34680** [fluent/fluentd#1019]
Install td-agent2 and faced the following problem at sending data

- Version: td-agent2 (fluentd 0.14.0)
- OS: CentOS 6.8
- Configuration

```
<source>
  @type unix
  path  /var/run/td-agent/td-agent.sock
</source>
```

- step

1. Install td-agent with "install-redhat-td-agent2.sh"
2. Wrote "/etc/td-agent/td-agent.conf"
3. Update all gems "td-agent-gem update"
4. Apply #1017 (rename in_stream.rb to in_unix.rb)
5. Start process "service td-agent start"

- problem

it is not allowed to write for group and other

**td-agent1**
```
# ls -l /var/run/td-agent/td-agent.sock
srwxrwxrwx 1 td-agent td-agent 0  4月 14 17:52 2016 /var/run/td-agent/td-agent.sock
```
**td-agent2**
```
# ls -l /var/run/td-agent/td-agent.sock
srwxr-xr-x 1 td-agent td-agent 0  6月  3 12:30 2016 /var/run/td-agent/td-agent.sock
```

**Comment by repeatedly** [comment]
Is it happend without `td-agent-gem update`?

**Comment by cbh34680** [comment]
I tried it.

```
]# ls -l /var/run/td-agent/
合計 4
-rw-r--r-- 1 td-agent td-agent 4  6月  3 16:16 2016 td-agent.pid
srwxrwxrwx 1 td-agent td-agent 0  6月  3 16:16 2016 td-agent.sock
```

It did not occur.
Is it incorrect to do "td-agent-gem update" ?

**Comment by repeatedly** [comment]
`td-agent-gem update` now installs v0.14.0 and it seems having a problem with --user/--group handling.

BTW, we don't recommend `td-agent-gem update` without any restriction.

**Comment by repeatedly** [comment]
@naritta @tagomoris Did you change this routine? We replaced core with ServerEngine. Does it affect user/group handling?

**Comment by cbh34680** [comment]
I understand.
Thank you for advice.

**Comment by tagomoris** [comment]
@repeatedly I have no idea about it... but there are nothing around file permissions related with serverengine as far as I remember.

**Comment by naritta** [comment]
I'll investigate this.

**Comment by naritta** [comment]
I guess here (https://github.com/treasure-data/td-agent/blob/b5f59de08d5a87028466fea72e2027baa7be3ec1/Makefile.am#L39) does't run well.
I'm investigating more.

**Comment by repeatedly** [comment]
@naritta td-agent repository is outdated. Check omnibus-td-agent instead.

**Comment by tagomoris** [comment]
@repeatedly Please check this issue to fix because @naritta seems busy now.

**Comment by repeatedly** [comment]
@tagomoris okay.

**Comment by repeatedly** [comment]
Memo:

- fluentd v0.12.x's `File.umask` returns 0 in supervisor and worker.
- fluentd v0.14.x's `File.umask` returns 18 in supervisor and worker.
