### ISSUE TITLE
Multiple reports of fluentd hanging

### ISSUE THREAD

**Issue by a-robinson** [fluent/fluentd#1020]
- fluentd or td-agent version.
  0.12.12 (although with the possibility that it also affects more recent versions)
- Environment information, e.g. OS.
  In a [Docker container based on ubuntu:14.04](https://github.com/kubernetes/kubernetes/blob/release-1.1/cluster/addons/fluentd-gcp/fluentd-gcp-image/Dockerfile)
- Your configuration
  https://github.com/kubernetes/kubernetes/blob/release-1.1/cluster/addons/fluentd-gcp/fluentd-gcp-image/google-fluentd.conf
  The most unusual bits are the use of the record_reformer filter and the google cloud output plugin. It's also worth noting that some of the files read by in_tail are actually symlinks, as noted in #767.
- Your problem explanation. If you have an error logs, write it together.
  A few different kubernetes users running on compute engine and/or container engine have reported that their fluentd containers have stopped sending logs to Google's cloud logging API (the logging team has confirmed that the logs stopped getting sent). The weird part is that in all of these cases fluentd container did not die or restart, and the processes didn't log anything at all. They're running with -q, which suppresses debug/info logs, but I'd expect anything that prevents logs from getting flushed to at least justify a warning message.

In at least one of the cases, the fluentd agent was under some memory pressure, using about 185MB out of its container's allotted 210MB.

Killing the container and starting a new one has always fixed the issue.

I know this probably isn't enough info to go off of unless there's already something that you're suspicious of, but do you have recommendations on how to properly debug this next time it comes up? Is there an easy way to generate a stack trace or otherwise determine where it's stuck? We haven't explicitly configured it to open up a debug port. What instructions could I give to a user to help track this down?

**Comment by a-robinson** [comment]
cc @repeatedly @jimmidyson

**Comment by repeatedly** [comment]
I'm not familiar with Kubernetes and Docker so I can't judge this problem is caused by fluentd or plugin or Docker.
If you can send a signal to fluentd instance, sending -CONT to fluentd process for dumping internal status is useful for debugging.

**Comment by repeatedly** [comment]
We use sigdump to dump memory allocation and thread traces: http://docs.fluentd.org/articles/trouble-shooting#dump-fluentd-internal-information

**Comment by a-robinson** [comment]
Thank you, Masahiro, I appreciate the quick response. I'll report back once I'm able to determine what the root cause is, which'll have to wait until another occurrence of this pops up.

**Comment by a-robinson** [comment]
So I was able to get some debugging info from a Kubernetes user who can pretty reliably reproduce the situation when doing an update of their application (which manifests to Fluentd as new log files showing up in the glob used by in_tail and old files no longer being appended to). There's a deadlock somewhere, but I'm not yet sure where.

The stuck process was stuck trying to wait on a futex, with `strace` giving the following series of system calls and signals:

```
futex(0x1369054, FUTEX_WAIT_PRIVATE, 15311708, NULL) = ? ERESTARTSYS (To be restarted)
--- SIGVTALRM (Virtual timer expired) @ 0 (0) ---
rt_sigreturn(0x1a)                      = -1 EINTR (Interrupted system call)
futex(0x1369054, FUTEX_WAIT_PRIVATE, 15311708, NULL) = ? ERESTARTSYS (To be restarted)
--- SIGVTALRM (Virtual timer expired) @ 0 (0) ---
rt_sigreturn(0x1a)                      = -1 EINTR (Interrupted system call)
futex(0x1369054, FUTEX_WAIT_PRIVATE, 15311708, NULL) = ? ERESTARTSYS (To be restarted)
--- SIGVTALRM (Virtual timer expired) @ 0 (0) ---
rt_sigreturn(0x1a)                      = -1 EINTR (Interrupted system call)
futex(0x1369054, FUTEX_WAIT_PRIVATE, 15311708, NULL) = ? ERESTARTSYS (To be restarted)
--- SIGVTALRM (Virtual timer expired) @ 0 (0) ---
rt_sigreturn(0x1a)
```

The other fluentd process had no syscall/signal activity according to strace.

The bad news in all of this is that the stuck process apparently didn't dump its stack in response to being sent a SIGCONT, so it's tough to tell where the process is getting deadlocked.

I've attached a file below with the instructions that the user followed to get debugging info and the output that they got. Do you have any other suggestions of how to follow up on this, @repeatedly?

[fluentd_traces.txt](https://github.com/fluent/fluentd/files/307964/fluentd_traces.txt)

**Comment by repeatedly** [comment]
@nurse Did you see a similar problem in Ruby issues?

**Comment by nurse** [comment]
@repeatedly I don't know.
The SIGVTALRM looks trying to wake up another thread which is waiting I/O, but maybe such thread doesn't exist?

To inspect further it will be Linux task.
May be you can know what is happening by following commands:
* `ps -lLFe` can get what threads are running and its status.
* `sudo perf top -g -p <pid>` can get what functions are working in the process and what calls the function.

**Comment by ibalashov** [comment]
Meanwhile, can we detect hanging fluend and restart its container as a temp workaround?

**Comment by a-robinson** [comment]
@ibalashov in what context? Do you mean in kubernetes specifically? Or in fluentd's supervisor process?

**Comment by a-robinson** [comment]
I have direct access to another instance of this, although its strace is slightly different from the previous instance. Instead of a FUTEX_WAIT_PRIVATE timing out, it was just stuck on one for a long time:

```
# strace -p 4800
Process 4800 attached - interrupt to quit
futex(0x1d66054, FUTEX_WAIT_PRIVATE, 252906941, NULL) = -1 EAGAIN (Resource temporarily unavailable)
futex(0x1d66054, FUTEX_WAIT_PRIVATE, 252906942, NULL^C <unfinished ...>
Process 4800 detached
```

Then, inside the docker container, I try the more advanced `ls` suggested by @nurse:

```
# ps xa
  PID TTY      STAT   TIME COMMAND
    1 ?        Ss     0:00 /bin/sh -c /usr/sbin/google-fluentd "$FLUENTD_ARGS"
    6 ?        Sl     0:00 /opt/google-fluentd/embedded/bin/ruby /usr/sbin/googl
    8 ?        Sl   1697:55 /opt/google-fluentd/embedded/bin/ruby /usr/sbin/goog
   38 ?        Ss     0:00 bash
   51 ?        R+     0:00 ps xa

# ps -lLFe
F S UID        PID  PPID   LWP  C NLWP PRI  NI ADDR SZ WCHAN    RSS PSR STIME TTY          TIME CMD
4 S root         1     0     1  0    1  80   0 -  1112 -        692   3 May19 ?        00:00:00 /bin/sh -c /usr/sbin/google-fluentd "$FLUENTD_ARGS"
0 S root         6     1     6  0    2  80   0 - 27181 -      27508  11 May19 ?        00:00:00 /opt/google-fluentd/embedded/bin/ruby /usr/sbin/google-fluentd -
1 S root         6     1     9  0    2  80   0 - 27181 -      27508   4 May19 ?        00:00:00 /opt/google-fluentd/embedded/bin/ruby /usr/sbin/google-fluentd -
1 S root         8     6     8  0   14  80   0 - 237989 -     114920  6 May19 ?        00:02:19 /opt/google-fluentd/embedded/bin/ruby /usr/sbin/google-fluentd -
1 S root         8     6    10  0   14  80   0 - 237989 -     114920  0 May19 ?        00:09:21 /opt/google-fluentd/embedded/bin/ruby /usr/sbin/google-fluentd -
1 S root         8     6    12  0   14  80   0 - 237989 -     114920 10 May19 ?        00:03:56 /opt/google-fluentd/embedded/bin/ruby /usr/sbin/google-fluentd -
1 S root         8     6    14  1   14  80   0 - 237989 -     114920  3 May19 ?        09:02:44 /opt/google-fluentd/embedded/bin/ruby /usr/sbin/google-fluentd -
1 S root         8     6    15  0   14  80   0 - 237989 -     114920 12 May19 ?        00:31:47 /opt/google-fluentd/embedded/bin/ruby /usr/sbin/google-fluentd -
1 S root         8     6    16  0   14  80   0 - 237989 -     114920  8 May19 ?        00:07:38 /opt/google-fluentd/embedded/bin/ruby /usr/sbin/google-fluentd -
1 S root         8     6    17  0   14  80   0 - 237989 -     114920 12 May19 ?        00:07:12 /opt/google-fluentd/embedded/bin/ruby /usr/sbin/google-fluentd -
1 S root         8     6    18  0   14  80   0 - 237989 -     114920 10 May19 ?        00:07:07 /opt/google-fluentd/embedded/bin/ruby /usr/sbin/google-fluentd -
1 S root         8     6    19  0   14  80   0 - 237989 -     114920 12 May19 ?        00:07:27 /opt/google-fluentd/embedded/bin/ruby /usr/sbin/google-fluentd -
1 S root         8     6    20  0   14  80   0 - 237989 -     114920 10 May19 ?        00:10:49 /opt/google-fluentd/embedded/bin/ruby /usr/sbin/google-fluentd -
1 S root         8     6    21  1   14  80   0 - 237989 -     114920  7 May19 ?        10:00:35 /opt/google-fluentd/embedded/bin/ruby /usr/sbin/google-fluentd -
1 S root         8     6    22  0   14  80   0 - 237989 -     114920  7 May19 ?        04:10:43 /opt/google-fluentd/embedded/bin/ruby /usr/sbin/google-fluentd -
1 S root         8     6    23  0   14  80   0 - 237989 -     114920  7 May19 ?        03:20:00 /opt/google-fluentd/embedded/bin/ruby /usr/sbin/google-fluentd -
1 S root         8     6    24  0   14  80   0 - 237989 -     114920  6 May19 ?        00:16:10 /opt/google-fluentd/embedded/bin/ruby /usr/sbin/google-fluentd -
4 S root        38     0    38  0    1  80   0 -  4537 -       3276  15 21:35 ?        00:00:00 bash
0 R root        52    38    52  0    1  80   0 -  3893 -       2220   3 21:36 ?        00:00:00 ps -lLFe
```



From outside the container again (getting the right dependencies inside a container to match the host kernel has been causing me a lot of frustration lately):

```
# perf top -g -p 4800
Samples: 388  of event 'cpu-clock', Event count (approx.): 2761049              
+   14.00%    14.00%  libc-2.19.so        [.] 0x0000000000108170
+   11.83%    11.83%  [kernel]            [k] do_sys_poll
+    8.74%     8.74%  libruby.so.2.1.0    [.] 0x00000000001d2014
+    8.44%     8.44%  libc-2.19.so        [.] 0x00000000000ed107
+    8.23%     8.23%  [kernel]            [k] pvclock_clocksource_read
+    8.02%     8.02%  [kernel]            [k] _raw_spin_unlock_irqrestore
+    6.28%     6.28%  libruby.so.2.1.0    [.] 0x000000000014b916
+    6.15%     6.15%  [kernel]            [k] __fget_light
+    5.55%     5.55%  libpthread-2.19.so  [.] 0x000000000000a417
+    3.17%     3.17%  [kernel]            [k] add_wait_queue
+    3.11%     3.11%  libruby.so.2.1.0    [.] 0x00000000001d1e3d
+    2.72%     2.72%  libc-2.19.so        [.] 0x00000000001081d8
+    2.38%     2.38%  libpthread-2.19.so  [.] 0x000000000000a410
+    1.85%     1.85%  libruby.so.2.1.0    [.] 0x00000000001d1e6b
+    1.64%     1.64%  libruby.so.2.1.0    [.] 0x00000000001d1e40
+    1.60%     1.60%  [kernel]            [k] __pollwait
+    1.07%     1.07%  libc-2.19.so        [.] 0x00000000001081e0
+    0.94%     0.94%  [kernel]            [k] hrtimer_init
+    0.72%     0.72%  [kernel]            [k] poll_schedule_timeout
+    0.72%     0.72%  [kernel]            [k] sys_poll
+    0.62%     0.62%  libruby.so.2.1.0    [.] 0x00000000001d1dbe
+    0.42%     0.42%  [kernel]            [k] schedule_hrtimeout_range_clock
+    0.28%     0.28%  libpthread-2.19.so  [.] 0x000000000000a414
+    0.21%     0.21%  libruby.so.2.1.0    [.] 0x00000000001d1f1a
+    0.19%     0.19%  [kernel]            [k] timespec_add_safe
+    0.18%     0.18%  libpthread-2.19.so  [.] 0x000000000000b7c0
+    0.17%     0.17%  [kernel]            [k] __fget
+    0.17%     0.17%  libc-2.19.so        [.] 0x00000000000ed100
+    0.15%     0.15%  libc-2.19.so        [.] 0x00000000000ed131
+    0.13%     0.13%  libpthread-2.19.so  [.] 0x000000000000a490
+    0.07%     0.07%  libruby.so.2.1.0    [.] 0x00000000001d1f3d
+    0.07%     0.07%  libruby.so.2.1.0    [.] 0x00000000001d1dc4
+    0.06%     0.06%  [kernel]            [k] pipe_poll
+    0.04%     0.04%  libruby.so.2.1.0    [.] 0x00000000001d1dd4
+    0.04%     0.04%  [kernel]            [k] select_estimate_accuracy
+    0.02%     0.02%  [kernel]            [k] schedule
+    0.01%     0.01%  [kernel]            [k] finish_task_switch
+    0.00%     0.00%  [kernel]            [k] hrtimer_try_to_cancel
Failed to open /lib/x86_64-linux-gnu/libpthread-2.19.so, continuing without symbols
```

I'm continuing to brainstorm other approaches to getting info, but if folks have suggestions then I should be able to iterate on them very quickly now!

**Comment by a-robinson** [comment]
@vishh @dchen1107 @igorpeshansky as a few folks who may have better ideas than me on how to suck more info out of this stuck process

**Comment by nurse** [comment]
`ps` shows there's 14 pthreads but all of them are sleeping.
To see what are those pthreads, could you run https://gist.github.com/nurse/0619b6af90df140508c2?

Before run above script, you should install libruby-dbg package through apt-get.
With this you can get the symbol of functions. (you can also get symbols of libruby on running `perf top`)

**Comment by repeatedly** [comment]
I remembered one user hits hanging problem with inotify inside in_tail.
We used above nurse's script to detect which function/plugin has a problem.
We want to know the result of above script.

**Comment by pseudobeer** [comment]
fluentd-0.12.26 on Google Compute Engine instance running CentOS Linux release 7.2.1511. Gets stuck with a deadlock. Can only be terminated with SIGALRM.

Process hierarchy looks like this
```
[Parent] -----------------
                |       |
            [Child0] [Child1]---------------------...------
                                 |          |             |
                            [Child1-0] [Child1-1] ... [Child1-x]
```


Config is below:
```
<source>
  type tail
  path /home/user/logfile.log
  tag log.type
  format /some regex/
  read_from_head true
  pos_file /var/log/td-agent/logfile.pos
</source>
```

File at path is not a symlink. We pass input from in_tail through record_reformer, forest and finally upload it to BigQuery.

strace on the [Child1] generates following output continuously:
```
futex(0x7faa4c82d644, FUTEX_WAKE_OP_PRIVATE, 1, 1, 0x7faa4c82d640, {FUTEX_OP_SET, 0, FUTEX_OP_CMP_GT, 1}) = 1
futex(0x7faa4c82d610, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x7faa4c82d678, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x7faa4c82d67c, FUTEX_WAIT_PRIVATE, 451, NULL) = -1 EAGAIN (Resource temporarily unavailable)
futex(0x7faa4c82d610, FUTEX_WAKE_PRIVATE, 1) = 0
sched_yield()                           = 0
futex(0x7faa4c82d644, FUTEX_WAKE_OP_PRIVATE, 1, 1, 0x7faa4c82d640, {FUTEX_OP_SET, 0, FUTEX_OP_CMP_GT, 1}) = 1
futex(0x7faa4c82d610, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x7faa4c82d678, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x7faa4c82d67c, FUTEX_WAIT_PRIVATE, 453, NULL) = -1 EAGAIN (Resource temporarily unavailable)
futex(0x7faa4c82d610, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x7faa4c82d644, FUTEX_WAKE_OP_PRIVATE, 1, 1, 0x7faa4c82d640, {FUTEX_OP_SET, 0, FUTEX_OP_CMP_GT, 1}) = 1
futex(0x7faa4c82d610, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x7faa4c82d678, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x7faa4c82d67c, FUTEX_WAIT_PRIVATE, 455, NULL) = -1 EAGAIN (Resource temporarily unavailable)
write(6, "!", 1)        
```

And here is the above mentioned pid2file on [Child1]: 
```
# /opt/td-agent/embedded/bin/ruby pid2line.rb 11010
LWPID: 11010 EIP: 7faa4e58a462 -> 142462
Elf vaddr: 142462 -> 142462
match_at
/var/cache/omnibus/src/ruby/ruby-2.1.10/regexec.c:2627
LWPID: 11011 EIP: 7faa4d81969d -> ec69d
Elf vaddr: ec69d -> ec69d
__poll_nocancel
:?
LWPID: 11014 EIP: 7faa4e237a82 -> ba82
Elf vaddr: ba82 -> ba82
__pthread_cond_timedwait
:?
LWPID: 11015 EIP: 7faa4e237a82 -> ba82
Elf vaddr: ba82 -> ba82
__pthread_cond_timedwait
:?
LWPID: 11021 EIP: 7faa4d8242c3 -> f72c3
Elf vaddr: f72c3 -> f72c3
__epoll_wait_nocancel
:?
LWPID: 11022 EIP: 7faa4d8242c3 -> f72c3
Elf vaddr: f72c3 -> f72c3
__epoll_wait_nocancel
:?
LWPID: 11023 EIP: 7faa4d81975f -> ec75f
Elf vaddr: ec75f -> ec75f
__GI_ppoll
:?
```

Stuck state was seen on both live logs and batch log uploads (>40 GB stream). All data was processed successfully, but CPU load was about 25% at all times on 4 core system. htop shows that  [Child1] loads a single core to 100%. buffer_type is filecache.

**Comment by nurse** [comment]
@pseudobeer 
strace result is timer thread's one; it's normal behavior.

pid2line's result shows the main thread is running in regular expression engine.
Maybe your configuration's `/some regex/` hits a [backtrack explosion](https://swtch.com/~rsc/regexp/regexp1.html).

**Comment by pseudobeer** [comment]
@nurse 

That was a backtrack explosion indeed. Fixing helped, thanks for a useful link.

**Comment by tagomoris** [comment]
This problem looks already be solved.
