### ISSUE TITLE
[Feature request]Be able to override plugins for development

### ISSUE THREAD

**Issue by perrin4869** [fluent/fluentd#1022]
During development, I want to be able to run `td-agent` manually on a custom path with plugins. These plugins are the same as those found in `/etc/td-agent/plugin`, which get loaded automatically. Unfortunately, if I run `td-agent` with the `-p` flag on the development plugins directory, the plugins get loaded twice and `td-agent` fails to load with the following error:

```
2016-06-03 16:00:16 +0900 [error]: fluent/supervisor.rb:368:rescue in main_process: unexpected error error="Fluent::TextFormatter::TimestampedLTSV: default value specified twice for delimiter"
```

Is there a way to tell `td-agent` not to load `/etc/td-agent/plugin` or, better yet, if 2 plugins have the same filename, to have the plugin in `/etc/` be overriden?

I'm running `td-agent 0.12.20`.
Thanks!

**Comment by repeatedly** [comment]
AFAIK, It has been already resolved since v0.14.0.
In v0.12, fluentd loads all `*.rb` plugins under specified directory during startup.
In v0.14, fluentd adds specified directory to search path and pick first one during startup.

**Comment by perrin4869** [comment]
I see! Will try 0.14 soon then, thanks!

**Comment by repeatedly** [comment]
v0.14.0 has some known issues, several issues are fixed at master.
Please check it carefully on your environment!

**Comment by perrin4869** [comment]
got it! btw, latest `td-agent` still comes with `0.12`. `td-agent` with fluentd `0.14` will be released once those issues are solved? Is it still possible to try new `fluentd` with the latest `td-agent`?

**Comment by repeatedly** [comment]
td-agent 3 will use fluentd v0.14: https://github.com/treasure-data/omnibus-td-agent/issues/80
td-agent 2 continue to use fluentd v0.12 versions.
User can use fluentd v0.14.0 by `/usr/sbin/td-agent-gem update fluentd` but we don't recommend it on production for now.
