### ISSUE TITLE
Millisecond precision on fluentd 0.14

### ISSUE THREAD

**Issue by Alars-ALIT** [fluent/fluentd#1024]
How do you enable millisecond precision on timestamps in version 0.14?

Running with this conf:

```aconf
<source>
    @type exec
    command "echo \"test\""
    keys k1
    tag_key "k1"
    run_interval 2s
  </source>
  <match **>
    @type stdout
  </match>
```

..generates this output:
2016-06-03 09:36:48 +0000 test: {}
..

**Comment by repeatedly** [comment]
v0.14 has already used nanosecond precision time.

> 2016-06-03 09:36:48 +0000 test: {}

Ruby's localtime method generates this format: http://ruby-doc.org/core-2.2.0/Time.html#method-i-localtime
