### ISSUE TITLE
@type file secondary output

### ISSUE THREAD

**Issue by Psyered** [fluent/fluentd#1036]
- fluentd or td-agent version. - 2.3.1-0.el7
- Environment information, e.g. - OS. Centos 7
- Your configuration:

```
buffer_chunk_limit 16m
        buffer_type file
        buffer_path /var/fluentd/buffer/*.buffer
        retry_limit 12
        max_retry_wait 10s
        <secondary>
            @type file
            path /var/fluentd/forward-failed/forward-failed
            time_slice_format %Y%m%d
            time_slice_wait 10m
            time_format %Y%m%dT%H%M%S%z
            compress gzip
        </secondary>
```

- Your problem explanation. If you have an error logs, write it together.

How can I flush / send secondary `@type file` logs to td-agent?

**Comment by repeatedly** [comment]
If you hit retry_limit in the primary, events are flushed to `<seconday>` immidiately.

**Comment by Psyered** [comment]
Hi, repeatedly
This is correct. My question is - How can I flush / send `@type file` stored data to `td-agent` socket or other source?

**Comment by repeatedly** [comment]
It depends on your environment.
Write simple script which reads stored data and forward it to fluentd is better.

**Comment by Psyered** [comment]
Example please. I cant understand it.
Which utilities should I use to send stored data to unix socket?

**Comment by repeatedly** [comment]
This is one example with TCP based `in_forward`: https://groups.google.com/forum/#!searchin/fluentd/FluentLogger$20secondary/fluentd/I4rDp2kwGZA/1LzEmyPvhokJ

fluent-logger-ruby doesn't support unix domain socket,
so using unix domain socket supported cilent, e.g. fluent-logger-php, or follow this protocol with your script: http://docs.fluentd.org/articles/in_forward#protocol
Of course, adding in_forward to yoru conf is another approach.

In addition, secondary content depends on primary plugin.
If primary is `out_forward`, content is msgpack.
If primary is `out_s3`, content depdends on `format` parameter.

**Comment by tagomoris** [comment]
Are there still problems? If so, please reopen this issue.
