### ISSUE TITLE
Problem log multipleline with docker-log-driver = fluentd

### ISSUE THREAD

**Issue by selfieblue** [fluent/fluentd#1037]
Hi, Fluentders
I am building logging solution for docker and I wanna use docker log-driver option but I stuck on log multiple lines and I cannot found any solution for this issue so I would like to get the suggestion or any workaround solution and eventually, I hope fluentder will be launch new fix this problem as soon as possible.

Best Reagrds,
Jesada

**Comment by okkez** [comment]
I've created filter plugin for this issue.

https://github.com/okkez/fluent-plugin-concat/

**Comment by repeatedly** [comment]
Follow this official guide: http://www.fluentd.org/guides/recipes/docker-logging

**Comment by repeatedly** [comment]
Closed. If you have hit a problem with concat plugin, please report it on fluent-plugin-concat repository.
