### ISSUE TITLE
router.emit instead of Engine.emit

### ISSUE THREAD

**Issue by Raznak** [fluent/fluentd#1041]
Hi,

I'm running fluentd v0.14.0 under FreeBSD
There is my configuration file:

```
<source>
  @type tail
  format multiline
  format_firstline /^--[a-fA-F0-9]{8}-A--$/
  format1 /(?<message>.*)/
  path /var/log/Vulture/worker/vulture-app111.bonsoir.com--security.log
  pos_file /var/log/fluentd/5756d081b9a6d0083c936fd7.pos
  tag apache.rawmodsec.5756d081b9a6d0083c936fd7
</source>

<match apache.rawmodsec.5756d081b9a6d0083c936fd7>
  type modsecurity-audit-format
  tag apache.security.5756d081b9a6d0083c936fd7.raw
</match>

<match apache.security.5756d081b9a6d0083c936fd7.*>
  @type elasticsearch
  hosts http://10.0.0.79:9200
  type_name sec
  logstash_format true
  logstash_prefix sec
  logstash_dateformat %Y.%m.%d
  time_key event_timestamp
  buffer_type memory
  buffer_chunk_limit 128m
  buffer_queue_limit 32
  retry_wait 1s
</match>
```

When a log came in the log file fluent show this warning:
`2016-06-07 17:13:00 +0200 [warn]: emit transaction failed: error_class=RuntimeError error="BUG: use router.emit instead of Engine.emit" tag="apache.rawmodsec.5756d081b9a6d0083c936fd7"`

The issue is the same when I forward the log to mongoDB.

**Comment by repeatedly** [comment]
Because `modsecurity-audit-format` plugin uses old API.
In v0.12 and v0.14, plugin should use `router.emit`, not `Engine.emit`.

**Comment by repeatedly** [comment]
See official announce: http://www.fluentd.org/blog/fluentd-v0.14.0-has-been-released

**Comment by Raznak** [comment]
Thanx.

When I change Engine.emit to router.emit, the module can't find router.....
There is a doc for writing plugin with Fluentd v0.14 ?
