### ISSUE TITLE
_key is listed as fluentd.warn

### ISSUE THREAD

**Issue by maverick-racheal** [fluent/fluentd#1070]
We are facing an issue where in if the fluentd docker container comes up before the elk, all the K8 logs have the key as fluentd.warn. This issue is seen even after i restart the docker container of fluentd.

 However in case if the fluentd docker container is brought up after the elk the key is set to the log file name. The following is the tdagent.conf

```
<source>
  type tail
  format multiline
  format_firstline /^\w\d{4}/
  format1 /^(?<severity>\w)(?<time>\d{4} [^\s]*)\s+(?<pid>\d+)\s+(?<source>[^ \]]+)\] (?<message>.*)/
  time_format %m%d %H:%M:%S.%N
  path /varlog/*controller*.log
  pos_file /var/log/es-kube-controller-manager.log.pos
  tag kube-controller-manager
</source>

<source>
  type tail
  format multiline
  format_firstline /^\w\d{4}/
  format1 /^(?<severity>\w)(?<time>\d{4} [^\s]*)\s+(?<pid>\d+)\s+(?<source>[^ \]]+)\] (?<message>.*)/
  time_format %m%d %H:%M:%S.%N
  path /varlog/*apiserver*.log
  pos_file /var/log/es-kube-apiserver.log.pos
  tag kube-apiserver
</source>

<source>
  type tail
  format multiline
  format_firstline /^\w\d{4}/
  format1 /^(?<severity>\w)(?<time>\d{4} [^\s]*)\s+(?<pid>\d+)\s+(?<source>[^ \]]+)\] (?<message>.*)/
  time_format %m%d %H:%M:%S.%N
  path /varlog/*scheduler*.log
  pos_file /var/log/es-kube-scheduler.log.pos
  tag kube-scheduler
</source>
<filter kubernetes.**>
  type kubernetes_metadata
</filter>

<match **>
   type elasticsearch
   log_level info
   include_tag_key true
   tag_key _key
   host elk
   port 9200
   logstash_format true
   # Set the chunk limit the same as for fluentd-gcp.
   buffer_chunk_limit 2M
   # Cap buffer memory usage to 2MiB/chunk * 32 chunks = 64 MiB
   buffer_queue_limit 32
   flush_interval 5s
   # Never wait longer than 5 minutes between retries.
   max_retry_wait 30
   # Disable the limit on the number of retries (retry forever).
   disable_retry_limit
</match>
```

Appreciate any help/workaround.

**Comment by repeatedly** [comment]
Could you show me the log message?

**Comment by maverick-racheal** [comment]
[fluentd.txt](https://github.com/fluent/fluentd/files/341203/fluentd.txt)
Attaching the logs

**Comment by repeatedly** [comment]
Where is `_key` related warn?

**Comment by maverick-racheal** [comment]
It was seen in Kibana. I dismantled my setup, shall bring it up and update.

**Comment by repeatedly** [comment]
> It was seen in Kibana.

Ah, I see.
You use `**` in match and it is why your es has `fluent.warn`.
Check this article: http://docs.fluentd.org/articles/logging#capture-fluentd-logs

**Comment by tagomoris** [comment]
It's better to use `@label ...` in all `<source>` sections, and `<label>` section to handle events from input plugins excluding events from Fluentd internal logs.
http://docs.fluentd.org/articles/config-file#5-group-filter-and-output-the-ldquolabelrdquo-directive
