### ISSUE TITLE
charset issue

### ISSUE THREAD

**Issue by plorent** [fluent/fluentd#1120]
When following http://docs.fluentd.org/articles/windows I get the following output:

`2016-07-20 11:59:44 +0000 windowslog: {"message":"W\u0000i\u0000n\u0000d\u0000o\u0000w\u0000s\u0000\r"}`

Any pointers on how to resolve this?

I'm running fluentd-0.12.26

**Comment by tagomoris** [comment]
I think that the encoding of your text file is UTF-16LE, and nxlog sends it as is.
Fluentd handles chars in UTF-8, so it shows like that.
Check your nxlog configuration (I found this page after googling): http://nxlog-ce.sourceforge.net/nxlog-docs/en/nxlog-reference-manual.html#xm_charconv_example
