### ISSUE TITLE
Subsecond time-stamp in docker logger driver for stderr

### ISSUE THREAD

**Issue by YerisAntonio** [fluent/fluentd#1121]
Hi all!

I am trying to log node.js apps erros in docker using the fluentd driver, all logs are sent to elasticsearch for kibana visualization.

I am using the latest td-agent but i also updated fluentd to latest with

sudo td-agent-gem install fluentd

What I looking to achieve here is to have subsecond time stamp so all stderr lines are at least ordered, however my logs still have the triple sero aftert minutes like this: July 19th 2016, 15:43:39.000

I use  time_key @timestamp and time_key_format %Y-%m-%dT%H:%M:%S.%N%z options in the conf file, but no luck. 

Is there a new configuration option added to 0.14.1 to enable the milisecond time stamp or is there more requirements to this, that I may be overlooking?

Kind regards

**Comment by YerisAntonio** [comment]
This is an example of stderr from the docker logging driver.

{
  "_index": "logstash-2016.07.20",
  "_type": "fluentd",
  "_id": "AVYIoWBjIqB9UlPi5fHu",
  "_score": null,
  "_source": {
    "container_name": "/thirsty_newton",
    "source": "stderr",
    "log": "ReferenceError: serviceName is not defined",
    "container_id": "119b2d9dae57a7492d8b7898ab7dff1af015c682bb6adf39765b0bf9e4fe000b",
    "@timestamp": "2016-07-20T08:06:40-06:00"
  },
  "fields": {
    "@timestamp": [
      1469023600000
    ]
  },
  "sort": [
    1469023600000
  ]
}

**Comment by tagomoris** [comment]
Currently, fluent-logger-golang (Docker logging driver based on it) doesn't support sub-second time. We need to make updates on it to support sub-second with Fluentd v0.14.

**Comment by tagomoris** [comment]
Anyway, it's not an issue of Fluentd itself. Please open another issue for fluent-logger-golang.

**Comment by YerisAntonio** [comment]
Hi tagomoris! You sure about it?, My stdout comes with sub second precisions the problem are the stderr messages that get the fluentd "On arrival time" timestamp.

I already opened the issue on the fluent-logger-golang project website, but as I say it looks to me like a fleuntd on arrival timestamp issue thing.

Kind regards

**Comment by tagomoris** [comment]
I'm sure about it, because i'm an author of docker logging driver of fluentd...

**Comment by nsaud01** [comment]
So the fluentd logging driver is at v0.12? Are there any updates on this?

**Comment by nsaud01** [comment]
@YerisAntonio Do you have a link to your fluent-logger-golang thread? Thanks!
