### ISSUE TITLE
syslog input has hardcoded max size at 2048 bytes

### ISSUE THREAD

**Issue by hjdr4** [fluent/fluentd#1123]
Message size may be up to 65K

Some of my Apache access logs were truncated because of this.

**Comment by MKo-xx** [comment]
I just came to this bug and wanted to open an issue :).
My Nginx logs also were truncated because of the line 184:
`SocketUtil::UdpHandler.new(@usock, log, 2048, callback)`
in the file **in_syslog.rb**

**Comment by repeatedly** [comment]
Released v0.12.27 including this fix.
