### ISSUE TITLE
Provide mechanism to acknowledge matching and handling of events to source

### ISSUE THREAD

**Issue by warmfusion** [fluent/fluentd#1125]
Scenario;

I am using the fluent-plugin-amqp to consume ~2k events a second off a rabbitmq broker into a multi-server elasticsearch cluster using the fluent-plugin-forest and fluent-plugin-elasticsearch

Problem;

In the event of an ElasticSearch failure - invalid message, cluster offline, node failure etc, the matcher is unable to reject the incoming message from RabbitMQ for retry; All messages need to be 'no-ack'd' which results in lost events.

Desire;

During the `router.emit` phase, a block, or some other callback is provided which is called in such a way that it can be determined if a given event has been matched, and handled successfully (with exception/message if not)

This would then allow me to implement a proper ack/nack interaction on the rabbitmq brokers, retrying on connection failures, or throwing to a 'invalid-syntax' queue badly formed messages as appropriate.

It'd also support monitoring as the RMQ queues will not be consumed as easily, with a spike in retries.

**Comment by repeatedly** [comment]
>  a block

You can use `buffer_queue_full_action block` in `<match>`.

**Comment by warmfusion** [comment]
Thats not the same thing;

I'm not saying the queues are full, i'm saying that some or all are failing and being thrown away - the buffers are empty as they're effectivly going into /dev/null

Theres no per-event feedback loop, preventing input sources from being able to make any guarantees on data safety.

**Comment by repeatedly** [comment]
> i'm saying that some or all are failing and being thrown away 

You mean you don't want to use buffer?

**Comment by repeatedly** [comment]
From your comment, fluentd's buffer methanizm doesn't fit your case.

**Comment by repeatedly** [comment]
In v0.14, we can select buffered/non-buffered by configuration.
So you can handle output error immidiately when elasticsearch has a problem.
But I'm not sure this fits your case.

**Comment by warmfusion** [comment]
Perhaps this might make things more clear;

```
        +----------+                       +---------+ +------4---->
+-1---> | ActiveMQ |                       | Output  | |----5-----X
        | Source   |                       | Matcher | +--------6--?
        +----+-----+                       +-----+---+
             |                                   ^
             2      +--------------------+       3
             |      |                    |       |
             +----> |   Fluent Internal  | +-----+
                    |   Black box        |
                    |                    |
                    +--------------------+
```

## Situation

1. Event arrives from RabbitMQ into the ActiveMQ Plugin
2. Event is sent into the Fluent Black Box through the use of `router.emit`
3. Fluent filters, matches and sends the event into the ElasticSearch Output Matcher

4. Event is sent sucessfully - Nothing needed
5. Event is rejected by the service used by the output
    * Database insert failure
    * Filesystem is full
    * Connection refused
6. Event is lost
    * Message sent to system, but no acknowledgement received

## Desire

In the case of 4,5,6 i'd like the source to be able to respond back at (1) indicating that the event was not only received, but also handled properly.

This doesn't make sense when reading off disk, or accepting async messages from say syslog, but could be used as a response mechanism for blocking event writes over HTTP, for sending ACK to brokers, or for simply managing flow control.

Does this help?

**Comment by repeatedly** [comment]
For 5, we provide secondary or error label to rescue destination related error.
So if you configure output plugin properly, data should not be lost.

Fluentd's data flow model is now push with robust buffering, not pull.
So if you want to use pull model with ack, fluentd is not the best.
We have a plan to add back-preasure like flow control,
but It seems not  provide end-to-end ack model.

**Comment by warmfusion** [comment]
I can understand the focus on the push model - I certainly recognise there are more use cases for that behaviour in a logging system like this.

Given this, I think I'll have to implement my own middleware between my incoming event stream and the ElasticSearch storage backend to ensure data consistency and error handling at the per-event level. 

I could abuse the error label and reemit events back into the rabbitmq queues for re-consumption, perhaps setting my own TTL headers and the like, but I think it makes more sense to use the built in (n)ack protocol messages.

**Comment by tagomoris** [comment]
Fluentd v0.14 provides APIs for output plugins which can work as both of buffered and non-buffered.
And with non-buffered output plugin, input plugin can wait the output plugins' process.
1. input plugin creates event streams (from input data from anywhere else)
2. input plugin emits event streams into Engine
3. Engine calls output plugin's `#process` method (in non-buffered mode)

In this model, input plugin can rescue any errors from output plugins, and can handle these errors in their own way.

But this use cases are far different from Fluentd's main purpose, so I think we cannot accept such request for now.
