### ISSUE TITLE
Add a feature to clean up position informations on in_tail 

### ISSUE THREAD

**Issue by thkoch2001** [fluent/fluentd#1126]
- fluentd version: 0.12.20 - commit aee8086e9fc
- environment: fluentd pods running on Google Container Engine / kubernetes

Google Container Engine uses fluentd pods to collect container log files via the in_tail plugin and forward the logs to Stackdriver logging.

When a container is deleted, kubernetes also deletes the containers log file and there will never be a log file at this filesystem path again.

However the position file will never clean up the obsolete line in the position file although the position value is ffffffffffffffff.

We see production clusters with position files of over 10000 lines.

Can this cause performance problems with fluentd? Should this be fixed?

The config stanza for the containers log files is:

```
<source>
  type tail
  format json
  time_key time
  path /var/log/containers/*.log
  pos_file /var/log/gcp-containers.log.pos
  time_format %Y-%m-%dT%H:%M:%S.%NZ
  tag reform.*
  read_from_head true
</source>
```

**Comment by repeatedly** [comment]
in_tail removes untracked file positions at start phase.
So if you restart fluentd, pos_file is updated.

> Can this cause performance problems with fluentd?

I'm not sure. I didn't receive any report of pos_file releated performance issue.

**Comment by tagomoris** [comment]
The file which grows infinitely sound terrible in production environment (even if that growing speed is slow, or if there are no reports about performance regression).
I think we should add any features to clean it up to tail plugin.

But currently, we have a plan to switch to use storage plugin from pos file for that purpose.
I think we can add this cleanup feature at the same time with switching storage plugins.

**Comment by repeatedly** [comment]
I added note for this issue on http://docs.fluentd.org/articles/in_tail.

**Comment by piosz** [comment]
cc @Crassirostris

**Comment by mrkstate** [comment]
How do we get this feature (defect) fixed?   This is creating a situation for us - as the POS file is growing rather quickly and the process has to continue to comb thru this file.  We see constant CPU cycles even after no additional data has been written to the tailed log.

**Comment by roffe** [comment]
@mrkstate Run a cron that kills fluentd every 30 minutes https://github.com/roffe/kube-gelf/blob/master/cron.yaml

**Comment by Krishna1408** [comment]
hi @roffe  If i kiil fluentd won't it create problem for logging ? e.g. fluentd was down for 2 minutes so in that case won't I loose the log data for those 2 minutes ?

**Comment by roffe** [comment]
@Krishna1408 no, since the position file will let it know where to pickup from last time

**Comment by TiagoJMartins** [comment]
Is restarting fluentd still the only solution to this? I've just confirmed it's still happening and would be nice to know if a fix is underway or if I can try and tackle the issue.

**Comment by ganmacs** [comment]
This feature will be released in the next version. https://github.com/fluent/fluentd/pull/2805

**Comment by juliantaylor** [comment]
we see position file corruption with the compaction enabled, see https://github.com/fluent/fluentd/issues/2918
