### ISSUE TITLE
Add size to tell the number of events in a message

### ISSUE THREAD

**Issue by ganmacs** [fluent/fluentd#1135]
To tell the number of events, add `size` key to `option` in forward protocol.

I think it'll work by adding below task.
* add `size` key to `option` at `ForwardOutput#send_data` 
* pass the size value to constructor's argument of `EventStream` at `ForwardInput#on_message`

ref https://github.com/fluent/fluentd/wiki/Forward-Protocol-Specification-v0

**Comment by tagomoris** [comment]
You mean "add `size` key to `option` at `ForwardOutput#send_data`", right?
Currently, `EventStream#initialize` doesn't have `size` argument. Will you add it?

**Comment by ganmacs** [comment]
> You mean "add size key to option at ForwardOutput#send_data", right?

Yes,  i'll fix it.


> Currently, EventStream#initialize doesn't have size argument. Will you add it?

Sorry, i was wrong.
`MessagePackEventStream` and `MultiEventStream`  require adding size argument. 
And `MessagePackEventStream` has already added `size`  argument.
So i'll add `size` argument to `MultiEventStream#initialize` like below

```rb
def initialize(time_array = [], record_array = [], size= time_arrry.size)
 ...
end
```

**Comment by tagomoris** [comment]
@ganmacs Okay, got it. Looks good to me.
