### ISSUE TITLE
Add a method to return time and record on filter plugins (instead of #format, with pipeline)

### ISSUE THREAD

**Issue by ganmacs** [fluent/fluentd#1139]
Add `filter_time_and_record` that returns `record` and `time` to `Fluent::Plugin::Filter` for plugins that updates `time`(e.g [fluent-plugin-parser](https://github.com/tagomoris/fluent-plugin-parser)).
(Existing filter plugins have `Fluent::Plugin::Filter#filter` method that returns `record` untill now.)

If you'll create a new filter plugin, you should implement either `filter` or `filter_time_and_record` method to your new filter plugin.
`filter_time_and_record` that you'll implement should return either `[time, record]` or `nil`.

**Comment by ganmacs** [comment]
@tagomoris 
I think that a method name of new filter that returns `record` and `time`is  `filter_time_and_record`.

What do you think about this method name?

**Comment by tagomoris** [comment]
That method is for plugins which updates time (like fluent-plugin-parser), right? If so, please update description to show use cases.

Naming is always big issue... I like shorter one. How about `filter_with_time`?
@repeatedly any thoughts?

**Comment by ganmacs** [comment]
> That method is for plugins which updates time (like fluent-plugin-parser), right? If so, please update description to show use cases.

thanks. updated!.

**Comment by repeatedly** [comment]
Hmm... this is hard thing.
`filter_with_time` looks like "filter records using time" but I don't have good name idea.

**Comment by tagomoris** [comment]
IMO, `filter` method has arguments of `tag`, `time` and `record`.
So I expect plugin authors to understand that `filter_with_time` means "return value includes time".

If you don't have alternatives, I'll proceed this as is.

**Comment by tagomoris** [comment]
@repeatedly https://github.com/fluent/fluentd/issues/1139#issuecomment-238142242
