### ISSUE TITLE
access nested json in fluentd using @type record_transformer 

### ISSUE THREAD

**Issue by Lavakush7** [fluent/fluentd#1148]
i have one requirement  as i want to access nested json object in fluentd.
Like in {"a":{"b":"c", "d":"e"} if i fetch ${a} then able to get a valid json {"b":"c", "d":"e"}.
i want to access b , i tried ${record["a"]["b"]} , ${a.b} but nothing seems to be working .
please help.

Thanks
Lavakush

**Comment by repeatedly** [comment]
Closed via https://github.com/fluent/fluentd/issues/1146#issuecomment-237874341
