### ISSUE TITLE
out_file plugin adds <parse> section to config then complains about it

### ISSUE THREAD

**Issue by macdjord** [fluent/fluentd#1157]
I have the following file output defined in my td-agent.conf:

    <store>
    	@type file
    
    	path /var/log/td-agent/docker-containers
    	time_slice_format %Y%m%d
    	time_slice_wait 10m
    	time_format %Y%m%d@%H%M%S%z
    	utc
    
    	compress gzip
    </store>

After parsing, this becomes in the log file:

    <store>
      @type "file"
      path "/var/log/td-agent/docker-containers"
      time_slice_format "%Y%m%d"
      time_slice_wait 10m
      time_format "%Y%m%d@%H%M%S%z"
      utc
      compress gzip
      buffer_path /var/log/td-agent/docker-containers.*
      localtime false
      <buffer time>
        flush_mode lazy
        retry_type exponential_backoff
        path /var/log/td-agent/docker-containers.*
        timekey_wait 10m
        timekey 86400
      </buffer>
      <parse>
        time_format %Y%m%d@%H%M%S%z
      </parse>
      <inject>
        time_format %Y%m%d@%H%M%S%z
        localtime false
      </inject>
    </store>

Shortly thereafter in the log, I get the following message:

    2016-08-10 17:50:17 -0400 [warn]: section <parse> is not used in <store> of out_file plugin

However, if you check, I never _defined_ a `<parse>` section. It was added for me, as a default value of some sort. Why in the world is it complaining about a thing _it added_? Or rather, why in the world is a section being added as a default when it is not used?

**Comment by macdjord** [comment]
Problem went away once I downgraded `gem 'fluentd' version '0.14.2'` to `gem 'fluentd' version '0.12.26'`.

**Comment by okkez** [comment]
`out_file` cannot accept sub sections, yet.
I'm working for issue on #1159

**Comment by tagomoris** [comment]
Fluentd v0.14 does convert configurations in v0.12 style (without `<parse>` section) into v0.14 style (with `<parse>` section) to make it compatible with both of v0.12 API plugins and v0.14 API plugins.
Currently (in v0.14.2), `tail` plugin works on v0.12 API. So the log you've shown is correct (I understand it's a bit confusing).
