### ISSUE TITLE
Support a data compression in buffer plugins

### ISSUE THREAD

**Issue by ganmacs** [fluent/fluentd#1169]
Buffer plugins maintain data as raw `String` object.
This way consumes many memory resource and bandwidth of the network.
To reduce this wasteful consumption, I propose that support a data compression in buffer plugins.

### Tasks

* Add `compress true` in buffer plugin configuration.
* Compress a `chunk` by using zlib in `concat`
* Decompress a `chunk` in `write_to`

**Comment by tagomoris** [comment]
It looks better to do decompression in `#open` with optional argument not to do it forcedly (to get compressed binary for any purpose, including compressed data transferring over network).
But let me see how your implementation goes.

**Comment by ganmacs** [comment]
I think implementing decompression code in `#open` doesn't work well in  `MemoryChunk` class.
Becuase `MemoryChunk ` class overrides `#write_to` to avoid calling `#open` for optimization. 
What do you think?

https://github.com/fluent/fluentd/blob/master/lib/fluent/plugin/buffer/memory_chunk.rb#L84

**Comment by tagomoris** [comment]
#1172 and #1179 are pushed as pull-requests to solve this issue.
