### ISSUE TITLE
How to rename fluentd key name besides using plugin?

### ISSUE THREAD

**Issue by harryge00** [fluent/fluentd#1175]
How to rename "message" to "log" ?
```
{"message":"some value", "tag":"abc","@timestamp":"2016-08-20T09:38:49+00:00"}
```

**Comment by repeatedly** [comment]
If you have a question, please use mailing list, not issue.
See the guide: https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md#got-a-question-or-problem
