### ISSUE TITLE
in_tail doesn't tail log file upon log rotation

### ISSUE THREAD

**Issue by stankud** [fluent/fluentd#1182]
fluentd version:  0.12
environment: Ubuntu AWS EC2 instance

configuration:
\<source>
  type tail
  format json
  time_format %Y-%m-%dT%H:%M:%S.%L%Z
  path /path/to/log/file,
  pos_file /path/to/pos/file
  read_from_head true
  tag desktop-site
\</source>

Upon log rotation in_tail does not tail the new log correctly. Removing the pos file and restarted fluentd agent fixes the issue.

@igorpeshansky

**Comment by repeatedly** [comment]
Could you show me the content of pos_file?
in_tail is widely used and it works well with log rotation like logrotate.
So I want to know what the cause is the problem.

**Comment by stankud** [comment]
@repeatedly 

/var/log/upstart/desktop-site.log	00000000000876fa	0000000000001eec

**Comment by stankud** [comment]
@repeatedly it looks like upstart tasks are rotated with logrotate. How does the pos file get reset? Maybe this is not happening because I'm using a custom directive?

**Comment by repeatedly** [comment]
> /var/log/upstart/desktop-site.log 00000000000876fa 0000000000001eec
> /var/log/upstart/desktop-site.log 00000000000885a5 0000000000001eec

`0000000000001eec` is inode. Is 2nd line after log rotated content?

> How does the pos file get reset? 

Currently, removing pos_file is needed if you want to reset the content.
Does your fluentd log contain "detected rotation" like message?

**Comment by stankud** [comment]
@repeatedly 
Yes, "detected rotation" message is there.

I think I may have figure out the source of this issue. This has to do with the default logrotation config for upstart on ec2: /etc/logrotate.d/upstart

The config is as follows:

/var/log/upstart/*.log {
        daily
        missingok
        rotate 7
        nocreate
        compress
        notifempty
}

Removing the nocreate option fixes the problem. I'm guessing not having the logfile available during rotation breaks something.

**Comment by repeatedly** [comment]
I see. I checked logrotate document and this document says "New  log  files  are  not  created" when `nocreate` is specified: http://www.linuxcommand.org/man_pages/logrotate8.html
I'm not sure when `nocreate` option is useful...

**Comment by tagomoris** [comment]
`nocreate` is used for the cases with no log lines between rotations, not to create empty files.

**Comment by repeatedly** [comment]
So `nocreate` is not fit for typical application logs?

**Comment by tagomoris** [comment]
Yes.

**Comment by repeatedly** [comment]
Thanks for the information. I will add this `nocreate` case to in_tail article.
