### ISSUE TITLE
Add v0.14.latest to docker hub

### ISSUE THREAD

**Issue by dimaqq** [fluent/fluentd#1216]
Right now, docker hub has 0.14.1 and 0.14.2:

https://hub.docker.com/r/fluent/fluentd/tags/

It would help a lot to have 0.14.latest and/or 0.14.6 (latest released)

**Comment by repeatedly** [comment]
Please open docker image related issue on fluentd-docker-image repository.

**Comment by dimaqq** [comment]
Done, thanks :)
