### ISSUE TITLE
Clarify EventTime msgpack extension

### ISSUE THREAD

**Issue by dimaqq** [fluent/fluentd#1221]
msgpack has 2 extension mechanisms:
* fixext for fixed length extension data where `len(data) in (1,2,4,8,16)`, and
* ext for variable length extensions

Wiki (https://github.com/fluent/fluentd/wiki/Forward-Protocol-Specification-v1#eventtime-ext-format) specifies extension starting byte `C7`, however:

example seems wrong: variable-length extensions need a size byte, thus message would be `c7 08 00 <8 bytes data>` (notice extra `08` byte after `c7`).

payload is 8 bytes, thus `msgpack` uses fixext format, and thus message becomes `d7 00 <8 bytes data>` (notice `d7` instead of `c7`).

Python sample:
```
In [21]: binascii.b2a_hex(msgpack.packb(msgpack.ExtType(code=0,  data=b'w'*8)))
Out[21]: b'd7007777777777777777'
```

References:
https://github.com/msgpack/msgpack/blob/master/spec.md#ext-format-family

**Comment by tagomoris** [comment]
I see what you mean. It's mistake of documentation.
IMO EventTime can be represented by `fixext8`(d7), or `ext8`(c8) (or larger).
There's no matter whether `d7` or `c8` is used.
I'll fix it later.

**Comment by tagomoris** [comment]
I updated the spec.
Diff: https://github.com/fluent/fluentd/wiki/Forward-Protocol-Specification-v1/_compare/d201bfe951d240e92b27705dc8d1af071bad0a39...0bac7c47d3852e45f3ec93c4b3a03cb96c9392f2

Thank you to let me know about it!

**Comment by dimaqq** [comment]
I think it's `c7 08 00` (tag, length, type code) per https://github.com/msgpack/msgpack/blob/master/spec.md#ext-format-family

**Comment by tagomoris** [comment]
Oops, you're right...

**Comment by tagomoris** [comment]
Done :P
