### ISSUE TITLE
monitor_agent does strange output in v0.14

### ISSUE THREAD

**Issue by kazegusuri** [fluent/fluentd#1226]
monitor_agent's ouput in v0.14 is weird and different from in v0.12. With folloing configuration:

```
<source>
  @type monitor_agent
</source>

<match nginx>
  @type copy
  <store>
    @type stdout
  </store>
</match>

<match nginx2>
  @type stdout
</match>
```

in v0.12.29

```
$ curl http://localhost:24220/api/plugins
plugin_id:object:3fe8b81d9c10	plugin_category:input	type:monitor_agent	output_plugin:false	retry_count:
plugin_id:object:3fe8b857d768	plugin_category:output	type:copy	output_plugin:true	retry_count:
plugin_id:object:3fe8b857c46c	plugin_category:output	type:stdout	output_plugin:true	retry_count:
plugin_id:object:3fe8b81f4038	plugin_category:output	type:stdout	output_plugin:true	retry_count:
```

in v0.14.6

```
$ curl http://localhost:24220/api/plugins
plugin_id:object:3fa09f9fad74	plugin_category:input	type:monitor_agent	output_plugin:false	retry_count:
plugin_id:object:3fa09f53ae4c	plugin_category:unknown	type:copy	output_plugin:false	retry_count:0
plugin_id:object:3fa09f4ed32c	plugin_category:output	type:stdout	output_plugin:true	buffer_total_queued_size:0	retry_count:0
plugin_id:object:3fa09f4ed32c	plugin_category:output	type:stdout	output_plugin:true	buffer_total_queued_size:0	retry_count:0
plugin_id:object:3fa09fa5e5e0	plugin_category:output	type:stdout	output_plugin:true	buffer_total_queued_size:0	retry_count:0
```

There seems to be 3 issues.

1. `copy` plugin is categorized as `unknown`
2. `stdout` plugin inside `copy` plugin is duplicate
3. `stdout` plugin is not buffered output plugin but displays metrics for buffered plugin such as `buffered_total_queue_size`

**Comment by tagomoris** [comment]
1. `copy` plugin is categorized as `unknown`.

It's the bug of `#plugin_category`, not to consider about `Fluent::Plugin::MultiOutput`.

**Comment by tagomoris** [comment]
* `stdout` plugin inside `copy` plugin is duplicated

It's the bug that `in_monitor_agent` plugin fetches output plugin instances from `root_agent.outputs`, and `output_instance.outputs` if output plugin is an instance of MultiOutput.
Now `root_agent.outputs` contains all output plugin instances including children of MultiOutput.

**Comment by tagomoris** [comment]
* `stdout` plugin is not buffered output plugin but displays metrics for buffered plugin such as `buffered_total_queue_size`

This bug description is not correct, because `out_stdout` can work as both of buffered and non-buffered plugin now (v0.14.5 and later).
But we can remove the buffer instance from `@buffer` when it works as non-buffered output. If we do so, we can update code of `in_monitor_agent`, and `buffer_total_queued_size` will disappear.
