### ISSUE TITLE
Oj in strict mode cannot format Symbols into json

### ISSUE THREAD

**Issue by tagomoris** [fluent/fluentd#1230]
As I noted on the comments below, setting Oj's default options in `parser_json` affects to the behavior of Oj in `format_json`.
https://github.com/fluent/fluentd/pull/1147#issuecomment-246307029

It's too strict, and a kind of bug.
We should use `compat` mode of Oj globally (need to consider about Oj's default options in both of formatter and parser).

**Comment by repeatedly** [comment]
I checked the behaviour and strict is not fit for fluentd.
I will write a patch.

```
require 'oj'

record = {'key1' => 'value1', :key2 => :value2, 'key3' => ':value3'}

p Oj.default_options[:mode]
result = Oj.dump(record)
puts result
p Oj.load(result)

Oj.default_options = {:mode => :compat}

p Oj.default_options[:mode]
result = Oj.dump(record)
puts result
p Oj.load(result)

Oj.default_options = {:mode => :strict}

p Oj.default_options[:mode]
result = Oj.dump(record)
puts result
p Oj.load(result)
```

```
:object
{"key1":"value1",":key2":":value2","key3":"\u003avalue3"}
{"key1"=>"value1", :key2=>:value2, "key3"=>":value3"}
:compat
{"key1":"value1","key2":"value2","key3":":value3"}
{"key1"=>"value1", "key2"=>"value2", "key3"=>":value3"}
:strict
oj_test.rb:20:in `dump': In :strict mode all Hash keys must be Strings, not Symbol. (TypeError)
        from oj_test.rb:20:in `<main>'
```

**Comment by repeatedly** [comment]
@tagomoris Could you give me an example configuration for checking this issue?
This is hard to write unittests so I want actual configuration.

**Comment by tagomoris** [comment]
No configuration (for plugins) are needed.
Just write tests which formats hashes including Symbol as values (should be formatted into string), and also parses JSON strings including string values with preceeding ':' (parsed into String).

**Comment by tagomoris** [comment]
See http://www.ohler.com/dev/oj_misc/encoding_format.html

**Comment by repeatedly** [comment]
> Just write tests which formats hashes including Symbol as values (should be formatted into string), and also parses JSON strings including string values with preceeding ':' (parsed into String).

Sorry, I can't understand this sentence correctly.
The problem is oj supports only global options and it causes a conflicts between parser/formatter.
In `formatter_json` tests, all tests are passed because `formatter_json` uses `compat` mode.
Adding above test doesn't test this problem.

**Comment by tagomoris** [comment]
The root cause of this problem depends on the order of files loaded. It can't be tested, because test runner loads all files just once in a test execution.
But it can be tested to confirm Oj's `default_option` is always equal to one designed, and it can parse/format json objects as expected, regardless of order of loading files.

If you want to test it strictly, spawn another process and do:

1. require json formatter
1. require json parser
1. test Oj's default options are equal to one set in formatter code

and reverse these in sight of parser.
IMO, no need to do these tests... we can't be sure about Oj's default options anytime, because 3rd party plugin can overwrite it anytime.
