### ISSUE TITLE
Enable log rotation for `Fluent::Log`

### ISSUE THREAD

**Issue by ganmacs** [fluent/fluentd#1231]
As the log file increases, it becomes difficult to handle the log file.
So, I want to enable the log rotation for `Fluent::Log` to keep log files down to a manageable size.

I'll add these command line arguments to `fluentd` command.

* `--log-rotate-age`

The number of old log files to keep, or frequency of rotation (`daily`, `weekly` or `monthly`). The default value is 5. it is used when you set a value to `--log-rotate-size` and don't set a value to `--log-rotate-age`.If you set 0 as a value of `--log-rotate-age`,  the logger will do no log rotation.

* `--log-rotate-size`

Maximum logfile size (only applies when `log-rotate-age` is a number).  The default value is 1M.
it is used when you set a value to `--log-rotate-age` and don't set a value to `--log-rotate-size`.

**Comment by tagomoris** [comment]
What happens when `--log-rotate-age` is 0?

**Comment by ganmacs** [comment]
`log-rotate-age` means "the number of old log files to keep".
When `--log-rotate-age` is 0,  old log files are not created.

**Comment by tagomoris** [comment]
@ganmacs What does it mean? Which one?:
* log file will be rotated, but old log will disappear immediately
* log file will not be rotated

**Comment by ganmacs** [comment]
> log file will not be rotated

This one.

`Fluent::Log`class uses `ServerEngine::DaemonLogger` class inside and `ServerEngine::DaemonLogger` extends Ruby's `Logger` class.
This is a design by ruby's `Logger` class( https://github.com/ruby/ruby/blob/7b2d47132ff8ee950b0f978ab772dee868d9f1b0/lib/logger.rb#L769 )

**Comment by tagomoris** [comment]
I meant that we should tell users that the default value of `--log-rotate-age=0` means "no log rotation" clearly.

**Comment by ganmacs** [comment]
I added a description about the case of `--log-rotate-age=0`.
