### ISSUE TITLE
record_transformer keep_keys option creates keys with 'nil' values for unset keys.

### ISSUE THREAD

**Issue by mr-salty** [fluent/fluentd#1240]
Check [CONTRIBUTING guideline](https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md) first and here is the list to help us investigate the problem.

I saw this on 0.12 but it looks like it still works the same way.

If you configure i.e.

```
<filter XXX>
  type record_transformer
  renew_record true
  keep_keys a,b,c
</filter>
```

Then the resulting record will always have 'a', 'b', and 'c' set, even if those keys were not present in the original record (in which case they get nil values).

instead of
`@keep_keys.each {|k| new_record[k] = record[k]} if @keep_keys and @renew_record`

should we do?
`@keep_keys.each {|k| new_record[k] = record[k] if record.has_key?(k)} if @keep_keys and @renew_record`

BTW, perhaps this should be a different issue but we also found it surprising/confusing that if you write
`keep_keys a, b, c`
those spaces get into the actual keys which are then named "a", " b", and " c".

**Comment by repeatedly** [comment]
@sonots Could you check it?

**Comment by repeatedly** [comment]
@sonots ping

**Comment by sonots** [comment]
I will take care of this later, but PR is always welcome!

> @keep_keys.each {|k| new_record[k] = record[k] if record.has_key?(k)} if @keep_keys and @renew_record

agree

> BTW, perhaps this should be a different issue but we also found it surprising/confusing that if you write `keep_keys a, b, c` those spaces get into the actual keys which are then named "a", " b", and " c".

The specification disallows to specify keys with white spaces, so I can not accept it.
We should be able to use a `array` parameter now, but it breaks compatibility, so let me keep as is.

**Comment by repeatedly** [comment]
> Another option is to use a array parameter type, but it breaks compatibility, so let me keep as is.

`array` parameter now has simplifed syntax feature: http://www.fluentd.org/blog/fluentd-v0.12.27-has-been-released

**Comment by repeatedly** [comment]
@sonots ping?

**Comment by sonots** [comment]
`array` parameter looks sweet. PR is always welcome!
