### ISSUE TITLE
Fluentd process never exits when blocking for full buffer queue

### ISSUE THREAD

**Issue by tagomoris** [fluent/fluentd#1260]
I confirmed this problem on Fluentd v0.12.29, but I know that v0.14.x has this problem too.

When we enable `<buffer> overflow_action block </buffer>` or `buffer_queue_full_action block` and the buffer queue is actually full, input threads will block, and never returns if output plugins doesn't go back to normal.

If users will try to stop Fluentd process under this situation, Fluentd don't stop these threads, and the process never stops.

**Comment by tagomoris** [comment]
@repeatedly will you fix this problem in v0.12 versions?

**Comment by repeatedly** [comment]
@tagomoris Okay, I will check it.

**Comment by tagomoris** [comment]
#1396 fixes this problem for v0.14 or later.

**Comment by zg** [comment]
Why is this issue still open if #1396 got merged?

**Comment by kenhys** [comment]
Released as v0.14.12
https://github.com/fluent/fluentd/blob/master/CHANGELOG.md#release-v01412---20170130 v0.14.12

**Comment by cosmo0920** [comment]
Fixed in v0.14.12. And v0.12 is now EOL? (No activities until end of 2019 as described in https://www.fluentd.org/blog/drop-schedule-announcement-in-2019)

**Comment by kenhys** [comment]
v0.12 is not maintained anymore, I'll close it.
