### ISSUE TITLE
Duplicating Logs

### ISSUE THREAD

**Issue by rodaan** [fluent/fluentd#1262]
**td-agent version:**
td-agent --version
td-agent 0.12.26

**Environment information:**
Distributor ID:	CentOS
Description:	CentOS Linux release 7.2.1511 (Core) 
Release:	7.2.1511

**Configuration:**

```
<source>
 @type tail
 path /var/log/errorlog/fakelogs.current
 tag tdagent
 format none
 read_from_head true
</source>

<match **>
 @type elasticsearch
 logstash_format true
 host 20.0.112.37
 port 9200
 index_name app_logs.${Time.at(time).getutc.strftime(@logstash_dateformat)}
 type_name tdagent 
 buffer_type file
 buffer_path /var/log/td-agent/buffer/backup.buffer
</match>
```

**Your problem explanation:**
I am running a test on td-agent and it looks like it is sending duplicate logs to my Elasticsearch database. Here is what the fakelogs.current looks like:

...
Wed Oct 5 16:02:05 PDT 2016 + This is a test log
Wed Oct 5 16:02:15 PDT 2016 + This is a test log
Wed Oct 5 16:02:25 PDT 2016 + This is a test log
Wed Oct 5 16:02:35 PDT 2016 + This is a test log
Wed Oct 5 16:02:45 PDT 2016 + This is a test log
Wed Oct 5 16:02:55 PDT 2016 + This is a test log
Wed Oct 5 16:03:05 PDT 2016 + This is a test log
Wed Oct 5 16:03:15 PDT 2016 + This is a test log
Wed Oct 5 16:03:25 PDT 2016 + This is a test log
Wed Oct 5 16:03:35 PDT 2016 + This is a test log
Wed Oct 5 16:03:45 PDT 2016 + This is a test log
Wed Oct 5 16:03:55 PDT 2016 + This is a test log
Wed Oct 5 16:04:05 PDT 2016 + This is a test log       <------ Log Example
Wed Oct 5 16:04:15 PDT 2016 + This is a test log
Wed Oct 5 16:04:25 PDT 2016 + This is a test log
Wed Oct 5 16:04:35 PDT 2016 + This is a test log
Wed Oct 5 16:04:45 PDT 2016 + This is a test log
...

Here is what I see on Kibana:
<img width="1418" alt="screen shot 2016-10-05 at 5 04 30 pm" src="https://cloud.githubusercontent.com/assets/6776207/19135998/d65afec6-8b1d-11e6-905f-bde032acf683.png">

This happens when I stop the td-agent and restart it. Any reason why it is doing this? How does Fluentd keep track of logs it has already received and processed?

Thanks,

Rodaan

**Comment by kzk** [comment]
This option might be the cause. This will ask Fluentd to read logs from the head, every time you restart it.

> read_from_head true

Can you please remove this option and add "pos_file" parameter?

> http://docs.fluentd.org/articles/in_tail

**Comment by repeatedly** [comment]
Removing `read_from_head true` is not required.
If pos_file contains correct offset/inode, read_from_head is ignored at second read.

**Comment by rodaan** [comment]
Oh okay! So do I just add in a path for the pos_file parameter? What do you mean by "pos_file contains correct offset/inode"?

**Comment by repeatedly** [comment]
> What do you mean by "pos_file contains correct offset/inode"?

It means pos_file is not broken. HDD crash or manual edit by other person may cause inconsistent state but it is very rare case.

**Comment by kzk** [comment]
@repeatedly that's right thanks for the correction.

pos_file is used to record the last position Fluentd read the logs. By specifying this parameter, Fluentd can resume reading the file from the last position it reads.

**Comment by repeatedly** [comment]
If you hit this problem with pos_file, please reopen.
