### ISSUE TITLE
in_syslog new line delimiter

### ISSUE THREAD

**Issue by elelement** [fluent/fluentd#1270]
- **td-agent version**: td-agent 0.12.26
- **Environment information, e.g. OS**: Debian 8 for td-agent, Windows 7 for Python code. 
- **Plugin**: in_syslog.rb
- **Configuration**:
```xml
<source>
  @type syslog
  port 5140
  bind 0.0.0.0
  tag graylog.syslog.dev
  format json
</source>
<source>
  @type syslog
  port 5142
  bind 0.0.0.0
  tag graylog.syslog.dev
  format json
  protocol_type tcp
</source>
```
- **Problem explanation**:

I'm using Python's SyslogHandler class from logging.handlers package to send syslog messages to a Fluentd **syslog** input (https://github.com/fluent/fluentd/blob/master/lib/fluent/plugin/in_syslog.rb), both in TCP and UDP. UDP works fine, but TCP does not work. 

The "problem" is that the handler is not ending messages with a new line '\n' character (I realized that using tcpdump). I've temporarily added this to line 855 of handlers.py: 

```python
msg = prio + msg + '\n' 
```

And now is working. 

I did this, because of this comment in the code:
```ruby
# syslog family add "\n" to each message and this seems only way to split messages in tcp stream
Coolio::TCPServer.new(@bind, @port, SocketUtil::TcpHandler, log, "\n", callback)
```

Technically, syslog protocol doesn't use any delimiter, but the message's length. After reading the RFC5424 it seems that there is no such "new line message delimiter":

```
4.3.1.  Message Length

   The message length is the octet count of the SYSLOG-MSG in the
   SYSLOG-FRAME.  A transport receiver MUST use the message length to delimit a syslog message
```

Am I right?

Thank you for your time.

**Comment by repeatedly** [comment]
> Am I right?

Maybe right but fluentd's syslog parser doesn't support RFC5424 spec including structured format.
So this is why in_syslog can't parse your syslog message correctly.

I didn't test but one plugin exists for RFC5424. https://github.com/athenahealth/fluent-plugin-newsyslog

**Comment by elelement** [comment]
Thanks for the link. They are reusing the same line of code:

```ruby
# syslog family add "\n" to each message and this seems only way to split messages in tcp stream
Coolio::TCPServer.new(@bind, @port, SocketUtil::TcpHandler, log, "\n", callback)
```

I've tested it and found the same behavior (tested with Python and PHP scripts; in both cases I had to add a \n at the end of the message). My conf file looks like this:

```xml
<source>
  type newsyslog
  port 5142
  bind 0.0.0.0
  tag graylog.syslog.dev
  protocol_type tcp
</source>
```

Besides, the same statement can be found in RFC3164:

> 4.1.3 MSG Part of a syslog Packet
> 
>    The MSG part will fill the remainder of the syslog packet.  This will
>    usually contain some additional information of the process that
>    generated the message, and then the text of the message.  **There is no
>    ending delimiter to this part**.

What do you think? I really don't have any problem adding that but maybe this is something to fix.

**Comment by repeatedly** [comment]
> There is no ending delimiter to this part.

Yes. Syslog protocol itself doesn't define delimiter for their payload.
But typical syslog implementation treats the message as a text and it contains `\n`.
RFC5424 also doesn't define it so handling multiple messages in one TCP connection seems to depend on implementation.
Maybe, we need to check rsyslog or syslog-ng's implementation for better handling.

**Comment by elelement** [comment]
I've read https://tools.ietf.org/html/rfc6587 and I think that I'm starting to understand it. Apparently, There are two methods to distinguish different messages while using TCP syslog:

> Syslog over TCP has been around for a number of years.  Just like
>    legacy syslog over UDP, different implementations exist.  The older
>    method of non-transparent-framing has problems.  The newer method of
>    octet-counting is reliable and has not been seen to cause problems
>    noted with the non-transparent-framing method.

**3.4.1.  Octet Counting**

It "prepends" the message length to the syslog frame:

```
TCP-DATA = *SYSLOG-FRAME
SYSLOG-FRAME = MSG-LEN SP SYSLOG-MSG   ; Octet-counting
                                       ; method
MSG-LEN = NONZERO-DIGIT *DIGIT
NONZERO-DIGIT = %d49-57
SYSLOG-MSG is defined in the syslog protocol [RFC5424] and may
           also be considered to be the payload in [RFC3164]
```

   MSG-LEN is the octet count of the SYSLOG-MSG in the SYSLOG-FRAME.

**3.4.2.  Non-Transparent-Framing**

A trailer character to separate messages. **This is what the plugin assumes**:

> The non-transparent-framing method inserts a syslog message into a frame and terminates it with a TRAILER character.
       
```
TCP-DATA = *SYSLOG-FRAME
SYSLOG-FRAME = SYSLOG-MSG TRAILER  ; non-transparent-framing
                                          ; method
TRAILER = LF / APP-DEFINED
APP-DEFINED = 1*2OCTET
SYSLOG-MSG is defined in the syslog protocol [RFC5424] and may
                  also be considered to be the payload in [RFC3164]
```

> A transport receiver can assume that non-transparent-framing is used
>    if a syslog frame starts with the ASCII character "<" (%d60).

---

I think we can close this ticket, but it would be nice to mention it in the documentation.

Thanks again for your time.

**Comment by repeatedly** [comment]
Added to docs.fluentd.org.
