### ISSUE TITLE
Running Fluentd in windows, failed to flush the buffer

### ISSUE THREAD

**Issue by sanju090** [fluent/fluentd#1272]
Hi Everyone,
     I am facing issue flushing buffer from fluentd to elasticsearch. I am new to Fluentd, can you please help?

ElasticSearch version -> elasticsearch-2.4.1
Fluentd Version -> 0.14.7
fluent-plugin-elasticseach -> 1.7.0
OS -> Windows 7
![flush_buffer_issue](https://cloud.githubusercontent.com/assets/22774141/19278689/39fb025e-8fac-11e6-8889-90ff15a46378.png)
![flush_buffer_issue](https://cloud.githubusercontent.com/assets/22774141/19279238/9d5e9bce-8fae-11e6-8e1f-2a3591240754.png)

**fluent.conf**

<source>
  @type forward
  port 24224
</source>
<match **>
  @type elasticsearch
  host localhost
  port 9200
  index_name fluentd
  type_name fluentd
  buffer_type memory
  buffer_chunk_limit 256m
  buffer_queue_limit 128
  flush_interval 5s
  disable_retry_limit false
  retry_limit 5
  retry_wait 1s
  max_retry_wait 5s
</match>

**Comment by repeatedly** [comment]
I'm not familiar with Windows but it seems not fluentd related issue.
Check your environment: http://stackoverflow.com/questions/2972600/no-connection-could-be-made-because-the-target-machine-actively-refused-it

**Comment by sanju090** [comment]
Hi Masahiro,
    Thank you very much for your quick response. Please ignore that "No connection could be made.." part that message came when i tried to kill the process by hitting Ctrl + C.  
    I am able to send log data from Java application to fluentd, i did stdout it was able to print the data. The issue occurs when sending those data to elasticsearch.

Here is my updated fluent.conf file
<source>
  @type forward
  port 24224
</source>
<match **>
  @type copy
  <store>
    @type stdout
  </store>
  <store>
  @type elasticsearch
  host localhost
  port 9200
  index_name fluentd
  type_name fluentd
  buffer_type memory
  buffer_chunk_limit 256m
  buffer_queue_limit 128
  flush_interval 5s
  disable_retry_limit false
  retry_limit 5
  retry_wait 1s
  max_retry_wait 5s
  </store>
</match>

Java Code to send log to fluentd

import java.util.HashMap;
import java.util.Map;
import org.fluentd.logger.FluentLogger;

public class FluentdLogger {
	final static FluentLogger LOG = FluentLogger.getLogger("fluentd", "localhost", 24224);
	
	public static void main (String [] args) {
		FluentdLogger fluentdlog = new FluentdLogger();
		fluentdlog.doApplicationLogic();
	}

    public void doApplicationLogic() {
        
        Map<String, Object> data = new HashMap<String, Object>();
        data.put("from", "userA");
        data.put("to", "userB");
        LOG.log("tag1", data);
        
      
    }

}

![buffer_issue1](https://cloud.githubusercontent.com/assets/22774141/19283139/d5067cbc-8fbe-11e6-9706-b53b314ffacc.png)
![buffer2](https://cloud.githubusercontent.com/assets/22774141/19283138/d502df6c-8fbe-11e6-9506-64871f96cefd.png)

**Comment by repeatedly** [comment]
I see.
It seems a regression by https://github.com/fluent/fluentd/pull/1263 .
I will check it.

**Comment by repeatedly** [comment]
Could you test this configuration with v0.14.6?

**Comment by repeatedly** [comment]
I confirmed this `msgpack_each` related error on Mac.
I will fix this issue soon.

**Comment by repeatedly** [comment]
I found the cause and I'm now writing the patch.
We will release v0.14.8 soon.

**Comment by sanju090** [comment]
Hi Masahiro, Thank you very much for looking into it and writing the patch. Can you please update this thread once v0.14.8 is ready. Thanks again

**Comment by repeatedly** [comment]
Release v0.14.8

**Comment by sanju090** [comment]
Thank you very much Masahiro for your quick responses and the fix  :+1:
