### ISSUE TITLE
in_forward should generate "time" with sub-second precision

### ISSUE THREAD

**Issue by njam** [fluent/fluentd#1276]
I noticed that `in_forward` generates event times with only seconds-precision when debugging with `fluent-cat`.

How about generating times with higher precision in [in_forward.rb](https://github.com/fluent/fluentd/blob/master/lib/fluent/plugin/in_forward.rb)?
Currently the code looks like this:
```rb
time = Engine.now if time.to_i == 0
```

**Comment by repeatedly** [comment]
in_forward is no problem.
The problem is fluent-cat sends second-precision time.
I will fix it.

**Comment by njam** [comment]
Aha, thanks!
