### ISSUE TITLE
if record is string. How to deal with it? 

### ISSUE THREAD

**Issue by orangemi** [fluent/fluentd#1279]
- fluentd v0.3.1
- docker.io/fluent/fluentd

I see the fluentd docs talking based on the `record` is a hash record. What if a record is a string record? Is there a way to convert it? #591 mentioned it but no description how to deal with it.

I tried to use transformer filter to convert like this but failed:
```
    <filter core.**>
      @type record_transformer
      enable_ruby
      <record>
        message ${record}
      </record>
    </filter>
```

Output:
```
  failed to reform records error_class=NoMethodError error="undefined method `merge!' for \"[2016-10-17T04:30:21.573Z] INFO {\\\"1\\\":234,\\\"abc\\\":\\\"abc\\\"}\":String"
```

I tried `record.to_str` but the same error.

I also tried to use filter_parser like this(configure errored if I wont add key_name):
```
    <filter core.**>
      @type parser
      format /^(?<message>.*)$/
      key_name record
    </filter>
```

Output:
```
2016-10-17 05:18:16 +0000 [warn]: record does not exist
```

I don't want to add format to `in_forward` because there are lots of sources use this port.

**Comment by repeatedly** [comment]
No way. Fluentd can't handle string type record.
Senders, e.g. fluent-logger, and input plugins must emit a record as a Hash.

**Comment by repeatedly** [comment]
Does senders or plugins emit string type record?

**Comment by orangemi** [comment]
Thank you for your quick reply. I will make a new PR to [fluent/fluent-logger-node](https://github.com/fluent/fluent-logger-node).

**Comment by repeatedly** [comment]
Ah, okay.
