### ISSUE TITLE
Maintenance Plugins

### ISSUE THREAD

**Issue by scrwr** [fluent/fluentd#1288]
I'm a bit worried about the maintenance of the Plugin repos, as fluents power is coming from this, but it seems like even pull request don't get touched anymore since a long time.

Example:
https://github.com/fluent/fluent-plugin-flume/pulls

Are these plugins going to be deprecated?

**Comment by tagomoris** [comment]
It's the problem of that plugin, not fluentd itself. Flume plugin now needs active maintainer...
Generally speaking, you should "ping" on threads when repository owners don't respond to issues or pull requests.
