### ISSUE TITLE
Apache to s3 issue

### ISSUE THREAD

**Issue by yalamber** [fluent/fluentd#129]
I followed example here : http://docs.fluentd.org/articles/apache-to-s3
but seems like it is not working I opened file in /var/log/td-agent/var/log/td-agent/td-agent.log
and there i saw this msg.
unexpected error error="Permission denied - /var/log/fluent"
also there doesnot seem to be any folder fluent in /var/log/fluent. how do i fix it?

**Comment by kajahno** [comment]
In my case I just did:
```
$ sudo mkdir /var/log/fluent
$ sudo chown -R td-agent:td-agent /var/log/fluent
```
