### ISSUE TITLE
in_udp buffer size issue

### ISSUE THREAD

**Issue by fevlake** [fluent/fluentd#1334]
td-agent version is:

root@kibanaes:~# dpkg -l | grep td-age
ii  td-agent                            2.3.2-0                             amd64        Treasure Agent: A data collector for Treasure Data

Ubuntu 14.04.

I have some issues with in_udp plugin.

We got a service which sends json messages over udp. And sometimes it sends about 500 000 messages in 10 secs. And just 5 000 of messages are delivered to kibana and local files.

I've checked configuration and found that issue is related to input udp buffer:

```
root@td-agent# netstat -su
IcmpMsg:
    OutType3: 817
Udp:
    2328648 packets received
    122718 packets to unknown port received.
    9310516 packet receive errors
    566 packets sent
    RcvbufErrors: 9310516

```

So, i've increased udp kernel parameters like this:

```
net.ipv4.udp_rmem_min = 1073741824
net.ipv4.udp_wmem_min = 1073741824
net.core.netdev_max_backlog=500000
net.core.rmem_max = 1073741824
```

But i still get a lot of RcvbufErrors. I think it's related to socket creation inside fluentd. Maybe there is some options to increase input buffer size to socket?

Configuration:

```
<source>
  @type udp
  format json
  tag udp-input
  time_key date
  time_format %Y-%m-%dT%H:%M:%S
  port 24226
  @label @json_udp
  body_size_limit 5MB
</source>
```

Thanks!

**Comment by repeatedly** [comment]
> I think it's related to socket creation inside fluentd.

How to check this?

**Comment by fevlake** [comment]
@repeatedly I thought about increasing SO_RCVBUF in socket options.. But seems that this value is taken from net.core.rmem_default by default.
But it also didn't help.

**Comment by fevlake** [comment]
@repeatedly i've checked linux udp stack using iperf:

```
[  3]  0.0-10.0 sec   488 MBytes   409 Mbits/sec   0.056 ms  480/348832 (0.14%)
```

No RcvbufErrors were seen. Average incoming rate was about 40 000 udp packet per sec.

Seems that fluentd can't handle such traf. Maybe i can debug it somehow?

Also i was checking fluentd using moniroring plugin and it didn't show me buffer_queue_len on elasticsearch output. So i think the problem is between kernel and fluent's socket. Any ideas?

**Comment by fevlake** [comment]
@repeatedly ok, i've fixed that issue. Sorry for your time.
Seems that fluent doesn't have input buffer or smth like that. So if fluent can't accept new event - kernel drops it.

I've splitted configuration for udp input into 3 configs with different ports. And installed multiprocess plugin to run multiple instances. So configuration looks like this.

td-agent.conf:

```
.... skipped ...
<source>
  @type multiprocess

  <process>
    cmdline -c /etc/td-agent/td-agent-udp-1.conf --log /var/log/td-agent/td-agent-udp-1.log
    sleep_before_start 1s
    sleep_before_shutdown 5s
  </process>
  <process>
    cmdline -c /etc/td-agent/td-agent-udp-2.conf --log /var/log/td-agent/td-agent-udp-2.log
    sleep_before_start 1s
    sleep_before_shutdown 5s
  </process>
  <process>
    cmdline -c /etc/td-agent/td-agent-udp-3.conf --log /var/log/td-agent/td-agent-udp-3.log
    sleep_before_start 1s
    sleep_before_shutdown 5s
  </process>
</source>

... skipped ...
```

td-agent-udp-1.conf:

```
<source>
  @type udp
  format json
  tag udp-input
  time_key date
  time_format %Y-%m-%dT%H:%M:%S
  port 24236
  body_size_limit 5MB
</source>

... skipped ...
```

td-agent-udp-2/3.conf are the same except port setting: 24237 and 24238 are used.

Then i've configured iptables as load balancer for udp input. Just because i didn't want to reconfigure services which sends logs to fluent. Configuration is like this:

```
-A PREROUTING -d x.x.x.x/32 -p udp -m udp --dport 24226 -m state --state NEW -m statistic --mode nth --every 3 --packet 0 -j DNAT --to-destination x.x.x.x:24236
-A PREROUTING -d x.x.x.x/32 -p udp -m udp --dport 24226 -m state --state NEW -m statistic --mode nth --every 3 --packet 1 -j DNAT --to-destination x.x.x.x:24237
-A PREROUTING -d x.x.x.x/32 -p udp -m udp --dport 24226 -m state --state NEW -m statistic --mode nth --every 3 --packet 2 -j DNAT --to-destination x.x.x.x:24238
```

Where:
- x.x.x.x - ip address of machine which is running fluentd
- 24226 - port which is used in client configs to send logs


Thats it. Just after that host was able to handle about 2000-4000 udp packets per second. And no packets were lost (rcvbuffererros counter was 0).

Also seems that iptables buffer packets somehow - because application has sent all logs in 10 seconds, but td-agent was receiving it during 2 minutes or smth like that.

So i think iptables will help with one agent too.

**Comment by repeatedly** [comment]
Thanks for the investigation.

I will link this issue from in_udp document.

**Comment by repeatedly** [comment]
Add note for this case: https://github.com/fluent/fluentd-docs/commit/1f41acf6c46e4d8be4661e3f69cf1e212cd580ff
Closed.

**Comment by fevlake** [comment]
@repeatedly sorry for reopening the issue, but seems that iptables solution didn't work properly. UDP buffer filled up in some hours and everything goes down again.

So i've created a small golang service which acts like udp proxy. It's not great solution i think, but it works. Best way seems to move to some storage like kafka and pull logs from it.

So, here the code goes:

`package main

import (
  "net"
  "fmt"
  "encoding/json"
  "time"
  "github.com/fluent/fluent-logger-golang/fluent"
)

const layout string = "2006-01-02T15:04:05"
var logger *fluent.Fluent

func handlePacket(buf []byte, rlen int) {
    var msg interface{}
    tag := "unknown"
    var date string

    log_json := buf[0:rlen]

    err := json.Unmarshal(log_json, &msg)
    if err != nil {
        fmt.Println(err)
    }

    entry := msg.(map[string]interface{})

    if val, ok := entry["tag"]; ok {
      tag = val.(string)
    }

    if val, ok := entry["date"]; ok {
      date = val.(string)
    }
    loc, _ := time.LoadLocation("Local")
    ts,err := time.ParseInLocation(layout, date, loc)
    if err != nil {
      ts = time.Now()
    }

    err = logger.EncodeAndPostData(tag, ts.Local(), msg)
    if err != nil {
        fmt.Println(err)
    }

}

func main() {
  logger, _ = fluent.New(fluent.Config{FluentPort: 24227, FluentHost: "127.0.0.1", BufferLimit: 64*1024*1024})
  defer logger.Close()

  addr, _ := net.ResolveUDPAddr("udp", ":24226")
  sock, _ := net.ListenUDP("udp", addr)
  sock.SetReadBuffer(64*1024*1024)

  for {
    buf := make([]byte, 65536)
    rlen, _, _ := sock.ReadFromUDP(buf)
    go handlePacket(buf, rlen)
  }
}`

We are getting tags from json. Also as a date. But date field is optional. So anyone could use that proxy to get logs by udp.

Thanks.
