### ISSUE TITLE
td-agent fails to install

### ISSUE THREAD

**Issue by usergoodvery** [fluent/fluentd#1347]
hi

I attempted to install using curl -L https://toolbelt.treasuredata.com/sh/install-ubuntu-xenial-td-agent2.sh | sh
on ubuntu Xenial  I get the follwoing error:
Setting up td-agent (2.3.3-0) ...
Conffile /etc/td-agent/td-agent.conf has been modified. Remain untouched.
Job for td-agent.service failed because the control process exited with error code. See "systemctl status td-agent.service" and "journalctl -xe" for details.
invoke-rc.d: initscript td-agent, action "start" failed.
dpkg: error processing package td-agent (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 td-agent
W: --force-yes is deprecated, use one of the options starting with --allow instead.
E: Sub-process /usr/bin/dpkg returned an error code (1)

Output of 'systemctl status td-agent.service':

● td-agent.service - LSB: data collector for Treasure Data
   Loaded: loaded (/etc/init.d/td-agent; bad; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sun 2016-12-04 17:11:43 AEDT; 2min 3
     Docs: man:systemd-sysv-generator(8)
  Process: 5574 ExecStart=/etc/init.d/td-agent start (code=exited, status=1/FAIL

Dec 04 17:11:43 db.ufsrv systemd[1]: Starting LSB: data collector for Treasure D
Dec 04 17:11:43 db.ufsrv td-agent[5574]: Starting td-agent: start-stop-daemon: u
Dec 04 17:11:43 db.ufsrv td-agent[5574]:  * td-agent
Dec 04 17:11:43 db.ufsrv systemd[1]: td-agent.service: Control process exited, c
Dec 04 17:11:43 db.ufsrv systemd[1]: Failed to start LSB: data collector for Tre
Dec 04 17:11:43 db.ufsrv systemd[1]: td-agent.service: Unit entered failed state
Dec 04 17:11:43 db.ufsrv systemd[1]: td-agent.service: Failed with result 'exit-

**Comment by repeatedly** [comment]
This is fluentd repository, not td-agent.
Please re-open on omnibus-td-agent repository.
