### ISSUE TITLE
multiline parser use case result can't appear.

### ISSUE THREAD

**Issue by liujiawinds** [fluent/fluentd#1355]
![image](https://cloud.githubusercontent.com/assets/1757754/20962350/e9fe7af4-bca3-11e6-8f99-43b3d380b7ba.png)

According to the [document](http://docs.fluentd.org/articles/in_tail), the stack trace didn't in the result as expected.

```
2013-03-03 14:27:33 +0900 zimbra.mailbox: {"thread":"main","level":"INFO","message":"  Main - Start"}
2013-03-03 14:27:33 +0900 zimbra.mailbox: {"thread":"main","level":"ERROR","message":" Main - Exception\njavax.management.RuntimeErrorException: null\n    at Main.main(Main.java:16) ~[bin/:na]"}
2013-03-03 14:27:33 +0900 zimbra.mailbox: {"thread":"main","level":"INFO","message":"  Main - End"}
```

versions:
fluentd:0.12.19
OS: centOS7

**Comment by tagomoris** [comment]
Please update your description with the version of Fluentd you're using, and the full configuration you're trying with.

**Comment by liujiawinds** [comment]
@tagomoris  Hi, I'm trying to parse the logs on the `td-agent-ui`. So, I do not have a real configuration about this.

**Comment by liujiawinds** [comment]
I've found this is a bug of `td-agent-ui`. when I tried configuration below, it works.

```
<source>
    type tail
    path /Users/admin/Downloads/scorer.log.tmp2
    tag scorer.temp
    format multiline
    format_firstline /\d{4}-\d{1,2}-\d{1,2} \d{1,2}:\d{1,2}:\d{1,2}.\d{3}/
    format1 /(?<time>\d{4}-\d{1,2}-\d{1,2} \d{1,2}:\d{1,2}:\d{1,2}.\d{3}) \[(?<thread>.*?)\] (?<level>[^\s]+)\s+\[(?<class>.*?):(?<rownum>.*?)\](?<message>.*)/
    read_from_head true
    pos_file /tmp/fluentd--1481166365.pos
  </source>
  <match **>
    type stdout
    output_type json
  </match>
```

![image](https://cloud.githubusercontent.com/assets/1757754/20996672/18755f74-bd3a-11e6-868c-5f8c24baa155.png)

As you see, this configuration can parse the stack trace log.

**Comment by repeatedly** [comment]
Close because this is the problem of fluentd-ui.

@uu59 Could you check this?

**Comment by uu59** [comment]
> According to the document, the stack trace didn't in the result as expected.

Did you mean "result" is the colored text or something else?

**Comment by liujiawinds** [comment]
@uu59 The second line in the result, it didn't contain the stack trace like the document.

**Comment by uu59** [comment]
I see. It seems fluentd-ui bug. Could you file it on the fluentd-ui repository?
