### ISSUE TITLE
keep_time_key' in <source> is not used.

### ISSUE THREAD

**Issue by suchisubhra** [fluent/fluentd#1360]
Check [CONTRIBUTING guideline](https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md) first and here is the list to help us investigate the problem.

- fluentd 0.14.8
- Environment information cents
- Your configuration

```
<source>
  type tail
  path /var/log/containers/*.log
  pos_file fluentd-container.pos
  #time_format %Y/%m/%dT%H:%M:%S.%N
  time_format %Y-%m-%dT%H:%M:%S.%NZ
  tag kubernetes.*
  format json
  keep_time_key true
  read_from_head false
</source>
```

- Your problem explanation. If you have an error logs, write it together.

```
parameter 'keep_time_key' in <source>
  type tail
  path "/var/log/containers/*.log"
  pos_file "fluentd-container.pos"
  time_format %Y-%m-%dT%H:%M:%S.%NZ
  tag "kubernetes.*"
  format json
  keep_time_key true
  read_from_head false
  <parse>
    @type json
    time_format %Y-%m-%dT%H:%M:%S.%NZ
  </parse>
</source> is not used.
```

and in elasticsearch i  am not getting time field...

**Comment by repeatedly** [comment]
You need to specify `time_key`.

**Comment by repeatedly** [comment]
If you hit same problem with v0.14.9 and with `time_key`,
reopen this issue.

**Comment by suchisubhra** [comment]
added time_key time
<source>
    type tail
    path "/var/log/containers/*.log"
    pos_file "fluentd-container.pos"
    time_format %Y-%m-%dT%H:%M:%S.%NZ
    tag "kubernetes.*"
    format json
    time_key time
    keep_time_key true
    read_from_head false
    <parse>
      @type json
      time_key time
      time_format %Y-%m-%dT%H:%M:%S.%NZ
    </parse>
  </source>

still  same issue
2016-12-09 00:06:19 +0000 [warn]: parameter 'keep_time_key' in <source>
  type tail
  path "/var/log/containers/*.log"
  pos_file "fluentd-container.pos"
  time_format %Y-%m-%dT%H:%M:%S.%NZ
  tag "kubernetes.*"
  format json
  time_key time
  keep_time_key true
  read_from_head false
  <parse>
    @type json
    time_key time
    time_format %Y-%m-%dT%H:%M:%S.%NZ
  </parse>
</source> is not used.

**Comment by repeatedly** [comment]
Do you use v0.14.9?

**Comment by suchisubhra** [comment]
I am using .14.8

**Comment by repeatedly** [comment]
Check my comment... https://github.com/fluent/fluentd/issues/1360#issuecomment-265878755

**Comment by suchisubhra** [comment]
It worked.. thank you

Suchi
