### ISSUE TITLE
Running with --dry-run causes segfault with my config

### ISSUE THREAD

**Issue by josh-tepper** [fluent/fluentd#1363]
Check [CONTRIBUTING guideline](https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md) first and here is the list to help us investigate the problem.

- fluentd 0.14.8
- Running inside docker in a container which is built on top of this image (which is, itself, based on centos): https://github.com/fabric8io/docker-fluentd/blob/master/Dockerfile
My child image contains additional dependencies, including the fluentd-redshift plugin.
- My configuration: 
```
<match fluent.**>
    @type null
</match>
<source>
    @type tail
    path "#{ENV['INPUT_FILE_PATTERN']}"
    pos_file /var/log/rs-containers.log.pos
    time_format %Y-%m-%dT%H:%M:%S.%NZ
    tag foo
    format json
    read_from_head true
</source>
<match foo>
    @type redshift
   REDSHIFT CONFIG REDACTED
</match>
```
- Note that this config w/ my image works (in docker) when not specifying --dry-run
- Running with --dry-run causes a segfault; I invoke the image as follows:
`docker run -e MY_ENV=blah -v /my/dir/no1:/my/dir/no1 -v /my/dir/no2:/my/dir/no2 -it my_image:my_tag --dry-run`
- The segfault is repeatable.
- The following logs are written to STDOUT:
[out.txt](https://github.com/fluent/fluentd/files/645139/out.txt)
#

**Comment by repeatedly** [comment]
From your logs, you use ruby 2.3.0-p0.
Could you update your ruby version to 2.3.3?

**Comment by josh-tepper** [comment]
Same issue with 2.3.3:
[out.txt](https://github.com/fluent/fluentd/files/646926/out.txt)

**Comment by josh-tepper** [comment]
Will have to get back to you shortly.  As I mentioned, I'm running from a centos image, and it seems that the latest ruby in the centos repos and software collection is 2.3.0.  Might have to build ruby

**Comment by repeatedly** [comment]
If someone hit this problem with latest ruby and fluentd, reopen the issue.
