### ISSUE TITLE
service td-agent start fails at read conf file

### ISSUE THREAD

**Issue by 3tinkers** [fluent/fluentd#1372]
My system is CentOS 7. When I run "service td-agent start", it fails.The log stop at 
"2016-12-14 18:39:51 +0800 [info]: reading config file path="/etc/td-agent/td-agent.conf"".
Is it for the reason that my conf file too large? My conf file is in the attach.

[td-agent.conf.zip](https://github.com/fluent/fluentd/files/651503/td-agent.conf.zip)

**Comment by repeatedly** [comment]
No. Your configuration contains following lines and it is broken.

```
    <match sensor_58511d30b0a5e>
    @type kafka
    brokers 192.168.31.212:9092
    default_topic sensor_data
    output_data_type json
    output_include_tag false
    output_include_time false
    </match>
    path /home/sensor-log/sensor_gps_1_2.log
        pos_file /home/sensor-log/sensor_gps_1_2.log.pos
        refresh_interval 2
        tag sensor_58511d30b0a5e
        format /^(?<systime>[^ ]+),(?<sensorId>[^ ]+),(?<longitude>[^ ]+),(?<latitude>[^ ]+)$/  
    </source>   
```

**Comment by repeatedly** [comment]
It seems not a bug so closed.
If you have a problem with proper configuration, reopen the issue.
