### ISSUE TITLE
Fluentd : error on forwerder thread error="Broken pipe"

### ISSUE THREAD

**Issue by M22an** [fluent/fluentd#1377]
- **td-agent version** : 0.12.29
- **OS** : 
Description:    Red Hat Enterprise Linux Server release 7.3 (Maipo)
Release:        7.3
Codename:       Maipo

- **Configuration**
```
<match app.DynamoDB app.DynamoDB.*>
  @type copy
  <store>
    @type dynamodb
    detach_process 4
    aws_key_id XXXXXX
    aws_sec_key XXXXXXX
    dynamo_db_endpoint XXXXXX
    dynamo_db_table XXXXXX
  </store>
  <store>
    @type file
    path /var/log/td-agent/templogs
  </store>
  <store>
    @type relabel
    @label @Email
  </store>
</match>
```

Fluentd seems to be breaking when a large number of requests are sent in a short period of time (i.e., 500 requests per sec). Here is the error log,

> 2016-12-16 02:59:22 -0500 [error]: error on forwerder thread error="Broken pipe"
>   2016-12-16 02:59:22 -0500 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.29/lib/fluent/process.rb:269:in `write'
>   2016-12-16 02:59:22 -0500 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.29/lib/fluent/process.rb:269:in `to_msgpack'
>   2016-12-16 02:59:22 -0500 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.29/lib/fluent/process.rb:269:in `block in run'
>   2016-12-16 02:59:22 -0500 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.29/lib/fluent/process.rb:268:in `each'
>   2016-12-16 02:59:22 -0500 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.29/lib/fluent/process.rb:268:in `run'

Can someone help me out on this issue, is there any other setting that I need to make to overcome this issue ?

**Comment by repeatedly** [comment]
Broken pipe happens with several reasons.
Hmm... there is no error in output plugin side or system logs?

BTW, `detach_process` will be deprecated in the future,
so avoiding it is better.
num_threads doesn't fit your case?

**Comment by ganmacs** [comment]
it's a stale issue. I'm closing. if you have any problem, updating fluentd might help it.
