### ISSUE TITLE
Issue with Fluentd(EFK) Configuration in EFK

### ISSUE THREAD

**Issue by vineethloka** [fluent/fluentd#1394]
Problem

Fluentd is Inserting unicode content into elasticsearch even though log4j2 configuration is sending utc-8

Steps to replicate

log4j2 config

< Socket name="socketMiddlewareSandbox" protocol="udp" port="5170" host="10.0.109.46">< SerializedLayout/>
< PatternLayout pattern="%d{ISO8601} %p: %m%n" charset="UTC-8"/>
</ Socket>

fluentd configuration(td-agent.conf)

type udp tag nginx.access port 5170 bind 0.0.0.0 delimiter \n format json codec json charset ISO-8859-1 index_name fluentd _index fluentd
<match *.**>
type copy

type elasticsearch
logstash_format true
host 10.0.109.46
port 9200
index_name fluentd
_index fluentd
type_name fluentd
include_tag_key true
tag_key @log_name
flush_interval 10s
index fluentd

type file
path /var/log/td-agent/td-mulesoft.log

Logs in Kibana view
pattern not match: "\xAC\xED\x00\x05sr\x00>org.apache.logging.log4j.core.impl.Log4jLogEvent$LogEventProxy\x9C\xED\x0F]p\xDA*\x16\x02\x00\rZ\x00\fisEndOfBatchZ\x00\x12isLocationRequiredJ\x00\ntimeMillisL\x00\ncontextMapt\x00\x0FLjava/util/Map;L\x00\fcontextStackt\x005Lorg/apache/logging/log4j/ThreadContext$ContextStack;L\x00\x05levelt\x00 Lorg/apache/logging/log4j/Level;L\x00\nloggerFQCNt\x00\x12Ljava/lang/String;L\x00\nloggerNameq\x00~\x00\x04L\x00\x06markert\x00!Lorg/apache/logging/log4j/Marker;L\x00\amessaget\x00Lorg/apache/logging/log4j/message/Message;L\x00\x06sourcet\x00\x1DLjava/lang/StackTraceElement;L\x00\nthreadNameq\x00~\x00\x04L\x00\vthrownProxyt\x003Lorg/apache/logging/log4j/core/impl/ThrowableProxy;xp\x00\x01\x00\x00\x01YC\xBFW\x01sr\x00\x1Ejava.util.Collections$EmptyMapY6\x14\x85Z\xDC\xE7\xD0\x02\x00\x00xpsr\x00>org.apache.logging.log4j.ThreadContext$EmptyThreadContextStack\x00\x00\x00\x00\x00\x00\x00\x01\x02\x00\x00xpsr\x00\x1Eorg.apache.logging.log4j.Level\x00\x00\x00\x00\x00\x18 \x1A\x02\x00\x03I\x00\bintLevelL\x00\x04nameq\x00~\x00\x04L\x00\rstandardLevelt\x00,Lorg/apache/logging/log4j/spi/StandardLevel;xp\x00\x00\x01\x90t\x00\x04INFO~r\x00org.apache.logging.log4j.spi.StandardLevel\x00\x00\x00\x00\x00\x00\x00\x00\x12\x00\x00xr\x00\x0Ejava.lang.Enum\x00\x00\x00\x00\x00\x00\x00\x00\x12\x00\x00xpt\x00\x04INFOt\x005org.apache.commons.logging.impl.SLF4JLocationAwareLogt\x00;org.mule.module.launcher.application.DefaultMuleApplicationpsr\x00.org.apache.logging.log4j.message.SimpleMessage\x8BtM0`\xB7\xA2\xA8\x02\x00\x01L\x00\amessageq\x00~\x00\x04xpt\x00\xBA\r\n++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++\r\n+ Initializing app 'amtrakservicesgroupd' +\r\n++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++sr\x00\ejava.lang.StackTraceElementa\t\xC5\x9A&6\xDD\x85\x02\x00\x04I\x00\nlineNumberL\x00\x0EdeclaringClassq\x00~\x00\x04L\x00\bfileNameq\x00~\x00\x04L\x00\nmethodNameq\x00~\x00\x04xp\x00\x00\x00\xA5q\x00~\x00\x17t\x00\eDefaultMuleApplication.javat\x00\x04initt\x00\x04mainpy"
...

any help or suggestions on this please?

**Comment by repeatedly** [comment]
This seems not fluentd core problem and questions.
Use mailing list first.

**Comment by repeatedly** [comment]
And for repreducing problem, please minimize your client code.
Hard to debug with only log4j configuration.
