### ISSUE TITLE
Using fluentd as tracking server - is it bullet proof? will I loose lines of logs?

### ISSUE THREAD

**Issue by nitzanav** [fluent/fluentd#1400]
Hi Guys,

I want to use a fluentd as a tracking server, nginx will redirect after immediately, but will append URLs to log files, make requests just before the redirection (using access multiple logs formatting).

Then fluentd will act a a messaging queue to read the logs which will actually be formatted as URLs list. seems to me that [fluent-plugin-out-http](https://github.com/ento/fluent-plugin-out-http) will do the job.

This stack should replace messaging queue, and be an initiative to use fluentd as scalable messaging queue and tracking server rather than in addition to its usage as log shipper. This stack can turn into the most scalable tracking server as it require only pure nginx at realtime.

Well this s the background, and my question is, will this be bullet-proof? what are the probability to loose a line of log when agent shut down or when log rotates?  I plan to have a single local fluentd for each nginx, so no need for fancy HA topology, in order to make it highly available right?

I have asked many other questions [in stackoverflow](http://stackoverflow.com/questions/41434437/fluentd-filebeat-rsyslog-output-to-script-curl) 

Will be very happy to get tips from you guys.

Sorry for opening an issue for a question, but I didn't know who else to turn to :)
Hope to get your support.

**Comment by tagomoris** [comment]
Please do not use issues for questions and answers.
https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md#got-a-question-or-problem

Use SO, Slack or Mailing list.
* Mailing list: https://groups.google.com/forum/#!forum/fluentd
* Slack: http://slack.fluentd.org/

**Comment by nitzanav** [comment]
will do, sorry.
