### ISSUE TITLE
custom http port field in configuration not being applied correctly

### ISSUE THREAD

**Issue by samlavery** [fluent/fluentd#1418]
fluentd 0.12.29, ubuntu 14.04, docker 1.12.0, kubernetes 1.4

I ran into an odd issue today with our fluentd container and configuring it to run on non-standard ports.  While using the following configuration, fluentd was connecting to elasticsearch on port 9200, NOT 9210 as expected.
`
<match docker.*>
  type elasticsearch
  logstash_format true
  host 10.0.254.188
  port 9210
  flush_interval 1s
  type_name container_logs
</match>
`

I verified via tcpdump that traffic from the container only used port 9200 (which resulted in writing to the wrong instance of elastic search).  After some tinkering, I did find a configuration that worked and verified that port 9210 was used.  It's this:
`<match docker.*>
  type elasticsearch
  logstash_format true
  hosts 10.0.254.188:9100
  flush_interval 1s
  type_name container_logs
</match>`

One would expect separate host and port lines to work, and I assume this is tripping up other engineers just trying to split their instances of elastic search up.  I hope this helps.

**Comment by repeatedly** [comment]
It sees es plugin issue.
