### ISSUE TITLE
The shutdown lifecycle_control order of multiple plugins was wrong.

### ISSUE THREAD

**Issue by reversi-fun** [fluent/fluentd#1430]
I am in trouble. The order of lifecycle of multi-stage plugin is not in order of configuration-file.

- fluentd  version: 0.14.11
- Environment information: Windows7 x64

- problem explanation. 
The order I expected was as per the config-file.
in_tail -> record_modifier_Filter -> concat_Filter -> ThreadsCounter_Filter -> out_copy -> out_elasticsearch  -> webAccesslog.**::out_file ->  timeout1.out_file.

The order actually executed was as follows.
in_tail -> out_copy -> out_elasticsearch -> timeout1.out_file -> record_modifier_Filter -> concat_Filter -> ThreadsCounter_Filter -> webAccesslog.**::out_file

Concat_Filter was  emit out_file, concat_Filter was shutting down after out_file.
For this reason, flush_buffer of concat_Filter has been lost.

``` 
[info]: shutting down input plugin type=:tail plugin_id="object:1d96dcc"
[info]: shutting down output plugin type=:copy plugin_id="object:17db574"
[info]: shutting down output plugin type=:elasticsearch plugin_id="object:1cfe4b0"
[info]: shutting down output plugin type=:file plugin_id="object:1d91798"
[info]: shutting down filter plugin type=:record_modifier plugin_id="object:1de1394"
[info]: shutting down filter plugin type=:concat plugin_id="object:1499d9c"
[info]: shutting down filter plugin type=:ThreadsCounter plugin_id="object:1539b70"
[info]: shutting down output plugin type=:file plugin_id="object:155016c"
```

I think, the reason is that the following part of Fluent :: RootAgent :: lifecycle is not topologically sorting the plugin order.

``` 
  def lifecycle(desc: false, kind_callback: nil)
      kind_or_label_list = if desc
                   [:output, :filter, @labels.values.reverse, :output_with_router, :input].flatten
                 else
                    [:input, :output_with_router, @labels.values, :filter, :output].flatten
                  end
```

- my Configlation
```
<source>
  @type tail
  path tomcat/logs/localhost_access_log.*.txt
  format /^[^ ]* [^ ]* [^ ]* \[(?<request_at_time>[^\]]+)\] "(?<http_method>\S+)(?: +(?<http_uri>[^ ?]+)(?:\?(?<http_query>[^ ]*))? +\S*)?" (?<http_status>[0-9-]+) (?<response_bytes>[0-9-]+) (?<process_time>\d+(?:\.\d+)?)(?: (?<referer>-|"[^\"]*"))?(?: (?<agent>-|"[^\"]*"))?/
  time_format "%d/%m/%Y:%H:%M:%S.%L %z"
  time_key request_at_time

  types response_bytes:integer,process_time:float
  tag webAccesslog
  rotate_wait 5
  read_from_head true
  refresh_interval 12
  read_lines_limit 40
</source>

<filter webAccesslog.**>
  @type record_modifier
  
  <record>
   request_at_time ${(time.sec+time.nsec/1000000000.0)}
   contextRoot "${require 'uri' unless  defined? URI; /^\\/?([^\\/ ]*)/.match(URI.unescape(record['http_uri']))[1] rescue ''}"
   queryID     "${record['http_method'] + ' ' + (URI.unescape(record['http_query']).scan(/((?:userId|userid|User\\.id)=.|(?:SRC|src|evt|request_id|reportID||taskId|sortBy|context|Project|objectType|supports|roleName|hiddensections)=[^& ]{1,254})/).flatten.select{|v| v.size <= 24}.sort.join(' ')[0..254]  rescue '')}"
   serverName  "${ENV['COMPUTERNAME']}"  # "${Socket.gethostname}"
  </record>
  remove_keys http_referer,http_agent,http_query
</filter>

<filter webAccesslog.**>
  @type concat
  log_level info
  key queryID
  n_lines 20
  flush_interval 20
  timeout_label timeout1
</filter>

<filter xx.webAccesslog.**>
 @type ThreadsCounter
  threads_count_max 512
  throughput_sensitivity 16
  <counts>
   threads_total 		ThreadsCount, serverName
   throughputs			Throughput	, serverName
  </counts>
</filter>

<match webAccesslog.**>
  @type file
    @type file
    time_slice_format %Y%m%d
    time_slice_wait 10m
    include_time_key true
    time_format "%Y-%m-%dT%H:%M:%S.%L%z"
    path ./test_out/apache2.log
</match>

<label timeout1>
<match webAccesslog.**>
  @type copy

  <store>
    @type elasticsearch
    scheme http
    host localhost
    port 9200
    flush_interval 30
    request_timeout 60s
    logstash_format true
    logstash_prefix tenant_apServer02
    type_name webAccesslog
    time_key_format "%Y-%m-%dT%H:%M:%S.%L%z"
  </store>

  <store>
    @type file
    time_slice_format %Y%m%d
    time_slice_wait 10m
    include_time_key true
    time_format "%Y-%m-%dT%H:%M:%S.%L%z"
    path ./test_out/apache3.log
  </store>

</match>
</label>
```

best reguards.

ps. in Japanease.
度々、分かり難い文書で、お騒がわせしています。
私はconcat_Filterを真似て、バッファリングとFlush_Buffer機能を内蔵するような、私自身のFluginを作ろうとしています。
処が、concat_Filterの後に動くべきFilterがある場合、Flush_Bufferの中でEMITしたrecordが失われるという問題に遭遇しました。
その原因は Fluent :: RootAgent :: lifecycleの実装にあり、全てのFilterをlabelで順序つけることでも回避できると推定しています。
しかしながら、もっとエレガントな使い方がないものでしょうか？　もし無ければ、機能改善を望みたいものです。

**Comment by repeatedly** [comment]
@reversi-fun Use ``` to format your configuration or code. hard to read your configuration.

**Comment by tagomoris** [comment]
It's intended. Fluentd v0.14 will shutdown plugins in this order:
* input plugins
* output plugins which can emit events into Fluentd (including all v0.12 API plugins using compat layer)
* filter plugins
* output plugins

Output plugins which can emit events will lose its events if it's shutdown after filters or other output plugins. There's no way without any problems.
Once fluent-plugin-elasticsearch is updated to use Fluentd v0.14 native API, there will be no such issues (I know that fluent-plugin-elasticsearch do not emit any events).

**Comment by reversi-fun** [comment]
I See...... It's intended. Fluentd v0.14 .

I would like to youres present a new function that can specify order so that out_file will not be executed before concat_filter.
Concat_filter is representative of a plugin containing buffer and flush_timeout_buffer.

**Comment by tagomoris** [comment]
I can understand your points.
I think we're ok to merge pull-requests to add any feature to control startup-shutdown order of plugins.
