### ISSUE TITLE
cannot find the best way to parse this ...

### ISSUE THREAD

**Issue by lionux2** [fluent/fluentd#1432]
I have this log message, and not logged of course:

!!!!!!!!!!!!!!!!!!!!!!!!!!!
[warn]: Error in processing message. error_class=MessagePack::MalformedFormatError 
[warn]: Error in processing message. error_class=EOFError error=#<EOFError: end of  
!!!!!!!!!!!!!!!!!!!!!!!!!!

I think that it is because the format from ZMQ is the following:
---------
logs {"serv":1, "field":"heartbeat",.....}
---------

So, it looks like the first word "logs" is causing this to fail, although the rest is in json format.
Tried to configure some plugins to remove the first word, ... without luck.
Any idea how I could do this efficiently (and most of all effectively)?

Thanks,

**Comment by repeatedly** [comment]
It seems zmq plugin issue, not fluentd core.

**Comment by lionux2** [comment]
Thanks repeatedly. I solved my issue by noticing that "logs" and "{...}" where on two different lines.
