### ISSUE TITLE
in_tail: tests about file rotation and deletion sometimes fail

### ISSUE THREAD

**Issue by tagomoris** [fluent/fluentd#1434]
On CI environment, tests of `in_tail`  sometimes fails with incorrect number of events, or wrong event order.

* test_rotate_file_with_write_old[parse](TailInputTest::rotate file)
  * https://travis-ci.org/fluent/fluentd/jobs/193651057
  * https://travis-ci.org/fluent/fluentd/jobs/195131107
* test_missing_file(TailInputTest)
  * https://travis-ci.org/fluent/fluentd/jobs/195731891
* test_multiline_with_multiple_formats[flat](TailInputTest::multiline)
  * https://ci.appveyor.com/project/fluent/fluentd/build/2345/job/mgy36d6xqqlye4bt
* test_emit_with_read_lines_limit
  * https://travis-ci.org/fluent/fluentd/jobs/196492970

This shows `in_tail` potentially has a bug to handle file rotation.

**Comment by ashie** [comment]
After adding some more changes to in_tail plugin and its tests, recent days we don't see such failures.
So I close this issue.
We should update information about unstable tests.

**Comment by ashie** [comment]
For windows, I've found a bug in the tests:  #3767
