### ISSUE TITLE
in_forward ingests and saves buffered files larger than buffer_chunk_limit

### ISSUE THREAD

**Issue by ghTravis** [fluent/fluentd#1436]
Hi

I'm currently experiencing an issue where I have a cluster of aggregator td-agent servers ingesting logs from our entire fleet of development servers. This cluster of aggregators has a buffer_chunk_limit set to 4MB. The limit is due to an AWS Elasticsearch ingestion limitation of 10MB per request because of the size of the elasticsearch nodes. This isn't much of a problem, however I have had to configure all the development nodes that send to the aggregator cluster to also have a buffer chunk limit of 4MB. 

What I've found is that if the aggregator connection goes down and the development servers start buffering, if they are set to say 16MB and they regain connection, they will send the whole file to the aggregator and the aggregator will save that buffer file as whatever size was sent to it instead of splitting it up into chunks the size of its own chunk limit. This causes the elasticsearch connection from the aggregator to fail as td-agent will attempt to send the entire buffer file and it will get a response back from AWS Elasticsearch which is EntityTooLarge and/or BrokenPipe.

td-agent version: 2.3.4-0
operating system: ubuntu 14.04 LTS

**Comment by repeatedly** [comment]
> if they are set to say 16MB and they regain connection, they will send the whole file to the aggregator

Does it mean forwarder set 16MB buffer_chunk_limit by mistake and send it to aggregator?
Or forwarder set 4MB buffer_chun k_limit but send unexpected 16MB chunk to aggregator?
With v0.12, smaller retry_limit avoids lots of retry and send failed chunk to secondary.
With v0.14, we introduced splitting chunk feature so this problem should be resolved.

**Comment by ghTravis** [comment]
I suppose the forwarder could be mistakenly set to a value higher than the aggregator's chunk_limit value, sure. Basically the issue is that the aggregator stores chunks larger than its own chunk_limit value if it receives a buffer file that large.

If you're saying that this was fixed in v0.14 is there a config setting that I need to set to enable this? Because as far as I know I have the latest version and I still see this problem

**Comment by repeatedly** [comment]
> Because as far as I know I have the latest version and I still see this problem

That's weird. This features is available since v0.14.2.
https://github.com/fluent/fluentd/pull/1062
https://github.com/fluent/fluentd/pull/1062#issuecomment-238312636

**Comment by ghTravis** [comment]
Are you able to verify on your side that this isn't a regression issue? I have an aggregator server that has buffer files in /var/log/td-agent/buffer/ at 16MB when the chunk limit is set to 4MB

**Comment by repeatedly** [comment]
Ah wait. Do you updat fluentd inside td-agent 2.3.4?
If not, you use fluentd v0.12 serise and v0.12 don't have this splitting feature.

**Comment by ghTravis** [comment]
Interesting, I have not. I didn't realize there was a td-agent3 out. How do I update fluentd to 0.14.x inside td-agent v2.3.4?
