### ISSUE TITLE
Improve error message "pattern not match"

### ISSUE THREAD

**Issue by thokari** [fluent/fluentd#1444]
I am using fluentd / td-agent 0.12.31, installed from TreasureData-yum-repository.

I find it very hard to get something useful out of the "pattern not match" error message.
While it does repeat the log line, it does not state the pattern which it is matching against, leaving that - potentially difficult - part to the user.
I am currently dealing with many similarly, but not identically formatted log files in many different places.
It would be really helpful, if the entry in the `td-agent.log` also mentioned at least which `<source>`-section / tag is causing the problem.

**Comment by repeatedly** [comment]
Sorry for late reply.
Since v0.14, when you set `@id` in plugin configuration, it is logged.

- When `@id foo`

```
2017-02-16 08:32:50 +0900 [warn]: #0 [foo] pattern not match: "127.0.0.1 192.168.0.1 - [06/Nov/2015:20:47:52 +0900] \"GET / HTTP/1.1\" 200
 777 \"-\" \"Opera/12.0\""
```

Backport this feature to v0.12 is one idea.

**Comment by thokari** [comment]
Cool, thanks!
