### ISSUE TITLE
Installing td-agent without internet access

### ISSUE THREAD

**Issue by rodaan** [fluent/fluentd#1446]
Hi,

I'm trying to install td-agent but on a vm that cannot have an open connection to the internet so scp the td-agent rpm into it. I've tried installing it but it looks like other things are needed. Can you tell me what are the other rpm dependencies needed by td-agent to work because it continues to try to access the internet? Also I've examined the install script and am wondering if the GPG key is necessary for td-agent to run properly. If I add ".gem" files in the "/etc/td-agent/plugin" directory, will those plugins be installed automatically or do I need to restart the td-agent service? What are the mandatory fields needed in the "td-agent.conf" file?

- fluentd or td-agent version: 
td-agent-2.3.3-0.el7.x86_64.rpm

- Environment information, e.g. OS.:
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	CentOS
Description:	CentOS Linux release 7.0.1406 (Core) 
Release:	7.0.1406
Codename:	Core

**Comment by rodaan** [comment]
Also another question, how can I get more information as to why td-agent failed to startup? I have a fresh install and yet td-agent fails when I run "sudo /etc/init.d/td-agent start".

**Comment by repeatedly** [comment]
This is td-agent question, not fluentd. So closed.
