### ISSUE TITLE
fluentd creating buffer path as directory rather as file

### ISSUE THREAD

**Issue by ram2valar** [fluent/fluentd#1457]
Hi,

We are using fluentd version (0.14.11), in the config though we specified buffer_type as file its creating buffer_path as directory instead of file.

sample config:
buffer_type        file
buffer_path        /logs/td-agent/buffer/demo.nginx.access.loggly.buffer

Based on above config it has to create /logs/td-agent/buffer/demo.nginx.access.loggly.buffer as file rather its creating as directory.

[ec2-user@dr-demo-nvirginia-1b1 modules]$ ls -ld /logs/td-agent/buffer/*nginx*
drwxr-xr-x 2 root 6 Feb  9 15:20 /logs/td-agent/buffer/demo.nginx.access.loggly.buffer

It suppose to be file but its created as directory. We are using tdagent version as 2.3.4 and following are the version of the fluentd gems:

[ec2-user@dr-ms-qa-ogilvy-self-sms-nvirginia-1b1 modules]$ /opt/td-agent/embedded/bin/gem list | grep fluent
fluent-logger (0.6.2)
fluent-mixin-config-placeholders (0.4.0)
fluent-mixin-plaintextformatter (0.2.6)
fluent-mixin-rewrite-tag-name (0.1.0)
fluent-plugin-copy_ex (0.0.2)
fluent-plugin-elasticsearch (1.9.2, 1.7.0)
fluent-plugin-geoip (0.6.1)
fluent-plugin-grep (0.3.4)
fluent-plugin-kafka (0.5.0)
fluent-plugin-loggly (0.0.8)
fluent-plugin-parser (0.6.1)
fluent-plugin-record-reformer (0.8.2)
fluent-plugin-redis-store (0.1.1)
fluent-plugin-rewrite-tag-filter (1.5.5)
fluent-plugin-s3 (1.0.0.rc1)
fluent-plugin-td (0.10.29)
fluent-plugin-td-monitoring (0.2.2)
fluent-plugin-typecast (0.2.0)
fluent-plugin-webhdfs (0.4.2)
fluentd (0.14.11)
fluentd-ui (0.4.3)

has anyone faced such issue. This is occuring in centos.

Thanks,
Ram.

**Comment by repeatedly** [comment]
This is expected behaviour, not a bug.
