### ISSUE TITLE
Fluentd - convert standart syslog datetime format into YYYYmmdd and put in mysql

### ISSUE THREAD

**Issue by luciflus** [fluent/fluentd#1471]
1) fluentd - fluentd-0.12.31
2) config file
<source>
type syslog
format /^(?<datetime>[^ ]*\s*[^ ]* [^ ]*) (?<host>[^ ]*) (?<ident>[a-zA-Z0-9_\/\.\-]*)(?:\[(?<pid>[0-9]+)\])?(?:[^\:]*\:)? *(?<message>.*)$/
port 24226
bind 0.0.0.0
tag system
</source>

<match system.**>
@type mysql_bulk
host my_ip
port 33307
database fluentd
username user
password user_password
table logs
column_names date,message,host,ident
key_name  datetime,message,host,ident
flush_interval 10s      
</match>  

=====================================================
Hello, all

I am new in fluentd. I need take logs from rsyslog servers and put them in mysql table.
I have column's below:

date     - varchar - 20   - (but i need convert into integer and date format YYYYmmdd)
message  - varchar - 250
host     - varchar - 15
ident    - varchar - 15
==========================================================
Now i can put data in mysql table in format below:
datetime - 2017-02-15 14:15:22 
host     - host,
ident    - systemd,
message  - systemd-logind.service: Got notification message from PID 783 (WATCHDOG=1).

and it's working fine.
----------------------------------------------------------------------------------------------------

But i need parse or maybe convert to format below:
datetime - 20170215 
host     - host,
ident    - systemd,
message  - systemd-logind.service: Got notification message from PID 783 (WATCHDOG=1)

Could you help me please, how can i made this.
Thank you for your help.

**Comment by repeatedly** [comment]
Follow the guideline: https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md#got-a-question-or-problem
