### ISSUE TITLE
configuration: built-in placecholder for popular use cases

### ISSUE THREAD

**Issue by repeatedly** [fluent/fluentd#1473]
I'm now considering adding several built-in placeholders to ruby embedded code: http://docs.fluentd.org/v0.12/articles/config-file#embedded-ruby-code

- `"#{hostname}"` for `"#{Socket.gethostname}"`

`Socket.gethostname` seems verbose and it needs ruby knowledge a bit.
In `record_transformer`, we use `${hostname}` placeholder for it. So `"#{hostname}"` is much easier.

- `"#{worker_id}"` for `"#{ENV['SERVERENGINE_WORKER_ID'] || 0}"`

With built-in multiprocess feature, users sometimes need to specify worker id to avoid destination conflict, e.g. S3 path.
With multiprocess plugin, users write unique parameter in each child configuration. We should support such use cases.
`"#{ENV['SERVERENGINE_WORKER_ID'] || 0}"` is bit messy, so adding `"#{worker_id}"` is better.

For `worker_id`, I considered `${worker_id}` support in `extract_placeholders` but it conflicts with `worker_id` field of event record. In addition, `worker_id` is not dynamic in data pipeline after fluentd started, so `"#{worker_id}"` is enough for almost cases.

## NOTE: event tag support

`"#{tag}"` is out of scope because `"#{}"` is processed during configuration parsing phase in startup. So `"#{}"` can't touch event tag, time and record. Placeholder should be available value before configuration parsing.

Other popular cases?

**Comment by y-ken** [comment]
How about tag and tag_parts?

**Comment by repeatedly** [comment]
tag can't be used becase ruby embedded code is processed during configuration parsing phase.
It is done with `${tag}` and `extract_placeholders` combination.

**Comment by y-ken** [comment]
Oh, I got it that it processed in execute process.

In that case, It sounds nice to have short_hostname.
Because our all of servers has common suffix.
* full hostname: web01-aaa.example.com
* short hostname: web01-aaa
