### ISSUE TITLE
GSoC2017 / Monitoring Dashboard

### ISSUE THREAD

**Issue by edsiper** [fluent/fluentd#1475]
This issue belongs to a Google Summer of Code project idea.

## Project Goals

This project aims to implement a fully featured web-based dashboard for Fluentd internals. The expectation is that from a web interface we can see the behavior of the service at it different phases and resources consumption:

- input
- parser
- filtering
- buffering
- output

Despite some of these requirements can be achieved with specific plugins and third party services like Prometheus and Grafana, we aim to provide a built-in solution that can be used in environments where that is not an option.

The scope of the project will be discussed with students during the application period.

## Skills required

- Ruby
- API
- CSS
- Javascript

**Comment by nainanurag** [comment]
Hello Sir,
I am Anurag , a Compute Science Undergraduate from Indraprastha University, Delhi, India. I have worked in Web Development. 
I read about Fluentd, it's very interesting. I am interested to work in this project . Could you please guide with the proper resources to know more about the scope of this project.

Regards
Anurag

**Comment by edsiper** [comment]
hi @nainanurag 

to understand the scope of the project I would suggest you take the following roadmap:

- get familiar with "what problem Fluentd solves": presentations: 
  - [Build the Unified Logging Layer](https://www.youtube.com/watch?v=sIVGsQgMHIo)
  - [Logging for Containers](https://www.youtube.com/watch?v=395iaisdZEY)
- Understand the concept of Log Forwarder and Log Aggregators:
  - https://www.slideshare.net/edsiper/log-forwarding-at-scale
- Learn about how Fluentd solves logging 
- Learn about running applications at scale with Kubernetes

Once you get familiar with these concepts you will get a better idea about the real scope of the project and what are the required features to implement that will help to monitor Fluentd.

Feel free to ping us anytime on our Slack channel at [slack.fluentd.org](http://slack.fluentd.org)

**Comment by repeatedly** [comment]
This is for 2017. So closed.
