### ISSUE TITLE
fluentd 0.14.11 & 0.14.13 parser plugin 'suppress_parse_error_log' not used

### ISSUE THREAD

**Issue by fmax** [fluent/fluentd#1480]
fluentd 0.14.11 & 0.14.13
parser plugin 'suppress_parse_error_log' not used.

filter parser since parser is built in  core - no parser plugin needed any more
[warn]: parameter 'suppress_parse_error_log' in <filter project.nginx*> is not used.
so this results in lot's of unwanted log messages, because there are two filters for ngnix logs:
* one for parsing access log nginx regex
* one for parsing error log nginx regex

so when access log filter matches, error log filter writes to td-agent.log:
'error_class=Fluent::Plugin::Parser::ParserError error="pattern not match'
same for error log filter matches, access log filter filling up td-agent.log
but different filters are needed to get different prefix attribute injected for elasticsearch output.

related config part:
<filter project.nginx*>
  @type parser
  key_name log
  suppress_parse_error_log true
  format /^nginx-access-log-regex$/
  inject_key_prefix nginx.acc.
</filter>
<filter project.nginx*>
  @type parser
  key_name log
  suppress_parse_error_log true
  format /^nginx-error-log-regex$/
  inject_key_prefix nginx.err.
</filter>

OS: ubuntu 16 LTS docker container
package: td-agent                     3.0.0-0
gems - manually updated gem 'fluentd' to 0.14.13 :
/opt/td-agent/embedded/bin/gem list --local | egrep "action|active|rail|fluent"
actionmailer (4.2.8)
actionpack (4.2.8)
actionview (4.2.8)
activejob (4.2.8)
activemodel (4.2.8)
activerecord (4.2.8)
activesupport (4.2.8)
fluent-logger (0.6.2)
fluent-mixin-config-placeholders (0.4.0)
fluent-mixin-plaintextformatter (0.2.6)
fluent-plugin-concat (2.0.1)
fluent-plugin-elasticsearch (1.9.2)
fluent-plugin-kafka (0.5.0)
fluent-plugin-rewrite (0.1.0)
fluent-plugin-rewrite-tag-filter (1.5.5)
fluent-plugin-s3 (1.0.0.rc1)
fluent-plugin-td (0.10.29)
fluent-plugin-td-monitoring (0.2.2)
fluent-plugin-webhdfs (0.4.2)
fluentd (0.14.13)
fluentd-ui (0.4.3)
font-awesome-rails (4.7.0.1)
haml-rails (0.5.3)
jquery-rails (3.1.4)
rails (4.2.8)
rails-deprecated_sanitizer (1.0.3)
rails-dom-testing (2.0.2, 1.0.8)
rails-html-sanitizer (1.0.3)
railties (4.2.8)
sass-rails (4.0.5)
sprockets-rails (2.3.3)

**Comment by repeatedly** [comment]
Sorry, I don't understand what you mean.
Why do you share same tag for different filters? > `<filter project.nginx*>`

**Comment by fmax** [comment]
because logs comming from multiple docker nginx containers.
each nginx container has tag set <projectname>.nginx
each nginx container logs access & error log to stdout
each nginx container is started with logging driver fluentd

so input is forward and for my understanding it's the only way to differ between nginx access & error logs.
fluentd should process this loglines before output into elasticsearch and shown in kibana

is there any other way to differ between access & error logs comming from same source or handle with different tags / labels what ever?
ideas are welcome

**Comment by repeatedly** [comment]
Hmm... I see. Without `inject_key_prefix`, you can use https://github.com/repeatedly/fluent-plugin-multi-format-parser.
Re-add `suppress_parse_error_log` is acceptable for me.

**Comment by repeatedly** [comment]
@fmax Could you have a chance to write a patch for this?

**Comment by fmax** [comment]
sadly no - i couldn't write a patch - i'm technician but no developer or ruby expert

**Comment by repeatedly** [comment]
#1494 is merged
