### ISSUE TITLE
Bundler is not in dependencies

### ISSUE THREAD

**Issue by tagomoris** [fluent/fluentd#1481]
Fluentd's `--gemfile` option executes Fluentd itself via `bundler`, but Fluentd doesn't have any dependency about `bundler` gem. It makes that bare `fluentd --gemfile` command will fails always, without extra `fluent-gem install bundler` command.

(td-agent is configured to install bundler in its environment, though)

IMO it's better to add a runtime dependency for `bundler`, or update the error message to instruct to run `fluent-gem install bundler` here:
https://github.com/fluent/fluentd/blob/master/lib/fluent/command/bundler_injection.rb#L25

**Comment by kenhys** [comment]
This issue affects only ruby 2.5.x series nowadays because bundler is bundled with since ruby 2.6 or newer version.
ruby 2.5 will reach EOL (date: 2021-03-31)

**Comment by kenhys** [comment]
Here is the reproducible steps with docker run -it debian:buster:

```
apt install ruby ruby-dev libmsgpack-dev build-essential
gem install fluentd
# cat Gemfile
source 'https://rubygems.org'
gem "fluent-plugin-out-http"
fluentd --gemfile Gemfile
root@a8e30abbd396:/# fluentd --gemfile Gemfile
error: Gem::MissingSpecError
```
