### ISSUE TITLE
write ruby code in multiple lines

### ISSUE THREAD

**Issue by kswapd** [fluent/fluentd#1489]
Hi, I use fluentd and filter_record_transformer plugin in my loggging system, when I set enable_ruby and write some ruby code in filter, I found ruby code must be written in one line as belows:
```
<filter docker.after.process>
  @type record_transformer
  enable_ruby
  <record>
    "data1" "test"
    "data2" ${require 'json';require "open-uri";html_response = nil;uuid="uuid_123";env_id = "123";namespace="namespace_123";container_name="containername_123";if $g_exid==nil; $g_exid=Hash.new; end; uri='http://169.254.169.250/latest/containers';urienv='http://169.254.169.250/latest/self/host';html_res_env=nil;info_env=nil; ......}
 </record>
</filter>
``` 
If the code for field "data2" above is written to multiple lines， there will be errors when starting  fluentd.
As some reasons, I have to write hundreds of lines of ruby code with this plugin, is  there any way or plugins that can help me to write beautiful ruby code with lines and indent? thank you.

**Comment by repeatedly** [comment]
> As some reasons, I have to write hundreds of lines of ruby code with this plugin, is there any way or plugins that can help me to write beautiful ruby code with lines and indent? 

Wrap `"` in the parameter. double quoted string supports multilines.
BTW, record_transformer's ruby code is evaluated at each record.
So maybe, your "hundreds of lines of ruby code" makes fluentd too slower.

**Comment by repeatedly** [comment]
Next, please follow guideline: https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md#got-a-question-or-problem

**Comment by kswapd** [comment]
I know, thanks!

**Comment by hzy46** [comment]
Figured it out:

```
<filter test-fluentd>
  @type record_transformer
  enable_ruby
  <record>
    test "${\
      if record['message'].include? 'x'
        'objectx'
      elsif record['message'].include? 'y'
        'objecty'
      end}"
  </record>
</filter>
```

**Comment by arturgspb** [comment]
Maybe someone needs a sample code.
Multi-strings did not work for me, but I found an option to replace many checks with just begin/rescueю

This code parse jwt token and pack google cloud logging format:

 ```
<filter reform.**>
      @type record_transformer
      enable_ruby true
      auto_typecast true
      tag nginx
      remove_keys stream, method, path, response_size, code, agent, remote, host, referer, latency, x_forwarded_for, http_autorization #, log
      <record>
        userId ${ begin; JSON.parse(Base64.decode64(http_autorization.split(" ")[1].split(".")[1]))["sub"]; rescue; ''; end; }
        oauthClientId ${ begin; JSON.parse(Base64.decode64(http_autorization.split(" ")[1].split(".")[1]))["cid"]; rescue; ''; end; }
        httpRequest ${ {"requestMethod": record['method'], "requestUrl": record['path'], "responseSize": record['response_size'], "status": record['code'], "userAgent": record['agent'], "remoteIp": record['remote'], "referer": record['referer'], "latency": record['latency'] + "s" } }
      </record>
    </filter>
```

This code does not parse the token in the best way, but for logs this is enough for me.
