### ISSUE TITLE
not support rsyslog v8?

### ISSUE THREAD

**Issue by loveshell** [fluent/fluentd#1503]
rsyslogd.conf

local5.err action(type="omfwd" Target="x.x.x.x" Port="5555" Protocol="tcp" )

fluentd invalid message

configure is error?

**Comment by repeatedly** [comment]
I'm not familar with rsyslog so can't judge fluentd's in_syslog has a problem or not.
in_syslog works on many environment so in_syslog works well nomarl syslog protocol.
Please investigate which is the problem rsyslog or fluentd before open an issue.

And follow guideline: https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md
