### ISSUE TITLE
Benchmarked: UNIX domain input is slower than TCP loopback input

### ISSUE THREAD

**Issue by roniemartinez** [fluent/fluentd#1509]
- **td-agent 0.12.26**
- **CentOS release 6.5 (Final)**
- **Configuration**
```
<source>
    @type forward
    port 24224
</source>

<source>
    @type unix
    path /var/log/td-agent/fluent-logger-cpp.sock
</source>
```
- **BUG: Unix domain benchmark is much slower than TCP loopback input**. Our use case is to log locally using td-agent and since we want to have a faster logging speed we assumed that the solution is to use Unix domain socket instead of TCP loopback. In theory, this should work since there is no overhead but upon integration, the performance seems to get worse. We created benchmarks to show the results. Note: We used PackedForward Mode with 100 events in 10 runs, 100 iterations each. We wrote our own (efficient) logging library in C++ using [messagepack-c](https://github.com/msgpack/msgpack-c) and using [Forward-Protocol-Specification-v0](https://github.com/fluent/fluentd/wiki/Forward-Protocol-Specification-v0) as our reference.

**TCP Loopback:**
```
[ RUN      ] FluentLoggerTcpFixture.TCPPackedForwardMode (10 runs, 100 iterations per run)
[     DONE ] FluentLoggerTcpFixture.TCPPackedForwardMode (392.512802 ms)
[   RUNS   ]        Average time: 39251.280 us
                         Fastest: 29501.489 us (-9749.791 us / -24.839 %)
                         Slowest: 41400.547 us (+2149.267 us / +5.476 %)
                                  
             Average performance: 25.47688 runs/s
                Best performance: 33.89659 runs/s (+8.41972 runs/s / +33.04847 %)
               Worst performance: 24.15427 runs/s (-1.32261 runs/s / -5.19140 %)
[ITERATIONS]        Average time: 392.513 us
                         Fastest: 295.015 us (-97.498 us / -24.839 %)
                         Slowest: 414.005 us (+21.493 us / +5.476 %)
                                  
             Average performance: 2547.68760 iterations/s
                Best performance: 3389.65942 iterations/s (+841.97181 iterations/s / +33.04847 %)
               Worst performance: 2415.42702 iterations/s (-132.26058 iterations/s / -5.19140 %)
```

**Unix Domain:**
```
[ RUN      ] FluentLoggerUnixFixture.UnixPackedForwardMode (10 runs, 100 iterations per run)
[     DONE ] FluentLoggerUnixFixture.UnixPackedForwardMode (1322.271626 ms)
[   RUNS   ]        Average time: 132227.163 us
                         Fastest: 116241.940 us (-15985.223 us / -12.089 %)
                         Slowest: 140010.863 us (+7783.700 us / +5.887 %)
                                  
             Average performance: 7.56274 runs/s
                Best performance: 8.60275 runs/s (+1.04000 runs/s / +13.75168 %)
               Worst performance: 7.14230 runs/s (-0.42044 runs/s / -5.55935 %)
[ITERATIONS]        Average time: 1322.272 us
                         Fastest: 1162.419 us (-159.852 us / -12.089 %)
                         Slowest: 1400.109 us (+77.837 us / +5.887 %)
                                  
             Average performance: 756.27426 iterations/s
                Best performance: 860.27470 iterations/s (+104.00044 iterations/s / +13.75168 %)
               Worst performance: 714.23030 iterations/s (-42.04397 iterations/s / -5.55935 %)
```

**We tried to create a mock server listening on a Unix domain socket to show the best-case scenario:**
```
[ RUN      ] MockFluentLoggerUnixFixture.UnixPackedForwardMode (10 runs, 100 iterations per run)
[     DONE ] MockFluentLoggerUnixFixture.UnixPackedForwardMode (39.957743 ms)
[   RUNS   ]        Average time: 3995.774 us
                         Fastest: 3929.320 us (-66.454 us / -1.663 %)
                         Slowest: 4060.936 us (+65.162 us / +1.631 %)
                                  
             Average performance: 250.26439 runs/s
                Best performance: 254.49696 runs/s (+4.23258 runs/s / +1.69124 %)
               Worst performance: 246.24865 runs/s (-4.01574 runs/s / -1.60460 %)
[ITERATIONS]        Average time: 39.958 us
                         Fastest: 39.293 us (-0.665 us / -1.663 %)
                         Slowest: 40.609 us (+0.652 us / +1.631 %)
                                  
             Average performance: 25026.43856 iterations/s
                Best performance: 25449.69613 iterations/s (+423.25758 iterations/s / +1.69124 %)
               Worst performance: 24624.86481 iterations/s (-401.57375 iterations/s / -1.60460 %)
```

If anyone can replicate the issue, it will help this project and the users. Thanks!

**Comment by repeatedly** [comment]
I'm not sure your code , but `unix` is bit faster than `forward` on my Mac.

- fluent.conf

```
<source>
  @type forward
  port 24223
</source>

<source>
  @type unix
  path /path/to/fluentd_unix.sock
</source>

<match foo.**>
  @type flowcounter_simple
  unit second
</match>
```

fluent-logger-ruby code:

```rb
require 'fluent-logger'

# for forward
log = Fluent::Logger::FluentLogger.new(nil, :host=>'localhost', :port=>24223)
# for unix
#log = Fluent::Logger::FluentLogger.new(nil, :socket_path => '/Users/repeatedly/tmp/fluentd/run/fluentd_unix.sock')
loop {
  # use small record to reduce deserialization cost
  log.post("foo.test", {'key' => 'vvvvvvvvvvvvvvvvvvvvvvvvvvvvv'})
  sleep 0.0001
}
```

With above client:

- in_forward: flowcounter_simple shows `6800/sec`
- in_unix: flowcounter_simple shows `7000/sec`

How to calculate above benchmark result?

**Comment by Code-ReaQtor** [comment]
We only changed the _file descriptor_ from TCP to UNIX. 

From:
```c
fileDescriptor = socket(AF_INET, SOCK_STREAM, 0);
```

To:
```c
fileDescriptor = socket(AF_UNIX, SOCK_STREAM, 0);
```

The library will not see a change since you can use write() and read() functions on both file descriptors. I doubt that the huge difference in performance can be measured significantly with interpreted languages (message serialization can be slow).

We tested our client code with dummy TCP and UNIX servers that does nothing but to read the request from the client and the performance was, in fact, the "ideal performance".

**Comment by jcalvert** [comment]
@Code-ReaQtor We noticed similar performance characteristics in a pre-production environment. What we saw was that this only showed up when you had several processes writing to fluentd concurrently. 

The two confounding factors seem to be parallelism and payload size. For instance using 10 processes writing 100000 messages each with: 

```
require 'fluent-logger'
require 'benchmark'
require 'securerandom'

random_string = (0..200).map{ SecureRandom.hex }.join

pids = 10.times.map do
fork do
log = Fluent::Logger::FluentLogger.new(nil, :host=>'localhost', :port=>24223)
100_000.times do 
log.post('foo.test', {'key' => random_string})
end
end
end
pids.each do |pid|
Process.waitpid(pid)
end
```
I get `102379/s` for throughput.

but simply exchanging for a UNIX socket, I get `65523/s` for throughput. However, at a smaller message size (6432 bytes vs 352 bytes), the UNIX socket is faster.

**Comment by Code-ReaQtor** [comment]
@jcalvert Thanks a lot!

This just means that the receiving end (fluentd) is being "choked" or unable to process the raw speed of the UNIX socket. I guess TCP is the best option for now since smaller message size is not a good size for logging data (for our use case).
