### ISSUE TITLE
Length limitation of the input message ?

### ISSUE THREAD

**Issue by dmigous** [fluent/fluentd#1514]
- td-agent 0.12.31
- Debian (Linux abdb1e263f59 4.4.14-200.fc22.x86_64 #1 SMP Fri Jun 24 21:19:33 UTC 2016 x86_64 GNU/Linux)
- configuration please see in [td-agent.conf.txt](https://github.com/fluent/fluentd/files/861331/td-agent.conf.txt)

__Issue description:__

I have a long log from nginx in ltsv format via syslog
at FluentD it is accepted via syslog input then goes to filter parser and then to stdout log (for debug purspose, and the goal to send into influxdb) see [td-agent.conf.txt](https://github.com/fluent/fluentd/files/861331/td-agent.conf.txt)

so I mentioned some length limit or what... Please see [FluentD_log.txt](https://github.com/fluent/fluentd/files/861309/FluentD_log.txt) there are 2 lines
* line 1 is a log from nginx with one parameter commented (means log message is shorter in about 12 symbols)
* line 2 all params from nginx are sent and there is `null` in the end of the message

and no matter what param at nginx `log_format` I comment it make it work at FluentD side without `null` issue. So it isn't related to some particular parameter, it's value or name. I assume it is related to the length of my message.

How can I debug this issue?

__Files:__
[nginx_log.txt](https://github.com/fluent/fluentd/files/861307/nginx_log.txt)
[FluentD_log.txt](https://github.com/fluent/fluentd/files/861309/FluentD_log.txt)
[td-agent.conf.txt](https://github.com/fluent/fluentd/files/861331/td-agent.conf.txt)

**Comment by dmigous** [comment]
Found  about `message_length_limit`. At http://www.fluentd.org/blog/fluentd-v0.12.27-has-been-released
Works fine. Sorry for noise

**Comment by repeatedly** [comment]
Ah..., I just found we forgot to add this option.
I will add it.
