### ISSUE TITLE
having this error fluent/root_agent.rb:194:handle_emits_error: emit transaction failed: error_class=NoMethodError error="undefined method `has_key?' for #<String:0x000000025b1128>" tag="kubernetes.var.log.containers.test-2-zhrpr_project1_test-8cf58c9207eef6320076e1d5fcee36234844b5674544694f7052429e62dcda77.log"

### ISSUE THREAD

**Issue by ayElwany** [fluent/fluentd#1520]
facing this issue , it is not clear if it is Fluentd issue or the fluent-plugin-kubernetes_metadata_filter issue
FLUENTD_VERSION=0.12.32
fluent-plugin-kubernetes_metadata_filter:0.24.0
Openshift 3.4

**Comment by repeatedly** [comment]
It seems your input plugin emits string record.
You can check emitted event by using `filter_stdout`.

http://docs.fluentd.org/v0.12/articles/filter_stdout

**Comment by repeatedly** [comment]
No response
