### ISSUE TITLE
Loading Data To BigQuery From Past MySQl Tables, cant Build dynamic table  name with past days partitions

### ISSUE THREAD

**Issue by kpmbro** [fluent/fluentd#1525]
Hi ,

I am trying to move 3TB of data from MySql to Bigquery using FluentD agnet . i used to run this with the google streaming API but i think fluent can be much more useful.

So i want to upload the tables to Bigquery and build Daily partitions starting from 2016-01-01 . i have a field at each MySql row that holds the date : 
`[other_fields] = ....`
`[transaction_id] = 1000`
`[transaction_date] = '2016-01-01'`
`[other_fields] = ....`

so i created a fluentd filter record 
`<filter transaction_data>`
  `@type record_transformer`
  `enable_ruby true`
  `<record>`
   ` date ${record["transaction_date"][0..9].gsub("-", "")}`
  `</record>`
`</filter>`

I am trying to get the ${date} as a partition to the table
`<match transaction_data>`
`  @type bigquery`
`  num_threads 4`
`  flush_interval 30`
`  buffer_queue_limit 10240`
`  buffer_chunk_records_limit 300`
` auth_method json_key   # default`
` email XXXXXXX@developer.gserviceaccount.com`
` json_key XXXXXXX.json`
` # private_key_passphrase notasecret # default`

` project xxxxprojectxxxx`
` dataset xxx_table_xxx `

` fetch_schema false`
` auto_create_table true`
` table transaction_${date}`
` schema_path`
` /home/table_schema.json`
`</match>`

But while i am doing this , the td-agent status is : running but when i am trying to post to the fluentd object a Sql row i getting the following error at the log

`[error]: tabledata.insertAll API project_id="xxxxprojectxxxx" dataset="xxx_table_xxx" `
`table="table transaction_${date}" code=400 message="invalid: The destination table's partition `
`table transaction_${date} is outside the allowed bounds. You can only stream to partitions within `
`0 days in the past and 0 days in the future relative to the current date."`

for the current setup i dont need bigquery time partition as the there another query that knows ho to collect the data from different tables from bigquery but it would be better to use the bigquery time partition (not a must)

i will much appreciate your help with this issue as i am spending the last day trying to figure this out , Thanks !

**Comment by kpmbro** [comment]
I have also tried to change the BigQuery Method from insert to load with no success 

`<match transaction_data >`
`  @type bigquery`
`  method insert`
`...`
Same error as above
`<match transaction_data >`
`  @type bigquery`
`  method load`
`...`
Same error as above

**Comment by kpmbro** [comment]
In addition at the Log i now noticed another part of the bug , it seems that there is an error at the filter level :

`failed to expand %Q[#{record["transaction_date"][0..9].gsub("-", "")}] error_class=NoMethodError error="undefined method []' for nil:NilClass`

**Comment by repeatedly** [comment]
Please follow: https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md#got-a-question-or-problem

**Comment by kpmbro** [comment]
i will , what is the slack channel ?
