### ISSUE TITLE
Fluentd polling time setting

### ISSUE THREAD

**Issue by bdqnghi** [fluent/fluentd#1530]
I am about to use Fluentd as the log collector to monitor a lot of docker instances. On a server, there will be around a hundred of docker instances that running on it. I'm afraid that Fluentd will keep polling log data to the server, thus degrade our server performance. I would like to ask if there is some setting or configuration to support this problem, like just send the log data periodically, etc.

**Comment by repeatedly** [comment]
> there is some setting or configuration to support this problem, like just send the log data periodically, etc.

For input, it depends on plugin configuration.
For output, you can configure it via buffer related parameters, flush_interval/buffer_chunk_limit/etc.

Fluentd performance depends on traffic and plugin configurations.
Simpley reading and data forwarding don't consume lots of resources.

BTW, this is question, not issue. So closed: https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md#got-a-question-or-problem
