### ISSUE TITLE
Question on serving buffered files

### ISSUE THREAD

**Issue by kklemmicknvidia** [fluent/fluentd#1532]
Not an issues as much as a question..

fluentd writes output to chunked buffer files and depending on the volume of output and configuration can write to multiple buffers before flushing to the final destination file.

What is the purpose of these buffer files? i.e: Why not just write to the final destination? What are these buffers useful for?

Secondly, if I want to view the entire file, but it's split into buffers, what is the proper way of doing this? For example, I have an nginx file server set up to view these files (in my case logs), but since they're split up it's not clear to me how to serve them properly. My initial approach was to serve the final final if present, then use a shortcut to the buffer file if not (to avoid having to know the randomized id). The problem with this approach is that if both files exist or if there are multiple buffer files the served log will be incomplete until the buffers have all flushed. Concatenating them of course would be possible, but is it safe to do this by modification date in order to get the ordering right? 

I'm considering just turning off buffering in order to avoid this and simplify the problem, but I'm wondering if I'll run into other problems - so this is why I'm trying to understand what the purpose of doing things this way is.

Any information on best practices here or docs on this subject would be appreciated. I've looked around but haven't found anything on the subject.

I'm running td-agent version 0.12.29
Configuration is very basic:
```
<match docker.jobid.*>
  @type forest
  subtype file
  remove_prefix docker
  <template>
    path /var/log/joblogs/${tag}.*
    symlink_path /var/log/joblogs/${tag}.B.log
    append true
    format json
    include_time_key true
  </template>
</match>
```

This is running on ubuntu 14.04

Thanks in advance,
Kevin

**Comment by repeatedly** [comment]
Don't use question for issue.
See: https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md#got-a-question-or-problem

**Comment by kklemmicknvidia** [comment]
My apologies, will look into the mailing list.

**Comment by repeatedly** [comment]
np :)
