### ISSUE TITLE
The last matched chunk is missing in multiline input

### ISSUE THREAD

**Issue by eakarsu** [fluent/fluentd#1533]
I am using the latest mac release td_agent package. I have configured multiline input like below.
All works fine perfectly. But the latest multiline match is not emitted into output file from fluentd.
Why fluentd is not not sending latest multiline match?

<source>
     @type tail
     @id tail_input
     format multiline
   format_firstline ....
   format1 .....
  format2 ....
</source>

**Comment by repeatedly** [comment]
Please follow guideline first: https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md#got-a-question-or-problem
