### ISSUE TITLE
More rubyish way for Fluent::Plugin::Output#formatted_to_msgpack_binary

### ISSUE THREAD

**Issue by kenhys** [fluent/fluentd#1538]
This is suggestion about method name about Fluent::Plugin::Output#formated_to_msgpack_binary

- fluentd version:
  * fluentd 0.14.x or later.
- environment infomation:
   * OS independent
- Your problem explanation. If you have an error logs, write it together.

  * Expected method name
    Fluent::Plugin::Output#formatted_to_msgpack_binary?

  * Actual method name
    Fluent::Plugin::Output#formatted_to_msgpack_binary

Traditionally, the method which returns boolean result is named with `?` suffix. That is more rubyish way to do it and easy to understand the behavior of #formated_to_msgpack_binary. How about `alias`?

**Comment by repeatedly** [comment]
LGTM.
@tagomoris @mururu How about this?

**Comment by mururu** [comment]
LGTM
