### ISSUE TITLE
server_create in server plugin helper doesn't provide on_connect callback customize feature

### ISSUE THREAD

**Issue by kou** [fluent/fluentd#1551]
- fluentd or td-agent version: 0.14.14
- Environment information, e.g. OS: Debian GNU/Linux sid
- Your configuration: https://github.com/groonga/fluent-plugin-groonga/blob/master/sample/http.conf
- Your problem explanation. If you have an error logs, write it together.

I'm trying rewriting [fluent-plugin-groonga](https://github.com/groonga/fluent-plugin-groonga) with 0.14 API.

fluent-plugin-groonga's input plugin creates a TCP server and it uses `on_connect` hook to initialize per connection state: https://github.com/groonga/fluent-plugin-groonga/blob/26fba85553a8fefc0d0ea844ee461f0c7fb947a1/lib/fluent/plugin/in_groonga.rb#L210-L221

```ruby
          def on_connect
            @repeater = @input.create_repeater(self)
            @repeater.on_connect_failed do
              @input.log.error("[input][groonga][connect][error] " +
                               "failed to connect to Groonga:",
                               :real_host => @input.real_host,
                               :real_port => @input.real_port)
              close
            end
            @request_handler = RequestHandler.new(@input, @repeater)
            @response_handler = ResponseHandler.new(self, @input)
          end
```

Fluentd 0.14 provides server plugin helper to create a TCP server in plugin. It provides [`#server_create`](https://github.com/fluent/fluentd/blob/master/lib/fluent/plugin_helper/server.rb#L122-L186) for easy to write a plugin.
It just provides `on_read` callback customize feature but doesn't provide `on_connect` callback customize feature. It always does `conn.data(&callback)`: https://github.com/fluent/fluentd/blob/master/lib/fluent/plugin_helper/server.rb#L155

Should we use low level APIs such as `#server_create_for_tcp_connection` instead of `#server_create` convenient API?

**Comment by kou** [comment]
Ah, should we use `#server_create_connection` when we want to custom `on_connect` callback?

**Comment by repeatedly** [comment]
Yes. See `in_forward` for example.

**Comment by kou** [comment]
Thanks!
