### ISSUE TITLE
Fluentd binary input from logrotation/compression strategy and crashes

### ISSUE THREAD

**Issue by boeboe** [fluent/fluentd#1561]
Hi all,

We are using fluentd as log forwarder in an Kubernetes cluster. One of the files we forward to ElasticSearch is the audit.log from Kubernetes, containing K8S authentication logs from the API Server. On this audit.log file, log rotation is configured.

fluentd.conf snippet:

	<source>
	  @type tail
	  format audit
	  path /var/log/kubernetes/audit.log
	  exclude_path ["/var/log/kubernetes/*.gz", "/var/log/kubernetes/*.zip"]
	  pos_file /var/log/es-audit.log.pos
	  tag audit
	</source>

Log rotation snippet:

	{{ kubeletLogDir }}/audit.log {
	  compress
	  daily
	  rotate 5
	  copytruncate
	  olddir {{ kubeletLogDir }}/old
	}

	{{ kubeletLogDir }}/audit-*.log {
	  compress
	  daily
	  rotate 5
	  olddir {{ kubeletLogDir }}/old
	}

The log rotation happen over night and we see that the nodes containing this audit.log (the master nodes of our kubernetes cluster), go in _overdrive_.

The reason seems that fluentd (enabled through a daemonset on kubernetes, with volume mounts to the hosts systems) picks up binary input (assumably from the compression):

	2017-05-09 01:24:40 +0000 [warn]: #0 retry succeeded. chunk_id="54f0d37f2b3cbf90dfc957fa319eaf9d"
	2017-05-09 01:26:01 +0000 [info]: #0 detected rotation of /var/log/kubernetes/audit.log
	2017-05-09 01:26:01 +0000 [info]: #0 following tail of /var/log/kubernetes/audit.log
	2017-05-09 01:26:04 +0000 [warn]: #0 pattern not match: "\x00\x00\x00\x00\x00\x00\x00\x00\x00...

I have been looking into extra configuration parameters within fluentd (_rotate_wait_) , but cannot pin-point the problem... is this a log rotation compatibility issues or a fluentd misconfiguration w.r.t. this use case?

Best regards,
Bart

**Comment by repeatedly** [comment]
I don't know the detailed behaviour of all logrotate, but how about removing copytruncate?

**Comment by boeboe** [comment]
Hi @repeatedly 

Closing this issue since it has been solved in the meanwhile and I forgot to update this issue. The cause was double rotation (once by k8s, once by log-rotate daemon)...

BR,
Bart

**Comment by repeatedly** [comment]
I see. Thanks for the update :)
