### ISSUE TITLE
does fluentd in_tail plugin support date-formated path?

### ISSUE THREAD

**Issue by jeremywu0127** [fluent/fluentd#1563]
I use the `in_tail` plugin to watch the log file, while the log file path is generated in date-formated like `/data/logs/nginx/2017-05-10/2017-05-10-15/xxx.log`, so I wonder if `fluentd` support   date-formated path in `in_tail` plugin like the following conf ?
```
 <source>
  @type tail
  path /data/logs/nginx/yyyy-mm/yyyy-mm-hh/access.log
  pos_file /tmp/access.log.pos
  tag nginx.access
  format none
  time_format %d/%b/%Y:%H:%M:%S %z
</source>
```

**Comment by repeatedly** [comment]
http://docs.fluentd.org/v0.12/articles/in_tail#path-required
