### ISSUE TITLE
does filter_parser support multi key_name?

### ISSUE THREAD

**Issue by jeremywu0127** [fluent/fluentd#1566]
as mentioned in  [doc](http://docs.fluentd.org/v0.12/articles/filter_parser), `filter_parser` can parse specified field in the event record, with the parameter `reserve_data true`, it keeps original data like:
```
# input data:  {"key":"value","log":"{\"user\":1,\"num\":2}"}
# output data: {"key":"value","log":"{\"user\":1,\"num\":2}","user":1,"num":2}
```
with `reserve_data false`, it looks like
```
# input data:  {"key":"value","log":"{\"user\":1,\"num\":2}"}
# output data: {"user":1,"num":2}
```
but I want to keep the `key` field  like the following:
```
# input data:  {"key":"value","log":"{\"user\":1,\"num\":2}"}
# output data: {"key":"value","user":1,"num":2}
```
how can I achieve this ? set the parameter like `key_name key,log` or any other ways ?

**Comment by repeatedly** [comment]
Use record_transformer to remove keys after `parser` filter.

**Comment by jeremywu0127** [comment]
it works when using `remove_keys` in `filter_record_transformer`

**Comment by repeatedly** [comment]
Next, please follow guideline showed in issue submitting page: https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md

**Comment by jeremywu0127** [comment]
ok, I'll obey that!
