### ISSUE TITLE
[Filter-Plugin Parser] Allow to preserve only part of the original record

### ISSUE THREAD

**Issue by martin21** [fluent/fluentd#1567]
Debian Stretch, Fluentd 0.14.15, Fluent Bit 0.11.4

As described in issue fluent/fluent-bit#261 I tried to use Fluent Bit to transfer Apache logs. I used ParserFilter plugin to parse Apache logs, as it seems that Fluent Bit is not yet able to do it.

Before that I let Fluentd add the hostname of the logsource into the `logsource` field (using this name to avoid a name clash with "host" field that Format apache seems uses for client host name). The filter removes that field again.

I know I could use `reserve_data yes`, but it would keep the complete old record including the complete log message which Fluent Bit stored in `log` field. Thus it would basically duplicate the amount of data saves.

I think an option like `reserve_fields logsource,otherimportantfield` would solve this neatly.

**Comment by repeatedly** [comment]
It seems good. Patches are welcome :)

**Comment by kenhys** [comment]
v0.12 is not maintained anymore, I'll close it.
