### ISSUE TITLE
Fluentd doesn't resume processing buffered chunks after a restart

### ISSUE THREAD

**Issue by soylent** [fluent/fluentd#1573]
I mentioned this problem some time ago in the chat (https://fluent-all.slack.com/archives/C0CTT63EE/p1494620941193222).

After some investigation I found out that Fluentd plugins inheriting from `BufferedOutput` store buffer chunks in dotfiles if `buffer_path` has no prefix before `*`, e.g. `buffer_path /var/log/td-agent/buffer/*.buffer`. `Dir.glob` ignores such files by default, please see https://github.com/fluent/fluentd/blob/v0.12.35/lib/fluent/plugin/buf_file.rb#L141.

It looks like buffer chunks should use `tag` as a prefix instead of an empty string, please see
https://github.com/fluent/fluentd/blob/v0.12.35/lib/fluent/output.rb#L267

The following configuration reproduces the issue:

```
<match foo.bar.*>
  @type exec_filter
  command cat
  buffer_path /var/log/td-agent/buffer/*.buffer
  buffer_type file
  tag filtered.exec
  in_format json
  out_format json
</match>
```

Fluentd stores buffer chunks in dotfiles in this case:

```
$ ls -la /var/log/td-agent/buffer/

drwxr-xr-x 2 td-agent td-agent 4096 May 15 14:28 .
drwxr-xr-x 8 td-agent td-agent 4096 May 12 14:39 ..
-rw-r--r-- 1 td-agent td-agent   14 May 15 14:28 .q54f90dcb21a14ace.buffer
```

fluentd 0.12.35
CentOS 7

**Comment by repeatedly** [comment]
Hm. Adding validation is better to avoid this problem.
Log message is like "buffer_path configuration generates no prefix file and it is not allowed. Add prefix before '*'"

**Comment by kenhys** [comment]
v0.12 is not maintained anymore, I'll close it.
