### ISSUE TITLE
document the `reserve_time` parameter

### ISSUE THREAD

**Issue by slang800** [fluent/fluentd#1591]
`reserve_time` is a configuration parameter used in a [couple places in the codebase](https://github.com/fluent/fluentd/search?utf8=%E2%9C%93&q=reserve_time&type=), but I can't find it in the documentation. It's not a particularly confusing parameter, but when I was looking for something to prevent the time field from being overwritten after using `rewrite_tag_filter`, I couldn't find it in the parser docs & had to dig for it in the codebase.

**Comment by repeatedly** [comment]
This is fluentd repository, not fluentd-docs.
Please use fluentd-docs for documentation issue.
