### ISSUE TITLE
Upgraded td-agent now errors on previously-working td-agent.conf

### ISSUE THREAD

**Issue by macavity23** [fluent/fluentd#1604]
td-agent 2.3.5 on ubuntu 16.04.2

Fails to startup with the following error:

> error_class=Fluent::ConfigError error="Invalid regexp '': No named captures"

The offending section seems to be the following:

```
  <filter **>
    @type parser
    key_name log
    format multiline
    format_firstline /^\d{4}-\d{2}-\d{2}/
    format1 /^(?<entry_time>\S+) (?<level>\w+) (?<message>.*)$/
    reserve_data true
  </filter>
```
 
If I remove the multiline and replace the above section with the following, it starts up fine (but now I lose my multiline capture):

```
  <filter **>
    @type parser
    key_name log
    format /^(?<entry_time>\S+) (?<level>\w+) (?<message>.*)$/
    reserve_data true
  </filter>
```

So some kind of issue with the multiline parsing. But what "regexp ''" is it talking about?

**Comment by repeatedly** [comment]
This is not td-agent upgrade issue.
You update fluentd to v0.14 and it is the cause.
See http://docs.fluentd.org/v0.12/articles/plugin-management#plugin-version-management

**Comment by repeatedly** [comment]
BTW, does your code work before?
`filter_parser` doesn't support multiline format correctly...

**Comment by macavity23** [comment]
Yes, it is working fine on td-agent 2.3.3-0 on ubuntu 14.04. Not sure how to get the fluentd version out of td-agent, we installed from apt.

**Comment by repeatedly** [comment]
> Yes, it is working fine on td-agent 2.3.3-0 on ubuntu 14.04.

That's weird. filter_parser doesn't have the code for `format_firstline` :p
So its parameter is ignored...
https://github.com/fluent/fluentd/blob/v0.12/lib/fluent/plugin/filter_parser.rb

**Comment by macavity23** [comment]
Ok, the working instance has fluentd 0.14.8 - at least I assume that's what the output of 'td-agent --version' means :)

**Comment by macavity23** [comment]
OK that is weird. I'm definitely getting multiline log entries... I'll try taking out the multiline from that rule and see if I still get them.

**Comment by repeatedly** [comment]
fluentd v0.14 has a compatibility layer for v0.12 configuration.
Almost v0.12 configuration works without error.
But its compatibility layer can't handle several cases and multiline parameter is one case.
Because multiline parameters are not fixed and automatic convert is hard.

**Comment by repeatedly** [comment]
> OK that is weird. I'm definitely getting multiline log entries.

Maybe, your log field is already multilined.

**Comment by repeatedly** [comment]
Ah, I see. `multiline` parser uses multiline mode regexp so `.` matches `\n`.
This is why `format multiline` works with your logs.
Non multiline parsers uses normal regexp so `.` doesn't match `\n`.

**Comment by repeatedly** [comment]
So with `filter_parser`, your configuration without `format_firstline` should work.

**Comment by macavity23** [comment]
Thanks for your help! However I get the same 'no named captures' error without `format_firstline`.

**Comment by repeatedly** [comment]
Do you use v0.14 syntax?

**Comment by macavity23** [comment]
This is using the config as above, but without format_firstline. I'm afraid it's not at all clear to me what v0.14 syntax is, and what other syntaxen I might be using.

**Comment by repeatedly** [comment]
I said, if you use v0.14, above configuration doesn't work because v0.12 multiline configuration can't be converted into v0.14 automatically. I refer the link to filter_parser and it shows v0.14 syntax.
In short:

- v0.12 multiline configuration doesn't work with fluentd v0.14.
- v0.14 multiline configuration doesn't work with fluentd v0.12.
- You need to write proper configuration for multiline parameters in each version.

I tested your configuration without `format_firstline` with fluentd v0.12 and it worked:

```
2017-06-28 08:31:11 +0900 [info]: reading config file path="test.conf"
2017-06-28 08:31:11 +0900 [info]: starting fluentd-0.12.37
2017-06-28 08:31:11 +0900 [info]: gem 'fluent-plugin-beats' version '0.1.2'
2017-06-28 08:31:11 +0900 [info]: gem 'fluent-plugin-elasticsearch' version '1.9.5'
2017-06-28 08:31:11 +0900 [info]: gem 'fluent-plugin-kafka' version '0.4.1'
2017-06-28 08:31:11 +0900 [info]: gem 'fluent-plugin-record-modifier' version '0.5.0'
2017-06-28 08:31:11 +0900 [info]: gem 'fluent-plugin-record-reformer' version '0.9.0'
2017-06-28 08:31:11 +0900 [info]: gem 'fluent-plugin-s3' version '0.8.2'
2017-06-28 08:31:11 +0900 [info]: gem 'fluent-plugin-secure-forward' version '0.4.4'
2017-06-28 08:31:11 +0900 [info]: gem 'fluentd' version '0.12.35'
2017-06-28 08:31:11 +0900 [info]: adding filter pattern="**" type="parser"
2017-06-28 08:31:11 +0900 [info]: using configuration file: <ROOT>
  <filter **>
    @type parser
    key_name log
    format multiline
    format1 /^(?<entry_time>\S+) (?<level>\w+) (?<message>.*)$/
    reserve_data true
  </filter>
</ROOT>
^C2017-06-28 08:31:12 +0900 [info]: shutting down fluentd
2017-06-28 08:31:12 +0900 [info]: shutting down filter type="parser" plugin_id="object:3fff750d6e5c"
2017-06-28 08:31:12 +0900 [info]: process finished code=0
```

**Comment by repeatedly** [comment]
More example is on https://github.com/repeatedly/fluent-plugin-multi-format-parser#configuration
