### ISSUE TITLE
Fluentd crashes when reading non-ascii char inside comment of config file

### ISSUE THREAD

**Issue by gheon** [fluent/fluentd#1606]
- fluentd or td-agent version: v0.12.36-debian
- environment information: Docker container inside Kubernetes cluster
- configuration: Docker image fluent/fluentd:v0.12.36-debian

When fluentd starts and reads its config file (in that case named 'fluent.conf'), it will crashes if some non-ascii characters are found inside comments. For instance (code snippet, where � is a non-ascii char):

```
[...]
    #�The source we want are the logs from the pods running inside the cluster.
    <source>
      type tail
      path /var/log/containers/proactive-*.log
      pos_file /mnt/fluentd-docker.pos
      time_format %Y-%m-%dT%H:%M:%S.%NZ
      tag kubernetes.*
      format json
      read_from_head true
    </source>
[...]
```
will make fluentd crash with the following exception:

```2017-06-23 13:15:16 +0000 [info]: reading config file path="/fluentd/etc/fluent.conf"
/var/lib/gems/2.3.0/gems/fluentd-0.12.36/lib/fluent/config/basic_parser.rb:56:in `skip': invalid byte sequence in US-ASCII (ArgumentError)
	from /var/lib/gems/2.3.0/gems/fluentd-0.12.36/lib/fluent/config/basic_parser.rb:56:in `skip'
	from /var/lib/gems/2.3.0/gems/fluentd-0.12.36/lib/fluent/config/basic_parser.rb:84:in `spacing'
	from /var/lib/gems/2.3.0/gems/fluentd-0.12.36/lib/fluent/config/v1_parser.rb:60:in `parse_element'
	from /var/lib/gems/2.3.0/gems/fluentd-0.12.36/lib/fluent/config/v1_parser.rb:43:in `parse!'
	from /var/lib/gems/2.3.0/gems/fluentd-0.12.36/lib/fluent/config/v1_parser.rb:33:in `parse'
	from /var/lib/gems/2.3.0/gems/fluentd-0.12.36/lib/fluent/config.rb:30:in `parse'
	from /var/lib/gems/2.3.0/gems/fluentd-0.12.36/lib/fluent/supervisor.rb:480:in `read_config'
	from /var/lib/gems/2.3.0/gems/fluentd-0.12.36/lib/fluent/supervisor.rb:144:in `start'
	from /var/lib/gems/2.3.0/gems/fluentd-0.12.36/lib/fluent/command/fluentd.rb:173:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /var/lib/gems/2.3.0/gems/fluentd-0.12.36/bin/fluentd:5:in `<top (required)>'
	from /usr/local/bin/fluentd:22:in `load'
	from /usr/local/bin/fluentd:22:in `<main>'
```

For sure, it's a minor 'bug' since it is quite unlikely that non-ascii chars are left inside the .conf file. However, it would be better if the parsing does not occur on the comment lines.

**Comment by repeatedly** [comment]
Thanks for the report.
We will check our parser.

**Comment by gheon** [comment]
Thanks for your tool, and good luck.

On Wed, Jun 28, 2017 at 2:33 PM, Masahiro Nakagawa <notifications@github.com

**Comment by repeatedly** [comment]
Ah okay. If the environment is LANG=C, this problem happen.

**Comment by Kuckkuck** [comment]
The same is happing for me with fluent 0.14.17/0.14.18 and US-ASCII with the fluent-plugin-grok-parser plugin, which is reading the grok-patterns, where month has the german character "ä". This was working with 0.14.16 with the same plugin version for fluent-plugin-grok-parser 2.3.1. I am using an Ubuntu container, where I have just changed the version number for fluentd and now it is crashing with: block in add_patterns_from_file': invalid byte sequence in US-ASCII (ArgumentError)
MONTH \b(?:[Jj]an(?:uary|uar)?|[Ff]eb(?:ruary|ruar)?|[Mm](?:a|ä .....
my LANG is not set.

Thanks a lot

**Comment by repeatedly** [comment]
@Kuckkuck Maybe, the problem is different. Please open an issue for grok-parser repository.
