### ISSUE TITLE
Please add resolve_hostname parameter for in_syslog plugin

### ISSUE THREAD

**Issue by jhaohai** [fluent/fluentd#1614]
Please add resolve_hostname parameter for in_syslog plugin , like what in_forward does.
When I enable include_source_host, fluentd auto lookup the hostname. But sometimes we do not need it, we just need IP address.
Thanks

**Comment by repeatedly** [comment]
For v0.12, right?

**Comment by jhaohai** [comment]
Yes. We are using fluentd 0.12.36 currently

**Comment by cosmo0920** [comment]
I've sent a patch: https://github.com/fluent/fluentd/pull/1615
Could you try this?

**Comment by jhaohai** [comment]
Thanks a lot, that works. @cosmo0920
