### ISSUE TITLE
Stable 0.12.x gem not installing in Ruby > 2.0.0

### ISSUE THREAD

**Issue by reidrac** [fluent/fluentd#1619]
fluentd 0.12.37 (stable) gem won't install in Ruby > 2.0.0 because it requires string-scrub that is only available (and required) for Ruby <= 2.0.0.

I believe this was broken by 91bf6821fc90e339479711e2fd7dfa03a26ccba8 ; it should check that string doesn't have scrub method before adding the requirement.

Also fuentd.org website says stable version is 0.12.36, but a 0.12.37 gem is available (not tagged in GH!).

**Comment by reidrac** [comment]
Now thinking about it I'm not sure if 0.12.x will work on 2.1, then these may need fixing:

- https://rubygems.org/gems/fluentd/versions/0.12.37
- http://docs.fluentd.org/v0.12/articles/install-by-gem

Both cases say Ruby >= 1.9.0.

Thanks!

**Comment by repeatedly** [comment]
string-scrub dependency should not be the problem.

```
% gem install fluentd --no-document -v 0.12.37
Fetching: string-scrub-0.0.5.gem (100%)
Building native extensions.  This could take a while...
Successfully installed string-scrub-0.0.5
Fetching: fluentd-0.12.37.gem (100%)
Successfully installed fluentd-0.12.37
2 gems installed
% ruby --version
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin15]
```

Maybe, your are something wrong.

> Also fuentd.org website says stable version is 0.12.36, but a 0.12.37 gem is available (not tagged in GH!).

Ah, I forgot to update this. Will update soon.

**Comment by reidrac** [comment]
string-scrub doesn't install here with Ruby 2.1; for some reason. Because of that fluend gem won't install.

I'll investigate further, thanks.

**Comment by repeatedly** [comment]
Maybe, you install latest version but fluentd gem doesn't depend on latest.

**Comment by reidrac** [comment]
Good point; I'll close this one for now.

Thanks for your help!
