### ISSUE TITLE
specify content-type header in output?

### ISSUE THREAD

**Issue by alexcurtin** [fluent/fluentd#1620]
I am running the latest fluentd image from google to send logs to elastic search and elastic search is replying with a ton of these logs:

[o.e.d.r.RestController ] Content type detection for rest requests is deprecated. Specify the content type using the [Content-Type] header.

Steps to reproduce:

Spin up an EFK stack with latest googles fluentd and elastic search 5.4.2, let the ES cluster boot and you will see the log [o.e.d.r.RestController ] Content type detection for rest requests is deprecated. Specify the content type using the [Content-Type] header.

Is this because of how the latest FluentD is shipping logs off to elastic search?

Provide logs (if relevant):

[o.e.d.r.RestController ] Content type detection for rest requests is deprecated. Specify the content type using the [Content-Type] header.

How can I specify the content-type header in the output of fluentd?

**Comment by repeatedly** [comment]
This is fluent-plugin-elasticsearch issue, not fluentd.
Closed.
