### ISSUE TITLE
Trimming long lines

### ISSUE THREAD

**Issue by datawrangl3r** [fluent/fluentd#1634]
I know that this issue has been closed.. But, it would be really helpful if there are any updates on this.

**Comment by repeatedly** [comment]
What does this issue mean?

**Comment by datawrangl3r** [comment]
This is just a duplicate of https://github.com/fluent/fluentd/issues/1318. 
While parsing a log containing a really long line, td-agent fails to match the pattern and the log delivery is halted.
The problem is weird, as the service was still running.

**Comment by datawrangl3r** [comment]
@repeatedly, I am still facing the issue. can you please explain me why this is happening or are there any options to explore, in order to trim the long lines? I am currently using, td-agent 0.12.35

**Comment by repeatedly** [comment]
> td-agent fails to match the pattern and the log delivery is halted.

Maybe, your regexp doesn't match long line.
If so, It seems not fluentd bug.
If you investigate your problem and if it is fluentd bug, please reopen this issue.

**Comment by datawrangl3r** [comment]
It can't be possible.. as, I have limited my text search. 
I've highlighted it below:
format /\[(?<timestamp>.*)\] lumen\.(?<severity>.*)\: **(?<message>.{,100})**/

**Comment by datawrangl3r** [comment]
Even if the pattern doesn't match, the next log line should be processed, right?

**Comment by repeatedly** [comment]
> Even if the pattern doesn't match, the next log line should be processed, right?

Yes. Try it first :)

**Comment by datawrangl3r** [comment]
Been there.. Done that.. :( Still facing the same issue!!!

**Comment by repeatedly** [comment]
I'm not sure the actual your issue because you don't write detailed information.
But if the fluentd log says "pattern not match", it means your regexp doesn't match your logs.

**Comment by datawrangl3r** [comment]
@repeatedly, the reason why td-agent was terminated was due to the line in the logfile.
The stack-trace had ad long line and was about 16MB in size. The pattern didn't match and td-agent stopped unexpectedly. Fixed the trace in the code, and now, td-agent is up and running.
Thanks for the help :) :+1:
