### ISSUE TITLE
Allow to customize time format in Fluentd's logs.

### ISSUE THREAD

**Issue by vvk** [fluent/fluentd#1640]
Currently time format in Fluentd logs [is hardcoded](https://github.com/fluent/fluentd/blob/master/lib/fluent/log.rb#L99) as `%Y-%m-%d %H:%M:%S %z `.
It should be customizable in Fluentd's configuration to easily apply necessary unified format in a solution which uses Fluentd.
The customization is required to provide painless parsing of Fluentd's for logs analyzing systems.

For example, it may be necessary to use [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) as time format.

**Comment by repeatedly** [comment]
It seems good idea.
I remember somone want to change log format to json, so adding more log related parameters is good like below.

```
<system>
  <log>
    format default # or json
    time_format default # or %iso8601
  </log>
</system>
```

**Comment by repeatedly** [comment]
Patch: https://github.com/fluent/fluentd/pull/1644
