### ISSUE TITLE
td-agent package leaves stale "dpkg-statoverride" setting

### ISSUE THREAD

**Issue by candlerb** [fluent/fluentd#1646]
td-agent package installs a dpkg-statoverride, but doesn't remove it on uninstallation.  This means that if you uninstall the package and remove `/var/log/td-agent` your system gets into a broken state.

To replicate, on fresh ubuntu 16.04:

~~~
# curl -L https://toolbelt.treasuredata.com/sh/install-ubuntu-xenial-td-agent2.sh | sh
...
# dpkg-query -l td-agent
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                    Version          Architecture     Description
+++-=======================-================-================-====================================================
ii  td-agent                2.3.5-0          amd64            Treasure Agent: A data collector for Treasure Data
# apt-get remove --purge td-agent
# rm -rf /var/log/td-agent
# dpkg-statoverride --list
root crontab 2755 /usr/bin/crontab
root mlocate 2755 /usr/bin/mlocate
td-agent td-agent 755 /var/log/td-agent    <<<<< NOTE
root messagebus 4754 /usr/lib/dbus-1.0/dbus-daemon-launch-helper
~~~

Then subsequent package installs/updates can give errors about non-existent file and abort.

The fix, when you know how, is fairly easy:

~~~
dpkg-statoverride --remove /var/log/td-agent
~~~

But I think the package uninstallation should do this automatically.

(Actually, I see no particular reason why the package needs to do statoverride in the first place.  Most packages are able to install directories with the correct permissions; statoverride is there for *users* who want to choose different permissions than those which were in the package)

**Comment by repeatedly** [comment]
This is fluentd repository, not td-agent repository.
Don't open td-agent specific issue on this repository.

**Comment by candlerb** [comment]
Moved now.

The reason I posted here is that https://www.fluentd.org/download provides td-agent packages for download, and https://www.fluentd.org/community points only to the fluentd issue tracker.

Therefore it might be helpful to point to the treasure-data repo on the community page.

**Comment by repeatedly** [comment]
Hmm... I see.

github shows https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md in the "New issue" page and users notice the right place.
