### ISSUE TITLE
td-agent needs restart if it loses contact with server

### ISSUE THREAD

**Issue by luisbrandao** [fluent/fluentd#1653]
I might beem doing things wrong, but if the client loses contact with our main server, it stops sending logs forever. Only a manual restart can fix this.
This is supposed to happen? we cant restart all agents everytime we need a maintenance on the log server.

```
[root@stagev2-rest td-agent]# cat /etc/td-agent/conf.d/30-match-logs.conf 
<match graylog2.*>
  type copy
  <store>
    flush_interval 2s
    num_threads 2
	buffer_type file
	retry_wait 15s
    buffer_path /var/log/td-agent/td-agent.*.buffer
    type gelf
    protocol tcp
    host -omitted-
    port 12202
  </store>
  <store>
    type stdout
  </store>
</match>
```

**Comment by repeatedly** [comment]
It seems gelf plugin issue.
Fluentd itself doesn't tuch connection inside plugins.

**Comment by cosmo0920** [comment]
I checked gelf plugin.
It does not provide to recover connection way when failing to connect server.
see: https://github.com/emsearcy/fluent-plugin-gelf/blob/master/lib/fluent/plugin/out_gelf.rb#L114

Could you report this issue in [fluent-plugin-gelf](https://github.com/emsearcy/fluent-plugin-gelf)?
