### ISSUE TITLE
fluentd splits log message

### ISSUE THREAD

**Issue by ymatsiuk** [fluent/fluentd#1669]
The following scenario has been tested on `v0.12` and `v0.14` images built from official [fluentd-docker-image](https://github.com/fluent/fluentd-docker-image) alpine based. Dockerfile was modified to include elasticsearch plugin (for details please check below)

**Description**: 
fluentd splits docker log message into chunks when pure log entry is longer than ~16374 characters. Found this out during investigation, app in container outputs huge json for debug purpose, later in kibana I fount that json split into 5 pieces and not readable at all. I didn't find any documented way to increase message size.

**How to reproduce**:
```
docker run -it -p 24224:24224 -v $(pwd)/fluent.conf:/fluentd/etc/fluent.conf ymatsiuk/fluentd-test:latest

docker run -it --log-driver=fluentd --log-opt tag=docker.{{.ID}} -v /Users/ymatsiuk/test:/root/test alpine cat /root/test/new.json
```

**Configuration, log example and output log**:

[fluent.conf](https://gist.github.com/ymatsiuk/3bb0ce001e771fd02b70a56e6bc053ff#file-fluent-conf)
[new.json](https://gist.github.com/ymatsiuk/3bb0ce001e771fd02b70a56e6bc053ff#file-new-json)
[output.log](https://gist.github.com/ymatsiuk/3bb0ce001e771fd02b70a56e6bc053ff#file-output-log)

**Dockerfile patch**
```
diff --git a/v0.12/alpine/Dockerfile b/v0.12/alpine/Dockerfile
index aecaf80..938e825 100644
--- a/v0.12/alpine/Dockerfile
+++ b/v0.12/alpine/Dockerfile
@@ -27,6 +27,7 @@ RUN apk update \
  && gem install oj -v 2.18.3 \
  && gem install json -v 2.1.0 \
  && gem install fluentd -v 0.12.39 \
+ && gem install fluent-plugin-elasticsearch \
  && apk del .build-deps \
  && rm -rf /var/cache/apk/* \
  && rm -rf /tmp/* /var/tmp/* /usr/lib/ruby/gems/*/cache/*.gem
```

**Comment by repeatedly** [comment]
Could you test fluent-logger with your `new.json` content?
It shows which, fluentd or docker, causes this problem.

**Comment by ymatsiuk** [comment]
@repeatedly could you please explain how can I do it?

**Comment by repeatedly** [comment]
If you can write ruby, send same record to fluentd's `in_forward` via fluent-logger-ruby.
Of course, other language client is ok. docker logging driver and fluent-loggers use same protocol.

**Comment by ymatsiuk** [comment]
@repeatedly I can confirm that the issue is not re-producible with fluent-logger-python
