### ISSUE TITLE
SIGTERM Blocks with in_tail and read_from_head true in v0.14.20

### ISSUE THREAD

**Issue by gstib** [fluent/fluentd#1672]
SIGTERM Blocks and fails to stop all threads when you set `read_from_head true` in `in_tail`.

The following configuration is used

```
<source>
  @type tail
  path /var/log/auth.log*
  pos_file /var/log/pos-auth.log
  read_from_head true
  tag auth.log
  path_key file
  format syslog
</source>
```

This configuration works in v0.12.39 but hangs in v0.14.20. 
I have a working example at https://github.com/gstib/fluentd_sigterm

Run the command `make run_12` and you will see that the `docker stop` command `SIGTERM` exits cleanly
Run the command `make run_14` and you will see that the `docker stop` command hangs.

The problem only appears in v0.14 with the above configuration and with multiple files that match the path.

**Comment by repeatedly** [comment]
Thanks for the report. We will check which point cause this problem.
I will try to reproduce the problem without docker first.
