### ISSUE TITLE
how to avoid push duplicate log  to es when rename file?

### ISSUE THREAD

**Issue by Bobi-zhou** [fluent/fluentd#1673]
- fluentd or td-agent version:0.12.39
- Environment information:centos 7
- conf
``` xml
<source>
        type tail
        path /u01/logs/*/logs/*audit.log
        pos_file /var/log/fluentd-pos/audit.log.pos
        tag audit.*
        format json
        refresh_interval 10
        read_from_head true
    </source>
```
 i generated a log named xxaudit.log and successful push the content to es
but if i rename xxaudit.log to yyaudit.log ,the fluentd will push the yyaudit.log content to es again,why?
the xxaudit.log inode is same as yyaudit.log

How to solve it？

**Comment by repeatedly** [comment]
> the fluentd will push the yyaudit.log content to es again,why?

See: https://docs.fluentd.org/v0.12/articles/in_tail#path-required

> How to solve it？

Try this patch: https://github.com/fluent/fluentd/pull/1660

**Comment by ganmacs** [comment]
it's stale. i'm closing. if you have any problem, updating fluentd might help you.
