### ISSUE TITLE
<regexp> is not used , td-agent V3

### ISSUE THREAD

**Issue by charlecoms** [fluent/fluentd#1675]
Hello everyone , 

I swiched to td-agent V3 on my Amazon-Linux distribution (By the way i took the Red-Hat package which is installed perfectly. I used the td-agent V2 before 
The record_accessor of the V3 can potentially resolve a lot of things in my configuration like to pass args in my command in section filter_out_exec from my events: (Say me if i'm wrong)

```
<match reverse_proxy.geo> 
  @type exec_filter
  command ruby ./ip.rb $.ip                    //usefull to pass args directly from json format 
  in_format json
  out_format json
  flush_interval 10s
  tag reverse.filtered
</match>
```

But in the rest of my configuration , i had a lot of grep filter . They doesn't work anymore ... Is <regexp> section deprecated or miss something in V3?

Part of my old conf , which worked in V2 (SSH Error for exemple ) : 

```
<source>
  @type kafka
  brokers 10.0.0.117:9092
  topics log_ssh
  add_suffix error
</source>

<filter log_ssh.error>
  @type grep
  <regexp>
  key message
  pattern ^.*(error|Invalid|Failed).*([0-9]{1,3}\.){3}[0-9]{1,3}.*$
  </regexp>
</filter>

<filter log_ssh.error>
  @type stdout
</filter>
```

Result of my logs when restarted

**2017-08-28 14:18:44 +0200 [warn]: section <regexp> is not used in <filter log_ssh.error> of grep plugin
2017-08-28 14:18:44 +0200 [warn]: section <regexp> is not used in <filter log_ssh.error> of grep plugin
2017-08-28 14:18:44 +0200 [warn]: section <regexp> is not used in <filter log_ssh.accepted> of grep plugin
2017-08-28 14:18:44 +0200 [warn]: section <regexp> is not used in <filter log_ssh.accepted> of grep plugin**

**Comment by repeatedly** [comment]
> The record_accessor of the V3 can potentially resolve a lot of things in my configuration like to pass args in my command in section filter_out_exec from my events:

`out_exec_filter` doesn't use `record_accessor` so it doesn't support nested access in any parameters.
From your configuration, `command ruby ./ip.rb $.ip `, accessing field in your script seems enough.

> Is section deprecated or miss something in V3?

Latest td-agent 3 is built at several months ago.
So you need to update bundled fluentd to latest v0.14.20.
