### ISSUE TITLE
output forward memory leak when transport is tls

### ISSUE THREAD

**Issue by gtt116** [fluent/fluentd#1678]
Check [CONTRIBUTING guideline](https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md) first and here is the list to help us investigate the problem.

- fluentd or td-agent version.
fluentd-0.14.16 and td-agent-3.0.1-0.el6.x86_64

- Environment information, e.g. OS.
Centos 6.4
- Your configuration

```
<system>
  root_dir /var/run/td-agent
  log_level error
</system>

<source>
    @type forward
    port 24284

    <transport tls>
      cert_path         /etc/td-agent/ssl/ca_cert.pem
      private_key_path  /etc/td-agent/ssl/ca_key.pem
      private_key_passphrase xxx
    </transport>
</source>


<match **>
  @id forward_a
  @type forward

  transport tls
  tls_cert_path                 /etc/td-agent/ssl/ca_cert.pem
  tls_allow_self_signed_cert    true
  tls_verify_hostname           false

  <server>
    host            127.0.0.1
    port            24284
  </server>

  <buffer>
    @type file
    flush_interval      10s
    flush_at_shutdown   true
  </buffer>

</match>
```

- Your problem explanation. If you have an error logs, write it together.

If disable `transport tls`, the memory usage keep about 40MB, but when enable tls, the memory usage will increase to 340MB. No errors found in log file.

![image](https://user-images.githubusercontent.com/1257631/29874395-362de800-8dc9-11e7-89bf-47a41c91c7a5.png)

**Comment by gtt116** [comment]
Updated fluentd to 0.14.20, this issue still there. Please let me know, if I can provide more information 

![image](https://user-images.githubusercontent.com/1257631/29874656-067d6f80-8dca-11e7-8957-31a3af92de71.png)

**Comment by repeatedly** [comment]
Does it mean memory usage keep to increase or not increase but larger than non-TLS?

**Comment by repeatedly** [comment]
This seems same as #1767 and it is fixed in recent versions.
