### ISSUE TITLE
[Question] Support editing tags in the built-in record_transformer plugin

### ISSUE THREAD

**Issue by qingling128** [fluent/fluentd#1685]
Hi,

Is there any plan to add support to edit tags in the record_transformer plugin? Right now we are using [`record_reformer`](https://github.com/sonots/fluent-plugin-record-reformer) to achieve this:
```
<match container.**>
  @type record_reformer
  enable_ruby true
  <record>
    "severity" ${if record['source'] == 'stderr' then 'ERROR' else 'INFO' end}
  </record>
  tag ${record['source']}
</match>
```

Wondering if there is a way to do it without introducing an additional gem.

**Comment by qingling128** [comment]
Some background: We are trying to use the [Docker Fluentd Logging Driver](https://docs.docker.com/engine/admin/logging/fluentd/) to handle Docker container stdout/stderr logs. We need to set `stderr` or `stdout` as the log tags. That info is in the log record field `source`, so we need to extract that field and set the tag accordingly.

The workaround would be to use the `record_reformer` plugin instead.

**Comment by repeatedly** [comment]
Filter doesn't allow tag rewriting so if you want to do it, use `record_reformer`.

**Comment by qingling128** [comment]
Understood. Thanks for the clarification!
