### ISSUE TITLE
fork bomb in case of failure

### ISSUE THREAD

**Issue by jefimm** [fluent/fluentd#1687]
Fluentd 0.14 +multiprocess plugin +monitoring plugin 

if multiprocess plugin starts workers and monitoring plugin fails to start due to address already in use there is missing cleanup for the multiprocess plugin
This causes host to die due to unrestricted spawning of workers
Unrestricted restart of failed workers is very bad design

This is a regression from 0.12 that does not have this issue

**Comment by repeatedly** [comment]
Hmm... you are right.
`address already in use` like error is not recoverable from fluentd side.
So fluentd should be die with proper cleanup.

**Comment by kenhys** [comment]
I've checked with:

* fluentd 1.11.5 + fluent-plugin-multiprocess 0.2.2
* fluentd 0.14.25 + fluent-plugin-multiprocess 0.2.2

It seems that fork bomb doesn't occur. it may be fixed already.

```
% cat fluent.conf
<source>
  @type multiprocess

  <process>
    cmdline -c child1.conf --log child1.log
    sleep_before_start 0s
    sleep_before_shutdown 5s
  </process>
  <process>
    cmdline -c child2.conf --log child2.log
    sleep_before_start 0s
    sleep_before_shutdown 10s
  </process>
</source>

<source>
  @type monitor_agent

  bind 127.0.0.1
  port 24224
</source>
```

```
% cat child1.conf
<source>
  @type forward
  port 24224
  bind 127.0.0.1
</source>

% cat child2.conf
<source>
  @type forward
  port 34224
  bind 127.0.0.1
</source>
```

It seems this issue was stalled, and there is no problem with newer release, so I'll close it.
