### ISSUE TITLE
Would you rename ChangeLog to CHANGELOG.md?

### ISSUE THREAD

**Issue by ryysud** [fluent/fluentd#1694]
I think rendering on GitHub is pretty good. What do you think?
https://github.com/fluent/fluentd/blob/master/ChangeLog

**Comment by repeatedly** [comment]
Does CHANGELOG.md rendering have format spec?

**Comment by ryysud** [comment]
Yes. It's markdown format.
You can write CHANGELOG.md freely using the markdown form.

**Comment by ryysud** [comment]
Thanks!
