### ISSUE TITLE
Butter file auto purse chunk event can't reach the hosts after flush_interval 

### ISSUE THREAD

**Issue by itlabvn** [fluent/fluentd#1695]
Hello. I am new with fluentd. I use td-agent v0.12 with ubuntu
Here is my td-agent.conf. My problem is , i want config fluent to buffer data if can not reach graylog in buffer_path and re-transfer to host when reached. But it auto purse chunk event can not reach my hosts. Plz help. Thank you 
```
<source>
  @type forward
</source>
<match docker>
   @type gelf
   host 172.17.0.4
   port 12201
   protocol tcp
   flush_interval 10s
   buffer_type file
   buffer_path /var/log/td-agent/buffer/td.*.buffer
</match>
```

**Comment by repeatedly** [comment]
Don't follow the guide. Closed: https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md#got-a-question-or-problem
