### ISSUE TITLE
Fluentd Counter metric incrementing with previous values 

### ISSUE THREAD

**Issue by akgunjal** [fluent/fluentd#1699]
Check [CONTRIBUTING guideline](https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md) first and here is the list to help us investigate the problem.

- fluentd or td-agent version.
**0.14.21**

- Environment information, e.g. OS.
**Ubuntu 16.04.2 LTS (xenial)**

- Your configuration
- Your problem explanation. If you have an error logs, write it together.
**Problem:**
I am using the prometheus plugin for my counter metrics. I tried using a example in community but the counter does not provide increments as expected. When a new counter increment has to be done it also adds it with previous values which is incorrect.

My configuration file:
```
<source>
  @type prometheus
</source>

<source>
  @type tail
  path /var/log/test.log
  format json
  tag message
  pos_file /mnt/ibm-kube-fluentd-persist/test.pos
  types foo:integer
</source>

<match message>
  @type prometheus
  <metric>
    name message_foo_counter
    type counter
    desc The total number of foo in message.
    key foo
  </metric>
</match>
```

Contents of log file /var/log/test.log:
```
{“foo”:50,“bar”:“10”,“baz”:“20”}
{“foo”:100,“bar”:“100",“baz”:“100"}
{“foo”:50,“bar”:“100”,“baz”:“100”}
```

Output I am seeing:
```
curl http://192.168.10.3:24231/metrics
# TYPE message_foo_counter counter
# HELP message_foo_counter The total number of foo in message.
message_foo_counter 400.0
```

Initially the log file was empty and I kept adding log lines to increment counter value.
As you see the value of counter 400 comes due to adding up old values - (50) + (50 + 100) + (50 + 100 + 50) = 400

**Comment by repeatedly** [comment]
This seems the question about fluent-plugin-prometheus, not fluentd core.
