### ISSUE TITLE
out_forward v0.14 to v0.12 corrupts buffers

### ISSUE THREAD

**Issue by rb1980** [fluent/fluentd#1702]
I was testing the Windows beta agent 3.0.1-0 (fluentd-0.14.13) out_forward into a well-established linux aggregator running td-agent-2.3.5-1.el7.x86_64 (fluentd-0.12.36)

I finally stumbled across the note about setting `time_as_integer` in out_forward setting in v0.14 fluentd, but prior to that: noticed that when the 0.14 agent was forwarding to 0.12, I was getting errors about the buffers on the 0.12 side not being able to drain. 
This ultimately led to none of the buffered events getting forwarded to ES, not even valid ones.
This seems like bad behavior. One bad event corrupts the whole buffer, and causes data loss.

```2017-09-27 09:31:08 -0700 [warn]: temporarily failed to flush the buffer. next_retry=2017-09-27 09:35:14 -0700 error_class="MessagePack::UnknownExtTypeError" error="unexpected extension type" plugin_id="object:3fcd4caf0b8c"
2017-09-27 09:31:08 -0700 [warn]: suppressed same stacktrace
2017-09-27 09:31:33 -0700 [warn]: failed to flush the buffer. error_class="MessagePack::UnknownExtTypeError" error="unexpected extension type" plugin_id="object:3fcd4cabe894"
2017-09-27 09:31:33 -0700 [warn]: retry count exceededs limit.
2017-09-27 09:31:33 -0700 [warn]: suppressed same stacktrace
2017-09-27 09:31:33 -0700 [error]: throwing away old logs.
```
The only way I was able to recover was to stop td-agent and delete the bad buffer files manually.
Would `skip_invalid_event` on the in_fwd side prevent this? I am confused by the note: "This option is useful at forwarder, not aggragator."
It just seems like a bad risk that a misconfigured client out in the wild could send an event to my aggregator that effectively brings it down.

**Comment by repeatedly** [comment]
> Would skip_invalid_event on the in_fwd side prevent this?

Maybe, no. Because `skip_invalid_event` checks incoming event is valid structure or not after deserialization.
But your error happens during deserialization phase, so same error happens in `in_forward`.
I assume some of your forwarders don't have `time_as_integer` parameter in `out_forward`.

**Comment by ganmacs** [comment]
it's a stale issue. I'm closing. if you have any problem, updating fluentd might help it.
