### ISSUE TITLE
No Way to tie Failed Buffer Chunks to Chunk ID

### ISSUE THREAD

**Issue by GLStephen** [fluent/fluentd#1705]
- V14
- CentOS
- Forwarder web servers, to aggregators

FluentD log files refer to chunk_id when it is emitting errors and warning. Sometimes of these lead to failed chunks. Those failed chunks can be put in a secondary location. However, the ${chunk_id} is not available in the failed log and the meta file is not in the failed folder so this chunk_id can't be used to figure out which specific failed buffer file an error relates to. 

Remedy: file & secondary_file should support something like ${chunk_id} placeholder so that the chunk_id can be retained.

**Comment by repeatedly** [comment]
Patch is here: https://github.com/fluent/fluentd/pull/1708

**Comment by GLStephen** [comment]
@repeatedly awesome, thanks!
