### ISSUE TITLE
Records Larger than Chunk Messaging Seems Unclear

### ISSUE THREAD

**Issue by GLStephen** [fluent/fluentd#1706]
- v14
- Centos 7
- Relevant config:

```
<source>
  @type forward
  port 24228
</source>

<match tag.**>
    ...
    <buffer tag, time>
        @type file
        ...
        chunk_limit_size 999k
        ...
    </buffer>
</match>
```

The following appears in logs, but all BufferChunkLimits are above this size:

2017-09-30 18:54:00 +0000 [error]: #0 unexpected error on reading data host="x.x.x.x" port=yyyyyy error_class=Fluent::Plugin::Buffer::BufferChunkOverflowError error="a 104398bytes record is larger than buffer chunk limit size"

Is this message slightly different than it sounds and is actually saying it can't split the message because an individual exceeds the buffer chunk limit by 100k? So, a 1.1mb *record* not a 104k *record*? Relevant code is here https://github.com/fluent/fluentd/blob/fcae0e0d783c3d5fdc3451a09e5e361596dadaa0/lib/fluent/plugin/buffer.rb#L579

**Comment by ganmacs** [comment]
it's a stale issue. I'm closing. if you have any problem, updating fluentd might help it.
