### ISSUE TITLE
--log-rotate-size && --log-rotate-age Cause Failure with workers > 1

### ISSUE THREAD

**Issue by GLStephen** [fluent/fluentd#1707]
- v14
- Centos 7
- Only difference is workers 2

When testing log rotation I found that fluentd crashes right when log rotate happens if workers > 1. This is under notable load (150k events per minute). When looking at ps aux it looks like one child process under the supervisor is restarted (new PID) and one is not. I don't have much more info at this time, but wanted to submit the issue.

**Comment by repeatedly** [comment]
Thanks for the report.
Do you have a error or something log in fluentd logs or
Did fluentd crash without any logs?

**Comment by GLStephen** [comment]
It crashed silently. No logs.  CPU usage drops out. Just stops processing.

**Comment by repeatedly** [comment]
I see.

So reproduce step is "set small `--log-rotate-size` value and force to rotate log with `workers 2` setting".
I will try it.

**Comment by GLStephen** [comment]
@repeatedly I believe the issue may be related to
