### ISSUE TITLE
Receiving "MessagePack::UnknownExtTypeError" when using forward source

### ISSUE THREAD

**Issue by ishkanan** [fluent/fluentd#1709]
Hi team,

I am repeatedly seeing the below error in the td-agent log file (attached) when using a forward plugin instance as a source. I am using Fluent-bit (td-agent-bit service, v0.12.4) to forward data to a Fluentd (td-agent service, v2.3.6-0) instance which sends data to ElasticSearch. All 3 products are running on the same server (as a prototype) running Ubuntu 16.04.3 patched up to last week.

The error I see is below (timestamp removed for brevity):

`[error]: forward error error=#<MessagePack::UnknownExtTypeError: unexpected extension type> error_class=MessagePack::UnknownExtTypeError
  [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.35/lib/fluent/plugin/in_forward.rb:337:in 'feed_each'
  [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.35/lib/fluent/plugin/in_forward.rb:337:in 'on_read_msgpack'
  [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.35/lib/fluent/plugin/in_forward.rb:323:in 'call'
  [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.35/lib/fluent/plugin/in_forward.rb:323:in 'on_read'
  [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/cool.io-1.4.6/lib/cool.io/io.rb:123:in 'on_readable'
  [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/cool.io-1.4.6/lib/cool.io/io.rb:186:in 'on_readable'
  [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/cool.io-1.4.6/lib/cool.io/loop.rb:88:in 'run_once'
  [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/cool.io-1.4.6/lib/cool.io/loop.rb:88:in 'run'
  [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.35/lib/fluent/plugin/in_forward.rb:120:in 'run'`

I have attached:
- the full td-agent log file
- the configuration for td-agent
- the configuration for td-agent-bit

I've scoured the docs for both services and I can't see what could be wrong with my configuration that is causing this error. I can't tell if the error is due to an issue with the fluentd forward plugin or one of the fluent-bit plugins I'm using.

Thanks for any help you can give :)

[files.zip](https://github.com/fluent/fluentd/files/1357671/files.zip)

**Comment by repeatedly** [comment]
I assume your fluent-bit configuration issue: https://docs.fluentd.org/v0.12/articles/in_forward#i-got-messagepackunknownexttypeerror-error-why

@edsiper ?

**Comment by edsiper** [comment]
Enable the option _Time_as_Integer On_ in the output config (Fluent Bit side)

**Comment by ishkanan** [comment]
@edsiper Thanks for the pointer, the error is gone now. Note to self, read the FAQ first :)

**Comment by luhn** [comment]
Link is broken.  New link:  https://docs.fluentd.org/v/0.12/input/forward#i-got-messagepack-unknownexttypeerror-error-why
