### ISSUE TITLE
in_tail, use path in output

### ISSUE THREAD

**Issue by sylr** [fluent/fluentd#1712]
Hi,

I'm trying to do something really simple but fail to do it so I'm asking here (maybe not the best place).

Basically I want to tail the container logs of my kubernetes nodes and send them to splunk.

To do so I' want to use the in_tail plugin and one of the splunk HEC output plugin, the configuration would look like this (this is not working cause `${record["path"]}` does not exists):

```
<source>
  @type tail
  path /var/log/containers/*.log
  pos_file /tmp/fluentd-containers.pos
  tag kubernetes.containers
  refresh_interval 5s
  log_level debug

  time_key time
  time_format %Y-%m-%dT%H:%M:%S.%NZ
  format json
  read_from_head true
</source>

<match kubernetes.containers>
  type splunk-http-eventcollector
  server 10.10.10.10:9990
  verify false
  token aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaaaaaaaaaa

  # Convert fluent tags to Splunk sources.
  # If you set an index, "check_index false" is required.
  host fluentd
  index kubernetes-containers
  #check_index false
  source ${record["path"]}
  sourcetype _json

  # TIMESTAMP: key1="value1" key2="value2" ...
  #time_format unixtime
  #format kvp

  # Memory buffer with a short flush internal.
  buffer_type memory
  buffer_queue_limit 16
  buffer_chunk_limit 8m
  flush_interval 10s
</match>
```

My problem lies with the `source` option of splunk output plugin, I would like it to be set to the value of the tailed file.

Could you tell me how I can do that ?

Regards.

**Comment by sylr** [comment]
Any idea ?

**Comment by repeatedly** [comment]
Need to use v0.14 and v0.14 new plugin API in output code.

https://docs.fluentd.org/v0.14/articles/api-plugin-output#understanding-chunking-and-metadata

BTW, don't use github issue for question. Please follow this guide

https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md#got-a-question-or-problem
