### ISSUE TITLE
0.14 doesn't support milliseconds 

### ISSUE THREAD

**Issue by alter** [fluent/fluentd#1725]
I've latest stable elastic and kibana
Also I tried 2 version of td-agent: 0.12/0.14 from package 2.3.6(even remove gem with 0.12 and used only 0.14)
and now I'm on 0.14.16 from package 3.0.1.

configuration of my source hosts:
```
<source>
  @type tail
  tag xxx
  path /var/log/json.log
  pos_file /var/opt/td-agent/log.pos
  format json
  time_key @timestamp
  time_format "%Y-%m-%dT%H:%M:%S.%L"
  read_from_head false
</source>

<filter xxx>
  @type record_transformer
  <record>
    hostname clientname
    node_id 6
  </record>
</filter>

<match **>
  @type forward
  <server>
    host server
  </server>
</match>
```

configuration of destination host:
```
<source>
  @type forward
  port 24224
</source>

# Store Data in Elasticsearch
<match *.**>
  @type copy
  <store>
    @type elasticsearch
    host localhost
    port 9200
    include_tag_key true
    tag_key @log_name
    logstash_format true
    flush_interval 10s
  </store>
</match>

```

json with data:
```
{"@timestamp":"2017-10-23T17:17:57.006","@version":1,"message":"transactions for microblock took 0ms","logger_name":"com.class.mining.MinerImpl","thread_name":"miner-pool-123","level":"TRACE","level_value":5000}
```

But in Kibana I still see **.000** for all records, what's wrong with it?

**Comment by RedactedProfile** [comment]
Just ran into this and ran into this thread just now: https://stackoverflow.com/questions/27928479/fluentd-loses-milliseconds-and-now-log-messages-are-stored-out-of-order-in-elast#comment44301861_27928598

**Comment by repeatedly** [comment]
Do you use v2.0.0 version?

https://github.com/uken/fluent-plugin-elasticsearch#requirements

v1.x doesn't support subsecond precision by default.

**Comment by alter** [comment]
@RedactedProfile your solution doesn't look nice, b/c it's insert time in ms during filter step, but each record in my log already has time with ms, and it's really actual time.

@repeatedly Huge thx, dude, it works perfectly!

**Comment by RedactedProfile** [comment]
@alter I agree none of this is nice. For the record, not my solution :p just a random stack thread I found
