### ISSUE TITLE
0.14 td-agent, buffers combined randomly in TCP source with heavy traffic case.

### ISSUE THREAD

**Issue by gordonlee** [fluent/fluentd#1726]
Check [CONTRIBUTING guideline](https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md) first and here is the list to help us investigate the problem.

- Version
  : td-agent 0.14.16
- OS
  : Ubuntu 16.04.2 LTS AND Windows 2012 R2 have same problem.
- Your configuration
  : 

```ruby

<system>
  workers 7
</system>
<source>
  @type  udp
  format json
  tag    TAG
  bind   0.0.0.0
  port   UDP_PORT
  body_size_limit 5MB
</source>

<source>
  @type  tcp
  format json
  tag    TAG
  bind   0.0.0.0
  port   TCP_PORT
</source>

<source>
  @type http
  port 8888
  bind 0.0.0.0
  body_size_limit 32m
  keepalive_timeout 10s
</source>

<match **>
  @type forward
  heartbeat_type none
  time_as_integer

  send_timeout 30s
  buffer_queue_limit 256
  expire_dns_cache 30

  <server>
    host DESTINATION_HOST
    port DESTINATION_PORT
  </server>

  <secondary>
    @type file
    path /var/log/td-agent/forward-failed
  </secondary>

</match>
```

- Your problem explanation. If you have an error logs, write it together.
: When fluentd receives using TCP source **with so much traffic**, sometimes it seems to mix buffer contents. For example, when A and B processes send packets {"key": "AAAA", "value": "111"} and {"key": "BBBB", "value": "22222222"} for each processes, fluentd sometime mixes the buffer contents like **{"key" : "AAAB", "value":"22222222"}**. It seems that two different packets are merged to one packet randomly. 
This usually doesn't appear, but sometimes does.

My test case is below.
: make C++ program to send JSON packets with infinite loops. Let say TestSender.exe
: run 4 more TestSender.exe processes to give stress to Fluentd. 
: If Fluentd configuration matches all packet to stdout or file, then you can find this error.

In addition, UDP and HTTP sources haven't appear like this problem. Only TCP source does.

**Comment by repeatedly** [comment]
Sorry for the late.
This problem is similar problem to https://github.com/fluent/fluentd/issues/1516.
Your configuration set `workers 7` but it happens with `workers 1`, right?

Could you share your test problem for reproducing the issue?

> In addition, UDP and HTTP sources haven't appear like this problem. Only TCP source does.

Hmm... in_http also uses TCP connection so frequent request may be the factor.

**Comment by gordonlee** [comment]
Yes, it happens with workers 1 too. 

I'm not sure that the test program file could be shared in public. I'll check whether it's possible or not. 

Hm.. A difference between http and tcp in my case, I'm suspicious that in_http closes connection after finishing sending one packet(probably one JSON content), but in_tcp keeps its connection until exiting the test program. I hope it could be helpful.

**Comment by repeatedly** [comment]
> but in_tcp keeps its connection until exiting the test program. I hope it could be helpful.

I see. We need to check connection handling of libev when connection is not closed.

**Comment by repeatedly** [comment]
Could you test https://github.com/fluent/fluentd/pull/1729 patch with your test workload?

**Comment by gordonlee** [comment]
Sorry for the late.
My teammate and I have tested #1729 patch and the problem is fixed. Maybe a cause of this issue seems to be sharing buffers. Thank you for support.

**Comment by billmers** [comment]
FWIW I have this issue as well, and I've tested PR #1729 and can confirm that it fixes the problem for me.

**Comment by repeatedly** [comment]
Release v0.14.23.rc1 for the fix.

**Comment by sampointer** [comment]
I am a colleague of the author of https://github.com/fluent/fluentd/pull/1729. We've tested this on our infrastructure successfully. `0.14.23` would be a great help.

**Comment by repeatedly** [comment]
You can use v0.14.23.rc1. It includes this fix.
