### ISSUE TITLE
fluentd CPU usage bring my machine freezed out

### ISSUE THREAD

**Issue by syukur91** [fluent/fluentd#1728]
So here's the case, I have td-agent running on  ubuntu 16.04, so the purpose is, we trying to catch the docker log and flush it to elasticsearch. The docker container itself is grpc endpoint which can be called via REST using specific load balancer. I do the test using wrk to loadtest the endpoint, automatically when I run the grpc docker I set the driver to fluentd. 

Firstly, I do the test using wrk with small connection and threads It successfully flush the data to elasticsearch and there's  no problem. But when tried to wrk this endpoint with a larger connection and threads, my machine freezed out, I took a while the htop before it freezed out and I found that all of the core (I have 8 cores) has been occupied. And the cpu usage around 100% .

Here's the result 
![image uploaded from ios](https://user-images.githubusercontent.com/12888873/31979314-34ca190c-b970-11e7-92f1-2e91749d3dc3.jpg)

![image uploaded from ios 1](https://user-images.githubusercontent.com/12888873/31979330-4f2cb0d4-b970-11e7-8547-b103341b33e5.jpg)

The latest wrk test show that it have around 521806 request at that time which mean that I have that count of record in my elasticsearch.

**Comment by repeatedly** [comment]
Your screenshot shows you launches several td-agent processes but only 1  td-agent process consumes CPU.
Do you actually test only 1 process?

**Comment by ganmacs** [comment]
it's a stale issue. I'm closing. if you have any problem, updating fluentd might help it.
