### ISSUE TITLE
fluent-logger-php repository has been removed

### ISSUE THREAD

**Issue by moon0326** [fluent/fluentd#1730]
Hi,

I did not know where to report this issue.

We've been using fluent/fluent-logger-php in our projects and just noticed that the repository has been removed without a warning.

It's still hosted in packagist, but the repository is not there.

https://packagist.org/packages/fluent/logger

Could someone please let us know what happened?

**Comment by repeatedly** [comment]
The repository is restored yesterday. So closed.
