### ISSUE TITLE
Upgrading td-agent from 2.3.5 to 2.3.6 fails

### ISSUE THREAD

**Issue by malinoff** [fluent/fluentd#1731]
**OS**: ubuntu 16.04 (xenial).
**Configuration**: the match below is in question:
```
<match **>
  @type forward
  buffer_type file
  buffer_path /etc/td-agent/buffer/
  buffer_chunk_limit 4m
  buffer_queue_limit 10000
  flush_interval 10s
  retry_limit 17
  retry_wait 1.0
  num_threads 1

  heartbeat_type tcp
  heartbeat_interval 1s
  <server>
    host central_logs.company.com
    port 24224
  </server>
</match>
```

**Error message**: 
```
config error file="/etc/td-agent/td-agent.conf" error_class=Fluent::ConfigError error="Other 'forward' plugin already use same buffer path: type = forward, buffer path = /etc/td-agent/forward_buffer/"
```

There's no other match sections, or buffers configured elsewhere. The same configuration works on 2.3.5, and keeps working when I downgraded from 2.3.6 to 2.3.5

```
$ apt-cache policy td-agent
td-agent:
  Installed: 2.3.5-0
  Candidate: 2.3.6-0
  Version table:
     2.3.6-0 500
        500 http://packages.treasuredata.com/2/ubuntu/xenial xenial/contrib amd64 Packages
 *** 2.3.5-0 100
        100 /var/lib/dpkg/status
```

**Comment by repeatedly** [comment]
Don't open the td-agent issue on fluentd repository.

**Comment by malinoff** [comment]
@repeatedly please, point me to a correct repository.

**Comment by malinoff** [comment]
@repeatedly ping?

**Comment by repeatedly** [comment]
> point me to a correct repository.

You already know it because it is mentioned in CONTRIBUTING.md :)
https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md#found-a-bug

**Comment by S569** [comment]
When I use 
"apt-get update && apt-get install td-agent " for upgrading td-agent from 2.3.6 to 3.0 on ubuntu 16.04. 
It says "td-agent is already the newest version (2.3.6-0)". Can anyone tell me how to upgrade it to latest version.
