### ISSUE TITLE
memory buffer + format multiline loses data on restarts

### ISSUE THREAD

**Issue by scottbuettner** [fluent/fluentd#1732]
* fluentd v0.14.16 (from the td-agent-3 installer)
* CentOS 7 under virtualbox
* Config to replicate:
```<source>
  @type tail
  read_from_head true
  path /tmp/test.log
  pos_file /var/log/td-agent/test.log.pos
  tag test
  format multiline
  time_format "%d-%b-%Y %H:%M:%S.%L"
  format_firstline /\d{2}-\S{3}-\d{4} \d{2}:\d{2}:\d{2}.\d{3}/
  format1 /(?<time>\d{2}-\S{3}-\d{4} \d{2}:\d{2}:\d{2}.\d{3}) +(?<message>(?:\n|.)+)/
</source>

<match test>
  @type file
  path "/var/log/td-agent/test.out"
  append true
  <buffer>
    @type memory
  </buffer>
</match>
```
* Steps to replicate:
    1. Start fluentd with the above config, with the attached file ([test.log](https://github.com/fluent/fluentd/files/1427503/test.log)) in /tmp/test.log
    2. Restart fluentd
    3. the log at /var/log/td-agent/test.out now contains messages 1-4.
    4. Add the attached lines to the end of /tmp/test.log ([test2.log](https://github.com/fluent/fluentd/files/1427508/test2.log))
    5. Restart fluentd again
    6. test.out will contain message 6, skipping message 5.

It looks like the multiline formatter (when using a memory buffer) is dropping the last held lines, which were waiting on a matching `format_firstline`, when you restart. An option to persist this data in the pos file or some other location would be helpful.

This issue does not affect `@type file` buffers from my testing. Also, I have yet to test on v0.12 to see if it is impacted as well. I should have time later today to test v0.12 and a newer v0.14 version.

**Comment by scottbuettner** [comment]
This does NOT appear to affect v0.12.

**Comment by repeatedly** [comment]
https://github.com/fluent/fluentd/pull/1763 also fixes this issue.

**Comment by repeatedly** [comment]
v0.14.25 includes above patch.
