### ISSUE TITLE
log not parsing

### ISSUE THREAD

**Issue by viquar22** [fluent/fluentd#1735]
- fluentd or td-agent version. v0.12
- Environment information, e.g. OS. Linux
- Your configuration 

[td-agent.txt](https://github.com/fluent/fluentd/files/1439134/td-agent.txt)

Need some help in parsing nginx logs and modifying the td-agent.conf. 
Tried modifying td-agent.conf with many configurations but didn't work... Still logs are not parsed in Kibana

**Comment by repeatedly** [comment]
The github issue is not for user support.
