### ISSUE TITLE
Excluding a value via .* pattern is misbehaving

### ISSUE THREAD

**Issue by gmile** [fluent/fluentd#1744]
**Versions info**:

* Fluentd version: 0.14.22 (installed as a gem)
* Ruby version: 2.4.2
* OS: macOS 10.12.3

**My configuration** (resides in `~/fluentd/fluent.conf`):

```xml
<source>
  @type forward
</source>

<filter eugene-testing>
  @type grep
  <exclude>
    key somekey
    pattern .*
  </exclude>
</filter>

<match eugene-testing>
  @type stdout
</match>
```

I start the server via `fluentd -c ~/fluentd/fluent.conf`, then I run:

```
echo '{"message": "My proud message!"}' | fluent-cat 'eugene-testing'
```

**Observed behaviour**:

`fluentd` does not report any message seen.

**Expected behaviour**:

`fluentd` sees:

```
2017-11-09 19:41:04.293648000 +0200 eugene-testing: {"message":"My proud message!"}
```
---
If I remove the `<exclude>` block from `<filter>`, things work. But I wanted to get a feeling that if a particular `<exclude>` is there, it still won't affect the message I'm sending since the **message does not even contain the key** specified in `<exclude>` block.

What am I missing?

**Comment by gmile** [comment]
I was trying to debug this, but unfortunately with no luck. For some reason putting `puts` across the codebase doesn't yield any output. Will need to investigate further, but a help would be appreciated. @repeatedly 

Here's the minimal repro code:

```ruby
require_relative 'test/helper';
require 'fluent/plugin/filter_grep';
require 'fluent/test/driver/filter';

config = "
<exclude>
  key $.abc
  pattern .*
</exclude>
"

d = Fluent::Test::Driver::Filter.new(Fluent::Plugin::GrepFilter).configure(config);

d.run do
  d.feed("filter.test", Time.now.to_i, {"foo" => "bar", "message" => "Some message"})
end

puts d.filtered_records.inspect
# => []
```

As far as I understand, `filtered_records` refer to records after the filter was applied. Meaning that `[]` is not correct, as it should have included:
```
{"message => "Some message"}
```

**Comment by repeatedly** [comment]
The problem is filter_grep tries to match the field value as much as possible.
For it, filter_grep calls `to_s` to incoming value, e.g. `10` to `"10"`, `nil` to `""`.
In your case, your record doesn't have `somekey` field and it is same as latter case, `nil` to `""`.
`.*` matches `""` so the record is excluded.

To avoid the problem, use `.+` instead of `.*` or adding option to check field existence.

**Comment by gmile** [comment]
So `.*` was actually matching all this time 😮 Thank you, @repeatedly!
