### ISSUE TITLE
Config plugin for fluentd

### ISSUE THREAD

**Issue by rhonnava** [fluent/fluentd#1745]
Usecase:
 - fluentd is installed on hundreds of client nodes, filters the needed application log events and sends them using an output plugin to a central Elasticsearch cluster.
 - Corresponding input and output plugins are installed for integrating with input source and with elasticsearch event sink.

Concern
 - If configuration needs to be updated, The configuration file needs to be updated on hundreds of client nodes using an external config management system like chef/ansible, etc

Proposal
 - Bring in creation of another type of first class plugin (instantiated by Engine) called CONFIG_REGISTRY in plugin.rb and allow for a new type of plugin called config plugin with prefix config_
 - This will allow the development of plugins that integrate with central fleet managers from where fluentd configuration can be managed.

**Comment by repeatedly** [comment]
HTTP `@include` is not enough for this?

https://docs.fluentd.org/v0.12/articles/config-file#(6)-re-use-your-config:-the-“@include”-directive

**Comment by rhonnava** [comment]
@include does not help as that would still need an external administration tool to reload the config on all fluentd instances explicitly by sending SIGHUP  or other means. I was thinking of a plugin that will poll a given HTTP(S) URI at scheduled interval and reload config if there is a change. 

One such example I can think of is OSQuery TLS config plugin where the plugin gets config from a remote API and keeps polling for it at a scheduled interval (https://osquery.readthedocs.io/en/stable/deployment/remote/#remote-server-api)

**Comment by repeatedly** [comment]
Hmm... Input plugin seems enough for me.
