### ISSUE TITLE
confuse about td-agent version

### ISSUE THREAD

**Issue by jeremywu0127** [fluent/fluentd#1750]
we install `fluentd` by using `td-agent`  which installed by `curl -L https://toolbelt.treasuredata.com/sh/install-redhat-td-agent2.sh | sh`,  but we find that the version of `td-agent` is different as well as `fluentd`, looks like:

**Host A** :
```
[root@hosta /tmp]#rpm -qa|grep td-agent
td-agent-2.3.5-1.el2017.x86_64
[root@hosta /tmp]#td-agent --version
td-agent 0.14.21
[root@hosta /tmp]#cat /etc/issue
Amazon Linux AMI release 2014.09
Kernel \r on an \m
```
**Host B** :
```
[root@hostb /tmp]#rpm -qa|grep td-agent
td-agent-2.3.5-1.el2017.x86_64
[root@hostb /tmp]#td-agent --version
td-agent 0.12.36 /etc/issue
[root@hostb /tmp]#cat /etc/issue
Amazon Linux AMI release 2014.09
Kernel \r on an \m
```
**Host C**:
```
[root@hostc /tmp]#rpm -qa|grep td-agent
td-agent-2.3.6-0.el2017.x86_64
[root@hostc /tmp]#td-agent --version
td-agent 0.12.40
[root@hostc /tmp]#cat /etc/issue
Amazon Linux AMI release 2014.09
Kernel \r on an \m
```
**Host D**
```
[root@hostd /tmp]# rpm -qa|grep td-agent
td-agent-2.3.6-0.el2017.x86_64
[root@hostd /tmp]# td-agent --version
td-agent 0.14.22
[root@hostd /tmp]# cat /etc/issue
Amazon Linux AMI release 2017.03
Kernel \r on an \m
```
I have 3 questions:
1. why cause the above scenario?
2.  how can I specify the `td-agent` version or the `fluentd` version?   
3. my install script is `td-agent2`, why does it install `fluentd-0.14`?

**Comment by repeatedly** [comment]
> 1.

I'm not sure. td-agent itself doesn't provide package for 2014.09.
Maybe, Install date is the cause because `latest` is changed when new amazon linux is released.

> 2. 3.

Maybe this: https://docs.fluentd.org/v0.12/articles/plugin-management#plugin-version-management

**Comment by jeremywu0127** [comment]
just one more question, in our case, forwarder is `0.14.22` and  aggregator is `0.12.36`, we use `out_s3` on aggregator, but logs of aggregator shows error:
```
2017-11-15 11:46:16 +0800 [warn]: emit transaction failed: error_class=MessagePack::UnknownExtTypeError error="unexpected extension type" tag="k8s.nginx.access2s3"
```
so, is this caused by different version of `td-agent`?

**Comment by repeatedly** [comment]
See: https://docs.fluentd.org/v0.12/articles/in_forward#i-got-messagepack::unknownexttypeerror-error.-why?

**Comment by jeremywu0127** [comment]
it does help! thanks a lot
