### ISSUE TITLE
optional tzinfo-data dependency

### ISSUE THREAD

**Issue by sandrobonazzola** [fluent/fluentd#1761]
Check [CONTRIBUTING guideline](https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md) first and here is the list to help us investigate the problem.

- fluentd or td-agent version. fluentd 0.12.41
- Environment information, e.g. OS. Fedora
- Your problem explanation. If you have an error logs, write it together.

fluentd 0.12.41 requires rubygem-tzinfo-data but according to https://bugzilla.redhat.com/show_bug.cgi?id=1373004#c2 it's not needed. You may consider dropping the dependency on linux systems at least.

**Comment by repeatedly** [comment]
The problem is rubygems doesn't support such conditional dependency for now.
If we drop tzinfo-data dependency, windows users failed to start by default.
This is not good experience.

**Comment by okkez** [comment]
If tzinfo-data gem is necessary only for Windows.
How about following patch?

```diff
diff --git a/fluentd.gemspec b/fluentd.gemspec
index 26b2e298..6ea3a279 100644
--- a/fluentd.gemspec
+++ b/fluentd.gemspec
@@ -26,7 +26,6 @@ Gem::Specification.new do |gem|
   gem.add_runtime_dependency("http_parser.rb", [">= 0.5.1", "< 0.7.0"])
   gem.add_runtime_dependency("sigdump", ["~> 0.2.2"])
   gem.add_runtime_dependency("tzinfo", ["~> 1.0"])
-  gem.add_runtime_dependency("tzinfo-data", ["~> 1.0"])
   gem.add_runtime_dependency("strptime", [">= 0.2.2", "< 1.0.0"])
   gem.add_runtime_dependency("dig_rb", ["~> 1.0.0"])
 
@@ -34,6 +33,7 @@ Gem::Specification.new do |gem|
   fake_platform = ENV['GEM_BUILD_FAKE_PLATFORM'].to_s
   gem.platform = fake_platform unless fake_platform.empty?
   if /mswin|mingw/ =~ fake_platform || (/mswin|mingw/ =~ RUBY_PLATFORM && fake_platform.empty?)
+    gem.add_runtime_dependency("tzinfo-data", ["~> 1.0"])
     gem.add_runtime_dependency("win32-service", ["~> 0.8.3"])
     gem.add_runtime_dependency("win32-ipc", ["~> 0.6.1"])
     gem.add_runtime_dependency("win32-event", ["~> 0.6.1"])
```

**Comment by repeatedly** [comment]
Currently, it doesn't resolve the problem because above `if` works with only gem build phase.
