### ISSUE TITLE
support multiline parser in in_tcp plugin

### ISSUE THREAD

**Issue by jpraet** [fluent/fluentd#1762]
From the doc:

> Unlike other parser plugins, this plugin needs  special code in input plugin, e.g. handle format_firstline. So  currently, in_tail plugin works with `multiline` but other input plugins  don't work with `multiline`.

It would be nice to support multiline parsing in the in_tcp plugin as well. I am using in_tcp to process log events that are delimited by '\n'. But the log message inside the log event might also contain '\n'. So with the multiline parser I would be able to aggregate those in a single log event, which is currently not possible.

**Comment by kenhys** [comment]
v0.12 is not maintained anymore, I'll close it.
