### ISSUE TITLE
Missing text in 0.12 docs for Buffer plugin

### ISSUE THREAD

**Issue by sparr** [fluent/fluentd#1765]
https://docs.fluentd.org/v0.12/articles/buffer-plugin-overview

> The suffixes “k” (KB), “m” (MB), and “g” (GB) can be used for `buffer_chunk_l

This paragraph is cut off mid-word. Obviously it's referring to buffer_chunk_limit, but maybe it should also mention something else after?

**Comment by repeatedly** [comment]
Thanks for pointing this out. Just fixed.

Next, please use fluentd-docs repository for documentation issue instead.
