### ISSUE TITLE
buffer_total_queued_size from monitor_agent is always increasing

### ISSUE THREAD

**Issue by kmevissen** [fluent/fluentd#1766]
Environment:
- fluentd version 0.14.23 in docker containers running in Kubernetes
- using [prometheus plugin](https://github.com/fluent/fluent-plugin-prometheus) for monitoring

Configuration:
- buffer type memory
- Collecting metrics from MonitorAgent:
```xml 
    <source>
      @type prometheus_monitor
    </source>
```

The prometheus metric called fluentd_output_status_buffer_total_bytes is increasing over time, and doesn't go down over time. This metric is taken from MonitorAgent's [buffer_total_queued_size](https://github.com/fluent/fluent-plugin-prometheus/blob/master/lib/fluent/plugin/in_prometheus_output_monitor.rb#L55), which in turn is based on [@buffer.stage_size](https://github.com/fluent/fluentd/blob/v0.14.23/lib/fluent/plugin/in_monitor_agent.rb#L282)

We noticed this increasing behaviour through time series in Prometheus where this queue size bytes is larger than the total memory used by the kubernetes pod running fluentd. Also the memory used by the pod is completely stable, while the queue size bytes is increasing over time.
After the buffer size values have gone up we've stopped data streams to reach the input and the buffer size value didn't drop down, but instead remained stable at the high value it had reached.

It looks like this \@buffer.stage_size is not reflecting the actual buffer byte size correctly. Shouldn't the \@buffer.queue_size be used in stead?

The buffer_queue_length from MonitorAgent is correctly reflecting the size, going up (or down to minimum of 0), which is what I'd expect to happen for the queue byte size as well.

**Comment by repeatedly** [comment]
> It looks like this @buffer.stage_size is not reflecting the actual buffer byte size correctly

Does it mean you see same behaviour with `in_monitor_agent`, not `in_prometheus_monitor`?

**Comment by repeatedly** [comment]
`Buffer#stage_size` is decreased when stage chunk is enqueued: https://github.com/fluent/fluentd/blob/363b1af858aab34d90d9a98d63107b1206afd141/lib/fluent/plugin/buffer.rb#L401

So if prometheus plugin uses this value directly, the exported value should be also decreased.
