### ISSUE TITLE
uninitialized constant Fluent::TextParser::Parser(fluentd v-0.12.33)

### ISSUE THREAD

**Issue by Ankushaccc** [fluent/fluentd#1769]
I  am using fluentd v-0.12.33. I am using json_in_json pluggin, it is giving me 
**uninitialized constant Fluent::TextParser::Parser**

/usr/lib/ruby/gems/2.3.0/gems/fluent-plugin-json-in-json-0.1.4/lib/fluent/plugin/parser_json_in_json.rb:5:in <class:TextParser>': 
uninitialized constant Fluent::TextParser::Parser (NameError) Did you mean? 
Parts from /usr/lib/ruby/gems/2.3.0/gems/fluent-plugin-json-in-json-0.1.4/lib/fluent/plugin/parser_json_in_json.rb:4:inmodule:Fluent'
from /usr/lib/ruby/gems/2.3.0/gems/fluent-plugin-json-in-json-0.1.4/lib/fluent/plugin/parser_json_in_json.rb:3:in `<top (required)>'

This pluggin is also availble on -- 

[https://github.com/gmr/fluent-plugin-json-in-json/blob/master/lib/fluent/plugin/parser_json_in_json.rb](url)

**Comment by cosmo0920** [comment]
Could you report this issue in https://github.com/gmr/fluent-plugin-json-in-json?
This is not Fluentd's issue.

**Comment by repeatedly** [comment]
It seems `require 'fluent/parser'` is missing in their code.
