### ISSUE TITLE
Fluentd forward Output Plugin: active/standby issue.

### ISSUE THREAD

**Issue by sergeyarl** [fluent/fluentd#1772]
Hi! 

We'd like to have an Active-Standby log servers pair. 

configuration of our forwarder hosts is the following:

```
...

<match **>
  @type forward

  heartbeat_type tcp
  send_timeout 60s
  recover_wait 10s
  heartbeat_interval 1s
  phi_threshold 16
  hard_timeout 60s

  <server>
    name logs1
    host logs1
    port 8889
    weight 60
  </server>

  <server>
    name logs2
    host logs2
    port 8889
    weight 60
    standby
  </server>

...
</match>
```
Fluentd documentation says 

> standby
> 
> Marks a node as the standby node for an Active-Standby model between Fluentd nodes. When an active node goes down, the standby node is promoted to an active node. The standby node is not used by the out_forward plugin until then.

That works perfectly. When I switch off logs1 node, Fluentd starts to send  logs to logs2 node. However when I switch logs1 node back on, Fluentd starts to distribute logs among both logs1 and logs2 nodes. It looks like both of them become active. And no standby nodes are present. 

Is it a normal behaviour? 

Thank you! 

Regards,
Sergey

**Comment by repeatedly** [comment]
That's weird.
I will check it after finished KubeCon.

**Comment by repeatedly** [comment]
I found a bug of heartbeat handling for TCP and send a patch: https://github.com/fluent/fluentd/pull/1784
