### ISSUE TITLE
record_transformer - unknown placeholder

### ISSUE THREAD

**Issue by epcim** [fluent/fluentd#1782]
I use in_kmsg on fluentbit, forward to fluentd and then I want to replace "mgs" key in record to "message".

- fluentd or td-agent version.
gem, 1.0.0 (but even the older 0.14.x)

- Environment information, e.g. OS.
ubuntu

- Your configuration
```
      <label @MAINSTREAM >

          ## FIXME: For debuging purposes

          <filter system.log.kernel >

             @type stdout

          </filter>

          <filter system.log.kernel >

              @type record_transformer

              renew_record false

              <record>

                  message ${record['msg']}

                  # message ${msg}    ## same issues

              </record>

          </filter>

          <filter system.log.kernel >

              @type record_transformer

              renew_record false

              remove_keys [ "msg" ]

          </filter>

```

- Problem - unknown placeholder `${record['msg']}` found`
- The same with `${msg}`

```
2017-12-07 14:54:14.000964150 +0000 system.log.kernel: {"priority":4,"sequence":5761471,"sec":12874928,"usec":964150,"msg":"NFS: state manager: check lease failed on NFSv4 server 10.1.1.233 with error 93","hostname":"control-node2.lab.zzz.xxx.ttt"}
2017-12-07 14:54:19.000967199 +0000 system.log.kernel: {"priority":4,"sequence":5761472,"sec":12874933,"usec":967199,"msg":"NFS: state manager: check lease failed on NFSv4 server 10.1.1.233 with error 93","hostname":"control-node2.lab.zzz.xxx.ttt"}
2017-12-07 15:39:52 +0000 [warn]: #0 unknown placeholder `${record['msg']}` found
2017-12-07 15:39:52 +0000 [warn]: #0 unknown placeholder `${record['msg']}` found
```

Corresponding source:
https://github.com/fluent/fluentd/blob/master/lib/fluent/plugin/filter_record_transformer.rb#L235

Am I missing something?

**Comment by repeatedly** [comment]
Because you use `record['msg']`, not `record["msg"]`.
Without `enable_ruby`, `${}` placeholder is not ruby syntax, so `record['key']` is not supported for now.
We can support it but it decreases the `record_transformer` performance.

**Comment by epcim** [comment]
OK, thanks, please mind the doc, it's missing mention about single apostrophes and the example miss the enable_ruby as well.
```
<filter foo.bar>
  @type record_transformer
  <record>
    hostname "#{Socket.gethostname}"
    tag ${tag}
  </record>
</filter>
```

**Comment by repeatedly** [comment]
Above example, `enable_ruby` is not needed because you don't use ruby script inside `${}`.

**Comment by epcim** [comment]
Undrstand, but I got the same issue with:
```
 <filter system.log.kernel >

              @type record_transformer

              renew_record false

              <record>

                  message ${msg}

              </record>

          </filter>
```

**Comment by repeatedly** [comment]
See FAQ's first: https://docs.fluentd.org/v1.0/articles/filter_record_transformer#faq

**Comment by repeatedly** [comment]
And just added second for `record['key']`.

**Comment by repeatedly** [comment]
`${tag}` and `${msg}` are different. See `<record>` directive document: https://docs.fluentd.org/v1.0/articles/filter_record_transformer#<record>-directive

**Comment by epcim** [comment]
Finally got the point. Thanks!
