### ISSUE TITLE
Error <Errno::EACCES: Permission denied @ dir_s_mkdir - /var/log/td-agent>

### ISSUE THREAD

**Issue by nupurbansal8** [fluent/fluentd#1785]
Check [CONTRIBUTING guideline](https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md) first and here is the list to help us investigate the problem.

- fluentd or td-agent version : fluentd:v0.12-debian
- Environment information : CentOS Linux release 7.1.1503 (Core)
- Your configuration : I have used fluentd with docker-compose to run as a container. fluentd.conf file is:

```
<source>
  @type forward
</source>
<match golang.**>
      type forward
      send_timeout 60s
      buffer_type file
      buffer_path /var/log/td-agent/test11/td-agent.buffer
      buffer_chunk_limit 8M
      buffer_queue_limit 128
      flush_interval 5s
      max_retry_wait 300
      disable_retry_limit
      recover_wait 10s
      heartbeat_type udp
      heartbeat_interval 1s
      phi_threshold 16
      retry_limit 50
      hard_timeout 60s
      <server>
            host 192.170.X.X
            port 24226
            weight 60
      </server>
</match>
```

This file is used to read docker logs and transfer to another td-agent on an external server.

- Your problem explanation : I am getting following error on running docker-compose up:

2017-12-11 05:51:21 +0000 [error]: unexpected error error_class=Errno::EACCES error=#<Errno::EACCES: Permission denied @ dir_s_mkdir - /var/log/td-agent>

And am not able to receive logs in my kibana attached to the td-agent on external server.

**Comment by muhahacz** [comment]
/var/log is owned by root:root, fluentd container is running under different user: https://github.com/fluent/fluentd-docker-image/blob/master/v0.12/debian/entrypoint.sh

**Comment by repeatedly** [comment]
This seems not fluentd bug, so closed.

At first, fluentd image doesn't create td-agent related directories.

**Comment by nganbph10804** [comment]
> /var/log is owned by root:root, fluentd container is running under different user: https://github.com/fluent/fluentd-docker-image/blob/master/v0.12/debian/entrypoint.sh

Can you explain more about this and how to fix?  Please

**Comment by keeth** [comment]
I fixed this by adding a couple of lines to my Dockerfile:

```
RUN mkdir -p /var/log/fluent
RUN chown -R fluent /var/log/fluent
```

Here's my complete Dockerfile, which adds the s3 plugin:

```
FROM fluent/fluentd:v1.16-1

# Use root account to use apk
USER root

# below RUN includes plugin as examples elasticsearch is not required
# you may customize including plugins as you wish
RUN apk add --no-cache --update --virtual .build-deps \
        sudo build-base ruby-dev \
 && sudo gem install fluent-plugin-s3 \
 && sudo gem sources --clear-all \
 && apk del .build-deps \
 && rm -rf /tmp/* /var/tmp/* /usr/lib/ruby/gems/*/cache/*.gem

COPY fluent.conf /fluentd/etc/

RUN mkdir -p /var/log/fluent
RUN chown -R fluent /var/log/fluent

USER fluent
```
