### ISSUE TITLE
out_forward raw tcp json instead of msgpack?

### ISSUE THREAD

**Issue by muhahacz** [fluent/fluentd#1786]
Is possible to force out_forward plugin to send raw tcp json data instead of msgpack? 
I need to send it on 127.0.0.1 (splunk universal forwarder - cannot handle splunk HEC input) that there is no point to use msgpack to safe data traffic.
Thanks

EDIT:
I used in 0.12 https://github.com/desdic/fluent-plugin-jsontcp plugin, but it does not work in 1.0

**Comment by repeatedly** [comment]
> Is possible to force out_forward plugin to send raw tcp json data instead of msgpack?

No way. out_forward focuses on fluentd forward protocol.
Supporting other protocol is not responsibility of this plugin.

> fluent-plugin-jsontcp

It seems missing `require 'fluent/output'`.
Sending patch seems better.
