### ISSUE TITLE
Confusion around which fluentd version is "production"

### ISSUE THREAD

**Issue by tehranian** [fluent/fluentd#1798]
From https://www.fluentd.org/download :

* The above page says : `Fluentd (v1.0, current stable)`
* This page also says : `Fluentd v0.12.42 (current stable. recommend for production)`

It seems to me like there cannot be two different versions which are "current stable" :)
Is it accurate that v0.12 is still recommended for production, or is that a historical note? 

Thanks,
Dan

**Comment by repeatedly** [comment]
It seems the documention mistake.
I will update it.

**Comment by repeatedly** [comment]
Fixed by https://github.com/fluent/fluentd-website/commit/f82f3caedb3d6c2d27763d15d88cb41200874cad

**Comment by repeatedly** [comment]
BTW, if you have a problem with fluentd website, plase post it on fluentd-website repository instead.
