### ISSUE TITLE
Expose record_accessor internal API

### ISSUE THREAD

**Issue by cosmo0920** [fluent/fluentd#1806]
Check [CONTRIBUTING guideline](https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md) first and here is the list to help us investigate the problem.

- fluentd or td-agent version. 

Fluentd v1

- Environment information,

All supported Operating Systems

- Your configuration

Nope. It is feature request for `record_accessor`.

- Your problem explanation. If you have an error logs, write it together.

Currently, `record_accessor` does not expose internal `@keys` instance.
We want to use this variable in [fluent-plugin-anonymizer](https://github.com/y-ken/fluent-plugin-anonymizer) like this:

https://github.com/cosmo0920/fluent-plugin-anonymizer/blob/0bb45b93cebc996b6ccb13b5b7a2a71b4682cf14/lib/fluent/plugin/filter_anonymizer.rb#L242-L249

##### Additional request

~~Now, `@keys` does not handle keys correctly when using `$['your']['some']['key']` notation.
We also want to use this variable (or API?) above use case.~~

Already supported above. :bowing_man:

**Comment by repeatedly** [comment]
LGTM
