### ISSUE TITLE
Date parse problem in log lines

### ISSUE THREAD

**Issue by inthuriel** [fluent/fluentd#1811]
- **fluentd**: 1.0.0
- _env_: linux **Ubuntu 16.04**

We're using **fluentd** with **td-agent-bit** to push log to **elasticsearch** on very small part of logs (few per day) date is wrongly parsed before push to **elasticsearch**.

Example log line:
```
2018-01-02 22:35:24.230409 7f0bc4d36700  0 -- 192.168.000.000:0000/560138 >> 192.168.000.000:0000/553077 conn(0x556a26292000 :6825 s=STATE_ACCEPTING_WAIT_CONNECT_MSG_AUTH pgs=0 cs=0 l=0).handle_connect_msg accept connect_seq 42 vs existing csq=41 existing_state=STATE_STANDBY
```

To parse this we're using **td-agent-bit** parser:
```[PARSER]
    Name ceph
    Format regex
    Regex ^(?<log_time>[^ ][-.\d\+:T]+[ ]*[.:\d]*)\s+(?<message>.*)$
    Time_Format %Y-%m-%d %H:%M:%S.%L
    Time_Keep Off
    Time_Key log_time
```
and line is parser correctly: http://rubular.com/r/FfCEgZI1Hg

in **fluentd** configuration we're using `time_as_integer`:
```    
<match ** >
                  @type elasticsearch
                  @id fluentd-other
                  @log_level debug
                  host elasticsearch
                  port 9200
                  index_name fluentd-other
                  type_name fluentd
                  logstash_format true
                  time_as_integer true
                  #index_name fluent-openstack
                  #flush_mode #default,interval,immediate,lazy
                  #flush_interval 30
                  #flush_thread_count 4
                  ssl_verify false
                  tag_key tag
                  include_tag_key true
                  #time_key log_time
       [...]
</match>
```

in given log line example date: **2018-01-02 22:35:24.230409** was converted to: **2059-07-15T23:39:24.000000000** in **elastic** so:
```
2059-07-15T23:39:24.000000000 -> epoch: 2825530764
```
instead of _proper_:
```
2018-01-02 22:35:24.230409 -> epoch: 1514928924
```

As `fluentd` uses _standard_ `ruby` to convert time to int at output, one place where error can occurs is parsing sting to time on input, to do that `fluentd` uses it's own class:
https://github.com/fluent/fluentd/blob/master/lib/fluent/time.rb
but in quick tests I didn’t found any issues there.

**Comment by repeatedly** [comment]
Which fluentd version do you use, v0.12 or v1.0?

**Comment by inthuriel** [comment]
We're using v1.0

**Comment by pirankashani** [comment]
I think there is a typo for parser format `regexp` ,as you mentioned in the issue.

**Comment by inthuriel** [comment]
@repeatedly have you any idea about that?
he updated also `elastic` to latest `6.1` version but it didn't helped.

**Comment by repeatedly** [comment]
Does out_stdout print wrong result?
If not, your elasticsearch plugin conf is wrong.
Some users use fluent-plugin-elasticsearch with fluentd v1 and elasticsearch v5 or v6 but no this issue.
If the problem is elasticsearch plugin issue, I will close the issue.
