### ISSUE TITLE
[Windows] supervisor.rb:689:in `read': No such file or directory

### ISSUE THREAD

**Issue by elinshu** [fluent/fluentd#1812]
- td-agent : td-agent-3.0.1-0-x64-beta2
- OS : windows 8.1 pro / 64bit
- Your configuration : nothing added
- Your problem explanation. If you have an error logs, write it together.

I just follow this guide(https://docs.fluentd.org/v1.0/articles/install-by-msi)
and error occured after execute 'fluentd -c conf\td-agent.conf'.

error : 
C:/opt/td-agent/embedded/lib/ruby/gems/2.3.0/gems/fluentd-0.14.13/lib/fluent/supervisor.rb:689:in `read': No such file or directory 

@ rb_sysopen - conf\td-agent.conf (Errno::ENOENT)
        from C:/opt/td-agent/embedded/lib/ruby/gems/2.3.0/gems/fluentd-0.14.13/lib/fluent/supervisor.rb:689:in `read_config'
        from C:/opt/td-agent/embedded/lib/ruby/gems/2.3.0/gems/fluentd-0.14.13/lib/fluent/supervisor.rb:431:in `run_supervisor'
        from C:/opt/td-agent/embedded/lib/ruby/gems/2.3.0/gems/fluentd-0.14.13/lib/fluent/command/fluentd.rb:294:in `<top (required)>'
        from C:/opt/td-agent/embedded/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/opt/td-agent/embedded/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/opt/td-agent/embedded/lib/ruby/gems/2.3.0/gems/fluentd-0.14.13/bin/fluentd:5:in `<top (required)>'
        from C:/opt/td-agent/embedded/bin/fluentd:22:in `load'
        from C:/opt/td-agent/embedded/bin/fluentd:22:in `<main>'

**Comment by repeatedly** [comment]
Ah, specifying full path of your configuration should resolve this problem.
We will update the document later.

BTW, please open document related issue in fluentd-docs, not fluentd repository.
