### ISSUE TITLE
Feature Request: in_syslog Add option for using message_format auto along with the ability to add additional Custom Parsers

### ISSUE THREAD

**Issue by bcharboneauiherb** [fluent/fluentd#1829]
td-agent 3.1.1
Windows Server 2012 R2

I would like to see an option to use custom parsers by specifying values such as the ones below in the td-agent.conf

Currently I am adding additional formats for syslogs that do not match the 2 default patterns to parser_syslog.rb. However, it would be easier for users and cleaner to add an option within the config file.

This is how i would like to see it in the config as I am sure it would help others as well: 
```
<source>
  @type syslog
  ...
  <parse>
    message_format auto
    <CUSTOM1>
       name {name for custom 1 parser}
       time_format {time format for custom 1 parser}
       REGEXP_DETECT {Auto Detect Pattern for custom 1 parser}
       REGEXP {Full REGEXP for Matching for custom 1 parser}
    </CUSTOM1>
    <CUSTOM2>
       name {name for custom 2 parser}
       time_format {time format for custom 2 parser}
       REGEXP_DETECT {Auto Detect Pattern for custom 2 parser}
       REGEXP {Full REGEXP for Matching for custom 2 parser}
    </CUSTOM2>
    <...>
    </...>
  </parse>
</source>

**Comment by repeatedly** [comment]
Yeah, specifying multi-format-parser or original parser may resolve this problem.
