### ISSUE TITLE
Custom index name doesn't work with nested field

### ISSUE THREAD

**Issue by ahrtr** [fluent/fluentd#1836]
The configuration file for fluentd is as below,

```
    <source>
      @type tail
      path /var/lib/docker/containers/*/*.log
      tag fluentd
      <parse>
        @type json
        time_key time
        keep_time_key true
      </parse>
      refresh_interval 5
    </source>
    <filter **>
        @type parser
        format json
        key_name log
        reserve_data true
        hash_value_field log
    </filter>
    <match fluentd>
      @type elasticsearch
      host elasticsearch
      port 9200
      flush_interval 10s
      index_name test-${log.tenantid}-%Y%m%d
      <buffer tag, log.tenantid, time>
         @type memory
         timekey 3600
      </buffer>
    </match>
```

I generated the following examle log entry,

`{"level":"info", "tenantid":"tenant1", "msg":"hello"}`

And docker converted the above log entry into:
`{"log": "{\"level\":\"info\", \"tenantid\":\"tenant1\", \"msg":\"hello\"}", "stream":"stderr", "time":"2018-01-27T02:38:16.382229755Z"`

Fluentd sent the log to elasticsearch successfully, and I could see the log on Kibana as well. But the issue was that the index name was "test--20180127", which wasn't what I expected. I was expecting to see the index name "test-tenant1-20180127".

**Using Fluentd and ES plugin versions**
OS version: Oracle Linux 7.3
Fluentd image was built with the following Dockerfile:
```
FROM fluent/fluentd:v0.12.33-debian
......
gem install fluent-plugin-elasticsearch
......
```

**Comment by ahrtr** [comment]
Previously I raised this issue for fluentd-plugin-elasticsearch, but I was requested to raise a feature request on Fluentd repository. please seee the following link,

> https://github.com/uken/fluent-plugin-elasticsearch/issues/352

**Comment by cosmo0920** [comment]
Sorry for my misunderstanding.
This requested feature can work with `index_name test-${$.log.tenantid}-%Y%m%d` instead of `index_name test-${log.tenantid}-%Y%m%d`.

**Comment by cosmo0920** [comment]
Detailed descriptions is https://www.fluentd.org/blog/fluentd-v0.14.22-has-been-released.

**Comment by cosmo0920** [comment]
> I wonder whether adoping buffer will cause fluentd to lose log entries when elasticsearch crashes or restarts?

For preventing to lose log, you can use `@type file` in buffer configuration:

```aconf
<buffer tag, $.log.tenantid, time>
  @type file
  timekey 3600
</buffer>
```
 
If you don't use `$.log.tenantid` in buffer directive argument, emitting chunk order will be changed.
But it does not cause to lose log in case of using file type buffer.

**Comment by ZMMWMY** [comment]
> Thanks for the info.

could you show you new configuration for custom index name ? thanks

**Comment by ZMMWMY** [comment]
> > I wonder whether adoping buffer will cause fluentd to lose log entries when elasticsearch crashes or restarts?
> 
> For preventing to lose log, you can use `@type file` in buffer configuration:
> 
> ```apache-config
> <buffer tag, $.log.tenantid, time>
>   @type file
>   timekey 3600
> </buffer>
> ```
> 
> If you don't use `$.log.tenantid` in buffer directive argument, emitting chunk order will be changed.
> But it does not cause to lose log in case of using file type buffer.

hey ,i try to use ${$.log.tenantid} ,but it does not work , this is my configuration
```
<source>
  @type forward
  port 24224
  bind 0.0.0.0
  <parse>
    @type json
    time_key time
    keep_time_key true
  </parse>
</source>

<filter *>
  @type record_transformer
  <record>
    yay test
  </record>
</filter>

<match *>
  @type elasticsearch
  host xx
  port 9200
  flush_interval 10s
  logstash_format true
  logstash_prefix ${$.yay}
  user xx
  password xx
</match>
```

**Comment by dobesv** [comment]
Here's an example solution using `target_index_key` and the `record_modifier` plugin:

https://gist.github.com/dobesv/ffb27537fcc2df74ce8049fcfb937c4d
