### ISSUE TITLE
connect_write timeout reached

### ISSUE THREAD

**Issue by elinshu** [fluent/fluentd#1844]
Check [CONTRIBUTING guideline](https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md) first and here is the list to help us investigate the problem.

- fluentd or td-agent version.
   3.1.1
- Environment information, e.g. OS.
   windows server 2008 / 64bit
- Your configuration
```
  <source>
    @type syslog
    tag "system"
  </source>
  <match **>
    @type elasticsearch
    logstash_format true
    host 192.168.0.223
    port 9200
    index_name fluentd
    type_name fluentd
    flush_interval 1s
    <buffer>
      flush_interval 1s
    </buffer>
  </match>
```
- Your problem explanation. If you have an error logs, write it together.
```
2018-02-05 09:56:43 +0000 [warn]: #0 [output_td] secondary type should be same w
ith primary one primary="Fluent::Plugin::TreasureDataLogOutput" secondary="Fluen
t::Plugin::FileOutput"

2018-02-05 09:57:45 +0000 [warn]: #0 failed to flush the buffer. retry_time=0 ne
xt_retry_seconds=2018-02-05 09:57:46 +0000 chunk="56474145504784b28cffa6ccf3a058
84" error_class=Fluent::Plugin::ElasticsearchOutput::ConnectionFailure error="Ca
n not reach Elasticsearch cluster ({:host=>\"192.168.0.223\", :port=>9200, :sche
me=>\"http\"})! connect_write timeout reached"
  2018-02-05 09:57:45 +0000 [warn]: #0 C:/opt/td-agent/embedded/lib/ruby/gems/2.
4.0/gems/fluent-plugin-elasticsearch-2.4.0/lib/fluent/plugin/out_elasticsearch.r
b:201:in `rescue in client'
  2018-02-05 09:57:45 +0000 [warn]: #0 C:/opt/td-agent/embedded/lib/ruby/gems/2.
4.0/gems/fluent-plugin-elasticsearch-2.4.0/lib/fluent/plugin/out_elasticsearch.r
b:198:in `client'
  2018-02-05 09:57:45 +0000 [warn]: #0 C:/opt/td-agent/embedded/lib/ruby/gems/2.
4.0/gems/fluent-plugin-elasticsearch-2.4.0/lib/fluent/plugin/out_elasticsearch.r
b:430:in `rescue in send_bulk'
  2018-02-05 09:57:45 +0000 [warn]: #0 C:/opt/td-agent/embedded/lib/ruby/gems/2.
4.0/gems/fluent-plugin-elasticsearch-2.4.0/lib/fluent/plugin/out_elasticsearch.r
b:424:in `send_bulk'
  2018-02-05 09:57:45 +0000 [warn]: #0 C:/opt/td-agent/embedded/lib/ruby/gems/2.
4.0/gems/fluent-plugin-elasticsearch-2.4.0/lib/fluent/plugin/out_elasticsearch.r
b:411:in `write'
  2018-02-05 09:57:45 +0000 [warn]: #0 C:/opt/td-agent/embedded/lib/ruby/gems/2.
4.0/gems/fluentd-1.0.2/lib/fluent/plugin/output.rb:1093:in `try_flush'
  2018-02-05 09:57:45 +0000 [warn]: #0 C:/opt/td-agent/embedded/lib/ruby/gems/2.
4.0/gems/fluentd-1.0.2/lib/fluent/plugin/output.rb:1318:in `flush_thread_run'
  2018-02-05 09:57:45 +0000 [warn]: #0 C:/opt/td-agent/embedded/lib/ruby/gems/2.
4.0/gems/fluentd-1.0.2/lib/fluent/plugin/output.rb:439:in `block (2 levels) in s
tart'
  2018-02-05 09:57:45 +0000 [warn]: #0 C:/opt/td-agent/embedded/lib/ruby/gems/2.
4.0/gems/fluentd-1.0.2/lib/fluent/plugin_helper/thread.rb:78:in `block in thread
_create'
```

should I check my network condition?
when tested on different server(windows server 2010/64bit) with the same setting, there was no problem.

**Comment by repeatedly** [comment]
This seems elaticsearch plugin, maybe elasticsearch gem or network condition, issue.
Closed.

**Comment by mingyuejishi** [comment]
> Check [CONTRIBUTING guideline](https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md) first and here is the list to help us investigate the problem.
> 
> * fluentd or td-agent version.
>   3.1.1
> * Environment information, e.g. OS.
>   windows server 2008 / 64bit
> * Your configuration
> 
> ```
>   <source>
>     @type syslog
>     tag "system"
>   </source>
>   <match **>
>     @type elasticsearch
>     logstash_format true
>     host 192.168.0.223
>     port 9200
>     index_name fluentd
>     type_name fluentd
>     flush_interval 1s
>     <buffer>
>       flush_interval 1s
>     </buffer>
>   </match>
> ```
> 
> * Your problem explanation. If you have an error logs, write it together.
> 
> ```
> 2018-02-05 09:56:43 +0000 [warn]: #0 [output_td] secondary type should be same w
> ith primary one primary="Fluent::Plugin::TreasureDataLogOutput" secondary="Fluen
> t::Plugin::FileOutput"
> 
> 2018-02-05 09:57:45 +0000 [warn]: #0 failed to flush the buffer. retry_time=0 ne
> xt_retry_seconds=2018-02-05 09:57:46 +0000 chunk="56474145504784b28cffa6ccf3a058
> 84" error_class=Fluent::Plugin::ElasticsearchOutput::ConnectionFailure error="Ca
> n not reach Elasticsearch cluster ({:host=>\"192.168.0.223\", :port=>9200, :sche
> me=>\"http\"})! connect_write timeout reached"
>   2018-02-05 09:57:45 +0000 [warn]: #0 C:/opt/td-agent/embedded/lib/ruby/gems/2.
> 4.0/gems/fluent-plugin-elasticsearch-2.4.0/lib/fluent/plugin/out_elasticsearch.r
> b:201:in `rescue in client'
>   2018-02-05 09:57:45 +0000 [warn]: #0 C:/opt/td-agent/embedded/lib/ruby/gems/2.
> 4.0/gems/fluent-plugin-elasticsearch-2.4.0/lib/fluent/plugin/out_elasticsearch.r
> b:198:in `client'
>   2018-02-05 09:57:45 +0000 [warn]: #0 C:/opt/td-agent/embedded/lib/ruby/gems/2.
> 4.0/gems/fluent-plugin-elasticsearch-2.4.0/lib/fluent/plugin/out_elasticsearch.r
> b:430:in `rescue in send_bulk'
>   2018-02-05 09:57:45 +0000 [warn]: #0 C:/opt/td-agent/embedded/lib/ruby/gems/2.
> 4.0/gems/fluent-plugin-elasticsearch-2.4.0/lib/fluent/plugin/out_elasticsearch.r
> b:424:in `send_bulk'
>   2018-02-05 09:57:45 +0000 [warn]: #0 C:/opt/td-agent/embedded/lib/ruby/gems/2.
> 4.0/gems/fluent-plugin-elasticsearch-2.4.0/lib/fluent/plugin/out_elasticsearch.r
> b:411:in `write'
>   2018-02-05 09:57:45 +0000 [warn]: #0 C:/opt/td-agent/embedded/lib/ruby/gems/2.
> 4.0/gems/fluentd-1.0.2/lib/fluent/plugin/output.rb:1093:in `try_flush'
>   2018-02-05 09:57:45 +0000 [warn]: #0 C:/opt/td-agent/embedded/lib/ruby/gems/2.
> 4.0/gems/fluentd-1.0.2/lib/fluent/plugin/output.rb:1318:in `flush_thread_run'
>   2018-02-05 09:57:45 +0000 [warn]: #0 C:/opt/td-agent/embedded/lib/ruby/gems/2.
> 4.0/gems/fluentd-1.0.2/lib/fluent/plugin/output.rb:439:in `block (2 levels) in s
> tart'
>   2018-02-05 09:57:45 +0000 [warn]: #0 C:/opt/td-agent/embedded/lib/ruby/gems/2.
> 4.0/gems/fluentd-1.0.2/lib/fluent/plugin_helper/thread.rb:78:in `block in thread
> _create'
> ```
> 
> should I check my network condition?
> when tested on different server(windows server 2010/64bit) with the same setting, there was no problem.

do you solve the problem ,i meet the same question,do you know how to solve it?

**Comment by golimer** [comment]
same here

**Comment by mingyuejishi** [comment]
> same here

reconnect_on_error true
reload_on_failure true
reload_connections false

**Comment by linbingdouzhe** [comment]
> > same here
> 
> reconnect_on_error true
> reload_on_failure true
> reload_connections false

in my case ,this is config not work for me

**Comment by cosmo0920** [comment]
@linbingdouzhe This isssue is already closed and not for Fluentd core. Don't use old issue and say same here.
Thanks!!!!
