### ISSUE TITLE
Time parsing is failing silently

### ISSUE THREAD

**Issue by dcosson** [fluent/fluentd#1848]
Something seems broken with time parsing in version 1.0 and 1.1. (Prior to version 1, I was parsing time in an inline ruby function and using renew_time_key which worked fine. However, my key was named "time" and that seems to have a special meeting as of version 1.0 which breaks my existing configuration, so I figured I would try to do it the new way).

Here's a sample fluent.conf:

```
<source>
  @type http
  port 8889
  bind 0.0.0.0
  <parse>
    time_key time
    time_type string
    time_format %Y-%m-%dT%H:%M:%S.%NZ
    keep_time_key true
  </parse>
</source>

<match **>
  @type stdout
</match>
```

Then I run fluentd via: `docker run -it -v ```pwd```/fluentd_etc:/fluentd/etc -p 8889:8889 fluent/fluentd:v1.1.0`

And I query it with:
`curl -X POST -d 'json={"action":"foo", "time":"2018-01-01T08:01:02.345678999Z"}' http://localhost:8889/some.tag`

I get the following output:

```
2018-02-06 02:06:51 +0000 [info]: parsing config file is succeeded path="/fluentd/etc/fluent.conf"
2018-02-06 02:06:51 +0000 [info]: using configuration file: <ROOT>
  <source>
    @type http
    port 8889
    bind "0.0.0.0"
    <parse>
      time_key "time"
      time_type string
      time_format "%Y-%m-%dT%H:%M:%S.%NZ"
      keep_time_key true
    </parse>
  </source>
  <match **>
    @type stdout
  </match>
</ROOT>
2018-02-06 02:06:51 +0000 [info]: starting fluentd-1.1.0 pid=5 ruby="2.3.6"
2018-02-06 02:06:51 +0000 [info]: spawn command to main:  cmdline=["/usr/bin/ruby", "-Eascii-8bit:ascii-8bit", "/usr/bin/fluentd", "-c", "/fluentd/etc/fluent.conf", "-p", "/fluentd/plugins", "--under-supervisor"]
2018-02-06 02:06:51 +0000 [info]: gem 'fluentd' version '1.1.0'
2018-02-06 02:06:51 +0000 [info]: adding match pattern="**" type="stdout"
2018-02-06 02:06:51 +0000 [info]: adding source type="http"
2018-02-06 02:06:51 +0000 [info]: #0 starting fluentd worker pid=15 ppid=5 worker=0
2018-02-06 02:06:51 +0000 [info]: #0 fluentd worker is now running worker=0
2018-02-06 02:06:51.941641805 +0000 fluent.info: {"worker":0,"message":"fluentd worker is now running worker=0"}
2018-02-06 02:06:53.376000766 +0000 some.tag: {"action":"foo"}
```

As you can see, it seems to recognize all the options and there are no warnings or errors about any unused or incorrect parameters in the config. But it's not actually parsing the time properly, and it's not keeping the key even though I specified that option. I also am unable to trigger an error or warning if I pass in nonsense in the time field that clearly doesn't match the time_format.

I've also double-checked that my time_format is valid in ruby:

```
docker run -it -v `pwd`/fluentd_etc:/fluentd/etc -p 8889:8889 fluent/fluentd:v1.1.0 irb
irb(main):001:0> require('time')
=> true
irb(main):002:0> Time.strptime("2018-01-01T08:01:02.345678999Z", "%Y-%m-%dT%H:%M:%S.%NZ")
=> 2018-01-01 08:01:02 +0000
```

What am I doing wrong here?

**Comment by dcosson** [comment]
(Not sure if #1833 is related, I originally posted this as a comment there but this seems different enough to be a separate issue).

**Comment by ahrtr** [comment]
I just replied your comment in #1833,  

@dcosson It seems that you missed the "@type json" in your parser, so the parser should be as below,

    <parse>
      @type json
      time_key "time"
      time_type string
      time_format "%Y-%m-%dT%H:%M:%S.%NZ"
      keep_time_key true
    </parse>

**Comment by repeatedly** [comment]
ahrtr is corect. in_http's default parsing mechanizm is passing time as a HTTP parameter: https://docs.fluentd.org/v1.0/articles/in_http#time-query-parameter
If you want to handle json format with exsiting mechanizm, please specify json and send json directly: https://docs.fluentd.org/v1.0/articles/in_http#<parse>-directive

**Comment by ganmacs** [comment]
it's a stale issue. I'm closing. if you have any problem, updating fluentd might help it.
