### ISSUE TITLE
Feature request: Filter out specific "bad actors"

### ISSUE THREAD

**Issue by JohnStarich** [fluent/fluentd#1858]
I would like to filter out messages that match multiple conditions. This would allow most logs to flow normally, while filtering out specific "bad actors" producing too many logs.

While this does sound similar to what `filter_grep` provides, it does not support this use-case.

For example, I have logs like the following:

```json
{"level":"debug", "log":"hello!",                 "container_name":"foo"}
{"level":"error", "log":"something bad happened", "container_name":"foo"}
{"level":"debug", "log":"hello!",                 "container_name":"bar"}
```

My goal is to filter out `debug` logs for container_name `foo`.

So output would be:

```json
{"level":"error", "log":"something bad happened", "container_name":"foo"}
{"level":"debug", "log":"hello!",                 "container_name":"bar"}
```

It is important that only container_name `foo` is affected, so if I add other containers with `debug` messages _later on_ then they will not be filtered out with this config.

In other words, the same config should allow new logs from container_name `thing`, even if they are `debug` level.

So with the same config, these logs should make it through:

```json
{"level":"debug", "log":"hello!", "container_name":"thing"}
{"level":"debug", "log":"hello!", "container_name":"some_app"}
```

### Problem

The current standard grep filter only supports `AND` matches between `<regexp>` blocks and `OR` matches between `<exclude>` blocks.

I can create a fluentd config for the above example that **almost** works:

```
<filter **>
    @type grep
    <exclude>
        key container_name
        pattern foo
    </exclude>

    <exclude>
        key level
        pattern debug
    </exclude>
</filter>
```

The problem with this config is that it excludes all logs from `foo` containers, including `error` logs. This also excludes `debug` logs from the `bar` containers.

Ok, so maybe we can flip it a little? Unfortunately, we now hit the complement of the same problem:

```
<filter **>
    @type grep
    <regexp>
        key container_name
        pattern (?!.*foo).*    # not foo
    </regexp>

    <regexp>
        key level
        pattern (?!.*debug).*  # not debug
    </regexp>
</filter>
```

This config still throws away all of `foo`'s logs and any debug logs.

### Possible solution

One possible solution is to modify the grep filter to support a new `<exclude-all>` block that ANDs together each block before throwing out a log.

Please let me know how I can help! 😄

**Comment by repeatedly** [comment]
`<exclude-all>` idea looks good.
Adding this condition to https://github.com/fluent/fluentd/blob/94287666b655edd9a6b4a142e6a5aa03fa0681ca/lib/fluent/plugin/filter_grep.rb#L108 is better.

```
if @_exclude_all
  # check key and condition pair
end
```

**Comment by okkez** [comment]
@JohnStarich I wrote some code for your feature request #1897 
Could you try it?

**Comment by JohnStarich** [comment]
Oh, nice. I like that idea. I have a feeling @repeatedly will want backwards compatibility so that standalone blocks of `regexp` and `exclude` will work. Perhaps these `<and>` and `<or>` blocks could be used in addition to the current behavior?

**Comment by okkez** [comment]
> Perhaps these <and> and <or> blocks could be used in addition to the current behavior?

Yes, you can use `<and>`, `<or>` with current behavior:

```
<filter>
  @type grep
  <and>
    <regexp>
      key level
      pattern ^ERROR|WARN$
    </regexp>
    <regexp>
      key method
      pattern ^GET|POST$
    </regexp>
  </and>
  <regexp>
    key path
    pattern ^/login$
  </regexp>
</filter>
```
For more combinations, see test code.

**Comment by JohnStarich** [comment]
Ah, yes you're right! I misread the changes in the diff as removing old behavior when it had really just moved.

Looks like it does exactly what I was looking for. Thanks!

**Comment by JohnStarich** [comment]
Great to see this made it to master in https://github.com/fluent/fluentd/pull/1897 !
Is there a released version available for installation?

**Comment by repeatedly** [comment]
v1.2.0.pre1 is released.

**Comment by JohnStarich** [comment]
Awesome! Thank you both! 🎉
