### ISSUE TITLE
Fluent::ElasticsearchOutput::TimeParser.error

### ISSUE THREAD

**Issue by NitinRanjan** [fluent/fluentd#1868]
Check [CONTRIBUTING guideline](https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md) first and here is the list to help us investigate the problem.

- fluentd 
- Docker

fluent           | 2018-02-23 10:08:21 +0530 [warn]: #0 fluent/log.rb:342:warn: dump an error event: error_class=ArgumentError error="invalid date" location="/usr/lib/ruby/gems/2.3.0/gems/fluent-plugin-elasticsearch-2.6.0/lib/fluent/plugin/out_elasticsearch.rb:184:in `strptime'" tag="Fluent::ElasticsearchOutput::TimeParser.error" time=#<Fluent::EventTime:0x00007f1fb5c37d88 @sec=1519360701, @nsec=399161772> record={"tag"=>"sol.sol__apc-audit", "time"=>1519360715, "format"=>"%Y-%m-%d %H:%M:%S.%3N", "value"=>"2018-01-12 03:01:23.176"}

**Comment by NitinRanjan** [comment]
%L helped , so closing the issue

**Comment by repeatedly** [comment]
BTW, don't use fluentd repo for asking question and 3rd party plugin issue.
This is described in CONTRIBUTING guide.
