### ISSUE TITLE
Changing install path on Windows doesn't work

### ISSUE THREAD

**Issue by scottbuettner** [fluent/fluentd#1871]
- td-agent 3.1.1
- Windows Server 2008
- Installed td-agent to "C:\Program Files"
- Changing the MSI's install path away from C:\opt for td-agent results in the "td-agent-prompt" not working. I get path not found errors when trying to run fluentd, fluent-cat, etc. I see that the .bat files have the C:\opt paths still.

**Comment by repeatedly** [comment]
This is td-agent issue, not fluentd. So closed.
