### ISSUE TITLE
td-agent3 has no ui 

### ISSUE THREAD

**Issue by zs787** [fluent/fluentd#1873]
After installing td-agent3 on CentOS 7 I dont see td-agent-ui under /usr/sbin/ 
However, installing td-agent2 on the same OS, but different machine, I can start and use the UI, it is there.

**Comment by repeatedly** [comment]
This is expected. See: https://docs.fluentd.org/v1.0/articles/td-agent-v2-vs-v3#features

**Comment by zs787** [comment]
Thank you!
But I guess the docs online needs to be updated ?
https://docs.fluentd.org/v1.0/articles/fluentd-ui
