### ISSUE TITLE
Suggest include_time_key of format section and keep_time_key of parse section change to same parameter

### ISSUE THREAD

**Issue by breath-co2** [fluent/fluentd#1884]
fluentd version :  1.1

In parse section parameter keep_time_key and format section parameter include_time_key is same characteristics. I suggest that they be unified, and I suggest the default value is true.

see: 
* https://docs.fluentd.org/v1.0/articles/parse-section
* https://docs.fluentd.org/v0.12/articles/formatter_json

**Comment by kenhys** [comment]
FYI:

It seems that `include_time_key` is unified into `time_key` in 1.x. See
https://docs.fluentd.org/plugin-helper-overview/api-plugin-helper-compat_parameters about details.
