### ISSUE TITLE
td-agent for windows 7 professional 32 bit operating system.

### ISSUE THREAD

**Issue by himmatb** [fluent/fluentd#1885]
- fluentd or td-agent version - 
    td-agent - v3.1.1
- Environment information(O.S.), 
   Windows 7 Professional 32-bit operating system

As my application running on Windows 7 and i am trying to install td-agent 3.1.1 version on windows 7 Professional O.S to get all logs and forward them to fluentd aggregator. 
but i end up with below error : 
"This installation package is not supported by this processor type. contact your product vendor"

is this td-agent is not supporting windows 7 OS ?
Please let me know what all Windows versions it will support and compatible version with windows7

**Comment by cosmo0920** [comment]
Here is Fluentd bug tracker.
Could you open this issue in [td-agent repository](https://github.com/treasure-data/omnibus-td-agent)?

**Comment by cosmo0920** [comment]
> is this td-agent is not supporting windows 7 OS ?
> Please let me know what all Windows versions it will support and compatible version with windows7

Currently, td-agent 3 installer is workable in Windows 7 *64bit* version or newer *64bit* Windows.

**Comment by himmatb** [comment]
Thanks @cosmo0920 for quick reply.

any other td-agent version is compatible with windows 7 32 bit version.

**Comment by cosmo0920** [comment]
Currently, there is no.build for 32bit Windows conpatible.
Because 32bit version of Windows cannot handle over 2GB memory per process and its limitatiom causes poor performance.

**Comment by repeatedly** [comment]
This is not fluentd issue. Closed.
