### ISSUE TITLE
Does Fluentd supports for Solaris Operating System ?

### ISSUE THREAD

**Issue by himmatb** [fluent/fluentd#1888]
My application is running on Solaris OS. I am planning to securely forward application related logs from solaris os to openshift elasticsearch.

does fluentd supports solaris operating system.?

**Comment by repeatedly** [comment]
I'm not familiar with Solaris but if Solaris provides Ruby package, fluentd should work.

**Comment by himmatb** [comment]
That's worked@repeatedly .. Thanks.. 

I need quick advice from you .. Please suggest me any way to forward logs to Openshift aggregator  from 32bit Windows 7 application.
This will help me a lot.
can i do same way what i have done for solaris OS.? 

Please advice.!!

**Comment by repeatedly** [comment]
> can i do same way what i have done for solaris OS.?

Yes. We didn't test fluentd on Windows 32bit but it should run.
