### ISSUE TITLE
Fluentd filtering Verion .14

### ISSUE THREAD

**Issue by chrisolido** [fluent/fluentd#1891]
Im getting this issue even i have setup my forwarder to 

 buffer_chunk_limit 36m
 buffer_queue_limit 512

and my fluent.conf

```
<filter gb*>
  @type grep
  <regexp>
   key message
   pattern gb-svc.*
  </regexp>
</filter>


<match gb.**>
 type copy
 <store>
  @type elasticsearch
  log_level info
  host X.X.X.X
  user elastic
  password changeme
  port 9200
  index_name fluentd_all
  logstash_format true
  logstash_prefix fluentd
  logstash_dateformat %Y%m%d
  include_tag_key true
  tag_key @log_name
  buffer_chunk_limit 36m
  buffer_queue_limit 512
  flush_interval 2
 </store>
</match>
```

Still geting this error

2018-03-14 02:29:11 +0000 [warn]: Size of the emitted data exceeds buffer_chunk_limit.
2018-03-14 02:29:11 +0000 [warn]: This may occur problems in the output plugins ``at this server.``
2018-03-14 02:29:11 +0000 [warn]: To avoid problems, set a smaller number to the buffer_chunk_limit
2018-03-14 02:29:11 +0000 [warn]: in the forward output ``at the log forwarding server.``

Please advise how to fix.

Check [CONTRIBUTING guideline](https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md) first and here is the list to help us investigate the problem.

- fluentd or td-agent version.
- Environment information, e.g. OS.
- Your configuration
- Your problem explanation. If you have an error logs, write it together.

**Comment by repeatedly** [comment]
> Im getting this issue even i have setup my forwarder to

Does this mean forwarder's buffer_chunk_limit is also `36m`?

**Comment by chrisolido** [comment]
Thats the current config of my forwarder also. 

yes its set to 36m
