### ISSUE TITLE
安装太繁琐，脚本不能执行

### ISSUE THREAD

**Issue by fengyingjie2018** [fluent/fluentd#1892]
Check [CONTRIBUTING guideline](https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md) first and here is the list to help us investigate the problem.

- fluentd or td-agent version.
- Environment information, e.g. OS.
- Your configuration
- Your problem explanation. If you have an error logs, write it together.
如果限制网络，脚本就不能执行，安装就失败了。希望可以有一个tar包，适用与contos7.2，解压后直接可以使用。

**Comment by cosmo0920** [comment]
What is your installation steps? (e.g. executing commands or operations)

请报告您的问题用英语而不是汉语。

**Comment by breath-co2** [comment]
碰巧看到 @fengyingjie2018 别把自己的无知当理由还跑来丢人现眼，在 https://www.fluentd.org/download 页面里有 centos 安装方法和连接地址，可以去 https://td-agent-package-browser.herokuapp.com/3/redhat/7/x86_64 里将自己需要的 rpm 包下载下来后直接安装。

在线安装方法：

```bash
yum install http://packages.treasuredata.com.s3.amazonaws.com/3/redhat/7/x86_64/td-agent-3.1.1-0.el7.x86_64.rpm
```

离线安装方法：

```bash
wget http://packages.treasuredata.com.s3.amazonaws.com/3/redhat/7/x86_64/td-agent-3.1.1-0.el7.x86_64.rpm
rpm -ivh td-agent-3.1.1-0.el7.x86_64.rpm
```

@cosmo0920 He is complaining slow installation network in china, will always fail. Indeed it is, I suggest you provide aws beijing area download for china if possible.

**Comment by ganmacs** [comment]
it's a stale issue. I'm closing. if you have any problem, updating fluentd might help it.

**Comment by Lin-ermao** [comment]
> 碰巧看到 @fengyingjie2018 别把自己的无知当理由还跑来丢人现眼，在 https://www.fluentd.org/download 页面里有 centos 安装方法和连接地址，可以去 https://td-agent-package-browser.herokuapp.com/3/redhat/7/x86_64 里将自己需要的 rpm 包下载下来后直接安装。
> 
> 在线安装方法：
> 
> ```shell
> yum install http://packages.treasuredata.com.s3.amazonaws.com/3/redhat/7/x86_64/td-agent-3.1.1-0.el7.x86_64.rpm
> ```
> 
> 离线安装方法：
> 
> ```shell
> wget http://packages.treasuredata.com.s3.amazonaws.com/3/redhat/7/x86_64/td-agent-3.1.1-0.el7.x86_64.rpm
> rpm -ivh td-agent-3.1.1-0.el7.x86_64.rpm
> ```
> 
> @cosmo0920 He is complaining slow installation network in china, will always fail. Indeed it is, I suggest you provide aws beijing area download for china if possible.


if i could not use the rpm way to install a fluentd; is there a another way to install

只有rpm这种方式来支持
