### ISSUE TITLE
Enabling limit_recently_modified 1 stops fluentd reading anything. No new files or old files are read 

### ISSUE THREAD

**Issue by AniGarikipati** [fluent/fluentd#1906]
Check [CONTRIBUTING guideline](https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md) first and here is the list to help us investigate the problem.

- Latest Docker Container
- Alpine 
- fluent.conf 

```
<source>
  @type tail
  path /**/log  
  tag **.log
  format /^(?<message>.*)$/
  read_from_head true  
  limit_recently_modified 1
</source>
```
 
- Without having a value for limit_recently_modified, all existing logs in directory are read, as well as new ones. After having it enabled no logs read at all. Existing or new.

**Comment by repeatedly** [comment]
With `limit_recently_modified 1`, in_tail picks new file which the modification time is within 1 seconds in file list refresh.
Do you gurantee modified time is within 1 seconds?

**Comment by AniGarikipati** [comment]
Yes i did confirm that modified time is within 1. However, i changed the code to read

**Comment by aligege123** [comment]
It's better to update the document together.
![image](https://github.com/fluent/fluentd/assets/43952414/8a789ce2-8cb1-4d24-a75a-7174445b0419)
