### ISSUE TITLE
Td-agent sometimes stop parsing logs to elasticsearch

### ISSUE THREAD

**Issue by agarwalshivam456** [fluent/fluentd#1921]
**td-agent version:**
root@lb # td-agent-gem --version
2.6.13

**OS:**
root@lb # lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.4 LTS
Release:        14.04
Codename:       trusty

**Configuration:**
\<source>
  @type tail
path /var/log/db-backup-monitoring.log 
pos_file /var/log/td-agent/db-backup-monitoring.log.pos
tag shivam.error
format /^(?<date>[^ ]*) (?<size>[^ ]*).* (?<dbname>[^ ]*)$/
time_format %d-%m-%Y
\</source>

\<match shivam.erro*>
 @type elasticsearch
 host  10.0.0.1
 port 9200
 include_timestamp true
 logstash_format true
 logstash_prefix backup-monitoring
 logstash_dateformat %Y
 index_name testing.%Y%m
\</match>

I am parsing a self created log file by running a cron at specific time once in a day which contain only 10 records and append the logs to exist file, sometimes it doesn't detect log rotation (once or twice in a week) so don't parse the logs to elastic-search.

Please let me know the problem what i'm not noticing.
Is this somehow related to buffer ?

**Comment by okkez** [comment]
See https://docs.fluentd.org/v1.0/articles/in_tail#logrotate-setting and check your log rotation configuration.

**Comment by ganmacs** [comment]
it's stale and no response. I'm closing
