### ISSUE TITLE
cool.io has been retired upstream

### ISSUE THREAD

**Issue by williamh** [fluent/fluentd#1926]
Hello.

I am a packager for Gentoo linux.

My place of employment is interested in using fluentd, so I am being asked to package it.
In checking for the dependencies, I found that cool.io is not packaged. I checked upstream, and the author is reporting that it is retired. This might also explain why no one has packaged cool.io already for Gentoo.

https://rubygems.org/gems/cool.io
https://coolio.github.io/

Are you planning to move away from cool.io? How should I proceed with packaging fluentd?

I am also tagging my co-worker, @sluidfoe, so he will see your response. 
Thanks much for your advice.

**Comment by repeatedly** [comment]
> Are you planning to move away from cool.io? 

No plan for now because we are maintaining cool.io for fluentd.
You can see cool.io has several new releases after original author stopped cool.io development.

**Comment by williamh** [comment]
Ok, that's fine, I also was pointed to the package in our distribution by another maintainer.
Sorry about the noise on this issue.
I will probably open an issue shortly based on a suggestion from our ruby team.
