### ISSUE TITLE
Would you consider dropping the dependency on tzinfo-data?

### ISSUE THREAD

**Issue by williamh** [fluent/fluentd#1929]
Hello,

this is a comment I got from the Gentoo ruby team.

> fluentd should not depend on tzinfo-data. We do not package this because tzinfo-1* will actually use 
> timezone-data without it, and it makes much more sense to have one consistent source of that stuff.
> tzinfo-data is a crutch only to be used when your system timezone stuff is completely out of whack.

What do you think?

**Comment by repeatedly** [comment]
Duplicated: https://github.com/fluent/fluentd/issues/1761
