### ISSUE TITLE
make the dependency on dig_rb conditional

### ISSUE THREAD

**Issue by williamh** [fluent/fluentd#1930]
Here is another comment I got from my ruby team:

> It looks like dig_rb isn't needed. It backports the dig method for Arrays and Hashes from ruby 2.3 back to > earlier versions. Since ruby 2.2 is going to go away very soon in Gentoo my proposal would be to remove > this gem from the gemspec and run without it because it is a no-op for ruby 2.3+

**Comment by repeatedly** [comment]
I'm not sure Gentoo environment but fluentd v1.x still supports ruby 2.1 or 2.2 so we can't remove it from gemspec. Of course, it will be removed in the future but the date is not fixed.
Closed.
