### ISSUE TITLE
${tag} in path in <match> not working

### ISSUE THREAD

**Issue by azyata** [fluent/fluentd#1931]
Assuming to [documetation](https://docs.fluentd.org/v1.0/articles/out_file), `${tag}` should dynamically create log files named from tag (match directive is working), but it creates
`service.${tag}.b56909ae20688d60b296b46c3be86cbc2.log` file

fluentd:latest from docker repository (fluentd 1.1.3)

match configuration:
```
<match service.*>
  @type copy
  <store> 
    @type file
    path /fluentd/log/service.${tag}.*.log
    <buffer time,tag>
      flush_at_shutdown true
    </buffer>
    time_slice_format %Y%m%d
    time_slice_wait 1s
    time_format %Y%m%dT%H%M%S%z
    time_key unix_timestamp
    compress gzip
    timezone +01:00
    format json
  </store>
</match>
```

**Comment by repeatedly** [comment]
See official document: https://docs.fluentd.org/v1.0/articles/out_file#path-(required)

**Comment by repeatedly** [comment]
Add FAQ for it: https://docs.fluentd.org/v1.0/articles/out_file#i-can-see-files-but-placeholders-are-not-replaced,-why?
Closed.
