### ISSUE TITLE
Tail misses out first log line in newly created log files

### ISSUE THREAD

**Issue by BentCoder** [fluent/fluentd#1933]
Hi,

Assume that the file `/home/ubuntu/registration.log` doesn't exist yet but I create it by running command below which writes the first log line to it.

```
$ echo '{"key":"1"}' >> /home/ubuntu/registration.log
```

In such case above, my configuration won't read the file because it didn't exist so `/home/ubuntu/td-agent-logs/logs.log` will be empty at this stage. However, if I run the same command again with `'{"key":"2"}'`, this time the `/home/ubuntu/td-agent-logs/logs.log` will contain `{"key":"2"}` which is perfect. As you can see here the problem is that, I will always miss out the very first line of newly created files (will occur when a file is created with a log rotator). How do I solve this issue?

Thanks

**SYSTEM**
td-agent: `2.3.6-0`
os: `Ubuntu 16.04`

**CONFIG**
```
<source>
  @type tail
  format json
  tag api.user.registration
  path /home/ubuntu/*
  pos_file /var/log/td-agent/tmp/registration.log.pos
</source>

<match api.user.registration>
  @type file
  path /home/ubuntu/td-agent-logs/logs.log
</match>
```

**Comment by repeatedly** [comment]
See: https://docs.fluentd.org/v1.0/articles/in_tail#read_from_head

And this doesn't follow CONTRIBUTING guide, so closed.
