### ISSUE TITLE
td-agent-gem can't use

### ISSUE THREAD

**Issue by nttdbpo-liudengke** [fluent/fluentd#1939]
Check [CONTRIBUTING guideline](https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md) first and here is the list to help us investigate the problem.

- fluentd or td-agent version.
td-agent-3.1.1-0.el2.x86_64
- Environment information, e.g. OS.
command: cat /etc/os-release
NAME="Amazon Linux AMI"
VERSION="2017.09"
ID="amzn"
ID_LIKE="rhel fedora"
VERSION_ID="2017.09"
PRETTY_NAME="Amazon Linux AMI 2017.09"
ANSI_COLOR="0;33"
CPE_NAME="cpe:/o:amazon:linux:2017.09:ga"
HOME_URL="http://aws.amazon.com/amazon-linux-ami/"
- Your configuration
not modify
- Your problem explanation. If you have an error logs, write it together.
command: td-agent-gem --help
/opt/td-agent/embedded/bin/ruby: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by /opt/td-agent/embedded/lib/libruby.so.2.4)

would i need to install glibc-2.25 rpm?
but aws's yum repo haven't this rpm.

**Comment by nttdbpo-liudengke** [comment]
use error version

**Comment by boodera** [comment]
GLIBC_2.25 not resolved. The latest version of the package was 2.17 available for Amazon Linux 2.
