### ISSUE TITLE
Does fluentd support parsing protobuf data?

### ISSUE THREAD

**Issue by ncepuwanghui** [fluent/fluentd#1944]
I want to use protobuf to transfer data to kafka and then use Fluentd to parse the data and write to Elasticsearch. But I can't find a suitable parse plugin and filter plugin.
Does anyone have the same problem?

**Comment by repeatedly** [comment]
Fluentd core doesn't provide protobuf parser.

**Comment by marcosflobo** [comment]
@repeatedly do you know if Fluentd supports protobuf in the HTTP input plugin? I'm not asking about parsing, just receive it and forward it to an output
