### ISSUE TITLE
Fluentd failed to capture log files from a specified directory

### ISSUE THREAD

**Issue by sharmarajat24** [fluent/fluentd#1945]
Check [CONTRIBUTING guideline](https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md) first and here is the list to help us investigate the problem.

- fluentd or td-agent version.
- Environment information, e.g. OS.
- Your configuration
- Your problem explanation. If you have an error logs, write it together.

**Comment by rajatvcsbuild** [comment]
OS: RHEL 7.4 with Kubernetes 

Fluentd entire configuration
`
![image](https://user-images.githubusercontent.com/13004301/38779867-0efabb4c-40ec-11e8-8246-c6ba7fdca171.png)
`

**Comment by rajatvcsbuild** [comment]
fluentd version: v1.1.3
OS: Rhel 7.4
configuration:

`/ # cat /etc/fluent/fluent.conf
<source>
  @type tail
  format none
  @label @INGRESS
  path /mydir/logs/*.log
  pos_file /var/log/my-file.log.pos
  tag mylogfiles
  read_from_head true
</source>
 
<label @INGRESS>
 
  <match mylogfiles.**>
    @type mongo_replset
    database fluent
    collection mylogs
 
    capped
    capped_size 1024m
 
    nodes mongo-0:27017,mongo-1:27017
 
    # The replica set name
    replica_set rs0
 
    # num_retries is threshold at failover, default is 60.
    # If retry count reached this threshold, mongo plugin raises an exception.
    num_retries 30
 
    # Specifies the read preference mode
    #read secondary
  </match>
 
</label>
 
 
`

**Comment by repeatedly** [comment]
Sorry, I can't understand the problem from your issue comments.

**Comment by repeatedly** [comment]
Maybe, this is better in mailing list.

**Comment by sharmarajat24** [comment]
Hi Author,

I want to capture logs from a log files residing inside a specific
directory host in a system (say /product_logs) in Kubernetes echosystem
using flunetd.

I am using the below fluentd configuration but that is not working. can you
please help.

/ # cat /etc/fluent/fluent.conf
<source>
  @type tail
  format none
  @label @INGRESS
  path /mydir/logs/*.log
  pos_file /var/log/my-file.log.pos
  tag mylogfiles
  read_from_head true
</source>

<label @INGRESS>
  <match mylogfiles.**>
    @type mongo_replset
    database fluent
    collection mylogs
    capped
    capped_size 1024m
    nodes mongo-0:27017,mongo-1:27017
    replica_set rs0
    num_retries 30
  </match>
</label>




Thanks,
Rajat
