### ISSUE TITLE
Brush the log when used s3 plugin start

### ISSUE THREAD

**Issue by bingxunali** [fluent/fluentd#1956]
fluentd td-agent 1.0.2
OS：Linux version 3.14.27-25.47.amzn1.x86_64 (mockbuild@gobi-build-60001) (gcc version 4.8.2 20140120 (Red Hat 4.8.2-16) (GCC) ) #1 SMP Wed Dec 17 18:36:15 UTC 2014.
configuration
<source>
 @type tail
 read_from_head true
 path /data/service/async_jump/log/count.log.%Y-%m-%d-%H
 pos_file /var/log/td-agent/count.log.pos
 format json
 tag count.log
 keep_time_key true
 time_format  %Y-%m-%dT%H:%M:%S.%L%Z
 utc 8
</source>

<match count.log>
 @type s3
 s3_bucket mob-ad
 s3_region us-east-1
 path 3s/async_jump
 flush_interval 60s
 store_as gzip_command
 buffer_chunk_limit 256m
 buffer_type file
 buffer_path /var/log/td-agent/buffer/count.buffer
 format json
 time_key time
 utc  8
 include_time_key  true
 time_format  %Y-%m-%dT%H:%M:%S.%L%Z
 s3_object_key_format %{path}/count/%{time_slice}/35.182.238.155-count.log.%Y-%m-%d-%H_%{index}.%{file_extension}
 time_slice_format %Y/%m/%d/canada/%H
</match>
- - problem when i used "td-agentd -vv" to start fluentd,I find some questions when "starting SSL for mob-ad.s3.amazonaws.com:443..." upon complete it will reading the log files from s3 path.These log files were first uploaded.He didn't start working until he had read the first log files

like this：
opening connection to mob-ad.s3.amazonaws.com:443...
opened
starting SSL for mob-ad.s3.amazonaws.com:443...
SSL established
<- "GET /?········································
-> "HTTP/1.1 200 OK\r\n"
-> "x-amz-id-2: BUR7AqmR4wXf4DJFFXen5r3Z2M+Q0Goi1i4e9JB+kXVxUV5nMrz7tqvcWAzODcf/H/D+YORUA9M=\r\n"
-> "x-amz-request-id: 1DA6873467DE7D02\r\n"
-> "Date: Wed, 18 Apr 2018 09:12:36 GMT\r\n"
-> "x-amz-bucket-region: us-east-1\r\n"
-> "Content-Type: application/xml\r\n"
-> "Transfer-Encoding: chunked\r\n"
-> "Server: AmazonS3\r\n"
-> "\r\n"
-> "2000\r\n"
reading 8192 bytes...
--》················· log information in s3
reading 8192 bytes...
--》····················log information in s3
reading 8192 bytes...
-->··················log information in s3
······························
························

**Comment by JamesJJ** [comment]
I do not understand your question, please could you write more clearly? 

（If it is easier, you could try writing the question in a different language, maybe we can understand.  不太懂你的問題， 可以寫清楚一點嗎？）

**Comment by repeatedly** [comment]
No response. And the question is about S3 plugin? closed.
