### ISSUE TITLE
can not download docs from https://docs.fluentd.org/v1.0/articles/quickstart

### ISSUE THREAD

**Issue by 4680185** [fluent/fluentd#1959]
I want download the doc of fluent as pdf ,when I clich the 
![image](https://user-images.githubusercontent.com/27662794/39232308-7975bf7a-489f-11e8-9764-16988b9ec99a.png)
and I write my information name,email,and company ,last I click 
![image](https://user-images.githubusercontent.com/27662794/39232425-d8983abe-489f-11e8-997f-a2f9940bcca8.png)
so I wait for the download ,but the download not work can you help me ? 
my email address is martiszhang@gmail.com

**Comment by repeatedly** [comment]
This is fluentd-docs issue. Closed.

**Comment by repeatedly** [comment]
BTW, I disabled PDF link temporarily: https://github.com/fluent/fluentd-docs/commit/4d5032d4d364b8b6d6e1add22e0da414d931c88d
