### ISSUE TITLE
Fluentd has the problem of deleting the files being used, the problem of space not releasing

### ISSUE THREAD

**Issue by fengyingjie2018** [fluent/fluentd#1960]
fluentd都会存在删除正在使用的文件，空间不释放的问题,采用脚本定时删除回滚后的日志文件的方式减少日志对系统盘的占有；这样肯定会出现某一个时刻这个acess.log刚刚回滚完产生一个旧文件acessold.log就执行定时任务脚本把这个文件给从磁盘上删除，那么如果这个旧文件acessold.log没有读完fluentd就会不关闭文件句柄，导致这个句柄空间不释放的问题（可以通过sudo lsof|grep deleted |grep fluentd方式查看）,一旦这个没有释放的空间积累量较大时候系统盘会被占满影响其他服务

**Comment by JamesJJ** [comment]
你的config是什麼？

Did you see this setting? :
https://docs.fluentd.org/v1.0/articles/in_tail#rotate_wait

**Comment by xidiandb** [comment]
如果超过了这个时间还没有读完呢？
