### ISSUE TITLE
regex format not working with syslog

### ISSUE THREAD

**Issue by kumaravel29** [fluent/fluentd#1962]
The regex format is not working with the syslog plugin

- fluentd or td-agent version. - 1.0.2
- Environment information, e.g. OS.
- Your configuration

```
<source>
  @type syslog
  port 12205
  bind 0.0.0.0
  tag system
  source_hostname_key "hostsource"
  priority_key "priority"
  facility_key "facilityLevel"
  #message_format rfc5424
  format /^\<(?<pri>[0-9]{1,3})\>[1-9]\d{0,2} (?<time>[^ ]+) (?<host>[^ ]+) (?<ident>[^ ]+) (?<pid>[-0-9]+) (?<msgid>[^ ]+) (?<extradata>(\[(.*)\]|[^ ]))\s{0,2}(?<message>.*)$/
  time_format "%Y-%m-%dT%H:%M:%S.%L%z"
</source>
```

- Your problem explanation. If you have an error logs, write it together.
failed to parse message data="<14>14 2018-01-01T00:00:00.00000Z 127.0.0.1 f5healthcheck - - [] F5 health check"
I am able to format the data in case of UDP type but the same not working in syslog. I went through the code and seems the default regex SYSLOG_REGEXP = /^\<([0-9]+)\>(.*)/ is considered.

Please help

**Comment by fujimotos** [comment]
I'm kinda wondering why you are trying to parse syslog data with your own regex,
rather than relying on the builtin parser. Frankly, this is the kind of job
you should delegate to Fluentd.

But anyway, try the following settings and please feedback us if it solves your problem:

```xml
<source>
  @type syslog
  port 12205
  bind 0.0.0.0
  tag system
  source_hostname_key "hostsource"
  priority_key "priority"
  facility_key "facilityLevel"
  <parser>
    @type regexp
    format /^\<(?<pri>[0-9]{1,3})\>[1-9]\d{0,2} (?<time>[^ ]+) (?<host>[^ ]+) (?<ident>[^ ]+) (?<pid>[-0-9]+) (?<msgid>[^ ]+) (?<extradata>(\[(.*)\]|[^ ]))\s{0,2}(?<message>.*)$/
    time_format %Y-%m-%dT%H:%M:%S.%L%z
  </parser>
</source>
```

The essential point is that `format` option is deprecated since Fluentd v0.14 and
you need to specify the formatting properly using the `<parser>` block.

**Comment by kumaravel29** [comment]
Thanks for the setting and details.

I started with using the builtin parser but a number of messages were being dropped(not parsed) because the data contained empty message like the one below
```
2018-04-26 09:58:28 +0200 [warn]: #0 failed to parse message data="<14>1 2018-04-26T07:58:28.167853Z 171.0.0.1 uaa - - [instance@xxxxxxxxxxx" id=\"yyyyyyyyyy\"] "
```

So I am trying for custom format parsing.

I tried the config shared but still not working as I get the warning and then the parsing fails

```
{"time":"2018-04-26","level":"warn","message":"section <parser> is not used in <source> of syslog plugin"}
```

**Comment by repeatedly** [comment]
> <parser>

`<parse>`, not `<parser>`.

https://docs.fluentd.org/v1.0/articles/parser-plugin-overview#how-to-use

**Comment by kumaravel29** [comment]
@repeatedly thanks for info.

I tried with the change and that error is gone but still the syslog messge is not parsed. The same regular expression works properly in udp. 
```
failed to parse message data="<14>14 2018-01-01T00:00:00.00000Z 127.0.0.1 f5healthcheck - - [] F5 health check"
```

Now I am not getting the reason for failure also as I was getting earlier mentioning the time format was wrong 
```
invalid input data=\"<14>14 2018-01-01T00:00:00.00000Z 127.0.0.1 f5healthcheck - - [] F5 health check\" error_class=Fluent::TimeParser::TimeParseError error=\"invalid time format: value = 14 2018-01-01T00:00:00.00000Z 127.0.0.1, error_class = ArgumentError, error = string doesn't match\"
```

Config used now 
```
<source>
  @type syslog
  port 12205
  bind 0.0.0.0
  tag system
  source_hostname_key "hostsource"
  priority_key "priority"
  facility_key "facilityLevel"
  <parse>
    @type regexp
    expression /^\<(?<pri>[0-9]{1,3})\>[1-9]\d{0,2} (?<syslogTime>[^ ]+) (?<host>[^ ]+) (?<ident>[^ ]+) (?<pid>[-0-9]+) (?<msgid>[^ ]+) (?<extradata>(\[(.*)\]|[^ ]))\s{0,2}(?<message>.*)$/
    time_key syslogTime
    time_format %Y-%m-%dT%H:%M:%S.%L%z
  </parse>
</source>
```

**Comment by fujimotos** [comment]
@kumaravel29 Now try this one. How it goes?

```xml
<source>
  @type syslog
  port 12205
  bind 0.0.0.0
  tag system
  source_hostname_key "hostsource"
  priority_key "priority"
  facility_key "facilityLevel"
  <parse>
    @type regexp
    expression /^[1-9]\d{0,2} (?<syslogTime>[^ ]+) (?<host>[^ ]+) (?<ident>[^ ]+) (?<pid>[-0-9]+) (?<msgid>[^ ]+) (?<extradata>(\[(.*)\]|[^ ]))\s{0,2}(?<message>.*)$/
    time_key syslogTime
    time_format %Y-%m-%dT%H:%M:%S.%L%z
  </parse>
</source>

**Comment by kumaravel29** [comment]
@fujimotos That worked. Thanks for the help.
I guess the syslog plugin sends the part of the message after the priority for parsing.

One more question, is it possible to support multiple time_format in the parse?

**Comment by fujimotos** [comment]
> One more question, is it possible to support multiple time_format in the parse?

No. You cannot specify multiple `time_format` options in a `<parse>` section right now.

Anyway, if you have further questions on the usage of Fluentd, please move to [the
support forum](https://groups.google.com/forum/#!forum/fluentd). The forum is better suited to handle the kind of questions...

**Comment by repeatedly** [comment]
> I guess the syslog plugin sends the part of the message after the priority for parsing.

This is mentioned in the official article.

https://docs.fluentd.org/v1.0/articles/in_syslog#<parse>-directive

Issue seems resolved.
