### ISSUE TITLE
Buffer retry blocks valid records after exception

### ISSUE THREAD

**Issue by kumaravel29** [fluent/fluentd#1967]
- fluentd or td-agent version. - gem 'fluentd' version '1.1.3'
- Environment information, e.g. OS. - Docker
- Your configuration 
```
<match *.logs.**>
  @type copy_ex
  <store ignore_error>
    @type forest
    subtype elasticsearch
   <template>
      hosts abc
      user admin
      password admin
      reload_on_failure true
      request_timeout 15s
      reload_connections true
      reconnect_on_error true
      index_name xx-${tag_parts[0]}-current
      template_name xx-${tag_parts[0]}
      template_file /etc/td-agent/alias_template.json
      index_prefix logstash
      type_name test
      # Use the beacon-generated UUID rather than a newly generated one by ES
      id_key UUID
      #remove_keys UUID # no need to have the field also as a separate attribute
      write_operation create # If id already exists, skip the record
      include_tag_key true
      @log_level debug
      num_threads 1
      <buffer>
        @type file
        path /var/log/td-agent/bufferv5/${tag_parts[0]}.data
        flush_interval 5s
        chunk_limit_size 6m
        queued_chunks_limit_size 4096
      </buffer>
    </template>
  </store>
</match>
```

- Your problem explanation. If you have an error logs, write it together.
I am using the Elasticsearch plugin to send data from the Fluentd. In case of exception for a particular record(like mapper exception), the chunk is retained for the retry. Because of the retry the buffer size keeps on increasing and the next chunk of data is also not processed.
1. Is it possible to clear only the failing chunk after x retry_limit?

**Comment by ahrtr** [comment]
If what you said "because of the retry, the buffer size keeps on increasing" is true, then I think it's a bug as well.  The only reason for the increase of buffer size should be coming from performance bottleneck instead of whatever error handling, i.e. retrying.  In other words, buffer size should only increase when the input rate is bigger than the output rate.

**Comment by ahrtr** [comment]
@kumaravel29 , I ran into the same issue recently. Have you resolved this issue or have any workaround?

**Comment by kumaravel29** [comment]
@ahrtr In case of an exception from elasticsearch, the plugin was retrying the buffer. So I just modified that part code to log the exception and not retry(exception out_of_memory_error and es_rejected_execution_exception will have the retry mechanism).

I think we should have a check on which type of exception/error from elasticsearch can be ignored, because in my case the mapping exception could be successful even after n number of retries but that blocked the flow.

**Comment by ahrtr** [comment]
@kumaravel29  Thanks for the feedback. 

I am not familiar with fluentd's source code. But I have a feeling that this is a bug related to the work flow instead of "which type of exception/error from elasticsearch can be ignored". The key point is that fluentd shouldn't block sending other normal chunks in whatever progress of retrying.

**Comment by ahrtr** [comment]
I think this should be a major bug, and deserve more attention.

**Comment by repeatedly** [comment]
I opened new issue on Elasticsearch plugin repository: https://github.com/uken/fluent-plugin-elasticsearch/issues/432

**Comment by cosmo0920** [comment]
@kumaravel29 Could you try fluent-plugin-elasticsearch v2.10.4 or later?

**Comment by ganmacs** [comment]
seems to be fluent-plugin-elasticsearch's issue. And fixed it.
