### ISSUE TITLE
Encryption support on out_forwarder plugin in Windows (Fluentd 1.0.2)

### ISSUE THREAD

**Issue by aturri** [fluent/fluentd#1968]
Hi,
is TLS/SSL supported by Fluentd embedded forwarder plugin in Windows?

I'm trying to push logs from Windows and Linux machines to a Fluentd server (Linux).
Linux machines can successfully send logs to the server with TLS.
Windows machines, instead, cannot send logs to the server, when configured with TLS. Both client and server say "connection established" when a buffer is flushed to the server, the buffer on the client gets erased, but the server receives nothing. I've tried to disable TLS on both client and server and communication works properly. I've tried to provide the client a forged certificate and it gives an OpesSSL error. But in my case there is no error and the server cannot receive logs.

I'm using Fluentd v1.0.2 for server and Linux client, td-agent v.3.1.1 for Windows clients (which is based on Fluentd v1.0.2).

Server configuration is:
```
<source>
  @type forward
  port 24224
  bind 0.0.0.0
  <transport tls>
    cert_path /certs/fluentd.crt
    private_key_path /certs/fluentd.key
    private_key_passphrase xxxx
  </transport>
</source>
```
Windows client configuration is:
```
<match xxx.**>
  @type forward
  transport tls
  tls_cert_path C:\certs\fluentd.crt
  tls_verify_hostname false
  tls_allow_self_signed_cert true
  <server>
    host xxxx
    port 24224
  </server>
</match>
```

Linux clients configuration is the same (except `tls_cert_path`).

Options
```
  tls_verify_hostname false
  tls_allow_self_signed_cert true
```
are necessary in my local (test) environment.

**Comment by repeatedly** [comment]
Tests for forward plugin with TLS on Windows is succeeded.
So the basic functionality should work but I'm not familiar with Windows network and OpenSSL limitation.
Need Windows expert help.
