### ISSUE TITLE
How Uniform consumption, uniform writing

### ISSUE THREAD

**Issue by yuan-make** [fluent/fluentd#1977]
version:  td-agent-3.1.0-0

structure：

fluentd  --> |
fluentd  --> | -----> kafka cluster --> fluentd --> elasticsearch
fluentd  --> |                                             |
                                                                  |
                                                      proxy  fluentd config:

```
<system>
  workers 4
</system>
<source> 
  @type kafka_group
  brokers ip1:9092,ip2:9092,ip3:9092
  consumer_group console-consumer-20018
  topics kitalog3
  format  json
  retry_emit_limit 1s
  max_bytes  30371840
  min_bytes  12428800
</source>
<match **>
  @type elasticsearch
  hosts ip1:i21:ip3:9200 
  reload_on_failure true
  reconnect_on_error true
  reload_connections false
  logstash_format true
  logstash_prefix online-log-prd
  logstash_dateformat %Y%m%d
  include_tag_key true
  tag_key @log_name
  flush_interval 1s
  buffer_chunk_limit 80m
  buffer_queue_limit 4
  num_threads 2
</match>

```
phenomenon：
     After a period of normal operation ，A large number of logs can suddenly be written into es  , resulting in high loading . and es  index No copies 12 Primary shards.  And about 20,000 writes per second

**Comment by repeatedly** [comment]
This is question, not fluentd issue.
