### ISSUE TITLE
issue about time of log

### ISSUE THREAD

**Issue by luweiv9988** [fluent/fluentd#1980]
td-agent version : 1.0.2

here is my configure:
```
<source>
  @type forward
  bind 0.0.0.0
  port 16537
</source>

<match app.access>
  @type file
  path /var/log/weblog/app-${tag[1]}.%Y-%m-%d.%H%M.log
  compress gzip
  append true
  <buffer tag,time>
    @type file
    path /tmp/buffer/transfer-access
    timekey    1d
    timekey_wait 0
    flush_mode interval
    flush_interval 86400
  </buffer>
</match>
```
now get log time is :
beginning:
![wx20180509-102137](https://user-images.githubusercontent.com/10349332/39800063-25b676cc-5399-11e8-8203-377a62777292.png)
end:
![wx20180509-102402](https://user-images.githubusercontent.com/10349332/39800079-36b682aa-5399-11e8-9a43-115b559a0596.png)

it's just beginng at 08:00 not 00:00 & my local timezone is CST , i'm also used "timekey_use_utc true",but does't work

how can i fix this issue?

**Comment by MingqingLi** [comment]
你解决了吗

**Comment by hunshenshi** [comment]
how can i fix this issue?

楼上的解决了不？ @MingqingLi  @luweiv9988

**Comment by luweiv9988** [comment]
升级到最新的 fluentd 不是td-agent 使用ruby运行

**Comment by hunshenshi** [comment]
@luweiv9988 你用的是什么版本？ 1.2.6可以解决这个问题不？

**Comment by hunshenshi** [comment]
1.2.6可以解决这个问题

**Comment by okkez** [comment]
Fluentd 1.2.6 resolves this issue. So closing.
if you encounter the issue again, reopne the issue.
