### ISSUE TITLE
in tail plugin sometimes fail to follow when logrotate.

### ISSUE THREAD

**Issue by monk-1** [fluent/fluentd#1981]
Check [CONTRIBUTING guideline](https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md) first and here is the list to help us investigate the problem.

- fluentd or td-agent version.
v1.1.3-debian

- Environment information, e.g. OS.
ubuntu, docker images

- Your configuration
```
<source>
@type tail
path **/**/stdout

<match **>
  @type stdout
</match>
```
- Your problem explanation. If you have an error logs, write it together.

I was able to notice there was a loss in log files when logrotate is on.
current logrotate settings.
```
rotate 10
missingok
notifempty
copytruncate
sharedscripts
size 5000000
```
after rotate, tail plugin leaves the log, that It have detected rotation.
But couldn't find any logs that It actually losses the logs.
It is not consistent, so It is too hard to track the exact problem.

There's an issue about this before, but in my case when rotating is over, It works just fine.
And problem is reproduced when it comes to time to rotate.
Is there any suggestions for the problem like this? logrotate settings, plugins settings...

By the way, thanks for the great program.

**Comment by marcin-je** [comment]
@monk-1 seems this is related to https://github.com/fluent/fluentd/issues/1595 where in_tail fails to read first few lines of a file it discovered with wildcard path watch
