### ISSUE TITLE
Fluentd behind haproxy: Massive amount of 'SD' errors (server disconnect)

### ISSUE THREAD

**Issue by chs-bnet** [fluent/fluentd#1982]
## Versions
td-agent 3, with fluentd gem updated to 1.1.3
haproxy 1.8
Everything on Ubuntu 16.04LTS.

haproxy using tcp forwarding to fluentd backends

## Your configuration
Relevant fluentd config:

```
<source>
  @id                       tls_forwarder_input
  @type                     forward
  port                      2514
 
  <transport tls>
    cert_path               /etc/td-agent/ca_cert.pem
    private_key_path        /etc/td-agent/ca_key.pem
    private_key_passphrase  passphrase
  </transport>
 
  <security>
    self_hostname           hostname
    user_auth               true
    shared_key              key
    <user>
      username {{ name }}
      password {{ password }}
    </user>
  </security>
</source>
```
haproxy config:

```
global
    maxconn 50000
    chroot /var/lib/haproxy
    log /dev/log local0
    log /dev/log local1 notice
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    balance roundrobin
    log global
    mode tcp
    timeout tunnel  1h
    timeout connect 30m
    timeout client  30m
    timeout server  30m
    timeout check   10s
    option dontlognull
    option log-health-checks
    option redispatch
    option tcplog
    option tcpka

frontend td-agent_frontend_2514
    bind :2514
    default_backend td-agent_backend_2514

backend td-agent_backend_2514
    server <host> <ip> check inter 5s
    server <host> <ip> check inter 5s
    server <host> <ip> check inter 5s
    server <host> <ip> check inter 5s
    server <host> <ip> check inter 5s
    server <host> <ip> check inter 5s
```

## Explanation

We've got several fluentd hosts configured behind an haproxy using tcp load balancing. Everything seems to work fine, we're doing excellent throughput up to 2 million documents a minute.

That said, we're seeing massive numbers of `SD` (server disconnect) messages in the haproxy logs. According to the haproxy documentation:

> S : the TCP session was unexpectedly aborted by the server, or the
>             server explicitly refused it.
> D : the session was killed by haproxy because the server was detected
>             as down and was configured to kill all connections when going down.

So it appears that fluentd behind the haproxy is terminating connections early.

This doesn't seem to be interfering with our ingest, but it is troublesome.

## Questions
* Is this normal?
  * If this is normal, why?
* What might be causing this?
* What should I look at to further troubleshoot this?
* Are there any fluentd config changes I can make that might improve this situation?
* Are there any haproxy config changes I can make that might improve this situation?
* Why isn't the client fluentd host making a long-term persistent connection?

**Comment by oudemen** [comment]
hello,@chs-bnet  ,you can try  in_forward Parameters: linger_timeout

**Comment by ganmacs** [comment]
True. https://docs.fluentd.org/v/0.12/input/forward#linger_timeout can help it.
also, it's a stale issue. I'm closing.
