### ISSUE TITLE
Filter type "parser" drops all matching events

### ISSUE THREAD

**Issue by srlps** [fluent/fluentd#1983]
# Environment
- fluentd version: 1.1.0
- OS image: debian:stretch-slim
# Configuration
    <source>
      @id fluentd-containers.log
      @type tail
      path /var/log/containers/*.log
      pos_file /var/log/es-containers.log.pos
      tag raw.kubernetes.*
      read_from_head true
      <parse>
        @type multi_format
        <pattern>
          format json
          time_key time
          time_format %Y-%m-%dT%H:%M:%S.%NZ
        </pattern>
        <pattern>
          format /^(?<time>.+) (?<stream>stdout|stderr) [^ ]* (?<log>.*)$/
          time_format %Y-%m-%dT%H:%M:%S.%N%:z
        </pattern>
      </parse>
    </source>

    # Detect exceptions in the log output and forward them as one log entry.
    <match raw.kubernetes.**>
      @id raw.kubernetes
      @type detect_exceptions
      remove_tag_prefix raw
      message log
      stream stream
      multiline_flush_interval 1
      max_bytes 500000
      max_lines 1000
    </match>

    # Enriches records with Kubernetes metadata
    <filter kubernetes.**>
      @type kubernetes_metadata
    </filter>
    
    # Deletes fluentd logs
    <filter kubernetes.**>
      @type grep
      <exclude>
        key $.kubernetes.container_name
        pattern fluentd-es
      </exclude>
    </filter>
    
    # Concats multiline logs 
    <filter kubernetes.**>
      @type concat
      key log
      multiline_start_regexp /^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}\.\d{3}/
      separator ""
      flush_interval 5
      use_first_timestamp true
      timeout_label @NORMAL
    </filter>
    
    <match **>
      @type relabel
      @label @NORMAL
    </match>

    <label @NORMAL>
      # Parses Spring logs 
      <filter kubernetes.**>
        @id spring_parser
        @type parser
        key_name log
        <parse>
          @type regexp
          expression /^(?<time>[^ ]* [^ ]*) +(?<level>[^ ]*) +(?<pid>[^ ]*) +--- +\[ *(?<thread>[^ ]*)\] +(?<class>[^ ]*) +: +(?<message>.*)$/
          time_format %Y-%m-%d %H:%M:%S.%z
          multiline true
          keep_time_key true
        </parse>
        hash_value_field parsed
        reserve_data true
        emit_invalid_record_to_error false
      </filter>
      
      <match **>
        @id elasticsearch
        @type elasticsearch
        @log_level info
        include_tag_key true
        host elasticsearch-logging
        port 9200
        logstash_format true
        <buffer>
          @type file
          path /var/log/fluentd-buffers/kubernetes.system.buffer
          flush_mode interval
          retry_type exponential_backoff
          flush_thread_count 2
          flush_interval 1s
          retry_forever
          retry_max_interval 30
          chunk_limit_size 2M
          queue_limit_length 8
          overflow_action block
        </buffer>
      </match>
    </label>
# Your problem explanation
The parser filter with id "spring_parser" drops any event that matches the regex

**Comment by repeatedly** [comment]
I'm not sure this is a bug of parser plugin or not.
Could you reduce the configuration to check your problem?

```
<source>
  @type tail # or forward
</source>

<filter test.**>
  @type parser
  # your configuration
</filter>

<match test**>
  @type stdout
</match>
```

We don't have actual log so we can't debug the problem.

**Comment by srlps** [comment]
I tried with a reduced configuration like this:

    <source>
      @id fluentd-containers.log
      @type tail
      path /var/log/containers/*.log
      pos_file /var/log/es-containers.log.pos
      tag kubernetes.*
      read_from_head true
      <parse>
        @type multi_format
        <pattern>
          format json
          time_key time
          time_format %Y-%m-%dT%H:%M:%S.%NZ
        </pattern>
      </parse>
    </source>

    # Enriches records with Kubernetes metadata
    <filter kubernetes.**>
      @type kubernetes_metadata
    </filter>
    
    # Deletes fluentd logs
    <filter kubernetes.**>
      @type grep
      <exclude>
        key $.kubernetes.container_name
        pattern fluentd-es
      </exclude>
    </filter>
    
    # Parses Spring logs 
    <filter kubernetes.**>
      @id spring_parser
      @type parser
      key_name log
      <parse>
        @type regexp
        expression /^(?<time>[^ ]* [^ ]*) +(?<level>[^ ]*) +(?<pid>[^ ]*) +--- +\[ *(?<thread>[^ ]*)\] +(?<class>[^ ]*) +: +(?<message>.*)$/
        time_format %Y-%m-%d %H:%M:%S.%z
        multiline true
        keep_time_key true
      </parse>
      hash_value_field parsed
      reserve_data true
      emit_invalid_record_to_error false
    </filter>
    
    <match **>
      @type stdout
    </match>
And I got my expected result.
However, if I try the elasticsearch output plugin:

      <match **>
        @id elasticsearch
        @type elasticsearch
        @log_level info
        include_tag_key true
        host elasticsearch-logging
        port 9200
        logstash_format true
        <buffer>
          @type file
          path /var/log/fluentd-buffers/kubernetes.system.buffer
          flush_mode interval
          retry_type exponential_backoff
          flush_thread_count 2
          flush_interval 1s
          retry_forever
          retry_max_interval 30
          chunk_limit_size 2M
          queue_limit_length 8
          overflow_action block
        </buffer>
      </match>
The problem returns.
This issue may be caused by this output plugin.

**Comment by kmotrebski** [comment]
@srlps I've found that adding `@id` to any plugin makes internal logs to be suppressed. I've added the issue here: https://github.com/fluent/fluentd/issues/2248 Is it possible it is connected with this problem?

**Comment by kmotrebski** [comment]
I've found that adding `@id` to any plugin makes internal logs to be suppressed. I've added the issue here: https://github.com/fluent/fluentd/issues/2248 Is it possible it is connected with this problem?

**Comment by srlps** [comment]
Maybe adding `@id` to the plugin is causing the issue. But I decided to use another technology, so I am no longer able to test this configuration. Feel free to replicate this scenario.

**Comment by kmotrebski** [comment]
> But I decided to use another technology

@srlps Interesting. Could you please briefly write to which one and why (if other reasons that this issue?

**Comment by kodefoundry** [comment]
Hi All,
I was also facing a similar issue where I wanted to take the nginx access log message key and parse it. Similar to the spring parser above and the access logs were vanishing from ES as soon as I add this to fluentd config.
A possible explanation could be that parser is modifying the message and the new record is not getting indexed properly..
After looking at some examples online I tried by adding "reserve_data true" like below and it worked for me

```
     <filter ingress.audit.log>
       @type parser
       key_name MESSAGE
       reserve_data true
       <parse>
         @type regexp
         expression /your expression/
       <parse>
     <filter>
```
