### ISSUE TITLE
file timezone problem

### ISSUE THREAD

**Issue by f-ueno** [fluent/fluentd#1986]
Fluentd version: td-agent 1.0.2

I want to transfer logfile from CentOS to CentOS by fluentd.
I could transfer file but file switches at incorrect time.
My timezone is +0900.

- output files (ls -l)
 rw-r--r-- 1 root root  34201618  5月 15 09:02 test-log.20180514
 rw-r--r-- 1 root root  40060437  5月 16 09:01 test-log.20180515
 rw-r--r-- 1 root root   5943936  5月 16 10:47 test-log.20180516

I want files switch at 00:00 but actually they switch at 09:00 everyday.
When I set time_slice_format = %Y%m%d_%H files switch correctly. (test.log.20180516_01 is created at 01:00 )

how can I solve it?

config (input) :
```
<source>
 type tail
 format none
 path /var/log/test-log
 pos_file /var/log/td-agent/test-log.pos
 tag hostfrom.test-log
</source>

<match *.*>
 type forward
 <server>
  host hostlog
  port 24224
 </server>
</match>
```

config (output) :
```
<source>
 @type forward
 bind 0.0.0.0
 port 24224
</source>

<match hostfrom.test-log>
 type file
 format single_value
 buffer_path /var/log/td-agent/buffer/test-log.buf
 path /log/test-log
 append true
 path_suffix
</match>
```

**Comment by luweiv9988** [comment]
i got same issue

**Comment by repeatedly** [comment]
The problem is  `%Y%m%d` time rage causes incorrect time but `%Y%m%d%H`time range has no problem, right?

**Comment by f-ueno** [comment]
Yes, %Y%m%d only happens.

**Comment by repeatedly** [comment]
Okay, will check.
For workaround, you can use `timekey 3600` in `<buffer>` and `%Y%m%d` in the `path`.

**Comment by f-ueno** [comment]
> For workaround, you can use timekey 3600 in <buffer> and %Y%m%d in the path.

It did not work because of config error.

[error]: config error file="/etc/td-agent/td-agent.conf" error_class=Fluent::ConfigError error="insufficient timestamp placeholders in path"

`%Y%m%d%H` in the `path` worked with `timekey 3600`

**Comment by luweiv9988** [comment]
@f-ueno  I try to set %Y%m%d%H in path, but getting configure error...

```
<match message.*>
  @type file
  path /tmp/messages/transfer.${tag[1]}.%Y-%m-%d.%H%M.log
  compress gzip
  append true
  <buffer tag,time>
    @type file
    path /tmp/buffer/message
    timekey     1d
    timekey_wait 0
    flush_mode interval
    flush_interval 86400
  </buffer>
</match>
```

**Comment by f-ueno** [comment]
@luweiv9988 I think you should use correct path depending on timekey

`%Y%m%d`  with  `timekey 1d`
`%Y%m%d%H`  with  `timekey 1h`
`%Y%m%d%H%M`  with  `timekey 1m`

**Comment by repeatedly** [comment]
It seems time calculation with larger timekey has bug.
I'm now trying to fix the problem.

**Comment by f-ueno** [comment]
@repeatedly do you have any workaround if the problem is not fixed ?

**Comment by okkez** [comment]
@f-ueno Could you try #2054?
