### ISSUE TITLE
Filter that changes tag

### ISSUE THREAD

**Issue by martinhynar** [fluent/fluentd#1987]
Rather than problem, I have a question. Is there a way to modify event's tag without re-issuing it to the whole processing pipeline as `rewrite_tag_filter` does?

I have a pipeline where at the end I need to change tag to certain value from record itself so that influxdb plugin stores it into given measurement (it uses tag for this). This value is variable, so I cannot use it for routing. Influxdb plugin for fluentd claims it supports `remove_tag_prefix`, which would suffice, but that seems to be not working.

**Comment by cosmo0920** [comment]
> Influxdb plugin for fluentd claims it supports remove_tag_prefix, which would suffice, but that seems to be not working.

Umm, fluent-plugin-influxdb's document is outdated.

And don't use github issue for quesiton. Please follow guideline.
Please consider to send your question slack or ML first.
