### ISSUE TITLE
installation failed on amazon linux 2018.03

### ISSUE THREAD

**Issue by shinji-m** [fluent/fluentd#1991]
It is failed to install td-agent and got 404 error if we use install script provided on https://docs.fluentd.org/v1.0/articles/install-by-rpm.

td-agent version:
v1.0, v0.12

Environment:
Amazon linux 2018.03

tried Install scripts:
$ curl -L https://toolbelt.treasuredata.com/sh/install-redhat-td-agent2.sh | sh
$ curl -L https://toolbelt.treasuredata.com/sh/install-amazon1-td-agent3.sh | sh
$ curl -L https://toolbelt.treasuredata.com/sh/install-amazon2-td-agent3.sh | sh

**Comment by repeatedly** [comment]
This is td-agent issue, not fluentd.

**Comment by randomor** [comment]
Seeing the same issue. td-agent repo is deprecated, omnibus td-agent can only build from source... 😫
