### ISSUE TITLE
Facing issue with customizing logging-image version v3.9 on openshift

### ISSUE THREAD

**Issue by himmatb** [fluent/fluentd#1992]
- fluentd version : 12.42
- Environment : RHEL

We have EFK stack running on openshift which provides us centralize logging capability for our openshift cluster. In our EFK stack, Fluentd is using below docker images and configuration files which run as an aggregator and fowarder for our logging solution :

- https://github.com/openshift/origin-aggregated-logging/tree/release-3.9/fluentd
(registry.access.redhat.com/openshift3/logging-fluentd:v3.9)

As per my customization need I am trying to customize fluentd docker images which provides me addon logs for security related features for ssh attacks, dissallowed ssh or authorized ssh login and other with below configuration ..

Dockerfile:
```
FROM registry.access.redhat.com/openshift3/logging-fluentd:v3.9

COPY fluent-plugin-grok-parser-1.0.1.gem .
RUN gem install fluent-plugin-grok-parser-1.0.1.gem
COPY input-pre-secure.conf /etc/fluent/configs.d/openshift/
COPY filter-pre-secure.conf /etc/fluent/configs.d/openshift/
```

Below is my input-pre-secure.conf
```
<source>
@type tail
@label @INGRESS
@id secure-input
path /var/log/secure*
read_from_head true
pos_file /var/log/secure.log.pos
tag audit.log
format none
</source>
```
and filter-pre-secure.conf
```
<filter audit.log>
@type parser
key_name message
format grok
<grok>
        pattern (?<timestamp>%{WORD} %{DATA} %{TIME}) %{HOSTNAME:host_target} sshd\[%{BASE10NUM}\]: (?<EventType>%{WORD} %{WORD}) (?<USERNAME>%{WORD}) from %{IP:src_ip} port %{BASE10NUM:port}
</grok>
<grok>
        pattern (?<timestamp>%{WORD} %{DATA} %{TIME}) %{HOSTNAME:host_target} sshd\[%{BASE10NUM}\]: %{DATA:EventType} for %{USERNAME:username} from %{IP:src_ip} port %{BASE10NUM:port} ssh2
</grok>
</filter>
```
I have deployed new logging images for aggregator and fluentd daemonset but i endup with below mentioned error .. please help !!

config error file="/etc/fluent/fluent.conf" error="'format' parameter is required"

2018-05-17 14:58:00 +0400 [info]: reading config file path="/etc/fluent/fluent.conf"
  | 2018-05-17 14:58:01 +0400 [warn]: 'block' action stops input process until the buffer full is resolved. Check your pipeline this action is fit or not
  | 2018-05-17 14:58:02 +0400 [warn]: 'block' action stops input process until the buffer full is resolved. Check your pipeline this action is fit or not
  | 2018-05-17 14:58:02 +0400 [error]: config error file="/etc/fluent/fluent.conf" error="'format' parameter is required"

I have tried above configuration in my local environment its working perfectly but while i am adding above configuration with docker images i am facing issue and getting above error.
 
Help will be appreciated!!! 
Thanks in advance!!

**Comment by himmatb** [comment]
Guys do you have any suggestions for. Above problem which i am facing..! Please help me.

**Comment by cosmo0920** [comment]
https://github.com/fluent/fluent-plugin-grok-parser#requirements helps you?
fluent-plugin-grok-parser does not support former Fluentd v0.12.

**Comment by himmatb** [comment]
It didnt help me.. becoz same thing is working on my local environment anyways i am closing this issue ..
