### ISSUE TITLE
FkuentD/td-agent as Log Aggregator in active-active configuration for 2, 3,.. nodes is possible?

### ISSUE THREAD

**Issue by fchiorascu** [fluent/fluentd#1998]
- fluentd or td-agent version.
**td-agent-2.3.6-0.el7.x86_64**

- Environment information, e.g. OS.
**CentOS Linux release 7.3.1611 (Core)**

- Your configuration.
- Your problem explanation. If you have an error logs, write it together.

Is there a way of configuring 2 nodes as log aggregators with FluentD in active-active configuration?

**Comment by cosmo0920** [comment]
https://docs.fluentd.org/v1.0/articles/high-availability may help you.

And don't use github issue for quesiton. Please follow guideline.
Please consider to send your question into community slack or Mailing List first.

**Comment by fchiorascu** [comment]
Already did this, thank you and sorry.
