### ISSUE TITLE
Filtering messages with a certain container_name does not work

### ISSUE THREAD

**Issue by grebois** [fluent/fluentd#2008]
- fluentd or td-agent version.

2.1.0

- Environment information, e.g. OS.

Kubernetes

- Your configuration

```
    # Source: https://docs.fluentd.org/v0.12/articles/filter_grep
    <filter **>
      @type grep
      <exclude>
        key kubernetes.container_name
        pattern istio-proxy
      </exclude>
    </filter>
```

- Your problem explanation. If you have an error logs, write it together.

Filtering messages with a certain container_name does not work, still showing on the logs.

**Comment by repeatedly** [comment]
If you want to access nested filed lilke `record["kubernetes"]["field"]`, you need to use v1.x serise: https://docs.fluentd.org/v1.0/articles/filter_grep#%3Cexclude%3E-directive

**Comment by grebois** [comment]
@repeatedly many thanks, works now :)
