### ISSUE TITLE
Pushing incomplete logs to S3

### ISSUE THREAD

**Issue by ku-s-h** [fluent/fluentd#2009]
**Fluentd version:** 1.1.3

My application writes logs to a file (600 logs/sec) which fluentd tails and pushes to s3 every 10 mins. Sometimes these files do not contain all the logs. For example yesterday, 5 consecutive files being pushed to s3 started and ended at the following lines numbers from the main log file.

10.json
S 355508
E 493247

20.json
S 722455
E 984158

30.json
S 1105528
E 1497162

40.json
S 1497163
E 1906154

50.json
S 1906155
E 2052295

Here, the start and end of files 10.json, 20.json and 30.json don't match but subsequent ones match. Also, weirdly, fluentd reads from the same file and send the logs to elasticsearch as well. There all the logs are present.

Config:
```
<source>
  @type tail
  format json
  read_from_head true
  path PATH
  exclude_path EXCLUDE_PATH
  pos_file POS_FILE
  tag s3
</source>

<match s3>
  @type s3

  aws_key_id KEY
  aws_sec_key SECRET
  s3_region REGION
  s3_bucket BUCKET
  path PATH
  s3_object_key_format FORMAT
  <buffer time>
    @type file
    path PATH
    timekey 600
    timekey_wait 30
    compress gzip
    flush_at_shutdown true
    chunk_limit_size 256m
  </buffer>

  <format>
    @type json
  </format>

  time_slice_format %Y-%m-%d-%H
</match>
```
Spread over multiple instances, this behaviour causes us to loose hundreds of thousands of logs over a 24hr period.

**Comment by mlasevich** [comment]
Have you checked if the files are still in buffer on local machine? I am noticing a similar issue where s3 seems to leave some chunks in the buffer well beyond the flush time. Restarting the service seem to eventually get them gone... we have retry forever with retry max interval set and no errors in the log related to s3 :-/
