### ISSUE TITLE
Error 'emit transaction failed  error="parse error.""'

### ISSUE THREAD

**Issue by iktiar** [fluent/fluentd#2010]
- fluentd version: v0.10.23 is
- OS: CentOS release 5.8 (Final)
- My server receives forwarding flunetd log. But when tried to parse them, gets 

> "2018-06-06 13:42:52 +0900: /usr/local/lib/ruby/gems/1.9.1/gems/fluentd-0.10.23/lib/fluent/plugin/in_forward.rb:75:in `run'
> 2018-06-06 13:43:52 +0900: emit transaction failed  error="parse error.""
    
[fluntd_conf.txt](https://github.com/fluent/fluentd/files/2078950/fluntd_conf.txt)
[error.txt](https://github.com/fluent/fluentd/files/2078951/error.txt)

-- Fluentd configuration 
[fluntd_conf.txt](https://github.com/fluent/fluentd/files/2078957/fluntd_conf.txt)
-- Error text
[error.txt](https://github.com/fluent/fluentd/files/2078959/error.txt)

**Comment by repeatedly** [comment]
fluentd v0.12.23 is EoL, I said this point in Mailing list.
Closed.
