### ISSUE TITLE
Getting error,  emit transaction failed: error_class=MessagePack::UnknownExtTypeError error="unexpected extension type"

### ISSUE THREAD

**Issue by iktiar** [fluent/fluentd#2011]
- fluentd version: 0.12.23
- OS:  CentOS Linux release 7.4.1708 (Core)
- Flunetd configuration
[fluntd_conf.txt](https://github.com/fluent/fluentd/files/2079503/fluntd_conf.txt)
- My server receives forwarding flunetd log. But when tried to parse them, gets 
> [warn]: emit transaction failed: error_class=MessagePack::UnknownExtTypeError error="unexpected extension type" tag="logging"

**Comment by repeatedly** [comment]
Maybe, your forwarder sends new Timestamp value.

https://docs.fluentd.org/v0.12/articles/in_forward#i-got-messagepack::unknownexttypeerror-error.-why?

**Comment by iktiar** [comment]
using 
`time_as_integer true`
has fixed the issue. Thank you.
