### ISSUE TITLE
emit transaction failed  error="parse error." for different fluentd version

### ISSUE THREAD

**Issue by iktiar** [fluent/fluentd#2013]
- fluentd version in_forward: 0.10.23 and out_forward: 0.12.23
-  in_forward OS: CentOS release 5.8 (Final) and out_forward OS: 7.4.1708 (Core)
-  configuration: in_forward
[in_forward_fluntd_conf.txt](https://github.com/fluent/fluentd/files/2082971/in_forward_fluntd_conf.txt)
- configuration out_forward
[out_forward_fluntd_conf .txt](https://github.com/fluent/fluentd/files/2082972/out_forward_fluntd_conf.txt)

When fluent (out_forward) forwards log to in_forward it getting following error.
`2018-06-08 12:58:33 +0900: /usr/local/lib/ruby/gems/1.9.1/gems/fluentd-0.10.23/lib/fluent/plugin/in_forward.rb:75:in `run'
2018-06-08 14:08:04 +0900: emit transaction failed  error="parse error."`
`2018-06-08 14:08:04 +0900: /usr/local/lib/ruby/gems/1.9.1/gems/fluentd-0.10.23/lib/fluent/plugin/in_forward.rb:75:in `run'
2018-06-08 14:08:04 +0900: forward error: parse error.`

**Comment by repeatedly** [comment]
v0.10 releated issues are closed due to v0.10 is EoL.
