### ISSUE TITLE
Precision lost when msgpacking EventTime

### ISSUE THREAD

**Issue by five-iron** [fluent/fluentd#2015]
For example
`> MessagePack.unpack(MessagePack.pack(Fluent::EventTime.now))`
returns only seconds:
`=> 1528611264`.

I see that [to_msgpack_ext](https://github.com/fluent/fluentd/blob/master/lib/fluent/time.rb#L80) exists, which would preserve the nanoseconds, but it doesn't seem to be getting called. Is there some configuration I need in order to use to_msgpack_ext instead?

**Comment by repeatedly** [comment]
See https://github.com/fluent/fluentd/blob/master/lib/fluent/msgpack_factory.rb
You need to regsiter ext type.

**Comment by repeatedly** [comment]
Please follow contribution guide. Don't use github issue for question.
