### ISSUE TITLE
HTTP input plugin failed to parse array of json when there is "time" property that is not a number

### ISSUE THREAD

**Issue by yantang-msft** [fluent/fluentd#2018]
Fluentd Version: 1.2.1
Environment: Windows 10
Configuration: 
```
<source>
  @type http
  port 8887
  <parse>
    @type json
    time_key nil
  </parse>
</source>

<match **>
  @type stdout
</match>
```
Problem:
Running this command `curl -X POST -d '[{"foo":"bar", "time": "2018-06-12T18:35:48.1488850Z"},{"abc":"def"},{"xyz":"123"}]' http://localhost:8887/app.log
` gives me this error `can't convert String into an exact number
`
This parsing logic should respect the `time_key nil` in the setting. It's not a problem if I'm only sending one json object like `curl -X POST -d '{"foo":"bar", "time": "2018-06-12T18:35:48.1488850Z"}' http://localhost:8887/app.log`

**Comment by repeatedly** [comment]
Sorry, I missed this issue.
Just created the patch: https://github.com/fluent/fluentd/pull/2025

**Comment by yantang-msft** [comment]
@repeatedly Yes, verified the fix to be working. Thank you for the quick turn around.
