### ISSUE TITLE
Json in 'log' field not parsed/exploded after migration from 0.12 to 1.2

### ISSUE THREAD

**Issue by jakubbujny** [fluent/fluentd#2021]
- fluentd or td-agent version: docker image fluent/fluentd-kubernetes-daemonset:v1.2-debian-elasticsearch
- Environment information, e.g. OS: kubernetes 1.9 
- Your configuration: default
- Your problem explanation. If you have an error logs, write it together.
I'm pushing microservices logs into Elasticsearch using fluentd. Our microservices are making json logs to stdout where Kubernetes catch them and stream to json files making 'json in json'. In version 0.12 those logs were automatically 'exploded' so I had possibility to easily filter by fields in those logs in Elasticsearch. In Fluentd 1.12 I see only json string in Kubernetes 'log' field. What happend?

**Comment by jakubbujny** [comment]
Thank you @repeatedly for answer!
Here is Log:
`{"log":"{\"Timestamp\":\"2018-06-11T14:44:57.3591704+00:00\",\"Level\":\"Warning\",\"MessageTemplate\":\"The LINQ expression '{expression}' could not be translated and will be evaluated locally.\",\"RenderedMessage\":\"The LINQ expression '\\\"where ([x] == [dummy].something)\\\"' could not be translated and will be evaluated locally.\"", "stream":"stdout","time":"2018-06-11T14:44:57.364059249Z"}`

In 0.12 I was able to easily filter in Elasticsearch using for example Level field. Now after migration I cant as in Elasticsearch I see only "log" field with whole json string which I provided

**Comment by jcardoso-bv** [comment]
We're having the exact same issue.

On 1.1.3 our JSON logs were being parsed correctly. Using 1.2.2, which fixes a stack trace problem we were having, no JSON log parsing is occuring.

Neither of the following configurations work for us on 1.2.x:

```
    <source>
      @id source_kubernetes_containers
      @type tail
      path /var/log/containers/*.log
      pos_file /var/log/fluentd/kubernetes-containers.pos
      read_from_head true
      tag kubernetes.*
      <parse>
        @type json
        json_parser yajl
        time_format %Y-%m-%dT%H:%M:%S.%NZ
      </parse>
    </source>
```
```
    <source>
      @id source_kubernetes_containers
      @type tail
      path /var/log/containers/*.log
      pos_file /var/log/fluentd/kubernetes-containers.pos
      read_from_head true
      tag kubernetes.*
      <parse>
        @type json
        time_format %Y-%m-%dT%H:%M:%S.%NZ
      </parse>
    </source>
```

**Comment by jakubbujny** [comment]
I confirm that downgrade to 1.1.3 fix the problem

**Comment by repeatedly** [comment]
https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter/pull/128

I found the root cause is fluent-plugin-kubernetes-metadata-filter removes automatic json merging feature since latest version.

**Comment by jakubbujny** [comment]
Fix for that in new version can be achieved using 
https://docs.fluentd.org/v1.0/articles/filter_parser
https://docs.fluentd.org/v1.0/articles/parser_json
as mentioned in https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter/issues/79 
Probably it can look like:
```
<filter foo.bar>
  @type parser
  format json
  key_name log
</filter>
```

**Comment by bamb00** [comment]
@jcardoso-bv I'm running version 1.1.3 for now. Could not get json_parser plugin to work in 1.2.4.  Can I see the complete conf? Are you using the filter parser with the <source> you have above.

> We're having the exact same issue.
> 
> On 1.1.3 our JSON logs were being parsed correctly. Using 1.2.2, which fixes a stack trace problem we were having, no JSON log parsing is occuring.
> 
> Neither of the following configurations work for us on 1.2.x:
> 
> ```
>     <source>
>       @id source_kubernetes_containers
>       @type tail
>       path /var/log/containers/*.log
>       pos_file /var/log/fluentd/kubernetes-containers.pos
>       read_from_head true
>       tag kubernetes.*
>       <parse>
>         @type json
>         json_parser yajl
>         time_format %Y-%m-%dT%H:%M:%S.%NZ
>       </parse>
>     </source>
> ```
> ```
>     <source>
>       @id source_kubernetes_containers
>       @type tail
>       path /var/log/containers/*.log
>       pos_file /var/log/fluentd/kubernetes-containers.pos
>       read_from_head true
>       tag kubernetes.*
>       <parse>
>         @type json
>         time_format %Y-%m-%dT%H:%M:%S.%NZ
>       </parse>
>     </source>
> ```

**Comment by Dinidu** [comment]
Im also having the same issue and tried couple of filter parser configs suggested here, but didn't work.. Any solution ?

**Comment by Dinidu** [comment]
FIX : https://github.com/fluent/fluentd/issues/2073#issuecomment-409469227
