### ISSUE TITLE
Multiline message issue with multi parsing

### ISSUE THREAD

**Issue by kumaravel29** [fluent/fluentd#2022]
Hello All,

I have a query related to the fluentd parser.
I receive multiple log messages(stacktrace) which is read using the tail plugin and parsed using multiline format and regular expression.
Further in the configuration i require to parse on the fields i the record using regular expression which contains the multiline part. When this is done, I loss the multiline message.

Example:
Raw message 
"[2018-05-28 09:30:32,170][DEBUG] [hostname] [indexname][1], node[xxxxx], [P], v[108], s[STARTED], a[id=xxxxx]: Failed to execute [org.elasticsearch.action.search.SearchRequest@7ca2d42a] lastShard [true]
RemoteTransportExceptionnested: IllegalArgumentException[Invalid format: "2017-12-23T7:59:59" is malformed at "7:59:59"];
Caused by: ElasticsearchParseException[failed to parse date field [2017-12-23T7:59:59] with format [strict_date_optional_time||epoch_millis]]; nested: IllegalArgumentException[Invalid format: "2017-12-23T7:59:59" is malformed at "7:59:59"];
        at org.elasticsearch.common.joda.DateMathParser.parseDateTime(DateMathParser.java:203)
        at org.elasticsearch.common.joda.DateMathParser.parse(DateMathParser.java:67)
"
Configuration:
```
<system>
  @log_level info
  <log>
    format json
  </log>
</system>

<source>
  @type tail
  path /log/elasticsearch/logs/*.log
  tag logfile
  format multiline
  multiline_flush_interval 5s
  format_firstline /^\[[0-9]{4}-[0-9]{2}-[0-9]{2}/
  format1 /^(?<message>.*)$/
  read_from_head true
  rotate_wait 5
  pos_file /etc/td-agent/td-agent-elasticsearch.pos
</source>

<filter logfile>
  @type parser
  key_name message
  reserve_data true
  <parse>
    @type regexp
    expression /^\[(?<timestamp>[^\]]+)\]\[(?<logLevel>[^\]]+)\] (?<message>.*)$/
  </parse>
</filter>

<match logfile>
  @type rewrite_tag_filter
  <rule>
    key logLevel
    pattern ^(\w*)
    tag $1.logfile
  </rule>
</match>

<filter DEBUG.logfile>
  @type parser
  key_name message
  reserve_data true
  <parse>
    @type regexp
    expression /^\[(?<hostname>[^\]]+)\] \[(?<indexname>[^\]]+)\](?<message>.*)$/
  </parse>
</filter>
```

Output:
```
{"timestamp": "2018-05-28 09:30:32,170",
"logLevel": "DEBUG",
"hostname": "hostname",
"indexname": "indexname",
"message":"[1], node[xxxxx], [P], v[108], s[STARTED], a[id=xxxxx]: Failed to execute [org.elasticsearch.action.search.SearchRequest@7ca2d42a] lastShard [true]"
}
```
The message field loses the multiline message and same is possible to maintained if we modify the message field by replacing \n in the message to something like '***' using the config 
```
<filter logfile>
  @type record_transformer
  enable_ruby true
  <record>
    message ${record["message"].gsub(/\n/,'***')}
  </record>
</filter>
```
 and then the output is like below
 ```
 {"timestamp": "2018-05-28 09:30:32,170",
 "logLevel": "DEBUG",
 "hostname": "hostname",
 "indexname": "indexname",
 "message":"[1], node[xxxxx], [P], v[108], s[STARTED], a[id=xxxxx]: Failed to execute [org.elasticsearch.action.search.SearchRequest@7ca2d42a] lastShard [true]***RemoteTransportExceptionnested: IllegalArgumentException[Invalid format: "2017-12-23T7:59:59" is malformed at "7:59:59"];*** Caused by: ElasticsearchParseException[failed to parse date field [2017-12-23T7:59:59] with format [strict_date_optional_time||epoch_millis]]; nested:***IllegalArgumentException[Invalid format: "2017-12-23T7:59:59" is malformed at "7:59:59"];***         at org.elasticsearch.common.joda.DateMathParser.parseDateTime(DateMathParser.java:203)***         at org.elasticsearch.common.joda.DateMathParser.parse(DateMathParser.java:67)"
 }
 ```

Is there a better way to handle this scenario?

**Comment by ganmacs** [comment]
it's a stale issue. I'm closing. if you have any problem, updating fluentd might help it.
