### ISSUE TITLE
td-agent runs into error of dns name resolution

### ISSUE THREAD

**Issue by shahamit2** [fluent/fluentd#2033]
Check [CONTRIBUTING guideline](https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md) first and here is the list to help us investigate the problem.

- fluentd or td-agent version.
td-agent 3
(http://packages.treasuredata.com/3/redhat/6/x86_64)
- Environment information, e.g. OS.
redhat6
- Your configuration
<source>
  type syslog
  tag graylog2
</source>
<source>
  @type tail
  path /opt/reuters/data/elasticsearch/logs/ES_cluster_12.log 
  pos_file /var/log/td-agent/httpd-access.log.pos
  tag fluentd.ip-172-30-200-49.*
  format none
</source>
<match **>
  type copy
  <store>
    type gelf
    host <route53 url>
    port 9896
    buffer_chunk_limit 256m
    buffer_queue_limit 30000
    num_threads 2
    flush_interval 5s
  </store>
  <store>
    type stdout
  </store>
</match>
- Your problem explanation. If you have an error logs, write it together.
Total messages to send 30,00,000
- It runs into error after sending 30,000 messages. 
- If host route53 url is replaced with host IP then it works like a charm.

**Comment by repeatedly** [comment]
It seems plugin issue, not core issue.
