### ISSUE TITLE
Http input plugin doesn't hornor parser time_format in batched scenario

### ISSUE THREAD

**Issue by yantang-msft** [fluent/fluentd#2035]
Fluentd Version: 1.2.1
Environment: Windows 10
Configuration: 
```
<source>
  @type http
  port 8887
  <parse>
    @type json
    time_format %iso8601
  </parse>
</source>

<match **>
  @type stdout
</match>
```
Problem:
Running this command `curl -X POST -d '[{"foo":"bar", "time": "2018-06-12T18:35:48.1488850Z"},{"abc":"def"},{"xyz":"123"}]' http://localhost:8887/app.log
` gives me this error `can't convert String into an exact number
`

It's very similar to this issue https://github.com/fluent/fluentd/issues/2018 I reported earlier. The difference is this time it's the time_format parameter instead of the time_key.
With this fix https://github.com/fluent/fluentd/pull/2025, I can workaround the issue by setting time_key to nil, so it's not an urgent for me. But still it would nicer if the time_format parameter is also supported in batched scenario.

**Comment by bitc** [comment]
I am seeing this too. Sending a single JSON event works, but sending a JSON array with multiple events triggers this error

**Comment by yantang-msft** [comment]
@fujimotos I confirm the patch fixes this issue. 😄

**Comment by fujimotos** [comment]
Now it has been merged in to the master branch today.
Thanks for reporting the issue and testing the patch.
