### ISSUE TITLE
No Patterns Matched

### ISSUE THREAD

**Issue by aj-rame3** [fluent/fluentd#2040]
I installed fluentd 1.2.2 on Ubuntu 16.04
I wrote an input login to listen to SNMP traps.
Everything was working good and suddenly, I keep getting the message
"#0 no patterns matched tag="SNMPTag""
 the logs give 

2018-06-26 17:50:01 -0700 [warn]: #0 fluent/log.rb:342:warn: no patterns matched tag="SNMPTag"
2018-06-26 17:50:01 -0700 [trace]: #0 fluent/log.rb:281:trace: no patterns matched tag="SNMPTag"

My Config looks like this

```
  <source>
    @type inputsnmp
    host "0.0.0.0"
    port 162
    tag "SNMPTag"
  </source>
  <match SNMPTag*>
    @type stdout
  </match>
```
Can somebody help me with this. I uninstalled and reinstalled the fluentd plugin. Not sure what is causing this issue.

**Comment by cosmo0920** [comment]
Please read the guideline.
https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md#got-a-question-or-problem
Closing for now.

**Comment by aj-rame3** [comment]
Do you know why this issue is coming up ? I thought it was a bug ? Why was it closed

**Comment by cosmo0920** [comment]
> Don't use Github issue for asking questions. 

Please send your question into [community slack](https://slack.fluentd.org/) or [mailing list](https://groups.google.com/forum/#!forum/fluentd) first.
