### ISSUE TITLE
Nginx logrotate isn't detected

### ISSUE THREAD

**Issue by Trane9991** [fluent/fluentd#2042]
Fluentd configuration: fluentd 1.2.2
Environment: Amazon Linux, Alpine docker image
Tail configuration:
```
<source>
  @type tail
  limit_recently_modified 1d
  format json
  path /var/log/nginx/access.log
  pos_file /fluentd/log/nginx-access.pos
  tag access
</source>
```

Logrotate configuration:
```
/var/log/nginx/*log {
    create 0644 nginx nginx
    daily
    rotate 10
    missingok
    notifempty
    compress
    sharedscripts
    postrotate
        /etc/init.d/nginx reopen_logs
    endscript
}
```

Logs:
```
$ docker logs fluentd | grep nginx
2018-06-26 15:05:53 +0000 [info]: #0 following tail of /var/log/nginx/access.log
```

Cron:
```
Jun 27 03:16:01 ip-10-0-111-92 run-parts(/etc/cron.daily)[23102]: starting logrotate
Jun 27 03:16:06 ip-10-0-111-92 run-parts(/etc/cron.daily)[23129]: finished logrotate
```

Nginx log files:
```
-rw-r--r-- 1 nginx nginx 21619455 Jun 27 09:05 access.log
-rw-r--r-- 1 root   root    4634491  Jun 27 03:16 access.log-20180627.gz
```

The last processed log arrived at 03:16.

Other applications logfiles seem to be picked up fine after the rotation.
Working logrotate configs:
```
/var/log/containers/*.log {
size 1M
rotate 5
missingok
compress
notifempty
copytruncate
dateext
dateformat %s
olddir /var/log/containers/rotated
}
```

Any ideas?

**Comment by repeatedly** [comment]
Hmm... your log rotation config has `create 0644 nginx nginx` line.
Does fluentd can read new log file, right?

**Comment by repeatedly** [comment]
Hmm... fluentd logs "detected rotation" in the fluentd log but no such logs only for `/var/log/nginx/access.log`, right?

**Comment by Trane9991** [comment]
Yes.
Actually, I updated configurations, to make it work, but weird that it doesn't work with the default logrotate settings.

(I will post working configurations in a min)

**Comment by Trane9991** [comment]
No, I didn't see any errors/warnings in fluentd log.

But I made it work by adding `copytruncate`  and removing the `/etc/init.d/nginx reopen_logs` options.

Working logrotate config:
```
            /var/log/nginx/*log {
                size 1M
                rotate 5
                missingok
                compress
                notifempty
                copytruncate
                dateext
            }
```

Now I can see:
```
2018-07-05 03:41:08 +0000 [info]: #0 detected rotation of /var/log/nginx/access.log
2018-07-05 03:41:08 +0000 [info]: #0 following tail of /var/log/nginx/access.log
```

**Comment by okkez** [comment]
Already resolved by the reporter. Closing.
