### ISSUE TITLE
remote_syslog

### ISSUE THREAD

**Issue by d4ntheman** [fluent/fluentd#2043]
Hello,

I'm using td-agent version on Redhat 7.X. All worked fine, until I followed documentation to install the remote_syslog plugin!   After running the following command, I can no longer start td-agent:

./fluent-gem install fluent-plugin-remote_syslog

the same problem happens if instead this command is used:

/usr/sbin/td-agent-gem install fluent-plugin-remote_syslog

Please advise !

**Comment by cosmo0920** [comment]
Could you show us your failure log?
Thanks.

**Comment by okkez** [comment]
No response. Closing.
