### ISSUE TITLE
Compression support in http input/output plugin

### ISSUE THREAD

**Issue by kishoreck** [fluent/fluentd#2047]
Summary:

When http is used as a medium of transport for large volumes of data, it will be helpful to have compression support in place. Data compression support in buffers and forward plugin is already made available. It will be a nice to have the compression support in the http plugins as well.

**Comment by repeatedly** [comment]
So you want to send large data with gzip to in_http, right?

**Comment by kishoreck** [comment]
Yup. That's correct.

**Comment by repeatedly** [comment]
Merged #2060

**Comment by kishoreck** [comment]
Awesome. Thanks👍

**Comment by boumitran** [comment]
we are looking forward to have a fluentd release with this in_http compression support. When is the next release schedule?

**Comment by rockliffelewis** [comment]
Hi,

Looking at the Pull Request #2060 , it would appear that this was only added to `in_http` and not the `out_http` plugin as well?

It would be most excellent if this could be added in, for http based fluentd to fluend setups.

**Comment by daipom** [comment]
Looks like it is not added to the `out_http`.
Could you make a new issue for the feature request?
