### ISSUE TITLE
how to resend buffer data

### ISSUE THREAD

**Issue by Barbazoo** [fluent/fluentd#2053]
Check [CONTRIBUTING guideline](https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md) first and here is the list to help us investigate the problem.

- fluentd or td-agent version.  fluentd:0.12
- Environment information, e.g. OS.   centos
- Your configuration        
- Your problem explanation. If you have an error logs, write it together.
I use fluentd read and write data to write es, because of es problems, resulting in a lot of chunk underneath worker(some file like buffer.q570**.log and .meta), so I move buffer worker to other disk and  restart fluentd, write recovery normal, now how can I  resend that data, I tried to copy meta and the log files  into the new buffer worker folder, which is not well.

**Comment by cosmo0920** [comment]
I guess you can use file buffer.

```aconf
<match **>
  @type elasticsearch
   buffer_type file
   buffer_path /var/log/fluent/myapp.*.buffer
  # ...
</match>
```

https://docs.fluentd.org/v0.12/articles/buf_file
And this is a question. Github issue is not for questions. Closed.
