### ISSUE TITLE
Bundler injection exiting unclean

### ISSUE THREAD

**Issue by therealgambo** [fluent/fluentd#2056]
Check [CONTRIBUTING guideline](https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md) first and here is the list to help us investigate the problem.

- fluentd or td-agent version. `v1.2.2 - fluent/fluentd-kubernetes-daemonset:v1.2-debian-elasticsearch`

Using `FLUENTD_DISABLE_BUNDLER_INJECTION` to install additional gems at runtime, the following error is happening occasionally.

```
/fluentd/vendor/bundle/ruby/2.3.0/gems/fluentd-1.2.2/lib/fluent/command/bundler_injection.rb:32:in `exit': no implicit conversion from nil to integer (TypeError)
	from /fluentd/vendor/bundle/ruby/2.3.0/gems/fluentd-1.2.2/lib/fluent/command/bundler_injection.rb:32:in `<top (required)>'
	from /fluentd/vendor/bundle/ruby/2.3.0/gems/fluentd-1.2.2/lib/fluent/command/fluentd.rb:228:in `load'
	from /fluentd/vendor/bundle/ruby/2.3.0/gems/fluentd-1.2.2/lib/fluent/command/fluentd.rb:228:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /fluentd/vendor/bundle/ruby/2.3.0/gems/fluentd-1.2.2/bin/fluentd:8:in `<top (required)>'
	from /fluentd/vendor/bundle/ruby/2.3.0/bin/fluentd:22:in `load'
	from /fluentd/vendor/bundle/ruby/2.3.0/bin/fluentd:22:in `<main>'
Fetching gem metadata from https://rubygems.org/....
```

**Comment by repeatedly** [comment]
fluentd daemonset doesn't run bundler install at runtime: https://github.com/fluent/fluentd-kubernetes-daemonset/blob/0eb03bffb3bff86b40ad794acf4983ea7799ef10/docker-image/v1.2/debian-elasticsearch/Dockerfile#L13
Do you change this line?

**Comment by therealgambo** [comment]
Yes, I did because we are installing extra gems at runtime.
