### ISSUE TITLE
rsyslog to fluentd via ssl

### ISSUE THREAD

**Issue by 1vish99** [fluent/fluentd#2057]
Check [CONTRIBUTING guideline](https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md) first and here is the list to help us investigate the problem.

- fluentd or td-agent version.
- Environment information, e.g. OS.
- Your configuration
- Your problem explanation. If you have an error logs, write it together.

**Comment by 1tarak** [comment]
I have been configuring to send data from rsyslog to fluentd via ssl.

I have installed secure_forward plugin in fluentd. This config is as below.

**Fluentd config:**

```
<source>
  @type secure_forward
  shared_key qeu1223123ecdcdjs
  self_hostname myhostname.domain.com
  secure yes
  ca_cert_path /etc/fluentd/appcertificate.crt
  ca_private_key_path /etc/fluentd/ssl.key
  ca_private_key_passphrase passpharse
  bind myhostname.domain.com
  port 25114
  keepalive 3600
  tag system
 <server>
   @type syslog
   port 25143
   bind myhostname.domain.com
   tag system
   format none
 </server>
</source>
```
**rsyslog config**

```
$defaultNetstreamDriverCAFile /etc/rsyslog.d/ca_cert.crt
$ActionSendStreamDriver gtls
$ActionSendStreamDriverMode 1
$ActionSendStreamDriverAuthMode x509/name
$ActionSendStreamDriverPermittedPeer *.domain.com
*.* @@myhostname.domain.com:25144

```
Can someone help if I am missing something. I dont know where to set shared_key in rsyslog config. Currently if i take tcpdump i see there is data coming but i dont see the same in output file.

**Comment by cosmo0920** [comment]
secure_forward uses "forward" tls protocol which is not suitable to connect rsyslog with TLS.
There is no TLS supported input syslog implementation right now.

**Comment by richm** [comment]
perhaps you would be interested in helping with https://github.com/ViaQ/fluent-plugin-relp which would allow fluentd to accept relp input from rsyslog

**Comment by ganmacs** [comment]
This should be fixed by https://github.com/fluent/fluentd/pull/2399
