### ISSUE TITLE
HTTPDATE error with td-agent 3.1.1

### ISSUE THREAD

**Issue by arunakalla** [fluent/fluentd#2058]
- td-agent-3.1.1-0.el7.x86_64.rpm
- centos
example log
00.000.000.000 - - [03/Jul/2018:10:45:37 -0400] "GET /private/ASVTEST/marketing-test/check/health HTTP/1.1" 200 114

following code in td-agent.conf .. cannot start td-agent.service (**Job for td-agent.service failed because the control process exited with error code. See "systemctl status td-agent.service" and "journalctl -xe" for details.**)

%{IPORHOST:clientip} %{USER:ident} %{USER:auth} \[%{HTTPDATE:timestamp}\] "(?:%{WORD:verb} %{NOTSPACE:request}(?: HTTP/%{NUMBER:httpversion}))" %{NUMBER:response} (?:%{NUMBER:bytes}|-)
 
when HTTPDATE changed to GREEDYDATA ... it works

%{IPORHOST:clientip} %{USER:ident} %{USER:auth} \[%{GREEDYDATA:timestamp}\] "(?:%{WORD:verb} %{NOTSPACE:request}(?: HTTP/%{NUMBER:httpversion}))" %{NUMBER:response} (?:%{NUMBER:bytes}|-)

**Comment by repeatedly** [comment]
Does this grok plugin?

**Comment by arunakalla** [comment]
yes

<source>
  @type tail
  path /xxx/xxx/xxx/*access*
  pos_file /var/log/td-agent/access.pos
  tag test-access
  <parse>
  @type grok
  grok_pattern %{IPORHOST:clientip} %{USER:ident} %{USER:auth} \[%{HTTPDATE:timestamp}\] "(?:%{WORD:verb} %{NOTSPACE:request}(?: HTTP/%{NUMBER:httpversion}))" %{NUMBER:response} (?:%{NUMBER:bytes}|-)
  </parse>
</source>

**Comment by arunakalla** [comment]
`<source>
  @type tail
  path /prod/msp/logs/*access*
  pos_file /var/log/td-agent/firebolt-access.pos
  tag marketingContent-access
  <parse>
  @type grok
  grok_pattern %{IPORHOST:clientip} %{USER:ident} %{USER:auth} \[%{HTTPDATE:timestamp}\] "(?:%{WORD:verb} %{NOTSPACE:request}(?: HTTP/%{NUMBER:httpversion}))" %{NUMBER:response} (?:%{NUMBER:bytes}|-)
  </parse>
</source>`

**Comment by repeatedly** [comment]
It seems grok plugin issue, not fluentd core issue.
If the problem is fluentd core, please reopen the issue.
