### ISSUE TITLE
Fetch Custom logs From Plain Text File To EFK Stack

### ISSUE THREAD

**Issue by subinmt** [fluent/fluentd#2074]
Hi Guys,

I have collected some logs/data from my server and stored in a text file. Now I want to display these logs/data to my own Kibana. After a detailed googling I could understood that, its possible by the basics of indexing/inputing my logs/data text file to Fluentd. How can I do this. Please help me. 

Regards, 
Subin

**Comment by cosmo0920** [comment]
Could you post your question into [mailing list](https://groups.google.com/forum/?fromgroups#!forum/fluentd) or [community slack](http://slack.fluentd.org/)?
Thanks.

**Comment by subinmt** [comment]
I have already posted  mailing list or community slack.. But no response. Any one please help.
