### ISSUE TITLE
fluentd-geoip-plugin - config for nginx-ingress controller

### ISSUE THREAD

**Issue by mprzygrodzki** [fluent/fluentd#2075]
Hello everyone,

Looking for some help with creating proper filter for Kubernetes Nginx-Ingress which have slightly different logs as i believe then basic Nginx deployment. At the moment i'm using this kind of filter to ship logs from nginx-ingress-controller to my EFK stack, and that's fine, logs are available in Kibana:
```
  nginxingress.conf: |-
    <source>
      @type tail
      path /var/log/containers/*.log
      pos_file /var/log/es-containers.log.pos
      time_format %Y-%m-%dT%H:%M:%S.%NZ
      tag kubernetes.*
      format json
      read_from_head true
      keep_time_key true
    </source>

    <filter kubernetes.var.log.containers.ingress-nginx-ingress-controller-**>
      # https://github.com/kubernetes/ingress/tree/master/controllers/nginx#log-format
      @type parser
      reserve_data true
      hash_value_field parsed
      key_name log
      format /^(?<remote>[^ ]*) (?<host>[^ ]*) (?<user>[^ ]*) \[(?<time>[^\]]*)\] "(?<method>\S+)(?: +(?<path>[^\"]*) +\S*)?" (?<code>[^ ]*) (?<size>[^ ]*)(?: "(?<referer>[^\"]*)" "(?<agent>[^\"]*)")?$/
      time_format %d/%b/%Y:%H:%M:%S %z
    </filter>
```

Logs are shipped as JSON to Kibana as in below:

`{"proxy_protocol_addr": "","remote_addr": "100.98.22.64", "proxy_add_x_forwarded_for": "100.98.22.64", "request_id": "c5a8cc6f8519992b09a2f43452b7852c","remote_user": "", "time_local": "17/Jul/2018:14:58:09 +0000", "request" : "GET /plugins/kibana/assets/play-circle.svg HTTP/1.1", "status": "304", "vhost": "kibana.staging.xxxxxxx.com","body_bytes_sent": "0", "http_referer":  "http://kibana.staging.xxxxxxx.com/app/kibana", "http_user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36", "request_length" : "555", "request_time" : "0.002", "proxy_upstream_name": "monitoring-kibana-80", "upstream_addr": "100.100.72.251:5601",  "upstream_response_length": "0", "upstream_response_time": "0.000", "upstream_status": "304"}`

But my goal is to create proper and working configuration to get working GeoIP logs based on nginx-ingress and can visualize them on map in Kibana. Was trying different configurations but none of them seems to be working. I've installed fluentd-geoip-plugin on my machines. Searching through the topics and readme's there are mostly some examples for Apache only.

I've added this config but i believe it's not working as i dont see any data:
```
  geoip-filter.conf: |- 
    <filter kubernetes.ingress-nginx-ingress-controller-**>
        @type geoip
        # Specify one or more geoip lookup field which has ip address (default: host)
        # in the case of accessing nested value, delimit keys by dot like 'host.ip'.
        geoip_lookup_keys  remote_addr
        # Specify optional geoip database (using bundled GeoLiteCity databse by default)
        # geoip_database    "/var/lib/gems/2.3.0/gems/fluent-plugin-geoip-1.2.0/data/GeoLiteCity.dat"
        # Set adding field with placeholder (more than one settings are required.)
        <record>
          city            ${city["remote_addr"]}
          lat             ${latitude["remote_addr"]}
          lon             ${longitude["remote_addr"]}
          country_code3   ${country_code3["remote_addr"]}
          country         ${country_code["remote_addr"]}
          country_name    ${country_name["remote_addr"]}
          dma             ${dma_code["remote_addr"]}
          area            ${area_code["remote_addr"]}
          region          ${region["remote_addr"]}
          geoip           '{"location":[${longitude["remote_addr"]},${latitude["remote_addr"]}]}'
        </record>
        # To avoid get stacktrace error with `[null, null]` array for elasticsearch.
        skip_adding_null_record  true
        # Set log_level for fluentd-v0.10.43 or earlier (default: warn)
        @log_level         info
        # Set buffering time (default: 0s)
        # flush_interval    1s
    </filter>
```

- fluentd 1.2.2
- elastcc 6.3.1
- Kubernetes

**Comment by okkez** [comment]
Could you post your question into [mailing list](https://groups.google.com/forum/?fromgroups#!forum/fluentd) or [community slack](http://slack.fluentd.org/)?
Thanks.
