### ISSUE TITLE
JSON parser swallowing messages without any indication of errors

### ISSUE THREAD

**Issue by kvidhya** [fluent/fluentd#2078]
Check [CONTRIBUTING guideline](https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md) first and here is the list to help us investigate the problem.

- fluentd or td-agent version.

```google-fluentd version 1.5.30-1  ```

- Environment information, e.g. OS.

```Ubuntu 16.04.4 LTS```

- Your configuration

```
<filter us-west-2.eng.default.docker.**>
  @type parser
  <parse>
    @type multi_format
    <pattern>
      format json
    </pattern>
    <pattern>
      format none
    </pattern>
  </parse>
  key_name log
  reserve_data true
</filter>
```

- Your problem explanation. If you have an error logs, write it together.

Some JSON messages are not coming through when using `format json`
Here is the json spitting from the application:

```
{"name":"db-setup","role":"dev-center-api","serviceVersion":"1.0.20","func":"db-setup","hostname":"300e017400ee","pid":1,"level":30,"type":"read","host":"eng-ide-devcenter-23cef02b4cb6.cv0su2inxpma.us-west-2.rds.amazonaws.com","msg":"Using database server { ts: '2018-07-16T16:34:00.061Z', logLevel: 'info' }","time":"2018-07-16T16:34:00.061Z","v":0}
```
If there was no `parse json`, i can see my message in stack driver. But when i use `parse json` - i dont see anything come through. I can `jq` my json fine - so it is a legal json. 

Since the json parse plugin does not show me any errors, it is hard to troubleshoot when we change something in the JSON and logs start to disappear all of a sudden. Is it possible to record ParseExceptions in fluentd logs so we know about failures?

**Comment by kvidhya** [comment]
I tried to create this issue in google-fluentd github issues, but got refered here since this was in the base fluentd codeline.  Ref: https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud/issues/230

**Comment by repeatedly** [comment]
> Some JSON messages are not coming through when using format json

What does this mean? Output plugin doesn't receive records or it doesn't show in stackdriver?
I tested your record and parsing it is succeeded, so I'm not sure what is your problem.

**Comment by repeatedly** [comment]
In addtion, fluentd shows warning logs for parsing error by default. If no warning message, parsing is succeeded.

```
2018-07-19 02:07:08 +0900 [warn]: #0 dump an error event: error_class=Fluent::Plugin::Parser::ParserError error="pattern not match with data 'foo'" location=nil tag="test.log" time=1531933628 record={"log"=>"foo"}
```

Of course, you put `format none` in the bottom, so this error doesn't happen because `format none` captures all logs.

**Comment by kvidhya** [comment]
Some JSON messages are not coming through when using format json

>>>> What does this mean? Output plugin doesn't receive records or it doesn't show in stackdriver?
I tested your record and parsing it as json is succeeded, so I'm not sure what is your problem.
Could you show actual problematic record?


The `parse json` seems to be swallowing the messages (meaning they dont come through to google stackdriver). I dont see any warnings or errors in the agent logs. 

When I remove the `parse json` leaving behind `parse none` then I see the messages in stack driver.

So I am assuming something is happening in the json parser, but since there are no clues in agent.log - it is hard to troubleshoot.

**Comment by repeatedly** [comment]
Could you use `stdout` output instead of `stackdriver` plugin?
If stdout plugin doesn't show incoming record, parser plugin is wrong.
If stdout plugin shows incoming record, your stackdriover plugin usage is wrong.

**Comment by kvidhya** [comment]
I am not sure I follow what you mean by stackdriver plugin .. can you please give me the configuration that you want me to test with? Thanks

**Comment by eigokor** [comment]
same situation:
Logs in valid JSON format could be send to STDOUT, but when use some other plugin nothing passing.
Disabling filter bring back logs on output plugin. 
```
    <filter logs.app.json>
      @type parser
      format json
      key_name log
      reserve_data true
      remove_key_name_field false
      inject_key_prefix user-graph.
      emit_invalid_record_to_error true
    </filter>


    #<match logs.app.json>
    #  @type stdout
    #</match>

    <match **>
      @type kinesis_firehose
      region us-east-1
      delivery_stream_name elastic-logs-stream
      include_tag_key true
    </match>
```

**Comment by repeatedly** [comment]
@eigokor Could you paste your json here?

**Comment by eigokor** [comment]
Updated with log samples

**Comment by eigokor** [comment]
oh guys sorry, just noticed

once filter enabled timestamps is incorrect!

  "fluent_added_timestamp": "2018-08-03T16:07:54.000+0000",
  "@timestamp": "2018-08-03T16:07:54.000+0000"

  "fluent_added_timestamp": "1970-01-01T00:33:38.000+0000",
  "@timestamp": "1970-01-01T00:33:38.000+0000"

**Comment by calinah** [comment]
Hi @eigokor  just so you're aware Stackdriver doesn't guarantee delivery of logs as they happen. I've looked into replacing Elasticsearch with Stackdriver months ago and because of this we ended up going back to Elasticsearch.  See https://cloud.google.com/logging/docs/view/overview 
```During periods of heavy load there could be delays in sending logs to Stackdriver Logging or in receiving and displaying the logs.```

**Comment by kelson-martins** [comment]
@eigokor thanks for your update.
I was for quite some time going through the same issue and just now noted the timestamp generated once filter is enabled.

**Comment by igorpeshansky** [comment]
The Stackdriver logging backend will reject entries that are over a year old, so something from 1970 will definitely get dropped. You should see error messages in the logs informing you of dropped entries.

**Comment by bvandewalle** [comment]
Had exactly the same issue here. FYI, if your json parser doesn't have the correct time format, it will default to time zero (1970), and it will be seamlessly rejected by stackdriver.

Best way to debug this is to change the output from StackDriver to stdout and make sure the time is correctly parsed.

Here is my filter that made it work:
```
<filter gce-nginx-ingress.**>
  @type parser
  <parse>
    @type multi_format
    <pattern>
      format json
      time_key time
      time_format %d/%b/%Y:%H:%M:%S %z
    </pattern>
    <pattern>
      format none
    </pattern>
  </parse>
  key_name log
  reserve_data true
</filter>
```

**Comment by vsxen** [comment]
@beautytiger  it works for me.
