### ISSUE TITLE
Escaped string received from in_forward could NOT be removed properly.

### ISSUE THREAD

**Issue by Gabriel1688** [fluent/fluentd#2079]
Check [CONTRIBUTING guideline](https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md) first and here is the list to help us investigate the problem.

Introduction about the parser decod.
https://fluentbit.io/documentation/current/parser/decoder.html

- fluentd or td-agent version.
    td-agent-bit-0.13.3-1.x86_64 ( Fluent Bit v0.13.3 )
    td-agent-3.2.0-0.el7.x86_64

- Environment information, e.g. OS.
   Cent OS 7
   Operating System: CentOS Linux 7 (Core)
   CPE OS Name: cpe:/o:centos:centos:7
   Kernel: Linux 3.10.0-327.13.1.el7.x86_64
   Architecture: x86-64

- Your configuration

< source > // source
  @type forward

  bind 0.0.0.0

  port 24224

  @id input_forward

  tag media
< /source > // end of source

< filter media > // filter media
  @type parser

  format json

  key_name Content

  reserve_data true

  **Decode_Field_As escaped Content do_next**
< /filter > // end of filter media

< match media > // match media
  @type file

  @id output_file

  path /var/log/td-agent/access
< /match > // end of match media

-- Filters and plugins:
application side: integrate two plugins:
    fluentbit - lib
    fluentbit forward protocol

Fluentd side
   in-forward
   filter parser
   file

- Your problem explanation. If you have an error logs, write it together.
  the message sending by fluent-bit via forward protocol includes the escaped string, which is mandate for JSON syntax.  the in_forward of fluentd couldn't remove these escaped string and convert to original string.  the Decode_Field_as couldn't apply to this scenario. 

**Following is the output ofthe td-agent log regarding of  filter parser initialization.**
2018-07-18 15:57:36 -0400 **[warn]: parameter 'Decode_Field_as' in** 
@type parser
format json
key_name "Message"
reserve_data true
**Decode_Field_as escaped Message do_next**

@type json

**is not used.**
202 2018-07-18 15:57:50 -0400 [warn]: #0 dump an error event: error_class=Fluent::Plugin::Parser::ParserError error="pattern not match with data '{"Content"=>"xxxxChannelClient::onResponse() location : \\\"\\/services\\/server\\/config\\\""}'" location=nil tag="media" time=1531943867 record={"Timestamp"=>"2018-07-18 15:57:47.156182", "Host"=>"xxxx.com", "Module"=>"Server", "LogLevel"=>"DEBUG ", "context"=>"Context = ", "Message"=>{"Content"=>"xxxCtrlChannelClient::onResponse() location : \"\/services\/server\/config\""}}

**output in a file** 
2018-07-18T15:57:47-04:00   media  {"Timestamp":"2018-07-18 15:57:47.156245","Host":"xxx.com","Module":"Server","LogLevel":"INFO  ","context":"Context = ","Message":{"Content":"location: \\\"\\/services\\/server\\\""}}

**Expected behavior**
the final output after filter parser should look like following, without escaped string anymore.
2018-07-18T15:57:47-04:00 media {"Timestamp":"2018-07-18 15:57:47.156245","Host":"xxx.com","Module":"Server","LogLevel":"INFO ","context":"Context = ","Content":"location: "**/services/server**"}} 
[Note: escaped string should be removed.]

**Comment by repeatedly** [comment]
You mixed fluentd and fluent-bit configuration.
fluentd's filter_parser's documentation is here: https://docs.fluentd.org/v1.0/articles/filter_parser
Please reopen after write correct configuration.
