### ISSUE TITLE
Filter parse of fluentd failed to remove additional escaped character added by fluentbit forward protocol.

### ISSUE THREAD

**Issue by Gabriel1688** [fluent/fluentd#2081]
Check CONTRIBUTING guideline first and here is the list to help us investigate the problem.

fluentd or td-agent version.
td-agent-bit-0.13.3-1.x86_64 ( Fluent Bit v0.13.3 )
td-agent-3.2.0-0.el7.x86_64

Environment information, e.g. OS.
Cent OS 7
Operating System: CentOS Linux 7 (Core)
CPE OS Name: cpe:/o:centos:centos:7
Kernel: Linux 3.10.0-327.13.1.el7.x86_64
Architecture: x86-64

Your configuration

< source > // source
@ type forward
bind 0.0.0.0
port 24224
@ id input_forward
tag media
< /source > // end of source

< filter media.** > // filter media
@ type parser
format json
key_name Message
remove_key_name_field true
tag filtered
< parse>
@ type json
< /parse>
hash_value_field Result
< /filter > // end of filter

< match filtered > // match media
@ type stdout
< /match > // end of match media

-- Filters and plugins:
application side: integrate two plugins:
fluentbit -intput--> lib
fluentbit output--> forward protocol

Fluentd side
input --> in-forward
parse--> filter parser
output--> stdout

Your problem explanation. If you have an error logs, write it together.
the message sending by fluent-bit via forward protocol includes the escaped string, which is mandate for JSON syntax. the filter parser couldn't remove these escaped string and convert to original string. more backslash was added in the final output.
Following is the output ofthe td-agent log regarding of filter parser initialization.
2018-07-20 14:37:19 -0400 [warn]: parameter 'tag' in 
@ type forward
bind "0.0.0.0"
port 24224
@ id input_forward
tag Powermedia
is not used.

2018-07-20 14:37:19 -0400 [warn]: parameter 'format' in <filter Powermedia.**>
@ type parser
format json
key_name "Message"
remove_key_name_field true
tag filtered
hash_value_field "Result"
< parse >
@ type "json"
< /parse >
is not used.

2018-07-20 14:37:19 -0400 [warn]: parameter 'tag' in <filter Powermedia.**>
@ type parser
format json
key_name "Message"
remove_key_name_field true
tag filtered
hash_value_field "Result"
< parse>
@ type "json"
< /parse>
is not used.

2018-07-20 14:37:44 -0400 [trace]: #0 [input_forward] connected fluent socket addr="192.168.0.16" port=46210
2018-07-20 14:37:44 -0400 [trace]: #0 [input_forward] accepted fluent socket addr="192.168.0.16" port=46210
101 2018-07-20 14:37:44 -0400 [warn]: #0 dump an error event: error_class=Fluent::Plugin::Parser::ParserError error="pattern not match with data '{"Content"=>"CdrCtrlChannelClient::onResponse() data : {\\n\\t\\\"cdrFileDuration\\\" : 1,\\n\\t\\\"activeCdrAge\\\" : 1, \\n\\t\\\"maxCdrDiskSpace\\\" : 4096\\n}"}'" location=nil tag="Powermedia" time=1532111861.061555 record={"Timestamp"=>"2018-07-20 14:37:41.061551", "Host"=>"xms.dialogic.com", "Module"=>"CdrServer", "LogLevel"=>"DEBUG ", "context"=>"Context = ", "Message"=>{"Content"=>"CdrCtrlChannelClient::onResponse() data : {\n\t\"cdrFileDuration\" : 1,\n\t\"activeCdrAge\" : 1,\n\t\"maxCdrDiskSpace\" : 4096\n}"}}
2018-07-20 14:37:44 -0400 [trace]: #0 no patterns matched tag="Powermedia"

input string after input-forward of fluentd
"Message":{"Content": "2018-07-20 14:37:41.061518 DEBUG CdrCtrlChannelClient::onResponse() location : "/services/cdrserver/config"
2018-07-20 14:37:41.061545 DEBUG CdrCtrlChannelClient::onResponse() data : {
"cdrFileDuration" : 1,
"activeCdrAge" : 1,
"maxCdrDiskSpace" : 4096
}}

Expected behavior
the final output after filter parser should look like following, without escaped string anymore.
2018-07-20 14:37:41.061518 DEBUG CdrCtrlChannelClient::onResponse() location : "/services/cdrserver/config"
2018-07-20 14:37:41.061545 DEBUG CdrCtrlChannelClient::onResponse() data : {
"cdrFileDuration" : 1,
"activeCdrAge" : 1,
"maxCdrDiskSpace" : 4096
}
[Note: escaped character "" should be removed.]

**Comment by fujimotos** [comment]
Check the following line in your debug log:

> 101 2018-07-20 14:37:44 -0400 [warn]: #0 dump an error event: error_class=Fluent::Plugin::Parser::ParserError error="pattern not match with data '{"Content"=>"CdrCtrlChannelClient::onResponse() data : {\n\t\"cdrFileDuration\" : 1,\n\t\"activeCdrAge\" : 1, \n\t\"maxCdrDiskSpace\" : 4096\n}"}'"

This line basically states that the `Message` field contains a string
that cannot be intepreted as JSON. You can also see the exact data
that was passed to Fluentd in the line:

```ruby
'{"Content"=>"CdrCtrlChannelClient::onResponse() data : {\n\t\"cdrFileDuration\":
1,\n\t\"activeCdrAge\" : 1, \n\t\"maxCdrDiskSpace\" : 4096\n}"}'
```

As you can see, it's not a proper JSON string (deliminated by `=>`, not `:`).

So my guess is that your input data has been mangled somehow (possibly
before transferred to Fluentd), and you first need to make sure that the
`Message` field of each record contains a valid JSON string.
