### ISSUE TITLE
grok pattern under the filter plugin

### ISSUE THREAD

**Issue by ibrasec** [fluent/fluentd#2082]
Hi...
Referring to the helpful closed issue

parse fields added but still recieve ConfigError error="<parse> section is required." #2077

I used the same configuration but an Error message raised saying
`2018-07-22 07:06:11 +0000 [warn]: #0 no patterns matched tag="a.tag.pattern"`

Although the grok patterns 100% match when i do 
```
<source>
 <parse>
  @type grok
  <grok>
  pattern (%{GREEDYDATA:message})
  </grok>
 </parse>
<source>
```

This is my configuraiton
```
<source>
  @type tail
  <parse>
    @type none
  </parse>
  path /var/log/syslog
  tag td.apache.access
</source>

<match td.apache.access>
  @type rewrite_tag_filter
  <rule>
    key     message
    pattern (.*?)192.168.1.1\D
    tag a.tag.pattern
  </rule>
</match>

<filter a.tag.pattern>
  @type parser
  key_name message
  # grok configuration
  <parse>
      @type grok
    <grok>
      pattern (%{GREEDYDATA:message})
    </grok>
</grok>
</parse>
.
.
.
```

Does the grok match only works under the Input plugin ?

**Comment by okkez** [comment]
> #0 no patterns matched tag="a.tag.pattern"

This means that `<filter a.tag.pattern>` cannot catch any events.
See also: [Life of a Fluentd event](https://docs.fluentd.org/v1.0/articles/life-of-a-fluentd-event), [Configuration File Syntax](https://docs.fluentd.org/v1.0/articles/config-file)

You can use the label feature for this purpose.

Could you post your question into [mailing list](https://groups.google.com/forum/?fromgroups#!forum/fluentd) or [community slack](http://slack.fluentd.org/)?
Thanks.

**Comment by ibrasec** [comment]
Thanks for yout reply okkez
i posted my question into the mailing list
