### ISSUE TITLE
filter_record_transformer - failed to expand `record[...]`

### ISSUE THREAD

**Issue by bappr** [fluent/fluentd#2090]
Check [CONTRIBUTING guideline](https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md) first and here is the list to help us investigate the problem.

- fluentd or td-agent version.
`fluentd-1.2.2`

- Environment information, e.g. OS.
`gcr.io/google-containers/fluentd-elasticsearch:v2.2.0`
`Debian GNU/Linux 9 (stretch)`

- Your configuration
```

<source>
  @type dummy
  tag dummy
  dummy {"log":"{\"message\":\"2018-08-01T03:53:28.155+0000 I NETWORK  [conn12] end connection 127.0.0.1:48480 (0 connections now open)\n\",\"id\":\"1234-5678-9\"}","kubernetes":{"container_name":"lanky-wolf-mongodb","labels":{"app":"mongodb","pod-template-hash":"1885764991","release":"lanky-wolf","type":"database"}}}
</source>

<filter **>
      @type record_transformer
      enable_ruby
      <record>
        pod_type ${record["kubernetes"]["labels"]["type"]}
      </record>
</filter>

<match **>
  @type stdout
</match>
```

- Your problem explanation. If you have an error logs, write it together.
```
2018-08-01 06:19:03 +0000 [warn]: #0 dump an error event: error_class=RuntimeError error="failed to expand `record[\"kubernetes\"][\"labels\"][\"type\"]` : error = undefined method `[]' for nil:NilClass" location="/var/lib/gems/2.3.0/gems/fluentd-1.2.2/lib/fluent/plugin/filter_record_transformer.rb:310:in `rescue in expand'" tag="fluent.info" time=2018-08-01 06:19:03.471886782 +0000 record={"worker"=>0, "message"=>"fluentd worker is now running worker=0"}
```

**Comment by cosmo0920** [comment]
Perhaps, you should specify concrete tag pattern in filter directive.
Fluentd itself generates `fluent.**` tagged events which does not contains kubernates released structured records.

And please send your question [mailing list](https://groups.google.com/forum/?fromgroups#!forum/fluentd) or [slack](https://slack.fluentd.org/) first.
