### ISSUE TITLE
how about out-file plugin if my disk is full??

### ISSUE THREAD

**Issue by vanke-renzhe** [fluent/fluentd#2091]
hi, i use copy in <match> section, to-file and to-es, 
if my disk is full, is it effect out-to-es?
my  log(file) is lost? Is it is discard?

**Comment by repeatedly** [comment]
> if my disk is full, is it effect out-to-es?

If your es plugin uses file buffer, it effects.

> my log(file) is lost? Is it is discard?

Not lost. But lots of error happens because fleuntd can't write new data into any files.

**Comment by repeatedly** [comment]
And this doesn't follow guideline. Closed.
