### ISSUE TITLE
Slow flushing in a collector server affecting the forwarder server

### ISSUE THREAD

**Issue by toniov** [fluent/fluentd#2092]
Hello, I have a forwarder server that get some data from another server, store logs in a file, and forward the data again; with the following config:

```
<source>
  type forward
  port 24224
</source>

<match **>
  type copy
  <store>
    type file
    path /var/log/td-agent/foo
    buffer_path /var/log/td-agent/buffer/foo
    buffer_chunk_limit 10g
  </store>
  <store>
    type forward
    flush_interval 30s
    buffer_type file
    buffer_path /var/log/td-agent/buffer/foo
    <server>
      host xx.xx.xx.xx
      port 24224
    </server>
  </store>
</match>
```

And a collector server that get the data forwarded above, and push it to Kinesis using [kinesis-plugin](https://github.com/awslabs/aws-fluent-plugin-kinesis):

```
<source>
  type forward
  port 24224
</source>

<match **>
  type kinesis_streams
  region xxx
  stream_name foo-stream
  aws_key_id xxx
  aws_sec_key xxx
  format my-format
  buffer_queue_limit 512
  flush_interval 30s
  buffer_chunk_limit 16m
  buffer_type file
  buffer_path /var/log/td-agent/buffer/bar
  num_threads 2
</match>
```

With this config It works without failing, but throughput to Kinesis is not enough in relation to the quantity of logs we get. When I try to increase throughput to Kinesis in the collector server, for example, adding more threads to `num_threads`, I get many of the following errors in the forwarder server:

```
[error]: suppressed same stacktrace
[warn]: emit transaction failed: error_class=Fluent::BufferQueueLimitError error="queue size exceeds limit" tag="**"
[warn]: suppressed same stacktrace
[error]: forward error error=#<Fluent::BufferQueueLimitError: queue size exceeds limit> error_class=Fluent::BufferQueueLimitError
```

And sometimes I get the following error in the collector server:

```
[warn]: buffer flush took longer time than slow_flush_log_threshold: plugin_id="object:3facf902f540"
elapsed_time=20.01857039 slow_flush_log_threshold=20.0
```

I can guess that increasing the throughput makes the flushing slower, but, why is the forwarder server affected by this? Is the collector server stopping the reception of chunks?

Thanks.

### System information

- Fluentd version: 
  - Forwarder server: 2.3.4 (fluentd 0.12.31)
  - Collector server: 2.3.5 (fluentd 0.12.35) (it was updated in order to be able to use Kinesis plugin)
- OS: CentOS 6.5

**Comment by kenhys** [comment]
@toniov
 Generally speaking, if you improve the throughput by increasing `num_threads`, you need to increase the buffer size, too.
I guess that this kind of improvements are also true for other servers such as forwarder because total amount of messages are incresed
as a result. Thus , `buffer_queue_limit` or `buffer_chunk_limit` and `flush_interval` need to be tuned appropriately.
