### ISSUE TITLE
How to retry unrecoverable errors

### ISSUE THREAD

**Issue by afshinm** [fluent/fluentd#2097]
- fluentd or td-agent version: 1.2.4
- Environment information, e.g. OS: Linux 4.9.0-7-amd64 1 SMP Debian 4.9.110-1 (2018-07-05) x86_64 GNU/Linux
- Your problem explanation. If you have an error logs, write it together.

There is an issue in the mysql plugin that raises NoMethodError if the connection is down. I've already sent the fix (https://github.com/tagomoris/fluent-plugin-mysql/pull/59) but I'd like to understand how can I change the behavior of retry for unrecoverable errors, such as NoMethodError, etc. 

My desired logic for retry is continue retrying unrecoverable errors for 10 times and then move the chunk to the backup folder.

**Comment by repeatedly** [comment]
> I'd like to understand how can I change the behavior of retry for unrecoverable errors, such as NoMethodError, etc.

Why do you want to retry unrecoverable error?
retry is never succeeded for such errors.

**Comment by afshinm** [comment]
Yeah so one possible problem could be an error in the plugin itself, such as this mysql issue that I've mentioned. I understand that it must be fixed in the plugin but I was wondering if it's possible to change this logic at all.

**Comment by ganmacs** [comment]
it's a stale issue. I'm closing. if you have any problem, updating fluentd might help it.
