### ISSUE TITLE
Monitoring : The metrics of Fluentd Fowarder in Prometheus

### ISSUE THREAD

**Issue by voltige** [fluent/fluentd#2100]
Hello,
Here is my configuration:  
Fluentd Fowarder(various instances)  -->  Fluentd Aggregator  <--  Prometheus

My goal is to send the metrics of the Fluentd Fowarder and Aggregator in Prometheus.

The official documentation (well written) explains how to setup Fluentd in way to retrieve its metrics in Prometheus.

However, my case is more complexe. In fact, I can send the metrics to the Fluentd Aggregator and verify that the data are well added in Prometheus. But, I can't display the different hostname or tag. Only the hostname/tag of the Fluent Aggregator appears. 

Is it possible in this kind of architecture, to visualize/identify specifically the metrics of Fluentd Fowarder in Prometheus?

For information, it's impossible to me  in my use case to connect the Fluent Fowarder to Prometheus directly. 

Best regards
Kodzo

**Comment by okkez** [comment]
Could you show me your current configuration?

Maybe you can use [fluent-plugin-rewrite-tag-filter](https://github.com/fluent/fluent-plugin-rewrite-tag-filter) in your Fluentd Aggregator instance.
