### ISSUE TITLE
How to add clickhouse db plugin

### ISSUE THREAD

**Issue by mohit5540** [fluent/fluentd#2102]
Hello All

Can anyone suggest How can we add clickhouse db plugin with td-agent. I checked this : [https://rubygems.org/gems/fluent-plugin-clickhouse/versions/0.0.1](https://rubygems.org/gems/fluent-plugin-clickhouse/versions/0.0.1)
But can anyone explain how to setup conf file after downloading this.

Beat Regards

**Comment by okkez** [comment]
This issue does not follow the guideline. So, closed.

And please send your question [mailing list](https://groups.google.com/forum/?fromgroups#!forum/fluentd) or [slack](https://slack.fluentd.org/) first.
