### ISSUE TITLE
Add option to send bad chunks to /dev/null or disable backups at all

### ISSUE THREAD

**Issue by monotek** [fluent/fluentd#2112]
- fluentd version: 1.2.4
- Environment information, e.g. OS: Docker / Kubernetes / GKE

We're using Fluentd inside a docker container to collect all Docker logs in our legacy environment and also inside Kubernetes. After updating to 1.2.0 container crashed after a while as /tmp/fluentd used all diskspace inside the container, which was limited to 3 gb. 

Via env var FLUENT_BACKUP_DIR we could modify the directory but still the only way to get around the problem is to mount the used directory to the host, and delete the files there from time to time.

Imho an option to send backups to /dev/null or to disable creation of this backups is missing currently.

Would be nice it could be added.

**Comment by repeatedly** [comment]
> Imho an option to send backups to /dev/null or to disable creation of this backups is missing currently.

Adding this option is not hard but you don't have similar problem with v0.12?
Did you ignore problematic chunks with v0.12?

**Comment by monotek** [comment]
Yes, problematic chunks were ignored.
We even don't were aware of having them...

**Comment by repeatedly** [comment]
Patch is here: https://github.com/fluent/fluentd/pull/2117

**Comment by monotek** [comment]
Thanks! :-)
