### ISSUE TITLE
Question about wildcard path log file with log rotation

### ISSUE THREAD

**Issue by qingling128** [fluent/fluentd#2114]
From https://docs.fluentd.org/v1.0/articles/in_tail#path:
"You should not use '*' with log rotation because it may cause the log duplication. In such case, you should separate in_tail plugin configuration."

From https://github.com/fluent/fluentd/blob/27e84796ebdd7f4f74c584c0cab244c312536732/lib/fluent/plugin/in_tail.rb#L249:
```
    # in_tail with '*' path doesn't check rotation file equality at refresh phase.
    # So you should not use '*' path when your logs will be rotated by another tool.
    # It will cause log duplication after updated watch files.
    # In such case, you should separate log directory and specify two paths in path parameter.
    # e.g. path /path/to/dir/*,/path/to/rotated_logs/target_file
```

Does this apply to configurations like `path /path/*.log`? Or is this only about `path /path/*`?

We have configurations like https://github.com/GoogleCloudPlatform/fluentd-catch-all-config/blob/master/configs/config.d/solr.conf. We are trying to figure out if this pattern would cause log duplication.

Thanks in advance!

**Comment by repeatedly** [comment]
> Does this apply to configurations like path /path/*.log?

If rotated file name doesn't have `.log` ext, the problem doesn't happen.

NG: app.log -> app.1.log
OK: app.log -> app.log.1

**Comment by qingling128** [comment]
Good to know. Thanks for the answer! Closing this.

**Comment by okapies** [comment]
Hi, @repeatedly. I have a similar question around the wildcard path handling in in_tail plugin.

I plan to collect logs by fluentd from Gunicorn and my Django application in Python. But there is no safe way to log into a single file in [some multiprocessing setups](https://stackoverflow.com/questions/47968861/does-python-logging-support-multiprocessing/48019901#48019901), so it appears each worker process run by Gunicorn needs to manage its own log files like _app-{pid}.log_, which are rotated by the logger implementation itself or other tools like `logrotate`.

In this setup, does the configuration like `path /path/app-*.log,/path/app-*.log.*` also work or not?

```
app-1234.log
app-1234.log.2020-03-01
app-1234.log.2020-03-02
app-5678.log
app-5678.log.2020-03-01
app-5678.log.2020-03-02
```

**Comment by repeatedly** [comment]
> path /path/app-*.log,/path/app-*.log.*

Why do you need latter pattern? It reads same log after log rotate happens.

**Comment by okapies** [comment]
Thanks for the response. I'm worried about some corner cases like the below:

1. fluentd stops working for some reason (manual maintenance, periodic restart, bugs, OOM killer, etc...)
2. Our application writes its log to the file
3. logrotate renames the log file and send a signal to the application
4. Our application starts writing its log to the new file
5. fluentd comes back to normal

Does fluentd also handle the logs written by 2 even if we don't have the setting for the rotated files?
