### ISSUE TITLE
[warn]: Could not push logs to loom systems, attempt=9 max_attempts=-1 wait=30s error=Connection refused - connect(2)

### ISSUE THREAD

**Issue by jain108shubhamtbt** [fluent/fluentd#2115]
Why is this coming ?
please help me .

**Comment by cosmo0920** [comment]
Could you fill the issue template?

**Comment by jain108shubhamtbt** [comment]
where to fill issue template ?

**Comment by jain108shubhamtbt** [comment]
please share me issue template, i am new to use fluentd

**Comment by jain108shubhamtbt** [comment]
please help me soon

**Comment by jain108shubhamtbt** [comment]
2018-08-28 09:59:48 -0400 [info]: following tail of /var/lib/docker/containers/ea315baa20ef05928ac737329f92b0dd475fe27f4c5c440b63888da73f975301/ea315baa20ef05928ac737329f92b0dd475fe27f4c5c440b63888da73f975301-json.log
--
  | 2018-08-28 10:00:49 -0400 [warn]: Could not push logs to loomsystems, attempt=1 max_attempts=-1 wait=0s error=Connection refused - connect(2)
  | 2018-08-28 10:00:49 -0400 [warn]: Could not push logs to loomsystems, attempt=2 max_attempts=-1 wait=1s error=Connection refused - connect(2)
  | 2018-08-28 10:00:50 -0400 [warn]: Could not push logs to loomsystems, attempt=3 max_attempts=-1 wait=4s error=Connection refused - connect(2)
  | 2018-08-28 10:00:54 -0400 [warn]: Could not push logs to loomsystems, attempt=4 max_attempts=-1 wait=9s error=Connection refused - connect(2)
  | 2018-08-28 10:01:03 -0400 [warn]: Could not push logs to loomsystems, attempt=5 max_attempts=-1 wait=16s error=Connection refused - connect(2)

**Comment by jain108shubhamtbt** [comment]
critical issuse

please help me .

**Comment by repeatedly** [comment]
> Connection refused - connect(2)

This error is not fluentd problem.
This is general error for networking setting issue.
So you need to check your network setting.

**Comment by repeatedly** [comment]
BTW, this issue doesn't follow contribution guide. Closed.
if the problem is fluentd core, please reopen the issue.
