### ISSUE TITLE
fluentd is not sending path, hostname when forwarder logs..........................?

### ISSUE THREAD

**Issue by jain108shubhamtbt** [fluent/fluentd#2120]
{
        "_index" : "fluentd-2014.10.18",
        "_type" : "fluentd",
        "_id" : "id",
        "_score" : 3.0,
        "_source" : {
          "message" : "some log message",
          "@timestamp" : "time"
        }
}

I mention "path" in input config, then why fluentd is not sending path with above json data.

Need : data like that format

{
        "_index" : "fluentd-2014.10.18",
        "_type" : "fluentd",
        "_id" : "id",
        "_score" : 3.0,
        "_source" : {
          "message" : "some log message",
          "path" : "path" 
          "@timestamp" : "time"
          "hostname" : "hostname"
        }
}

**Comment by jain108shubhamtbt** [comment]
please help me .

**Comment by jain108shubhamtbt** [comment]
i am sorry, by mistake click on close ? 
Please help me .

**Comment by capt-abhi** [comment]
Hi Shubham,
Share your td- agent configuration and sample log which you are trying to
move/parse by td-agent

**Comment by jain108shubhamtbt** [comment]
Hi Capt-abhi,

This is configuration which am i using : 


<source>
    type tail
    path /tmp/*/*-json.log
    pos_file /tmp/fluentd-docker.pos
    path_key source
    tag docker.*
    format json
  </source>
  <match **>
    @type elasticsearch
    logstash_format false
    index_name indexname
    host ip
    port port
  </match>

**Comment by cosmo0920** [comment]
This is not Fluentd core issue.
It seems that fluent-plugin-elasticsearch issue. Closed.
