### ISSUE TITLE
Fluentd https input plugin support

### ISSUE THREAD

**Issue by mnivedithaa** [fluent/fluentd#2124]
Fluentd http input plugin doesn't support https
Our requirement is an input plugin that supports HTTPS and TLS termination in addition to existing http plugin features like batching and compression

**Comment by alepuccetti** [comment]
This will be really nice to simplify logging capture from external sources.

**Comment by manojpardeshi** [comment]
+1

**Comment by cosmo0920** [comment]
@repeatedly @ganmacs Can we close this issue?
Because #2395 have already merged and Fluentd v1.5.0 had been released.

**Comment by repeatedly** [comment]
Ah, auto close by merge didn't work.
