### ISSUE TITLE
@timestamp is not getting when we send logs using bulk in fluentd ?

### ISSUE THREAD

**Issue by jain108shubhamtbt** [fluent/fluentd#2126]
Getting : 

{
        "_index" : "index",
        "_type" : "fluentd",
        "_id" : "id",
        "_score" : 1.0,
        "_source" : {
          "message" : "{\"log\":\"2018-09-13 05:24:56 -0400 [info]: following tail of /var/lib/json.log\\n\",\"stream\":\"stdout\",\"time\":\"2018-09-13T09:24:56.332149103Z\"}",
          }
}

Need : 

{
        "_index" : "index",
        "_type" : "fluentd",
       "@timestamp" : "timestamp value",
        "_id" : "id",
        "_score" : 1.0,
        "_source" : {
          "message" : "{\"log\":\"2018-09-13 05:24:56 -0400 [info]: following tail of /var/lib/json.log\\n\",\"stream\":\"stdout\",\"time\":\"2018-09-13T09:24:56.332149103Z\"}",
          }
}

**Comment by jain108shubhamtbt** [comment]
Please help me .

**Comment by jain108shubhamtbt** [comment]
can some one help Asap ?

**Comment by jain108shubhamtbt** [comment]
it is very critical .

**Comment by capt-abhi** [comment]
Hi Shubham,
Please share your  td-agent.conf file.
I guess you are either not defining time_format and time_key in the conf.

**Comment by capt-abhi** [comment]
Hi shubham in the source tag, where you are defining the source of your data add the following line-

time_key time_local
time_format %Y%m%d%h%m%s

**Comment by cosmo0920** [comment]
This is also es plugin setting not for Fluentd core. Closed.
