### ISSUE TITLE
Is there  a method to replace the placeholder in Buffer Path and  symlink_path？

### ISSUE THREAD

**Issue by atm1992** [fluent/fluentd#2127]
Check [CONTRIBUTING guideline](https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md) first and here is the list to help us investigate the problem.

- fluentd version, fluentd-1.2.2
- Is there  a method to replace the placeholder in Buffer Path and  symlink_path？I have seen the https://docs.fluentd.org/v1.0/articles/out_file#i-can-see-files-but-placeholders-are-not-replaced,-why

**Comment by repeatedly** [comment]
> Is there a method to replace the placeholder in Buffer Path and symlink_path？

Does it mean you want to expand placeholder for temporary buffers?
If so, currently no way.
