### ISSUE TITLE
Td-agent: Connect failed for test event

### ISSUE THREAD

**Issue by elyoncyber** [fluent/fluentd#2133]
Hello,

Trying to finish installing td-agent using the following guide:
https://docs.fluentd.org/v1.0/articles/install-by-msi

Presently on the part with send a test event to the td process. Receiving the following error:

![image](https://user-images.githubusercontent.com/34746882/45772951-aba3c180-bc0e-11e8-9a9e-e9e1525ae231.png)

Firewall has been ruled-out as the issue.

**Comment by cosmo0920** [comment]
Fill the isssue template, please.

**Comment by elyoncyber** [comment]
Hi @cosmo0920 , not sure what you mean?

**Comment by cosmo0920** [comment]
@elyoncyber 

```
Check [CONTRIBUTING guideline](https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md) first and here is the list to help us investigate the problem.

- fluentd or td-agent version.
- Environment information, e.g. OS.
- Your configuration
- Your problem explanation. If you have an error logs, write it together.
```
