### ISSUE TITLE
Unable to start Td-agent with secure-forwarding help required. 

### ISSUE THREAD

**Issue by malingaraj** [fluent/fluentd#2143]
Check [CONTRIBUTING guideline](https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md) first and here is the list to help us investigate the problem.

- fluentd or td-agent version. = td-agent 3.2
- Environment information, e.g. OS. = Rhel7
- Your configuration = I installed td-agent with secure forwarding 
- Your problem explanation. If you have an error logs, write it together. below is the error
+++++++++++++++++++++++++++++++++++++++++
Agent installed = td-agent-3.2.0-0.el7.x86_64
OS = RHEl 7.4
I installed 2 gems required = fluent-plugin-grok-parser-2.3.0.gem & fluent-plugin-secure-forward-0.4.5.gem 
+++++++++++++++++++++++++++++++++++++++++

* Agent is starting without secure forwarding configuration in the td-agent.conf.
* Issue is when, I change the configuration to secure forwarding under td-agent.conf agent not starting. 

++++++++++++++++++++++++++++++++++++++++++

error:-

When i start :- 
Job for td-agent.service failed because the control process exited with error code. See "systemctl status td-agent.service" and "journalctl -xe" for details.
                                                        
td-agent.log says :- 

2018-10-04 12:54:41 -0500 [info]: parsing config file is succeeded path="/etc/td-agent/td-agent.conf"
2018-10-04 12:54:41 -0500 [info]: parsing config file is succeeded path="/etc/td-agent/td-agent.conf"
2018-10-04 12:54:42 -0500 [info]: parsing config file is succeeded path="/etc/td-agent/td-agent.conf"

journalctl -xe says = I changed the server name for security reason to  Server.domainname in this issue. 

Oct 04 12:54:42 ### Server.domainname ###[20241]: from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/plugin.rb:14
Oct 04 12:54:42 ### Server.domainname ###[20241]: from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/plugin.rb:10
Oct 04 12:54:42 ### Server.domainname ###[20241]: from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/agent.rb:128
Oct 04 12:54:42 ### Server.domainname ###[20241]: from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/agent.rb:72:
Oct 04 12:54:42 ### Server.domainname ###[20241]: from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/agent.rb:64:
Oct 04 12:54:42 ### Server.domainname ###[20241]: from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/agent.rb:64:
Oct 04 12:54:42 ### Server.domainname ###[20241]: from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/root_agent.r
Oct 04 12:54:42 ### Server.domainname ###[20241]: from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/engine.rb:13
Oct 04 12:54:42 ### Server.domainname ###[20241]: from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/engine.rb:96
Oct 04 12:54:42 ### Server.domainname ###[20241]: from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/supervisor.r
Oct 04 12:54:42 ### Server.domainname ###[20241]: from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/supervisor.r
Oct 04 12:54:42 ### Server.domainname ###[20241]: from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/supervisor.r
Oct 04 12:54:42 ### Server.domainname ###[20241]: from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/supervisor.r
Oct 04 12:54:42 ### Server.domainname ###[20241]: from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/command/flue
Oct 04 12:54:42 ### Server.domainname ###[20241]: from /opt/td-agent/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:5
Oct 04 12:54:42 ### Server.domainname ###[20241]: from /opt/td-agent/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:5
Oct 04 12:54:42 ### Server.domainname ###[20241]: from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/bin/fluentd:8:in `<top
Oct 04 12:54:42 ### Server.domainname ###[20241]: from /opt/td-agent/embedded/bin/fluentd:23:in `load'
Oct 04 12:54:42 ### Server.domainname ###[20241]: from /opt/td-agent/embedded/bin/fluentd:23:in `<main>'
Oct 04 12:54:42 ### Server.domainname ### systemd[1]: td-agent.service: control process exited, code=exited status=1
Oct 04 12:54:42 ### Server.domainname ### systemd[1]: Failed to start td-agent: Fluentd based data collector for Treasure Data.
-- Subject: Unit td-agent.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit td-agent.service has failed.
--
-- The result is failed.
Oct 04 12:54:42 ### Server.domainname ### systemd[1]: Unit td-agent.service entered failed state.
Oct 04 12:54:42 ### Server.domainname ### systemd[1]: td-agent.service failed.
Oct 04 12:54:42 ### Server.domainname ### systemd[1]: td-agent.service holdoff time over, scheduling restart.
Oct 04 12:54:42 ### Server.domainname ### systemd[1]: start request repeated too quickly for td-agent.service
Oct 04 12:54:42 ### Server.domainname ### systemd[1]: Failed to start td-agent: Fluentd based data collector for Treasure Data.
-- Subject: Unit td-agent.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit td-agent.service has failed.
--
-- The result is failed.
Oct 04 12:54:42 ### Server.domainname ### systemd[1]: Unit td-agent.service entered failed state.
Oct 04 12:54:42 ### Server.domainname ### systemd[1]: td-agent.service failed.

Any idea why? and no other errors

**Comment by malingaraj** [comment]
And, When I run td-agent --dry-run it shows below.


2018-10-04 14:46:16 -0500 [info]: parsing config file is succeeded path="/etc/td-agent/td-agent.conf"
2018-10-04 14:46:16 -0500 [info]: starting fluentd-1.2.2 as dry run mode ruby="2.4.4"
/opt/td-agent/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- resolve/hostname (LoadError)
        from /opt/td-agent/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-secure-forward-0.4.5/lib/fluent/plugin/out_secure_forward.rb:8:in `<top (required)>'
        from /opt/td-agent/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /opt/td-agent/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/registry.rb:102:in `block in search'
        from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/registry.rb:99:in `each'
        from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/registry.rb:99:in `search'
        from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/registry.rb:44:in `lookup'
        from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/plugin.rb:146:in `new_impl'
        from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/plugin.rb:104:in `new_output'
        from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/agent.rb:128:in `add_match'
        from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/agent.rb:72:in `block in configure'
        from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/agent.rb:64:in `each'
        from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/agent.rb:64:in `configure'
        from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/root_agent.rb:112:in `configure'
        from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/engine.rb:131:in `configure'
        from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/engine.rb:96:in `run_configure'
        from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/supervisor.rb:795:in `run_configure'
        from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/supervisor.rb:579:in `dry_run'
        from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/supervisor.rb:566:in `dry_run_cmd'
        from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/supervisor.rb:501:in `run_supervisor'
        from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/command/fluentd.rb:310:in `<top (required)>'
        from /opt/td-agent/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /opt/td-agent/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/bin/fluentd:8:in `<top (required)>'
        from /opt/td-agent/embedded/bin/fluentd:23:in `load'
        from /opt/td-agent/embedded/bin/fluentd:23:in `<top (required)>'
        from /sbin/td-agent:7:in `load'
        from /sbin/td-agent:7:in `<main>'
[root@pgawdcekm0101 thrinath.gubba]# nslookup pgawdccosig01.sl.bluecloud.ibm.com

**Comment by repeatedly** [comment]
https://github.com/tagomoris/fluent-plugin-secure-forward/blob/master/fluent-plugin-secure-forward.gemspec#L18

secure-forward requires `resolve-hostname` gem. Could you check this gem is installed or not.

**Comment by malingaraj** [comment]
Thank You after installed it worked. thanks much. We can close this.
