### ISSUE TITLE
feature request: Enabling fluentd to utilised configured number of CPU cores without multi-process plugin

### ISSUE THREAD

**Issue by ashishtilara** [fluent/fluentd#2150]
- fluentd or td-agent version.
     - fluent/fluentd:v1.2.5
- Environment information, e.g. OS.
     - docker image
- Your configuration
     - one input from 10000+ devices, 6 outputs to different bigquery tables
- Your problem explanation. If you have an error logs, write it together.

currently, the docker container only utilises one CPU core, is it possible to introduce the configuration to make fluentd to utilise multiple cores without using multiprocess plugin?

The requirement for this varies client to client, and its hard to split the traffic from device because client networking restrictions and we hardly get one port to push data out to an instance.

Appreciate any feedback.

**Comment by repeatedly** [comment]
Try built-in multiprocess feature

https://www.fluentd.org/blog/fluentd-v0.14.12-has-been-released
https://www.fluentd.org/blog/fluentd-v0.14.15-has-been-released

**Comment by repeatedly** [comment]
BTW, we forgot to add the article about multiprocess feature to fluentd-docs. Will add it.

**Comment by ashishtilara** [comment]
Thank you @repeatedly deployed the changes to prod and works as I wanted it too, now I need to figureout why all those workers using 100% of CPU all the time.. will keep you posted. 👍 

Really appreciate your help.
