### ISSUE TITLE
td-agent.service lacks both ExecStart= and ExecStop= setting. Refusing.

### ISSUE THREAD

**Issue by cuiliang5** [fluent/fluentd#2152]
[root@localhost ~]# systemctl status td-agent.service
● td-agent.service
   Loaded: error (Reason: Invalid argument)
   Active: failed (Result: exit-code) since Fri 2018-10-19 17:24:04 CST; 3 days ago
 Main PID: 9234 (code=exited, status=0/SUCCESS)

Oct 22 14:48:01 localhost.localdomain systemd[1]: [/usr/lib/systemd/system/td-agent.service:2] Assignment outside of section. Ignoring.
Oct 22 14:48:01 localhost.localdomain systemd[1]: [/usr/lib/systemd/system/td-agent.service:3] Assignment outside of section. Ignoring.
Oct 22 14:48:01 localhost.localdomain systemd[1]: [/usr/lib/systemd/system/td-agent.service:4] Assignment outside of section. Ignoring.
Oct 22 14:48:01 localhost.localdomain systemd[1]: td-agent.service lacks both ExecStart= and ExecStop= setting. Refusing.
Oct 22 15:00:46 localhost.localdomain systemd[1]: [/usr/lib/systemd/system/td-agent.service:2] Assignment outside of section. Ignoring.
Oct 22 15:00:46 localhost.localdomain systemd[1]: td-agent.service lacks both ExecStart= and ExecStop= setting. Refusing.
Oct 22 17:27:13 localhost.localdomain systemd[1]: [/usr/lib/systemd/system/td-agent.service:2] Assignment outside of section. Ignoring.
Oct 22 17:27:13 localhost.localdomain systemd[1]: td-agent.service lacks both ExecStart= and ExecStop= setting. Refusing.
Oct 22 17:28:12 localhost.localdomain systemd[1]: [/usr/lib/systemd/system/td-agent.service:2] Assignment outside of section. Ignoring.
Oct 22 17:28:12 localhost.localdomain systemd[1]: td-agent.service lacks both ExecStart= and ExecStop= setting. Refusing.
Warning: td-agent.service changed on disk. Run 'systemctl daemon-reload' to reload units.

**Comment by repeatedly** [comment]
This is not fluentd issue, closed.
