### ISSUE TITLE
Greatly increased file buffer write i/o activity moving from 0.12.x to 1.2.x

### ISSUE THREAD

**Issue by mffiedler** [fluent/fluentd#2153]
- fluentd 1.2.6 file buffer behavior vs. fluentd 0.12.43
- RHEL 7.5.x, fluentd configured to read Docker json-file container logs
```aconf
      <buffer>
        @type file
        path '/var/lib/fluentd/buffer-output-es-config'
        flush_interval 1s
        flush_thread_count 8
        flush_at_shutdown 'false'
        retry_max_interval 300
        retry_forever true
        queued_chunks_limit_size 32
        chunk_limit_size 8m
        overflow_action block
      </buffer>
```

- Identical workload for both fluentd versions
- constant 1000 1KB messages per second per fluentd to be forwarded to elasticsearch.   
- 1.2.6 uses much less cpu than 0.12.43 (50% as much) 
- 1.2.6 has much higher write I/O activity to the file buffer directory (verified with sysdig).   
- eventually, 1.2.6 is throttled on iowait when higher message rates (2000 1KB messages/sec) are attempted - the nvme is provisioned for 3000 IOPS
- attached are graphs with a) write IOPS activity comparison from iostat and b) block device write activity comparison from vmstat.   
- Both fluentd systems are on identical AWS m5.xlarge instances with nvme storage for /var/lib/fluentd.

At 1000 IOPS for a workload of 1000 messages/second it seems 1.2.6 is performing a unique IO for each message.   I've tried adjusting the flush_interval, but still see consistent 1000 write iops for this workload.

![block_dev_write](https://user-images.githubusercontent.com/1133529/47385311-a1765680-d6d7-11e8-86f2-e756435bd4e7.png)
![write_iops](https://user-images.githubusercontent.com/1133529/47385312-a1765680-d6d7-11e8-8f13-381099f817f0.png)

Any thoughts on tuning this to lower the disk activity?  Other info that would help?

**Comment by repeatedly** [comment]
fluentd v1 has metadata for buffer chunks so the number of IO operation is increased.
fluentd buffers handles these operations per event stream.
Do you send 1 event x 1000 / sec or 1000 msg x 1 / sec?

**Comment by richm** [comment]
In this test, input is coming from in_tail for kubernetes/docker json-file logs: https://github.com/openshift/origin-aggregated-logging/blob/master/fluentd/lib/generate_throttle_configs/lib/generate_throttle_configs.rb#L183
```
<source>
  @type tail
  path /var/log/containers/*.log
  tag kubernetes.*
  ...
</source>
```
so things are tagged like `kubernetes.var.log.containers.$pod-name_$namespace-name_$container-name-$containerID.log` as they go through the filtering/processing part of the pipeline

but - just before output (and buffering?  is this where buffering happens?) we retag everything to have a single tag: https://github.com/openshift/origin-aggregated-logging/blob/master/fluentd/configs.d/filter-post-z-retag-one.conf#L7
```
<match **>
  @type rewrite_tag_filter
  @label @OUTPUT
  <rule>
    key message
    pattern .+
    tag output_tag
  </rule>
  <rule>
    key message
    pattern .+
    tag output_tag
    invert true
  </rule>
</match>
```
so by the time the records get to the elasticsearch output (and the buffering?) they should all have the same tag.

Not sure if this answers your question - I guess I don't understand what you mean by "Do you send 1 event x 1000 / sec or 1000 msg x 1 / sec"

**Comment by repeatedly** [comment]
fluent-plugin-rewrite-tag-filter splits batched event stream, e.g. MultiEventStream / MessagePackEventStream , into one event stream so IO cost may increase:

https://github.com/fluent/fluent-plugin-rewrite-tag-filter/blob/2c017db8a80dabdba32fa1718d72ab507f5e5769/lib/fluent/plugin/out_rewrite_tag_filter.rb#L73

So several approaches to decrease IO:

- add re-emit batch event stream mode to rewrite-tag-filter. Create "tag -> event stream" map before each emit.
- use `route` or other tag handling plugin. rewrite-tag-filter is useful for lots of dynamic patterns. rewrite-tag-filter doesn't focus on your fixed simple pattern.

**Comment by nhosoi** [comment]
Thank you for your comments, @repeatedly.

> fluent-plugin-rewrite-tag-filter splits batched event stream, e.g. MultiEventStream / MessagePackEventStream , into one event stream so IO cost may increase:

One of the reasons why we replaced the various tags with a single tag "output_tag" using the rewrite-tag-filter plugin was to avoid switching a buffer chunk to the next one by the tag change.  I.e., if logs with tagA are coming, they are buffered in the file buffer /PATH/TO/FILEBUFFER.tagA.ID.log.  Then, a log with tagB comes in, the buffer is switched to /PATH/TO/FILEBUFFER.tagB.ID.log.  We observed that it increased the number of buffer files and it reduced the advantage of bulk write to the elasticsearch.

If we follow your second suggestion, do we lose the benefit?

> use route or other tag handling plugin. rewrite-tag-filter is useful for lots of dynamic patterns. rewrite-tag-filter doesn't focus on your fixed simple pattern: https://docs.fluentd.org/v1.0/articles/routing-examples#re-route-event-by-tag

If the answer is yes, your first suggestion - modifying the rewrite-tag-filter plugin would be the only one solution?

> add re-emit batch event stream mode to rewrite-tag-filter. Create "tag -> event stream" map before each emit.

**Comment by repeatedly** [comment]
v1.7 fixes this problem by 2 approaches:
https://github.com/fluent/fluentd/pull/2551
https://github.com/fluent/fluentd/pull/2579

**Comment by richm** [comment]
@repeatedly When would someone use buffer type `file` vs. `file_single`?

**Comment by repeatedly** [comment]
By #2551, `file` also reduces the IO operation. We check `iostat` to avoid lots of IO tps.
So keep to use `file` should be no problem.
