### ISSUE TITLE
Problem with fluent plugin ->  fluent-plugin-prometheus (1.0.1). Allow only 5 Connections.

### ISSUE THREAD

**Issue by sanjuicgithub** [fluent/fluentd#2156]
Hello, 

There seems to be bug in this plugin (fluent-plugin-prometheus (1.0.1)) .  Details are provided below. Kindly analyse and help to fix this problem.

- td-agent version : td-agent-3.1.1-0
- Environment information : Red Hat Enterprise Linux 7.3

- Our configuration
--------------------
### PROMETHEUS-PLUGIN CONFIG on TD-AGENT
<source>
  @type prometheus
  bind 0.0.0.0
  port 9999
  metrics_path /metrics
</source>
<source>
  @type prometheus_output_monitor
  interval 10
</source>

--------------------
- Problem is that , It allows only five TCP connects.  As soon as 6th instances connects on port 9999, it start misbehaving in just a few minutes and many connections goes in 'CLOSE_WAIT' state and then it stucks completely, after some times when the CLOSE_WAIT connections grows, it stops serving all the request for /metrics.       Note that , our other port (24224) on which logs are streaming has no issue at all and it's handling huge number of requests without any issue.   The problem is only with the port (9999) which is used by Prometheus to scrape the metrics. 

Our current setup : 
We have 7 prometheus instances which are  scraping the metrics from the td-agent server.   

Tests done so far :  
We have tested by allowing 5 or less number of connections and they are very much stable.

**Comment by sanjuicgithub** [comment]
Hello, 

May I kindly request somebody to look at this issue. It's bit urgent for us.

**Comment by repeatedly** [comment]
This is not fluentd core issue, so closed.

BTW, the problem is input plugin set 5 max connections in its setup.

https://github.com/fluent/fluent-plugin-prometheus/blob/76865e40905cda3f1139da9756760310bb55d053/lib/fluent/plugin/in_prometheus.rb#L54
