### ISSUE TITLE
Differences between fluentd buffer_queue_limit, queue_limit_length and queued_chunks_limit_size

### ISSUE THREAD

**Issue by Misterhex** [fluent/fluentd#2157]
My understanding is that `buffer_queue_limit` and `queue_limit_length` are the same. These parameters determine how many chunks will be maintained until its full which trigger `overflow_action`?

Is `queued_chunks_limit_size` the same thing? 

Thanks for the help!

**Comment by mattayes** [comment]
@Misterhex Did you find an answer?

**Comment by sharon-vendrov** [comment]
I was wondering the same, never found an answer

**Comment by solacens** [comment]
I guess you will never have the answer.

**Comment by llrrbaba** [comment]
wondering
