### ISSUE TITLE
Unable to forward logs from one fluentd server to another fluentd server.

### ISSUE THREAD

**Issue by ReenaAcharya** [fluent/fluentd#2160]
Hi,

I have configured secure forward using this link "http://docs.fluentd.org/v0.12/articles/forwarding-over-ssl".  I have two servers with fluentd installed (td-agent).  However I am not able to view the logs in other fluentd server.

Let me know if more information\details are required.

Any suggestion here would be very helpful.

Thanks,
Reena

**Comment by repeatedly** [comment]
Don't use github issue for the question. See contribution guideline: https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md#got-a-question-or-problem
