### ISSUE TITLE
Time zone not right, always rotate the out_file at 08:00AM  in the morning, not at 00:10AM

### ISSUE THREAD

**Issue by David-Gee** [fluent/fluentd#2161]
Check [CONTRIBUTING guideline](https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md) first and here is the list to help us investigate the problem.

- 'fluentd' version '1.2.2'
- CentOS release 6.10 (Final)
- My configuration
```
<source>
  @type forward
  port 60000
</source>
<match lcmcn_login_pay.**>
    @type copy
    <store>
      @type file
      path /data/from_infra/lcmcn/from_log/%Y%m%d/lcmcn-login-pay_%Y%m%d
      append true
      compress gzip
      <format>
	@type json
      </format>
      <buffer>
        timekey 1d
        timekey_wait 10m
      </buffer>
    </store>
    <store>
	@type kafka2
	brokers 10.96.29.136:19092,10.96.29.137:19092,10.96.29.138:19092
	default_topic new_lcm_realkpi
	<format>
	  @type json
	</format>
	<buffer topic>
	  flush_interval 1s
	</buffer>
    </store>
</match>
```
==============================================
- My Problem:
The out_file always rotate at 08:00AM not 0:00,no matter I add 
<buffer>
        timekey 1d
        timekey_wait 10m
</buffer>
or just delete buffer section(keep the buffer as out_file default setting)

Could you please help? Thanks in advance

**Comment by okkez** [comment]
Upgrade Fluentd to v1.2.4 or later.
See https://github.com/fluent/fluentd/blob/master/CHANGELOG.md#release-v124---20180801 for more details.

**Comment by repeatedly** [comment]
If this problem happens with latest version, please reopen the issue.

**Comment by David-Gee** [comment]
Hi  Masahiro San & okkez,
I checked this morning, after upgrading to v1.2.6, the problem is solved.
Thanks a lot ~~~
