### ISSUE TITLE
fluentd doesnt forward data to a kinesis stream hosted in a different aws account

### ISSUE THREAD

**Issue by manjunathramesh** [fluent/fluentd#2163]
Check [CONTRIBUTING guideline](https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md) first and here is the list to help us investigate the problem.

- fluentd or td-agent version.
- Environment information, e.g. OS.
- Your configuration
- Your problem explanation. If you have an error logs, write it together.
im using fluentd version 1.2.6 and the below-mentioned gems  

 gem 'fluent-plugin-detect-exceptions' version '0.0.11'
 gem 'fluent-plugin-kinesis' version '2.1.1'
 gem 'fluent-plugin-kubernetes_metadata_filter' version '2.1.4'
gem 'fluent-plugin-logzio' version '0.0.18'
gem 'fluent-plugin-record-modifier' version '1.1.0'
 gem 'fluent-plugin-rewrite-tag-filter' version '2.1.0'
gem 'fluent-plugin-systemd' version '1.0.1'
 gem 'fluentd' version '1.2.6

when i deploy the fluentd.yaml the pods comes up fine but it keeps looking at the same account for the kinesis stream instead of forwarding the data to a kinesis stream hosted in a different aws account. I have mentioned the role arn  in fluentd.conf file but still it doesnt work. 

below is conf file . 

# AUTOMATICALLY GENERATED
# DO NOT EDIT THIS FILE DIRECTLY, USE /templates/conf/fluent.conf.erb

@include systemd.conf
@include kubernetes.conf

<match **>
  @type kinesis_streams
  @id out_kinesis_streams
  region "#{ENV['FLUENT_KINESIS_STREAMS_REGION'] || 'us-east-1' }"
  stream_name "#{ENV['FLUENT_KINESIS_STREAMS_STREAM_NAME']}"
  aws_key_id "#{ENV['AWS_KEY_ID']}"
  aws_sec_key "#{ENV['AWS_SEC_KEY']}"
  include_time_key "#{ENV['FLUENT_KINESIS_STREAMS_INCLUDE_TIME_KEY'] || false}"
 <assume_role_credentials>
    role_arn      "#{ENV['ROLE_ARN']}"
    role_session_name FLUENTDTESTING
  </assume_role_credentials>
 <buffer>
    flush_interval 1
    chunk_limit_size 1m
    flush_thread_interval 0.1
    flush_thread_burst_interval 0.01
    flush_thread_count 15
  </buffer>
</match>

-----

error seen: 

2018-11-02 14:41:52 +0000 [warn]: #0 [out_kinesis_streams] failed to flush the buffer. retry_time=5 next_retry_seconds=2018-11-02 14:42:07 +0000 chunk="579af8905028993a08c4a16476dbb733" error_class=Aws::Kinesis::Errors::AccessDeniedException error="User: arn:aws:sts::478050912766:assumed-role/masters.711.k8s.local/i-05de01649fe85ab0b is not authorized to perform: kinesis:PutRecords on resource: arn:aws:kinesis:us-east-1:478050912766:stream/prod-7LogsKinesisStream"

role arn points belongs to account 774047977279. 

we need  a solution to forward fluentd logs to kinesis stream hosted in a different aws account.

**Comment by repeatedly** [comment]
Please follow contribution guide. This is not fluentd core issue, closed.
