### ISSUE TITLE
Fluentd Support Configurable Directory

### ISSUE THREAD

**Issue by ysundar** [fluent/fluentd#2174]
Hi Team,

Is td-agent-3.2.0-0.el7.x86_64.rpm file is relocatable? If yes could you please help me to provide the command

rpm -ivh --relocate /opt/=/home/ td-agent-3.2.0-0.el7.x86_64.rpm

**Comment by repeatedly** [comment]
> Is td-agent-3.2.0-0.el7.x86_64.rpm file is relocatable

No.

And this is not fluentd issue. Closed.

**Comment by ysundar** [comment]
@repeatedly Thanks for your quick reply. Last question on this therad. Does rpm can be made relocatable?
