### ISSUE TITLE
Exclude_path in in_tail plugin does not exclude log file

### ISSUE THREAD

**Issue by jwp23** [fluent/fluentd#2178]
Fluentd version: fluentd 1.2.6
OS: CentOS 7.4
Configuration
```
<source>
  @type tail
  path /xxx/log/**/*%Y%m%d.log
  exclude_path ["*feed*", "*Feed*", "*XxxFeed*", "*pricelogger*", "fix_om*2_JLQD*"]
  pos_file /var/log/td-agent/fluentd.log.pos
  tag ems.*
  <parse>
    @type multiline
    format multiline
    format_firstline /\d{8} \d{2}:\d{2}:\d{2}\.\d{9}/
    format1 /^(?<time>\d{8} \d{2}:\d{2}:\d{2}\.\d{9}) (?<level>-[a-zA-Z]-) (?<message>.*)/
  </parse>
</source>
```
Problem Statement:
I updated our configuration to exclude additional file paths `*Feed*` and `*feed*`, and `fix_om*2_JLQD`, but I still see results in elasticsearch where the files match the path `XxxFeed`
The files I do not expect to see are:
fix_XxxFeed_xxxx-taker_20181113.log
feed_kraken_trade_20181113.log

I've looked at #681 but that does not address my problem.

**Comment by repeatedly** [comment]
You need to specify entire path like `/xxx/log/**/*feed*`.

**Comment by jwp23** [comment]
Thank you. I converted to using entire paths and the exclude path works as expected.

**Comment by jcam** [comment]
Adding one related comment here that while the `path` attribute allows references to ENV variables, `exclude_path` does not, which bit me this week
