### ISSUE TITLE
How to resend files that appears in secondary_file  path 

### ISSUE THREAD

**Issue by bobykus31** [fluent/fluentd#2194]
- td-agent                       3.2.1-0
- Ubuntu 16.04.5
```
    <secondary>
      @type secondary_file
      directory /var/spool/td-agent/fluentd_failed_system
    </secondary>

```
This is actually not a problem, just a question. I have a couple of files appeared   in secondary. The question is how to resent it in easy way, do fluentd have any tools to do such?

Thank you.

**Comment by okkez** [comment]
Please follow the [guideline](https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md).

Check built-in [in_tail](https://docs.fluentd.org/v1.0/articles/in_tail) to read data from files.
