### ISSUE TITLE
Fluentd buffer plugin creates a very long file name, larger than allowed by the OS

### ISSUE THREAD

**Issue by HackToHell** [fluent/fluentd#2195]
Version: fluentd 0.12.43

The buffer plugin is configured as follows for an ES output.
```
<match rio.**>
    @type elasticsearch
    @id rio_deploy_logs
    host "#{ENV['DEPLOYMENT_LOGS_ES_HOST']}"
    port "#{ENV['DEPLOYMENT_LOGS_ES_PORT']}"
    target_index_key elastic_index_name
    type_name stdout
    remove_keys elastic_index_name
    ssl_version TLSv1_2
    reload_connections "#{ENV['ES_RELOAD_CONNECTIONS'] || 'true'}"
    # https://github.com/uken/fluent-plugin-elasticsearch#reload-after
    reload_after "#{ENV['ES_RELOAD_AFTER'] || '100'}"
    # https://github.com/uken/fluent-plugin-elasticsearch#sniffer-class-name
    sniffer_class_name "#{ENV['ES_SNIFFER_CLASS_NAME'] || 'Fluent::ElasticsearchSimpleSniffer'}"
    buffer_type file
    request_timeout 120
    buffer_path /var/lib/fluentd/buffer-dep-logs
    buffer_queue_limit 3
    resurrect_after 5s
    flush_interval 5s
    disable_retry_limit true
    max_retry_wait 120s
    buffer_chunk_limit 8388608
    reload_on_failure false
    buffer_queue_full_action block
</match>
```

ES then tries to buffer these on disk, resulting in ENAMETOOLONG.
```
2018-11-28 12:16:11 +0000 [warn]: emit transaction failed:  error_class=Errno::ENAMETOOLONG error="File name too long -  /var/lib/fluentd/buffer-dep-logs.rio.logs.deployments.kubernetes.var.log.containers.inst-ysauuvskapyvhtshpbqfvifd-djgbjv-7f6dcff658-xq29w_dep-ns-inst-ysauuvskapyvhtshpbqfvifd_init-container-65e097926491bf56fc44745c36859752d2e5fdb777e7156d085d198898160920.log.b57bb888201553442.log"   location="/opt/app-root/src/gems/fluentd-0.12.43/lib/fluent/plugin/buf_file.rb:30:in  `initialize'"  tag="rio.logs.deployments.kubernetes.var.log.containers.inst-ysauuvskapyvhtshpbqfvifd-djgbjv-7f6dcff658-xq29w_dep-ns-inst-ysauuvskapyvhtshpbqfvifd_init-container-65e097926491bf56fc44745c36859752d2e5fdb777e7156d085d198898160920.log"
```
The buffer chunking logic must have a size restriction on the file name size.

**Comment by okkez** [comment]
It seems that you use k8s and collect `/var/log/containers/*` using built-in in_tail.
Your k8s cluster generates files that have very long filename such as `/var/log/containers/inst-ysauuvskapyvhtshpbqfvifd-djgbjv-7f6dcff658-xq29w_dep-ns-inst-ysauuvskapyvhtshpbqfvifd_init-container-65e097926491bf56fc44745c36859752d2e5fdb777e7156d085d198898160920.log`.
This length is 194 bytes.

`buffer-dep-logs.rio.logs.deployments.kubernetes` is buffer_path + tag, 47 bytes.
`.b57bb888201553442.log` is the unique id added by fluentd, 22 bytes.

194 + 47 + 22 = 263 bytes > 255 bytes (OS limit)

See also https://groups.google.com/d/msg/fluentd/VKkbB47Bmqw/9fyMttiQBAAJ

**Comment by HackToHell** [comment]
Yup, the problem is that kubernetes names can be 253 bytes long. In this case it wasn't that long but it can be potentially 253 + 253 _just_ for the names. 
Might require a long term solution. (We switched to reading from journald source).

**Comment by HackToHell** [comment]
If kubelet switches to the CRI format as specified in this [design document](https://github.com/kubernetes/community/blob/4fde5ddb4eb5d7f31d2faba4d6fce99cc9b97e90/contributors/design-proposals/node/kubelet-cri-logging.md). This issue should not happen.
