### ISSUE TITLE
How to configure multilines plugin on fluentd 0.12.43 on Openshift

### ISSUE THREAD

**Issue by danilorsilva** [fluent/fluentd#2197]
I have a openshift 3.11 with EFK stack installed.

My fluentd is 0.12.43.

I would like to configure this https://docs.fluentd.org/v0.12/articles/parser_multiline

I tried to put on fluent.conf:

**format multiline
format_firstline /\d{4}-\d{1,2}-\d{1,2}/
format1 /^(?<time>\d{4}-\d{1,2}-\d{1,2} \d{1,2}:\d{1,2}:\d{1,2}) \[(?<thread>.*)\] (?<level>[^\s]+)(?<message>.*)/**

Without success.
I tried to put on fluent.conf:

**\<source>
format multiline
format_firstline /\d{4}-\d{1,2}-\d{1,2}/
format1 /^(?<time>\d{4}-\d{1,2}-\d{1,2} \d{1,2}:\d{1,2}:\d{1,2}) \[(?<thread>.*)\] (?<level>[^\s]+)(?<message>.*)/
\</source>**

Without success.

I cannot find a complete documentation teaching how to do it.

Anyone can help me?

Thanks!

**Comment by okkez** [comment]
This does not follow [contribution guide line](https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md).
So, closing.

[Docker Logging](https://www.fluentd.org/guides/recipes/docker-logging) may help you.
