### ISSUE TITLE
td-agent v3.2.1 does not close log files on rotation

### ISSUE THREAD

**Issue by zerkms** [fluent/fluentd#2200]
Check [CONTRIBUTING guideline](https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md) first and here is the list to help us investigate the problem.

- fluentd or td-agent version: `3.2.1-0`, installed through .deb files from https://www.fluentd.org/download
- Environment information, e.g. OS: ubuntu bionic 18.04
- Your configuration: irrelevant
- Your problem explanation. If you have an error logs, write it together.

When logrotate rotates the logs using the configuration shipped and installed by the .deb file:

```
/var/log/td-agent/td-agent.log {
  daily
  rotate 30
  compress
  delaycompress
  notifempty
  create 640 td-agent td-agent
  sharedscripts
  postrotate
    pid=/var/run/td-agent/td-agent.pid
    if [ -s "$pid" ]
    then
      kill -USR1 "$(cat $pid)"
    fi
  endscript
}
```

```
$ cat /var/run/td-agent/td-agent.pid
387
```

I have found that the "main" `fluentd` process does not close the file and holds it til the process restart.

Here is the corresponding `lsof`.

1. Before rotation:
```
fluentd 387 td-agent    7w      REG             253,62  5296042    526173 /var/log/td-agent/td-agent.log.1
fluentd 387 td-agent    9w      REG             253,62     4381    528081 /var/log/td-agent/td-agent.log
ruby    392 td-agent    7w      REG             253,62     4381    528081 /var/log/td-agent/td-agent.log
```

2. After rotation:
```
fluentd 387 td-agent    7w      REG             253,62  5296042    526173 /var/log/td-agent/td-agent.log.1 (deleted)
fluentd 387 td-agent    9w      REG             253,62     4381    530471 /var/log/td-agent/td-agent.log
ruby    392 td-agent    7w      REG             253,62     4381    530471 /var/log/td-agent/td-agent.log
```

3. After yet another rotation
```
fluentd 387 td-agent    7w      REG             253,62  5296042    526173 /var/log/td-agent/td-agent.log.1 (deleted)
fluentd 387 td-agent    9w      REG             253,62       66    528081 /var/log/td-agent/td-agent.log
ruby    392 td-agent    7w      REG             253,62       66    528081 /var/log/td-agent/td-agent.log
```

**Comment by repeatedly** [comment]
I confirmed this problem happens with fluentd v1.
On my test, next rotation doesn't have this problem so initial logger setup may have a problem.

**Comment by ghanane** [comment]
We are facing the same issue and it is not fixed after the first rotation.
