### ISSUE TITLE
JSON Parser implementation and documentation mismatch

### ISSUE THREAD

**Issue by Trane9991** [fluent/fluentd#2222]
Hello,
I faced unexpected behavior from fluentd JSON parser, because of the `parse` documentation and actual implementation of JSON parser differs.

Long story short, fluentd picked event time from json key `time`, when I expected it to use the current time:

[Documentation](https://docs.fluentd.org/v1.0/articles/parse-section#parse-parameters) says:

> **time_key** (string) (optional): Specify time field for event time. If the event doesn’t have this field, current time is used.
> - Default: nil

[Implementation](https://github.com/fluent/fluentd/blob/master/lib/fluent/plugin/parser_json.rb#L29) says:
> `config_set_default :time_key, 'time'`

**Comment by repeatedly** [comment]
Could you file a documentation issue on fluentd-docs?

**Comment by Trane9991** [comment]
yup, sorry, didn't know there is a separate repo for the docs:
https://github.com/fluent/fluentd-docs/issues/596
