### ISSUE TITLE
is this symlink_path bug?

### ISSUE THREAD

**Issue by yechanpark** [fluent/fluentd#2224]
Check [CONTRIBUTING guideline](https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md) first and here is the list to help us investigate the problem.

- fluentd or td-agent version.
correctly working fluentd : 0.12.26
not correctly working fluentd : 1.2.2

- Environment information, e.g. OS.
Centos 6.9

- Your configuration
- Your problem explanation. If you have an error logs, write it together.

hi. im using fluentd both 0.12.26 and 1.2.2. (different server)

when i using symlink_path with tag in v0.12.26 (exactly, tags are ${tag_parts[1], ${tag_parts[2]}, ${tag} etc. ), symlink file has been created correctly.

in my conf, logfile's path is generated by tag.
so, i want to generate symlink file's path by tag too.

for example, in 0.12.26,

if tag value is 'a.b.c',
then file path is '/a/b/c/a-b-c-file.log',
and symlink file path is '/a/b/c/a-b-c-current.log'

if tag value is 'a.b.d',
then file path is '/a/b/d/a-b-d-file.log',
and symlink file path is 'a/b/d/a-b-d-current.log'

it working perfectly.

but in 1.2.2, above setting doesn't working.
so i moved 'symlink_path' command line to everywhere.
but this setting causing error or nothing to generate current file.

so i decided downgrading fluentd version to 0.12.26.
is this correctly working now in 1.2.2?

do i don't know 1.2.2's setting with 'symlink_path'?
then how set 'symlink_path' with using tags?

i cant understand. why earlier version is working correctly but currently version is not working??

**Comment by repeatedly** [comment]
> i cant understand. why earlier version is working correctly but currently version is not working??

You don't paste your configuration, so I'm not sure what is the wrong but here is one working example.

```
<source>
  @type forward
</source>

<match test.**>
  @type file
  path /path/to/symlink/test-${tag}
  symlink_path /path/to/symlink/sym
  <buffer tag,time>
    # for test
    flush_mode interval
    flush_interval 5s
  </buffer>
</match>
```

Here is the result:

```
% ls -al symlink/
total 16
drwxr-xr-x    5 repeatedly  staff   170B 12 10 04:28 ./
drwxr-xr-x  340 repeatedly  staff    11K 12 10 04:28 ../
lrwxr-xr-x    1 repeatedly  staff    94B 12 10 04:28 sym@ -> /path/to/symlink/test-${tag}/buffer.b57caa1b13e9621e823d5a0813fc7b8d7.log
drwxr-xr-x    2 repeatedly  staff    68B 12 10 04:28 test-${tag}/
-rw-r--r--    1 repeatedly  staff    72B 12 10 04:28 test-test.foo.20181210_0.log
```

BTW, symlink_path is not good for fluentd v1 because last file is non-trivial because file chunks are generated in parallel with tag, time and field.

**Comment by yechanpark** [comment]
@repeatedly 
thanks for your response.

exactly what i mean 'symlink_path' problem is 
```
<match test.**>
  @type file
  path /path/to/symlink/test-${tag}
  symlink_path /path/to/${tag[0]]/${tag}-current.log   // here
  <buffer tag,time>
    # for test
    flush_mode interval
    flush_interval 5s
  </buffer>
</match>
```

i understood that i cant using symlink_path in td-agent 1.2.2 with tags like above setting.

so i have using fluentd-plugin-forest(https://github.com/tagomoris/fluent-plugin-forest)
for hard-coding symlink_path for each tags.

like this
```
<match a.*.**>
        @type copy
        <store>
                @type forest
                subtype file
                <template>
                        # i can using tags in 'path' paremeter
                        path /${tag[1]}/log/td-agent/${tag[1]}-${tag[2]}/${tag[1]}-${tag[2]}-%Y-%m-%d
                        <format>
                                @type json
                        </format>

                        <buffer tag, time>
                                @type file
                                chunk_limit_size 15k
                                path /var/log/td-agent/buffer/file/${tag}.buffer
                        </buffer>
                </template>

                # symlink_path doesn't working with tag placeholder. so, i must hard-coding this config.
                # so i using fluent-plugin-forest.
                <case a.b.a>
                        symlink_path /a/b/a/a-b-a-current.log
                </case>

                <case a.b.b>
                        symlink_path /a/b/b/a-b-b-current.log
                </case>

                <case a.b.c>
                        symlink_path /a/b/c/a-b-c-current.log
                </case>
        </store>
</match>
```

but this setting causing error like this when logs were coming
```
2018-12-11 10:26:05 +0900 [warn]: #0 emit transaction failed: error_class=Errno::ENOENT error="No such file or directory @ rb_file_s_symlink - (/var/log/td-agent/buffer/file/a.b.c.buffer/buffer.b57cb4f7255abfe32687e111ac86e9ace.log, /a/b/c/a-b-c-current.log)" location="/opt/td-agent/embedded/lib/ruby/2.4.0/fileutils.rb:321:in `symlink'" tag="a.b.c"
  2018-12-11 10:26:05 +0900 [warn]: #0 suppressed same stacktrace
2018-12-11 10:26:05 +0900 [error]: #0 unexpected error on reading data host="111.111.111.111" port=50710 error_class=Errno::ENOENT error="No such file or directory @ rb_file_s_symlink - (/var/log/td-agent/buffer/file/a.b.c.buffer/buffer.b57cb4f7255abfe32687e111ac86e9ace.log, /a/b/c/a-b-c-current.log)"
  2018-12-11 10:26:05 +0900 [error]: #0 suppressed same stacktrace
```


there is no way to using symlink_path in fluentd v1.2.2?

**Comment by yechanpark** [comment]
i solved problem.
using <template> and <case> setting via fluentd-plugin-forest is valid configuration.

problem was my td-agent.conf.
in my symlink_path, spelling of directory name in path was wrong...

sorry, and thanks for response about my useless question.

ill close this issue.

**Comment by yechanpark** [comment]
i closed this issue before.

what i mean 'i solved problem' is my typing miss.

and i cant using dynamic symlink_path with tags.

this feature cant be fix??

**Comment by yechanpark** [comment]
i will make symlink_path before using directory.

close.
