### ISSUE TITLE
Reloading the td-agent after configuration changes throws a nil:NilClass exception

### ISSUE THREAD

**Issue by Skarlso** [fluent/fluentd#2226]
NAME="Ubuntu"
VERSION="16.04.5 LTS (Xenial Xerus)"

Hi. 

So we are changing our configuration to update a log cluster information. The config doesn't really matter at that point because the the agent is running fine.

However when the fluentd logcollector is stopped by systemd and then restarted in the middle of that, td-agent says this: 

```
Dec  7 13:45:33 xxx-7 log[8870]: No log cluster configured for this server.
Dec  7 13:45:33 xxx-7 log[8870]: updated /etc/td-agent/log.d/server_logs.conf
Dec  7 13:45:33 xxx-7 log[8870]: Reloading td-agent after configuration changes.
Dec  7 13:45:33 xxx-7 systemd[1]: Stopping Fluentd log collector...
Dec  7 13:45:33 xxx-7 td-agent[7101]: Unexpected error undefined method `each' for nil:NilClass
Dec  7 13:45:33 xxx-7 td-agent[7101]:   /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/sigdump-0.2.4/lib/sigdump.rb:52:in `dump_backtrace'
Dec  7 13:45:33 xxx-7 td-agent[7101]:   /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/sigdump-0.2.4/lib/sigdump.rb:34:in `block in dump_all_thread_backtrace'
Dec  7 13:45:33 xxx-7 td-agent[7101]:   /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/sigdump-0.2.4/lib/sigdump.rb:33:in `each'
Dec  7 13:45:33 xxx-7 td-agent[7101]:   /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/sigdump-0.2.4/lib/sigdump.rb:33:in `dump_all_thread_backtrace'
Dec  7 13:45:33 xxx-7 td-agent[7101]:   /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/sigdump-0.2.4/lib/sigdump.rb:16:in `block in dump'
Dec  7 13:45:33 xxx-7 td-agent[7101]:   /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/sigdump-0.2.4/lib/sigdump.rb:136:in `open'
Dec  7 13:45:33 xxx-7 td-agent[7101]:   /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/sigdump-0.2.4/lib/sigdump.rb:136:in `_open_dump_path'
Dec  7 13:45:33 xxx-7 td-agent[7101]:   /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/sigdump-0.2.4/lib/sigdump.rb:14:in `dump'
Dec  7 13:45:33 xxx-7 td-agent[7101]:   /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/serverengine-2.0.6/lib/serverengine/server.rb:107:in `block (2 levels) in install_signal_handlers'
Dec  7 13:45:33 xxx-7 td-agent[7101]:   /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/serverengine-2.0.6/lib/serverengine/signal_thread.rb:96:in `main'
Dec  7 13:45:34 xxx-7 systemd[1]: Stopped Fluentd log collector.
Dec  7 13:45:34 xxx-7 systemd[1]: Started Fluentd log collector.
```

Right now we are ignoring this because after that the td-agent runs just fine, but I would rather not have a nil class exception in there. Is this something excepted or are we doing something wrong or is there a bug in the code?

I would be happy to investigate this in the code if you don't have any free cycles for this.

Thank you!

**Comment by repeatedly** [comment]
> Dec  7 13:45:33 xxx-7 td-agent[7101]: Unexpected error undefined method `each' for nil:NilClass

Hmm... this is very weird because we check backtrace field before access.

https://github.com/frsyuki/sigdump/blob/e47589517f2d84858f12156b1928706540b6734c/lib/sigdump.rb#L53

Is this problem reproducible? I'm not sure why sigdump is called in fluentd stop but I assume fluentd stopped threads which sigdump dumps.

**Comment by Skarlso** [comment]
After digging into this a bit, it might not be fluentd-s problem per say. 🤔 I think we are doing something extra to it maybe. We'll investigate further on our part. I will close up this issue for now. It's linked into our internal bug tracking system, so if it's reopened it will be more detail. If not, I guess it was our fault. :) 

Thanks for chiming in @repeatedly.
