### ISSUE TITLE
Not a issue, I just need some help with fluentd output file type

### ISSUE THREAD

**Issue by gabriel-vicente** [fluent/fluentd#2227]
Check [CONTRIBUTING guideline](https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md) first and here is the list to help us investigate the problem.

- fluentd or td-agent version.  
2.5
- Environment information, e.g. OS.  
Ubuntu
- Your configuration
```
<source>
 @type tail
 format json
 path /var/ossec/logs/alerts/alerts.json
 pos_file /var/log/td-agent/ossec_log_json.pos
 tag ossec.*
</source>

<source>
  @type syslog
  port 42185
  time_key time
  tag  firewall.*
</source>

<match firewall.*>
 @type file
  path /data/logs/firewall
  compress gzip
</match>

<match ossec.*>
 @type file
  path /data/logs/hids
  compress gzip
</match>

<match **>
 @type elasticsearch
 host localhost
 port 9200
 include_timestamp 
</match>

```
- Your problem explanation. If you have an error logs, write it together.
All works fine and it send data to ES, however I wanted also a copy to be send on /data/logs. I added the type file and the path however I cannot see any file there. I have tried everything already, I even tried this other configuration here, but still no files are been sent to /data/log.
Thanks for the help and sorry if this isn't the right place to ask it.
```

<source>
 @type tail
 format json
 path /var/ossec/logs/alerts/alerts.json
 pos_file /var/log/td-agent/ossec_log_json.pos
 tag ossec.*
</source>

<source>
  @type syslog
  port 42185
  time_key time
  tag  firewall.*
</source>

<match firewall.*>
 @type copy
  <store>
    type file
    path /data/logs/firewall
	compress gzip
   <buffer>
    timekey 1d
    timekey_use_utc true
    timekey_wait 10m
   </buffer>
  </store>
</match>

<match ossec.*>
 @type copy  
  <store>
    type file
    path /data/logs/hids
	compress gzip
   <buffer>
    timekey 1d
    timekey_use_utc true
    timekey_wait 10m
   </buffer>
  </store>
</match>

<match **>
 @type elasticsearch
 host localhost
 port 9200
 include_timestamp
</match>           
```

**Comment by repeatedly** [comment]
This doesn't follow cotribution guide and I have already replied on ML. Closed.
