### ISSUE TITLE
Building td-agent rpm/relocatable rpm

### ISSUE THREAD

**Issue by akshatsharma4** [fluent/fluentd#2228]
Hi, 

This is not an issue but more of a query.

I am trying to build td-agent rpm using the project available on : "https://github.com/treasure-data/td-agent" , which is an obsolete repository, as mentioned. 
While building the rpm, I am facing many dependency issues, hence not able to make rpm out of it.

My query is, how the latest td-agent rpms available on: "https://td-agent-package-browser.herokuapp.com/3/redhat/7/x86_64" are built ? where can I find the source code or spec files to build these rpms?

Can you please help me with the steps/link that I need to follow in order to make td-agent rpm?

Note: I am trying to build relocatable td-agent rpm. Once this is achieved, it will be contributed to open source. 

Thanks,
Akshat

**Comment by repeatedly** [comment]
README links to new repository: https://github.com/treasure-data/td-agent#note
