### ISSUE TITLE
In_tail plugin not expending paths properly with subfolders (multiple * in the path)

### ISSUE THREAD

**Issue by visla** [fluent/fluentd#2229]
fluentd version: 1.3.1
environment - official docker image used. (1.3-debian-onbuild)
logging level of fluentd: debug

I have the following setup for in_tail 
```
<source>
  @type tail
  path /container-logs/*/alloc/logs/*.stdout.0
  pos_file /tmp/fluentd/logging-containers.log.pos
  refresh_interval 30
  tag containers.*
  <parse>
      @type none
  </parse>
</source>

```
if my source is setup like this it never expands the paths and shows no trace/debug logs that it started tailing any files. Also I don't get anything matched and nothing goes to my elasticsearch. 

If I just change the path in source to 
/container-logs/1235/alloc/logs/*.stdout.0 (replaced first * with exact number of container guid) all works fine. Log would show me that it is tailing the right files, and I am starting to get results. 

I've checked the 1.3 ruby code for input tail plugin and I don't see any problems why this should not work. My log structure mounted via docker to fluentd container is like this:
/container-logs/container-guid/alloc/logs/container-name.stdout.0
/container-logs/container-guid2/alloc/logs/container-name2.stdout.0
/container-logs/container-guid3/alloc/logs/container-name3.stdout.0
...

I lost time and time to decipher why it is unable to tail all these logs properly. Am I missing some generic setting, or something?

I've tried the following without success, too.
```
/container-logs/**/alloc/logs/*.stdout.0
/container-logs/**/*.stdout.0
```

**Comment by repeatedly** [comment]
Does fluentd have the permission for container-logs and its sub-directory?

**Comment by visla** [comment]
Great hint. it seems that might be the problem, just checked. Will try to find the best way to inject my user_id and run fluentd as that user instead. If you have any best advice on that it would be appreciated.
