### ISSUE TITLE
fluentd_output_status_num_errors is not reseting to zero after a successful retry

### ISSUE THREAD

**Issue by sanjuicgithub** [fluent/fluentd#2230]
Check [CONTRIBUTING guideline](https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md) first and here is the list to help us investigate the problem.

- fluentd or td-agent version  :  3.2.0
- Environment information,  Docker container running on Centos 7.
- Your configuration

td-agent.conf 

```
<match prod.**>
 @type copy
 <store>
   @type forward
   <server>
     name <target server>
     host <target server ip>
     port 24224
   </server>
   <buffer>
     flush_interval 5s
     flush_thread_count 4
   </buffer>
 </store>
 <store>
   @type prometheus
   <metric>
     name fluentd_output_status_num_records_total
     type counter
     desc The total number of outgoing records
     <labels>
       tag ${tag}
       hostname ${hostname}
     </labels>
   </metric>
 </store>
</match>

### PROMETHEUS-PLUGIN OUTPUT
<source>
  @type prometheus
  bind 0.0.0.0
  port 9010
  metrics_path /metrics
</source>
<source>
  @type prometheus_output_monitor
  interval 10
</source>
```

- Your problem explanation. If you have an error logs, write it together.
'fluentd_output_status_num_errors' is not reseting to zero after a successful retry and this leads to a false active alerts in Prometheus. We have an alert defined if this remains non-zero for longer time.

fluentd_output_status_num_errors{job="tdagents"} > 0

I already read this  issue  [https://github.com/fluent/fluentd/issues/1379] but it looks to be existing in older version and has already been addressed however this exists in the latest version (td-agent-3.2.0) too.  

Can you please look into this issue ?

**Comment by repeatedly** [comment]
prometheus plugin doesn't provide a metric for `@retry.steps`?

**Comment by repeatedly** [comment]
Do you want to remove fluentd_output_status_retry_count from metrics?
prometheus plugin issue?

**Comment by shivamdixit** [comment]
and prometheus pluging doesn't provide `retry.steps`. It only has `retry_count` and `retry_wait`.

**Comment by repeatedly** [comment]
@shivamdixit From above comment, you can use fluentd_output_status_retry_count for checking the retry count. `num_errors` counts the errors, not retry count.

**Comment by repeatedly** [comment]
Closed. `num_errors` shows the total number of emit/flush errors.

**Comment by petergvizd** [comment]
So maybe one question why it is then of type gauge, when it is behaving like counter?
