### ISSUE TITLE
suppress_parse_error_log missing 

### ISSUE THREAD

**Issue by da125** [fluent/fluentd#2231]
Hi,

I noticed in version 1.x of fluentd, the parser type is missing the suppress_parse_error_log option. Sadly, without it, we get an error every time a log doesn't match because of a regexp we're using.

Is there maybe an alternative or a different way of writing the config so that we ignore errors about non-matching regex but still keep other errors?

PS: fluentd is running inside a container (fluentd:1.3.1) and collecting logs from other containers via the fluentd docker login-driver. The host is an ubuntu 16.04 openstack instance.

current config:
```
<source>
  @type  forward
  port  24224
</source>
<filter docker.xxx>
  @type parser
  key_name log
  reserve_data true
  <parse>
    @type regexp
    expression /^(?<_extra_field>^MYSTRING)/
  </parse>
</filter>
<filter docker.*>
  @type record_transformer
  enable_ruby true
  <record>
    version "1.1"
    host "${hostname}"
    short_message "short messsage"
    full_message ${record["log"]}
    timestamp ${time.to_i}
    level ${1}
    _container_id ${record["container_id"]}
    _container_name ${record["container_name"]}
    _source ${record["source"]}
  </record>
  remove_keys source,message,worker,log,container_id,container_name
</filter>
<match docker.*>
  @type http
  ssl_no_verify   true
  endpoint_url    "http://1.2.3.4/"
  http_method     post
  serializer      json
  custom_headers  {"id":"myid","pass":"mypass"}
</match>

```

**Comment by repeatedly** [comment]
How about setting `emit_invalid_record_to_error flase`?

**Comment by da125** [comment]
I must have had some weird config because it works now but it didn't work when I tested it 6h ago.

Anyway, issue can be closed, it seems this was another case of PEBKAC.
