### ISSUE TITLE
Fluentd on Windows does not resolve ffi 1.10.0 dependency when using Ruby 2.1.0

### ISSUE THREAD

**Issue by cosmo0920** [fluent/fluentd#2255]
Check [CONTRIBUTING guideline](https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md) first and here is the list to help us investigate the problem.

- fluentd or td-agent version.

 master

- Environment information, e.g. OS. 

Windows, AppVeyor

- Your configuration none. 

Depelopment issue.

- Your problem explanation. If you have an error logs, write it together.

When using ffi 1.10.0 and Ruby 2.1.0 on Windows, bundle install cannot continue due to Gem::RuntimeRequirementNotMetError:

```log
Gem::RuntimeRequirementNotMetError: ffi requires Ruby version >= 2.2, < 2.7.dev.
The current ruby version is 2.1.0.
An error occurred while installing ffi (1.10.0), and Bundler cannot continue.
Make sure that `gem install ffi -v '1.10.0' --source 'https://rubygems.org/'`
succeeds before bundling.
In Gemfile:
  fluentd was resolved to 1.3.3, which depends on
    win32-service was resolved to 0.8.10, which depends on
      ffi-win32-extensions was resolved to 1.0.3, which depends on
        ffi
```

ref: https://ci.appveyor.com/project/fluent/fluentd/builds/21449636/job/6sqtuwx52t9dbayp#L27

I confirmed that ffi does not include binary for Ruby 2.1.0 since 1.10.0-(x86|x64)-mingw32.
How do we fix it?

**Comment by repeatedly** [comment]
Maybe no need for the fix because ruby 2.1 is EOL and no reason to use ruby 2.1 on windows.
