### ISSUE TITLE
Buffer options retry_forever and secondary shouldn't be exclusive

### ISSUE THREAD

**Issue by yann-soubeyrand** [fluent/fluentd#2257]
Hi,

In my opinion, buffer options retry_forever and secondary output shouldn't be exclusive. Indeed, I expect Fluentd to retry forever in case of recoverable errors, but to proceed with secondary in case of unrecoverable errors. In my understanding, the code already works like this and the only thing to do is to remove the configuration constraint (to confirm by someone more familiar with Fluentd's code).

**Comment by repeatedly** [comment]
Patch is here: https://github.com/fluent/fluentd/pull/2276

**Comment by yann-soubeyrand** [comment]
Thanks a lot!
