### ISSUE TITLE
Fluent fails to resolve elastic search host

### ISSUE THREAD

**Issue by Mymetique** [fluent/fluentd#2269]
Hello,

We are using fluent on arch linux and have something like this in our conf : 

`<source>
  @type systemd
  tag native
  path /var/log/journal
  <storage>
    @type local
    persistent true
    path /var/log/systemd.pos
  </storage>
  <entry>
    fields_strip_underscores true
    fields_lowercase true
  </entry>
  read_from_head true
</source>

<match **>
  @type elasticsearch
  include_tag_key true
  host elasticsearch
  port 9200
  scheme http
  reload_connections true
  logstash_prefix logstash
  tag_key @log_name
  logstash_format true
  type_name fluentd
  <buffer>
    flush_thread_count 2
    flush_interval 5s
    chunk_limit_size 2M
    queue_limit_length 32
    retry_max_interval 30
    retry_forever true
  </buffer>
</match>`

As you can see host is elasticsearch, we can ping and access 'elasticsearch' from this node. When we run fluent, it will work for a while then it will start to throw errors like : 

`error_class=Fluent::Plugin::ElasticsearchOutput::RecoverableRequestFailure error="could not push logs to Elasticsearch cluster ({:host=>\"elasticsearch\", :port=>9200, :scheme=>\"http\"}): Connection refused - connect(2) for 127.0.0.1:9200 (Errno::ECONNREFUSED)`

Well of course connection is refused on 127.0.0.1, but why fluent resolves elasticsearch as localhost while in the node's routes it is something completely different ? 

Thanks for you help.

**Comment by cosmo0920** [comment]
Please follow the [contributing guideline](https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md).
This is not Fluentd issue, so closed.

**Comment by cosmo0920** [comment]
This issue seems to be caused by fluent-plugin-elasticsearch and its dependent gems.
Please open a new issue in [fluent-plugin-elasticsearch's bug tracker](https://github.com/uken/fluent-plugin-elasticsearch/issues).
