### ISSUE TITLE
The “match” directive does not support embedded Ruby

### ISSUE THREAD

**Issue by zhelyan** [fluent/fluentd#2273]
Using the official `fluent/fluentd:v1.3.3-onbuild-1.0` docker image:

```
fluentd-1.3.3
ruby="2.5.2"
fluent-plugin-ec2-metadata version '0.1.2'
fluent-plugin-multi-format-parser version '1.0.0'
fluent-plugin-s3 version '1.1.7'
```
I confugure fluentd using environment variables and noticed that the `match` directive does not expand the match pattern:

```
# FLUENT_TAG is set dynamically at deployment time to match
# the application being deployed e.g. `prod.project1.web`


<source>
 @type tail
   ....
  tag "docker.#{ENV['FLUENT_TAG']}"
</source>

<match "docker.#{ENV['FLUENT_TAG']}" >
  @type ec2_metadata
  output_tag ${tag}.${instance_id}
</match>

<match docker.**>
  @type s3
  ...
</match>
 ....

```

Is this intended behaviour? If yes - what are the workarounds?

**Comment by repeatedly** [comment]
> Is this intended behaviour? 

Yes because the argument of match directive doesn't support embbeded ruby code for now.

> what are the workarounds?

Currently, fluentd forwards such tasks to deployment tools.
But supporting it seems no problem for me.

**Comment by zhelyan** [comment]
@repeatedly thanks for confirming, you can close this now but I wonder if the official documentation should be updated to avoid further confusion until support is added?
