### ISSUE TITLE
Timezone problem

### ISSUE THREAD

**Issue by chenjienn** [fluent/fluentd#2278]
Problem

When the timestamp field in my log is 00:00:00 , the field in es is 08:00:00. My timezone is +8:00 , how can i store the correct timestamp

the attach file is the fluentd config file.

Using Fluentd and ES plugin versions

td-agent 3.2.1
paste result of fluentd --version or td-agent --version
ES version 6.2.3

[td-agent.conf.dest.txt](https://github.com/fluent/fluentd/files/2805598/td-agent.conf.dest.txt)
[td-agent.conf.source.txt](https://github.com/fluent/fluentd/files/2805599/td-agent.conf.source.txt)

**Comment by cosmo0920** [comment]
I've answered here:
https://github.com/uken/fluent-plugin-elasticsearch/issues/534

BTW: Here is not community forum. We use GitHub issues as an issue tracker and don't use support forum.
So, I'm closing this issue.
Perhaps, you have an additional question, you can use fluent-plugin-elasticsearch issue tracker or Fluentd community slack.

**Comment by cosmo0920** [comment]
Current Fluentd's parser_json handle Timezone in time key automatically.
Should Fluentd handle timezone settings in `<parse>` section?

There is no paramter to specify timekey timezone for now.

**Comment by repeatedly** [comment]
I'm not sure failure case with parser_json.

https://github.com/fluent/fluentd/blob/162d20ead3dd77885e019a73ec307407e2769863/lib/fluent/plugin/parser_json.rb#L69

parser_json uses time parser in parsing. This time parser doesn't include parser settings properly?

**Comment by cosmo0920** [comment]
Oh..., I've misunderstood parser_json implementation.

Here is a configuration to specify timezone in parse section:

```aconf
  <parse>
    @type json
    time_key @timestamp
    time_format %Y-%m-%dT%H:%M:%S.%N%z
    timezone +00:00
  </parse>
```

I can handle timezone in parser_json.
