### ISSUE TITLE
extract_placeholders does not support timezone?

### ISSUE THREAD

**Issue by u-shunya** [fluent/fluentd#2279]
`extract_placeholders` does not support timezone?

My server's local timezone is JST(+0900).
When setting the following, flushed file does not rotate until am 9.
That is, until 2019-01-29 08:59:59 events are flushed to `foo.20190128.log`.
I set timekey_use_utc to true, but nothing changed.

```
  <match **>
    @type file
    path /var/log/${tag}.%Y%m%d
    append true
    <buffer tag,time>
      @type file
      path /var/log/buffer/buf.*.log
      flush_mode interval
      flush_interval 10s
      timekey 86400
      timekey_wait 10m
    </buffer>
  </match>
```

**Comment by ganmacs** [comment]
No response from the author for a long time. I'm closing. feel free to ask us if you have additional info.
