### ISSUE TITLE
Docs don't contain conf location for Docker

### ISSUE THREAD

**Issue by DarrienG** [fluent/fluentd#2285]
I'm not entirely sure where the doc source is located, so I'm posting here. Not a very big issue to fix, but the current docs for finding the config file are located here: https://docs.fluentd.org/v0.12/articles/config-file

And are also the top Google result if you Google `fluent config file`

The current docs list: 

```
/etc/td-agent/td-agent.conf
```
and
```
/etc/fluent/fluent.conf
```

As the only two places the config file might be.

However when using the Docker container, the config file is located in `/fluentd/etc` which is not documented there and is hiding somewhere in the middle of the official DockerHub repo: https://hub.docker.com/r/fluent/fluentd/ only briefly mentioned in a docker mount command:

```
docker run -ti --rm -v /path/to/dir:/fluentd/etc fluentd -c /fluentd/etc/ -v
```

I spent a good 30 minutes poking around for this non-standard config location. Since the place in docker containers for the config file is... uh... interesting, could it please be added to https://docs.fluentd.org/v0.12/articles/config-file ?

Thanks :)

**Comment by repeatedly** [comment]
> Since the place in docker containers for the config file is... uh... interesting, could it please be added to https://docs.fluentd.org/v0.12/articles/config-file ?

This is docker image specific directory, this is why we need `-c` option to tell it,so if we add note for conf location, it should be in docker image README.

**Comment by DarrienG** [comment]
I disagree, by doing that you're pretty much saying Docker is not a first class citizen (which I think most people using Fluentd would disagree with).

Take a competitor - Filebeat for instance: https://www.elastic.co/guide/en/beats/filebeat/current/directory-layout.html

Default paths for all installation types are listed. There's even an explanation of what each dir does, and how they can autostart!

**Comment by repeatedly** [comment]
> I think most people using Fluentd

You have a point. Fluentd with docker is now popular so adding it to the fluentd-docs seems reasonable.
Could you send a PR?

**Comment by DarrienG** [comment]
Sure :)

https://github.com/fluent/fluentd-docs/pull/614

**Comment by repeatedly** [comment]
Merged fluentd-docs patch. Thanks
