### ISSUE TITLE
JSON log field not being parsed using json_parser

### ISSUE THREAD

**Issue by bamb00** [fluent/fluentd#2287]
Hi, 

I'm using the json_parser plugin to get the one json map per line like below.  But it seems the json parser plugin is not parsing the json log field.  

     record:
     {
       "level"  : "info",
       "msg"  : "started handling request",
       "method": "GET",
       ...
     }

- fluentd version 1.2.4
- Redhat 7.6, K8s v1.13.1
- Configuration:

      <filter kubernetes.var.log.containers.**>
         @type parser
         <parse>
            @type json
            json_parser json
         </parse>
         replace_invalid_sequence true
         emit_invalid_record_to_error false
         key_name log
         reserve_data true
      </filter>

Log:

     {"log":"time=\"2019-02-07T02:05:50Z\" level=info msg=\"request\" method=DELETE remote=\"109.23.88.254:48899\" request=/zzzzz source=\"aaaa@v0.0.0/make.py:6784\"\n","stream":"stderr","time":"2019-02-07T02:05:50.308453245Z"}

Thanks.

**Comment by repeatedly** [comment]
> time=\"2019-02-07T02:05:50Z\" level=info msg=\"request\" method=DELETE remote=\"109.23.88.254:48899\" request=/zzzzz source=\"aaaa@v0.0.0/make.py:6784\"\n

This is not json.

**Comment by bamb00** [comment]
Hi,
It is a valid json.  I ran it through a JSON validator (https://jsonlint.com/).  I don't understand why is not a json.
Thanks.

**Comment by repeatedly** [comment]
>  {"log":"time=\"2019-02-07T13:54:35Z\" level=info msg=\"completed handling request\" _source=\"negroni-logrus@v0.0.0-20170801195057-31067281800f/middleware.go:141\" measure#web.latency=121700 method=GET remote=\"10.233.108.0:12345\" request=/healthz status=200 text_status=OK took=\"121.7µs\"\n","stream":"stderr","time":"2019-02-07T13:54:35.344089098Z"}

Yes. This is valid json object. But 

> time=\"2019-02-07T13:54:35Z\" level=info msg=\"completed handling request\" _source=\"negroni-logrus@v0.0.0-20170801195057-31067281800f/middleware.go:141\" measure#web.latency=121700 method=GET remote=\"10.233.108.0:12345\" request=/healthz status=200 text_status=OK took=\"121.7µs\"\n

This is not valid json object.

**Comment by bamb00** [comment]
Hi, Do I need to set the key_name to _source? The goal is to parse the entire keys=values in log.  Thanks.

**Comment by bamb00** [comment]
key_name is a required parameter.  Then I would need to specified all the keys to parse the field log.

**Comment by repeatedly** [comment]
The problem is your log format is original `"key"="value"` format, not json.
So there are two approaches to parse it.

- Change your application log format from your original format to json. I'm not sure your logger supports json format or not.
- Write your own parser for your original format and specify it in parser config like below.

```
<filter>
  @type parser
  key_name log
  <parse>
     @type your_parsera_name
  </parse>
</filter>
```

**Comment by bamb00** [comment]
Thanks for the help.  We are working on changing the log format.
