### ISSUE TITLE
in_http cannot work with https

### ISSUE THREAD

**Issue by ialidzhikov** [fluent/fluentd#2290]
Check [CONTRIBUTING guideline](https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md) first and here is the list to help us investigate the problem.

- fluentd or td-agent version.
- Environment information, e.g. OS.
- Your configuration
- Your problem explanation. If you have an error logs, write it together.

`in_http` cannot accept `transport` or `server` configuration in order to be configured with ssl. For example the kube-apiserver from version `1.13.0` has an alpha feature to send audit logs to a destination over `https`- https://kubernetes.io/docs/tasks/debug-application-cluster/audit/#dynamic-backend . Currently fluentd cannot be a dynamic backend for kubernetes audit logs.

Do you plan support for any https input plugin?

**Comment by cosmo0920** [comment]
Duplicated of https://github.com/fluent/fluentd/issues/2124?

**Comment by ialidzhikov** [comment]
> Duplicated of #2124?

Yes, I will close this one and lets track the update in #2124 .
