### ISSUE TITLE
Incoming chunk is broken JSON - log4j2 socket appender

### ISSUE THREAD

**Issue by missourian55** [fluent/fluentd#2293]
Check [CONTRIBUTING guideline](https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md) first and here is the list to help us investigate the problem.

- fluentd or td-agent version.
**fluentd 1.3.3**
- Environment information, e.g. OS.
**mac os and debian**
- Your configuration
```
<source>
  @type forward
  port 24224
  bind 0.0.0.0
  @log_level debug
</source>

<match **>
  @type stdout
</match>
```
- Your problem explanation. If you have an error logs, write it together.
Java application using log4j2 **Socket Appender** and JSON Layout.

**Application Logs in console**

```

{"thread":"localhost-startStop-1","level":"DEBUG","loggerName":"org.springframework.beans.factory.support.DefaultListableBeanFactory","message":"Creating instance of bean 'cxf'","endOfBatch":false,"loggerFqcn":"org.apache.logging.log4j.jcl.Log4jLog","instant":{"epochSecond":1550109138,"nanoOfSecond":512000000},"threadId":15,"threadPriority":5,"timestamp":"2019-02-13T19:52:18.512-0600"}
```
**Fluentd log**

```
2019-02-13 19:41:49 -0600 [warn]: #0 incoming chunk is broken: host="127.0.0.1" msg={"thread"=>"localhost-startStop-1", "level"=>"DEBUG", "loggerName"=>"org.springframework.beans.factory.support.DefaultListableBeanFactory", "message"=>"Creating instance of bean 'cxf'", "endOfBatch"=>false, "loggerFqcn"=>"org.apache.logging.log4j.jcl.Log4jLog", "instant"=>{"epochSecond"=>1550108509, "nanoOfSecond"=>935000000}, "threadId"=>15, "threadPriority"=>5, "timestamp"=>"2019-02-13T19:41:49.935-0600"}
```

**Comment by missourian55** [comment]
wrong config in application

**Comment by r-dilip** [comment]
@missourian55 : Can you please elaborate on this? 

> wrong config in application

**Comment by TamerDev** [comment]
Did you resolve this? I'm getting same error. Also I'm not sure why the received message replaces ":" with "=>" .

**Comment by r-dilip** [comment]
>Also I'm not sure why the received message replaces ":" with "=>" .
I believe thats ruby converting JSON to a hash and logging it on the console. When that happens, ruby displays => for the key => value depiction

FWIW, in my case, I was sending to http out and reading using in_forward which is fluent protocol . Once I fixed that, this problem went away for me. Hope that helps!

**Comment by TamerDev** [comment]
so what is the proper way?  Here is my current config:
<source>
  @type forward
  port 24224
  tag debug.*
  bind 0.0.0.0
  @log_level debug
  <parse>
      @type json
    </parse>
</source>
<match debug.*>
  @type copy
  <store>
    @type stdout
    @id output_stdout
    format json
  </store>
</match>

and message are sent using TCP protocol. 
If I change the  "@type forward" to "@type tcp", the td-agent does not receive the message at all.

**Comment by r-dilip** [comment]
here forward is receiving the messages. What is the config of the component that is sending these messages? 
Are you using the [https://docs.fluentd.org/output/forward](forward) plugin?

**Comment by TamerDev** [comment]
yes, I'm using the forward plugin. also I think I tried the tcp.
I'm working with the firwall team to open up udp so I can send over udp and hopefully this will not have the truncation error.
