### ISSUE TITLE
fluentd out_file created  time is not the same  with system time

### ISSUE THREAD

**Issue by SFHfeihong** [fluent/fluentd#2294]
fluentd or td-agent version: 3.2.0
Environment information: centos 6.7
```
cat /etc/td-agent/td-agent.conf
<source>
  @type forward
  port 24224
  bind 0.0.0.0
</source>

<match accessLog-1100000221>
  @type file
  path /mnt/1100000221/30000/adms-service-access-%Y-%m-%d-%H-%M
  append true
  <format>
    @type single_value
  </format>
  <buffer time>
    @type file
    flush_mode interval
    flush_interval 5s
    timekey 1m
  </buffer>
</match>
```
The problem:
![image](https://user-images.githubusercontent.com/27404167/52758415-23054200-3043-11e9-89df-dee4c65e1d2a.png)
The  time out file created does not  match the system time of server.

**Comment by ganmacs** [comment]
yes. in_forward respects the original time like [this](https://github.com/fluent/fluentd/blob/6ef77be211d33c06c8602f71daa47910822e042e/lib/fluent/plugin/in_forward.rb#L330). this means if there is time parameter in message in_forward receives, in_forward uses it and the value is sure to be diffirent from system time.

BTW, please follow the contribution guide next time. https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md#got-a-question-or-problem
