### ISSUE TITLE
Getting failed to parse error for field with value = "OK [0]"

### ISSUE THREAD

**Issue by warrenackerman** [fluent/fluentd#2296]
Check [CONTRIBUTING guideline](https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md) first and here is the list to help us investigate the problem.

- fluentd or td-agent version.
1.3.3
- Environment information, e.g. OS.
Rhat 7.6
- Your configuration
- Your problem explanation. If you have an error logs, write it together.
dump an error event: error_class=Fluent::Plugin::ElasticsearchErrorHandler::ElasticsearchError error="400 - Rejected by Elasticsearch [error type]: mapper_parsing_exception [reason]: 'failed to parse [parsed.status]'" location=nil tag="my.log" time=2019-02-14 14:37:49.504640216 +0000 record={"log"=>"{\"trace_id\":\"1ad740260ab3f0562aa6dde99fdb3323\",\"span_id\":\"cdfa9664c7cc29f2\",\"span\":\"/health\",\"status\":\"OK [0]\",\"elapsed\":\"0s\",\"attributes\":{\"http.host\":\"\",\"http.method\":\"GET\",\"http.path\":\"/health\",\"http.status_code\":200,\"http.user_agent\":\"kube-probe/1.13\"}}\n", "stream"=>"stdout", "time"=>"2019-02-14T14:37:48.76839547Z", "parsed"=>{"trace_id"=>"1ad740260ab3f0562aa6dde99fdb3323", "span_id"=>"cdfa9664c7cc29f2", "span"=>"/health", "status"=>"OK [0]", "elapsed"=>"0s", "attributes"=>{"http.host"=>"", "http.method"=>"GET", "http.path"=>"/health", "http.status_code"=>200, "http.user_agent"=>"kube-probe/1.13"}}}

I assume it does not like [0] but I dont understand why.

**Comment by cosmo0920** [comment]
This is [fluent-plugin-elasticsearch](https://github.com/uken/fluent-plugin-elasticsearch) issue not Fluentd. 
Please read [the contributing guideline](https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md) before opening an issue.
Closing.
