### ISSUE TITLE
after restart the fluentd, Buffer would never retry if no new data come

### ISSUE THREAD

**Issue by maxwellzdm** [fluent/fluentd#2302]
If output plugin failed to send the data, it will persist the buffer on to the disk.
when I shutdown the fluentd, the buffer file would remain on the disk.
But the buffer file would never be flushed until new data come in.

**Comment by ganmacs** [comment]
please read https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md#got-a-question-or-problem
