### ISSUE TITLE
ElasticSearch output plugin with time-based index via buffer time and timezone

### ISSUE THREAD

**Issue by yechanpark** [fluent/fluentd#2315]
Check [CONTRIBUTING guideline](https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md) first and here is the list to help us investigate the problem.

- fluentd or td-agent version.
v1.2.2

- Environment information:
	- Operating system: `cat /etc/os-release`
	- Kernel version: `uname -r`

- Your configuration
```
<store>
                @type elasticsearch

                index_name ${tag}_%Y.%m.%d

               <buffer tag, time>
                  @type file
                  path /var/log/td-agent/buffer/elasticsearch/${tag}.buffer

                  timekey_zone +0900

                  chunk_limit_size 5m
                  flush_mode interval
                  flush_interval 1s

                  timekey 1m # chunks per hours ("3600" also available)
               </buffer>

                host 127.0.0.1
                port 9200

        <secondary>
                   @type file
                    path /var/log/td-agent/buffer/failed/${tag}.buffer
        </secondary>
</store>
```

- Your problem explanation. If you have an error logs, write it together.
im using ta-agent 1.2.2

im using elasticsearch's curator, and deleting indices that older than 6 days.

so, i creating indices like this.
'log_index_2019_02_27'

so, my fluentd config is using buffer (for fail over and inject logs to time-based indices).

above is my config, but this config doesn't working.

i expected following.
if index name is 'log_index_2019_02_26',
this index must including 2019/02/26 00:00 ~ 2019/02/26 23:59  time range's logs

if index name is 'log_index_2019_02_27',
this index must including 2019/02/27 00:00 ~ 2019/02/27 23:59  time range's logs.

but in my case, 
if index name is 'log_index_2019_02_26',
this index including 2019/02/26 09:00 ~ 2019/02/27 08:59  time range's logs

if index name is 'log_index_2019_02_27',
this index including 2019/02/27 09:00 ~ 2019/02/28 08:59  time range's logs.

so, i want to +9 hours (or -9 hours? i confused)

im testing following configs in <buffer> section.
timekey_use_utc true (or false)
timekey_zone -0900 (or +0900)

how can i controll time index_name's date(%Y.%m.%d) in fluentd config ??

im looking [reference](https://docs.fluentd.org/v1.0/articles/buffer-section), but i'm confusing.

**Comment by repeatedly** [comment]
Is this related https://github.com/fluent/fluentd/pull/2054 ?

**Comment by yechanpark** [comment]
@repeatedly 
thx for your response.

i solved this problem, and following is my td-agent.conf

```
<store>
                @type elasticsearch

                index_name ${tag}_%Y.%m.%d

               <buffer tag, time>
                  @type file
                  path /var/log/td-agent/buffer/elasticsearch/${tag}.buffer
                  
                  timekey_use_utc false   #added
                  timekey_zone +0900

                  flush_mode interval
                  flush_interval 1s

                  timekey 1m
               </buffer>

                host 127.0.0.1
                port 9200

        <secondary>
                   @type file
                    path /var/log/td-agent/buffer/failed/${tag}.buffer
        </secondary>
</store>
```

close.
