### ISSUE TITLE
Support of json formatter in elasticsearch output

### ISSUE THREAD

**Issue by aido93** [fluent/fluentd#2320]
Hello! Do you plan to add support of json formatter in elasticsearch output and other outputs?
I see in docs that it is supported only by three outputs: https://docs.fluentd.org/v1.0/articles/formatter-plugin-overview

But in our use-case we need to send logs from haproxy to rsyslog (because haproxy can send its logs only there) that directs them into fluentd that directs them to ElasticSearch (haproxy->rsyslog->fluentd->ES).
Also we need to see in kibana **labeled** metrics of haproxy. Therefore, we use json in haproxy logs. If I add `format json` to 'source'-section, then it cannot parse input (syslog format, not json).

**Comment by aido93** [comment]
Also when I try to add to rsyslog next lines
```
template(name="ls_json" type="list" option.json="on") {
  constant(value="{")
  constant(value="\"@timestamp\":\"") property(name="timereported" dateFormat="rfc3339")
  constant(value="\",\"@version\":\"1")
  constant(value="\",\"message\":\"") property(name="msg")
  constant(value="\",\"host\":\"") property(name="hostname")
  constant(value="\",\"severity\":\"") property(name="syslogseverity-text")
  constant(value="\",\"facility\":\"") property(name="syslogfacility-text")
  constant(value="\",\"programname\":\"") property(name="programname")
  constant(value="\",\"procid\":\"") property(name="procid")
  constant(value="\"}\n")
}
*.* @@fluentd:5140;ls_json
```
And in fluentd config:
```
<source>
  @type syslog
  tag haproxy
  bind 0.0.0.0
  port 5140
  protocol_type tcp
  format json
</source>
```
Then I have in logs:
```
[warn]: #0 invalid syslog message: "{
\"@timestamp\":\"2019-02-27T16:53:51+00:00\",
\"@version\":\"1\",
\"message\":\" {
\\\"client\\\":\\\"XXX.XXX.XXX\\\",
\\\"frontend_type\\\":\\\"PRIVATE_HTTP\\\",
\\\"url\\\":\\\"example.com\\\",\\\"retries\\\":0,\\\"read\\\":119003,
\\\"upload\\\":270,\\\"server_queue\\\":0,
\\\"backend_queue\\\":0,\\\"status\\\":200,
\\\"request\\\":\\\"GET /metrics HTTP/1.1\\\"}\",
\"host\":\"XXX.XXX.XXX.XXX\",\"severity\":\"info\",
\"facility\":\"local1\",\"programname\":\"haproxy\",\"procid\":\"8\"}"
```

**Comment by cosmo0920** [comment]
This is fluent-plugin-elasticsearch issue not Fluentd.
Could you open this issue in [fluent-plugin-elasticsearch's bug tracker](https://github.com/uken/fluent-plugin-elasticsearch/issues/new)?
Closing.

**Comment by repeatedly** [comment]
Hmm... Is this es plugin issue or how to parse json payload with syslog input?
Issue title and issue body seems different for me.
BTW, the questino should be in mailing list so closing issue is ok.
