### ISSUE TITLE
Custom Time format

### ISSUE THREAD

**Issue by Oyabi** [fluent/fluentd#2322]
- fluentd or td-agent version : `td-agent 3.3.0-1`
- Environment information:
	- Operating system: `cat /etc/os-release` : 
```
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
	- Kernel version: `uname -r` : `4.9.0-8-amd64`
- Your configuration:
```
<source>
  @type tail

  path /home/web/mydomain.com/appli/**/log/mydomain.log
  path_key tailed_path
  pos_file /var/log/td-agent/tmp/mydomain.pos
  read_from_head true
  tag tag.mydomain
  format /(?<time>\d{2}\/\d{2}\/\d{4} a \d{2}:\d{2}:\d{2})\|(?<action>trsp:\d{3} - [a-zA-Z]*: *[a-zA-Z]*)\|(?<src>[^\|]+)\|(?<message>.*)/
  time_format %d/%m-%Y a %H:%M:%S
</source>
```

- Log example:
```
Le   06/02/2019 a 02:31:22|trsp:253 - login:          |  1.1.1.1|- from:           | Login admin: [master69]
```

Hi,
I must implement a log management for and old application but I don't really know how to do that.
As you can see the time field (`Le   06/02/2019 a 02:31:22`) contain some french words useful for people (¯\_(ツ)_/¯) but usuless in fluentd.
I can't find a way to remove them (or integrate I don't really care) in `time_format`.
Ideally, we should not modify the log format (so we must keep `Le xx/xx/xxxx a xx:xx:xx`).
Would you know a way to achieve this goal?

Regards.

**Comment by cosmo0920** [comment]
Could you check that your time_format is valid?

I think that `%d/%m/%Y a %H:%M:%S` should be used in time_format.

BTW, Fluentd regular expression can test on https://fluentular.herokuapp.com/.
And your log can be parsed:
https://fluentular.herokuapp.com/parse?regexp=%28%3F%3Ctime%3E%5Cd%7B2%7D%5C%2F%5Cd%7B2%7D%5C%2F%5Cd%7B4%7D+a+%5Cd%7B2%7D%3A%5Cd%7B2%7D%3A%5Cd%7B2%7D%29%5C%7C%28%3F%3Caction%3Etrsp%3A%5Cd%7B3%7D+-+%5Ba-zA-Z%5D*%3A+*%5Ba-zA-Z%5D*%29%5C%7C%28%3F%3Csrc%3E%5B%5E%5C%7C%5D%2B%29%5C%7C%28%3F%3Cmessage%3E.*%29&input=Le+++06%2F02%2F2019+a+02%3A31%3A22%7Ctrsp%3A253+-+login%3A++++++++++%7C++1.1.1.1%7C-+from%3A+++++++++++%7C+Login+admin%3A+%5Bmaster69%5D&time_format=%25d%2F%25m%2F%25Y+a+%25H%3A%25M%3A%25S

But we do not use issue as user forum.
So, I close this.
