### ISSUE TITLE
Can source collection be paused?

### ISSUE THREAD

**Issue by jcantrill** [fluent/fluentd#2326]
We utilize the in_tail plugin and file buffering.  We have seen issues where the buffer becomes corrupt and the only thing that seems to be the cause is possible lack of disk space to fully write the buffer chunks.  Is it possible to tell in_tail(or other input) plugin to 'pause' collection while allowing output plugins to continue to push?  Ideally, we could implement a plugin or service to monitor space to pause collection until more space exists to buffer.

**Comment by repeatedly** [comment]
in_tail plugin pauses collecting logs when buffer raises overflow.

https://github.com/fluent/fluentd/blob/eae8611f6dd89e1b84c5424dd5e0a5536378f3a6/lib/fluent/plugin/in_tail.rb#L403

Is your buffer setting larger than actual disk space?
Or fluentd behavuour is something wrong?

**Comment by jcantrill** [comment]
> in_tail plugin pauses collecting logs when buffer raises overflow.
> 
> [fluentd/lib/fluent/plugin/in_tail.rb](https://github.com/fluent/fluentd/blob/eae8611f6dd89e1b84c5424dd5e0a5536378f3a6/lib/fluent/plugin/in_tail.rb#L403)
> 
> Line 403 in [eae8611](/fluent/fluentd/commit/eae8611f6dd89e1b84c5424dd5e0a5536378f3a6)
> 
>  rescue Fluent::Plugin::Buffer::BufferOverflowError 
> Is your buffer setting larger than actual disk space?
This is immaterial in relation to the question.  Buffer settings are static and assuming output is possible but unable to push faster then input, entries flow to disk to be buffered.  I don't know what causes a `BufferOverflowError` but if it were possible to pause input based on a threshold being exceeded, this would mitigate the space problem.

> Or fluentd behavuour is something wrong?

We have several cases where fluentd is unable to unpack buffers with issues like:
```
2019-03-05 13:50:06 +0100 [warn]: temporarily failed to flush the buffer. next_retry=2019-03-05 13:50:06 +0100 error_class="MessagePack::UnknownExtTypeError" error="unexpected extension type" plugin_id="object:3fee30089cfc"
  2019-03-05 13:50:06 +0100 [warn]: /usr/share/gems/gems/fluentd-0.12.43/lib/fluent/buffer.rb:123:in `each'
```
and 
```
[warn]: temporarily failed to flush the buffer. next_retry=2018-11-05 14:40:27 -0500 error_class="Elasticsearch::Transport::Transport::Errors::InternalServerError" error="[500] {\"error\":{\"root_cause\":[{\"type\":\"json_parse_exception\",\"reason\":\"Invalid UTF-8 start byte 0x92\\n at [Source: [B@53d93e65; line: 1, column: 179]\"}],\"type\":\"json_parse_exception\",\"reason\":\"Invalid UTF-8 start byte 0x92\\n at [Source: [B@53d93e65; line: 1, column: 179]\"},\"status\":500}" plugin_id="object:3f9728980be4
```
which we believe to be related to the disk space.

**Comment by jcantrill** [comment]
@repeatedly I don't think my question was ever answered.  Does `Fluent::Plugin::Buffer::BufferOverflowError` occur when there is not sufficient disk space?

**Comment by repeatedly** [comment]
> Fluent::Plugin::Buffer::BufferOverflowError occur when there is not sufficient disk space?

Yes. See https://github.com/fluent/fluentd/blob/3566901ab4a00e0168b4a6078153dde85601fc53/lib/fluent/plugin/buffer/file_chunk.rb#L283
But the problem seems you use fluentd v0.12 with wrong data. 
I'm not sure what happens but your buffer contains v1 data, v1 uses ext type for event time, in buffers.

**Comment by jcantrill** [comment]
> But the problem seems you use fluentd v0.12 with wrong data.
> I'm not sure what happens but your buffer contains v1 data, v1 uses ext type for event time, in buffers.
I'm not sure what this means unless you are referring to buffering format of v0.12 versus v1.  I don't know how that is even possible given we have used v0.12 for the last several years in up to 6 or more of our releases and we are seeing this issue.  We have only recently embraced v1 which has yet be released for use by our customers.

The particular error reference is a new one to us.  The one we have seen typically is `Invalid UTF-8 start byte 0x92` which we  believe is related to space and once occurs blocks any message processing unless we utilize error and retry queues to filter out the bad records.

**Comment by jcantrill** [comment]
@repeatedly this is the issue we saw in 0.12 for which we wrote a utility otherwise fluent was stuck, continually trying to flush the same buffer:

```
[warn]: temporarily failed to flush the buffer. next_retry=2018-11-05 14:40:27 -0500 error_class="Elasticsearch::Transport::Transport::Errors::InternalServerError" error="[500] {\"error\":{\"root_cause\":[{\"type\":\"json_parse_exception\",\"reason\":\"Invalid UTF-8 start byte 0x92\\n at [Source: [B@53d93e65; line: 1, column: 179]\"}],\"type\":\"json_parse_exception\",\"reason\":\"Invalid UTF-8 start byte 0x92\\n at [Source: [B@53d93e65; line: 1, column: 179]\"},\"status\":500}" plugin_id="object:3f9728980be4````

I believe it to be related to running out of disk and the buffer only being able to partially write a record.

**Comment by jcantrill** [comment]
closing as stale
