### ISSUE TITLE
Fluentd failed to expand record.to_json

### ISSUE THREAD

**Issue by mdnix** [fluent/fluentd#2328]
Fluentd record transformer drops message when transforming it to json.

- Error message:
`2019-03-08 15:42:47 +0000 [warn]: #0 dump an error event: error_class=RuntimeError error="failed to expand `record.to_json` : error = \"\\xC3\" from ASCII-8BIT to UTF-8" location="/opt/app-root/src/gems/fluentd-1.2.5/lib/fluent/plugin/filter_record_transformer.rb:310:in `rescue in expand'" `

- fluentd version: fluentd 1.2.5
- Environment information:
	- Operating system: Red Hat Enterprise Linux Server release 7.5 (Maipo)
	- Kernel version:  3.10.0-862.14.4.el7.x86_64

- Your configuration:
```
<filter **go-api-dev**>
  @type record_transformer
  enable_ruby 
  renew_record 
  <record>
    message ${record.to_json}
  </record>
</filter>
```

**Comment by repeatedly** [comment]
This problem? https://docs.fluentd.org/v1.0/articles/faq#i-got-enconding-error-inside-plugin.-how-to-fix-it?

**Comment by ganmacs** [comment]
No response from the author for a long time. i'm closing
