### ISSUE TITLE
Fleuntd got mad after installing falco

### ISSUE THREAD

**Issue by Ashraf-Hassan** [fluent/fluentd#2333]
Check [CONTRIBUTING guideline](https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md) first and here is the list to help us investigate the problem.

- fluentd or td-agent version: v.2.3.2
- Environment information:
	- Operating system: `cat /etc/os-release` Centos7
	- Kernel version: `uname -r` : 3.10.0-957.5.1.el7.x86_64
- Your configuration:
I have a Kubernetes cluster on 3 masters, 2 infra nodes and 4 workers.
- Your problem explanation. If you have an error logs, write it together
I installed rge elasticsearch using the following helm command:

`helm install --name elasticsearch incubator/elasticsearch -f elsaticsearch-values.yaml --namespace monitoring-logging`
 
 where the config file has the info about the nodeselector and the persistent storage.
The I installed fluentd using the command : 

 `helm install --name fleuntd stable/fluentd-elasticsearch --namespace=monitoring-logging`

And this setup was working perfectly for days,
Then I installed falco using helm, where all of the sudden the cluster went mad, so I uninstalled flaco, and then fluentd, and the elastic search, then deleted all the pvc and pv, and deleted on every single the node 
the following: 

`rm -rf /var/log/fluentd*`

Then on every single node I ran:

`docker system prune`

But when I install the EFK again still find:
1- Old logstash's there once I reinstall the fluentd.
2- The cluster goes mad again the es-client keep crashing as if the falco is still there, honestly I do not want the falco, so I can I do proper uninstall and get back to the old state?

**Comment by repeatedly** [comment]
> so I can I do proper uninstall and get back to the old state?

I'm not sure... if the root cause is falco, it should back to nomarl.

**Comment by Ashraf-Hassan** [comment]
But once I install the fleuntd after installing the elasticshare I can see it is still trying to push a huge amount of pretty old logstash, rather than just starting fresh to send new data only , and I do not know from where it is getting these old logstash?!! I how can I make a full cleanup?!

**Comment by repeatedly** [comment]
>  I can see it is still trying to push a huge amount of pretty old logstash, 

If you have a problem with logstash, elastic community is better.

> how can I make a full cleanup?!

I'm not sure your cluster management but create new cluster doesn't work?

**Comment by Ashraf-Hassan** [comment]
I installed fluent-bit which is lighter and better, so we can close the case.

**Comment by repeatedly** [comment]
Does it means fluent-bit works with falco?
