### ISSUE TITLE
http_in plugin cors_allow_origins be able to specify wildcard subdomains

### ISSUE THREAD

**Issue by hirokikana** [fluent/fluentd#2336]
`cors_allow_origins` is support * or the exact matching. HTTP request from many subdomain case is need to add many domain in `cors_allow_origins` setting.

I want to specify wildcard subdomain as a solution. But, according to `Access-Control-Allow-Origin` header specification unusable( https://www.w3.org/TR/cors/#access-control-allow-origin-response-header ).

May I add this feature? If allowed, I can create PullRequest.

**Comment by repeatedly** [comment]
> May I add this feature? If allowed, I can create PullRequest.

yes please :)

**Comment by repeatedly** [comment]
Patch is merged. Forgot to close.
