### ISSUE TITLE
Td-agent 'too many open files' after extended time, Windows

### ISSUE THREAD

**Issue by krankin** [fluent/fluentd#2342]
### fluentd or td-agent version.

```fluentd-1.0.2```

### Environment information:
	- Operating system: `Windows 10`

### Your configuration
 ``` <source>
    @type tcp
    tag "tcp.XXXX"
    format none
    port 5170
    bind "0.0.0.0"
    <parse>
      @type none
    </parse>
  </source>

  <filter tcp.**>
    @type record_transformer
    enable_ruby 
    <record>
      message ${record["message"].to_s.encode('UTF-8', invalid: :replace, undef: :replace, replace: "??")}
    </record>
  </filter>

  <match tcp.**>
    @type azureeventhubs_buffered
    connection_string "MyEndpoint"
    hub_name "MyHub"
    batch true
    max_batch_size 10
    print_records false
    include_tag true
    include_time true
    <buffer>
      @type "file"
      path "c:\\opt\\td-agent\\etc\\td-agent\\td-agent.log"
      chunk_limit_records 100
      flush_at_shutdown true
      flush_mode interval
      flush_interval 1
      flush_thread_count 16
      flush_thread_interval 1
      flush_thread_burst_interval 1
      retry_forever true
      retry_type exponential_backoff
    </buffer>
  </match>
```
### Issue
We've deployed td-agent to a number of windows computers in our environment  as a service
[following this guide](https://docs.fluentd.org/v1.0/articles/install-by-msi). 

and after running for an extended period of time, we start to see this show up in the logs.

```
2019-03-19 11:35:17 -0400 [warn]: #0 suppressed same stacktrace
2019-03-19 11:35:17 -0400 [error]: #0 unexpected error on reading data host="10.225.91.61" port=49159 error_class=Fluent::Plugin::Buffer::BufferOverflowError error="can't create buffer file for c:\\\\opt\\\\td-agent\\\\etc\\\\td-agent\\\\td-agent.log/buffer.*.log. Stop creating buffer files: error = Too many open files @ rb_sysopen - c:\\\\opt\\\\td-agent\\\\etc\\\\td-agent\\\\td-agent.log/buffer.b58474408f953c81ca4ad09d898bab7c4.log"
```
When this happens Fluentd sends the same messages to destination over and over until the service is restarted, messages from our source are no longer buffered (but are accepted) and thus we lose data. 

### Workaround
Restarting the service causes fluent to begin operating again. We have scheduled the service to restart on a periodic interval (every 24 hours).

**Comment by repeatedly** [comment]
What is the number of windows version of ulimit?

https://docs.fluentd.org/v1.0/articles/before-install#increase-max-#-of-file-descriptors

I assume you hit the process limit.

**Comment by krankin** [comment]
I assume I did too, but from what I [read](https://blogs.technet.microsoft.com/markrussinovich/2009/09/29/pushing-the-limits-of-windows-handles/) , that number is close to 16 million. We might get ~1 million messages a day on a high traffic box. My initial assumption is that the handles aren't being closed after Fluent sends messages from the file buffer. I'll try to test that assumption. 

The bigger concern I have is that when it gets in this state, our destination (Azure Eventhubs) receives the same message repeatedly. The messages arrive in Azure, but it causes a lot of noise and we'd really like it to be an "At least once + At most once" type of operation. I'm guessing that's a plugin issue and not fluentd.

**Comment by krankin** [comment]
I was looking through the docs and noticed that 1.1.3 introduces
`queued_chunks_limit_size`  
and says: 

> If you set smaller flush_interval, e.g. 1s, there are lots of small queued chunks in buffer. This is not good with file buffer because it consumes lots of fd resources when output destination has a problem. This parameter mitigates such situations.

would upgrading to > 1.1.3 help with my specific issue?

**Comment by repeatedly** [comment]
If the problem is the number of queued chunks, it helps the situation.
Since v1.3.0, the default value is `flush_thread_count`: https://github.com/fluent/fluentd/blob/master/CHANGELOG.md#release-v130---20181110

**Comment by cosmo0920** [comment]
Ruby is built with C runtime library on Windows.

rb_sysopen uses [`_open`](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/open-wopen?view=vs-2019) which is one of the low level I/O function in C runtime.

MSDN says that low level I/O function's file open limit is 8192.

> C run-time I/O now supports up to 8,192 files open simultaneously at the low I/O level. This level includes files opened and accessed using the _open, _read, and _write family of I/O functions. 

ref: https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/setmaxstdio?view=vs-2019

I guess that Windows ulimit is 8192 under using C runtime circumstance.

**Comment by cosmo0920** [comment]
I checked opening file limit with the following code:

```c
#include <stdio.h>

int main(void)
{
  printf("maxstdio: %d\n", _getmaxstdio());
  _setmaxstdio(2048);
  printf("maxstdio: %d\n", _getmaxstdio());

  return 0;
}
```

```
PS> ./test.exe
maxstdio: 512
maxstdio: 2048
```

Windows default ulimit(opening file limit) is 512.
