### ISSUE TITLE
Issue in parsing csv

### ISSUE THREAD

**Issue by amitdhawan** [fluent/fluentd#2344]
Check [CONTRIBUTING guideline](https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md) first and here is the list to help us investigate the problem.

- fluentd or td-agent version.
td-agent
- Environment information:
	- Operating system: `cat /etc/os-release`
NAME="Ubuntu"
VERSION="16.04.5 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.5 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
	- Kernel version: `uname -r`
4.4.0-1077-aws

- Your configuration

- Your problem explanation. If you have an error logs, write it together.

I have an CSV with headers and space separated values.Below is the example if input CSV i receive in s3 input plugin as gz file.
```
#Fields: timestamp time-taken c-ip filesize s-ip s-port sc-status sc-bytes cs-method cs-uri-stem - rs-duration rs-bytes c-referrer c-user-agent customer-id x-ec_custom-1
1545332400 0 122.181.245.110 - 151.195.211.91 80 TCP_HIT/304 289 GET http://google.com - 0 877 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3642.0 Safari/537.36" 6849 "REF: http://yahoo.com ORG: -" 
1545332400 0 33.30.14.37 0 192.16.15.206 443 TCP_HIT/200 328 GET http://google.com - 0 1608 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:64.0) Gecko/20100101 Firefox/64.0" 6849 "REF: http://yahoo.com ORG: -"
```

Below is my source plugin in conf file:-

```
<source>
  @type s3
  @log_level debug
  s3_bucket bucketname
  s3_region us-east-1
  format csv
  <parse>
    @type csv
    delimiter (' ')
    keys timestamp,time-taken,c-ip,filesize,s-ip,s-port,sc-status,sc-bytes,cs-method,cs-uri-stem,-,rs-duration,rs-bytes,c-referrer,c-user-agent,customer-id,x-ec_custom-1
    #time_key timestamp
  </parse>
  <assume_role_credentials>
    role_arn  myarn
    role_session_name mysession
  </assume_role_credentials>
  <sqs>
    queue_name fluentd_queue
  </sqs>
</source>
```

How can i parse the above CSV? Currently it gives me parse errors as the above csv has headers.

**Comment by amitdhawan** [comment]
@repeatedly can u help?

**Comment by repeatedly** [comment]
`delimiter (' ')` means delimiter is `(' ')`, not ` `.
Is it intended?
BTW, parser plugin doesn't have skipping first N lines feature so if you want to do it, need to extend s3 input plugin on your side or send a PR to s3 plugin.

**Comment by amitdhawan** [comment]
Nopes I intenteded to provide space as delimiter.

So what should be delimiter for that?

Sure I can give it a shot to write the skip option in s3 plugin

**Comment by amitdhawan** [comment]
Should there be not a csv parser that parses the headers too. I can see the same functionality in tools like logstash.
