### ISSUE TITLE
Parser filter plugin not working

### ISSUE THREAD

**Issue by amitdhawan** [fluent/fluentd#2345]
Check [CONTRIBUTING guideline](https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md) first and here is the list to help us investigate the problem.

- fluentd or td-agent version.
`td-agent 1.3.3`
- Environment information:
	- Operating system: `cat /etc/os-release`
        ```
        NAME="Ubuntu"
        VERSION="16.04.5 LTS (Xenial Xerus)"
        ID=ubuntu
        ID_LIKE=debian
        PRETTY_NAME="Ubuntu 16.04.5 LTS"
        VERSION_ID="16.04"
        HOME_URL="http://www.ubuntu.com/"
        SUPPORT_URL="http://help.ubuntu.com/"
        BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
        VERSION_CODENAME=xenial
        UBUNTU_CODENAME=xenial
        ```
	- Kernel version: `uname -r`
        ```
        4.4.0-1077-aws
        ```
- Your configuration
- Your problem explanation. If you have an error logs, write it together.
Im using filter_parser plugin in my conf file as below:-

```
<filter input.s3>
 @type parser
 key_name message
 remove_key_name_field true
  <parse>
   @type regexp
   expression /^?<timestamp>[^ ]*) [^ ]* [^ ]* [^ ]* [^ ]* [^ ]* [^ ]* [^ ]* [^ ]* (?<url>[^ ]*) [^ ]* [^ ]* [^ ]* [^ ]* (?<platform>".+") [^ ]* (?<ref>".+")$/
    time_format %d/%b/%Y:%H:%M:%S %z
  </parse>
</filter>
```

Now, when i restart td-agent by below command i get error in command out put.

`sudo /etc/init.d/td-agent restart`
`Error:- [....] Restarting td-agent (via systemctl): td-agent.serviceJob for td-agent.service failed because the control process exited with error code. See "systemctl status td-agent.service" and "journalctl -xe" for details.`

My conf file is correct as i can see the parse succeeds in the log file of td agent as below:-

```
2019-03-24 11:53:16 +0000 [info]: parsing config file is succeeded path="/etc/td-agent/td-agent.conf"

```

Also, when i try to install the filter parser for older fluentd version that is from v0.12 (td-agent2, it seems to work and gives me error like format field is required which makes sense as the td-agentv3 doesn't have any format paramater.

When i remove this filter plugin everything works for me and the restart is successful.

It seems like the parser plugin for td-agentv3 is not working or detected by td-agent for me. Any guidance will be super helpfule for me.

**Comment by amitdhawan** [comment]
@repeatedly you seem to be a frequent contributor to this repo any ide u can help me on this.

**Comment by repeatedly** [comment]
Please paste entire fluentd/td-agent log.

**Comment by amitdhawan** [comment]
This is the only line that gets printed in log many times.Thats why I didn't pasted the repetition.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

 
Amit Dhawan
Lead Software Engineer
Monotype Solutions India Pvt. Ltd.
Fourth Floor - Tower B, Prius Universal Plot A-3, 4 & 5, Sector -125
Noida 
201301
Phone +91  9953936137
Our Brand Family
​
Monotype.com
Olapic.com

**Comment by amitdhawan** [comment]
@repeatedly we can do one thing, you can send me the config file which works for you and I can check the same on my machine

**Comment by repeatedly** [comment]
> This is the only line that gets printed in log many times

Which log? systemd or /var/log/td-agent/td-agent.log?

**Comment by amitdhawan** [comment]
/var/log/td-agent/td-agent.log

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

 
Amit Dhawan
Lead Software Engineer
Monotype Solutions India Pvt. Ltd.
Fourth Floor - Tower B, Prius Universal Plot A-3, 4 & 5, Sector -125
Noida 
201301
Phone +91  9953936137
Our Brand Family
​
Monotype.com
Olapic.com

**Comment by repeatedly** [comment]
Try https://docs.fluentd.org/v1.0/articles/trouble-shooting#check-uncaught-logs

**Comment by amitdhawan** [comment]
Stiil the same. I can see only 
```
2019-03-24 11:53:16 +0000 [info]: parsing config file is succeeded path="/etc/td-agent/td-agent.conf"
```

Can you try this filter at ur end using td-agentv3?

**Comment by amitdhawan** [comment]
It isn't working from me on ubuntu neither i see the logs of what the problem is.

**Comment by amitdhawan** [comment]
Below is the output for systemctl status td-agent.service

```
d-agent.service - td-agent: Fluentd based data collector for Treasure Data
   Loaded: loaded (/lib/systemd/system/td-agent.service; disabled; vendor preset: enabled)
   Active: failed (Result: start-limit-hit) since Sun 2019-03-24 16:36:19 UTC; 37s ago
     Docs: https://docs.treasuredata.com/articles/td-agent
  Process: 8951 ExecStop=/bin/kill -TERM ${MAINPID} (code=exited, status=0/SUCCESS)
  Process: 9419 ExecStart=/opt/td-agent/embedded/bin/fluentd --log /var/log/td-agent/td-agent.log --daemon /var/run/td-agent/td-agent.pid $TD_AGENT_OPTIONS (code=exited, status=1/FAILURE)
 Main PID: 7253 (code=exited, status=0/SUCCESS)
```

**Comment by amitdhawan** [comment]
I got the problem and fixed it.

was missing opening braces in regex
   expression /^?<timestamp>[^ ]*) [^ ]* [^ ]* [^ ]* [^ ]* [^ ]* [^ ]* [^ ]* [^ ]* (?<url>[^ ]*) [^ ]* [^ ]* [^ ]* [^ ]* (?<platform>".+") [^ ]* (?<ref>".+")$/

should be

/^(?<timestamp>[^ ]*)

**Comment by amitdhawan** [comment]
But the logs were not at all supportive in this case and i spent a day debugging this scenario,

**Comment by amitdhawan** [comment]
I was able to get the error log when i ran the below command

```
sudo /etc/init.d/td-agent force-reload
```

**Comment by repeatedly** [comment]
I tested your config and jornald has proper logs.

```
-- Logs begin at Wed 2016-08-10 09:25:35 PDT, end at Sun 2019-03-24 12:31:23 PDT. --
Mar 24 12:31:20 ubuntu systemd[1]: Stopped td-agent: Fluentd based data collector for Treasure Data.
-- Subject: Unit td-agent.service has finished shutting down
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit td-agent.service has finished shutting down.
Mar 24 12:31:20 ubuntu systemd[1]: Starting td-agent: Fluentd based data collector for Treasure Data...
-- Subject: Unit td-agent.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit td-agent.service has begun starting up.
Mar 24 12:31:20 ubuntu fluentd[34156]: /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.3.3/lib/fluent/config/types.rb:84:in `initialize': unmatched close parenthesis: /^?<timestamp>[^ ]*) [^ ]* [^ ]* [^ ]* [^ ]* [^ ]* [^ ]* [^ ]* [^ ]* (?<url>[^ ]*) [^ ]* [^ ]* [^ ]* [^ ]* (?<platform>".+") [^ ]* (?<ref>".+")$/ (RegexpError)
Mar 24 12:31:20 ubuntu fluentd[34156]:         from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.3.3/lib/fluent/config/types.rb:84:in `compile'
```

systemd captures fluentd stdout/stderr logs. Your journald didn't have these logs?

**Comment by amitdhawan** [comment]
Yes, it didn't had. Any idea why they were missing?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

 
Amit Dhawan
Lead Software Engineer
Monotype Solutions India Pvt. Ltd.
Fourth Floor - Tower B, Prius Universal Plot A-3, 4 & 5, Sector -125
Noida 
201301
Phone +91  9953936137
Our Brand Family
​
Monotype.com
Olapic.com

**Comment by repeatedly** [comment]
I'm not sure because my systemd got logs correctly with td-agent 3.3.0 and ubuntu 16.04 combo.
Maybe, your setup or systemd setting is something wrong.
Testing with vanilla box is good for investigation or asking it to systemd community is better.

1. setup OS. No install additional compoent
1. install td-agent
2. edit config with above invalid regexp
3. sudo systemctl restart td-agent.service
4. journalctl -xe -u td-agent.service

This is my step to get above logs.
BTW, this is not fluentd core issue and this doesn't follow contribution guide, so closed.

**Comment by amitdhawan** [comment]
I think the only difference in my case is I start fluentd d with init.d/td-agent start. Will that be a d case not showing me logs?
