### ISSUE TITLE
[Kubernetes] Provide way for in_tail plugin relay on container state

### ISSUE THREAD

**Issue by janario** [fluent/fluentd#2349]
- Environment information:
	- Kubernetes on EKS
	- in_tail > kubernetes metadata > cloud watch logs

We are collecting logs from the container using the path `/var/log/containers/*my-app*.log`
When a pod is deleted or a log rotation happens the `in_tail` plugin detects as expected

The problem is, if the pod is restarted, failed or completed(job) the logs still there but it won't have no more data. So in_tail will open an stream and leave it there forever

I was going to try the option [limit_recently_modified](https://docs.fluentd.org/v1.0/articles/in_tail#limit_recently_modified) expecting that a file that is stopped for a while probably is done for some of the states

But even with it, it will just mark the file to be closed on the shutdown of fluentd
* [expand_paths](https://github.com/fluent/fluentd/blob/master/lib/fluent/plugin/in_tail.rb#L227) won't return the file when it gets old
* marked as [unwatched](https://github.com/fluent/fluentd/blob/master/lib/fluent/plugin/in_tail.rb#L263)
* but the [stop](https://github.com/fluent/fluentd/blob/master/lib/fluent/plugin/in_tail.rb#L266) is not `immediate`, leaving the file open `detach_watcher_after_rotate_wait` until the pod is removed in that case

At some point because of that and much other files, it will start to show `Too many open file`

---

I was thinking

It could work in stages and validating the kubernetes pod status, those stages could be saved in disk
* `to_consume` (files that were never started to be consumed)
 * if the file was never consumed, even if the container is in the state {failed, completed, restarted}. Send it to in_tail marking as `consuming`.
 * if the file consume was started, checks the state of the container, {failed, completed, restarted} should finish the current stream and close it marking as consumed (similar to `open_on_every_update`)

**Comment by repeatedly** [comment]
> It could work in stages and validating the kubernetes pod status, those stages could be saved in disk

So your suggestion is in_tail access to k8s to check log file status?

**Comment by janario** [comment]
No, in_tail is plugin and it works fine for its purpose. I don't think it should have access to k8s

Maybe a way to extend it or a new plugin made for k8s that integrates with it


```yaml
<source>
      @type kubernetes
      selectors ["app=my-app"]
...

```

Internally, k8s access, k8s metadata and pushes to in_tail which files it should be read
