### ISSUE TITLE
Fluentd buffer can loose some logs even with graceful shutdown

### ISSUE THREAD

**Issue by janario** [fluent/fluentd#2351]
- fluentd
- Environment information:
	- Kubernetes
	- fluentd pod, in_tail > kubernetes metadata > cloud watch logs [buffer]

We were validating fluentd, changes in case we have a config change in the middle of the day

To test that we've created a pod that will generate 10k lines of logs, and fluentd that will collect it

my buffer conf
```
<buffer log_group_name, log_stream_name>
      @type file
      path /var/log/logs-buffer/cw.*.buffer

      flush_interval 5s
      chunk_limit_size 512k
      queued_chunks_limit_size 6
      overflow_action block
    </buffer>
```

So while the generator is generating, when fluentd had some buffer files, I deleted the pod
```
ls -la
drwxr-xr-x 19 root root 131072 Mar 28 01:00 ..
-rw-r--r--  1 root root 508754 Mar 28 01:00 cw.b5851c3dd118095db1c05fa8c8b7f0c34.buffer
-rw-r--r--  1 root root    145 Mar 28 01:00 cw.b5851c3dd118095db1c05fa8c8b7f0c34.buffer.meta
-rw-r--r--  1 root root 131803 Mar 28 01:00 cw.b5851c3e205603cc9577745ec032b7874.buffer
-rw-r--r--  1 root root    143 Mar 28 01:00 cw.b5851c3e205603cc9577745ec032b7874.buffer.meta
-rw-r--r--  1 root root  91651 Mar 28 01:00 cw.q5851c3d7740e42ec9d11b38d8c76922e.buffer
-rw-r--r--  1 root root    143 Mar 28 01:00 cw.q5851c3d7740e42ec9d11b38d8c76922e.buffer.meta
-rw-r--r--  1 root root 508305 Mar 28 01:00 cw.q5851c3dcf870e8b755b88e7095e51770.buffer
-rw-r--r--  1 root root    145 Mar 28 01:00 cw.q5851c3dcf870e8b755b88e7095e51770.buffer.meta
-rw-r--r--  1 root root 499311 Mar 28 01:00 cw.q5851c3dd2ab0debbeda2ce5a4e52399e.buffer
-rw-r--r--  1 root root    145 Mar 28 01:00 cw.q5851c3dd2ab0debbeda2ce5a4e52399e.buffer.meta
-rw-r--r--  1 root root 501240 Mar 28 01:00 cw.q5851c3e03509854e1dbdf615e20074f1.buffer
-rw-r--r--  1 root root    145 Mar 28 01:00 cw.q5851c3e03509854e1dbdf615e20074f1.buffer.meta
root@logs-77444ddd75-smpqc:/home/fluent# ls -la /var/log/logs-memory-break-4command terminated with exit code 137
janario@ubuntu:~$ kubectl -n janario-logs exec -it logs-77444ddd75-smpqc bash

ls -la
-rw-r--r--  1 root root 508754 Mar 28 01:00 cw.b5851c3dd118095db1c05fa8c8b7f0c34.buffer
-rw-r--r--  1 root root    145 Mar 28 01:00 cw.b5851c3dd118095db1c05fa8c8b7f0c34.buffer.meta
```

After the restart it consumes all the logs, but it remained 2 files
* -rw-r--r--  1 root root 508754 Mar 28 01:00 cw.b5851c3dd118095db1c05fa8c8b7f0c34.buffer
* -rw-r--r--  1 root root    145 Mar 28 01:00 cw.b5851c3dd118095db1c05fa8c8b7f0c34.buffer.meta

Looking at cw logs the stream has `9544` lines and the left file `469` (13 more)

Is there a way to know why it doesn't collect only this file?
Or any config to avoid loosing logs?

**Comment by repeatedly** [comment]
Hmm... that's weird. With `debug` log level. still no buffer related message in the log?

**Comment by repeatedly** [comment]
> Or any config to avoid loosing logs?

How about setting `flush_at_shutdown true` in the buffer configuration?

**Comment by janario** [comment]
I've tried and it worked as expected, thanks

---
just to make sure, when the graceful shutdown starts, in_tail stops to push logs and just the buffer will finish the flush? or in_tail keeps pushing it?

I'm just worried in cases where the flush takes longer than the grace period (I know we could increase the grace period, but if in_tail just stops that should be fine)

**Comment by ganmacs** [comment]
>  when the graceful shutdown starts, in_tail stops to push logs and just the buffer will finish the flush? or in_tail keeps pushing it?

in_tail should stop first. 

BTW seems to be resolved. I'm closing
