### ISSUE TITLE
Restrict fluentd to send more than 1000 fields as the output

### ISSUE THREAD

**Issue by Priyanrekha** [fluent/fluentd#2357]
Check [CONTRIBUTING guideline](https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md) first and here is the list to help us investigate the problem.

- fluentd or td-agent version.
- Environment information:
	- Operating system: `cat /etc/os-release`
	- Kernel version: `uname -r`
- Your configuration
- How do I restrict fluentd from sending more than 1000 fields as the output.Currently we have 
Fluentd that is running across several machines,but we would like to restrict the number of fields that it sends.

**Comment by ganmacs** [comment]
Right. The requirement is too specific so I don't think we will support such kind of feature.
the best solution to achieve what you want to do is creating your own simple plugin to do it.
