### ISSUE TITLE
out_foward: Send duplicate events repeatedly.

### ISSUE THREAD

**Issue by u-shunya** [fluent/fluentd#2363]
Environment information:
* fluentd v1.3.3 (td-agent v3.3.0)
* Configuration pattern: Each service > Aggregator-A (4 node) > Aggregator-B (2 node)

I found that out_foward plugin send duplicate events repeatedly in a specific situation.
It occurs in the following scenarios:
1. Stop the all Aggregator-A by `kill -9`.
2. All Aggregator-A are detached by the Each service(forwarding clients).
(Sending Logs is going to retried with exponential backoff)
3. Start all Aggregator-A. (recover forwarding targets)
4. Events forwarded from Aggregator-A to Aggregator-B are repeatedly sent. In short, it is duplicated.

Just before, the following log was on Aggregator-B.
```
emit transaction failed: error_class=NoMethodError error="undefined method `unstaged?' for nil:NilClass" location="/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.3.3/lib/fluent/plugin/buffer.rb:343:in `block (2 levels) in write'" tag="myservice.foo.bar"
```

After that, a large number of buffer files are created under the buffer directory, and finally a `Too many open files` error occurs.
The original log volume is about 10 MB, but 60 GB of files were sent to the Aggregator-B.

**Comment by repeatedly** [comment]
> Events forwarded from Aggregator-A to Aggregator-B are repeatedly sent. In short, it is duplicated.

Does this mean, you use `required_ack_response true` and Aggregator-B returns always error to A by above error, right?
So the root cause is `NoMethodError` on B, right?
To reproduce the problem, we need to identify proper scenario.

**Comment by ganmacs** [comment]
no response from the author for a long time. i'm closing. feel free to notify us if there is more info.
