### ISSUE TITLE
What is a recommended file buffer configuration?

### ISSUE THREAD

**Issue by max-rocket-internet** [fluent/fluentd#2365]
fluentd: `1.3.3`
fluent-plugin-cloudwatch-logs: `0.7.3`
docker image: `fluent/fluentd-kubernetes-daemonset:v1.3-debian-cloudwatch-1`

We currently trying to reduce memory usage by configuring a file buffer. I've read the [doc](https://docs.fluentd.org/v1.0/articles/buffer-section) and attempted to emulate settings from [GKE](https://github.com/GoogleCloudPlatform/google-fluentd/blob/master/templates/etc/td-agent/td-agent.conf) and ended up with this:

```
    <match **>
      <buffer>
        @type file
        flush_thread_count 4
        flush_interval 5s
        chunk_limit_size 1m
        retry_wait 5
        retry_max_times 5
        retry_forever false
        retry_timeout 2h
        retry_exponential_backoff_base 2
        path /var/log/fluentd/buffer
      </buffer>

      @type cloudwatch_logs
      @id out_cloudwatch_logs
      @log_level "#{ENV['LOG_LEVEL']}"
      aws_key_id 
...
```

But fluentd created 1000s of files in `/var/log/fluentd/buffer/buffer.xxx.log`, never deleted them and then hit open file limit:

```
2019-04-03 15:28:09 +0000 [warn]: #0 emit transaction failed: error_class=Fluent::Plugin::Buffer::BufferOverflowError error="can't create buffer file for /var/log/fluentd/buffer/buffer.*.log. Stop creating buffer files: error = Too many open files @ rb_sysopen - /var/log/fluentd/buffer/buffer.b585a1e6a6b788d77a41fd25e3934e68e.log" location="/fluentd/vendor/bundle/ruby/2.3.0/gems/fluentd-1.3.3/lib/fluent/plugin/buffer/file_chunk.rb:283:in `rescue in create_new_chunk'" tag="kubernetes.var.log.containers.as01-prd01-integration-middleware-frontend-c994657bf-4hlsl_default_app-be557c891d8f0dd3dc17bc8994e6e5b871a3a416f6f2c6d3e6d7e8a658434f5a.log"
```

And then stopped sending logs to cloudwatch.

What am I doing wrong here? If I set `total_limit_size` to 500MB, is that safe?

**Comment by max-rocket-internet** [comment]
It created 3.2GB of buffer files. I don't understand why it would create this sort of volume of files?

**Comment by repeatedly** [comment]
I'm not familiar with cloudwatch logs's import performance.
The import performance is faster than buffer growth?
No warning logs with `slow_flush_log_threshold 5s`?

**Comment by max-rocket-internet** [comment]
Thanks for the reply @repeatedly 

> I'm not familiar with cloudwatch logs's import performance.

We don't have any issues when running without the file buffer config though. i.e direct to cloudwatch logs. It just uses a lot of memory, about 1GB per k8s node. Log throughput is anywhere between 50-100k logs per minute. But then with the above file buffer configuration we get all the buffer files created.

Am I expecting too much? i.e. is 1G memory and using about 0.25-0.5 CPU cores normal?

> No warning logs with slow_flush_log_threshold 5s?

Never heard of this and it's not listed in the [buffer-section](https://docs.fluentd.org/v1.0/articles/buffer-section). I'll add it and see.

**Comment by repeatedly** [comment]
> But then with the above file buffer configuration we get all the buffer files created.

Hmm... IO read performance is good? file buffer increases the number of IO operation to maintain chunk metadata and chunk body.

> Never heard of this and it's not listed in the buffer-section. I'll add it and see.

This is output plugin parameter, not inside `<buffer>`.
We failed to migrate v0.12 document so I will add it to docs.

**Comment by repeatedly** [comment]
Ah, `slow_flush_log_threshold` is float type, not time.
So `5` or `5.0` is correct.

**Comment by max-rocket-internet** [comment]
> Ah, slow_flush_log_threshold is float type, not time.

OK I've set it to `slow_flush_log_threshold 5.0` and now I see these messages:

```
2019-04-04 11:54:13 +0000 [warn]: #0 [out_cloudwatch_logs] buffer flush took longer time than slow_flush_log_threshold: elapsed_time=21.882551135960966 slow_flush_log_threshold=5.0 plugin_id="out_cloudwatch_logs"
```

> We don't have any issues when running without the file buffer config though

This is wrong. I see a lot of these messages both with and without file buffer:

```
2019-04-04 11:32:43 +0000 [warn]: #0 emit transaction failed: error_class=Fluent::Plugin::Buffer::BufferOverflowError error="buffer space has too many data" location="/fluentd/vendor/bundle/ruby/2.3.0/gems/fluentd-1.3.3/lib/fluent/plugin/buffer.rb:269:in `write'" tag="kubernetes.var.log.containers.xxxxxx-78bc6d9c76-hpg4r_default_app-85e1921cc2778c94879c324f86a7c505796ce78487a5e267e8cb4a1a4b9e216b.log"
```

So I think perhaps fluentd simply can't keep up with the log volume at all. Would that be correct?

**Comment by max-rocket-internet** [comment]
> Hmm... IO read performance is good? file buffer increases the number of IO operation to maintain chunk metadata and chunk body.

There's no IO wait time for these hosts the fluentd pods are writing at about 5-7MB/s each. So I think that's not an issue

**Comment by max-rocket-internet** [comment]
I checked Graylog and there is about 500 messages/second per k8s node. It's running as a daemonset so one fluentd pod per node.

**Comment by max-rocket-internet** [comment]
Looking at [the limits of cloudwatch logs](https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/cloudwatch_limits_cwl.html), I think this is our bottleneck.

**Comment by max-rocket-internet** [comment]
I'm gonna close this since I'm pretty sure now it's not a config problem.
