### ISSUE TITLE
error_class=ArgumentError error="invalid value for Integer()

### ISSUE THREAD

**Issue by sandstonewater** [fluent/fluentd#2374]
Hi, i think i am also hitting this issue again with octet_count over tcp, using fluentd docker image: fluent/fluentd:v1.4-1

The in_syslog config is (i need to use a custom regex for non-standard syslog):

<source>
  @type syslog

  port 11011
  bind 0.0.0.0
  protocol_type tcp
  tag blah.syslog
  frame_type octet_count
  <parse>
    @type regexp
    expression /^(?<time>[^ ]+) (?<host>[^ ]*) (?<ident>[a-zA-Z0-9_\/\.\-]*)(?:\[(?<pid>[0-9]+)\])?(?:[^\:]*\:)? *(?<message>.*)$/
    time_key time
    time_type string
    time_format %Y-%m-%dT%H:%M:%S.%N%z 
    with_priority true
  </parse>
</source>

The incoming records are parsed properly:

2019-04-09 08:23:28.634910000 +0000 blah.syslog.err: {"host":"cic-3.domain.tld","ident":"swift-object-server","pid":"5128","message":"192.168.13.3/2 responded as unmounte"}

However the records are not validated, due to the below fluentd error:

2019-04-09 08:23:28 +0000 [error]: #0 unexpected error on reading data host="10.33.90.138" port=51570 error_class=ArgumentError error="invalid value for Integer(): \"d196 \""

Much appreciate your help on this issue!

**Comment by repeatedly** [comment]
Do you have reproducible step?

**Comment by sandstonewater** [comment]
Hi, yes this problem is reproducible. What information would you like me to collect??

**Comment by repeatedly** [comment]
Could you write reproducible step here with actual log/syslog example?

**Comment by sandstonewater** [comment]
Hi, i tried again with the following configuration using custom parse expression, and octet-count syslog is working now :)
Thanks,
Neil.

<source>
  @type syslog
  port {{lab_string}}11
  bind 0.0.0.0
  protocol_type tcp
  tag dc{{lab_string}}.openstack
  frame_type octet_count
  <parse>
    @type regexp
    expression /^(?<time>[^ ]+) (?<host>[^ ]*) (?<ident>[a-zA-Z0-9_\/\.\-]*)(?:\[(?<pid>[0-9]+)\])?(?:[^\:]*\:)? *(?<message>.*)$/
    time_key time
    time_type string
    time_format %Y-%m-%dT%H:%M:%S.%N%z 
    with_priority true
    keep_time_key true
  </parse>
</source>
