### ISSUE TITLE
Fluentd keeps on enqueuing all chunks in buffer

### ISSUE THREAD

**Issue by amitdhawan** [fluent/fluentd#2379]
Check CONTRIBUTING guideline first and here is the list to help us investigate the problem.

fluentd or td-agent version.
td-agent 1.3.3

Environment information:

Operating system: cat /etc/os-release
NAME="Ubuntu"
VERSION="16.04.5 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.5 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
Kernel version: uname -r
4.4.0-1077-aws
Your configuration

Your problem explanation. If you have an error logs, write it together.

Below is my config file:-

```
<source>
  @type s3
  s3_bucket testtemplatedata
  s3_region us-east-1
 @log_level error
 <assume_role_credentials>
     role_arn  arn:aws:iam::720991919452:role/Base-Role_webfontgenerator-preprod
     role_session_name fluentdSession
</assume_role_credentials>
  <sqs>
    queue_name fluentd_queue
  </sqs>
</source>

#<system>
#  process_name fluendpoc
#  <log>
#    format json
#    time_format %Y-%m-%d
#  </log>
#</system>
<filter input.s3>
 @type grep
  <regexp>
    key message
    pattern /1.css/
  </regexp>
</filter>

<filter input.s3>
 @type parser
 key_name message
 remove_key_name_field true
 <parse>
    @type regexp
    expression /^(?<timestamp>[^ ]*) [^ ]* [^ ]* [^ ]* [^ ]* [^ ]* [^ ]* [^ ]* [^ ]* (?<url>[^ ]*) [^ ]* [^ ]* [^ ]* [^ ]* "(?<platform>[^\"]*)" [^ ]* [^ ]* (?<ref>[^ ]*)/
    time_format %d/%b/%Y:%H:%M:%S %z
  </parse>
</filter>

<match input.s3>
 #<store>
 #  @type file
 #  path /var/log/td-agent/s3.log
 #</store>
# <store>
   @type kinesis_streams
   stream_name PageViewTrackingStream
   region us-east-1
   <assume_role_credentials>
     role_arn  arn:aws:iam::720991919452:role/Base-Role_webfontgenerator-preprod
     role_session_name kinesisSession
   </assume_role_credentials>
 #</store>
</match>
```

Im processing log files uploaded on S3 and pushing them to Kinesis stream.
For checking out Fluentd capabilities right now im running td-agent in AWS EC2 t2.micro instance.
Now, for log files containg 100 records or so Im getting the output logs in Kinesis.
But when i upload a log file of aroung 175MB gz format the fliuentd seems to behave unexpectedly and keeps on showing me the trace log as below

```
2019-04-11 18:22:25 +0000 [trace]: #0 fluent/log.rb:281:trace: enqueueing all chunks in buffer instance=69999571134220
```
<img width="1151" alt="Screen Shot 2019-04-11 at 11 45 16 PM" src="https://user-images.githubusercontent.com/14885126/55982105-ca0a0100-5cb5-11e9-862f-10eec0d7d5b3.png">

Please help.I cannot use fluentd in production if it cannot handle large files.

**Comment by amitdhawan** [comment]
@repeatedly any help suggestions?

**Comment by repeatedly** [comment]
> 2019-04-11 18:22:25 +0000 [trace]: #0 fluent/log.rb:281:trace: enqueueing all chunks in buffer instance=69999571134220

This is no problem because output plugin shows this message when you set trace level.

**Comment by amitdhawan** [comment]
Im not able to get the logs in Kinesis though, Will the S3 input plugin be able to parse a log file of size 4gb?

**Comment by repeatedly** [comment]
This is S3 plugin issue. Closed.

**Comment by Venture200** [comment]
Hey @amitdhawan did you find solution for this ?
@repeatedly I am also getting this issue

**Comment by daipom** [comment]
@Venture200 Does this happen with the latest `in_s3` ([fluent-plugin-s3](https://github.com/fluent/fluent-plugin-s3))?
If so, could you comment briefly about the situation in the following issue?

* https://github.com/fluent/fluent-plugin-s3/issues/271

Then, I will reopen the issue.

**Comment by Venture200** [comment]
Hello, @daipom 
No, I am using Elasticseach as backend. For other logs, I can see tracing logs but for specific log ID It only shows` enqueuing all chunks in buffer`

**Comment by daipom** [comment]
@Venture200 
Could you explain the situation on Q&A?

* https://github.com/fluent/fluentd/discussions/categories/q-a
