### ISSUE TITLE
Drop older ruby 2.1/2.2/2.3 support

### ISSUE THREAD

**Issue by repeatedly** [fluent/fluentd#2380]
Fluentd v1 now works on ruby 2.1 or later but it has several drawbacks.

- ruby 2.1/2.2 are dead version. ruby team doesn't maintain it.
- Need dig_rb gem for `dig` method: See https://github.com/fluent/fluentd/pull/2372

Removing 2.1/2.2 is good for the further development. td-agent and docker images use ruby 2.3 or later so it doesn't break popular environment.
However removing support without the transition period may break user environment. So support 2.1/2.2 until the end of 2019 is better.

UPDATE: Drop 2.3 together. See https://www.fluentd.org/blog/drop-schedule-announcement-in-2019

**Comment by henrich** [comment]
Thanks for opening this issue.
Maybe it's also better to discuss future support roadmap, I mean "when we drop support with Ruby2.3, 2.4, 2.5... for fluentd in the future" policy. Not fixed one but a rough consensus is good, IMO.

**Comment by repeatedly** [comment]
> Maybe it's also better to discuss future support roadmap, I mean "when we drop support with Ruby2.3, 2.4, 2.5... for fluentd in the future"

One year support after EOL is good for me but several popular distributions use EOL version with own patches. So fixed drop timeline is not good for community.

**Comment by henrich** [comment]
Of course, we should care about distributions, and we can predict distros EOL thus suggest "plan" to the community, right?

distro | ruby version | date
------- | ----------------  | ------
Ubuntu 14.04 LTS | ruby 1.9.1 | EOL in this April
RHEL6 (CentOS6) | ruby 1.8.7  | November 2020
Ubuntu 16.04 LTS | ruby 2.3.1  | April 2021
Debian9 LTS | ruby 2.3.3  | June 2022
Ubuntu 18.04 LTS | ruby 2.5.1 | April 2023 
Debian10 LTS | ruby 2.5.5 | May? 2024
RHEL7 (CentOS7) | ruby 2.0.0 | June 2024
RHEL8 (CentOS8) | ? | ? 2029

So, I suggest you
- drop ruby2.1 and 2.2 support in this summer (2019)
- drop ruby2.3 and 2.4 support in July 2022
- drop ruby2.5 support - no plan ;)

note: distribution EOL: [Ubuntu](https://wiki.ubuntu.com/Releases) / [Debian](https://wiki.debian.org/LTS) /  [RHEL](https://access.redhat.com/support/policy/updates/errata/) /  [CentOS](https://wiki.centos.org/FAQ/General#head-fe8a0be91ee3e7dea812e8694491e1dde5b75e6d)

**Comment by ioquatix** [comment]
If current release supports 2.1 and so on, why can’t existing users continue to use it? Why do you need to support forward compatibility for LTS? Surely it’s enough to have a stable branch which backport security issues etc. LTS Indicated some desire for stability so do user want to use latest release or stick with known good version?

**Comment by ganmacs** [comment]
updated: https://www.fluentd.org/blog/drop-schedule-announcement-in-2019

**Comment by ioquatix** [comment]
Thanks for the update. I will probably remove 2.3 support too.

**Comment by ioquatix** [comment]
Nice work!
