### ISSUE TITLE
facing issue while reading one log event present in logfile

### ISSUE THREAD

**Issue by himmatb** [fluent/fluentd#2382]
- fluentd or td-agent version: `fluentd 1.3.3`

- Environment information:
	- Operating system: `windows 21012 R2`

- My configuration

```
<source>
    @type 
    path "C:\\Bharath020419100816.txt"
    pos_file etc/td-agent/pos/xxxxxxxxxx.pos
    tag xxxxxxxx
    path_key tailed_path 
    format none
    read_from_head true
</source>

<filter xxxxxx-**>
    @type record_modifier
    <record>
        entity "xxxxxxxxxx"
        shipped_time "${Time.at(time).to_s}"
        log_time "${record['tailed_path'].split(\"/\")[-1].split(\".\")[0][-12..-1]}"
        component ${tag}
        hostname "#{Socket.gethostname}"
    </record>
</filter>
<match **>
   @type stdout
</match>
```

- Our problem explanation :

One of application is one event logs to one file with timestamp extension to file example : xxxxxxxxxxxxxxxxxx020419100816.txt 

Each event is writing one log event in single logfile with timestamp at prefix of file as above examples. 
when i am providing enter at end of log event in file then only its start consuming. but i should not be change any content in log file because its written by application itself.

example of log event :--
Log file : xxxxxxxxxxxxxxxxxx020419100816.txt 

Below is just example one Log event in file :--
 2019-04-14 17:00:45.234 DEBUG com.cs.xxxxxxxxxxxxxxxxxxx(IntfUtilLog.java:40) 

Let me know if you need any other information.
Please help me to identify this issue.

**Comment by himmatb** [comment]
If i am following same steps in RHEL server using td-agent , Fluentd able to read that event !! is there some issue with windows td-agent ? not sure how to debug more on this ..

**Comment by okkez** [comment]
Please try `path "C:/Bharath020419100816.txt"`.

See also https://stackoverflow.com/questions/7173000/slash-and-backslash-in-ruby

**Comment by himmatb** [comment]
its didn't worked. when i am hitting EOF with new line , its started capturing logs. but if no newline character at end of log its not capturing anything from log file.
