### ISSUE TITLE
EHOSTUNREACH error: fluentd tries to connect to pod IP in a different k8s cluster

### ISSUE THREAD

**Issue by zenglian** [fluent/fluentd#2383]
**Version**: 
https://github.com/fluent/fluentd-kubernetes-daemonset/blob/master/fluentd-daemonset-elasticsearch.yaml

**Configuration**:
default, except the elasticsearchhost = den01zur.example.com. **Note** this elasticsearch runs in a **different** kubernetes cluster.

**Sympton** 
After running several hours, it got below error. When it occurs, no more events received by elastich search.
> 2019-04-16 07:08:24 +0000 [warn]: #0 [out_es] failed to flush the buffer. retry_time=1476 next_retry_seconds=2019-04-16 07:08:52 +0000 chunk="5869ecacffab3db4a502b2a3a36515b1" error_class=Fluent::Plugin::ElasticsearchOutput::RecoverableRequestFailure error="could not push logs to Elasticsearch cluster ({:host=>\"den01zur.example.com\", :port=>9200, :scheme=>\"http\", :path=>\"\"}): No route to host - connect(2) for 10.244.0.111:9200 (Errno::EHOSTUNREACH)"

**Diagnosis**
The log message shows "No route to host - connect(2) for 10.244.0.111:9200" --- this is **wrong**, as "10.244.0.111" is the pod IP of ES which is in a **different** cluster (unreachable of course). It should **always** use external IP to connect ES.
So, looks it switched to pod IP due to some reason after several hours, but that IP is unreachable.

**Comment by repeatedly** [comment]
This seems elasticsearch plugin issue so this place is incorrect. See contribution guide: https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md#found-a-bug

@cosmo0920 This seems reload connection issue?

**Comment by cosmo0920** [comment]
Hmm, this case seems to be reload connection issue but reporter does not provide his Fluentd configuration.
I couldn't dig into root cause of his issue.

**Comment by zenglian** [comment]
I'm not familiar with ruby, so won't debug it or create PR.

**Comment by zenglian** [comment]
Is there any workaround?

**Comment by zenglian** [comment]
close, see https://github.com/uken/fluent-plugin-elasticsearch/issues/577
