### ISSUE TITLE
can i use placeholder in <source> tag?

### ISSUE THREAD

**Issue by yechanpark** [fluent/fluentd#2387]
Hi. im using td-agent version both 0.12.26 and 1.3.3

im using fluentd-forest-plugin in 0.12.26,
and 1.3.3 using both fluentd-forest-plugin and buffer for using placeholder.

i want to send multiple nginx error log to other server via tail type source.

in match tag, i can handle these logs via placeholder .
but i want to use placeholder in <source> tag. 

can i do this?

**Comment by repeatedly** [comment]
Currently, we have no plan for placeholder support in input side's `tag` parameter because it can be done by rewrite-tag-filter or similar plugins.

**Comment by yechanpark** [comment]
@repeatedly 
ok. thanks for your response. i will check it. 😄
