### ISSUE TITLE
Failover mechanism implementation to route the traffic to Secondary host instances

### ISSUE THREAD

**Issue by nreddy67** [fluent/fluentd#2389]
Hi,

Currently I was not able to see any documentation around the failover mechanism implementation to route the traffic to secondary Elastic instance in case of any primary Elastic failover . Can you please point me to it.

I tried the below and it doesn't work.

```
<match book.**>
  @type elasticsearch
    <server>
  host host.docker.internal
  port 9200
  index_name bookdata
  type_name book
  id_key id
    </server>
    <server>
      @type elasticsearch
      host 96749bbc7dd34f278e2f9be4dc280b34.abc.xyz.com
      port 9200
      index_name bookdata
      type_name books
      user elastic
      password Ww1jrcVfrYvUke8lM3VTUAXz
      id_key id
      standby yes
    </server>
</match>
```

**Comment by nreddy67** [comment]
Hi,

I have tried the following, but doesn't seem to be working.

<match sample.**>
  @type elasticsearch
  host host.docker.internal
  port 9200
  index_name sample
  type_name book
  id_key bookNumber
    <secondary>
      @type elasticsearch
      host 96749bbc7dd34f278e2f9be4dc280b34.xyz.abc.com
      user elastic
      password XXXXX
        port 9200
        index_name sample
        type_name book
        id_key bookNumber
    </secondary>

</match> 

Can you suggest me the best feasible option.

**Comment by ganmacs** [comment]
please read the document https://docs.fluentd.org/output#secondary-output
and here is not for the QA. please also read https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md
