### ISSUE TITLE
show-plugin-config not working?

### ISSUE THREAD

**Issue by Jonnymcc** [fluent/fluentd#2400]
td-agent.x86_64: 2.3.4-1.el2016
gem 'fluentd' version '1.4.2'

- Environment information:
	- Operating system: `NAME="Amazon Linux AMI"
VERSION="2016.03"
ID="amzn"
ID_LIKE="rhel fedora"
VERSION_ID="2016.03"
PRETTY_NAME="Amazon Linux AMI 2016.03"
ANSI_COLOR="0;33"
CPE_NAME="cpe:/o:amazon:linux:2016.03:ga"
HOME_URL="http://aws.amazon.com/amazon-linux-ami/"`
	- Kernel version: `4.4.11-23.53.amzn1.x86_64`

`--show-plugin-config` does not show any useful output.

```
td-agent --show-plugin-config=output:s3
2019-04-25 16:40:46 -0400 [info]: Use fluent-plugin-config-format --format=txt output s3
```

**Comment by repeatedly** [comment]
> 2019-04-25 16:40:46 -0400 [info]: Use fluent-plugin-config-format --format=txt output s3

See log comment :)

**Comment by repeatedly** [comment]
BTW, adding `deprecated` to `--help` result is better.
