### ISSUE TITLE
How to parse multiple records from single nginx record

### ISSUE THREAD

**Issue by JohnMealy23** [fluent/fluentd#2402]
Check [CONTRIBUTING guideline](https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md) first and here is the list to help us investigate the problem.

- fluentd or td-agent version.
    - fluentd 1.4.1
- Environment information:
	- Kernel version: `4.9.125-linuxkit` 
	- Operating system: `Alpine Linux v3.7.1`
- Your configuration
```
<source>
  @type tail
  tag events
  path /nginx-log/tracker.log
  pos_file /nginx-log/tracker.log-fluentd.pos
  format json
  json_parser oj
  read_lines_limit 40
  time_key @timestamp
  time_format %FT%T+00:00
</source>
```
- Your problem explanation.

We're using in_tail plugin to parse Nginx logs.  Currently each line in the Nginx log is a single request from the browser, and each request contains a single record.  

We'd like to start sending multiple records with each request from the browser.  We're looking for a way of breaking the multiple records in each request into individual records *without* using a Ruby plugin.  

Does anyone have a solution for breaking large arrays of records into individual tagged records without using a Ruby plugin?

**Comment by ganmacs** [comment]
sorry for the late reply but please read  https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md
