### ISSUE TITLE
out_file does not preserve order

### ISSUE THREAD

**Issue by tarvip** [fluent/fluentd#2403]
I have td-agent (3.2.0) installed on Amazon Linux 1.
td-agent has been setup to receive messages sent by fluent-bit and write them to disk. Configuration is following:
```
<source>
  @type forward
  port 24224
  bind 0.0.0.0
</source>

<filter kube.*.log>
  @type record_modifier
  <record>
    kube_app "${record['kube_labels_app'] || record['kube_labels_k8s-app'] || 'unknown-kube-app'}"
  </record>
</filter>

<match kube.*.log>
  @type file
  path /log/%Y-%m-%d/${kube_cluster_name}-${kube_app}_${kube_container_name}-${stream}
  <buffer time, kube_cluster_name, kube_app, kube_container_name, stream>
    @type memory
    flush_mode interval
    flush_interval 1s
  </buffer>
  <format>
    @type kube_out_file
    fields time,kube_pod_name,log
  </format>
  append true
</match>
```

kube_out_file formatter is following:
```
require 'fluent/plugin/formatter'

module Fluent::Plugin
  class KubeOutFileFormatter < Formatter
    Fluent::Plugin.register_formatter("kube_out_file", self)

    config_param :fields, :array, value_type: :string
    config_param :delimiter, :string, :default => " "

    def configure(conf)
      super
    end

    def format(tag, time, record)
      values = []

      @fields.each do |field|
        v = record[field]
        unless v
          log.error "#{field} is missing."
        end
        values << v.to_s
      end

      values.join(@delimiter)
    end
  end
end
```

`/log` has xfs filesystem.

The problem is that fluentd is not always preserving receiving log order. When looking log then entries are not always ordered by timestamps, sometimes there are new entries first and then older entries.

I have debugged this issue a bit with `tcpdump`, basically logged incoming stream to disk and investigated cases where timestamp order in log file was wrong. From tcpdump output it seems that data is coming in in correct order.

Is there a way to strictly preserve receive order in fluentd out_file plugin? I have played with flushing parameters, so far without luck. Also tried latest td-agent 3.3 on amazon linux 2, it had same issue.

**Comment by igortin** [comment]
the same problem with out_elasticsearch. 
Can somebody provide recommendations how to solve this problem.

What i found :
I suppose that the problem appears because fluentd send bulk write request to elasticsearch and it   writes documents to different shards with the same timestamp and the same assigns sort key.Thats why order of logs is wrong.
Note:
Sort key consists timestamp(unixtime) + subseconds.

How i can configure fluentd to avoid the problem with wrong timestamp without performance issues?

**Comment by repeatedly** [comment]
> Is there a way to strictly preserve receive order in fluentd out_file plugin?

**Comment by igortin** [comment]
Thank you, you are right.
