### ISSUE TITLE
how to use fluentd+elasticsearch+grafana to display the first 12 characters of the container ID?

### ISSUE THREAD

**Issue by lenoAlex** [fluent/fluentd#2406]
Need to use fluentd to collect logs of kubernets cluster and store them in elasticsearch db. And use grafana to display logs and digests. However, the docker's container id is 64 characters. How to set the fluentd, to display just first 12-character of container id in grafana?

my config file as follow:

[fluentd-es-configmap.zip](https://github.com/fluent/fluentd/files/3146357/fluentd-es-configmap.zip)

**Comment by repeatedly** [comment]
If you still have the problem, please post the question on google groups, not here.
