### ISSUE TITLE
Json in json not parsed / nginx and severall other services

### ISSUE THREAD

**Issue by cccdemon** [fluent/fluentd#2415]
Check [CONTRIBUTING guideline](https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md) first and here is the list to help us investigate the problem.

- fluentd 1.5.0 & 1.3.4
- Environment information:
	- Operating system: `google kubernetes / Container OS`
	- Kernel version: `unknown`
- Configuration 

`
  fluent.conf:
    <match fluent.**>
      @type null
    </match>  

    <source>
      @id blablafoo-containers.log
      @type tail
      tag default
      path /var/log/containers/web*blablafooo*.log
      pos_file /var/log/blablafooo-containers.log.pos
      read_from_head true
      tag blablafooo.access*
      <parse>
        @type json
        time_format %Y-%m-%dT%H:%M:%S.%NZ
      </parse>
    </source>

    <source>
      @id microcaching-containers.log
      @type tail
      tag default
      path /var/log/containers/microcache-proxy*.log
      pos_file /var/log/webstats-containers.log.pos
      read_from_head true
      tag webstats.access*
      <parse>
        @type json
        time_format %Y-%m-%dT%H:%M:%S.%NZ
      </parse>
    </source>

    <source>
      @id fluentd-containers.log
      @type tail
      tag default
      path /var/log/containers/*.log
      pos_file /var/log/es-containers.log.pos
      read_from_head true
      tag kubernetes.*
      <parse>
        @type json
        time_format %Y-%m-%dT%H:%M:%S.%NZ
      </parse>
    </source>

    <source>
      @type tail
      @id in_tail_docker
      path /var/log/docker.log
      pos_file /var/log/fluentd-docker.log.pos
      tag docker
      <parse>
        @type regexp
        expression /^time="(?<time>[^)]*)" level=(?<severity>[^ ]*) msg="(?<message>[^"]*)"( err="(?<error>[^"]*)")?( statusCode=($<status_code>\d+))?/
      </parse>
    </source>

    <source>
      @type prometheus
    </source>

    <source>
      @type prometheus_output_monitor
    </source>
  
    <filter kubernetes.**>
      @type kubernetes_metadata
      @id filter_kube_metadata
    </filter>

    <filter **microcache-proxy**>
      @type stdout
      key_name log
      <format>
        @type json
      </format>
    </filter>

    <match **blablafoo**>
      @type copy
      <store>
        @type elasticsearch
        @log_level info
        host elasticsearch-data
        port 9200
        logstash_format true
        logstash_prefix default-blablafoo
        logstash_dateformat %Y%m%d
        include_tag_key true
        type_name access_log
        tag_key @log_name
        flush_interval 1s
      </store>  
    </match>        

    <match **microcache-proxy**>
      @type copy
      <store>
        @type elasticsearch
        @log_level info
        host elasticsearch-data
        port 9200
        logstash_format true
        logstash_prefix default-microcache
        logstash_dateformat %Y%m%d
        include_tag_key true
        type_name access_log
        tag_key @log_name
        flush_interval 1s
      </store>
    </match>        

    <match kubernetes.var.log.containers.**>
      @type copy
      <store>
        @type elasticsearch
        @log_level info
        host elasticsearch-data
        port 9200
        logstash_format true
        logstash_prefix default
        logstash_dateformat %Y%m%d
        include_tag_key true
        type_name access_log
        tag_key @log_name
        flush_interval 1s
      </store>  
    </match>        

`

- JSON Filter Logs (example): 

`

{"log":"{\"time_local\":\"21/May/2019:10:06:46 +0000\",\"remote_addr\":\"10.214.5.2\",\"remote_user\":\"\",\"request\":\"GET /static-composition/composition/navigation.html HTTP/1.1\",\"status\": \"200\",\"body_bytes_sent\":\"22579\",\"request_time\":\"0.002\",\"http_referrer\":\"\",\"http_user_agent\":\"Symfony BrowserKit\"}\n","stream":"stdout","docker":{"container_id":"62089cd30b770ae3a7aa1585dfbfe7831b3e8b47ca8af48350ccbda1f0d7b0a5"},"kubernetes":{"container_name":"microcaching-proxy","namespace_name":"default","pod_name":"microcache-proxy-6898bd7754-nq6gb","container_image":"nginx:1.15.12-alpine","container_image_id":"docker-pullable://nginx@sha256:57a226fb6ab6823027c0704a9346a890ffb0cacde06bc19bbc234c8720673555","pod_id":"848725e5-7ba1-11e9-b686-4201ac100209","labels":{"app":"microcache-proxy","pod-template-hash":"2454683310"},"host":"you dont need to know","master_url":"https://10.215.0.1:443/api","namespace_id":"42b82f4c-e979-11e8-b076-4201ac100203"}}

`

Expected: JSON Explodes in Kibana
RESULT: JSON is logged as "String" with Key "Log" 

AND YES - i tried to use default nginx filter with default nginx config. Same issue (well not json, but not parsed successfull - no i did not create my own nginx log_format)

There is actual no way to add nginx logs properly to elasticsearch.... i tried them all! 

/bug

**Comment by cccdemon** [comment]
![Bildschirmfoto 2019-05-21 um 12 17 04](https://user-images.githubusercontent.com/7745289/58088178-64693880-7bc2-11e9-9d0b-5fa2c1534f0f.png)
![Bildschirmfoto 2019-05-21 um 12 16 59](https://user-images.githubusercontent.com/7745289/58088179-6501cf00-7bc2-11e9-8334-bd01bdf1ede3.png)

**Comment by repeatedly** [comment]
Use parser filter.

See "Additional Step 1: Parse log message": https://www.fluentd.org/guides/recipes/docker-logging 
https://docs.fluentd.org/filter/parser

**Comment by cccdemon** [comment]
@repeatedly like this?

` 
<filter **microcache-proxy**>
  @type stdout
  key_name log
  <format>
    @type json
  </format>
</filter>
` 
???

**Comment by cccdemon** [comment]
@repeatedly thanks a lot! 

it works now as expected 🤷‍♂ 👍
