### ISSUE TITLE
Cannot exclude logs from fluentd 

### ISSUE THREAD

**Issue by Pigmalion** [fluent/fluentd#2419]
I have installed fluentd with HELM thus I am trying to configure it threw values.yaml. 
```
This is the set up- 
configMaps:
  output.conf: |
    <filter **>
     <exclude>
        key MESSAGE
        pattern /from/
     </exclude>
    </filter>
```
also tryed : 
```
configMaps:
  output.conf: |
    <filter **>
     type grep
       exclude1 MESSAGE cloud
    </filter>
```

Yet, nothing is excluded from my kibana report. 
What am I doing wrong?

**Comment by Pigmalion** [comment]
Any response ??

**Comment by Pigmalion** [comment]
Still no responce? 
feeling: https://funnyjunk.com/funny_gifs/2178649/Luuuuchaaaaaa/

**Comment by repeatedly** [comment]
Please post it on maling list with actual event and fluentd log, not here. This issue doesn't follow contribution guide.

**Comment by ganmacs** [comment]
as @repeatedly said, please follow the contribution guide.  https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md
