### ISSUE TITLE
fluent-plugin-gelf-hs do not add milliseconds to time.

### ISSUE THREAD

**Issue by EverGreen5455** [fluent/fluentd#2420]
- Fluentd version: 0.12.33
- fluent-plugin-gelf-hs version: 1.0.8
- Configuration

```
<source>
  @type tail
  path /var/log/containers/*.log
  pos_file /var/log/es-containers.log.pos
  time_format %Y-%m-%dT%H:%M:%S
  tag docker.*
  format json
  keep_time_key true
  read_from_head true
  exclude_path []
  read_lines_limit 500
</source>

<match docker.**>
  @type copy_ex
  <store ignore_error>
    @type gelf
    host <graylog_host>
    port <graylog_port>
    protocol tcp
    add_msec_time true
    flush_interval 5s
  </store>
</match>
```

- Problem explanation:
Plugin do not add milliseconds to time.
In the Graylog I get logs with time 2019-05-27T22:16:21.000Z

**Comment by cosmo0920** [comment]
Because you use Fluentd v0.12:
https://github.com/bodhi-space/fluent-plugin-gelf-hs/blob/master/lib/fluent/plugin/out_gelf.rb#L65

But this issue doesn't follow the contribution guideline.
This issue is fluent-plugin-gelf-hs' issue not Fluentd core's.
So, closing this issue.

**Comment by EverGreen5455** [comment]
@cosmo0920, is there an opportunity to support Fluentd v0.12?

In the 'fluent-plugin-gelf-hs' repository it is impossible to create a new issue. 
Please tell me how to solve this problem using Fluentd v0.12.

**Comment by cosmo0920** [comment]
There is no solution for v0.12 with fluent-plugin-gelf-hs itself. 
Because Fluentd v0.12's events don't have milliseconds precision in timestamp.
Thanks.

**Comment by EverGreen5455** [comment]
Thanks a lot.
