### ISSUE TITLE
Use journalctl command with td-agent

### ISSUE THREAD

**Issue by bhavyabhatj** [fluent/fluentd#2428]
Hi ,
I am using td-agent to push logs from influxdb to elastic search.
I am facing an issue where in when i give exec with journalctl command in source i am unable to get any logs for the same.
How can i forward logs from journalctl -f -u "myservice" to elk server?

**Comment by repeatedly** [comment]
You need to check fluentd has a permission to read jurnalctl logs.
BTW, this is question so this is not right place. closed.
