### ISSUE TITLE
Unable to start td-agent after stopping it 

### ISSUE THREAD

**Issue by rameshVeeramani** [fluent/fluentd#2432]
This seems to be an ongoing issue, and it has occurred at least thrice. 

OS : Centsos 7

On stopping td-agent and starting (not restarting) the service. The td-agent service doesn't start while throwing error message as 

systemctl start td-agent
**Job for td-agent.service failed because the control process exited with error code. See "systemctl status td-agent.service" and "journalctl -xe" for details.**

On using the script to start the service 

 _: td-agent.service: control process exited, code=ex...s=1
 Failed to start td-agent: Fluentd based data coll...ta.
 Unit td-agent.service entered failed state.
 : td-agent.service failed.
  td-agent.service holdoff time over, scheduling restart.
 Stopped td-agent: Fluentd based data collector fo...ta.
 start request repeated too quickly for td-agent.service
 Failed to start td-agent: Fluentd based data coll...ta.
 Unit td-agent.service entered failed state.
  td-agent.service failed._

I have to delete all the td-agent folder and reinstall for it work again . I guess want to check if I am missing out something or ..is this a valid issue ?

**Comment by ganmacs** [comment]
The information is too little to grasp all of the error. Could you add all of the logs from journalctl and your situation more detail?

**Comment by ganmacs** [comment]
No response from an author. I'm closing. if you have additional info, feel free to notify me.
