### ISSUE TITLE
How to remove "\" or "\\\" in fluentd

### ISSUE THREAD

**Issue by gogovan-vincentngai** [fluent/fluentd#2435]
I am new in fluentd 
I want to use fluentd capture my log with specifca keyword and output to kinese

I find that fluent-bit (as my target is in K8S also ) , does not support kinese plugin ?

With below config 
```
    <match fluent.**>
      @type null
    </match>
    
    <source>
      @type tail
      path /var/log/containers/*.log
      pos_file /var/log/fluentd-containers.log.pos
      tag ggt
      read_from_head true
      reserve_data true
      <parse>
        @type regexp
        expression /(?<remove>.?)\[TARGET_KEYWORD\](?<message>.*)/
      </parse>
    </source>

    <match ggt>
      @type file
      path /fluentd/log
    </match>
```

I and get in to the pod , i got 

`{"message":"{\\\"A\\\":\\\"B\\\",\\\"C\\\":\\\"D\\\",\\\"E\\\":\\\"F\\\",\\\"G\\\":{\\\"H\\\":,\\\"I\\\":J,\\\"K\\\":L},\\\"M\\\":\\\"N\\\",\\\"datetime\\\":1559479129343,\\\"version\\\":\\\"1.0.0\\\",\\\"O\\\":{\\\"P\\\":\\\"Q\\\",\\\"R\\\":U},\\\"V\\\":\\\"X\\\"}\\n\",\"stream\":\"stdout\",\"time\":\"2019-06-02T12:38:49.343263769Z\"}"}`

But i just dont what those "\" , "\\\" and "\n" 

May i know what is you guys suggest ?

I Check post from fluent-bit 
https://github.com/fluent/fluent-bit/issues/278

**Comment by ganmacs** [comment]
Sorry for the late response. but here is not for  QA. please read https://github.com/fluent/fluentd/blob/6ef77be211d33c06c8602f71daa47910822e042e/CONTRIBUTING.md#got-a-question-or-problem
