### ISSUE TITLE
how to control fluentd output speed

### ISSUE THREAD

**Issue by like-inspur** [fluent/fluentd#2440]
I use fluentd output for kafka or elasticsearch. Because kafka and elasticsearch all have limit speed of data send. So I want to know how to control fluentd output speed, and also use for multi users in limited bandwidth environment

**Comment by readygodom** [comment]
The same question... How to control the speed when I use fluentd to output my log metric???

**Comment by repeatedly** [comment]
You can control it with output and buffer parameters.

https://docs.fluentd.org/output#buffering-retrying-parameters

BTW, this doesn't follow contribution guide so I will close this issue tomorrow.
Please post it on mailing list.
