### ISSUE TITLE
What is the purpose of Plugin Helper: Server?

### ISSUE THREAD

**Issue by ananth07reddy** [fluent/fluentd#2442]
Without creating any certificates using the below config worked for me. But I am not sure about the logs are really encrypted in the transit from fluent bit to fluentd or not.

**Fluentd.conf**
  <transport tls>
    generate_private_key_length 2048
    generate_cert_country US
    generate_cert_state CA
    generate_cert_locality Mountain View
    generate_cert_common_name "Common Name"
    generate_cert_expiration "#{10 * 365 * 86400}"
    generate_cert_digest sha256
  <transport>

**Fluentbit.conf**
[OUTPUT]
        Name            forward
        Match           *
        Host            ${FORWARD_HOST}
        Port            ${FORWARD_PORT}
        tls             On
        # see fluentd <transport tls> config
        tls.verify      Off
        tls.debug       1
        shared_key      ${FLUENT_SHARED_KEY}
        # Setting the retry counts to unlimited, see fluentd scheduler configuration (https://docs.fluentbit.io/manual/configuration/scheduler)
        Retry_Limit     False

Could please explain the difference between using openssl certificates from both sides (fluent bit and fluentd) and using the above config?

**Comment by ganmacs** [comment]
Is this fluent-bit question? the please post it to https://github.com/fluent/fluent-bit
