### ISSUE TITLE
Allow configuring fluetnd windows service using ENV variable

### ISSUE THREAD

**Issue by rishisharmamt** [fluent/fluentd#2448]
Check [CONTRIBUTING guideline](https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md) first and here is the list to help us investigate the problem.

- fluentd or td-agent version: 1.3.3
- Environment information:
	- Operating system: Windows Server 2016 Datcenter v1607
- Your configuration
- Your problem explanation. If you have an error logs, write it together.

When running fluentd as a windows service, the command line options passed to fluentd program is configured in windows registry under "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\fluentdwinsvc\fluentdopt".
There is no option to pass command line options to fluentd program run as windows service because of which log rotation cannot be configured for fluentd logs.
We can use an environment variable like for systemd service ($TD_AGENT_OPTIONS) and append that to "fluentdopt" value set in registry.

**Comment by repeatedly** [comment]
> There is no option to pass command line options to fluentd program run as windows service because of which log rotation cannot be configured for fluentd logs.

https://docs.fluentd.org/installation/install-by-msi#step-3-register-td-agent-to-windows-service

So in your case, you can't set command line options at `--reg-winsvc-fluentdopt` setup phase?

**Comment by ganmacs** [comment]
No response from an author. I'm closing. if you have additional info, feel free to notify us.
