### ISSUE TITLE
Fluentd tail file is not working with log rotation

### ISSUE THREAD

**Issue by akhilkumarpdd** [fluent/fluentd#2449]
I am trying to tail nifi-app.log which is rotated by apache nifi in every one hour. The tail file with fluentd works fine initially, but once nifi rotates the file, the tail file stops working.

I have mounted /nifi/nifi/logs/nifi-app.log to /fluentd/etc/nifi-app.log inside docker container.

The fluentd configuration file (fluent.conf) is given below :

<source>
  @type tail
  read_from_head true
  path /fluentd/etc/nifi-app.log
  pos_file /fluentd/etc/fluentd-docker.pos
  tag docker.*
  <parse>
    @type none
  </parse>
  refresh_interval 50s
</source>
<filter>
  @type grep
  <regexp>
    key message
    pattern /nifi-log/
  </regexp>
</filter>
<match>
    @type kafka2

    # list of seed brokers
    brokers localhost:6667

    <buffer topic>
      flush_interval 10s
    </buffer>

    # topic settings
    topic_key new-log-data
    default_topic new-log-data

    compression_codec gzip

    <format>
      @type json
    </format>
</match>

Is there any option that is missing in the configuration? I want fluentd to continuously monitor nifi-app.log even after the log rotates.

Thanks in advance.

**Comment by repeatedly** [comment]
Reply on the mailing list. If this is the bug of fluentd, reopen the issue.
