### ISSUE TITLE
Start even if failed to parse certificate file

### ISSUE THREAD

**Issue by summerwind** [fluent/fluentd#2458]
- fluentd version: 1.4.2
- Environment information:
  - Operating system: `16.04.6 LTS (Xenial Xerus)`
  - Kernel version: `4.4.0-145-generic`
- Your configuration
```
<source>
  @type forward
  bind 0.0.0.0
  port 24224

  <transport tls>
    cert_path /fluentd/etc/fluentd.pem
    private_key_path /fluentd/etc/fluentd.pem
  </transport>
</source>

<match **>
  @type null
</match>
```

It seems that fluentd start even if failed to parse certificate file in forward input with TLS.

If we use a certificate file that does not end with a newline (`\n`), it will not match Fluentd's internal pattern[^1]. However Fluentd seems to start and listen on TLS connection. If you connect to Fluentd with TLS in this state, all handshakes will fail.

[^1]: https://github.com/fluent/fluentd/blob/ea651827782d7ec92c3cd09cb6ada65e32bfab44/lib/fluent/plugin_helper/cert_option.rb#L171

**Comment by brokencube** [comment]
I literally just had this exact issue, though in my case, it failed to even open port 24224, it just hung on the regex.

I think the regex in: plugin_helper/cert_option.rb:171
```ruby
pattern = Regexp.compile('-+BEGIN CERTIFICATE-+\n(?:[^-]*\n)+-+END CERTIFICATE-+\n', Regexp::MULTILINE)
```

Should be changed from
```regex
'-+BEGIN CERTIFICATE-+\n(?:[^-]*\n)+-+END CERTIFICATE-+\n'
```
to
```regex
'-++BEGIN CERTIFICATE-++\n(?:[^-]*\n)+-++END CERTIFICATE-++\n?'
```
(The `++` is a "possessive" greedy match which should speed up non matches)

**Comment by repeatedly** [comment]
For both cases, adding `?` to last fixes the problem, right?

**Comment by summerwind** [comment]
Yes, adding '?' to the end is a simple way.

**Comment by repeatedly** [comment]
@summerwind If you have a chance, could you send a patch?

**Comment by summerwind** [comment]
I sent a patch on #2466.
