### ISSUE TITLE
How to put ASCII  encoded delimiter to csv formatter plugin 

### ISSUE THREAD

**Issue by bobykus31** [fluent/fluentd#2463]
We use latest  fluetd by td-agent  3.3.0-1. We made an attempt to use unit separator from ASCII table https://en.wikipedia.org/wiki/Delimiter (ASCII Dec) as a csv delimiter like

```
        <format>
           @type csv
           delimiter "\x31"
           fields host,facility,severity,ident,time,pod,message
           force_quotes false
        </format>
```

We got 

```
Jun 18 09:16:29 fluentd1 fluentd[5467]: /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.3.3/lib/fluent/config/basic_parser.rb:92:in `parse_error!': unexpected back-slash escape character 'x' at main.conf line 83,24 (Fluent::ConfigParseError)
Jun 18 09:16:29 fluentd1 fluentd[5467]:  82:            @type csv
Jun 18 09:16:29 fluentd1 fluentd[5467]:  83:            delimiter "\x31"
Jun 18 09:16:29 fluentd1 fluentd[5467]:      ------------------------^


```
What is the right way to use  delitimer of ASCII table?

**Comment by ganmacs** [comment]
Could you follow the issue template?  And see [CONTRIBUTING.md](https://github.com/fluent/fluentd/blob/25b081c49abcc15c72dbd4b69cc347c771e0b89f/CONTRIBUTING.md)

>  If you have questions about Fluentd and plugins, please direct these to 
 https://groups.google.com/forum/#!forum/fluentd

I think `delimiter '\x31'` or `delimiter "\\x31"` works.

Anyway, this PR follows nither the issue template nor CONTRIBUTING.md.
I'll close this.
