### ISSUE TITLE
Keep the input files in the output

### ISSUE THREAD

**Issue by MickaelBZH** [fluent/fluentd#2471]
Hi,

I sending a folder of files to S3 using Fluentd and I would like to keep the exact folder structure and files in the output, ie I don't want files to be buffered into one file for example.

Is there a way to achieve this with Fluentd?

**Comment by ganmacs** [comment]
This seems https://github.com/fluent/fluent-plugin-s3 's issue and does not follow the [CONTRIBUTION guide](https://github.com/fluent/fluentd/blob/a0240f6b7d897502fa36f9a720f9fb6b85a23bae/CONTRIBUTING.md). So I'm closing.

**Comment by repeatedly** [comment]
Yes. mailing list is better for asking question.
BTW, fluentd doesn't focus on file copy use case. If you want to sync folder between local directory and S3 bucket, using other tool seems better.
