### ISSUE TITLE
Google cloud - running Fluentd in GKE cluster as Pod - error is after few days Fluentd does not forward logs to Stackdriver? buffer folder is full 

### ISSUE THREAD

**Issue by manojshetty28** [fluent/fluentd#2472]
In Google cloud - running Fluentd in GKE cluster as Pod - error is after few days Fluentd does not forward logs to Stackdriver? buffer folder is full 

For 3 days - fluentd does forward App - Pod logs to Stackdriver

But suddenly after 3 days, the Fluentd container Buffer folder does not store the App Pod logs and does not for forward logs to Google Stackdriver?

We need all App Pod logs in Stackdriver? 

Please suggest ..Thanks

**Comment by repeatedly** [comment]
Please follow contribution guide: https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md#got-a-question-or-problem
Post it with fluentd logs and your traffic / buffer grow info on mailing list.
