### ISSUE TITLE
do we need a forwarder and aggregator everytime to send logs to elastic , can't i do it with just a forwarder ?

### ISSUE THREAD

**Issue by hari819** [fluent/fluentd#2473]
i installed fluent/fluentd image from docker hub and installed elastic gem using fluent-gem install fluent-plugin-elasticsearch and trying to send data to elastic ,  fluent is able to tail json data from the volume mount i added , but it is unable to send data to elastic ,

i am thinking  do i need another instance of fluentd running to actually send data to elastic ?,
if the first fluentd is pulling data from a mounted folder , if i have to send data to say , another instance of fluentd running as a aggregator , i will need the host/ip of the aggregator . So in this case do i need a stateful set so that i can set a static hostname ?

it is just sending the last line of fluentd log like "worker 0 is started " to elastic .

can any one help ?

**Comment by ganmacs** [comment]
It depends on your environment, Although we recommend you to use aggregator nodes.

BTW, Please follow the [CONTRIBUTING.md](https://github.com/fluent/fluentd/blob/07fee9bff6b7402d63686c8640f54dd08a2997cd/CONTRIBUTING.md)
