### ISSUE TITLE
README: Fluentd architecture image is broken link

### ISSUE THREAD

**Issue by nokute78** [fluent/fluentd#2480]
**Describe the bug**
`README.md` has broken link.

Fluentd architecture image (https://docs.fluentd.org/images/fluentd-architecture.png) is dead link .
It seems to be cached by github.

The file is contained at fluentd-docs-gitbook repo.
https://github.com/fluent/fluentd-docs-gitbook/blob/1.0/images/fluentd-architecture.png

**To Reproduce**
None 

**Expected behavior**
Fix image URL.

**Your Environment**

- Fluentd or td-agent version: `fluentd --version` or `td-agent --version`
 None. (document issue)
- Operating system: `cat /etc/os-release`
 None. (document issue)
- Kernel version: `uname -r`
 None. (document issue)

**Your Configuration**
 None. (document issue)

**Your Error Log**
 None. (document issue)

**Additional context**
None

**Comment by repeatedly** [comment]
Thx. Just fixed.
