### ISSUE TITLE
include directive does not support Windows directory with spaces

### ISSUE THREAD

**Issue by rossbeehler** [fluent/fluentd#2485]
On Windows, if using an include directive with spaces in the path, the only way to load the file is to use old DOS short path notation.

**To Reproduce**
- In Windows, create an external config file with any valid configuration in a path similar to "C:\Folder With Spaces\fluentd.conf"
- In the root config file (e.g. td-agent.conf), add an include directive similar to "@include C:/Folder With Spaces/fluentd.conf"
- Start the fluentdwinsvc per normal, and the logs (e.g. td-agent.log) will contain no information

The only variant of the above example path that will work is "C:/FOLDER~1/fluentd.conf".  

Note that URI encoding the path (i.e. using %20 for each space) allows fluentd to start correctly, but still does not load the external configuration file. 

**Expected behavior**
The include directive should support directories with spaces, or at least document how to escape them, etc.  Additionally, some better logging around this would have been extremely helpful.

**Your Environment**
- td-agent v3.4.1
- Windows 2012 R2 (recreated on other Windows too)

**Additional context**
Note that I believe I understand the issue by reviewing the eval_include function in lib/fluent/config/v1_parser.rb.  It appears that any path given in the include directive is first passed into URI.parse, which will fail if it has spaces.  If you encode the path, URI.parse will succeed, but then when the path is extracted out of the URI, it will have the form "/Folder%20With%20Spaces/fluentd.conf", and that will not work with Dir.glob.  Not sure exactly what fix should be used, but I find it interesting that all paths must go through URI.parse, when file paths would not need to.

**Comment by repeatedly** [comment]
Thanks for the report.

> URI.parse, which will fail if it has spaces.

I first knew this behaviour. Hmm... one easy way to call URI.encode before URI.parse and call URI.decode for getting actual path like below.

```
diff --git a/lib/fluent/config/v1_parser.rb b/lib/fluent/config/v1_parser.rb
index a9667919..c90b781c 100644
--- a/lib/fluent/config/v1_parser.rb
+++ b/lib/fluent/config/v1_parser.rb
@@ -147,11 +147,11 @@ module Fluent
       end
 
       def eval_include(attrs, elems, uri)
-        u = URI.parse(uri)
-        if u.scheme == 'file' || (!u.scheme.nil? && u.scheme.length == 1) || u.path == uri # file path
+        u = URI.parse(URI.encode(uri))
+        if u.scheme == 'file' || (!u.scheme.nil? && u.scheme.length == 1) || u.path == URI.encode(uri) # file path
           # When the Windows absolute path then u.scheme.length == 1
           # e.g. C:
-          path = u.path
+          path = URI.decode(u.path)
           if path[0] != ?/
             pattern = File.expand_path("#{@include_basepath}/#{path}")
           else
```

**Comment by cosmo0920** [comment]
I'm taking a look on this.

**Comment by cosmo0920** [comment]
This issue is also affected on non-Windows platform.
