### ISSUE TITLE
fluentd crashes on undefined method `has_key?' 

### ISSUE THREAD

**Issue by fahedouch** [fluent/fluentd#2506]
Check [CONTRIBUTING guideline](https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md) first and here is the list to help us investigate the problem.

**Describe the bug**

I have a fluent-bit, which forward logs to fluentd, but my fluentd crash after a few minutes.

**Expected behavior**

**Your Environment**
fluentd version : fluentd:v1.4.2-1.0
fluent-bit version : fluent-bit:1.0.6

**Your Configuration**

My fluentd configuration is
```
<source>
  @type         forward
  port          24224
  bind          0.0.0.0
</source>
<source>
  @type prometheus
  bind 0.0.0.0
  port 24231
  metrics_path /metrics
</source>
<source>
  @type prometheus_output_monitor
  interval 10
  <labels>
    hostname ${hostname}
  </labels>
</source>
# Rename all keys begining by _ (underscore)
# as old elasticsearches don't support those
<filter **>
  @type rename_key
  rename_rule1 ^_(.+) ${md[1]}
</filter>


<match **>
  @id elasticsearch
  @type elasticsearch
  @log_level trace
  log_es_400_reason true
  include_tag_key true
  type_name doc
  logstash_format true
  logstash_prefix "box-default"
  target_index_key @target_index
  host "elasticsearch.infra.ritmx.ninja"
  port "9200"
  scheme "http"
  ssl_version: "TLSv1_2"
  reconnect_on_error true
  request_timeout 60s
  slow_flush_log_threshold 60.0
  # Liveness probe is based on file buffers under /var/log/fluentd-buffers
  # as a result, don't use in memory buffer otherwise, fluentd will crash loop
  <buffer>
    @type file
    path /var/log/fluentd-buffers/kubernetes.system.buffer
    flush_mode interval
    retry_type exponential_backoff
    flush_thread_count 2
    flush_interval 5s
    retry_forever
    retry_max_interval 30
    chunk_limit_size "10M"
    queue_limit_length "64"
    overflow_action block
  </buffer>
</match>

```

**Your Error Log**

```
2019-07-18 08:30:08 +0000 [warn]: #0 [elasticsearch] failed to flush the buffer. retry_time=18 next_retry_seconds=2019-07-18 08:30:41 +0000 chunk="58ded62cb61f43db06e78e4bd63ad546" error_class=Fluent::Plugin::ElasticsearchOutput::RecoverableRequestFailure error="could not push logs to Elasticsearch cluster ({:host=>\"elasticsearch.infra.ritmx.ninja\", :port=>9200, :scheme=>\"http\"}): undefined method `has_key?' for #<String:0x0000562784617b30>"
```

**Additional context**

**Comment by repeatedly** [comment]
From the issue content, we can't judge this is the bug of fluentd or fluent-bit or elasticsearch plugin.
Could you write reproducible step?

**Comment by repeatedly** [comment]
Remove bug tag for now because we can't determine this is the fluentd bug or not.

**Comment by cosmo0920** [comment]
This is ES plugin issue.
Here is a patch for this issue:
https://github.com/uken/fluent-plugin-elasticsearch/compare/handle-nil-items-resp

@fahedouch Could you check the above patch?

**Comment by fahedouch** [comment]
Hello @cosmo0920 

thank you for the patch, I tested it, but it doesn't resolve the problem of `has_key?` . I always I still have `has_key?`  in me logs

Have a nice day.

**Comment by cosmo0920** [comment]
@fahedouch Could you open an issue in https://github.com/uken/fluent-plugin-elasticsearch?
This issue must be fluent-plugin-elasticsearch not Fluentd core's.
