### ISSUE TITLE
Message are not parsing correctly from syslog-ng #1444

### ISSUE THREAD

**Issue by vaibhavt19** [fluent/fluentd#2507]
I'm new at FluentD and trying to parse my application logs through syslog-ng logs to fluentd but I'm getting the error on parsing the message. At first I thought it was due to timestmap, i have tried many combinations but it's not working.
Also getting the duplicate logs on ourput file, i think the issue is the second date field in raw message but don't know how to fix it.

## FluentD configuration
```
<source>
  @type syslog
  port 1517
  tag firehose
  protocol_type tcp
  append true
  time_format %b %d %H:%M:%S
  #message_format rfc3164
</source>
<match *.**>
  @type file
  path  /firehose/%Y/%m/%d.log
  buffer_type memory
  compress text
  append true
</match>
```

## Raw message
`Jul 17 00:00:00 10.139.2.41 iprod/cloud/iBackupsrv[2053]: [2019-07-17 00:00:00,006] [INFO] inSyncBackupSrv-472 Handing over: cid=6478, sid=8109, uid=1337955, did=1743743, type=Backup, sessionid=1353783308, email=test@test.com, wk=n90-c5-cloud.test.com, sname=test, Inc._us-east-1, bid=750.`

## Error log message:
`2019-07-17 14:10:01 +0000 [warn]: #0 failed to parse message data="366 <133>1 2019-07-17T14:10:00+00:00 cm0-phoenix.druva.com roboConfigServer.py 2013129 - [meta dir_id=\"robo/CloudMaster\" index=\"true\"] [2019-07-17 14:10:00,367] [INFO] [CS 2013129] ts=1563372600367547904 service=PhoenixConfigServer type=rlog method=apidispatcher:SCTasks;api:listrp; stime=1563372599778070016 etime=1563372600367539968 duration=589469909 customerid=1065"`

**Comment by repeatedly** [comment]
Try `octet_count` and `rfc5424` message_format. Check official document: https://docs.fluentd.org/input/syslog

**Comment by vaibhavt19** [comment]
Thanks, it's working.
