### ISSUE TITLE
Using parts of ${tag} for logstash_prefix

### ISSUE THREAD

**Issue by rudyryk** [fluent/fluentd#2508]
We're using Fluentd with Elasticsearch to log very diverse services and would like to create multiple indexes.

Seems like for now we need to create multiple filters. Also, such config doesn't work as we need, because as `${tag}` we have `foo.bar.some.thing` and we'd want to have index prefixed with just `foo`:

```
<source>
  @type forward
  @id maininput
  @label @mainstream
  port 24224
</source>

<label @mainstream>
  <match **>
    @type copy
    <store>
      @type elasticsearch
      host 127.0.0.1
      port 9200
      logstash_format true
      logstash_prefix logs-${tag}
      logstash_dateformat %d
      include_tag_key true
      tag_key @log_name
      type_name _doc
    </store>
    <store>
      @type stdout
    </store>
  </match>
</label>
```

**Describe the solution you'd like**

We would like to configure like this:

```
      logstash_prefix logs-${tag_parts[0]}
```

**Comment by repeatedly** [comment]
See official document example: https://docs.fluentd.org/configuration/buffer-section#placeholders

**Comment by rudyryk** [comment]
@repeatedly Oh, thank you, this is great. I've read most of other chapters as well as searched Google. I think this is very useful feature and should be presented probably in separate chapter, like "Config: Placeholders". Thank you again!
