### ISSUE TITLE
Operation not permitted (Errno::EPERM) on using "--user" or "--group" parameter

### ISSUE THREAD

**Issue by josephine-rueckert** [fluent/fluentd#2531]
**Describe the bug**
Fluentd crashes when it's started with either "--user" or "--group" parameter with the following error message: 
/usr/lib64/ruby/gems/2.5.0/gems/serverengine-2.1.1/lib/serverengine/privilege.rb:50:in `groups=': Operation not permitted (Errno::EPERM)

**To Reproduce**
Start fluentd with "--user" or "--group" parameter.

**Expected behavior**
No crash.

**Your Environment**
- Fluentd 1.5.2
- Operating system: 
NAME="openSUSE Leap"
VERSION="15.0"
ID="opensuse-leap"
ID_LIKE="suse opensuse"
VERSION_ID="15.0"
PRETTY_NAME="openSUSE Leap 15.0"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:leap:15.0"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"
- Kernel version: 4.4.0-150-generic

**Your Configuration**

```
<match fluent.**>
  @type null
</match>

# Example:
# {"log":"[info:2016-02-16T16:04:05.930-08:00] Some log text here\n","stream":"stdout","time":"2016-02-17T00:04:05.931087621Z"}
<source>
  @type tail
  path /var/log/containers/*_fluentd_*.log
  pos_file /var/log/es-containers-fluentd-calico-peacock.log.pos
  tag kubernetes.*
  time_key time
  time_format '%Y-%m-%dT%H:%M:%S.%NZ'
  format json
  read_from_head true
</source>

<filter kubernetes.**>
  @type kubernetes_metadata
</filter>

<filter kubernetes.**>
  @type record_transformer
  enable_ruby
  <record>
    time_epoch ${time.to_f.to_s.gsub('.','').to_i}
    @timestamp ${time.strftime('%Y-%m-%dT%H:%M:%S.%NZ')}
    namespace ${record["kubernetes"]["namespace_name"]}
    host ${record["kubernetes"]["host"]}
    container ${record["kubernetes"]["container_name"]}
    pod ${record["kubernetes"]["pod_name"]}
  </record>
  remove_keys stream,docker,kubernetes
</filter>

<filter **>
  @type grep
  regexp1 "namespace ^fluentd$"
  exclude1 "container (fluentd|kibana|grafana|prometheus-kube-state-metrics|prometheus-alertmanager)"
</filter>

<match **>
   @type elasticsearch
   @log_level info
   include_tag_key true
   host elasticsearch
   port 9200
   logstash_format true
   time_key_format '%Y-%m-%dT%H:%M:%S.%NZ'
   # Set the chunk limit the same as for fluentd-gcp.
   buffer_chunk_limit 2M
   # Cap buffer memory usage to 2MiB/chunk * 32 chunks = 64 MiB
   buffer_queue_limit 32
   flush_interval 5s
   # Never wait longer than 5 minutes between retries.
   max_retry_wait 30
   # Disable the limit on the number of retries (retry forever).
   disable_retry_limit
   # Use multiple threads for processing.
   num_threads 8
</match>
```

**Your Error Log**
```
Traceback (most recent call last):
	10: from /usr/bin/fluentd:8:in `<main>'
	 9: from /usr/lib64/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:39:in `require'
	 8: from /usr/lib64/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
	 7: from /usr/lib64/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:135:in `require'
	 6: from /usr/lib64/ruby/gems/2.5.0/gems/fluentd-1.5.2/lib/fluent/command/fluentd.rb:310:in `<top (required)>'
	 5: from /usr/lib64/ruby/gems/2.5.0/gems/fluentd-1.5.2/lib/fluent/supervisor.rb:502:in `run_supervisor'
	 4: from /usr/lib64/ruby/gems/2.5.0/gems/fluentd-1.5.2/lib/fluent/supervisor.rb:597:in `supervise'
	 3: from /usr/lib64/ruby/gems/2.5.0/gems/fluentd-1.5.2/lib/fluent/supervisor.rb:577:in `dry_run'
	 2: from /usr/lib64/ruby/gems/2.5.0/gems/fluentd-1.5.2/lib/fluent/supervisor.rb:782:in `change_privilege'
	 1: from /usr/lib64/ruby/gems/2.5.0/gems/serverengine-2.1.1/lib/serverengine/privilege.rb:50:in `change'
/usr/lib64/ruby/gems/2.5.0/gems/serverengine-2.1.1/lib/serverengine/privilege.rb:50:in `groups=': Operation not permitted (Errno::EPERM)
```

**Comment by ganmacs** [comment]
Please see your log.

> `Operation not permitted`

You don't have permission to the specified user. 
Closing because you don't follow the contribution guide. https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md#got-a-question-or-problem

**Comment by jdrueckert** [comment]
> You don't have permission to the specified user.
@ganmacs Permission for what exactly? Isn't this exactly the purpose of providing "--user" and "--group": to run fluentd as this user of this group instead of almighty root?
Is it intended that fluentd crashes instead of exiting graciously with a well-understandable error message, e.g. which operation is not permitted and which permissions would be required?

I read the contribution guide but fluentd crashing directly when using documented parameters that don't mention any specific permissions being required felt more like a bug than a question..

**Comment by josephine-rueckert** [comment]
> You don't have permission to the specified user.

@ganmacs Permission for what exactly? Isn't this exactly the purpose of providing "--user" and "--group": to run fluentd as this user of this group instead of almighty root?
Is it intended that fluentd crashes instead of exiting graciously with a well-understandable error message, e.g. which operation is not permitted and which permissions would be required?

I read the contribution guide but fluentd crashing directly when using documented parameters that don't mention any specific permissions being required felt more like a bug than a question..

**Comment by repeatedly** [comment]
> with a well-understandable error message, e.g. which operation is not permitted and which permissions would be required?

This point is right. Basically, `setgroups` needs root permission so adding it to log message is better.

**Comment by josephine-rueckert** [comment]
Okay, so if I understand correctly, I'll need to start fluentd as root because `setgroups` needs root permission, but then the user and group set via the parameters will actually run it?

**Comment by ganmacs** [comment]
> Is it intended that fluentd crashes instead of exiting graciously with a well-understandable error message, e.g. which operation is not permitted and which permissions would be required?

Right. Sorry. It's my bad. This issue looks like we need to discuss.

> then the user and group set via the parameters will actually run it?

Yes. I confirmed.

```
$ cat Dockerfile
FROM ruby:2.6

RUN gem install fluentd
RUN groupadd -r fluent && useradd -r -g fluent fluent

ADD fluent.conf .

CMD ["fluentd", "--user", "fluent", "--group", "fluent", "-c", "fluent.conf"]
$ docker build -t test-user .
Sending build context to Docker daemon  3.072kB
Step 1/5 : FROM ruby:2.6
 ---> 682cc2f5b383
Step 2/5 : RUN gem install fluentd
 ---> Using cache
 ---> b1894b85a8f8
Step 3/5 : RUN groupadd -r fluent && useradd -r -g fluent fluent
 ---> Using cache
 ---> 13fe67ebcf99
Step 4/5 : ADD fluent.conf .
 ---> Using cache
 ---> 5c1a1389b0cb
Step 5/5 : CMD ["fluentd", "--user", "fluent", "--group", "fluent", "-c", "fluent.conf"]
 ---> Using cache
 ---> f001205fc76f
Successfully built f001205fc76f
Successfully tagged test-user:latest
$ docker run -it test-user
2019-08-01 02:37:43 +0000 [info]: parsing config file is succeeded path="fluent.conf"
2019-08-01 02:37:43 +0000 [warn]: both of Plugin @id and path for <storage> are not specified. Using on-memory store.
2019-08-01 02:37:43 +0000 [warn]: both of Plugin @id and path for <storage> are not specified. Using on-memory store.
2019-08-01 02:37:43 +0000 [info]: using configuration file: <ROOT>
  <source>
    @type dummy
    tag "dummy"
  </source>
  <match dummy>
    @type stdout
    <buffer>
      flush_interval 1s
    </buffer>
  </match>
</ROOT>
2019-08-01 02:37:43 +0000 [info]: starting fluentd-1.6.3 pid=1 ruby="2.6.3"
2019-08-01 02:37:43 +0000 [info]: spawn command to main:  cmdline=["/usr/local/bin/ruby", "-Eascii-8bit:ascii-8bit", "/usr/local/bundle/bin/fluentd", "--user", "fluent", "--group", "fluent", "-c", "fluent.conf", "--under-supervisor"]
2019-08-01 02:37:43 +0000 [info]: gem 'fluentd' version '1.6.3'
2019-08-01 02:37:43 +0000 [info]: adding match pattern="dummy" type="stdout"
2019-08-01 02:37:43 +0000 [info]: adding source type="dummy"
2019-08-01 02:37:43 +0000 [warn]: #0 both of Plugin @id and path for <storage> are not specified. Using on-memory store.
2019-08-01 02:37:43 +0000 [warn]: #0 both of Plugin @id and path for <storage> are not specified. Using on-memory store.
2019-08-01 02:37:43 +0000 [info]: #0 starting fluentd worker pid=8 ppid=1 worker=0
2019-08-01 02:37:43 +0000 [info]: #0 fluentd worker is now running worker=0
2019-08-01 02:37:44.063591900 +0000 dummy: {"message":"dummy"}
2019-08-01 02:37:45.079370200 +0000 dummy: {"message":"dummy"}
2019-08-01 02:37:46.094923300 +0000 dummy: {"message":"dummy"}
2019-08-01 02:37:47.016230800 +0000 dummy: {"message":"dummy"}
```

**Comment by josephine-rueckert** [comment]
> Yes. I confirmed.

@ganmacs Okay, thanks 🙂

**Comment by su7811659** [comment]
Hello, I was working on fluentd upgrades recently, and I encounter this problem, too.

**Describe the bug**
Fluentd crashes when it's started with the command 
**`fluentd --daemon <pid file> --user <user> --group <group> --config <conf_file> --log <log_file>`**
with the following error message:
/usr/local/share/gems/gems/serverengine-2.2.1/lib/serverengine/privilege.rb:50:in `groups=': Operation not permitted

However,  fluentd works without the option 'daemon' of the above command. 

**To Reproduce**
Start fluentd with `fluentd --daemon <pid file> --user <user> --group <group> --config <conf_file> --log <log_file>`

**Expected behavior**
No crash.

**Your Environment**
```
Operating system       CentOS 8.2.2004
ruby                   2.5.5p157
fluentd                1.11.2
fluent-plugin-sqlite3  1.0.2
```

**Your Error Log**

```
Starting fluentd: Traceback (most recent call last):
        16: from /usr/local/bin/fluentd:23:in `<main>'
        15: from /usr/local/bin/fluentd:23:in `load'
        14: from /usr/local/share/gems/gems/fluentd-1.11.2/bin/fluentd:8:in `<top (required)>'
        13: from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:59:in `require'
        12: from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:59:in `require'
        11: from /usr/local/share/gems/gems/fluentd-1.11.2/lib/fluent/command/fluentd.rb:341:in `<top (required)>'
        10: from /usr/local/share/gems/gems/fluentd-1.11.2/lib/fluent/supervisor.rb:562:in `run_supervisor'
         9: from /usr/local/share/gems/gems/fluentd-1.11.2/lib/fluent/supervisor.rb:712:in `supervise'
         8: from /usr/local/share/gems/gems/serverengine-2.2.1/lib/serverengine/daemon.rb:68:in `run'
         7: from /usr/local/share/gems/gems/serverengine-2.2.1/lib/serverengine/daemon.rb:107:in `main'
         6: from /usr/local/share/gems/gems/serverengine-2.2.1/lib/serverengine/daemon.rb:142:in `daemonize_with_double_fork'
         5: from /usr/local/share/gems/gems/serverengine-2.2.1/lib/serverengine/daemon.rb:142:in `fork'
         4: from /usr/local/share/gems/gems/serverengine-2.2.1/lib/serverengine/daemon.rb:150:in `block in daemonize_with_double_fork'
         3: from /usr/local/share/gems/gems/serverengine-2.2.1/lib/serverengine/daemon.rb:150:in `fork'
         2: from /usr/local/share/gems/gems/serverengine-2.2.1/lib/serverengine/daemon.rb:154:in `block (2 levels) in daemonize_with_double_fork'
         1: from /usr/local/share/gems/gems/serverengine-2.2.1/lib/serverengine/privilege.rb:50:in `change'
/usr/local/share/gems/gems/serverengine-2.2.1/lib/serverengine/privilege.rb:50:in `groups=': Operation not permitted (Errno::EPERM)

 ```

**Comment by piotrkochan** [comment]
same here, ubuntu 20

**Comment by pmoogi-redhat** [comment]
Same issue i am facing - 

fluentd  -v --user 0  --group 0  -c fluent-test-tail.conf 
2021-01-22 20:23:41 +0530 [info]: fluent/log.rb:329:info: parsing config file is succeeded path="fluent-test-tail.conf"
2021-01-22 20:23:41 +0530 [info]: fluent/log.rb:329:info: gem 'fluent-plugin-prometheus' version '1.8.5'
2021-01-22 20:23:41 +0530 [info]: fluent/log.rb:329:info: gem 'fluentd' version '1.12.0'
Traceback (most recent call last):
	
../.gem/ruby/gems/serverengine-2.2.2/lib/serverengine/privilege.rb:41:in `change_privilege': Operation not permitted (Errno::EPERM)

**Comment by pmoogi-redhat** [comment]
sudo fluentd .... also doesn't work. Can you help ?
