### ISSUE TITLE
Logs get duplicated when using tail plugin

### ISSUE THREAD

**Issue by CyberSeppi** [fluent/fluentd#2543]
Hi there,

I have this configuration 

Docker: fluent/fluentd:v1.6.2-debian-1.0

Fluent.conf

> @include conf.d/*.conf

conf.d/metrics.conf

```
<source>
  @type tail
  #path /fluentd/log/**/project/clusterDomain-*metrics*.log.0
  path /fluentd/log/**/SRV/node0/project/clusterDomain-i0_lpflexapp01-metrics.log.0
#  path /fluentd/log/**/*.log
  tag metric
  pos_file /fluentd/infra/metrics_file.pos
    <parse>
      @type grok
      custom_pattern_path /fluentd/grok_patterns
      <grok>
        pattern %{METRICSDATE:time}.*?\[(?<loglvl>.+?)\].+?##.+?End of call\: (?<method>.*).$
      </grok>
      <grok>
        pattern %{METRICSDATE:time}.*?\[(?<loglvl>.+?)\](?<message>.*)
      </grok>
      <grok>
        pattern (?<message>.*)
      </grok>
    </parse>
</source>
```

There are 2 other conf files in conf.d, but they are irrelevant atm.

The file z_output.conf look like that:

```
<match *>
  @type stdout
<match>
```

Now when I delete the pos file and start up the docker it tells me that it tails the file and then it waits.
Then when I just go in the file and save it again he processes all 42k lines in file.
Then I save it again (one more line) ...it processes all 42k (+1 line) lines....
and so on .....

normally I would say he can´t write pos file, but between these saves it looks like that

> /fluentd/log/SRV/node0/project/clusterDomain-i0_lpflexapp01-metrics.log.0       0000000000705d8d        00000000000fc001
and then
> /fluentd/log/SRV/node0/project/clusterDomain-i0_lpflexapp01-metrics.log.0       0000000000705e0f        00000000000fc001

I deleted the file before and it got created during startup again (it won´t recreate it though, when I delete it during the container is up)

Any ideas what I´m doing wrong ?

Thanks and cheers,

Julian

**Comment by CyberSeppi** [comment]
An addition is, that when I just go into the file and save it without changin anything, fluentd processes all 42k lines again and when I save it again it processes them again.....
The pos_file doesn´t change, but the logs all get processed again and again

**Comment by repeatedly** [comment]
Hmm... that's weird.
Could you show the complete command list to reproduce the issue?

**Comment by repeatedly** [comment]
I tested locally and works as expected:

```
% docker run -ti --rm -v /path/to/workdir:/fluentd/etc -v /path/to/workdir:/fluentd/log fluent/fluentd:v1.6.2-debian-1.0 -c /fluentd/etc/f.conf
2019-08-06 13:30:17 +0000 [info]: parsing config file is succeeded path="/fluentd/etc/f.conf"
2019-08-06 13:30:17 +0000 [info]: using configuration file: <ROOT>
  <source>
    @type tail
    path "/fluentd/log/**/data/test.log"
    tag "metric"
    pos_file "/fluentd/log/pos/metrics_file.pos"
    <parse>
      @type "none"
    </parse>
  </source>
  <match *>
    @type stdout
  </match>
</ROOT>
2019-08-06 13:30:17 +0000 [info]: starting fluentd-1.6.2 pid=7 ruby="2.6.3"
2019-08-06 13:30:17 +0000 [info]: spawn command to main:  cmdline=["/usr/local/bin/ruby", "-Eascii-8bit:ascii-8bit", "/usr/local/bundle/bin/fluentd", "-c", "/fluentd/etc/f.conf", "-p", "/fluentd/plugins", "--under-supervisor"]
2019-08-06 13:30:18 +0000 [info]: gem 'fluentd' version '1.6.2'
2019-08-06 13:30:18 +0000 [info]: adding match pattern="*" type="stdout"
2019-08-06 13:30:18 +0000 [info]: adding source type="tail"
2019-08-06 13:30:18 +0000 [info]: #0 starting fluentd worker pid=14 ppid=7 worker=0
2019-08-06 13:30:18 +0000 [info]: #0 following tail of /fluentd/log/data/test.log
2019-08-06 13:30:18 +0000 [info]: #0 fluentd worker is now running worker=0
2019-08-06 13:30:22.617905809 +0000 metric: {"message":"hello"}
2019-08-06 13:30:24.457150884 +0000 metric: {"message":"hello"}
2019-08-06 13:30:29.681523063 +0000 metric: {"message":"hello hello"}
```

- add log

```
% echo 'hello' >> log/data/test.log
% echo 'hello' >> log/data/test.log
% echo 'hello hello' >> log/data/test.log
```

**Comment by CyberSeppi** [comment]
omg .... I did it with nano ....... editing the log file I mean ....
nano seems to replace the whole file somehow or does something else that makes fluentd´s _in_tail to process the whole file again ....

When I do it with echo it works ...... omg .... I´m the worst developer out there :-)

Many thanks man!.....
