### ISSUE TITLE
fluentd memory leak

### ISSUE THREAD

**Issue by 27bharath** [fluent/fluentd#2562]
**Describe the bug**
Fluentd is consuming high memory if we increase high volume of messages.

**Environment**
- Fluentd 1.1.1 version

**Test Case 1**
Messages : 2000 messages per second from 140 log files
```
<match data-**>
    @type kafka_buffered
    brokers "xx.xxx.x.xxx:xxxx,xx.xxx.x.xxx:xxxx,xx.xxx.x.xxx:xxxx"
    default_topic test-data
    flush_interval 5s
    kafka_agg_max_bytes 1000000
    max_send_limit_bytes 5000000
    discard_kafka_delivery_failed true
    #data type settings
    output_data_type json
    compression_codec gzip
    #producer settings
    max_send_retries 1
    required_acks 1
    get_kafka_client_log true	
\</match>
```
With above configuration we tested and observed there is gradually memory increase (Initially used 250 MB) in the production server and utilized all the server memory (15GB) which was available in over period of time (within 2 weeks)

**Test Case 2**
```
<match data-**>
    @type kafka_buffered
    brokers "xx.xxx.x.xxx:xxxx,xx.xxx.x.xxx:xxxx,xx.xxx.x.xxx:xxxx"
    default_topic test-data
    flush_interval 5s
    kafka_agg_max_bytes 1000000
    max_send_limit_bytes 5000000
    discard_kafka_delivery_failed true
    #data type settings
    output_data_type json
    compression_codec gzip
    #producer settings
    max_send_retries 1
    required_acks 1
    get_kafka_client_log true
	\<buffer>
               @type file
		path /usr/local/fluentd/buffer
		chunk_limit_size 10MB 
		total_limit_size 100MB
		chunk_full_threshold 0.7 
		compress gzip 
		flush_mode default
		flush_interval 5s
		flush_thread_count 2
		overflow_action block
		retry_timeout 2m
	\</buffer>
\</match>
```
With the above configuration observed the same and it consumed all memory as same as Test case 1 and memory is not flushing even after all the messages are pushed to kafka.

Please help us on how we can limit the memory resource usage for high volume messages through fluentd configuration

**Comment by repeatedly** [comment]
Could you test it with latest fluentd and `out_kafka2` instead of `out_kafka_buffered`?
Your first case uses one flush thread and memory buffer. So if the problem happens on your kafka cluster or network, memory usage is increasing.

**Comment by ganmacs** [comment]
No response from the author for a long time. I'm closing. but feel free to notify us if any problems.
