### ISSUE TITLE
Fluentd v1.6 performance is  worse than v0.12

### ISSUE THREAD

**Issue by chenguolin** [fluent/fluentd#2570]
hi ~
     i use https://github.com/fluent/fluentd-benchmark test Fluentd performance. The original is expected Fluentd v1.6 is better than v0.12.x，but the result is opposite
    here is my test data
    
    Fluent v0.12
![image](https://user-images.githubusercontent.com/5453241/63148714-a45e8100-c034-11e9-83dc-a8d71f534b57.png)

    Fluentd v1.6
![image](https://user-images.githubusercontent.com/5453241/63148730-b17b7000-c034-11e9-8cf0-6692fb20f14b.png)

**Comment by chenguolin** [comment]
@repeatedly please help me，thanks~

**Comment by repeatedly** [comment]
> The original is expected Fluentd v1.6 is better than v0.12.x

We don't say v1 is faster than v0.12 because v1's focus is flexibility for more usecase support.
Yeah, your result is slower than expected because 2000 qps is small traffic but v0.12/v1 consumes 50+% CPU usage.
