### ISSUE TITLE
TimeZone configuration bug

### ISSUE THREAD

**Issue by zakariahoussa** [fluent/fluentd#2575]
**Describe the bug**
I try to use to set the timezone on parser as you describe in the doc
---------------------------------------------------------------------------------------------------------
timezone (string) (optional): use specified timezone. one can parse/format the time value in the specified timezone.
Default: nil
Available time zone format:
[+-]HH:MM (e.g. "+09:00") (recommended)
[+-]HHMM (e.g. "+0900")
[+-]HH (e.g. "+09")
Region/Zone (e.g. "Asia/Tokyo")
Region/Zone/Zone (e.g. "America/Argentina/Buenos_Aires")
---------------------------------------------------------------------------------------------------------

It works fine for "+09:00" but not with Region/Zone.

**Your Environment**

- Fluentd or td-agent version: `fluentd --version` or `td-agent --version`
fluentd --version
- Operating system: `cat /etc/os-release`
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

- Kernel version: `uname -r`
Kubernetes

**Your Configuration**
```
<source>
  @type syslog
  tag syslog
  port 514
  bind 0.0.0.0
  protocol_type tcp
  message_length_limit 2048   # 2048 by default
  <parse>
    message_format auto
    timezone  "Asia/Tokyo"
  </parse>
</source>
```
**Your Error Log**

/var/lib/gems/2.3.0/gems/fluentd-1.3.3/lib/fluent/time.rb:206:in `-': nil can't be coerced into Fixnum (TypeError)
from /var/lib/gems/2.3.0/gems/fluentd-1.3.3/lib/fluent/time.rb:206:in `initialize'
from /var/lib/gems/2.3.0/gems/fluentd-1.3.3/lib/fluent/time.rb:169:in `new'
from /var/lib/gems/2.3.0/gems/fluentd-1.3.3/lib/fluent/time.rb:169:in `time_parser_create'
from /var/lib/gems/2.3.0/gems/fluentd-1.3.3/lib/fluent/plugin/parser.rb:64:in `configure'
from /var/lib/gems/2.3.0/gems/fluentd-1.3.3/lib/fluent/plugin/parser_syslog.rb:48:in `configure'
from /var/lib/gems/2.3.0/gems/fluentd-1.3.3/lib/fluent/plugin.rb:164:in `configure'
from /var/lib/gems/2.3.0/gems/fluentd-1.3.3/lib/fluent/plugin_helper/parser.rb:90:in `block in configure'
from /var/lib/gems/2.3.0/gems/fluentd-1.3.3/lib/fluent/plugin_helper/parser.rb:85:in `each'
from /var/lib/gems/2.3.0/gems/fluentd-1.3.3/lib/fluent/plugin_helper/parser.rb:85:in `configure'
from /var/lib/gems/2.3.0/gems/fluentd-1.3.3/lib/fluent/plugin/in_syslog.rb:110:in `configure'
from /var/lib/gems/2.3.0/gems/fluentd-1.3.3/lib/fluent/plugin.rb:164:in `configure'
from /var/lib/gems/2.3.0/gems/fluentd-1.3.3/lib/fluent/root_agent.rb:282:in `add_source'
from /var/lib/gems/2.3.0/gems/fluentd-1.3.3/lib/fluent/root_agent.rb:122:in `block in configure'
from /var/lib/gems/2.3.0/gems/fluentd-1.3.3/lib/fluent/root_agent.rb:118:in `each'
from /var/lib/gems/2.3.0/gems/fluentd-1.3.3/lib/fluent/root_agent.rb:118:in `configure'
from /var/lib/gems/2.3.0/gems/fluentd-1.3.3/lib/fluent/engine.rb:131:in `configure'
from /var/lib/gems/2.3.0/gems/fluentd-1.3.3/lib/fluent/engine.rb:96:in `run_configure'
from /var/lib/gems/2.3.0/gems/fluentd-1.3.3/lib/fluent/supervisor.rb:795:in `run_configure'
from /var/lib/gems/2.3.0/gems/fluentd-1.3.3/lib/fluent/supervisor.rb:579:in `dry_run'
from /var/lib/gems/2.3.0/gems/fluentd-1.3.3/lib/fluent/supervisor.rb:597:in `supervise'
from /var/lib/gems/2.3.0/gems/fluentd-1.3.3/lib/fluent/supervisor.rb:502:in `run_supervisor'
from /var/lib/gems/2.3.0/gems/fluentd-1.3.3/lib/fluent/command/fluentd.rb:310:in `<top (required)>'
from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
from /var/lib/gems/2.3.0/gems/fluentd-1.3.3/bin/fluentd:8:in `<top (required)>'
from /usr/local/bin/fluentd:22:in `load'
from /usr/local/bin/fluentd:22:in `<main>'

**Comment by repeatedly** [comment]
This is fixed since v1.5.1: https://github.com/fluent/fluentd/pull/2421
Try latest version :)
