### ISSUE TITLE
missing time and tag when using out_file plugin with @type json

### ISSUE THREAD

**Issue by shinji3887** [fluent/fluentd#2581]
Check [CONTRIBUTING guideline](https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md) first and here is the list to help us investigate the problem.

**Describe the bug**

I am running fluentd in a kubernetes cluster and use fluentd to create logs on the work node,and I use `out_file` plugin to do this.
My Configuration is like this
```xml
<match pattern>
  @type file
  path /var/log/fluent/myapp
  compress gzip
  <buffer>
    timekey 1d
    timekey_use_utc true
    timekey_wait 10m
  </buffer>
  <format>
    @type json
  </format>
</match>
```
this Configuration can create logs on path ` /var/log/fluent/myapp` correctly but the **time** and **tag** attributes are missing while the docs says they shoube be there.

**To Reproduce**

```json
{"stream":"stdout","docker":{"container_id":"a7e01168b2db8037409974fac4bd0f3363d0fd237566026571baeafeb0d45c1b"},"kubernetes":{"container_name":"dashboard-vue","namespace_name":"dcs","pod_name":"daocloud-dcs-dashboard-vue-5b7c894f74-bgrd9","container_image":"daocloud.io/dc_pokeman/daocloud-dashboard-vue:2.6.2","container_image_id":"docker://sha256:466f8a440e38eca36d5c0add7cc546b18a80b2542959afb04b0056d1ec8446c7","pod_id":"7d401d4a-a921-11e9-895f-0242ac120003","host":"dce304-cal-vm1","labels":{"daocloud-dcs-module-name":"dashboard-vue","pod-template-hash":"1637450930"},"master_url":"https://10.96.0.1:443/api","namespace_id":"0b5e3b58-4092-11e9-818e-0242ac120003"},"message":"22.196.66.224 - - [20/Aug/2019:06:00:32 +0000] \"GET /ping HTTP/1.1\" 200 832 \"-\" \"kube-probe/1.10\" \"-\"\n"}
```

**Expected behavior**

```json
{"time": "2014-08-25 00:00:00 +0000", "tag":"foo.bar","stream":"stdout","docker":{"container_id":"a7e01168b2db8037409974fac4bd0f3363d0fd237566026571baeafeb0d45c1b"},"kubernetes":{"container_name":"dashboard-vue","namespace_name":"dcs","pod_name":"daocloud-dcs-dashboard-vue-5b7c894f74-bgrd9","container_image":"daocloud.io/dc_pokeman/daocloud-dashboard-vue:2.6.2","container_image_id":"docker://sha256:466f8a440e38eca36d5c0add7cc546b18a80b2542959afb04b0056d1ec8446c7","pod_id":"7d401d4a-a921-11e9-895f-0242ac120003","host":"dce304-cal-vm1","labels":{"daocloud-dcs-module-name":"dashboard-vue","pod-template-hash":"1637450930"},"master_url":"https://10.96.0.1:443/api","namespace_id":"0b5e3b58-4092-11e9-818e-0242ac120003"},"message":"22.196.66.224 - - [20/Aug/2019:06:00:32 +0000] \"GET /ping HTTP/1.1\" 200 832 \"-\" \"kube-probe/1.10\" \"-\"\n"}
```

**Your Environment**

- Fluentd or td-agent version: 1.5.1
- docker image version: quay.io/fluentd_elasticsearch/fluentd:v2.6.0
- deployment yaml version: https://raw.githubusercontent.com/kubernetes/kubernetes/master/cluster/addons/fluentd-elasticsearch/fluentd-es-ds.yaml
- Operating system: centos 7.6
- Kernel version: 3.10.0-862.el7.x86_64

If you hit the problem with older fluentd version, try latest version first.

**Your Configuration**

```
<!-- Write your configuration here -->
```

**Your Error Log**

```
<!-- Write your **ALL** error log here -->
```

**Additional context**

**Comment by shinji3887** [comment]
and I don't understand what's below mean in the offical docs:
```
By default, json formatter result doesn't contain tag and time field.
```
How can I contain tag and time field?

**Comment by repeatedly** [comment]
Use `<inject>` for it: https://docs.fluentd.org/output/file#less-than-inject-greater-than-section
BTW, this is question and it doesn't follow contribution guide. So please use ML first.

**Comment by shinji3887** [comment]
`<inject>` does works! thx a lot!
