### ISSUE TITLE
How to read SQL server Tracefile

### ISSUE THREAD

**Issue by yeruvass** [fluent/fluentd#2588]
Hi Fluentd,

Is it possible to read SQL server tracefile logs via fluentd.
Below script I tried but giving not readable format.
Do we have any option to read this scenario.

<source>
  @type tail
  path **D:/Program Files/Microsoft SQL Server/MSSQL13.MSSQLSERVER/MSSQL/Log/log_64.trc**
  pos_file C:/opt/td-agent/etc/td-agent/pos/test.pos
  tag apache.access
  format none
</source>

<match **>
  @type stdout
</match>

Please help me to answer this question.

**Comment by ganmacs** [comment]
Please follow the [CONTRIBUTION guide](https://github.com/fluent/fluentd/blob/a81a54eea3ccfc0a63e0a41476c1f76f8e7bf9ad/CONTRIBUTING.md)

could you post these kinds of question on google groups?
