### ISSUE TITLE
S3 Encryption

### ISSUE THREAD

**Issue by Shayner85** [fluent/fluentd#2596]
When using the S3 output plugin to a S3 bucket that has aws:kms the S3 file overview states server-side encryption: access denied.  The permissions within AWS are set to allow:
"Action": [
                "s3:PutObject*",
                "s3:GetObject",
                "s3:ListBucket"
            ],

Not the * on PutObject that would allow ACL as well.

In fluentd conf file the aws:kms information is specified. the S3 bucket prevents uploading of non encrypted files however, the file is uploaded and there is an error with encryption stating access denied.  The fix has been to re-encrypt the file using the same AWS encryption key.  Without this re-encryption the file can not be selected from the S3 console within AWS or useable by Glue or Athena.

Spent days trying different things and validating configurations and this looks to be a potential bug with the S3 output plugin when using AWS server side encryption.

**Comment by ganmacs** [comment]
This is not a core issue. could you please re-issue in https://github.com/fluent/fluent-plugin-s3?

**Comment by evertonevaristo** [comment]
@Shayner85 this setup it's cross-account? maybe you're uploading the file with a kms key that belongs to other account.
