### ISSUE TITLE
In_exec command output directly parsed to single key

### ISSUE THREAD

**Issue by s-shubh** [fluent/fluentd#2611]
I have installed td-agent recently and I am about to discover its in_exec plugin behavior against multiline output.

Exec Command -

#free -m
               total        used        free      shared  buff/cache   available 
Mem:           1838         921         101          15      815         668 
Swap:          2047          89        1958

I want to parse this entire output values in one key as message. 

Please help.

My config is shown below.

```
<source>
   @type exec
   command free -m 
   <parse>
     @type regexp
     expression /(?<message>(.*\n))/m
   </parse>
  tag my_linux
  run_interval 10m
</source>
<match my_linux>
@type file
@id linux_mem
path /var/log/td-agent/td-linux_mem
</match>
```

**Comment by ganmacs** [comment]
> If you have further questions about Fluentd and plugins, please direct these to Mailing List. Don't use Github issue for asking questions. Here are examples:

https://github.com/fluent/fluentd/blob/07d9eecf0ce1413ab7873da84462b6f8fe9fae04/CONTRIBUTING.md
