### ISSUE TITLE
Output stdout do not working

### ISSUE THREAD

**Issue by tuananh170489** [fluent/fluentd#2612]
Hi guys, I have a case with below config but output to stdout do not working
My config:
```
<source>
  @type tail
  path /var/log/td-agent/nagios-*-bandwidth.log
  pos_file /var/log/td-agent/nagios.pos
  <parse>
    @type regexp
    expression /^\[(?<time>.+)\] (?<title>[\w\s]+): (?<item>[\w-]+); (?<bandwidth>.+): (?<num>\d+);(?<alert>\w+);(?<type>\w+);(?<index>\d+);(?<message>.+)$/
    time_key time
    time_type unixtime
  </parse>
  tag opsview
  rotate_wait 5
  refresh_interval 60
  read_from_head true
</source>

<match opsview>
  @type stdout
  <format>
    @type stdout
    output_type json
  </format>
</match>
```
My config syntax is okie, but /var/log/td-agent/td-agent.log is empty.
Can everybody help me?
Thank a lot!

**Comment by ganmacs** [comment]
> If you have further questions about Fluentd and plugins, please direct these to Mailing List. Don't use Github issue for asking questions. Here are examples:

https://github.com/fluent/fluentd/blob/07d9eecf0ce1413ab7873da84462b6f8fe9fae04/CONTRIBUTING.md
