### ISSUE TITLE
Fluentd Kafka buffered output plugin credential encryption support

### ISSUE THREAD

**Issue by xPB12** [fluent/fluentd#2623]
Check [CONTRIBUTING guideline](https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md) first and here is the list to help us investigate the problem.

**Is your feature request related to a problem? Please describe.**

Current FluentD Kafka buffered output plugin required credentials to be stored in plain text on the disk which pose security risk.

**Describe the solution you'd like**

We would like to have some encryption mechanism for the credentials to be stored in encrypted form and be decrypted on the fly.

**Describe alternatives you've considered**

Credentials being fetched from some vault using CURL request.

**Comment by ganmacs** [comment]
This is https://github.com/fluent/fluent-plugin-kafka/ issue, right?
could you re-created this issue at fluent-plugin-kafka repo?

**Comment by ganmacs** [comment]
if you have a question, please create an issue at https://github.com/fluent/fluent-plugin-kafka/ .
thanks for your corporation
