### ISSUE TITLE
unable to send the logs to s3 while using aws-elastic-search-plugin

### ISSUE THREAD

**Issue by nareshnani529** [fluent/fluentd#2625]
#### Problem
Unable to send logs to AWS ES and S3 at same time and nothing shows up in logs. At this point of time would like to check AWS ES plugin will support s3? If any inputs highly apperciated

Td-agent version : 2.5.x

Infrastructure > AWS ECS > Fluentd Aggregrators (2 instances and load balanced) > ES > Kibana

As we see some lags (5 to 6mins) in logs processing would like to check with adding other output(like s3) to view the logs. Is this right action to take?

Config :

```
<source>
        @type forward
        @id input_forward
</source>


<filter *.**>
  @type record_transformer
 <record>
    container_id ${record["container_id"]}
  </record>


<match *.**>
        type aws-elasticsearch-service
        logstash_format true
        logstash_prefix ${tag[0]}
        include_tag_key true
        tag_key "Application_name"
        flush_interval 5s

    <buffer>
      flush_at_shutdown true
      flush_mode immediate
      flush_thread_count 8
      flush_thread_interval 1
      flush_thread_burst_interval 1
      retry_forever true
      retry_type exponential_backoff
    </buffer>

        <endpoint>
                url https://vpc-xxxx.aws.amazon.com
                region us-east-1
                access_key_id "xxxxxxxxxxxxxxxx"
                secret_access_key "xxxxxxxxxxxxxxxxxxxx"
        </endpoint>
</match>
```
* OS version - Ubuntu 18.04 LTS
td-agent version : 2.5
* AWS ES version - 6.8
* fluent-plugin-aws-elasticsearch-service (2.1.0)

**Comment by ganmacs** [comment]
dups https://github.com/fluent/fluentd-kubernetes-daemonset/issues/351
