### ISSUE TITLE
Install fluentd on Windows - No UI and meeting blocker

### ISSUE THREAD

**Issue by ggpaue** [fluent/fluentd#2627]
Check [CONTRIBUTING guideline](https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md) first and here is the list to help us investigate the problem.

**Is your feature request related to a problem? Please describe.**

Install fluentd on Windows

**Describe the solution you'd like**

Install fluentd on Windows

**Describe alternatives you've considered**

I really like the solution introduced here:
https://docs.fluentd.org/installation/install-by-msi
I'm stuck at step 4 start Fluentd Window Service
because currently I only have kubernetes worker node cmd, no windows ui available, can we have a cmd installation instruction?

**Additional context**

**Comment by repeatedly** [comment]
Need from windows/docker expert.

**Comment by cosmo0920** [comment]
I'll take a look on this.

**Comment by cosmo0920** [comment]
`net.exe` can handle Windows service start/stop synchronously.

```log
PS C:\Users\hhatake> net start fluentdwinsvc
The Fluentd Windows Service service is starting.
The Fluentd Windows Service service was started successfully.
```

```log
PS C:\Users\hhatake> net stop fluentdwinsvc
The Fluentd Windows Service service is stopping.
The Fluentd Windows Service service was stopped successfully.
```

**Comment by repeatedly** [comment]
Thanks @cosmo0920 !

**Comment by ggpaue** [comment]
@cosmo0920 thanks for the solution, it works out
