### ISSUE TITLE
Restart fluentd ,it's tail the new file ,not according to  file's inode to listen file！

### ISSUE THREAD

**Issue by XiaoGe2030** [fluent/fluentd#2628]
my td-agent's conf file like follow:

![image](https://user-images.githubusercontent.com/22184388/65480259-6a01c280-dec3-11e9-8bd2-fab653b87ea0.png)

my log4j config xml file like :
![image](https://user-images.githubusercontent.com/22184388/65480271-738b2a80-dec3-11e9-8d23-fab76537a973.png)

First only slow.log file ,ta-agent work well .when slow.file is near 9M，I systemctl stop td-agent , and  Keep writing data ，until slow.file more than 10M . Then , there are two files , slow.log and slow.log.1 . Finally ,I systemcl start td-agent ,I found td-agent just tail the new file(slow.log) , the data in the old file (slow.log.1 is renamed from slow.log) did not sent to  remote_syslog 。That's why? ??

**Comment by ganmacs** [comment]
Because you specify slow.log. so td-agent won't check other paths.
also See https://github.com/fluent/fluentd/blob/8535c9a5b0ee4f7e3b0dd65de8954f9436eafecc/CONTRIBUTING.md#got-a-question-or-problem
