### ISSUE TITLE
Need to downgrade tzinfo for fluent-pluigin that depends on ActiveSupport?

### ISSUE THREAD

**Issue by ganmacs** [fluent/fluentd#2634]
**This is just a reminder for fluentd team**.

ref: https://github.com/fluent/fluentd/pull/2479

>  Looks like this PR made things a bit more complex for fluentd plugins that depend on ActiveSupport (e.g. fluent-plugin-splunk-hec). Because Rails and ActiveSupport have hard dependency on tzinfo v1.1 (see rails/rails#34799) it conflicts with v2.0 requirements that this PR added.

**Comment by repeatedly** [comment]
I'm not sure...
For example, fluent-plugin-splunk-hec depends on activesupport via fluent-plugin-kubernetes-metadata-filter/kubeclient. fluent-plugin-splunk-hec doesn't need to depend on this plugin. I think this is bug of fluent-plugin-splunk-hec.
