### ISSUE TITLE
How to merge java multi-line error log?

### ISSUE THREAD

**Issue by forewei** [fluent/fluentd#2641]
Check [CONTRIBUTING guideline](https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md) first and here is the list to help us investigate the problem.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ganmacs** [comment]
Please read this https://github.com/fluent/fluentd/blob/a14af3066bec35c7c2bd47e75953b3428a26ac00/CONTRIBUTING.md#got-a-question-or-problem

**Comment by forewei** [comment]
hello, I can't find the configuration of the merge error log through the official website.Is fluentd not supported?
