### ISSUE TITLE
[question] how to collect logs from strftime dynamic path?

### ISSUE THREAD

**Issue by ted222** [fluent/fluentd#2644]
hello guys, I want to use fluentd to collect logs from strftime dynamic path, for example the time now is 9:32:06, then we have a log in path /app/logs/xx191010/09/32/06/a.log, almost every second the system  prints logs like this, and my fluentd config is like this:

![image](https://user-images.githubusercontent.com/30408499/66533576-fd82f680-eb45-11e9-91c7-8acdb97e48f7.png)

the question is :
at 9:32:06 , in the path there is a .log :  /app/logs/xx191010/09/32/06/a.log
the last log item in a.log is 9:34:02, but the refresh_interval default is 60s, is this means that I have lost  the logs between 9:33:00 - 9:34:02 in a.log , just because after refresh , the fluentd doesn't colloct logs in /app/logs/xx191010/09/32/06 but collect logs in the new path /app/logs/xx191010/09/33/* ?
how to config fluentd to solve this problem? thanks

**Comment by repeatedly** [comment]
> how to config fluentd to solve this problem?

Set shorter `refresh_interval`.

**Comment by repeatedly** [comment]
Ah, wait. 06 is second?

**Comment by ted222** [comment]
> Ah, wait. 06 is second?
> If you use `**/*` in the path with shorter `refresh_interval`, all files under /app/logs/xx191010/09/32/ should be collected.
> 
> BTW, your system is very weird. Creating log files per second is not efficient...

thanks, if the refresh_interval set to 1s, the next second a new log b.log will be written and follow by fluentd , after refresh , a.log which was born at last second is still followed by fluentd?  How to config fluentd to follow the log file from the file borned and keep follow an hour?

**Comment by ted222** [comment]
@masaki

> Ah, wait. 06 is second?
> If you use `**/*` in the path with shorter `refresh_interval`, all files under /app/logs/xx191010/09/32/ should be collected.
> 
> BTW, your system is very weird. Creating log files per second is not efficient...

how mang files can fluentd follow at the sametime?I guess in my situation, single fluentd mast keep following nearly 200 thousand files, can fluentd hold this? if I use the strftime dynamic path /home/lamp/cin/logs/HB%y%m%d/%H/%M/%S/**/*.log and set the refresh interval to 1s, the next second the path is changed, fluentd still follow the logs in the last second path?   The para rotate_wait means fluentd keep tailing the log file for rotate_wait time long? please, thanks!
