### ISSUE TITLE
[out_http] missing timestamp field

### ISSUE THREAD

**Issue by roycarser** [fluent/fluentd#2650]
Check [CONTRIBUTING guideline](https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md) first and here is the list to help us investigate the problem.

**Describe the bug**

the json generated by out_http don't contain event time

**To Reproduce**

**Expected behavior**

the event time is contained in the json body
**Your Environment**

- Fluentd or td-agent version: `fluentd --version` or `td-agent --version`
fluentd v1.7.3 in docker 
- Operating system: `cat /etc/os-release`
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.9.4
PRETTY_NAME="Alpine Linux v3.9"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://bugs.alpinelinux.org/"

If you hit the problem with older fluentd version, try latest version first.

**Your Configuration**

```
<system>
  workers 2
</system>

<source>
  @type forward
  port 24224
  bind 0.0.0.0
</source>

<filter **>
  @type record_transformer
  <record>
    # you should set time field manually
    time ${time}
  </record>
</filter>

<match **>
    @type http
    endpoint http://logging-aggregator.istio-system.svc.cluster.local:8080
    retryable_response_codes  [503,429]
</match>

<!-- Write your **ALL** error log here -->
```

**Additional context**

**Comment by repeatedly** [comment]
I can't reproduce this problem on my test.

```
<system>
  workers 2
</system>

<source>
  @type forward
  port 24224
</source>

<filter test.**>
  @type record_transformer
  <record>
    # you should set time field manually
    time ${time}
  </record>
</filter>

<match test.**>
  @type http
  endpoint http://localhost:8000/test
  retryable_response_codes [503,429]
  <buffer>
    flush_interval 5s # for test
  </buffer>
</match>
```

- example server

```
require 'webrick'
require 'webrick/https'

s = WEBrick::HTTPServer.new(:Port => 8000,
                            :HTTPVersion => WEBrick::HTTPVersion.new('1.2'))
s.mount_proc('/test') { |req, res|
  puts req.body
  res['Content-Type'] = 'text/plain'
  res.body = 'Hi!'
}

Signal.trap('INT'){ s.shutdown }
s.start
```

- server output

```
[2019-10-15 14:48:50] INFO  WEBrick 1.4.2
[2019-10-15 14:48:50] INFO  ruby 2.6.3 (2019-04-16) [x86_64-darwin18]
[2019-10-15 14:48:50] INFO  WEBrick::HTTPServer#start: pid=40747 port=8000
{"message":"hello","time":"2019-10-15 14:48:46 +0900"}
```

**Comment by roycarser** [comment]
sorry,there is a mistake in our enviroment
