### ISSUE TITLE
Quick Start is broken

### ISSUE THREAD

**Issue by nokute78** [fluent/fluentd#2659]
Check [CONTRIBUTING guideline](https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md) first and here is the list to help us investigate the problem.

**Describe the bug**

Quick Start is broken at git master.
out_forward with @id may not work.

It works on v1.7.3.

**To Reproduce**

```
$ mkdir tmp
$ bin/fluentd -s tmp
$ bin/fluentd -c tmp/fluent.conf
```

**Expected behavior**

Fluentd works.

**Your Environment**

- Fluentd or td-agent version: `fluentd --version` or `td-agent --version`
git master b1bd1dab520f4a4592e96e4ba64908a4e6aa6c65
- Operating system: `cat /etc/os-release`
Ubuntu 18.04
```
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```
- Kernel version: `uname -r`
5.0.0-31-generic

If you hit the problem with older fluentd version, try latest version first.

**Your Configuration**
https://github.com/fluent/fluentd/blob/b1bd1dab520f4a4592e96e4ba64908a4e6aa6c65/fluent.conf

**Your Error Log**

```
$ bin/fluentd -c tmp/fluent.conf 
2019-10-18 22:56:11 +0900 [info]: parsing config file is succeeded path="tmp/fluent.conf"
2019-10-18 22:56:11 +0900 [info]: adding forwarding server '192.168.0.12:24224' host="192.168.0.12" port=24224 weight=60 plugin_id="object:2b0a500b55c4"
2019-10-18 22:56:11 +0900 [error]: config error file="tmp/fluent.conf" error_class=Fluent::ConfigError error="Duplicated plugin id `forward_output`. Check whole configuration and fix it."
$ 
```

**Additional context**
It works on v1.7.3.
#2541 seems to break Quick Start.

**Comment by ganmacs** [comment]
Thanks. I'll check it next Monday!

**Comment by ganmacs** [comment]
this issue has been fixed in https://github.com/fluent/fluentd/pull/2661 . Thank you for the report!

**Comment by nokute78** [comment]
It works!
Thank you for fixing.
