### ISSUE TITLE
record_transformer don't change type on the same key

### ISSUE THREAD

**Issue by cde0** [fluent/fluentd#2662]
**Describe the bug**
Hello, I don't know if is a bug or the default behaviour from fluentd. 
I want to convert a key in fluentd from string to date.
When i convert it and send to elastic, elastic show that is a string and not a date.

Elastic only show the type is date when the two keys on the @type record_transformer is not the same/

**To Reproduce**

1. log_time_2  ${require 'time'; Time.parse(record["log_time"]).strftime("%Y-%m-%dT%H:%M:%S.%LZ")}

**Elastic show date on the field**

2. log_time ${require 'time'; Time.parse(record["log_time"]).strftime("%Y-%m-%dT%H:%M:%S.%LZ")}

**Elastic show string on the field**

**Expected behavior**
I was expecting to get date field on elastic.

- Fluentd or td-agent version: td-agent 1.7.0
- Operating system: Ubuntu 18.04.2 LTS
- Kernel version: 4.15.0-55-generic

**Your Configuration**

```
<filter providers_pricing>
  @type record_transformer
  enable_ruby true
  auto_typecast true
  <record>
    log_time ${require 'time'; Time.parse(record["log_time"]).strftime("%Y-%m-%dT%H:%M:%S.%LZ")}
  </record>
</filter>
```

**Your Error Log**

```
No error log
```

Cheers

**Comment by ganmacs** [comment]
See https://github.com/fluent/fluentd/blob/8535c9a5b0ee4f7e3b0dd65de8954f9436eafecc/CONTRIBUTING.md#got-a-question-or-problem
