### ISSUE TITLE
Can not specify index format(add timestamp) when output to elasticsearch 

### ISSUE THREAD

**Issue by linbingdouzhe** [fluent/fluentd#2676]
hi
i use fluentd transfer log file to elasticsearch . and i dont want to use logstash format , i use index_name to specify the index name . 
this is my output conf file:

```
  output.conf: |
    <match **>
      @id elasticsearch
      @type elasticsearch
      include_tag_key true
      # Replace with the host/port to your Elasticsearch cluster.
      host "elasticsearch-master.elk.svc.cluster.local"
      port "9200"
      scheme "http"
      ssl_version "TLSv1"
      index_name dma-service-%Y.%m.%d
      <buffer>
        @type file
        path /var/log/fluentd-buffers/kubernetes.system.buffer
        flush_mode interval
        retry_type exponential_backoff
        flush_thread_count 2
        timekey 1h
        flush_interval 5s
        retry_forever
        retry_max_interval 30
        chunk_limit_size "#{ENV['OUTPUT_BUFFER_CHUNK_LIMIT']}"
        queue_limit_length "#{ENV['OUTPUT_BUFFER_QUEUE_LIMIT']}"
        overflow_action block
      </buffer>
    </match>

```

but when i deploy that on k8s , i see the kibana index is" dma-service-%y.%m.%d ". It's not a date format , just a string . is this is a bug ? or my configure file have some problem ?

@pjjw

**Comment by repeatedly** [comment]
We don't know because we are not fluent-plugin-elasticsearch maintainers.
Please check contribution guide before posting issue on fluentd repository: https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md#got-a-question-or-problem
