### ISSUE TITLE
reverse from json format file to raw file

### ISSUE THREAD

**Issue by zffocussss** [fluent/fluentd#2691]
Hi team:
            I am using td-agent 1.7.4 on Ubuntu 18. I use udp to collect logs from remote server.
           I want to store record in both ES and local file under a path.
           All the above job is fine now.But I have a question about the log format on local file.because I use parse section inside source.so I can find the json format records in the log.how can I make the record raw before parsed by regex and other formaters?

**Comment by zffocussss** [comment]
I use @type copy inside match section

**Comment by ganmacs** [comment]
please see https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md#got-a-question-or-problem
