### ISSUE TITLE
[question]how the fluentd detect the rotation of a log file?

### ISSUE THREAD

**Issue by ted222** [fluent/fluentd#2692]
hello , I've met a problem when I used fluentd to collect logs.
here is my conf:
![image](https://user-images.githubusercontent.com/30408499/68724034-6225eb00-05f5-11ea-82f3-0b1c5cb87524.png)

when the fluentd started, the td-agent.log showed "following tail of /home/sn/log/sn-10.log", after a few seconds, the log showed “detected rotation of /home/sn/log/sn-10.log; waiting 5 seconds”, it just liked the file pointer was changed , fluentd read the log file from head, but I used the ls -l to check the log file sn-10.log, it wasn't changed ! so I want to ask how fluentd detect the rotation of file? thanks

**Comment by ganmacs** [comment]
the condition to detect the rotation is here.
If the file's inode changed and the file size is smaller than previous status of size, fluentd identified the log rotation occurred.

https://github.com/fluent/fluentd/blob/8b46fd0240243d865315fe46c67efa09c78924f1/lib/fluent/plugin/in_tail.rb#L861

**Comment by repeatedly** [comment]
in_tail uses timer and inotify based watcher to check file stauts.
