### ISSUE TITLE
Allow file path to have year, month, day as placeholders?

### ISSUE THREAD

**Issue by singhravi1** [fluent/fluentd#2693]
I think if we can format the directory for [file output](https://docs.fluentd.org/output/file) with year, month and day placeholder, the log management would become more awesome.

Something Like,
```

<match app.**>
    @type file
    path /var/log/fluentd/app/%Y/%m/%d
    compress gzip
    append true
</match>
```

Or is there any plugin already available that can do this?

**Comment by repeatedly** [comment]
You can do it. See document: https://docs.fluentd.org/output/file#path

**Comment by singhravi1** [comment]
Thanks @repeatedly  for the suggestion.
This will have date format in a single directory , for example, `/var/log/fluentd/app.20190909`?
But i need a directory with year then with month then with day, for example, `/var/log/fluentd/2019/09/09`.
I used the format that i have given in main description, and it creates directory with names "%Y", '%m', '%d', like, literaly `/var/log/fluentd/%Y/%m/%d`.

**Comment by repeatedly** [comment]
See note in `path`.

> Initially, you may see a file which looks like /path/to/file.%Y%m%d/buffer.b5692238db04045286097f56f361028db.log. This is an intermediate buffer file (b5692238db04045286097f56f361028db identifies the buffer). Once the content of the buffer has been completely flushed, you will see the output file without the trailing identifier

After flushed buffers, you still see `%Y` in the file path?

**Comment by singhravi1** [comment]
I currently have the `timekey` set to `1d` so, i suppose this will be flushed at midnight?
I'm leaving that as it is (not trying to change `timekey` and check again), will notify tomorrow if that gets resolved.
Thanks!

**Comment by singhravi1** [comment]
This actually worked as expected!
Thanks a lot @repeatedly :)
