### ISSUE TITLE
output buffer produce too many small files

### ISSUE THREAD

**Issue by like-inspur** [fluent/fluentd#2696]
I use file buffer for output plugin, when output server is down（fluentd-kafka）, there are so many buffer file under buffer path, which cause system open too may files, and each size of buffer.q file is soo small. The buffer file is like this:
-rw-r--r-- 1 root root  12K Nov 14 09:15 buffer.q5974433fadf720e68e5a699940530f27.log
-rw-r--r-- 1 root root   71 Nov 14 09:15 buffer.q5974433fadf720e68e5a699940530f27.log.meta
-rw-r--r-- 1 root root 102K Nov 14 09:15 buffer.q5974433fc59302b37a3ee72427224c50.log
-rw-r--r-- 1 root root   77 Nov 14 09:15 buffer.q5974433fc59302b37a3ee72427224c50.log.meta
-rw-r--r-- 1 root root  12K Nov 14 09:15 buffer.q59744340a19ad6529d931edb824dc5a5.log
-rw-r--r-- 1 root root   71 Nov 14 09:15 buffer.q59744340a19ad6529d931edb824dc5a5.log.meta
-rw-r--r-- 1 root root 117K Nov 14 09:15 buffer.q59744340c09758ae11135cf9a386af67.log

I config output buffer is like this, so I don't know why fluentd produce so may buffer files and don't compose some small files to a 15M size file
```   
   <match *.log>
      @type forward
      expire_dns_cache 60
      ignore_network_errors_at_startup true
      slow_flush_log_threshold 120.0
      heartbeat_type none
      compress gzip
      <server>
        host fluentd-kafka
        port 24224
      </server>
      <buffer>
        @type file
        path /fluentd/log
        total_limit_size 100M
        chunk_limit_size 15M
        #queued_chunks_limit_size 64
        retry_type periodic
        retry_wait 60
        flush_mode interval
        flush_interval 60s
        flush_thread_count 2
        retry_forever true
        overflow_action block
      </buffer>
    </match>
```

**Comment by ganmacs** [comment]
Don't delete the issue template we provide and follow  https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md .

**Comment by like-inspur** [comment]
And I found the size of buffer directory has exceeed  100M which I set the value of total_limit_size
