### ISSUE TITLE
Parsing error on fluentd

### ISSUE THREAD

**Issue by YunSangJun** [fluent/fluentd#2701]
**Describe the bug**

- I use fluentd as syslog input server. There is a parsing error on fluentd such as a following.
    ```
    2019-11-08 02:35:03 +0000 [warn]: #0 failed to parse message data="<142>Nov  8 02:35:03 haproxy[106]: 172.30.249.61:48460 [08/Nov/2019:02:35:03.884] public be_http:sample:nginx-example/<NOSRV> 1/-1/-1/-1/0 503 3278 - - SCNN 1/1/0/0/0 0/0 \"GET / HTTP/1.1\""
    ```

- I setted up fluent configuration via following guide.
https://www.fluentd.org/guides/recipes/haproxy-elasticsearch

- I proved my parsing rule in fluentular web site.
[http://fluentular.herokuapp.com/](http://fluentular.herokuapp.com/parse?regexp=%28%3F%3Cps%3E%5Cw%2B%29%5C%5B%28%3F%3Cpid%3E%5Cd%2B%29%5C%5D%3A+%28%3F%3Cc_ip%3E%5B%5Cw%5C.%5D%2B%29%3A%28%3F%3Cc_port%3E%5Cd%2B%29+%5C%5B%28%3F%3Ctime%3E.%2B%29%5C%5D+%28%3F%3Cf_end%3E%5B%5Cw-%5D%2B%29+%28%3F%3Cb_end%3E%5B%5Cw%5C%3A%5C-%5D%2B%29%5C%2F%28%3F%3Cb_server%3E%5B%5Cw%5C%3A%5C-%5C.%5C%3C%5C%3E%5D%2B%29+%28%3F%3Ctq%3E%5B%5Cd%5C-%5D%2B%29%5C%2F%28%3F%3Ctw%3E%5B%5Cd%5C-%5D%2B%29%5C%2F%28%3F%3Ctc%3E%5B%5Cd%5C-%5D%2B%29%5C%2F%28%3F%3Ctr%3E%5B%5Cd%5C-%5D%2B%29%5C%2F%28%3F%3Ctt%3E%5B%5Cd%5C-%5D%2B%29+%28%3F%3Cstatus_code%3E%5Cd%2B%29+%28%3F%3Cbytes%3E%5Cd%2B%29+%28%3F%3Creq_cookie%3E%5CS%2B%29+%28%3F%3Cres_cookie%3E%5CS%2B%29+%28%3F%3Ct_state%3E%5B%5Cw-%5D%2B%29+%28%3F%3Cactconn%3E%5Cd%2B%29%5C%2F%28%3F%3Cfeconn%3E%5Cd%2B%29%5C%2F%28%3F%3Cbeconn%3E%5Cd%2B%29%5C%2F%28%3F%3Csrv_conn%3E%5Cd%2B%29%5C%2F%28%3F%3Cretries%3E%5Cd%2B%29+%28%3F%3Csrv_queue%3E%5Cd%2B%29%5C%2F%28%3F%3Cbackend_queue%3E%5Cd%2B%29+%5C%5C%22%28%3F%3Crequest%3E%5B%5E%22%5D*%29%5C%5C%22&input=%3C142%3ENov++8+02%3A35%3A03+haproxy%5B106%5D%3A+172.30.249.61%3A48460+%5B08%2FNov%2F2019%3A02%3A35%3A03.884%5D+public+be_http%3Asample%3Anginx-example%2F%3CNOSRV%3E+1%2F-1%2F-1%2F-1%2F0+503+3278+-+-+SCNN+1%2F1%2F0%2F0%2F0+0%2F0+%5C%22GET+%2F+HTTP%2F1.1%5C%22&time_format=)

    Regular Expression
    ```
    (?<ps>\w+)\[(?<pid>\d+)\]: (?<c_ip>[\w\.]+):(?<c_port>\d+) \[(?<time>.+)\] (?<f_end>[\w-]+) (?<b_end>[\w\:\-]+)\/(?<b_server>[\w\:\-\.\<\>]+) (?<tq>[\d\-]+)\/(?<tw>[\d\-]+)\/(?<tc>[\d\-]+)\/(?<tr>[\d\-]+)\/(?<tt>[\d\-]+) (?<status_code>\d+) (?<bytes>\d+) (?<req_cookie>\S+) (?<res_cookie>\S+) (?<t_state>[\w-]+) (?<actconn>\d+)\/(?<feconn>\d+)\/(?<beconn>\d+)\/(?<srv_conn>\d+)\/(?<retries>\d+) (?<srv_queue>\d+)\/(?<backend_queue>\d+) \\"(?<request>[^"]*)\\"
    ```

    Test String
    ```
    <142>Nov  8 02:35:03 haproxy[106]: 172.30.249.61:48460 [08/Nov/2019:02:35:03.884] public be_http:sample:nginx-example/<NOSRV> 1/-1/-1/-1/0 503 3278 - - SCNN 1/1/0/0/0 0/0 \"GET / HTTP/1.1\"
    ```

**To Reproduce**
1. Deploy a following fluentd resources on Kubernetes.
https://github.com/YunSangJun/fluentd-syslog-to-es/tree/add-haproxy-format

2. Send HAProxy log to fluentd syslog port
The port is 5140 in my configuration.

3. Watch an error log on fluentd container.
    ```
    # kubectl logs -f fluend-syslog-to-es-xxx
    2019-11-08 02:35:03 +0000 [warn]: #0 failed to parse message data="<142>Nov  8 02:35:03 haproxy[106]: 172.30.249.61:48460 [08/Nov/2019:02:35:03.884] public be_http:sample:nginx-example/<NOSRV> 1/-1/-1/-1/0 503 3278 - - SCNN 1/1/0/0/0 0/0 \"GET / HTTP/1.1\""
    ```

**Expected behavior**
I expected haproxy log message is parsed successfully.

**Your Environment**
- Fluentd or td-agent version: `fluentd --version` or `td-agent --version`
```
# fluentd --version
fluentd 1.6.3
```
- Operating system: `cat /etc/os-release`
```
# cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

- Kernel version: `uname -r`
```
# uname -r
3.10.0-1062.1.2.el7.x86_64
```

**Your Configuration**
- The following is my fluentd server and configuration resources.
https://github.com/YunSangJun/fluentd-syslog-to-es/tree/add-haproxy-format

**Your Error Log**

```
2019-11-08 02:35:03 +0000 [warn]: #0 failed to parse message data="<142>Nov  8 02:35:03 haproxy[106]: 172.30.249.61:48460 [08/Nov/2019:02:35:03.884] public be_http:sample:nginx-example/<NOSRV> 1/-1/-1/-1/0 503 3278 - - SCNN 1/1/0/0/0 0/0 \"GET / HTTP/1.1\""
```

**Comment by ganmacs** [comment]
This issue has nothing to do with fluentd core and read this. https://github.com/fluent/fluentd/blob/1f3e685389c04bcbeb408c0671291d0dab46f9a8/CONTRIBUTING.md#got-a-question-or-problem
