### ISSUE TITLE
Can the param refresh_interval  set to 100ms?

### ISSUE THREAD

**Issue by ted222** [fluent/fluentd#2703]
hello,
     the param refresh_interval's default value is 60(seconds), can I set the refresh_interval to 100ms?
I want to have a fine-grained refresh_interval. thanks

**Comment by repeatedly** [comment]
Yes. See `time` part in this section: https://docs.fluentd.org/configuration/config-file#supported-data-types-for-values
Of course, frequent refresh makes CPU usage higher and we don't test such cases for now...
