### ISSUE TITLE
Multiple Http Port

### ISSUE THREAD

**Issue by zhulinwei** [fluent/fluentd#2704]
I had to bind multiple http port, config for example:
```
    <source>
      @type http
      port 443
      bind 0.0.0.0
      body_size_limit 32m
      keepalive_timeout 10s
    </source>

    <source>
      @type http
      port 80
      bind 0.0.0.0
      body_size_limit 32m
      keepalive_timeout 10s
    </source>
```
The difference is just ports, and there is no problem with the above configuration(It run well), but someone  have a better way to show it?

**Comment by ganmacs** [comment]
You can use `@include` directive 
https://docs.fluentd.org/configuration/config-file#6-re-use-your-config-the-include-directive

**Comment by zhulinwei** [comment]
@ganmacs thanks
