### ISSUE TITLE
Fluentd does not ship the first log entry in the log file.

### ISSUE THREAD

**Issue by andrei-galkin** [fluent/fluentd#2707]
I setup fluentd to transfer my app logs data from logs files to Elastic Search and observing that the first log entry from logs files is not transferred by fluentd each time.
Is it normal behavior or I miss a setting?

Thank in advance for the help.

**Comment by ganmacs** [comment]
see https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md#got-a-question-or-problem
