### ISSUE TITLE
I can't get nginx logs when set docker log-driver=fluentd

### ISSUE THREAD

**Issue by kiddingl** [fluent/fluentd#2717]
Check [CONTRIBUTING guideline](https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md) first and here is the list to help us investigate the problem.
step1
```
docker run -d --log-driver fluentd --log-opt fluentd-address=localhost:24224 --log-opt tag="nginx-test" --log-opt fluentd-async-connect  --name nginx-test -p 80:80 nginx
```
step2
```
docker run -d -p 24224:24224  -v /data:/fluentd/log fluent/fluentd
```
step3
```
docker logs -f nginx-test
```
And I got the errors from step3:
```
docker logs -f nginx-test
Error response from daemon: configured logging driver does not support reading
```

**Expected behavior**

I get nginx logs when set log-driver=fluentd
**Your Environment**
os: centos7
kernerl: 3.10.0-957.21.3.el7.x86_64
fluentd: latest
docker version: 19.03.4

**Comment by utkudarilmaz** [comment]
If you use a logging driver which sends logs to a file, an external host, a database, or another logging back-end, docker logs may not show useful information. (https://docs.docker.com/config/containers/logging/)

**Comment by kiddingl** [comment]
oh, I learn it
