### ISSUE TITLE
how to specify the last line in format multiline

### ISSUE THREAD

**Issue by zpavlig** [fluent/fluentd#2723]
hello
I have a large interval between logs and my logs format multiline
I need to determine the last line of the log
How can I do that?
multiline_flush_interval - this is not suitable since the logs are formed for a long and different time
thx

**Comment by ganmacs** [comment]
read this https://github.com/fluent/fluentd/blob/bfc39b5dd847253efeb849bf5e67836eaf3ef428/CONTRIBUTING.md
