### ISSUE TITLE
specify the last line in format multiline

### ISSUE THREAD

**Issue by zpavlig** [fluent/fluentd#2724]
td-agent version - 3.1.1
Environment information, Centos 6

configuration:

```
<source>
  @type tail
  path /var/log/test.log
  pos_file /var/cache/td-agent/test.pos
  tag test.log
  format multiline
  format_firstline /\d{4}\/\d{1,2}\/\d{1,2} \d{1,2}\:\d{1,2}\:\d{1,2} \[\d{1,9}\] fist line/
  format1 /(?<time>\d{4}\/\d{1,2}\/\d{1,2} \d{1,2}\:\d{1,2}\:\d{1,2})) ((?<message>.*)|(?<message>.*)/
</source>
```

I have a large interval between logs and my logs format multiline
I need to determine the last line of the log
How can I do that?
multiline_flush_interval - this is not suitable since the logs are formed for a long and different time

**Comment by ganmacs** [comment]
Multiline parser can't specify a regex of last line . see https://docs.fluentd.org/parser/multiline
How about https://github.com/fluent-plugins-nursery/fluent-plugin-concat? 

BTW, Read the contribution guide and follow the template.
