### ISSUE TITLE
Daemon doesn't work without supervision

### ISSUE THREAD

**Issue by jkohen** [fluent/fluentd#2735]
**Describe the bug**
When fluentd runs with `--daemon --no-supervisor`, it ignores `--daemon`. The supervisor doesn't run, as expected.

**To Reproduce**
Run fluentd with `--daemon file.pid --no-supervisor`.

**Expected behavior**
Fluentd runs without the supervisor (single process, single worker) and goes to the background, writing its pid to `file.pid`.

**Your Environment**

- Fluentd or td-agent version: `fluentd --version` or `td-agent --version`
- Operating system: `cat /etc/os-release`
- Kernel version: `uname -r`

If you hit the problem with older fluentd version, try latest version first.

I used 1.6.3, but based on the code at https://github.com/fluent/fluentd/blob/master/lib/fluent/supervisor.rb, this shouldn't work at HEAD either.

**Additional context**

I filed this as a bug because nothing in the docs (https://docs.fluentd.org/deployment/command-line-option) says these options shouldn't work together, and fluentd accepts them. One could argue it's a feature request, because nothing in the implementation (https://github.com/fluent/fluentd/blob/master/lib/fluent/supervisor.rb) seems to indicate that this should work.

**Comment by ganmacs** [comment]
I've confirmed it. will fix it later. Thank you for reporting!

**Comment by ganmacs** [comment]
https://github.com/fluent/fluentd/pull/2912 should fix this patch.
