### ISSUE TITLE
On Linux worker node, logs are not rotating after add log rotation config

### ISSUE THREAD

**Issue by ggpaue** [fluent/fluentd#2743]
Check [CONTRIBUTING guideline](https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md) first and here is the list to help us investigate the problem.

**Describe the bug**
Added log rotate option in config, but logs are not rotating, they are still all in one log file

**To Reproduce**
On Linux worker node, add log-rotate-age & log-rotate-size into bin/ctl and restart this process
logs are still in one log file, not rotating as expected

**Expected behavior**
Logs should start rotating after restart the fluentd process
**Your Environment**

- Fluentd or td-agent version: `fluentd --version` or `td-agent --version`
- Operating system: `cat /etc/os-release`
- Kernel version: `uname -r`

If you hit the problem with older fluentd version, try latest version first.

**Your Configuration**
```
exec ${PKG_DIR}/bin/fluentd \
      -c ${JOB_DIR}/config/fluent.conf \
      -p ${PKG_DIR}/plugins/ \
      --log-rotate-age 3 \
      --log-rotate-size 100000 \
      --no-supervisor \
      >>  ${LOG_DIR}/fluentd.stdout.log \
      2>> ${LOG_DIR}/fluentd.stderr.log
    ;;
```

**Your Error Log**

```
root      9869     1  3 01:00 ?        00:00:06 ruby /var/vcap/packages/vrli-fluentd/bin/fluentd -c /var/vcap/jobs/fluentd/config/fluent.conf -p /var/vcap/packages/vrli-fluentd/plugins/ --log-rotate-age 3 --log-rotate-size 1000 --no-supervisor
```

**Additional context**

**Comment by ganmacs** [comment]
it works. could tell me how to reproduce it.

commad line  option

```
 docker run -it --rm fluentd-rotate --log-rotate-age 5 --log-rotate-size 1000 --log fluentd/stdout/output.log
```

docker file

```
FROM fluent/fluentd:v1.7-debian

ADD fluent.conf /fluentd/etc/

```

config
```
<source>
  @type dummy
  tag dummy.ts3
  rate 1000
</source>

<match>
  @type stdout
</match>
```

log



```
fluent@da588e8bd843:/$ ls -la fluentd/log/
total 28
drwxr-xr-x 1 fluent fluent 4096 Dec 23 08:16 .
drwxr-xr-x 1 fluent fluent 4096 Oct 26 09:50 ..
-rw-r--r-- 1 fluent fluent  937 Dec 23 08:16 stdout.log
-rw-r--r-- 1 fluent fluent 1004 Dec 23 08:16 stdout.log.0
-rw-r--r-- 1 fluent fluent 1004 Dec 23 08:16 stdout.log.1
-rw-r--r-- 1 fluent fluent 1004 Dec 23 08:16 stdout.log.2
-rw-r--r-- 1 fluent fluent 1004 Dec 23 08:16 stdout.log.3
```

**Comment by ganmacs** [comment]
No response and it worked. closed.
