### ISSUE TITLE
fluentd register win service faild

### ISSUE THREAD

**Issue by LeeYearJ** [fluent/fluentd#2745]
I run the commond line test.event follow the official website succeed, such as:

#send the msg
echo {"msg":"hello"}| fluent-cat test.event

#the prompt receivec and shows:
2019-12-23 11:22:50.161324000 +0800 test.event: {"msg":"hello"}

#but when i register the fluentd as windows's services, it faild:
#type the two commands
fluentd --reg-winsvc -i
fluentd --reg-winsvc-fluentdopt '-c C:/opt/td-agent/etc/td-agent/td-agent.conf -o C:/opt/td-agent/td-agent.log'

#the prompt shows faild
C:/opt/td-agent/embedded/lib/ruby/2.4.0/win32/registry.rb:289:in `OpenKey': system can't find the spefified file。 (Win32::Registry::Error)
        from C:/opt/td-agent/embedded/lib/ruby/2.4.0/win32/registry.rb:431:in `open'
        from C:/opt/td-agent/embedded/lib/ruby/2.4.0/win32/registry.rb:542:in `open'
        from C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/command/fluentd.rb:296:in `<top (required)>'
        from C:/opt/td-agent/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:68:in `require'
        from C:/opt/td-agent/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:68:in `require'
        from C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/bin/fluentd:8:in `<top (required)>'
        from C:/opt/td-agent/embedded/bin/fluentd:22:in `load'
        from C:/opt/td-agent/embedded/bin/fluentd:22:in `<main>'

Can somebody tell me what happen? 
Thank you~

**Comment by ganmacs** [comment]
please read https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md

**Comment by LeeYearJ** [comment]
sorry , because i forgetten closed the other prompt window, so it will occur the error...
