### ISSUE TITLE
arm64 package build (Ubuntu bionic deb)

### ISSUE THREAD

**Issue by rjemanuele** [fluent/fluentd#2752]
**Is your feature request related to a problem? Please describe.**

I see there are tests and a CI pipeline for ARM64.  Is there a package built for Ubuntu Bionic ARM64 like "td-agent"?  Also, is there an ARM64 docker image?

**Describe the solution you'd like**

Either a package built for Ubuntu Bionic or instructions to create one. 

**Describe alternatives you've considered**

I can use fluent-bit if I have to as I've compiled that for ARM64 but the rest of our cluster uses fluentd (td-agent).

**Additional context**

This is very useful. :)

**Comment by repeatedly** [comment]
>  is there an ARM64 docker image?

You can see arm related tags in docker hub.
Use it: https://hub.docker.com/r/fluent/fluentd/tags

> Is there a package built for Ubuntu Bionic ARM64 like "td-agent"? 

This is beta. See https://github.com/treasure-data/omnibus-td-agent/issues/209#issuecomment-568633733

This repository is not for docker image or td-agent. close.

**Comment by rjemanuele** [comment]
Hi,

Thank you for showing me where these are.  There are 2 issues that you can see here: https://hub.docker.com/r/fluent/fluentd/tags

1. None of these tags look to be ARM64.  (They look to be armhf which was often used on 32 bit Raspberry Pis. That’s an Arm v7 architecture.). It is possible they will function on the Arm v8 core used by the ARM64 or aarch64 platforms.  That’ll require some testing. 

2. All the Arm tags have their architecture set to linux/amd64 which can preclude them from being found automatically. 

Thanks again!

**Comment by repeatedly** [comment]
> None of these tags look to be ARM64

I can see arm64 images...

<img width="1252" alt="2e7d44c333e5eed022e9737290ce40fe" src="https://user-images.githubusercontent.com/16928/71951384-37839780-321e-11ea-94cc-ec334ff1f6a6.png">

> All the Arm tags have their architecture set to linux/amd64 which can preclude them from being found automatically.

How to set arm64? We use this script to push images: https://github.com/fluent/fluentd-docker-image/blob/master/post_push.erb
If you have a patch, it is great.

**Comment by cosmo0920** [comment]
I confirmed that v1.8-arm64-debian image can run on RaspberryPi 3 AArch64 Wayland/Weston image:

![wayland-screenshot-2020-01-08_11-58-04](https://user-images.githubusercontent.com/700876/72032993-517fb180-32d4-11ea-905d-e09b212dc70e.png)

What is the shortage of running on your ARM64 docker environment?
