### ISSUE TITLE
Adding a new field to record

### ISSUE THREAD

**Issue by secure0** [fluent/fluentd#2776]
Check [CONTRIBUTING guideline](https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md) first and here is the list to help us investigate the problem.

**Describe the bug**
I am trying to add new field to Fluentd record,with two filter sections for the same source section, but the new record doesn't seem to be added.

**To Reproduce**

**Expected behavior**

**Your Environment**

- Fluentd0.12.40
- NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"

- Kernel version: 3.10.0-1062.el7.x86_64
<source>
  type syslog
  port 25226
  bind 127.0.0.1
  protocol_type udp
  tag oms.syslog
</source>

<filter oms.syslog.**>
  type record_transformer
  <record>
    myownfield "ABCDE"
  </record>
</filter>

<filter oms.syslog.**>
  type filter_syslog
</filter>

No related errors.

**Comment by ganmacs** [comment]
See https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md#got-a-question-or-problem. Here is not for Q&A.
