### ISSUE TITLE
Emit transaction failed when receive huge log traffic ingestion 

### ISSUE THREAD

**Issue by toan-hf** [fluent/fluentd#2784]
**Describe the bug**
First of all, thank you for your great effort to maintain this awesome project. 
My problem like many others buffer issue here. Basically, We are following all best practices to achieve high performance logging system. But we realised when fluent aggregator got huge log traffic there are thousand of error relate to buffer appears on our log console 

```emit transaction failed: error_class=NoMethodError error="undefined method `unstaged?'
for nil:NilClass" location="/fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.7.4/lib/fluent/plugin/buffer.rb:339:in `block (2 levels) in write'" tag="kubernetes.var.log.containers.logs-generator_logging_logs-generator-d4a9f43846fa303a1ea5b0422253f9537b2da5a24b4afde4bcc4419f4a59e6c5.log"```

Our topology like that 

![image](https://user-images.githubusercontent.com/57263227/72731088-398d1500-3b93-11ea-9706-e516860ef8a8.png)

Overall the error at above  always happen for those box who thrown more than 6000 message per minutes. And we trying to adjust buffer - also flush thread count every day to make it better.  

**To Reproduce**
Quite easy to reproduce the case above with log generator. In this example i try to generate 1mil log lines per minutes. So it around 16,600 log line per second which is affected by the throttling rule immediately 
```
kubectl run logs-generator-1mil   --generator=run-pod/v1   --image=k8s.gcr.io/logs-generator:v0.1.1   --restart=Never   --env "LOGS_GENERATOR_LINES_TOTAL=1000000"   --env "LOGS_GENERATOR_DURATION=1m"
```
**Expected behavior**
I wish the current buffer configuration and other resource allocation, we able to handle more than 10,000 msg / second. but for now it just around 2000. 

**Your Environment**

- Fluentd 1.7.4 (fluentd-kubernetes-daemonset:v1.7-debian-graylog-2)
- Debian 
- 

If you hit the problem with older fluentd version, try latest version first.

**Your Configuration**

Apart of our configuration which was tuned like that 

```
 <match **>
      @type copy
      <store>
        @type flowcounter
        tag flow.count
        @label @flowcountall
      ...
      </store>
      <store>
        @type gelf
       ...
        protocol udp
        <buffer>
          @type file
          path /var/log/fluentd-buffers/kubernetes.system.buffer
          flush_mode immediate
          retry_type exponential_backoff
          flush_thread_count 900
          flush_thread_interval 2
          retry_forever
          retry_max_interval 30
          chunk_limit_size "8M"
          queue_limit_length "900"
          overflow_action drop_oldest_chunk
          total_limit_size 8192MB
        </buffer>
      </store>
      <store>
        @type prometheus
        <metric>
         ...
          </labels>
        </metric>
      </store>
    </match>
```

We know that logging source event from our application sometime really mess thus applied throttling mechanism like that 

```
    <filter kubernetes.**>
      @type throttle
      group_key kubernetes.pod_name
      group_bucket_limit      6000
      group_bucket_period_s   60
      group_reset_rate_s      -1
      group_warning_delay_s    5
      group_drop_logs false
    </filter>
```

**Your Error Log**

```
2020-01-20 13:19:30 +0000 [warn]: #0 rate exceeded group_key=["logs-generator"] rate_s=46104 period_s=60 limit=6000 rate_limit_s=100 reset_rate_s=-1
2020-01-20 13:19:30 +0000 [warn]: #0 emit transaction failed: error_class=NoMethodError error="undefined method `unstaged?' for nil:NilClass" location="/fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.7.4/lib/fluent/plugin/buffer.rb:339:in `block (2 levels) in write'" tag="kubernetes.var.log.containers.logs-generator_logging_logs-generator-d4a9f43846fa303a1ea5b0422253f9537b2da5a24b4afde4bcc4419f4a59e6c5.log"
```

**Additional context**

Because we also using fluent running as daemonset to collect log before sending to aggregator pod. So those daemonset used to have full buffer disk as well-known issue like below 

```
error_class=Fluent::Plugin::Buffer::BufferOverflowError error="buffer space has too many data" location="/fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.7.4/lib/fluent/plugin/buffer.rb:265:in write'" tag="kubernetes.var.log.containers.logs-generator-1mil_logging_logs-generator-1mil-1cc9e2d16ab51040a7897a0a8af858936d08bfde18a6d4a6a30c8d2a22b0766d.log"
```

***From my thoughtful*** 
Always keep in mind those things as i have got some suggestion from other similar issues like 

> BufferOverflowError happens when output speed is slower than incoming traffic.
> So there are several approaches:
> 
> Scale up / scale out destination when writing data is slow
> Increase flush_thread_count when the write latency is lower. Launch multiple threads can hide the latency.
> Improve network setting. If network is unstable, the number of retry is increasing and it makes buffer flush slow.
> Optimize buffer chunk limit or flush_interval for the destination. For example, kafka and mongodb have different characteristic for data ingestion.

I also want to migrate those collector pods which running fluentd to fluentbit. Because i know fluentbit with backpressure mechanism can help us. It reduce some high pressure before logging come to aggregation node. So the topology will change slightly like that 

>FluentBit --- FluentD -- Graylog

**Comment by toan-hf** [comment]
I uploaded here 2 images to show the behaviour when huge traffic log coming and vice versa. 
As you can see on the high traffic log. We have around 8k - 10k incoming message (before throttling). So the error rate - retry rate also the buffer go higher immediately. When checking the console log at that time, We received those errors at i mentioned at above 

![image](https://user-images.githubusercontent.com/57263227/72734031-51679780-3b99-11ea-9fa8-1ff7abcabe3e.png)


Vice versa, when logging traffic decreasing |(1-2k)|, We back to normal situation 

![image](https://user-images.githubusercontent.com/57263227/72734152-78be6480-3b99-11ea-9d58-aeb9f7f7d0f9.png)

**Comment by repeatedly** [comment]
> emit transaction failed: error_class=NoMethodError error="undefined method `unstaged?' for nil:NilClass" 

I assume your output/buffer configuration combo causes this error. TD customers process 10k+ msg/sec without problems, so I will check which point has a problem. Thanks for the report.

**Comment by toan-hf** [comment]
1 more thing i need to note here is : we are use GELF output plugin which is sending the log record directly to Graylog under UDP protocol. Currently we also observed several issues with this plugin but i think i will create another issue in particular channel. 
Looking forward to dive deeper those issues with you @repeatedly !

**Comment by fuusuke** [comment]
> > emit transaction failed: error_class=NoMethodError error="undefined method `unstaged?' for nil:NilClass"
> 
> I assume your output/buffer configuration combo causes this error. TD customers process 10k+ msg/sec without problems, so I will check which point has a problem. Thanks for the report.

Could you please point me to buffer configs? I am using a simple port listener:
&lt;source&gt;  
  @type forward  
  bind 0.0.0.0  
  port 24224
&lt;/source&gt;

Getting the same error at higher TPS. ~15K
