### ISSUE TITLE
fluentd logs are separated when using UDP 

### ISSUE THREAD

**Issue by zffocussss** [fluent/fluentd#2785]
Check [CONTRIBUTING guideline](https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md) first and here is the list to help us investigate the problem.

**Describe the bug**

uwsgi logs are sent to fluentd through udp,Meanwhile,we have a monitor logic in application log,which will sent the traceback logs to other place.when I try to find the these traceback error messages,they are missing.
so I guess these traceback message are catched and seperated by application code so that they are missed in logs (accepted by Fluentd UDP port,recorded by file store)

**To Reproduce**

**Expected behavior**

I hope the traceback logs can be displayed on both fluentd logs and other place (sent by application code)

**Your Environment**

- Fluentd or td-agent version: `fluentd --version` or `td-agent --version`
td-agent 1.7.4

- Operating system: `cat /etc/os-release`
Ubuntu 18.04.3 LTS

- Kernel version: `uname -r`
5.0.0-1023-azure

If you hit the problem with older fluentd version, try latest version first.

**Your Configuration**
```
<source>
@type udp
  tag uwsgi-integ3-raw
  <parse>
  @type none
  </parse>
  port 20001               # optional. 5160 by default
  bind 0.0.0.0             # optional. 0.0.0.0 by default
  message_length_limit 1MB # optional. 4096 bytes by default
</source>

<match uwsgi-integ3-raw>
#  @type copy
#  <store>
  @type file
  path /data/logs/integ3/uwsgi.*.log
  flush_interval 60s
  time_slice_format %Y%m%d
  time_slice_wait 10m
  <format>
  @type single_value
  localtime false
  #add_newline false
  </format>
  #format none
  append true
  buffer_path /var/log/td-agent/integ3
  include_tag_key true
  utc
#  </store>
</match>

```

**Additional context**

**Comment by ganmacs** [comment]
Sorry I can't get what you're saying. what is the 'traceback'? could you explain more detail?

**Comment by zffocussss** [comment]
> Sorry, I can't get what you are getting at. what is the 'traceback'? could you explain more detail(and more specific)?

traceback is error messages(multilines) in python.
