### ISSUE TITLE
Compress gzip option stops working with time_slice_format %Y%m%d

### ISSUE THREAD

**Issue by Sunanda-S2** [fluent/fluentd#2791]
<match s2_events**.log>
@type file
path /var/log/s2/s2_events/
time_slice_format %Y%m%d
compress gzip
With default time_slice_format, I could see zip files getting created every hour. After I added this time_slice_format to create a file every day instead of every hour, I don't see a gzip getting created. I see the following files:

root@s2-fluentd-zthgf:/var/log/s2/s2_events# ls -la
total 2320
drwxr-xr-x 2 root root 61440 Jan 22 00:00 .
drwxr-xr-x 3 root root 4096 Jan 22 00:00 ..
-rw-r--r-- 1 root root 913583 Jan 21 23:59 buffer.b59cae9c9e9d044db89f3832f08e064b8.log
-rw-r--r-- 1 root root 70 Jan 21 23:59 buffer.b59cae9c9e9d044db89f3832f08e064b8.log.meta
-rw-r--r-- 1 root root 1369306 Jan 22 18:01 buffer.b59caf34afda758bc8d4d42a21281bee1.log
-rw-r--r-- 1 root root 70 Jan 22 18:01 buffer.b59caf34afda758bc8d4d42a21281bee1.log.meta

Another question: Can I control the naming of these buffer files?

**Comment by Sunanda-S2** [comment]
Actually the gzip compression happened after several hours 12+, so wondering how this gets triggered. Do I need to add any flush interval? I would still like to know what's the predictable behavior I can expect. TIA

**Comment by ganmacs** [comment]
follow the issue template and see https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md#got-a-question-or-problem

**Comment by repeatedly** [comment]
Reading official article of output/buffer should resolve this question.
