### ISSUE TITLE
Unable to override fluentd output plugin's chunk_limit_size

### ISSUE THREAD

**Issue by pankajtalk** [fluent/fluentd#2819]
Check [CONTRIBUTING guideline](https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md) first and here is the list to help us investigate the problem.

**Describe the bug**
I am writing a Fluentd output plugin (in buffered mode) and would like to override the chunk_limit_size parameter. For this, I set the parameter in the fluentd conf file as follows:
```
   <buffer tag>
      @type file
      path                /tmp/
      flush_interval      30s
      chunk_limit_size    256MB
    </buffer>
```
The inspect o/p (on buffer config object) is

`<Fluent::Config::Section {"chunk_keys":["tag"],"@type":"file","timekey":null,"timekey_wait":600,"timekey_use_utc":false,"timekey_zone":"-0800","flush_at_shutdown":null,"flush_mode":"default","flush_interval":30,"flush_thread_count":10,"flush_thread_interval":0.5,"flush_thread_burst_interval":0.05,"delayed_commit_timeout":60,"overflow_action":"block","retry_forever":false,"retry_timeout":259200,"retry_max_times":17,"retry_secondary_threshold":0.8,"retry_type":"exponential_backoff","retry_wait":2,"retry_exponential_backoff_base":2,"retry_max_interval":null,"retry_randomize":true,"disable_chunk_backup":true,"type":"file","chunk_limit_size":1048576,"chunk_limit_records":50,"total_limit_size":5368709120}>`

As we can see, the chunk_limit_size is set to 1048576. This is the default value I have set for this param in the code. It does not get overridden by the value I set in the fluentd conf file. Am I missing something here?

**Comment by pankajtalk** [comment]
To add some more details..I basically want to get hold of the chunk_limit_size value (if configured in the conf file) and check if the value is less than 2 MB. If yes, proceed. If not, generate a config error. How do I need the chunk_limit_size in my output plugin? It's not reflected in the buffer_config in configure(conf) function

**Comment by ganmacs** [comment]
> I am writing a Fluentd output plugin (in buffered mode) 

this is not fluentd core issue. see https://github.com/fluent/fluentd/blob/1f3e685389c04bcbeb408c0671291d0dab46f9a8/CONTRIBUTING.md
