### ISSUE TITLE
Fluentd Tomcat Logs collector on Kubernetes

### ISSUE THREAD

**Issue by malavikad072** [fluent/fluentd#2822]
Hi,

I have one requirement on fluentd. I need to install fluentd as a daemon set on kubernetes to collect application logs which is in the exact path location /usr/local/tomcat/logs/* . Any help on this how to collect logs as a fluentd daemonset . Fluentd as a sidecar i can able to collect tomcat logs but it is another container sitting on each application pod, I dont need as a side car . Need to deploy Fluentd as a daemon set . Any help will be appreciated thanks in advance.

Thanks 
Malavika D

**Comment by ganmacs** [comment]
Please follow the issue template.
