### ISSUE TITLE
Missing Docs for releases after 0.12

### ISSUE THREAD

**Issue by AlecIsaacson** [fluent/fluentd#2825]
Check [CONTRIBUTING guideline](https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md) first and here is the list to help us investigate the problem.

**Describe the bug**
The documentation for all releases after 0.12 are missing from https://docs.fluentd.org/.

**To Reproduce**
Go to https://docs.fluentd.org/, click on 1.0, see only the introduction, no other docs.

**Expected behavior**
Go to the site and see all docs.

**Your Environment**
N/A

**Your Configuration**
N/A

**Your Error Log**
N/A
```

**Additional context**

N/A

**Comment by repeatedly** [comment]
Dup of https://github.com/fluent/fluentd-docs-gitbook/issues/149
