### ISSUE TITLE
output_file can only keep 9 days logs

### ISSUE THREAD

**Issue by zffocussss** [fluent/fluentd#2828]
Check [CONTRIBUTING guideline](https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md) first and here is the list to help us investigate the problem.

**Describe the bug**

uwsgi send logs to udp port of fluentd.then the logs are in store with output_file
but it can only keep 9 days logs

**To Reproduce**

Keep all the logs,as I do not want to miss any logs.

**Expected behavior**

Keep all the logs,as I do not want to miss any logs.

**Your Environment**

- Fluentd or td-agent version: `fluentd --version` or `td-agent --version`
td-agent 1.7.4
- Operating system: `cat /etc/os-release`
buntu 18.04.3 LTS
- Kernel version: `uname -r`
5.0.0-1029-azure

If you hit the problem with older fluentd version, try latest version first.

**Your Configuration**

```
<!-- Write your configuration here -->
```
```
<source>
@type udp
  tag uwsgi-prod-raw
  <parse>
  @type none
  </parse>
  port 20103               # optional. 5160 by default
  bind localhost             # optional. 0.0.0.0 by default
  message_length_limit 1MB # optional. 4096 bytes by default
</source>

<match uwsgi-prod-raw>
#  @type copy
#  <store>
  @type file
  path /data/logs/prod/drafter/uwsgi.*.log
  flush_interval 1
  time_slice_format %Y%m%d
  time_slice_wait 24h
  <format>
  @type single_value
  localtime false
  #add_newline false
  </format>
  #format none
  append true
  buffer_path /var/log/td-agent/drafter-prod
  include_tag_key true
  utc
#  </store>
</match>

```

**Your Error Log**

```
<!-- Write your **ALL** error log here -->
```
there are many "pattern not matched" in logs,but I do not think it is related with missing logs from uwsgi

**Additional context**

**Comment by zffocussss** [comment]
what is fluentd version?I am using td-agent.but I follow fluentd docuements

**Comment by repeatedly** [comment]
>  it can only keep 9 days logs

This point is unclear. out_file doesn't have file delete mechanism.
Could you describe your detailed situation?

**Comment by zffocussss** [comment]
> > it can only keep 9 days logs
> 
> This point is unclear. out_file doesn't have file delete mechanism.
> Could you describe your detailed situation?

@repeatedly ,I am running application on k8s.application logs are sent to UDP port of fluentd directly.
the logs are store in /data/logs/prod/drafter
uwsgi.20200213.log
uwsgi.20200214.log
uwsgi.20200215.log
...
uwsgi.20200221.log

it seems like it only keep the latest 9 days logs.
I want to keep all the logs

**Comment by repeatedly** [comment]
> it seems like it only keep the latest 9 days logs.
> I want to keep all the logs

It seems non fluentd issue. fluentd and out_file don't remove files. Maybe, your environment has the script which removes older files.

**Comment by zffocussss** [comment]
> > it seems like it only keep the latest 9 days logs.
> > I want to keep all the logs
> 
> It seems non fluentd issue. fluentd with out_file don't remove files. Maybe, your environment has the script/mechanizm which removes older files.

I did not set crontab job for it.it is very curious

**Comment by zffocussss** [comment]
I am using lsyncd to transfer logs to remote sever.I will look into it thanks
