### ISSUE TITLE
parser_syslog.rb dropping part of CEF message

### ISSUE THREAD

**Issue by dicolanl** [fluent/fluentd#2835]
Check [CONTRIBUTING guideline](https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md) first and here is the list to help us investigate the problem.

**Describe the bug**
Syslog parser is dropping CEF part of CEF message in RFC 3164 messages.

**To Reproduce**
Source Syslog message:
<43>Feb 24 11:05:17 172.17.116.129 PowerShell CEF:0|Microsoft|Powerhsell|6.2|ID|PWSH|6|src=8.8.8.8 dst=67.166.178.142

output:
2020-02-24 11:08:50.000000000 +0000 syslog.local7.info: {"host":"172.17.116.129","ident":"PowerShell","message":"0|Microsoft|Powerhsell|6.2|ID|PWSH|6|src=8.8.8.8 dst=67.166.178.142"}

**Expected behavior**
output should be
2020-02-24 11:08:50.000000000 +0000 syslog.local7.info: {"host":"172.17.116.129","ident":"PowerShell","message":"CEF:0|Microsoft|Powerhsell|6.2|ID|PWSH|6|src=8.8.8.8 dst=67.166.178.142"}

**Your Environment**

- Fluentd or td-agent version: `fluentd --version` or `td-agent --version`
td-agent 1.9.2
- Operating system: `cat /etc/os-release`
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
- Kernel version: `uname -r`
4.15.0-88-generic

If you hit the problem with older fluentd version, try latest version first.

**Your Configuration**

```
<source>
  @type syslog
  port 5514
  bind 0.0.0.0
  <transport udp>
  </transport>
  tag syslog
  <parse>
        @type syslog
        message_format auto
  </parse>
</source>

<match syslog.**>
  @type stdout
</match>
```

**Your Error Log**

```
<!-- Write your **ALL** error log here -->
```

**Additional context**

**Comment by repeatedly** [comment]
Put `parser_type string` in `<parse>` resolves this problem. Closed.

**Comment by dicolanl** [comment]
worked.  thanks
