### ISSUE TITLE
Missing /var/run/td-agent/td-agent.sock

### ISSUE THREAD

**Issue by Tsidkenu** [fluent/fluentd#284]
Installed td-agent on my Ubuntu system, and started it. Now trying to get it to work with Fluent PHP Logger, but it is missing td-agent.sock.

The only thing in /var/run/td-agent/ folder is td-agent.pid. Permission of the folder is drwxrwxrwx, and ownership is td-agent:td-agent.

Added to td-agent.conf the UNIX input source.
<source>
type unix
path /var/run/td-agent/td-agent.sock
</source>

Any idea why the td-agent.sock isn't being created?

**Comment by ayandev007** [comment]
however, I got the same problem. how to solve the issue?

**Comment by ayandev007** [comment]
thanks !  I have solved forget to open the cfg
