### ISSUE TITLE
apache2 parser expression excludes valid user agents

### ISSUE THREAD

**Issue by durzo** [fluent/fluentd#2841]
The expression in the apache2 parser uses `"(?<agent>[^\"]*)"` to identify user agents however this excludes the " character, which appears to be valid according to the RFC.

I am seeing at least one build of Safari 11 on IOS that sends `\"` as part of its user-agent and none of this clients requests are being picked up by fluent, instead we see:

`[warn]: #0 pattern not matched: "1.1.1.1 - - [25/Feb/2020:18:55:34 +0000] \"GET / HTTP/1.1\" 302 5080 \"-\" \"\\\"Mozilla/5.0 (iPhone; CPU iPhone OS 11_0 like Mac OS X) AppleWebKit/604.1.38 (KHTML, like Gecko) Version/11.0 Mobile/15A372 Safari/604.1\\\"\""`

I solved this by changing the parser from apache2 to regexp and use expression with `"(?<agent>.*)")` but I'm not sure that is 100% correct solution.

**Comment by ganmacs** [comment]
>  however this excludes the " character, which appears to be valid according to the RFC.

According to https://tools.ietf.org/html/rfc7231#section-5.5.3 and https://tools.ietf.org/html/rfc7230#section-3.2.6 's BNF,  user-agent does not accept an double quote( " ). or I missed something?
Can you please give us a pointer where you found double quote is valid?

**Comment by ganmacs** [comment]
I'll close this. if you have any questions, please feel free to ask.
