### ISSUE TITLE
in_tail Multiline mode does not work

### ISSUE THREAD

**Issue by yingjianjian** [fluent/fluentd#2846]
**Describe the bug**

I am using fluentd with beloe pipeline config:
`&lt;source\>

 @type tail
 @id isc-algo-engine-service
 format multiline
 multiline_flush_interval 3s
 format_firstline /\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}(,|.)\d{3}/
 format1 /^(?<timestamp>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}(,|.)\d{3}) (?<hostname>.*) (?<appname>\[.*\]) (?<loglevel>([A-a]lert|ALERT|[D|d]ebug|DEBUG|[N|n]otice|NOTICE|[I|i]nfo|INFO|[W|w]arn?(?:ing)?|WARN?(?:ING)?|ERR?(?:OR)?|[C|c]rit?(?:ical)?|CRIT?(?:ICAL)?|[F|f]atal|FATAL|[S|s]evere|SEVERE|EMERG(?:ENCY)?|[Ee]merg(?:ency)?)) (?<class>.* .* .*) (?<process>[\s\S]*) (?<thread>[\s\S]*) : (?<message>.*)/
 path /srv/isc-algo-engine-service/logs/out-test.log
 pos_file /var/log/python2.posg
 tag java-online.*
 time_format %Y-%m-%dT%H:%M:%S.%NZ
 refresh_interval 120
 &lt;source>`

Usecase:

No problem if I use single line mode:
`
2020-02-26T13:53:35+00:00 java-online.srv.isc-algo-engine-service.logs.out-test.log {"timestamp":"2020-02-26 12:23:13,910","hostname":"isc-algo-engine-service-7896997cdc-bvnhb","appname":"[isc-algo-engine-service]","loglevel":"ERROR","class":"utility wrapper 127","process":"[31]","thread":"[140659836589824]","message":"Traceback (most r2020年 02月 26日 星期三 21:53:32 CST"}`

But the multi-line mode will take about 10 minutes to capture:

`2020-02-26T14:16:09+00:00 java-online.srv.isc-algo-engine-service.logs.out-test.log {"timestamp":"2020-02-26 12:23:13,897","hostname":"isc-algo-engine-service-7896997cdc-bvnhb","appname":"[isc-algo-engine-service]","loglevel":"ERROR","class":"utility wrapper 127","process":"[31]","thread":"[140659836589824]","message":"Traceback (most r\necent call last)\njava.lang.NullPointerException: null\n at com.isyscore.os.isclink.data.save.run.emq.EmqHandleRunnable.tagOldUpload(EmqHandleRunnable.java:70)\n at com.isyscore.os.isclink.data.save.run.emq.EmqHandleRunnable.run(EmqHandleRunnable.java:47)\n at com.isyscore.os.isclink.data.save.run.emq.EmqHandleRunnable$$FastClassBySpringCGLIB$$29f375f2.invoke()\n at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)\n at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:746)\n at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)\n at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:88)\n at com.isyscore.boot.web.monitor.MonitorAspect.doAroundService(MonitorAspect.java:30)\n at sun.reflect.GeneratedMethodAccessor69.invoke(Unknown Source)\n at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)\n at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)\n at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)\n at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)\n at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)\n at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)\n at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:88)\n at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:88)\n at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:88)\n at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:88)\n at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:88)\n at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:88)"}`

Expected behavior:
Capture log in 3 minutes

My Environment:
Fluentd or td-agent version: fluentd 1.8.1
Docker Image : fluentd:v1.8.1-debian-2.0

**Comment by hzhu007** [comment]
You don't have parse section.

**Comment by ganmacs** [comment]
seems to be solved by hzhu007 's answer. @hzhu007 thank you for your help!!!
