### ISSUE TITLE
Multiple filter and formatting issue

### ISSUE THREAD

**Issue by hbceylan** [fluent/fluentd#2850]
Hi,

I'm trying to use grep and format plugin in the filter section as below but it doesn't work as expected. How can I use both in the filter section or separated?

```
<source>
  @type syslog
  port 8888
  tag rsyslog
</source>

<filter rsyslog.**>
  @type grep
  <regexp>
      key message
      pattern /COMMAND/
  </regexp>
  <format>
      @type csv
      fields hostname,from,to
  </format>
</filter>

<match rsyslog.**>
  @type datadog
  @id awesome_agent
  api_key xxxxxxxxxx
</match>
```

**Comment by repeatedly** [comment]
> it doesn't work as expected.

Why 'expected'? `grep` filter doesn't support `<format>`: https://docs.fluentd.org/filter/grep

BTW, this doesn't follow contribution guide. closed.

**Comment by hbceylan** [comment]
@repeatedly the issue content has been updated. Could you please open it again?

> Why 'expected'? grep filter doesn't support <format>: https://docs.fluentd.org/filter/grep

Ok, so how can handle this task?
