### ISSUE TITLE
Multiple filter and formatting issue

### ISSUE THREAD

**Issue by hbceylan** [fluent/fluentd#2851]
Hi,

I'm trying to use grep and format plugin in the filter section as below but it doesn't work as expected. How can I use both in the filter section or separated?

```
<source>
  @type syslog
  port 8888
  tag rsyslog
</source>

<filter rsyslog.**>
  @type grep
  <regexp>
      key message
      pattern /COMMAND/
  </regexp>
  <format>
      @type csv
      fields hostname,from,to
  </format>
</filter>

<match rsyslog.**>
  @type datadog
  @id awesome_agent
  api_key xxxxxxxxxx
</match>
```

Current without format

<img width="871" alt="Screenshot 2020-02-28 at 00 20 06" src="https://user-images.githubusercontent.com/23728382/75613910-b4e6cc80-5b2a-11ea-9211-b2d18feb5a16.png">

Expectation with format
<img width="887" alt="Screenshot 2020-02-28 at 00 21 00" src="https://user-images.githubusercontent.com/23728382/75613914-ba441700-5b2a-11ea-9f40-4133711705c4.png">

**Comment by ganmacs** [comment]
read https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md#got-a-question-or-problem and follow the issue template.
