### ISSUE TITLE
Fluentd CPU usage increased by 50% from version 1.7 to 1.8.

### ISSUE THREAD

**Issue by qingling128** [fluent/fluentd#2871]
Check [CONTRIBUTING guideline](https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md) first and here is the list to help us investigate the problem.

**Describe the bug**
When upgrading Fluentd 1.6 to the latest 1.9, our soak tests detected that the CPU usage increased by 50% given the same log throughputs. Further investigation revealed the CPU usage increase is triggered by some change between `1.7.4` and `1.8.1`.

**CPU usage increased by 50%**
![image](https://user-images.githubusercontent.com/5287526/76286651-14ef1880-6279-11ea-9577-a7a53bd9b284.png)
**Memory (RSS) is roughly the same** 
![image](https://user-images.githubusercontent.com/5287526/76286592-fbe66780-6278-11ea-8717-f0871650d9ba.png)
**Log throughputs decreased**
The agent can no longer catch up with the same log throughput of 1000 log entries per second:
![image](https://user-images.githubusercontent.com/5287526/76286743-423bc680-6279-11ea-83f5-81fb91487031.png)

**Expected behavior**
CPU usage does not increase dramastically

**Your Environment**
Fluentd runs inside a Debian 9 based container in GKE with fixed throughput of 1000 log entries per second.

**Your Configuration**

https://github.com/Stackdriver/kubernetes-configs/blob/b67c14df983107a5eacecf6bdc8371d284aa4d10/logging-agent.yaml#L131

**Comment by qingling128** [comment]
Further experiments with various Fluentd versions (`1.7.4`, `1.8.0.rc1`, `1.8.0.rc2`, `1.8.0.rc3`, `1.8.0`, `1.8.1`) narrow down to the changes between `1.7.4` and `1.8.0.rc1`.

![image](https://user-images.githubusercontent.com/5287526/76288066-40bfcd80-627c-11ea-85f7-689ff4053149.png)

There are 64 commits in between these two versions: https://github.com/fluent/fluentd/compare/v1.7.4...v1.8.0.rc1.

Did anything look obvious that might contribute to the CPU usage?

**Comment by ganmacs** [comment]
I'm not sure but  [this commit](https://github.com/fluent/fluentd/commit/fcd467c722c491919c7044c772e9e49ead3ef787) might affect usage of CPU. Could you please do the experiment on the previous commit(8535c9a)? 

Most of the change between v1.7.4 to v1.8.0rc1 is adding service discovery feature but it seems that it's not related to this issue since https://github.com/Stackdriver/kubernetes-configs/blob/b67c14df983107a5eacecf6bdc8371d284aa4d10/logging-agent.yaml#L131 doesn't use out_forward.

**Comment by repeatedly** [comment]
Here is the changes from `git diff v1.7.4 v1.8.0.rc1`:

```
+# Unreleased
+
+### New feature
+
+* Add service discovery plugin and `out_forward` use it
+  https://github.com/fluent/fluentd/pull/2541
+
+### Enhancement
+
+* formatter_csv: Support nested fields
+  https://github.com/fluent/fluentd/pull/2643
+* record_accessor helper: Make code simple and bit faster
+  https://github.com/fluent/fluentd/pull/2660
+* clean up internal classes / code
+  https://github.com/fluent/fluentd/pull/2647
+  https://github.com/fluent/fluentd/pull/2648
+  https://github.com/fluent/fluentd/pull/2653
+  https://github.com/fluent/fluentd/pull/2654
+  https://github.com/fluent/fluentd/pull/2657
+
+### Bug fixes
+
+* suppress warning
+  https://github.com/fluent/fluentd/pull/2652
+
```

If you don't use csv, nested fields and out_forward, `clean up internal classes / code` commits may affect.

**Comment by qingling128** [comment]
Just got back to this (got distracted by some stuff including the corona virus). Hope everyone is well!

I did some blind scans of the commits.

1. Grab all the commits and number them by order.

The command I used to get commits was `git log v1.7.4...v1.8.0.rc1 | grep "^commit "`. The resulting commit hashes are as below.

NOTE: `01` => `68` is in time reverse order. In other words, `01` is the latest and `68` is the oldest in this set of commit hashes.

```
~/fluentd-cpu$ cat commits
COMMIT_ORDER=01 COMMIT_HASH=5e44de bash experiment.sh
COMMIT_ORDER=02 COMMIT_HASH=bf0fdc bash experiment.sh
COMMIT_ORDER=03 COMMIT_HASH=cd95ee bash experiment.sh
COMMIT_ORDER=04 COMMIT_HASH=9c577a bash experiment.sh
COMMIT_ORDER=05 COMMIT_HASH=7b166f bash experiment.sh
COMMIT_ORDER=06 COMMIT_HASH=55d633 bash experiment.sh
COMMIT_ORDER=07 COMMIT_HASH=537736 bash experiment.sh
COMMIT_ORDER=08 COMMIT_HASH=87c831 bash experiment.sh
COMMIT_ORDER=09 COMMIT_HASH=fcd467 bash experiment.sh
COMMIT_ORDER=10 COMMIT_HASH=8535c9 bash experiment.sh
COMMIT_ORDER=11 COMMIT_HASH=fa0348 bash experiment.sh
COMMIT_ORDER=12 COMMIT_HASH=1e08d7 bash experiment.sh
COMMIT_ORDER=13 COMMIT_HASH=e92e16 bash experiment.sh
COMMIT_ORDER=14 COMMIT_HASH=90534e bash experiment.sh
COMMIT_ORDER=15 COMMIT_HASH=0dbef0 bash experiment.sh
COMMIT_ORDER=16 COMMIT_HASH=0e8b05 bash experiment.sh
COMMIT_ORDER=17 COMMIT_HASH=01f5ca bash experiment.sh
COMMIT_ORDER=18 COMMIT_HASH=077508 bash experiment.sh
COMMIT_ORDER=19 COMMIT_HASH=45425b bash experiment.sh
COMMIT_ORDER=20 COMMIT_HASH=4209dc bash experiment.sh
COMMIT_ORDER=21 COMMIT_HASH=5df793 bash experiment.sh
COMMIT_ORDER=22 COMMIT_HASH=9c0ba5 bash experiment.sh
COMMIT_ORDER=23 COMMIT_HASH=5324ee bash experiment.sh
COMMIT_ORDER=24 COMMIT_HASH=b1bd1d bash experiment.sh
COMMIT_ORDER=25 COMMIT_HASH=477908 bash experiment.sh
COMMIT_ORDER=26 COMMIT_HASH=540f0a bash experiment.sh
COMMIT_ORDER=27 COMMIT_HASH=24a0fe bash experiment.sh
COMMIT_ORDER=28 COMMIT_HASH=7825ff bash experiment.sh
COMMIT_ORDER=29 COMMIT_HASH=4ce7f3 bash experiment.sh
COMMIT_ORDER=30 COMMIT_HASH=48ed65 bash experiment.sh
COMMIT_ORDER=31 COMMIT_HASH=307722 bash experiment.sh
COMMIT_ORDER=32 COMMIT_HASH=61455a bash experiment.sh
COMMIT_ORDER=33 COMMIT_HASH=a7894c bash experiment.sh
COMMIT_ORDER=34 COMMIT_HASH=99e3f0 bash experiment.sh
COMMIT_ORDER=35 COMMIT_HASH=a72a0a bash experiment.sh
COMMIT_ORDER=36 COMMIT_HASH=afdcdc bash experiment.sh
COMMIT_ORDER=37 COMMIT_HASH=9db46a bash experiment.sh
COMMIT_ORDER=38 COMMIT_HASH=dc86f7 bash experiment.sh
COMMIT_ORDER=39 COMMIT_HASH=02c1e2 bash experiment.sh
COMMIT_ORDER=40 COMMIT_HASH=ee2ae7 bash experiment.sh
COMMIT_ORDER=41 COMMIT_HASH=8fd445 bash experiment.sh
COMMIT_ORDER=42 COMMIT_HASH=7791d8 bash experiment.sh
COMMIT_ORDER=43 COMMIT_HASH=a14af3 bash experiment.sh
COMMIT_ORDER=44 COMMIT_HASH=6e9d91 bash experiment.sh
COMMIT_ORDER=45 COMMIT_HASH=105933 bash experiment.sh
COMMIT_ORDER=46 COMMIT_HASH=f626ed bash experiment.sh
COMMIT_ORDER=47 COMMIT_HASH=157592 bash experiment.sh
COMMIT_ORDER=48 COMMIT_HASH=bf7bb7 bash experiment.sh
COMMIT_ORDER=49 COMMIT_HASH=fd14d0 bash experiment.sh
COMMIT_ORDER=50 COMMIT_HASH=0a0264 bash experiment.sh
COMMIT_ORDER=51 COMMIT_HASH=694745 bash experiment.sh
COMMIT_ORDER=52 COMMIT_HASH=3548e7 bash experiment.sh
COMMIT_ORDER=53 COMMIT_HASH=85f097 bash experiment.sh
COMMIT_ORDER=54 COMMIT_HASH=248834 bash experiment.sh
COMMIT_ORDER=55 COMMIT_HASH=fcb95e bash experiment.sh
COMMIT_ORDER=56 COMMIT_HASH=665682 bash experiment.sh
COMMIT_ORDER=57 COMMIT_HASH=8e362a bash experiment.sh
COMMIT_ORDER=58 COMMIT_HASH=bb7434 bash experiment.sh
COMMIT_ORDER=59 COMMIT_HASH=c761f9 bash experiment.sh
COMMIT_ORDER=60 COMMIT_HASH=067f6d bash experiment.sh
COMMIT_ORDER=61 COMMIT_HASH=051360 bash experiment.sh
COMMIT_ORDER=62 COMMIT_HASH=a62b22 bash experiment.sh
COMMIT_ORDER=63 COMMIT_HASH=48d404 bash experiment.sh
COMMIT_ORDER=64 COMMIT_HASH=ce870c bash experiment.sh
COMMIT_ORDER=65 COMMIT_HASH=070b3b bash experiment.sh
COMMIT_ORDER=66 COMMIT_HASH=17ae60 bash experiment.sh
COMMIT_ORDER=67 COMMIT_HASH=8d1e4a bash experiment.sh
COMMIT_ORDER=68 COMMIT_HASH=5780b9 bash experiment.sh
```

2. Wrote a script to set up the experiment (it integrates with our existing GKE testing framework).

```
~/fluentd-cpu$ cat experiment.sh
#!/bin/bash
set -e
set -x

COMMIT_ORDER="${COMMIT_ORDER:-}"
COMMIT_HASH="${COMMIT_HASH:-}"

cd ~/repo/fluentd
git checkout .
git checkout $COMMIT_HASH
gem install bundler
bundle install --path vendor/bundle
sed -i "s/VERSION.*/VERSION = '1.2.3-$COMMIT_ORDER-$COMMIT_HASH'/g" lib/fluent/version.rb
rm *.gem
gem build fluentd.gemspec
cd ~/repo/stackdriver-kubernetes
FLUENTD_LOCAL_GEM=fluentd-1.2.3.pre.$COMMIT_ORDER.pre.$COMMIT_HASH.gem GENERATED_CONFIGS_GIT_BRANCH=fluentd-$COMMIT_ORDER-$COMMIT_HASH bash generate-configs-for-logging-agent.sh
CONFIGS_GIT_BRANCH=fluentd-$COMMIT_ORDER-$COMMIT_HASH CLUSTER_NAME=fluentd-$COMMIT_ORDER-$COMMIT_HASH bash create-regression-cluster.sh
```

3. First ran experiments with all the `COMMIT_ORDER` ending with `5` and `0`.

![image](https://user-images.githubusercontent.com/5287526/77173369-c9691580-6a95-11ea-9c1e-bcfbf78b78cd.png)

This narrowed down the issue to be between commit `05` and commit `10`:

```
COMMIT_ORDER=05 COMMIT_HASH=7b166f bash experiment.sh (bad)
COMMIT_ORDER=06 COMMIT_HASH=55d633 bash experiment.sh (to be decided next)
COMMIT_ORDER=07 COMMIT_HASH=537736 bash experiment.sh (to be decided next)
COMMIT_ORDER=08 COMMIT_HASH=87c831 bash experiment.sh (to be decided next)
COMMIT_ORDER=09 COMMIT_HASH=fcd467 bash experiment.sh (to be decided next)
COMMIT_ORDER=10 COMMIT_HASH=8535c9 bash experiment.sh (good)
```

The corresponding `git log` is:

```
commit 7b166f08f1f1c5d7aa8f49709843bc0b332ee33e
Author: Yuta Iwama <ganmacs@gmail.com>
Date:   Fri Oct 25 15:51:11 2019 +0900

    Revive MsgpackPack for compat

    Signed-off-by: Yuta Iwama <ganmacs@gmail.com>

commit 55d63355b3d7e7feaba84e69a30a53ba0a28ea66
Author: Masahiro Nakagawa <repeatedly@gmail.com>
Date:   Thu Oct 24 14:10:10 2019 +0900

    Merge pull request #2663 from fluent/logrotate-windows

    Support logrotate on Windows correctly. Fix #2446
    Signed-off-by: Masahiro Nakagawa <repeatedly@gmail.com>

commit 537736f519d4c34aba76580b93af5eb9530d6949 (HEAD)
Author: Masahiro Nakagawa <repeatedly@gmail.com>
Date:   Tue Oct 15 16:15:26 2019 +0900

    Merge pull request #2649 from fluent/fix-child_process-stderr

    child_process helper: fix stderr blocking for discard case. fix #2609
    Signed-off-by: Masahiro Nakagawa <repeatedly@gmail.com>

commit 87c831807fa17c216ee6f6528ba093934ea7aba5
Author: Masahiro Nakagawa <repeatedly@gmail.com>
Date:   Wed Oct 9 22:06:16 2019 +0900

    Merge pull request #2640 from achinchen/modify-response-http-code

    Semantic Status Code - modify on_request response from 200 to 204 in plugin/in_http
    Signed-off-by: Masahiro Nakagawa <repeatedly@gmail.com>

commit fcd467c722c491919c7044c772e9e49ead3ef787
Merge: 8535c9a5 4209dcf8
Author: Yuta Iwama <ganmacs@gmail.com>
Date:   Fri Oct 25 10:59:51 2019 +0900

    Merge pull request #2657 from ganmacs/remove-mixin

    there is no reason calling mesgpacker_unapcker/packer from Fluent::Engine

commit 8535c9a5b0ee4f7e3b0dd65de8954f9436eafecc
Merge: 1e08d763 fa0348d5
Author: Masahiro Nakagawa <repeatedly@gmail.com>
Date:   Thu Oct 24 14:10:10 2019 +0900

    Merge pull request #2663 from fluent/logrotate-windows

    Support logrotate on Windows correctly. Fix #2446
```

4. Next, I'm running the experiments with `06` - `09`. I will paste the results shortly.

**Comment by qingling128** [comment]
Experiments done. Looks like the commit that triggered the CPU usage increase is `05-7b166f`:

```
commit 7b166f08f1f1c5d7aa8f49709843bc0b332ee33e
Author: Yuta Iwama <ganmacs@gmail.com>
Date:   Fri Oct 25 15:51:11 2019 +0900

    Revive MsgpackPack for compat

    Signed-off-by: Yuta Iwama <ganmacs@gmail.com>
```

![image](https://user-images.githubusercontent.com/5287526/77188091-d5f86880-6aab-11ea-8563-68e49b0fbb1b.png)

@repeatedly @ganmacs - What should we do next? It looks like a simple PR (effectively one line). Is this PR something we can safely revert? If not, can we add a flag to optionally disable it?

![image](https://user-images.githubusercontent.com/5287526/77188358-40a9a400-6aac-11ea-82b8-22bf302d26c8.png)

**Comment by ganmacs** [comment]
> Experiments done. Looks like the commit that triggered the CPU usage increase is 05-7b166f:

Thank you for the great help!

> What should we do next? It looks like a simple PR (effectively one line). Is this PR something we can safely revert? If not, can we add a flag to optionally disable it?

I'll take care of it.

**Comment by ganmacs** [comment]
https://github.com/fluent/fluentd/pull/2903 should fix this issue. 

@qingling128  Could you please confirm this path works fine in the experiments env?

**Comment by qingling128** [comment]
Thanks @ganmacs ! Sure thing. On it now.

**Comment by qingling128** [comment]
CPU usage looks positive. Memory and throughput looks good too.
@ganmacs Thanks for the fix!

**CPU**
![image](https://user-images.githubusercontent.com/5287526/77366256-0818fd00-6d2e-11ea-8bac-679ebc6f4958.png)

**Comment by ganmacs** [comment]
@qingling128 Thank you so much for the help!! 

fluent-plugin-google-cloud uses deprecated methods. So I created PR to fix it
https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud/pull/386 . Can you please take a look at it If you have a chance?

**Comment by qingling128** [comment]
Sure thing. I will again run the experiment and merge that PR once it passes our tests.
