### ISSUE TITLE
fluentd memory problem

### ISSUE THREAD

**Issue by ted222** [fluent/fluentd#2872]
hello，
I‘ve met a problem about memory when I used fluentd to collect logs.
I started six fluentd workers to collect logs, The memory which fluentd used increased a little everyday,. I found every worker used about average 15% memory of all:
![image](https://user-images.githubusercontent.com/30408499/76291032-4999b900-62e7-11ea-9bc0-0a8d90953aec.png)

I doubt it will be out of memory one day.

my log situation:
there are nearly 3000 log files every minutes，I set 6 workers to collect these log files. my td-agent.conf is :
<system>
  log_level error
  workers 6
</system>

<worker 0>
	<source>
	  @type tail
	  path /home/lamp/cin/logs/LN%y%m%d/%H/0*/**/*.log
	  pos_file /home/td-agent/pos/pos0.log
	  tag snlog
	  path_key filename
	  read_from_head true
	  refresh_interval 1s
	  multiline_flush_interval 5s
	  rotate_wait 600
	  limit_recently_modified 200
	  encoding UTF-8
	  <parse>
		@type multiline
		format_firstline /^\[\d{4}-\d{1,2}-\d{1,2}/
		format1 /^\[(?<@logtime>\d{4}-\d{1,2}-\d{1,2} \d{1,2}:\d{1,2}:\d{1,2})\] (?<message>.*)/
		time_key @timestamp
	  </parse>
	</source>

	<filter caih-*>
	  @type grep
	  <exclude>
		key severity
		pattern /DEBUG/
	  </exclude>
	</filter>

	<filter caih-*>
		@type record_transformer
		<record>
			hostname "#{Socket.gethostname}"
		</record>
	</filter>

	<match caih-*>
	  @type forward
	  @log_level info
	  <server>
		host 10.33.22.81
		port 24224
		weight 50
	  </server>
	  <server>
		host 10.33.22.82
		port 24224
		weight 50
	  </server>
	  <buffer tag,time>
		@type file
		path /home/td-agent/buffer/worker1
		timekey 10
		timekey_wait 0s
		timekey_use_utc false
		flush_mode interval
		flush_interval 5s
                #flush_thread_count 4
                queued_chunks_limit_size 5000
		chunk_limit_size 200M
	  </buffer>
	</match>
</worker>

**Comment by ganmacs** [comment]
Please follow the issue template and read https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md
