### ISSUE TITLE
Issue with FluentD time key . time key is showing an wrong value in the fluentD record

### ISSUE THREAD

**Issue by anandr781** [fluent/fluentd#2875]
Check [CONTRIBUTING guideline](https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md) first and here is the list to help us investigate the problem.

**Describe the bug**
FluentD V1.9.2 does not write the correct time . My configuration : 

<img width="1614" alt="Screen Shot 2020-03-11 at 11 22 31 PM" src="https://user-images.githubusercontent.com/38281150/76447802-4984e080-63ef-11ea-9435-8b0d11e08614.png">

**To Reproduce**

**Expected behavior**
The correct time key should be injected as per the inject configuration .

**Your Environment**

- Fluentd or td-agent version:  FluentD V1.9.2
- Operating system: Official FluentD V1.9.2 docker container
- Fluent Bit v1.3.10

If you hit the problem with older fluentd version, try latest version first.

**Your Configuration**
 See Above  

**Your Error Log**
```
020-03-11 17:51:43 +0000 [info]: #0 starting fluentd worker pid=20 ppid=6 worker=0
**2020-03-11 17:51:43 +0000** [info]: #0 [input1] listening port port=24224 bind="0.0.0.0"
**2020-03-11 17:51:43 +0000 [info]:** #0 fluentd worker is now running worker=0
**2077-10-11 09:10:10.000000000 +0000** jsonpayloadfaker.payload: {"fakeJson-1":"{\"studentName\":\"TestStudent\",\"studentID\":17,\"studentPhone\":\"123-456-789\",\"studentAddress\":[{\"address\":\"123, ABC Road\",\"addressType\":\"Office\"},{\"address\":\"456, XYZ Road\",\"addressType\":\"Home\"}]}","hostname":"flb.docker1","time":"10/2077/11T09:10:10.000000000Z"}
2077-10-11 09:43:58.000000000 +0000 jsonpayloadfaker.payload: {"fakeJson-2":"{\"studentName\":\"TestStudent\",\"studentID\":17,\"studentPhone\":\"123-456-789\",\"studentAddress\":[{\"address\":\"123, ABC Road\",\"addressType\":\"Office\"},{\"address\":\"456, XYZ Road\",\"addressType\":\"Home\"}]}","hostname":"flb.docker1",**"time":"10/2077/11T09:43:58.000000000Z"**}
2077-10-11 10:17:19.000000000 +0000 jsonpayloadfaker.payload: {"fakeJson-3":"{\"studentName\":\"TestStudent\",\"studentID\":17,\"studentPhone\":\"123-456-789\",\"studentAddress\":[{\"address\":\"123, ABC Road\",\"addressType\":\"Office\"},{\"address\":\"456, XYZ Road\",\"addressType\":\"Home\"}]}","hostname":"flb.docker1",**"time":"10/2077/11T10:17:19.000000000Z"**}
```
**Additional context**

As you can see the bolded parts of the log and the attached screenshot when FluentD starts it shows the correct timestamp but when logs start to arrive and the inject section injects the incorrect timestamp "2077-09-18......." when the correct timestamp should be something like "2020-03-11......." .

**Comment by ganmacs** [comment]
I think it's expected behavior. The bolded parts are not the log stdout output emits.

**Comment by anandr781** [comment]
I was able to get this to work after stopping to send the timestamp from the code and allowed FluentBit to generate the timestamp.
