### ISSUE TITLE
How to index Windows application logs from D-drive to Elastic search using Fluentd

### ISSUE THREAD

**Issue by muralikri32** [fluent/fluentd#2887]
Hi,

I am trying to index Windows application logs from D-drive to elasticsearch using fluentd. Once i start the Fleutd service none of the logs are indexing. I am new to EFK, could someone guide me how to index plain test files from windows to Elasticsearch.

Config file:
##INPUT 
<source>
  @type tail
  @id input_tail
  format single_value
  <parse>
  type none
  </parse>
  path D:/testlogs/applogs.txt
  pos_file /opt/td-agent/applog.pos
  tag server.app.log
</source>

##output config path
<match *.**>
  @type forward
  @type elasticsearch
  host elastic-search-hostname
  port 9200
  logstash_format false
  include_timestamp true
  index_name fluentd_server
</match>
D:/testlogs/applogs.txt
  Servername:RUNNING:CPU90:INODE80
  Servername:RUNNING:CPU90:INODE80
  Servername:RUNNING:CPU90:INODE80

**Comment by ganmacs** [comment]
Follow an issue template

**Comment by muralikri32** [comment]
Hi ganmacs, I am new to this forum. As you suggest above could you please guide me to post this issue in issue template..
