### ISSUE TITLE
How to index RAW data from Windows machine to Elastic search using Fluentd

### ISSUE THREAD

**Issue by muralikri32** [fluent/fluentd#2895]
Check [CONTRIBUTING guideline](https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md) first and here is the list to help us investigate the problem.

**Describe the bug**
I am trying to index Windows RAW data from D-drive to elasticsearch using fluentd. Once i start the Fleutd service none of the logs are indexing. I am new to EFK, could someone guide me how to index plain test files from windows to Elasticsearch.

**To Reproduce**
Created a RAW data file and created config file with "none" parse option as below and after start td-agent service in windows i could find any logs in Kibana

**Expected behavior**
Expect RAW data as present in log file to be index in Kibana without any parses or any formats

**Your Environment**
Windows 2012 server and it is DEv machine

- Fluentd or td-agent version: fluentd 1.7.4
- Operating system: Windows 2012
- Kernel version: `uname -r`

If you hit the problem with older fluentd version, try latest version first.

**Your Configuration**

##INPUT 1
<source>
  @type tail
  path D:/testlogs/testfile.txt
  pos_file C:/opt/td-agent/testfile.pos
  tag server.testfile.log
  read_from_head true
  @log_level error
  <parse>
  @type none
  </parse>
</source>

<label @fluent_log>
  <match @fluent.*>
    @type null
  </match>
</label>

##output config path
<match server.**>
  @type forward
  @type elasticsearch
  host elasticsearch-hostname
  port 9200
  logstash_format false
  include_timestamp true
  index_name nonprod_server
  fluentd flush_thread_count 30s
</match>

**Your Error Log**

Logs are fine and couldn't find logs are indexing in kibana

**Additional context**

**Comment by cosmo0920** [comment]
Follow the guideline. Here is not forum but issue tracker. Thanks!
