### ISSUE TITLE
Create SECURITY.md policy + post security audit

### ISSUE THREAD

**Issue by caniszczyk** [fluent/fluentd#2910]
Fluentd should create a SECURITY.md file which is the standard way for GitHub now to deal with security disclosures. You should also post a link to the 2019 audit: https://cure53.de/pentest-report_fluent.pdf

Once you do, I recommend updating your README like this:
https://github.com/envoyproxy/envoy#security

**Comment by edsiper** [comment]
@caniszczyk is this ok ?

https://github.com/fluent/fluentd#security
