### ISSUE TITLE
Cisco syslog invalid input data error

### ISSUE THREAD

**Issue by from88** [fluent/fluentd#2925]
**Describe the bug**
Invalid time format error

**To Reproduce**
Send CISCO Nexus syslog to fluentd

**Expected behavior**
To be automatically parsed without errors

**Your Environment**

- Fluentd or td-agent version: fluentd 1.10.0
- Operating system: CentOS Linux 7
- Kernel version: 3.10.0-1062.4.3.el7.x86_64

If you hit the problem with older fluentd version, try latest version first.

**Your Configuration**
```
<source>
  @type syslog
  port 5140
  bind 0.0.0.0
  tag system
</source>
```

**Logs**

```
tail -f /var/log/td-agent/td-agent.log
2020-04-01 10:46:57 +0200 [error]: #0 invalid input data="<189>: 2020 Apr  1 09:46:57 CET: %ETH_PORT_CHANNEL-5-PORT_INDIVIDUAL_DOWN: individual port Ethernet104/1/6 is down" error_class=Fluent::TimeParser::TimeParseError error="invalid time format: value = : 2020 Apr, error_class = ArgumentError, error = string doesn't match"
2020-04-01 10:47:07 +0200 [error]: #0 invalid input data="<189>ITXNET03A: 2020 Apr  1 09:47:07 CET: %ETHPORT-5-SPEED: Interface Ethernet119/1/11, operational speed changed to 1 Gbps" error_class=Fluent::TimeParser::TimeParseError error="invalid time format: value = ITXNET03A: 2020 Apr, error_class = ArgumentError, error = string doesn't match"
```

As you see line above doesnt have hostname prepended and the host beyond has it. But error is in both situations.
AFAIK the fluentd should parse syslog messages automatically. as Cisco syslog is RFC rfc3164  (at least it tries:) )
What could i do to fix this behaviour ?
Also, do i need to parse it correctly if my goal is to send them via remote_syslog plugin or kafka plugin to logstash system ? and do the finam parsing there

**Comment by ganmacs** [comment]
Your log doesn't follow rfc3164. See https://tools.ietf.org/html/rfc3164#section-4.1.2
rfc3164 doesn't allow `:` between priority and timestamp.

**Comment by from88** [comment]
thanks, so as i understand i need to parse it manually ?
Btw, maybe you know if;s possible to forward further (via remote syslog plugin) this unparsed log ? Thank you !

**Comment by ganmacs** [comment]
> so as i understand i need to parse it manually ?

Yes.

> Btw, maybe you know if;s possible to forward further (via remote syslog plugin) this unparsed log ?

I'm not sure your situation in detail but you might make it with in_tcp or in_udp.

> And btw seems like the second log entry (from other device): obey that ":" rule:


rfc3164 doesn't allow : between priority and timestamp.

Priority is `<189> ` and timestamp is `2020 Apr 1 16:03:48`. Please read RFC https://tools.ietf.org/html/rfc3164#section-4.1.2


If you have any question, Please ask in mailing list. https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md#got-a-question-or-problem

**Comment by from88** [comment]
thank you.

**Comment by RenanHingel** [comment]
Sorry to dig up this thread, I'm facing the very same issue with my firewalls, what solution did you apply @from88 ?

**Comment by from88** [comment]
Hello, i made a configufation to just forward the log message without any parsing/formating

**Comment by bradkelso32** [comment]
@from88 sorry to add a comment to this old thread. I removed the parse, filter, and format tags in the td-agent.conf file but I still get the TimeParseError error. How did you configure it to remove all parsing/formatting?

**Comment by from88** [comment]
> @from88 sorry to add a comment to this old thread. I removed the parse, filter, and format tags in the td-agent.conf file but I still get the TimeParseError error. How did you configure it to remove all parsing/formatting?

hello, i'm not using it anymore, but from the documentation i see that the configuration steps was like this: 

0)https://docs.fluentd.org/installation/before-install
1)curl -L https://toolbelt.treasuredata.com/sh/install-redhat-td-agent3.sh | sh
2)
sudo systemctl start td-agent.service
sudo systemctl status td-agent.service
sudo systemctl enable td-agent.service

3)
add iptables permantetly:

sudo iptables -A PREROUTING -t nat -p udp --dport 514 -i eth0 -j REDIRECT --to-port 5140
sudo iptables -A PREROUTING -t nat -p tcp --dport 514 -i eth0 -j REDIRECT --to-port 5140

iptables-save > /etc/sysconfig/iptables

nano /etc/rc.local
# Load iptables rules from this file
iptables-restore < /etc/sysconfig/iptables

chmod +x /etc/rc.d/rc.local
systemctl start rc-local

4) install ruby 2.7: 
https://tecadmin.net/install-ruby-latest-stable-centos/

5) install remote syslgo plugin
sudo td-agent-gem install fluent-plugin-remote_syslog

6)add sources and tables cat /etc/td-agent/td-agent.conf

<source>
  @type udp
  port 5140
  bind 0.0.0.0
  tag systema
  format none
  source_address_key client_addr
</source>

<source>
  @type tcp
  port 5140
  bind 0.0.0.0
  tag systema
  format none
  source_address_key client_addr
</source>

<match systema>
  @type remote_syslog
  host laas-logstash-shipper.service.discovery.pr.xxx.zone
  port 5560
</match>

**Comment by from88** [comment]
> @from88 sorry to add a comment to this old thread. I removed the parse, filter, and format tags in the td-agent.conf file but I still get the TimeParseError error. How did you configure it to remove all parsing/formatting?

hello, i'm not using it anymore, but from the documentation i see that the configuration steps was like this: 

[config.txt](https://github.com/fluent/fluentd/files/11098148/config.txt)
