### ISSUE TITLE
Support tag and format for unix socket input plugin

### ISSUE THREAD

**Issue by lzang** [fluent/fluentd#2929]
Check [CONTRIBUTING guideline](https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md) first and here is the list to help us investigate the problem.

**Is your feature request related to a problem? Please describe.**

Tried to use unix socket input plugin as described here
https://docs.fluentd.org/input/unix
Then realized that it  doesn't support tag and format from fluentd log

```
2020-04-02 00:09:53 +0000 [warn]: parameter 'format' in <source>
  @type unix
  format json
  tag test-log
  path "/var/log/test-log.sock"
</source> is not used.
2020-04-02 00:09:53 +0000 [warn]: parameter 'tag' in <source>
 @type unix
  format json
  tag test-log
  path "/var/log/test-log.sock"
</source> is not used.
```
What is the reason that these parameters are not supported?

**Describe the solution you'd like**

Support unix socket in the same way as tcp socket input plugin.

**Describe alternatives you've considered**

**Additional context**

**Comment by ganmacs** [comment]
in_unix plugin expects the data format like below.  So it can't allow setting `format` and  `tag`.
@repeatedly Do you know the reason for this?

https://github.com/fluent/fluentd/blob/cc97aa414f918e0ae7a596cc5ccca8e5fa080ee2/lib/fluent/plugin/in_unix.rb#L61-L80

**Comment by repeatedly** [comment]
> Do you know the reason for this?

`in_unix` supports forward protocol for TCP based `in_forward` replacement.
This is mainly for PHP like environment.

Users can set tag in application side, so I'm not sure why tag/format is needed.

**Comment by lzang** [comment]
Theoretically it should be no different from tcp socket, right? If TCP socket supports tag/format, why unix socket doesn't?  forward sounds a different plugin.

**Comment by repeatedly** [comment]
>  If TCP socket supports tag/format, why unix socket doesn't? forward sounds a different plugin.

Because in_unix is born for unix domain socket version of in_forward for PHP like environment. I mentioned it in my previous comment.

If need unix domain socket version of in_tcp, create new plugin is better for now.
