### ISSUE TITLE
Option to ignore empty messages composed entirely of non-printable characters - ie: line breaks, tabs and spaces

### ISSUE THREAD

**Issue by juliohm1978** [fluent/fluentd#2940]
**Is your feature request related to a problem? Please describe.**

I'm managing a Kubernetes cluster with a large number of Java applications, most of which tend to use empty line breaks between log messages. Fluentd sends logs to a Graylog instance, and the GELF protocol refuses empty records.

```
java.lang.IllegalArgumentException: GELF message <e0281040-79cd-11ea-8753-0000ac19acf0> (received from <172.25.173.167:50695>) has empty mandatory "short_message" field.
```
While this problem is particularly related to the GELF protocol, refusing to store apparently empty messages in a search index is a reasonable requirement.

Because of the nature of our applications, Graylog is flooded with the same error messages, which takes its toll on performance at large scale.

Under the hood, in docker logs, these messages appear with the following format:

```
{"log":"\n","stream":"stderr","time":"2020-03-25T18:08:47.256011014Z"}
```

Fluentd captures that record and sends `\n` as the message content.

I've been trying to configure fluentd to ignore messages that contain a single new line character `\n`, but I can't seem to get that filter to work. While I work this out in the help forums, I decided to write this feature request.

**Describe the solution you'd like**

Add a global flag somewhere in the native fluentd configuration that allows these empty messages to be ignored, mainly messages composed entirely of space, line break and tab characters -- the usual `\s+` in a regular expression.

**Describe alternatives you've considered**

I'm trying to configure fluentd filters to ignore these log messages, but I'm having a hard time getting it to work. The following filter has no effect:

```
<filter **>
  @type grep
  <exclude>
    key message
    pattern ^\n$
  </exclude>
</filter>
<filter **>
  @type grep
  <exclude>
    key short_message
    pattern ^\n$
  </exclude>
</filter>
```

**Comment by ganmacs** [comment]
The following grep test works. This might help you https://docs.fluentd.org/configuration/config-file#note-on-match-order
```
<source>
  @type dummy
  tag dummy
  dummy {"message": "\n"}
</source>

<filter **>
  @type grep
  <exclude>
    key message
    pattern ^\n$
  </exclude>
</filter>

<match>
  @type stdout

  <buffer>
    flush_interval 1s
  </buffer>
</match>
```

**Comment by juliohm1978** [comment]
I was not aware of the dummy source. That is so helpful!

I managed to figure out my problem. I was matching against `key message`, when in fact I sould be matchin `key log`

```
{"log":"\n","stream":"stderr","time":"2020-03-25T18:08:47.256011014Z"}
```

So, the following works as expected:

```
<filter **>
  @type grep
  <exclude>
    key log
    pattern ^\n$
  </exclude>
</filter>
```

Thank you!
