### ISSUE TITLE
ArgumentError error="message does not exist" in Fluentd

### ISSUE THREAD

**Issue by ashleshmandke** [fluent/fluentd#2944]
Hey,

I am getting below error :-
[warn]: #0 dump an error event: error_class=ArgumentError error="message does not exist"
I also cleared my current index and executed the fluentd script but its still rejecting records and giving out "[warn]: #0 dump an error event: error_class=ArgumentError error="message does not exist"" error.

what should be the key_name value I had given message (docs suggest it should be name of the field to be parsed, I gave a unique field name "id" but it seems to give out same error)
For almost 2.5 years this never give an issue and no suddenly its giving out error.

Seems it is a issue with elasticsearch. Please help ;)

Our data also has json fields c&d and they are defined as text in kibana template.
Please find sample of my fluentd script: [fluentd.txt](https://github.com/fluent/fluentd/files/4460464/fluentd.txt)

**Comment by dborysenko** [comment]
If you are like me came here by looking for an answer on why you getting `error_class=ArgumentError error="message does not exist"` Fluentd error, here is what I found for myself and wanted to share.

Lets say you have below config
```
#Assuming log lines coming from /var/log/whatever.log have a field "message" which contains JSON.
<source>
  @type tail
  path /var/log/whatever.log
  tag in.tail
</source>

<filter in.tail>
    @type parser
    key_name message
    remove_key_name_field true
    reserve_data false
    <parse>
        @type json
    </parse>
</filter>

<match in.tail>
  @type opensearch
  <endpoint>
    url https://my-opensearch.example.com
    region us-west-2
  </endpoint>
  log_os_400_reason yes
  logstash_format true
  logstash_prefix whatever-index
</match>
```

First obvious reason to get `error_class=ArgumentError error="message does not exist"` error is when indeed log line came from input did not have "message" field.
Second not that obvious reason is when your output plugin (Opensearch in my case, could be Elasticsearch as well) send bulk ingest request, but not all records within the batch were indexed. In this case output plugin will re-emit the record with same tag. This leads the record to go through filter plugin again, where filter will try to find and parse "message" key which is not there.

To prevent it, you could use LABEL to route your retries, or use `retry_tag` in opensearch output plugin like below:

```
<match in.tail.retry>
  @type opensearch
  <endpoint>
    url https://my-opensearch.example.com
    region us-west-2
  </endpoint>
  log_os_400_reason yes
  logstash_format true
  logstash_prefix whatever-index
  retry_tag 'in.tail.retry'
</match>
```

This way retried records will skip filter and go directly to output.
