### ISSUE TITLE
Convert timestamp with nanoseconds JSON attribute to MongoDB ISODate

### ISSUE THREAD

**Issue by magsoftware** [fluent/fluentd#2954]
**Describe the bug**
I am trying to push JSON message with createdAt (timestamp with nanoseconds) field to MongoDB. I want to save this field as timestamp with nanoseconds in MongoDB - exactly in the same way as time field is saved. Either am I doing something wrong or it seems not to work. I tried to:
1. define type of this field to time, but nanoseconds are cut off in MongoDB
2. define time field to take value from createdAt (time_key) - I get strange values for time.

**To Reproduce**
Post this to http source:
curl -X POST -d '{"createdAt": "2018-05-14T11:37:30.339593", "count": 78, "status": "Sent", "dataId": "332"}' http://localhost:9090/flex

With the configuration:
```
<source>
  @type http
  port 9090
  bind 0.0.0.0
  <parse>
    @type json
    types createdAt:time:%Y-%m-%dT%H:%M:%S.%N, count:integer, status:string, dataId:string
  </parse>
</source>
```
I get 

```
createdAt: 1526297850
time: 2020-04-15T20:30:32.499+00:00
```
And when I try to define createdAt as time_key:
```
<source>
  @type http
  port 9090
  bind 0.0.0.0
  <parse>
    @type json
    time_key createdAt
    keep_time_key true
  </parse>
</source>
```

I get:
```
createdAt: "2018-05-14T11:37:30.339593"
time: 1970-01-01T00:33:38.339+00:00
```

So, createdAt is saved as string (correct), but time has strange value.

**Expected behavior**
1. I would expect to have createdAt with nanoseconds stored like time field.
2. I would expect time field to have value of createdAt.

**Your Environment**

Docker with base image: fluent/fluentd:v1.10-1

```
'fluent-plugin-mongo' version '1.3.0'
'fluent-plugin-rabbitmq' version '0.0.9'
'fluentd' version '1.10.2'
ruby="2.5.8"
```

**Your Configuration**

1.

```
<source>
  @type http
  port 9090
  bind 0.0.0.0
  <parse>
    @type json
    types createdAt:time:%Y-%m-%dT%H:%M:%S.%N, count:integer, status:string, dataId:string
  </parse>
</source>

<match *>
  @type mongo
  connection_string mongodb://xxx
  collection events
  <buffer>
    flush_interval 1s
  </buffer>
</match>
```

2.

```
<source>
  @type http
  port 9090
  bind 0.0.0.0
  <parse>
    @type json
    time_key createdAt
    keep_time_key true
  </parse>
</source>

<match *>
  @type mongo
  connection_string mongodb://xxx
  collection events
  <buffer>
    flush_interval 1s
  </buffer>
</match>
```

**Comment by repeatedly** [comment]
Fixed by mongo plugin side.
