### ISSUE TITLE
memory usage seems to be growing indefinitely until OOM

### ISSUE THREAD

**Issue by 4ndr4s** [fluent/fluentd#2955]
Check [CONTRIBUTING guideline](https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md) first and here is the list to help us investigate the problem.

**Describe the bug**
Memory usage is growing with elasticsearch plugin and type stdout until OOM, the issue started after migration from fluentd version 0.12.26 to 1.9.3 I just tested the 1.10.2 version with the same result.
![Screen Shot 2020-04-15 at 11 44 21 PM](https://user-images.githubusercontent.com/28128535/79415497-2bbd1500-7f73-11ea-97d5-13bf0e18bb8b.png)

**To Reproduce**
run a docker container collecting high amount of logs.

**Expected behavior**
stable memory usage:
![Screen Shot 2020-04-15 at 11 38 19 PM](https://user-images.githubusercontent.com/28128535/79415168-3b882980-7f72-11ea-93d9-f0a925dde130.png)

**Your Environment**

- Fluentd or td-agent version: `fluentd 1.10.2`
- Operating system: `alpine 3.9`

**Your Configuration**

```
<source>
  @type syslog
  port 514
  <transport udp>
  </transport>
  tag  system
  @log_level info
</source>

<source>
  @type syslog
  port 514
  <transport tcp>
  </transport>
  tag  system
</source>

<source>
  @type monitor_agent
  bind 0.0.0.0
  port 24220
</source>

<label @FLUENT_LOG>
  <match fluent.**>
    @type null
  </match>
</label>

<filter **>
  @type elasticsearch_genid
  hash_id_key alert_hash
</filter>

<match **>
  @type copy
  <store>
    @type elasticsearch
    host elasticsearch.example.com
    logstash_format true
    include_tag_key true
    tag_key key
    flush_interval 10s
    id_key alert_hash
    remove_keys alert_hash
  </store>
  <store>
    @type stdout
  </store>
</match>

<system>
  log_level warn
  emit_error_log_interval 300
  path /var/log/fluent/fluentd
</system>
```

**Your Error Log**

```
No error logs
```

**Additional context**

I ran a similar configuration with fluentd 0.12.26 and alpine 3.4 without any issues, that version is running in our production environments collecting huge amount of logs without any OOM issue.

https://github.com/fluent/fluentd/issues/2926#issuecomment-614114095

**Comment by ganmacs** [comment]
As @repeatedly said in #2926, your configuration doesn't use file buffer. Can you try to use file buffer? https://docs.fluentd.org/buffer/file

> Your graph shows it is not memory leak. Issue author and you use memory buffer.
So if incoming speed is faster than output spped, memory usage is growing.

**Comment by repeatedly** [comment]
You can use in_monitor_agent to get the buffer status.
If buffer queue is growing, the problem is output speed of elasticsearch plugin.

**Comment by 4ndr4s** [comment]
@repeatedly im using that plugin and you are right, the buffer is growing but that wasn’t happening with 0.12.26 version and handled a huge amount of logs, both versions are running now and we are having issues only with the new one.

**Comment by 4ndr4s** [comment]
closing this, issue was sorted out

**Comment by bragi92** [comment]
@4ndr4s I'm curious as to how the issue was resolved for you. Was it something related to the buffer plugin or something else?

**Comment by 4ndr4s** [comment]
@bragi92 hello, I didn't sorted this using the latest version, when I used buffer as file that give me a new problem the disk was filling up quickly, and was necessary limit the buffer size to avoid it, at the end I keep the old version working without any issue.

fluentd version 0.12.43
```<source>
  @type syslog
  port 514
  protocol_type udp
  tag  system
  @log_level info
</source>

<source>
  @type syslog
  port 514
  protocol_type tcp
  tag  system
</source>

<source>
  @type monitor_agent
  bind 0.0.0.0
  port 24220
</source>

<match fluent.**>
  @type null
</match>

<filter **>
  @type elasticsearch_genid
  hash_id_key alert_hash
</filter>

<match **>
  @type copy
  <store>
    @type elasticsearch
    host elasticsearch.example.com
    logstash_format true
    include_tag_key true
    tag_key key
    flush_interval 10s
    id_key alert_hash
    remove_keys alert_hash
  </store>
  <store>
    @type stdout
  </store>
</match>

<system>
  log_level warn
  emit_error_log_interval 300
  path /var/log/fluent/fluentd
</system>

**Comment by kfantonio** [comment]
@4ndr4s I'm also having the same issue (fluentd 1.10.2, debian container, Elasticsearch plugin v4.0.2). I wonder if it could be related to the Elasticsearch plugin itself. Which version of the plugin do have on your working fluentd ?

**Comment by 4ndr4s** [comment]
Hello @kfantonio I've been using an old but stable plugins and configuration, we have fluent container running as sidecar, managing near to 2k messages per second and those are the plugins:

elasticsearch (7.5.0)
elasticsearch-api (7.5.0)
elasticsearch-transport (7.5.0)
fluent-plugin-elasticsearch (1.13.0)
