### ISSUE TITLE
Wrong time when field "time" exist in the logs

### ISSUE THREAD

**Issue by SmittyCooger** [fluent/fluentd#2971]
**Describe the bug**
I have a log in json format (docker) that has a field time already in it,
when i start fluentd the log is displayed wiith a wrong time

**To Reproduce**
just run the below config with this file log :
test.log 
> {"log":"Listening for transport dt_socket at address: 8001\n","stream":"stdout","time":"2020-04-25T17:47:34.356937755Z"}

**Expected behavior**
it should display the time of the event

**Your Environment**

- td-agent version: `td-agent 1.9.2`
- Operating system: `Red Hat Enterprise Linux Client 7.7 (Maipo)`
- Kernel version: `3.10.0-1062.el7.x86_64`

**Your Configuration**
fluent.conf :
```
<source>
@type tail
path ./test.log
tag k8s.log
  <parse>
    @type json
  </parse>
</source>

<match **>
@type stdout
</match>
```

**Your Error Log**
in the out put it shows the time just minutes later from when the count of the unix timestamp has began :
```
1970-01-01 01:33:40.356937755 +0100 k8s.log: {"log":"Listening for transport dt_socket at address: 8001\n","stream":"stdout"}
```

**Comment by repeatedly** [comment]
Specify proper time_format in your `<parse>` config.

https://docs.fluentd.org/configuration/parse-section#time-parameters

**Comment by SmittyCooger** [comment]
Yep worked fine thanx
