### ISSUE TITLE
Nginx log not supported

### ISSUE THREAD

**Issue by serut** [fluent/fluentd#2991]
Hello

**Describe the bug**
I use the default nginx parser and one type of message is not correctly handled (others are fine). I don't know where your regex is but I hope the fix won't be too complicated.

This is the message not supported :

> 2020/05/04 17:01:22 [error] 13#13: *4528 connect() failed (111: Connection refused) while connecting to upstream, client: 10.11.1.4, server: , request: \"GET /api/v1/rs-admin/notifications?page=0&size=1&state=READ HTTP/1.1\", upstream: \"http://10.11.5.82:9030/api/v1/rs-admin/notifications?page=0&size=1&state=READ\

Another message not supported :
> 2020/05/05 13:18:09 [error] 11#11: *5828 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 10.11.1.4, server: , request: \"POST /zuul/api/v1/rs-notifier/microservice/configuration HTTP/1.1\", upstream: \"http://10.11.5.82:9030/zuul/api/v1/rs-notifier/microservice/configuration\", host: \"172.26.47.176\", referrer: \"http://172.26.47.176/admin/project1/microservice/rs-notifier/conf-backup\"

**Expected behavior**

This message should be parsed right ?

**Your Environment**

- Fluentd docker  `v1.10-1`

**Your Configuration**

```

# Use NGINX parse for front logs
<label @PARSENGINX>
    <filter front>
        @type parser
        key_name message
        <parse>
            @type nginx
        </parse>
    </filter>
    <match **>
        @type copy
        <store>
            @type relabel
            @label @OUTPUT
        </store>
    </match>
</label>

```

**Your Error Log**

```
geode_rs-fluent.0.waomh38kdr5x@regards-clone1.cloud-espace.mycompany.fr    | 2020-05-11 13:35:02 +0000 [warn]: #0 dump an error event: error_class=Fluent::Plugin::Parser::ParserError error="pattern not matched with data '2020/05/04 17:01:22 [error] 13#13: *4528 connect() failed (111: Connection refused) while connecting to upstream, client: 10.11.1.4, server: , request: \"GET /api/v1/rs-admin/notifications?page=0&size=1&state=READ HTTP/1.1\", upstream: \"http://10.11.5.82:9030/api/v1/rs-admin/notifications?page=0&size=1&state=READ\", host: \"172.26.47.176\", referrer: \"http://172.26.47.176/admin/project1/microservice/board\"'" location=nil tag="front" time=2020-05-11 13:35:02.685976742 +0000 record={"message"=>"2020/05/04 17:01:22 [error] 13#13: *4528 connect() failed (111: Connection refused) while connecting to upstream, client: 10.11.1.4, server: , request: \"GET /api/v1/rs-admin/notifications?page=0&size=1&state=READ HTTP/1.1\", upstream: \"http://10.11.5.82:9030/api/v1/rs-admin/notifications?page=0&size=1&state=READ\", host: \"172.26.47.176\", referrer: \"http://172.26.47.176/admin/project1/microservice/board\"", "emitter"=>"front", "container_id"=>nil}

```

**Comment by ayushwebkul** [comment]
Are you using both nginx access and error log parser?

**Comment by serut** [comment]
I'm sending both error and access logs to this parser :

        <parse>
            @type nginx
        </parse>

Am I doing something wrong ?

**Comment by repeatedly** [comment]
nginx's error log format is different from nginx's access log.
error log format is free form so hard to write regexp for actual log message.

One way is using regexp parser to extract `time` and `message` fields, e.g. time is `2020/05/04 17:01:22 ` and message is `[error] 13#13: *4528 connect() failed (111: Connection refused) while connecting to upstream, client: 10.11.1.4, server: , request: "GET /api/v1/rs-admin/notifications?page=0&size=1&state=READ HTTP/1.1", upstream: "http://10.11.5.82:9030/api/v1/rs-admin/notifications?page=0&size=1&state=READ\`

**Comment by ayushwebkul** [comment]
Hi @repeatedly  please checkout my issue here:- https://github.com/fluent/fluentd/issues/2998 and suggest me how I can use 2 regex for a single file as my file is producing 2 different types of logs pattern.

**Comment by ayushwebkul** [comment]
Hi @serut if you are still experiencing issue try to use the following regex for the patterns you mentioned:-
FOR 1st pattern 
-------------------------
(?<date>\d{4}\/\d{2}\/\d{2}) (?<time>[0-9:]+) (?<log_level>\[(.*?)\]) (?<message>[^,]*),(?<client>([^,]*)), (?<server>[^,]*), (?<request>request:[^,]+), (?<upstream>.+)

FOR 2nd Pattern 
--------------------------
(?<date>\d{4}\/\d{2}\/\d{2}) (?<time>[0-9:]+) (?<log_level>\[(.*?)\]) (?<message>[^,]*),(?<client>([^,]*)), (?<server>[^,]*), (?<request>request:[^,]+), (?<upstream>.+), (?<host& path>[^,]*)

**Comment by serut** [comment]
I'm not used to Fluentd config file, stops me if I'm wrong, but you can have several regex in the same parser right ? And Fluentd will stop on the first matching one or fail if none succeed ?

In that case you could add a regex matching 2020/05/04 17:01:22 [error] (<date> [error]), then collect everything after ?

**Comment by ayushwebkul** [comment]
yes you can do that too , the following regex will for both of your nginx patterns:-

(?<date>\d{4}\/\d{2}\/\d{2}) (?<time>[0-9:]+) (?<log_level>\[(.*?)\]) (?<message>.+)

**Comment by ayushwebkul** [comment]
or more specifically use this:-

(?<date>\d{4}\/\d{2}\/\d{2}) (?<time>[0-9:]+) (?<log_level>\[(.*?)\]) (?<message>.+)

**Comment by ayushwebkul** [comment]
or more specifically use this:-

(?<date>\d{4}\/\d{2}\/\d{2}) (?<time>[0-9:]+) (?<log_level>\[(.*?)\]) (?<messages>.+)

**Comment by ayushwebkul** [comment]
**(?<date>\d{4}\/\d{2}\/\d{2}) (?<time>[0-9:]+) (?<log_level>\[(.*?)\]) (?<message>.+)**

**Comment by ayushwebkul** [comment]
`(?<date>\d{4}\/\d{2}\/\d{2}) (?<time>[0-9:]+) (?<log_level>\[(.*?)\]) (?<message>.+)`

**Comment by ayushwebkul** [comment]
or more specifically use this regex:-

`**(?<date>\d{4}\/\d{2}\/\d{2}) (?<time>[0-9:]+) (?<log_level>\[(.*?)\]) (?<message>.+)**`

**Comment by ayushwebkul** [comment]
or more specifically use this regex:-

`(?<date>\d{4}\/\d{2}\/\d{2}) (?<time>[0-9:]+) (?<log_level>\[(.*?)\]) (?<message>.+)`

**Comment by serut** [comment]
@ayushwebkul I would prefer some edit on your comments, I appreciate your effort but it hard to read...

Something like that @repeatedly? I still think it should be provided by the official parser..
```
# Use NGINX parse for front logs
<label @PARSENGINX>
    <filter front>
        @type parser
        key_name message
        <parse>
            @type nginx
        </parse>
    </filter>
    <filter front>
        # Handle errors
        @type parser
        key_name message
        <parse>
            @type regexp
            expression /^(?<logtime>\d{4}\/\d{1,2}\/\d{1,2} \d{1,2}:\d{1,2}:\d{1,2}) (?<log_level>\[[^\s]+\]) (?<message>.*)$/
            time_key logtime
            time_format %Y/%m/%d %H:%M:%S
        </parse>
    </filter>
    <match **>
        @type copy
        <store>
            @type relabel
            @label @OUTPUT
        </store>
    </match>
</label>

```
