### ISSUE TITLE
Using 2 regex patterns for one Input file in Fluentd

### ISSUE THREAD

**Issue by ayushwebkul** [fluent/fluentd#2998]
Check [CONTRIBUTING guideline](https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md) first and here is the list to help us investigate the problem.

**Describe the bug**
I want to use 2 regex patterns for a single file, as my file is producing 2 different types of logs pattern. Please suggest me way to do it.

**To Reproduce**

**Expected behavior**

**Your Environment**

- Fluentd or td-agent version: `fluentd --version` or `td-agent --version`
- Operating system: `cat /etc/os-release`
- Kernel version: `uname -r`

If you hit the problem with older fluentd version, try latest version first.

**Your Configuration**
<source>
  @type tail
  pos_file /var/log/td-agent/magento-server2.pos
  format multiline
  format1 /(?<timestamp>\[(\d{4}+-\d{2}+-\d{2}+ \d{2}:\d{2}:\d{2})]) (?<@Log_level>[a-z]+.[A-Z:]+) (?<message>.+)/
  tag magento.debug
  time_format %Y-%m-%d %T,%L
  path /home/ayush/elastic-stack/log/debug.log
</source>

<source>
  @type tail
  pos_file /var/log/td-agent/magento-server2.pos
  format multiline
  format1 (?<timestamp>\[([0-9-]+ [0-9:]+)]) (?<@Log_level>[a-z]+.[A-Z:]+)(?<message_type>[^"]*)[^:]*:(?<method>[^"]*("[A-Z]+")),[^:]*:(?<URL>(http[s]?:\/\/)?([^\/\s]+\/)[^"]*)",(?<"message">"invalidateInfo":.+)
  tag magento.debug
  time_format %Y-%m-%d %T,%L
  path /home/ayush/elastic-stack/log/debug.log
</source>

```

**Your Error Log**

```

```

**Additional context**

<!-- Add any other context about the problem here. -->
I tried to create 2 different source inputs , but that doesn't work.

**Comment by repeatedly** [comment]
The author posted the question on proper mailing list. Closed.
