### ISSUE TITLE
Serious output delays with fine grained buffering

### ISSUE THREAD

**Issue by jiping-s** [fluent/fluentd#3005]
*Help and clarification needed, not necessarily a bug*

**Describe the bug**
We're experiencing delays in output (up to several days) and accumulation of buffers to Loki after introducing fine-grained buffering by unique labelset and timekey, to deal with Loki's restriction about out-of-order logs - all while the loading of fluentd and network traffic to Loki is minimal.

**To Reproduce**
There are no steps but the problem didn't appear until we have log input from a lot more servers. At any given time there are as many as 500 buffers open (within the timekey+delay duration) now. Note it's actually low input and output traffic, while there was no problem when we tested over 10K log lines per second previously, from a single source which should produce no more than 5 buffers (just different levels of logs, all sent to fluentd orderly).

**Expected behavior**
We expect fluentd to output the buffers continuously, but there are apparently long pauses between each sending / flushing of buffers, even when there are many buffers ready to be sent.

The problem seems to be here in `plugin/buffer.rb`:

```ruby
      def queue_full?
        synchronize { @queue.size } >= @queued_chunks_limit_size
      end
```

`@queued_chunks_limit_size` = count of flush threads, which in our case has to be set to one because if parallelized Lokit would reject out-of-order logs in the same labelset, without further modification to the Loki output plugin.

Because of this, in each run of flush thread's loop, only a single (up to count of flush threads) of staged / open buffers is queued for output and there is long pause between each run, in `plugin/output.rb`:

```ruby
      def enqueue_thread_run
        value_for_interval = nil
        if @flush_mode == :interval
          value_for_interval = @buffer_config.flush_interval
        end
        if @chunk_key_time
          if !value_for_interval || @buffer_config.timekey < value_for_interval
            value_for_interval = [@buffer_config.timekey, @buffer_config.timekey_wait].min
          end
        end
        unless value_for_interval
          raise "BUG: both of flush_interval and timekey are disabled"
        end
        interval = value_for_interval / 11.0
```

which means several seconds between each output flushing since the queue is always considered full, while each actual output takes only a fraction of one second.

**Your Environment**

- Fluentd or td-agent version: td-agent 1.7.4
- Operating system: CentOS Linux 7 (Core)
- Kernel version: 3.10.0-957.1.3.el7.x86_64

**Your Configuration**

```
<match logdump>
  @type copy
  <store>
    @type loki
    url https://......
    <buffer time, host, app, instance, source>
      @type file
      path /mnt/data/fluent/buffer/loki
      timekey 120
      timekey_wait 120
      chunk_limit_size 12mb
      total_limit_size 20gb
    </buffer>
    <label>
      host
      app
      type
      instance
      source
      level
      fluentd
    </label>
    line_format "key_value"
    drop_single_key true
    flush_at_shutdown true
  </store>
  ......
```

**Additional context**

Changing `queue_full` function to accept very high numbers of buffers such as 500 (depends on the timekey delay / expected time to output) in queue seems to work for us with minimal log traffic - mostly only logs from per-minute http test, which resulted in the reported problem before patching.

Are there some other configurations we could use instead? We have only two workers at the moment and just one flush thread (per worker it seems) due to the stated problem with Loki.

**Comment by repeatedly** [comment]
> Changing queue_full function to accept very high numbers of buffers such as 500 (depends on the timekey delay / expected time to output) in queue seems to work for us with minimal log traffic

`queued_chunks_limit_size` is configurable parameter: https://docs.fluentd.org/configuration/buffer-section#buffering-parameters
Why do you change this parameter?

**Comment by jiping-s** [comment]
I overlooked the parameter! Thanks a lot!
