### ISSUE TITLE
Option to ignore pattern not matched with custom parser plugin

### ISSUE THREAD

**Issue by andredxc** [fluent/fluentd#3011]
Check [CONTRIBUTING guideline](https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md) first and here is the list to help us investigate the problem.

**Is your feature request related to a problem? Please describe.**

I wrote a custom parser plugin which outputs a record with the data I want based on what is read from the in_tail source plugin. But, as this parser purposefully ignores the lines which are not in a certain format, I get a lot of log lines saying 

``` 2020-05-28 10:11:44 -0300 [warn]: #0 pattern not matched: "28/05/2020 10:11:43.760 : TFIXConnection.OnSocketDataAvailable : 3 : translate 446 : Discard 0" ```

when log level is set to warning or lower.

**Describe the solution you'd like**

I`d like an option not to print these lines so I can run the application in warning or lower log level without getting huge log files.

**Describe alternatives you've considered**

I\`ve tried an option inside the match tag (though I can`t remember or find what is was). The only way to avoid this problem has been to raise the log level to error, which makes it hard to investigate some connection issues.

Also tried to return nil or {} (empty hash) in the plugin`s parse function, but both have the same result.

**Additional context**

Config file used:

```
<source>
  @type tail
  path D:/log/EventLogs%Y%m%d/*

  pos_file C:/opt/td-agent/pos/positions_9
  pos_file_compaction_level 1h # Timeout to remove untracked positions
  open_on_every_update true    # Does not acquire lock for directory
  read_from_head false      
  enable_stat_watcher false    # Testing as a solution for hanging
  tag hadesLog
  <parse>
    @type hades
    time_format %d/%m/%Y %H:%M:%S.%L
    broker_id 9
  </parse>
</source>

# Ship data to the aggregator
<match hadesLog>
  @type forward

  send_timeout 20s
  recover_wait 20s
  hard_timeout 60s

  flush_interval 10s
  flush_at_shutdown true

  <server>
    host *********
    port 24224
  </server>
</match>

<system>
  log_level debug
</system>
```

**Comment by afarah1** [comment]
We're experiencing this issue with our plugin which parses the log for certain patterns and ignores everything else, is there any way to disable the warnings for lines with no matches? It's the intended behavior for us.

**Comment by andredxc** [comment]
An answer would have been nice, but we were able to figure out how to get rid of that log by removing the yield statement in the parse function when the line does not match our intended pattern instead of returning nil or an empty record.
