### ISSUE TITLE
td-agent latest version in amazon1 repo

### ISSUE THREAD

**Issue by shivshankarb** [fluent/fluentd#3013]
Check [CONTRIBUTING guideline](https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md) first and here is the list to help us investigate the problem.

**Is your feature request related to a problem? Please describe.**

I was looking for the solution for the "Logs flooded with warning message - Detected ES 7.x or above: _doc will be used as the document _type"
And come across with this fix uken/fluent-plugin-elasticsearch#589
Which seems to be fixed in td-agent version 3.4.2+

**Describe the solution you'd like**

We are using td-agent on some of our Amazon linux 1 machines as well to forward logs to AWS ES 7.2; However latest version of td-agent 3.4+ aren't included in the Amazon linux 1 repo.
https://td-agent-package-browser.herokuapp.com/3/amazon/1/2018.03/x86_64

Is it possible to add latest version (or atleast 3.5) to Amazon linux 1 repo?

**Describe alternatives you've considered**

**Additional context**

**Comment by repeatedly** [comment]
> Is it possible to add latest version (or atleast 3.5) to Amazon linux 1 repo?

We can't. We have already dropped amazon linux 1 support to focus on amazon linux 2.
You can avoid this problem by upgrading fluent-plugin-elasticsearch after installed td-agent.
