### ISSUE TITLE
Error reading SysLog logs

### ISSUE THREAD

**Issue by fuzeto** [fluent/fluentd#3017]
First I apologize if I'm opening this bug on the wrong way.
I read several posts and opened bugs here on github and still haven't found the solution.

**Describe the bug**
I'm capturing in Fluentd the logs sent via SysLog. That is being generated by NxFilter.
The massage is being broken as you can see below:
```
{"host":"nxfilter-xxx","ident":"{\"Prefix\"","message":"\"NXFILTER\",\"Time\":\"2020-05-29 19:30:43\",\"Blocked\":\"N\",\"Domain\":\"domain.com\",\"User\":\"username\",\"ClientIp\":\"0.0.0.0\",\"Policy\":\"Teste\",\"Category\":\"Download\",\"Reason\":\"\",\"Type\":1,\"Group\":\"test\"}"}
```

**To Reproduce**
Syslog config on NxFilter:
![syslog-config](https://user-images.githubusercontent.com/6377104/83446777-acea4180-a425-11ea-9298-16551d9a6327.png)

**Expected behavior**
The correct log message would be like this:
```
{"host":"nxfilter-xxx","ident": {"Prefix":"NXFILTER","Time":"2020-05-29 19:30:43","Blocked":"N","Domain":"domain.com","User":"username","ClientIp":"0.0.0.0","Policy":"Test","Category":"Download","Reason":"","Type":1,"Group":"test"}}
```

**Your Environment**
- Fluentd version: `fluent/fluentd:v1.10-debian-1`
- NxFilter version v4.3.6.5
- Kubernetes

**Your Configuration**
```
<source>
  @type syslog
  port 5140
  bind 0.0.0.0
  tag system
  <parse>
    @type syslog
  </parse>
</source>

<match system.**>
  @type copy
  <store>
    @type stdout
  </store>
</match>
```

**Your Error Log**
```
{"host":"nxfilter-xxx","ident":"{\"Prefix\"","message":"\"NXFILTER\",\"Time\":\"2020-05-29 19:30:43\",\"Blocked\":\"N\",\"Domain\":\"domain.com\",\"User\":\"username\",\"ClientIp\":\"0.0.0.0\",\"Policy\":\"Teste\",\"Category\":\"Download\",\"Reason\":\"\",\"Type\":1,\"Group\":\"test\"}"}
```

**Additional context**
I suppose NxFilter is using the RFC3164 pattern, because when I put some wrong or invalid parser, Fluentd returns the follow error:
```
#0 failed to parse message data="<14>Jun  2 11:08:52 nxfilter-77f69696c7-xkf2w {\"Prefix\":\"NXFILTER\",\"Time\":\"2020-06-02 11:08:52\",\"Blocked\":\"N\",\"Domain\":\"mmg-domain.net\",\"User\":\"username\",\"ClientIp\":\"0.0.0.0\",\"Policy\":\"Test\",\"Category\":\"Chat\",\"Reason\":\"\",\"Type\":1,\"Group\":\"test\"}"
```

Looking at this message you can see that the date format received is "%b %d %H:%M:%S".
First comes the date, then the message key, and third comes JSON with the log itself.
I've tried using RFC5424 pattern but the error still persists.

**Comment by fuzeto** [comment]
I just investigated the log that is captured by SysLog, that is, the format that fluentd will receive:
```
<14> Jun  2 16:13:15 nxfilter-master-65986f6f77-pz8cb {"Prefix":"NXFILTER","Time":"2020-06-02 16:13:15","Blocked":"N","Domain":"domain.com","User":"username","ClientIp":"0.0.0.0","Policy":"Test","Category":"Computer\/Technology","Reason":"","Type":1,"Group":"test"}
```

**Comment by repeatedly** [comment]
Built-in syslog parser doesn't support json parsing for message part because it is out scope of syslog protocol.
If you want json parsed content, you need additional task.

- write your parser for such specific message
- use json parser in parser filter or use record_modifier filter with enable_ruby to inplace update.

**Comment by fuzeto** [comment]
Thank you for the explanation. We changed the approach to reading the log from a UDP source. And then I used <parser> to get the relevant content from the log. It works for me!

Config:
```
<source>
    @type udp
    tag system
    port 5140
    bind 0.0.0.0
    <parse>
        @type regexp
        expression /^\<(?<pri>[0-9]+)\>(?<time>[^ ]* {1,2}[^ ]* [^ ]) (?<host>[^ ]) (?<message>.)$/
    </parse>
</source>

<filter system.**>
    @type parser
    key_name message
    hash_value_field log
    <parse>
        @type json
    </parse>
</filter>

<match system.**>
        @type stdout
</match>
```
