### ISSUE TITLE
Communication between two fluentd instances using http plugin fails with bad request

### ISSUE THREAD

**Issue by aliench0** [fluent/fluentd#3022]
**Describe the bug**
I have a problem with communication between fluentds using http_out and http_in plugins. I have two kubernetes clusters and I want the fluentd-A in the first cluster to send it's logs to the fluentd-B in the second cluster.
But when fluentd-A tries to send the logs it recieves:
```
#0 got unrecoverable error in primary and no secondary error_class=Fluent::UnrecoverableError error="400 Bad Request 400 Bad Request\n'json' or 'msgpack' parameter is required\n"
#0 bad chunk is moved to /tmp/fluent/backup/worker0/object_3ff8a73edae8/5a71a08ca19b1b343c8dce1b74c9a963.log
```

When I cat this file the logs in it has the following pattern:

    {log: ...., ... other json fields... }
    {log: ...., ... other json fields... }
    {log: ...., ... other json fields... }

I think the problem is that the concatenation of json objects is not a json and that is why fluentd-B sends as response 400 Bad Request but I thought that _content_type json_ will fix this because it sets the content type of the request to _application/x-ndjson_.

I have tested the fluentd-B with curl with the following requests and it works ok:

    curl -X POST -d '{"foo":"bar"}' -H 'Content-Type: application/json' http://<fluentd-B-ip>:9880/app.log
    curl -X POST -d 'json=[{"foo":"bar"},{"abc":"def"},{"xyz":"123"}]' http://<fluentd-B-ip>:9880/app.log

It this some bug or my configuration is not right, because I found only one example for the http_out plugin and maybe I am missing something...

**To Reproduce**
Deploy the two fluentd images on different clusters with the configuration below.
**Expected behavior**
Except the first fluentd to send its logs to the second fluentd using http plugin.

**Your Environment**

The fluentd-A image is: fluent/fluentd-kubernetes-daemonset:v1.10.3-debian-forward-1.0
Тhe fluentd-B image is: fluent/fluentd-kubernetes-daemonset:v1.10.3-debian-elasticsearch7-1.0

**Your Configuration**

```
This is the config of the fluentd-A:

    <match **>
      @type http
      content_type json
      endpoint http://<Fluentd-B-IP>:9880/api.log
      open_timeout 2
    </match>

    <match fluent.**>
      @type null
    </match>

    <source>
      @type tail
      @id in_tail_container_logs
      path /var/log/containers/*.log
      pos_file /var/log/fluentd-containers.log.pos
      tag "#{ENV['FLUENT_CONTAINER_TAIL_TAG'] || 'kubernetes.*'}"
      exclude_path "#{ENV['FLUENT_CONTAINER_TAIL_EXCLUDE_PATH'] || use_default}"
      read_from_head true
      <parse>
        @type "#{ENV['FLUENT_CONTAINER_TAIL_PARSER_TYPE'] || 'json'}"
        time_format %Y-%m-%dT%H:%M:%S.%NZ
      </parse>
    </source>

    <filter kubernetes.**>
      @type kubernetes_metadata
      @id filter_kube_metadata
      kubernetes_url "#{ENV['FLUENT_FILTER_KUBERNETES_URL'] || 'https://' + ENV.fetch('KUBERNETES_SERVICE_HOST') + ':' + ENV.fetch('KUBERNETES_SERVICE_PORT') + '/api'}"
      verify_ssl "#{ENV['KUBERNETES_VERIFY_SSL'] || true}"
      ca_file "#{ENV['KUBERNETES_CA_FILE']}"
    </filter>

    <filter kubernetes.**>
      @type grep
      <regexp>
        key $.kubernetes.namespace_name
        pattern /test/
      </regexp>
    </filter>


This is the config of the fluentd-B:


    # ... the other config for sending logs to elasticsearch is tested and ok, that's why I am skipping it.
    <source>
      @type http
      port 9880
      bind 0.0.0.0
      body_size_limit 32m
      keepalive_timeout 10s
      <parse>
        @type json
      </parse>

    </source>

```

**Your Error Log**

```
#0 got unrecoverable error in primary and no secondary error_class=Fluent::UnrecoverableError error="400 Bad Request 400 Bad Request\n'json' or 'msgpack' parameter is required\n"
#0 bad chunk is moved to /tmp/fluent/backup/worker0/object_3ff8a73edae8/5a71a08ca19b1b343c8dce1b74c9a963.log
```

**Additional context**

None.

**Comment by cosmo0920** [comment]
This is because _communicating with http in/out is not supported_.
Please use in/out forward to communicate between collector and aggregator Fluentds.

Or, sending http protocol is preferable for communicating in different k8s clusters?
Communicating in/out forward can handle k8s Service kind of Node port:
https://kubernetes.io/docs/concepts/services-networking/service/#nodeport

This is because in/out forward uses TCP protocol not HTTP.
So, when using in/out forward, Ingress is not usable for this purpose.

**Comment by aliench0** [comment]
Thank you for your answer. 
Is it possible to add this statement to the documentation? Because I think it's misleading in some way to have http_out and http_in but not to be able to use them together.

**Comment by cosmo0920** [comment]
> Is it possible to add this statement to the documentation? 

Hmm..., this should be added....

But, I'd found that the current implementation can handle out_http to in_http with masgpack format:
https://github.com/fluent/fluentd/issues/2909#issuecomment-604205451
https://github.com/fluent/fluentd/issues/2909#issuecomment-604370251

**Comment by ganmacs** [comment]
Have you checked `json_array` option?(I'm not sure it is mentioned in documents) 

https://github.com/fluent/fluentd/pull/2973

**Comment by cosmo0920** [comment]
Yep, using `json_array` is also able to communicate between two fluentd via HTTP:

##### in_http.conf

```aconf
<source>
  @type http
  port 9881
  bind 0.0.0.0
  <parse>
    @type json
  </parse>
</source>
<match **>
  @type stdout
</match>
```

##### out_http.conf

```aconf
<source>
  @type forward
</source>
<match **>
  @type http
  endpoint http://127.0.0.1:9881/http
  <format>
    @type json
  </format>
  json_array true
  <buffer>
    flush_interval 2s
  </buffer>
</match>
```

##### results

```
% echo '{"elmo":"3years old", "abby":"a fairy","message":"On the youtube!"}' | bundle exec fluent-cat json_array.testing  
```

###### in_http node

```
2020-06-09 14:52:54.944603000 +0900 http: {"elmo":"3years old","abby":"a fairy","message":"On the youtube!"}
```

**Comment by cosmo0920** [comment]
This should be documented in https://github.com/fluent/fluentd-docs-gitbook/pull/184.
Closing.
