### ISSUE TITLE
Elasticsearch dns incorrectly resolved

### ISSUE THREAD

**Issue by antoinep92** [fluent/fluentd#3032]
Check [CONTRIBUTING guideline](https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md) first and here is the list to help us investigate the problem.

**Describe the bug**
Elasticsearch hostname resolution fails silently and wrongly resolved to localhost if there is an issue with `/etc/hosts`

**To Reproduce**
Configure an "elasticsearch" entry in `/etc/hosts` to something other than `127.0.0.1` and `chmod +x /etc/hosts` (a bug in a deployment script did that for us)
When running flutend with `host elasticsearch` in `/etc/fluentd.conf` this error is repeated:

    could not push logs to Elasticsearch cluster ({:host=>\"elasticsearch\", :port=>9200, :scheme=>\"http\"}): Connection refused - connect(2) for 127.0.0.1:9200 (Errno::ECONNREFUSED)

Note that the executable flag did not affect other services or the OS resolution, e.g. `getent hosts elasticsearch` returned the configured IP. Removing the executable flag on `/etc/hosts` or hardcoding the IP in `/etc/fluentd.conf` solves the problem, but the error is misleading so I though I'd report that.

**Expected behavior**
I expect the hostname to either be correctly resolved, or fail with an error like: `Failed to resolve IP for the configured elasticsearch hostname: "elasticsearch"`. Resolving it to localhost instead is misleading.

**Your Environment**

- Fluentd or td-agent version: `fluentd --version` or `td-agent --version`
1.10.4
- Operating system: `cat /etc/os-release`
Arch Linux
- Kernel version: `uname -r`
5.6.15-arch1-1

**Comment by repeatedly** [comment]
This seems fluent-plugin-elasticsearch issue.
