### ISSUE TITLE
http_in does not log internal server error details

### ISSUE THREAD

**Issue by dobesv** [fluent/fluentd#3035]
**Describe the bug**

We currently are seeing in the HTTP statistics a fair number of 500 responses coming back from the fluentd http input.  This indicates that some exception was thrown in the process of queueing the log entry.  However, the error is not logged to the server logs, so we have to figure out what the user(s) are doing to cause it.

**To Reproduce**

Just for example:

```
curl 'https://fluentd-hostname/web' \
  -H 'content-type: application/x-www-form-urlencoded' \
  -H 'accept: */*' \
  -H 'accept-language: en-GB,en-US;q=0.9,en;q=0.8' \
  --data-raw 'json=%5B%7B%22anonymousId%22%3A%225eb1b213517fe50000ea9b52%22%2C%22name%22%3A%22formative%22%2C%22level%22%3A40%2C%22levelName%22%3A%22warn%22%2C%22msg%22%3A%22test%22%2C%22time%22%3A%222020-06-10T17%3A30%3A29.802Z%22%2C%22timestamp%22%3A%222020-06-10T17%3A30%3A29.804Z%22%7D%5D'
```

This causes an internal server error parsing the "time" field.  The error message is returned to the client but not logger in the server logs.

**Expected behavior**

I think internal server errors like this should be logged in the server logs since "Internal Server Error" generally indicates a programmer or configuration error, reporting this to the end user is not useful.

**Your Environment**

fluentd (1.11.0) running in kubernetes using the docker debian image.

**Comment by repeatedly** [comment]
Patch: https://github.com/fluent/fluentd/pull/3039
