### ISSUE TITLE
Allow not - match - pattern

### ISSUE THREAD

**Issue by ferbar** [fluent/fluentd#3057]
**Is your feature request related to a problem? Please describe.**
I'm having several input plugins, for example tags aaa.* bbb.* ccc.* etc
I would like to apply record_modifier to everything but aaa.*

**Describe the solution you'd like**

```
<filter /(?!aaa).*/ >
   @type record_modifier
   ....
```

== or ==

```
<filter !aaa.**>
   @type record_modifier
   ....
```

**Describe alternatives you've considered**

explicitly filter for bbb.** ccc.** etc

**Additional context**
(?!aaa) doesn't work at the moment because every non-word character is escaped in 
https://github.com/fluent/fluentd/blob/master/lib/fluent/match.rb#L113

I see 3 possible, easy to implement solutions:
1. allow regex with a / prefix, string must end with /
`<filter /some-regex/>
`
2. don't escape "(?!" and the corresponding ")"

3. allow pattern like
!aaa.**

and create a regex (?!aaa).* from it

**Comment by ferbar** [comment]
A patch for the /regex/ variant

```
--- lib/ruby/gems/2.4.0/gems/fluentd-1.7.4/lib/fluent/match.rb.org      2020-06-25 12:54:51.804997090 +0200
+++ lib/ruby/gems/2.4.0/gems/fluentd-1.7.4/lib/fluent/match.rb  2020-06-25 13:05:50.757008340 +0200
@@ -33,6 +33,15 @@

   class GlobMatchPattern < MatchPattern
     def initialize(pat)
+      if pat[0,1] == "/"
+        if pat[pat.length - 1,1] == "/"
+          @regex = Regexp.new("\\A"+pat[1, pat.length-2]+"\\Z")
+          return
+        else
+          throw "invalid regex"
+        end
+      end
+
       stack = []
       regex = ['']
       escape = false
```

**Comment by repeatedly** [comment]
Looks good for me. Could you send a patch?
