### ISSUE TITLE
filter, record_assessor, grep 

### ISSUE THREAD

**Issue by scvRdy** [fluent/fluentd#3060]
Check [CONTRIBUTING guideline](https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md) first and here is the list to help us investigate the problem.

**Describe the bug**
I've read through the documentation and am unable to find an example.

is there something wrong with this syntax?
```<filter **>
@type grep
  <regexp>
     key category
     pattern /\bAUDIT\b/
</regexp>
<regexp>
    key $.details.description
   pattern /\bAuthentication activity\b/
</regexp>
</filter>
```
The second regexp, seems to have no effect.

**To Reproduce**

**Expected behavior**

**Your Environment**

- Fluentd or td-agent version: `fluentd --version` or `td-agent --version`
- Operating system: `cat /etc/os-release`
- Kernel version: `uname -r`

If you hit the problem with older fluentd version, try latest version first.

**Your Configuration**

```
<!-- Write your configuration here -->
```

**Your Error Log**

```
<!-- Write your **ALL** error log here -->
```

**Additional context**

**Comment by repeatedly** [comment]
Please write reproduce step.
