### ISSUE TITLE
Fluentd in_tail unexpected format_firstline regex behavior

### ISSUE THREAD

**Issue by shamsalmon** [fluent/fluentd#3061]
Check [CONTRIBUTING guideline](https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md) first and here is the list to help us investigate the problem.

**Describe the bug**
I am running fluentd on windows. When I use the following format_firstline format it fails to detect the first line for a file that starts like the following:
```
ProgramName
Data
Data
Data
```

Format:
```
<source>
  @type tail
  <parse>
     @type multiline
	 format_firstline /^ProgramName$/
```

It does work if I specify the literal return and new line characters:
```
<source>
  @type tail
  <parse>
     @type multiline
	 format_firstline /^ProgramName\r\n/
```

**To Reproduce**
Create a file with the above format. Try to parse with both the first example format_firstline and second. It will fail if you try to use the end of line character.

**Expected behavior**
I expect the following parser to be able to detect when the line is ending:
```
<source>
  @type tail
  <parse>
     @type multiline
	 format_firstline /^ProgramName$/
```

Windows Server 2016
fluentd 1.10.2

- Fluentd or td-agent version: `fluentd --version` or `td-agent --version`
- Operating system: `cat /etc/os-release`
- Kernel version: `uname -r`

If you hit the problem with older fluentd version, try latest version first.

**Your Configuration**

Posted above

**Your Error Log**
```
 {"message":"got incomplete line before first line from D:/x/LO_LOG_FILES/BATCHLOG/x_INBOUND_20200627_171106.log: \"ProgramName\\r\\n\""}
```

**Comment by kenhys** [comment]
@shamsalmon 
As you mentioned, `format_firstline /^ProgramName\r\n/` works. 

ref. https://docs.ruby-lang.org/en/2.7.0/Regexp.html#class-Regexp-label-Anchors
`$ - Matches end of line`, not for carrige return or newline. so it worked as you described.
If you want not to care about  `\r\n` or `\n`, `/^ProgramName\p{Space}$/` will work as you like.

**Comment by kenhys** [comment]
@shamsalmon I'll close this issue after a while.

**Comment by shamsalmon** [comment]
Thanks. I will close.
