### ISSUE TITLE
Fields not getting added

### ISSUE THREAD

**Issue by biskit** [fluent/fluentd#3069]
Check [CONTRIBUTING guideline](https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md) first and here is the list to help us investigate the problem.

**Describe the bug**

Fields not getting added

**To Reproduce**

I want to add a few fields to `syslog` that is not parsed and ship it out.
Use the config below to reproduce:

Here's my config
```
<source>
 @type syslog
 <parse>
   @type none
 </parse>
 tag syslog
</source>
<filter syslog>
  @type record_transformer
  <record>
    type "syslog"
    hostname "#{Socket.gethostname}"
  </record>
</filter>
<match **>
  @type stdout
</match>
```

This writes logs without adding tags
`2020-07-09 04:54:22.687445444 +0000 syslog.daemon.info: {"message":"Jul  9 04:54:22 ub182 ntpd[2914]: Soliciting pool server 91.189.94.4"}`

**Expected behavior**

i expected to see `"hostname":"foo"`, `"type":"syslog"` along with `message`.

**Your Environment**

- Fluentd or td-agent version: `fluentd --version` or `td-agent --version`
td-agent 1.11.1
- Operating system: `cat /etc/os-release`
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

- Kernel version: `uname -r`
4.15.0-106-generic

If you hit the problem with older fluentd version, try latest version first.

**Comment by repeatedly** [comment]
syslog plugin adds facility and priority to tag.
See official article: https://docs.fluentd.org/input/syslog#example-usage

So use `<filter syslog.**>` resolve the problem.

**Comment by biskit** [comment]
I don't want syslog line getting parsed. I was expecting something like
`2020-07-09 04:54:22.687445444 +0000 syslog.daemon.info: {"message":"Jul 9 04:54:22 ub182 ntpd[2914]: Soliciting pool server 91.189.94.4"} {"hostname":"foo"}, {"type":"syslog"}`

is it possible?
