### ISSUE TITLE
Elasticsearch 7.X - Deprecated "types" in document.

### ISSUE THREAD

**Issue by DandyDeveloper** [fluent/fluentd#3073]
**Describe the bug**
Deprecated types is present in documents managed by latest fluentd version (Possibly the fluentd_elasticsearch plugin):

Same issue described here in fluentbit: https://github.com/fluent/fluent-bit/issues/1359

**To Reproduce**
Forward a document via  the `elasticsearch` output plugin on any 7.X instance. 

**Expected behavior**
No warning messages from Elasticsearch

**Your Environment**
- Fluentd image: fluent/fluentd:v1.11-1
- Plugin via gem install: https://github.com/uken/fluent-plugin-elasticsearch

**Your Error Log**

```
warning: 299 Elasticsearch-7.8.0-757314695644ea9a1dc2fecd26d1a43856725e65 "[types removal] Specifying types in bulk requests is deprecated."
warning: 299 Elasticsearch-7.8.0-757314695644ea9a1dc2fecd26d1a43856725e65 "[types removal] Specifying types in bulk requests is deprecated."
warning: 299 Elasticsearch-7.8.0-757314695644ea9a1dc2fecd26d1a43856725e65 "[types removal] Specifying types in bulk requests is deprecated."
```

**Comment by repeatedly** [comment]
This seems fluent-plugin-elasticsearch issue, not fluentd core.
