### ISSUE TITLE
Missing logs in Cloudwatch with fluend-cloudwatch

### ISSUE THREAD

**Issue by saurabh1git** [fluent/fluentd#3077]
Check [CONTRIBUTING guideline](https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md) first and here is the list to help us investigate the problem.

**Describe the bug**
Missing logs in Cloudwatch with fluend-cloudwatch

**To Reproduce**
Usecase is batch processing. We are putting 5K messages in SQS, which are polled by 6 containers in the backend. 

**Expected behavior**
log messages for all 5K messages should show up in Cloudwatch 

**Your Environment**

- Fluentd or td-agent version: `fluentd --version` or `td-agent --version`
we are using fluentd-cloudwatch 0.13 helm chart
- Operating system: `cat /etc/os-release`
Ubuntu
- Kernel version: `uname -r`
Linux ip-10-25-23-151 4.4.0-1074-aws fluent/fluentd#84-Ubuntu SMP Thu Dec 6 08:57:58 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

If you hit the problem with older fluentd version, try latest version first.
yeah, using latest version of fluentd
**Your Configuration**
```aconf
<match **>
      @type cloudwatch_logs
      log_group_name "#{ENV['LOG_GROUP_NAME']}"
      auto_create_stream true
      use_tag_as_stream true
      json_handler yajl
      @log_level debug
      <buffer>
          chunk_limit_size 8m
          queued_chunks_limit_size 256
          flush_thread_count 5
          flush_mode interval
          retry_max_times 20
          retry_wait 10s
          retry_max_interval 10s
          overflow_action block
          retry_forever true
      </buffer>
      retention_in_days 90
    </match>
```

**Your Error Log**
```
98008308054649844779807053269166973026514" thread=70008146723580 request_sec=0.030821989
2020-07-16 09:54:08 +0000 [debug]: #0 taking back chunk for errors. chunk="5aa8c0178a5db007ed70c78071be9dba"
2020-07-16 09:54:08 +0000 [warn]: #0 failed to flush the buffer. retry_time=0 next_retry_seconds=2020-07-16 09:54:18 +0000 chunk="5aa8c0178a5db007ed70c78071be9dba" error_class=**Aws::CloudWatchLogs::Errors::ThrottlingException error="Rate exceeded"**
```

**Additional context**

AWS recommends to use exponential retry. Is this something thats supported in Fluentd

**Comment by repeatedly** [comment]
This issue is unclear for me.

> AWS recommends to use exponential retry. Is this something thats supported in Fluentd

Yes. Fluentd's retry mechanism uses exponential backoff by default.
Your error log says fluentd will retry buffer flush > `failed to flush the buffer. retry_time=0 next_retry_seconds=2020-07-16 09:54:18 +0000 chunk="5aa8c0178a5db007ed70c78071be9dba" error_class=**Aws::CloudWatchLogs::Errors::ThrottlingException error="Rate exceeded"**`
