### ISSUE TITLE
in_tail performance difference between 1.7.4 & 1.11.1

### ISSUE THREAD

**Issue by jcantrill** [fluent/fluentd#3078]
Check [CONTRIBUTING guideline](https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md) first and here is the list to help us investigate the problem.

**Describe the bug**
We have a scalability test that using 1.7.4  is able to consistently pass with no message loss at 2500m/s when running in a kubernetes environment using a single container to generate the load.  Bumping to fluent 1.11.1 consistently demonstrates message loss of anywhere between 5 and 25%.

Varying the following various parameters using 1.11.1 do not seem to make any difference: rotate_wait, refresh_interval.

The largest changes I can see in commit history in this area look to be refactoring work around the position file maintenance.  Also, pegging the version of cool.io to an earlier version doesn't seem to make any difference either.

**To Reproduce**
We have an internal test suite that spins up an openshift cluster and:
* starts log generator producing 2500 m/s (1k) for a total of 1,125,000 lines
* container runtime rotates the log generator files periodically during the run

**Expected behavior**
* Consistent log collection between the different versions 

**Your Environment**

- Fluentd or td-agent version: `fluentd --version` or `td-agent --version`
- Operating system: `cat /etc/os-release`
- Kernel version: `uname -r`

If you hit the problem with older fluentd version, try latest version first.

**Your Configuration**

```
    <source>
      @type tail
      @id container-input
      path "/var/log/containers/*.log"
      exclude_path ["/var/log/containers/*-*_openshift*_*.log", "/var/log/containers/*-*_kube*_*.log", "/var/log/containers/*-*_default_*.log"]
      pos_file "/var/log/es-containers.log.pos"
      refresh_interval 1
      rotate_wait 300
      tag kubernetes.*
      read_from_head "true"
      @label @CONCAT
      <parse>
        @type multi_format
        <pattern>
          format json
          time_format '%Y-%m-%dT%H:%M:%S.%N%Z'
          keep_time_key true
        </pattern>
        <pattern>
          format regexp
          expression /^(?<time>.+) (?<stream>stdout|stderr)( (?<logtag>.))? (?<log>.*)$/
          time_format '%Y-%m-%dT%H:%M:%S.%N%:z'
          keep_time_key true
        </pattern>
      </parse>
    </source>

```

**Comment by repeatedly** [comment]
I'm now checking this issue by writing test script.

**Comment by repeatedly** [comment]
I tested following script but no data lost. Could you explain the details of log generation, e.g. the number of files, how to rotate and more?

- test script: 2000 - 3000 msg/s

```
require 'parallel'
require 'logger'

msg = "Hello from fluentd for test! 1234567890 sample data true baz\n"

def wait(time)
  start_time = Time.now
  yield
  sleep_time = time - (Time.now - start_time)
  sleep sleep_time if sleep_time > 0
end

Parallel.each(1..3) { |i|
  begin
    f = Logger.new("a#{i}.log", 10000, 2048576)
    while true
      current_time = Time.now.to_i
      10.times do
        break unless (Time.now.to_i <= current_time)
        wait(0.1) {
          350.times {
            f << msg
          }
        }
      end
      while (Time.now.to_i <= current_time)
        sleep 0.01
      end
    end
  ensure
    f.close rescue nil
  end
}

```

- config

```
<source>
  @type tail
  @id container-input
  path "/Users/repeatedly/tmp/fluentd/i3078/a*.log"
  pos_file "/Users/repeatedly/tmp/fluentd/i3078/es-containers.log.pos"
  refresh_interval 1
  rotate_wait 300
  tag test.*
  read_from_head true
  <parse>
    @type none
  </parse>
</source>

<match test.**>
  @type file
  path "/Users/repeatedly/tmp/fluentd/i3078/result/test.bin"
  append true
  <format>
    @type single_value
  </format>
  <buffer>
    flush_at_shutdown true
  </buffer>
</match>

```

- result

```
# generated logs
% wc -l a*
...
 2768213 total

# the number of logs in buffer
% wc -l result/test.bin/buffer.b5aaf59bc26513b156f05afa02f9f485a.log
 2768213 result/test.bin/buffer.b5aaf59bc26513b156f05afa02f9f485a.log
```

**Comment by jcantrill** [comment]
> I tested following script but no data lost. Could you explain the details of log generation, e.g. the number of files, how to rotate and more?

I am working to narrow down the bits which specifically effect what I'm seeing.  We run in a containerized OpenShift environment and are scraping container logs.  These logs are rotated by the container runtime which I don't have the specifics.  The specific test in question only tails on log generator container.  I'll see what I can do to provide more specifics

**Comment by jcantrill** [comment]
I started to try and write some code [1] to mimic containerd behavior on kubernetes to generate logs and rotate them but was not able to fully replicate the issue I was seeing.  Possible issues may be related to running these tests on AWS where throttling and quota are outside of our control.

Closing the issue for now.

[1] https://gist.github.com/jcantrill/8c3d72048f74c9ac4dcef2a8b07c3583
