### ISSUE TITLE
[WIP] Idea notes for next generation Buffer/Input/Output plugins

### ISSUE THREAD

**Issue by tagomoris** [fluent/fluentd#309]
Related with #287

**Comment by tagomoris** [comment]
`buffer_dir_path` instead of `buffer_path`, to manage specified directory exclusively against other plugin instance. All files in specified directory are to be flushed by specifying plugin instance.

* That is useful for fluent-plugin-forest to flush all buffer files at startup
* `buffer_path` has priority than `buffer_dir_path`.

**Comment by tagomoris** [comment]
New configuration parameter set for buffer plugins:

* buffer_space_limit (buffer plugin)
  * to specify total size of buffer chunks (`== buffer_chunk_limit * buffer_queue_limit`)
  * to replace specifying buffer_queue_limit with this parameter to show disk/memory usage explicitly
* `<buffer>` section to specify parameters of buffer plugins (output plugin)
  * by using `config_section`

**Comment by tagomoris** [comment]
Fluent::PluginSupport::* mixin modules instead of Actor
* Fluent::PluginSupport::Thread
* Fluent::PluginSupport::ChildProcess (for exec_filter and others)
* Fluent::PluginSupport::Timer
* Fluent::PluginSupport::Socket (provides listener, tcpsocket(?), sslsocket(?))

**Comment by tagomoris** [comment]
Common API to generate paths with timestamp placeholders like `%Y`, `%m` and `%d`.
Related:
 * buffer chunk id
 * time slice key generation

**Comment by tagomoris** [comment]
Benchmark plugins:
 * [in/out] forward(w/, w/o SSL)
 * [in/out] scribe
 * [out] td, bigquery, s3, mongo, file, exec
 * [in] exec, http, syslog, unix
 * [filter] exec, grep, record_transformer

**Comment by tagomoris** [comment]
Simple datastore for plugin instances & plugin types, to store on-memory data at shutdown (and to resume it at startup).
* Serialization format? (msgpack or json?)
* Datastore? (plain text file, sqlite or pluggable?)

My idea:
 * format: JSON for human readability
 * datastore: Pluggable datastore, but plain text file only at first

**Comment by tagomoris** [comment]
v11 actors: async_actor, background_actor, io_actor, socket_actor, timer_actor

Notes:
* async and background are actually same? (run once or many times)
* socket actor should be separated into tcp, udp and unix socket utils.
* file io actor is needed? it seems to be required only by out_file

**Comment by tagomoris** [comment]
API & configuration param to flush records in buffers ASAP.

**Comment by repeatedly** [comment]
Supporting pluggable compression.
Currently, we have own compression mechanizm in each plugin.
This is not good for plugin ecosystem.

FYI, s3 example: https://github.com/fluent/fluent-plugin-s3#use-your-compression-algorithm

**Comment by tagomoris** [comment]
Idea for compression:
* `CompressedBuffer` super class as base class to support compression
* `GzipBuffer < CompressedBuffer` in built-in class
* new Buffer API should have hook point to execute compression for specified size

And forward protocol should be extended:
* add a new flag to `opts` to specify compressed buffers and its algorithm
* Only MessagePackEventStream should be supported with compression flag

**Comment by tagomoris** [comment]
Plugin lifecycle with v0.12 APIs:
1. initialize
2. configure
3. start
4. shutdown

Plugin lifecycle with v0.14 APIs:
1. initialize
2. configure
3. start
4. stop (used by plugin supports in normal)
5. shutdown

`stop` is used to:
* tell input plugins not to emit any more records
* mark all sockets to close ASAP
* mark all threads to stop ASAP (break from while loop, etc)
* mark all buffers to be flushed ASAP

`shutdown` is used to:
* close all listening sockets unless closed
* flush all buffers if not flushed yet
* join & kill all threads

@repeatedly @sonots How do you think about this idea?

**Comment by tagomoris** [comment]
I rethink that 3 steps should exists in shutdown sequence.

**Comment by tagomoris** [comment]
@kiyoto Do you have any good word for `(TBD)` above?

**Comment by tagomoris** [comment]
I fixed plugin shutdown sequence with 5 steps!
@repeatedly @sonots could you review it?

**Comment by tagomoris** [comment]
Predefined buffer format
* To create common format between many kind of plugins

**Comment by tagomoris** [comment]
New buffer plugin `buf_x` to:
* store data in memory under situation without output errors
* store data in file under situation with output errors

**Comment by tagomoris** [comment]
This issue is already outdated.
