### ISSUE TITLE
parse reg-expression for nginx logs

### ISSUE THREAD

**Issue by farooqdevops** [fluent/fluentd#3099]
**Describe the bug**
i am using fluentd to send logs to elastic-search. While using regexpression in parser, i get following error:
`config error file="/fluentd/etc/fluent.conf" error_class=Fluent::ConfigError error="'@type' parameter is required, in section parse`

**Your Environment**

- fluent/fluentd-kubernetes-daemonset:v1.10.3-debian-cloudwatch-1.0

**Your Configuration**
`<source>
      @type tail
      @id in_tail_nginx_container_logs
      @label @nginx_containers
      path /var/log/containers/nginx*.log
      pos_file /var/log/nginx-containers.log.pos
      tag *
      read_from_head true
      <parse>
        @type json
      </parse>
    </source>

<label @nginx_containers>
      <filter **>
        @type parser
        key_name log
        <parse>
          expression /^(?<remote>[^ ]*) (?<host>[^ ]*) (?<user>[^ ]*) \[(?<time>[^\]]*)\] "(?<method>\S+)(?: +(?<path>[^\"]*?)(?: +\S*)?)?" (?<code>[^ ]*) (?<size>[^ ]*)(?: "(?<referer>[^\"]*)" "(?<agent>[^\"]*)?)?"$/
          time_format %d/%b/%Y:%H:%M:%S %z
        </parse>
      </filter>
    </label>

`
```

**Your Error Log**

```
config error file="/fluentd/etc/fluent.conf" error_class=Fluent::ConfigError error="'@type' parameter is required, in section parse
```

**Additional context**

Kibana logs pattern: 192.168.10.250 - - [04/Aug/2020:20:41:09 +0000] "GET / HTTP/1.1" 404 872 "-" "Mozilla/5.0"

I tested the above regexp
`expression /^(?<remote>[^ ]*) (?<host>[^ ]*) (?<user>[^ ]*) \[(?<time>[^\]]*)\] "(?<method>\S+)(?: +(?<path>[^\"]*?)(?: +\S*)?)?" (?<code>[^ ]*) (?<size>[^ ]*)(?: "(?<referer>[^\"]*)" "(?<agent>[^\"]*)?)?"$/`
 from https://regex101.com/ and it matches correctly with above log pattern. However i see the json format of logs like this (having "\n at the end). "log":"192.168.10.250 - - [04/Aug/2020:20:41:09 +0000] \"GET / HTTP/1.1\" 404 872 \"-\" \"Mozilla/5.0 \"\n"

Can someone have a look into this where i am getting this wrong? Thanks

**Comment by repeatedly** [comment]
Need `@type regexp`. See error log first.

https://docs.fluentd.org/filter/parser#example-configurations

**Comment by farooqdevops** [comment]
Thanks @repeatedly . I am able to parse nginx logs correctly. but when i want geoip filter to use that parser field "remote". There's no error but  i also don't get any geoip records in kibana.

My fluentd config looks like this:
`<label @nginx_containers>
      <filter **>
        @type parser
        key_name log
        <parse>
          @type nginx
        </parse>
      </filter>

      <filter **>
        @type geoip

       # Specify one or more geoip lookup field which has ip address (default: host)
       geoip_lookup_keys  remote

       # Specify optional geoip database (using bundled GeoLiteCity databse by default)
       # geoip_database    "/path/to/your/GeoIPCity.dat"
       # Specify optional geoip2 database (using bundled GeoLite2 database by default)
       # geoip2_database   "/path/to/your/GeoLite2-City.mmdb"
       # Specify backend library (geoip2_c, geoip, geoip2_compat)
       backend_library geoip2_c

       # Set adding field with placeholder (more than one settings are required.)
        <record>
          city            ${city.names.en["remote"]}
          latitude        ${location.latitude["remote"]}
          longitude       ${location.longitude["remote"]}
          country         ${country.iso_code["remote"]}
          country_name    ${country.names.en["remote"]}
          postal_code     ${postal.code["remote"]}
          region_code     ${subdivisions.0.iso_code["remote"]}
          region_name     ${subdivisions.0.names.en["remote"]}
        </record>

        # To avoid get stacktrace error with `[null, null]` array for elasticsearch.
        skip_adding_null_record  true
      </filter>

      <filter **>
        @type kubernetes_metadata
      </filter>

      <filter **>
        @type record_transformer
        <record>
          stream_name ${tag_parts[3]}
        </record>
        remove_keys $.kubernetes.pod_id, $.kubernetes.master_url, $.kubernetes.container_image_id, $.kubernetes.namespace_id
      </filter>

      <match **>
        @type stdout
        @type relabel
        @label @NORMAL
      </match>
    </label>`

and kibana logs look like this:

`"remote":"10.0.0.1","host":"-","user":"-","method":"GET","path":"/","code":"404","size":"872","referer":"-","agent":"Mozilla/5.0"`
