### ISSUE TITLE
How to run TCP server (daemon) correctly through in_exec?

### ISSUE THREAD

**Issue by pikhovkin** [fluent/fluentd#3106]
**Describe the bug**
How to run TCP server (daemon) correctly through in_exec?
I started TCP server and write in stdout but fluentd do not output data from stdout's TCP server.

**To Reproduce**

**Expected behavior**

**Your Environment**

- Fluentd or td-agent version: `fluentd --version` or `td-agent --version`

      fluentd 1.11.1

- Operating system: `cat /etc/os-release`

      PRETTY_NAME="Debian GNU/Linux 10 (buster)"
      NAME="Debian GNU/Linux"
      VERSION_ID="10"
      VERSION="10 (buster)"
      VERSION_CODENAME=buster
      ID=debian
      HOME_URL="https://www.debian.org/"
      SUPPORT_URL="https://www.debian.org/support"
      BUG_REPORT_URL="https://bugs.debian.org/"

- Kernel version: `uname -r`

      5.4.0-42-generic

**Your Configuration**

```
<source>
  @type exec
  command python tcp_server.py
  <parse>
    @type json
  </parse>
  tag mytag
</source>

<match mytag>
  @type stdout
</match>
```

**Your Error Log**

```
in fluentd's log no errors
```

**Additional context**

**Comment by repeatedly** [comment]
I tested ruby based tcp echo server and it works.

```
require "socket"

gs = TCPServer.open(23000)
addr = gs.addr
addr.shift
STDOUT.printf("server is on %s\n", addr.join(":"))

while true
  Thread.start(gs.accept) do |s|
    STDOUT.print(s, " is accepted\n")
    while msg = s.gets
      s.write(msg)
    end
    STDOUT.print(s, " is gone\n")
    STDOUT.flush
    s.close
  end
end
```

```
<source>
  @type exec
  command ruby tcp_server.rb
  <parse>
    @type none
  </parse>
  tag mytag
</source>

<match mytag>
  @type stdout
</match>
```

```
# test command
echo 'hello' | nc 127.0.0.1 23000

# log
2020-08-13 14:13:57 +0900 [info]: #0 fluentd worker is now running worker=0
2020-08-13 14:14:01.206193000 +0900 mytag: {"message":"server is on 23000::::::"}
2020-08-13 14:14:01.206670000 +0900 mytag: {"message":"#<TCPSocket:0x00007ff27b86cea8> is accepted"}
2020-08-13 14:14:01.206747000 +0900 mytag: {"message":"#<TCPSocket:0x00007ff27b86cea8> is gone"}
```

I assume your TCP server is something wrong for output message or default configuration is not fit for your log output, e.g. https://docs.fluentd.org/parser/json#stream_buffer_size

**Comment by pikhovkin** [comment]
Thank you! The problem was in section  
```
<parse>
  @type json
</parse>
```
I changed it with
```
<parse>
  @type none
</parse>
```
and it started working
