### ISSUE TITLE
Possible to flush buffer when tailed file is deleted? 

### ISSUE THREAD

**Issue by ninja-** [fluent/fluentd#3116]
Check [CONTRIBUTING guideline](https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md) first and here is the list to help us investigate the problem.

**Is your feature request related to a problem? Please describe.**

I am looking to design a small tool for accessing our cluster logs based on one principle: either we access live container logs if container is alive or fetch the log files from S3 if it's dead and Kubernetes deleted the container.
I already configured fluentd to create S3 files per container, and buffer per hour.
Would it be possible to force fluentd to flush the buffer when detecting that tailed file has been removed in addition to per-hour flushing?

**Describe the solution you'd like**

An option to flush the buffer when tailed file is deleted.

**Describe alternatives you've considered**

.
**Additional context**

.

**Comment by repeatedly** [comment]
Currently, no way.
in_tail uses timer with file listing, so the time lag happens for file delete detection.
I'm not familiar with entire k8s APIs. If you can hook the event for container delete, use it and send it signal is better for now.

**Comment by ninja-** [comment]
@repeatedly it would flush all files at once then which could create cpu spikes :/

**Comment by repeatedly** [comment]
fluentd handles data as a stream and output buffer doesn't know the data origin.
So in_tail can't flush only one buffer file for per tailing file.
