### ISSUE TITLE
Support Windows container FluentD querying Windows event logs

### ISSUE THREAD

**Issue by inosvaruag** [fluent/fluentd#3117]
**Is your feature request related to a problem? Please describe.**

FluentD currently only runs as a service or local process. It cannot be used as a container on Windows and get the underlying VM's event logs. File logs can be captured using mounts.

**Describe the solution you'd like**

Allow FluentD to accept credentials and login to the underlying host for getting access to event logs. Remote event log access, WMI Remoting, Powershell remoting, CIM sessions, etc. could be used for establishing this connection.

**Describe alternatives you've considered**

There is no way of running FluentD to get underlying VM's event logs from within a container

**Comment by repeatedly** [comment]
I'm not sure what the feature is needed in fluentd core.
Writing plugin is not enough for this?

**Comment by inosvaruag** [comment]
Thank for the tip, I opened https://github.com/fluent/fluent-plugin-windows-eventlog/issues/65 on the plugin.
