### ISSUE TITLE
How to suppress  the deprecation warning in rb_check_safe_object

### ISSUE THREAD

**Issue by PreetSangha** [fluent/fluentd#3120]
Check [CONTRIBUTING guideline](https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md) first and here is the list to help us investigate the problem.

**Describe the bug**
We get thousands of this warning when deploying our services and they are making our deployment logs much harder to maintain.

```
"C:/opt/td-agent/lib/ruby/gems/2.7.0/gems/windows-api-0.4.4/lib/windows/api.rb:333: warning: rb_check_safe_obj will be removed in Ruby 3.0"
```

**To Reproduce**
Just start fluentd either as a service or from cli

**Expected behavior**
we would like to know what we can do suppress these warnings.

**Your Environment**

- Fluentd or td-agent version: fluentd 1.17.1
- Operating system: windows 10 professional (Microsoft Windows [Version 10.0.20201.1000]) and on multiple windows 2019 servers (Microsoft Windows [Version 10.0.17763.1397])
- Kernel version: n/a

If you hit the problem with older fluentd version, try latest version first.

**Your Configuration**

Any configuration.

```
<!-- Write your **ALL** error log here -->
```
![image](https://user-images.githubusercontent.com/15098094/92046975-fc029280-edd7-11ea-801b-36437c225d24.png)

**Additional context**

none

**Comment by repeatedly** [comment]
ruby runtime generates its deprecation warning.
You can disable this message by passing `-W:no-deprecated` parameter via `RUBYOPT` environment variable.

The root cause is windows-api/win32-api gems use deprecated ruby function. Open an issue on these repositories instead of this repository.
