### ISSUE TITLE
the config file error!

### ISSUE THREAD

**Issue by Hello-Linux** [fluent/fluentd#3123]
Check [CONTRIBUTING guideline](https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md) first and here is the list to help us investigate the problem.

**Describe the bug**

when I restart the command systemctl restart td-agent.service  error is show :
```
[error]: config error file="/etc/td-agent/td-agent.conf" error_class=Fluent::ConfigError error="<parse> section is required."
```
why?

**Your Environment**

- td-agent 1.11.2
- Operating system: centos7.5
- Kernel version: `3.10.0-957.21.3.el7.x86_64

If you hit the problem with older fluentd version, try latest version first.

**Your Configuration**
```
<source>
  @id pro-basemanageZY-8905
  @type tail
  path /mnt/logs/8905/node.log
  pos_file /mnt/logs/8905/basemanageZY.log.pos
  tag pro-basemanageZY-8905
  read_from_head true
</source>

<filter pro-basemanageZY-8905>
  @type parser
  key_name log
  <parse>
    @type regexp
    time_key time
    expression /\[(?<time>[^\]]*)\](?<content>.*)$/
    time_format %Y-%m-%dT%H:%M:%S
  </parse>
</filter>

<match pro-basemanageZY-8905>
  @type elasticsearch
  scheme http
  host localhost
  port 80
  user elastic
  password Admsdf
  validate_client_version true
  index_name ${tag}.%Y%m%d
</match>
```

**Your Error Log**

```
2020-09-07 13:29:57 +0800 [info]: parsing config file is succeeded path="/etc/td-agent/td-agent.conf"
2020-09-07 13:29:57 +0800 [info]: gem 'fluent-plugin-elasticsearch' version '4.1.1'
2020-09-07 13:29:57 +0800 [info]: gem 'fluent-plugin-kafka' version '0.14.1'
2020-09-07 13:29:57 +0800 [info]: gem 'fluent-plugin-prometheus' version '1.8.2'
2020-09-07 13:29:57 +0800 [info]: gem 'fluent-plugin-prometheus_pushgateway' version '0.0.2'
2020-09-07 13:29:57 +0800 [info]: gem 'fluent-plugin-record-modifier' version '2.1.0'
2020-09-07 13:29:57 +0800 [info]: gem 'fluent-plugin-rewrite-tag-filter' version '2.3.0'
2020-09-07 13:29:57 +0800 [info]: gem 'fluent-plugin-s3' version '1.4.0'
2020-09-07 13:29:57 +0800 [info]: gem 'fluent-plugin-systemd' version '1.0.2'
2020-09-07 13:29:57 +0800 [info]: gem 'fluent-plugin-td' version '1.1.0'
2020-09-07 13:29:57 +0800 [info]: gem 'fluent-plugin-webhdfs' version '1.2.5'
2020-09-07 13:29:57 +0800 [info]: gem 'fluentd' version '1.11.2'
2020-09-07 13:29:58 +0800 [error]: config error file="/etc/td-agent/td-agent.conf" error_class=Fluent::ConfigError error="<parse> section is required."
```

**Comment by ashie** [comment]
You need to add `<parse>` section for the in_tail plugin:
> ```
> <source>
>   @id pro-basemanageZY-8905
>   @type tail
> ...
> ```

See https://docs.fluentd.org/input/tail#less-than-parse-greater-than-directive-required

**Comment by Hello-Linux** [comment]
@ashie  I don't quite understand what you mean, can you help me write a template?

**Comment by Hello-Linux** [comment]
@ashie You mean I need to remove parser in filter and add parser in tail plugin?

**Comment by Hello-Linux** [comment]
I have another question is  :  my index name is "index_name fluentd.${tag}.%Y%m%d",and I see in kibana the index name is pro-basemanagezy-8905.%y%m%d ,why the %y%m%d is not date?

```
<match pro-basemanageZY-8905>
  @type elasticsearch
  scheme http
  host elastic.zhongyuanib.com
  port 80
  user elastic
  password Admin
  validate_client_version true
  index_name ${tag}.%Y%m%d
  <buffer tag, time>
  timekey 1h
  </buffer>
</match>
```

**Comment by Hello-Linux** [comment]
@ashie

**Comment by cosmo0920** [comment]
We use issues for bug tracker **not for user forum**.
Read this documentation first:
https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md
Could you send your question into [community slack](http://slack.fluentd.org/) or [mailing list](https://groups.google.com/forum/#!forum/fluentd)? Thanks!!!

**Comment by repeatedly** [comment]
> can you help me write a template?

Official document has it :)
See https://docs.fluentd.org/input/tail#less-than-parse-greater-than-directive-required
If you have further quesiton, follow cosmo0920 comment.

**Comment by vgokul984** [comment]
@repeatedly I have been using the below configuration on kubernetes version 1.23 and fluentd version v1.15-debian-cloudwatch which work fine with out any issue when am trying use the same config for 1.24 with updated version  v1.16-debian-cloudwatch its give me config error "**config error file="/fluentd/etc/../../../etc/fluent/fluent.conf" error_class=Fluent::ConfigError error="Section <label @fluentdlogs> appears twice**""
[config.txt](https://github.com/fluent/fluentd/files/12108157/config.txt)
can you help on on this
