### ISSUE TITLE
Load balance logs from a single docker instance accross multiple workers

### ISSUE THREAD

**Issue by bvandewalle** [fluent/fluentd#3127]
**Is your feature request related to a problem? Please describe.**
I have a single Docker container on a host which outputs a lot of logs that require processing by a plugin, before being flushed out to Stackdriver.

The issue I'm hitting is that even in multi-worker mode, I didn't find a way to make those logs processed by multiple workers. The single worker which processes all the logs for that docker container is using a full core. In Blocking mode, Docker puts the container in sleep until fluentd got some processing capability. In non-blocking mode, docker simply drops the logs.

How would you achieve this? How can those logs be processed in parallel by multiple workers?

**Describe alternatives you've considered**

By using the fluentd docker loggind driver, a single connection is opened for the container, and a single worker is assigned that connection and is processing all the logs from that container.The other workers are not doing anything

I also thought about redirecting the docker output to a file and processing the file, but again the in_tail driver requires that a single file is processed by a single worker.

**Additional context**

**Comment by kenhys** [comment]
@bvandewalle 
It seems that it may be better to use [Mailing List](https://groups.google.com/g/fluentd).

Anyway, as there is no sample configuration, I guess that  [worker directive](https://docs.fluentd.org/deployment/multi-process-workers#less-than-worker-greater-than-directive) section may be useful. I hope it will help you.

**Comment by repeatedly** [comment]
> The issue I'm hitting is that even in multi-worker mode

Maybe, they use `workers` directive. The problem is docker's logging driver keeps one connection.
To fix the problem, one way is improving fluent-logger-golang to support multiple connections/addresses for load-balancing.

**Comment by kenhys** [comment]
> To fix the problem, one way is improving fluent-logger-golang to support multiple connections/addresses for load-balancing.

Hmm, I may be wrong, thanks you follow up.
