### ISSUE TITLE
Pull Logs from Fluentd

### ISSUE THREAD

**Issue by NIRLESH** [fluent/fluentd#3133]
Check [CONTRIBUTING guideline](https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md) first and here is the list to help us investigate the problem.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

Hello All,
I need to fetch the logs of kubernetes from fluentd it is possible how can i pull logs from fluentd through API.

**Comment by kenhys** [comment]
@NIRLESH 
For these kinds of question, it may be better to ask on [Mailing list](https://groups.google.com/forum/#!forum/fluentd)

**Comment by cosmo0920** [comment]
You shouldn't post a question.
We use this _issue tracker as just issue tracking not use forum_.
And this issue seems to be muiti-posted:
https://groups.google.com/g/fluentd/c/y5_gwkaghnE
Closing.
