### ISSUE TITLE
not able to filter logs using the parser plugin in fluentd

### ISSUE THREAD

**Issue by PrabuddhaRaj** [fluent/fluentd#3135]
Check [CONTRIBUTING guideline](https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md) first and here is the list to help us investigate the problem.

**Describe the bug**
not able to filter logs using the parser plugin in fluentd

**To Reproduce**
add the below code in the match plugin of configmap.yaml file. 
</match>
      #  <filter tail.containers.**>
      #  @type parser
      #  key_name log
      #     <parse>
      #     @type regexp
      #     expression /^\[(?<type>[^\]]*)\]\s+\[(?<messageType>[^\]]+)\]:[^"]+"(?<method>\S*)[^"]*"\s+"(?<url>[^"]+)".*"ApplicationID:\s*(?<applicationid>[^"]+)" "TrueCallerIP:\s*(?<truecallerip>[^"]*)" "TenantID:\s*(?<tenantid>[^"]+)"/
      #     time_format %d/%b/%Y:%H:%M:%S %z
      #  </parse>
      # </filter> 

**Expected behavior**
i need to extract some fields from my log as a key value pair so i am trying to use parser plugin but i am not getting the exact result. so i tried a few approaches:
1) my log looks like this: 
[INFO] [API Access Log]: 172.17.0.2 - [2020-09-25 17:35:33.35] "GET http/1.1" "/api/sap/c4c/odata/v1/c4codataapi/AppointmentAttachmentFolders" 200 2 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36" "ApplicationID: app1345" "TrueCallerIP: " "TenantID: "
i want to aggregate on some fields and hence i want to extract ApplicationId,tenantId and TruecallerIP from teh above log.
i tried to parse it through a regex and i get no error in logs as the log is parsed correctly but in the output i get the same log and not the formatted one as expected.
i need something like : {"type": "INFO",.......,"ApplicationID":"app1345"} like that...
https://regex101.com/r/uiTloy/2
i tried in the above tool and parsing is happening correctly but i am not getting it in the same way as an output in splunk UI.
i ams ending logs to splunk via the above configuration. 

2) i tried to extract using the record_transformer plugin:
<filter tail.containers.**>
        @type record_transformer
        enable_ruby
        <record>
          # set the sourcetype from splunk.com/sourcetype pod annotation or set it to kube:container:CONTAINER_NAME
          sourcetype ${record.dig("kubernetes", "annotations", "splunk.com/sourcetype") ? "kube:"+record.dig("kubernetes", 
     "annotations", "splunk.com/sourcetype") : "kube:container:"+record.dig("kubernetes","container_name")}
          container_name ${record.dig("kubernetes","container_name")}
          namespace ${record.dig("kubernetes","namespace_name")}
          pod ${record.dig("kubernetes","pod_name")}
           application_id ${record["log"]["ApplicationID:"]}
          trueCaller_ip ${record["TrueCallerIP:"]}
          tenant_id  ${record["TenantID:"]}
       </record>
</filter>
this also didnt work. 
3) <format>
          # we just want to keep the raw logs, not the structure created by docker or journald
          @type single_value
          message_key log
          add_newline false
        </format>
this is the code that converts it into a single line log, if i dont use this then i would get a json and i can dig in the record like this but i think i am missing something in this approach or i have not understood the working of fluentd plugin.

Environment: Kubernetes - v1.16.6

Kubernetes version (use kubectl version):
Ruby version (use ruby --version):
OS (e.g: cat /etc/os-release): Mac
Splunk version:
Others: Using Docker for Desktop and running single cluster using it locally on Mac
i am using splunk connect for kubernetes helm chart.
https://github.com/splunk/splunk-connect-for-kubernetes

If you hit the problem with older fluentd version, try latest version first.

**Your Configuration**

```
<!-- Write your configuration here -->
```

**Your Error Log**

```
<!-- Write your **ALL** error log here -->
```

**Additional context**

**Comment by kenhys** [comment]
@PrabuddhaRaj 

Hi, It seems that your configuration file doesn't contain `time_key` and appropriate regexp expression like this:

```
<source>
  @type tail
  @id tail
  path sample.log
  pos_file sample.pos
  <parse>
    @type none
  </parse>
  read_from_head true
  tag tail.containers
</source>

<filter tail.containers.**>
  @type parser
  key_name message
  <parse>
    @type regexp
    #expression /^\[(?<type>[^\]]*)\]\s+\[(?<messageType>[^\]]+)\]:[^"]+"(?<method>\S*)[^"]*"\s+"(?<url>[^"]+)".*"ApplicationID:\s*(?<applicationid>[^"]+)" "TrueCallerIP:\s*(?<truecallerip>[^"]*)" "TenantID:\s*(?<tenantid>[^"]+)"/
    expression /^\[(?<type>[^\]]*)\]\s+\[(?<messageType>[^\]]+)\]:[^"]+\[(?<logtime>[^\]]*)\] "(?<method>\S*)[^"]*"\s+"(?<url>[^"]+)".*"ApplicationID:\s*(?<applicationid>[^"]+)" "TrueCallerIP:\s*(?<truecallerip>[^"]*)" "TenantID:\s*(?<tenantid>[^"]+)"/
    time_key logtime
    time_format %Y-%m-%d %H:%M:%S.%L
  </parse>
</filter>

<match **>
  @type stdout
</match>

```

I hope it wil help.

```
2020-10-19 13:45:55 +0900 [info]: starting fluentd-1.11.3 pid=94027 ruby="2.7.2"
2020-10-19 13:45:55 +0900 [info]: spawn command to main:  cmdline=["/home/kenhys/.rvm/rubies/ruby-2.7.2/bin/ruby", "-Eascii-8bit:ascii-8bit", "/home/kenhys/.rvm/gems/ruby-2.7.2@fluentd/bin/fluentd", "-c", "filter.conf", "--under-supervisor"]
2020-10-19 13:45:55 +0900 [info]: adding filter pattern="tail.containers.**" type="parser"
2020-10-19 13:45:55 +0900 [info]: adding match pattern="**" type="stdout"
2020-10-19 13:45:55 +0900 [info]: adding source type="tail"
2020-10-19 13:45:55 +0900 [warn]: #0 define <match fluent.**> to capture fluentd logs in top level is deprecated. Use <label @FLUENT_LOG> instead
2020-10-19 13:45:55 +0900 [info]: #0 starting fluentd worker pid=94034 ppid=94027 worker=0
2020-10-19 13:45:55 +0900 [info]: #0 [tail] following tail of sample.log
2020-09-23 21:04:33.800000000 +0900 tail.containers: {"type":"INFO","messageType":"API Access Log","method":"GET","url":"/api/sap/c4c/odata/v1/c4codataapi/AppointmentAttachmentFolders","applicationid":"app1345","truecallerip":"","tenantid":" "}
2020-10-19 13:45:55 +0900 [info]: #0 fluentd worker is now running worker=0
2020-10-19 13:45:55.918316217 +0900 fluent.info: {"pid":94034,"ppid":94027,"worker":0,"message":"starting fluentd worker pid=94034 ppid=94027 worker=0"}
2020-10-19 13:45:55.918726283 +0900 fluent.info: {"message":"[tail] following tail of sample.log"}
2020-10-19 13:45:55.918991489 +0900 fluent.info: {"worker":0,"message":"fluentd worker is now running worker=0"}
```

**Comment by kenhys** [comment]
@PrabuddhaRaj  I'll close this issue after a while.

**Comment by kenhys** [comment]
I'll close this issue without a response for a while.
