### ISSUE TITLE
Some log messages sent unparsed to elasticsearch

### ISSUE THREAD

**Issue by alcyxob** [fluent/fluentd#3140]
Check [CONTRIBUTING guideline](https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md) first and here is the list to help us investigate the problem.

**Describe the bug**
We use parser for log parsing and elasticsearch for output. Sometimes fluentd sends unparsed log to elasticsearch.

**To Reproduce**
Send logs and use elasticsearch as an output

log example:
```
2020-10-02 15:56:17.512 [INFO] [c.b.c.x.marketdata.repo.RepoController:112] [1:ault-executor-4] [c73637247d48e246:a72df132-15c6-4f81-b158-4254049924bc] Updating Repo with UUID: f6344d9f-a486-4632-bb94-6f7d5d0da30e
```

**Expected behavior**
All  logs are parsed

**Your Environment**

- Fluentd or td-agent version: 1.11.3
- Operating system: Debian GNU/Linux 10 (buster)
- Kernel version: 4.19.76-linuxkit

**Your Configuration**

```
    <filter kubernetes.var.log.containers.**>
      @id filter_parser2
      @type parser
      reserve_data true
      remove_key_name_field true
      emit_invalid_record_to_error false
      replace_invalid_sequence true
      key_name message
      <parse>
        @type regexp
        expression /^(?<time>(\d)+(-\d+)+(\S)+\W(\S)+)(\s+)*\[(?<log-level>[^\s]+)\](\s+)*\[(?<classfilename>(\S)+)[:](?<line>\d+)\](\s+)*\[(?<process-id>(\d)+)[:](?<thread-id>\S+)\](\s+)*\[(?<jaegger-id>(\S)*)[:](?<correlation-id>\S*)\](\s+)*(?<message>.*)$/
      </parse>
    </filter>
```

**Your Error Log**
Fluentd doesn't throw any logs when the message is not parsed

**Additional context**

All messages follow the same format, but approximately 10% of all messages are not parsed

**Comment by cosmo0920** [comment]
This issue is multi-posted and for fluent-plugin-elasticsearch issue. Closing.
