### ISSUE TITLE
Fluent::Plugin::ConcatFilter should support filter or say why it does not

### ISSUE THREAD

**Issue by grosser** [fluent/fluentd#3142]
Check [CONTRIBUTING guideline](https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md) first and here is the list to help us investigate the problem.

**Describe the bug**

I'm seeing this in the logs `disable filter chain optimization because [Fluent::Plugin::ConcatFilter] uses #filter_stream method`
since this is a builtin plugin I assume using it means I cannot use the filter chain optimization
so please either fix that by adding filter or some docs on why it is not possible ... ideally in the warning directly

**To Reproduce**

start fluentd

**Expected behavior**

no warning

**Your Environment**

- Fluentd or td-agent version: `fluentd --version` or `td-agent --version` 1.11.3
- Operating system: `cat /etc/os-release` does not matter
- Kernel version: `uname -r` does not matter

If you hit the problem with older fluentd version, try latest version first.

**Your Configuration**

```
none
```

**Your Error Log**

```
<!-- Write your **ALL** error log here -->
none
```

**Additional context**

none

**Comment by repeatedly** [comment]
> some docs on why it is not possible

See also: https://docs.fluentd.org/filter#filter-chain-optimization
Do you want to know the implementation detail?

> so please either fix that by adding filter

I'm not sure concat plugin can use `filter` method for good performance.

**Comment by grosser** [comment]
for example there in the docs it could say `for example xyz does not use it because <reason>`
I'm guessing there is a good reason, but it would be nice to for example list all built-in plugins that can't use it.
I tried googling for the error message I got and did not find anything pointing out why ConcatFilter can't use it.
I'd guess it's because it tries to concat multiple messages so working on a single message makes no sense, but calling that out would be nice.

**Comment by cosmo0920** [comment]
fluent-plugin-concat uses `Fluent::MultiEventStream` class to manipulate multiple records to concatenate.:
https://github.com/fluent-plugins-nursery/fluent-plugin-concat/blob/master/lib/fluent/plugin/filter_concat.rb#L120

In essence, fluent-plugin-concat(Fluent::Plugin::ConcatFilter) needs multiple records as enumerable format.
So, using `#filter_stream` implementation is reasonable for now.

I don't think that using `#filter` is good for performance.

**Comment by grosser** [comment]
that makes sense, thx!
docs pointing this out would be great too, so nobody has to dig in from the warning :)
