### ISSUE TITLE
Remove unused "question" label from GitHub issues

### ISSUE THREAD

**Issue by kenhys** [fluent/fluentd#3149]
Check [CONTRIBUTING guideline](https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md) first and here is the list to help us investigate the problem.

**Is your feature request related to a problem? Please describe.**

Please, remove "question" label from GitHub issues because "question" label is not used at all. (0 open, 0 closed)
I've attached the current status of it.

**Describe the solution you'd like**

Remove "question" label.

**Describe alternatives you've considered**

N/A

**Additional context**

**0 open 0 closed** !

![image](https://user-images.githubusercontent.com/225841/96202276-c1c10f00-0f99-11eb-8cba-edbe5a8f85e3.png)

**Comment by cosmo0920** [comment]
I'd deleted "question" from label.
Closing,
