### ISSUE TITLE
I have checked that fluentd has collected the logs, but I can't see the logs in Elastic search.

### ISSUE THREAD

**Issue by BangShinChul** [fluent/fluentd#3154]
Check [CONTRIBUTING guideline](https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md) first and here is the list to help us investigate the problem.

**Describe the bug**

Hello! :) 
Currently, I am collecting logs with Elastic Search and Fluentd.
In this process, only certain logs behave strangely.

Fluentd collects logs and inserts them into Elasticsearch, and Fluentd's log (td-agent) shows that the logs have been collected well.
There are no other log contents in Elastic Search's log.

However, when I actually check with Kibana, there are no logs collected.. I tried to query by direct query to ElasticSearch because I was wondering if Kibana was a problem, but I still could not check the collected logs.

**To Reproduce**

**Expected behavior**

**Your Environment**

- Fluentd or td-agent version: `fluentd --version` or `td-agent --version`
- Operating system: `cat /etc/os-release`
- Kernel version: `uname -r`

fluentd version : 1.7.4
OS : apline linux:3.9 (docker image)

If you hit the problem with older fluentd version, try latest version first.

**Your Configuration**

fluentd is deployed and operated inside a container in the kubernetes environment.
That fluentd will collect log files by referencing a specific directory.
Send the collected log files to the Elastic search server.

```
<!-- Write your configuration here -->
```

**Your Error Log**

I have not found any error logs related to this issue.

```
<!-- Write your **ALL** error log here -->
```

**Additional context**

In my opinion, there seems to be a problem with fluentd delivering logs to Elastic Search.
I don't know what problem fluentd faced at this time, but I think that it couldn't handle the normal behavior due to network errors or problems of Elastic Search.

Please reply to me. 
Thank you!

**Comment by BangShinChul** [comment]
I solved this problem.

I proceeded to determine the cause of the problem in the following order. : 

- I tried entering data with the index name that is not being collected in Elastic Search. : 
```
# example
$ curl -XPUT "http://localhost:9200/my_index/_doc/1" -H 'Content-Type: application/json' -d'
{
  "name": "Foo bar",
  "message": "Hello Elasticsearch"
}'
```

- Execution result : 
```
{"error":{"root_cause":[{"type":"validation_exception","reason":"Validation Failed: 1: this action would add [2] total shards, but this cluster currently has [1000]/[1000] maximum shards open;"}],"type":"validation_exception","reason":"Validation Failed: 1: this action would add [2] total shards, but this cluster currently has [1000]/[1000] maximum shards open;"},"status":400}
```

- I recognized this result as a lack of number of shards, and increased the number of shards per node through the command below. : 
```
$ curl -X PUT http://localhost:9200/_cluster/settings -H "Content-Type: application/json" -d '{ "persistent": { "cluster.max_shards_per_node": "3000" } }'
```

- Check the result of modifying the number of shards : 
```
$ curl -s http://localhost:9200/_cluster/settings?pretty
{
  "persistent" : {
    "cluster" : {
      "max_shards_per_node" : "3000"
    }
  },
  "transient" : {
    "search" : {
      "max_buckets" : "20000"
    }
  }
}
```

- PUT request retry : 
```
$ curl -XPUT "http://localhost:9200/my_index/_doc/1" -H 'Content-Type: application/json' -d'
{
  "name": "Foo bar",
  "message": "Hello Elasticsearch"
}'
{"_index":"my_index","_type":"_doc","_id":"1","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":0,"_primary_term":1}
```

* * * 

The above process confirmed that a new index (shard) was created.
The issue has been resolved.

But the strange thing is, When Fluentd sent the log to Elastic Search,
If Elastic Search lacked the number of shards, Elastic Search would have returned an error and Fluentd had to deal with the failed log transmission for this error.
But Fluentd didn't.

In my personal conclusion, Elastic Search returned a value of status:400 to Response Body on error return due to lack of shard, but HTTP Status Code returned 200, so I think it was determined that the logs were sent normally from Fluentd's perspective.

**Comment by kenhys** [comment]
> The issue has been resolved.

So, I'll close this issue.
If you have further question, I'll recommend  posting to https://groups.google.com/g/fluentd
