### ISSUE TITLE
Can't parse simple log file with regexp

### ISSUE THREAD

**Issue by davidcsi** [fluent/fluentd#3157]
Check [CONTRIBUTING guideline](https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md) first and here is the list to help us investigate the problem.

**Describe the bug**
I'm not able to parse a simple log file with regexp.
As an example this line:

(I tried fluentular and still got)

text:
```
f6a6e1ae-e52e-4aba-a8a5-4e3cc7f40914 2020-11-03 14:32:34.975779 [CRIT] mod_dptools.c:1866 audio3: https://mydomain.s3-eu-west-1.amazonaws.com/media/576d06e5-04fc-11eb-a52c-020fd8c14d18/5f9ddf2d5df0f698094395.mpg
```
regexp:
```
^(?<UUID>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}) (?<time>[^ ].*) (?<message>[^ ]*)$
```
and got:
```
time    2020/11/03 14:32:34 +0000
UUID    f6a6e1ae-e52e-4aba-a8a5-4e3cc7f40914
message https://mydomain.s3-eu-west-1.amazonaws.com/media/576d06e5-04fc-11eb-a52c-020fd8c14d18/5f9ddf2d5df0f698094395.mpg
```
It's missing what's between the datetime and "https"
I should get:

time: `2020/11/03 14:32:34 +0000`
UUID: `f6a6e1ae-e52e-4aba-a8a5-4e3cc7f40914`
message: `[CRIT] mod_dptools.c:1866 audio3:https://mydomain.s3-eu-west-1.amazonaws.com/media/576d06e5-04fc-11eb-a52c-020fd8c14d18/5f9ddf2d5df0f698094395.mpg`

I also can't figure out how to NEGATE something. i.e.: All lines NOT beginning with a UUID, i.e.:
```
variable_call_uuid: [f6a6e1ae-e52e-4aba-a8a5-4e3cc7f40914]
```

Would be part of a multiline

Many thanks!

**Comment by kenhys** [comment]
It may be better to use https://groups.google.com/g/fluentd for asking fluentd community support.

Anyway, the following sample configuration may work.

```
<source>
  @type tail
  path sample.log
  read_from_head true
  <parse>
    @type regexp
    expression /^(?<UUID>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}) (?<time>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}\.\d+?) (?<message>.+)$/
    time_key time
    time_format %Y-%m-%d %H:%M:%S.%L
  </parse>
  tag dummy
</source>

<match **>
  @type stdout
</match>
```

Output:

```
2020-11-09 14:04:37 +0900 [info]: #0 following tail of sample.log
2020-11-03 14:32:34.975779000 +0900 dummy: {"UUID":"f6a6e1ae-e52e-4aba-a8a5-4e3cc7f40914","message":"[CRIT] mod_dptools.c:1866 audio3: https://mydomain.s3-eu-west-1.amazonaws.com/media/576d06e5-04fc-11eb-a52c-020fd8c14d18/5f9ddf2d5df0f698094395.mpg"}
2020-11-09 14:04:37 +0900 [info]: #0 fluentd worker is now running worker=0
```

**Comment by kenhys** [comment]
@davidcsi  I'll close this issue after a while.
