### ISSUE TITLE
File output plugin flash line in wrong position. 

### ISSUE THREAD

**Issue by shenmuxiaosen** [fluent/fluentd#3163]
**Describe the bug**
File output plugin writes logs in wrong position which can mess up with previous line. 

**To Reproduce**
It's hard to reproduce as it only happens when the remote disk in the VM where fluentd is running shortly disconnects and reconnects several seconds after.  

**Expected behavior**
Each log should start with a new line. 

**Your Environment**

- Fluentd or td-agent version: `1.11.1`
- Operating system: `Ubuntu 16.04.7 LTS`
- Kernel version: `5.4.0-1026-azure`

**Your Configuration**

```
<match notification>
  @type file
  path /var/log/td-agent/notification
  append true
  buffer_type file
  time_slice_wait 12h
  buffer_path /var/log/notification/buffer
  buffer_chunk_limit 2g
  time_slice_format %Y%m%d%H
  format json
</match>
```

**Additional context**

The file output plugin mostly works well but in some circumstances it will flush the log to the wrong position. Ideally every log should start with a new line, but we have observed something like below:

{first line}
{second line}
**{third { forth line}**    NOT Valid Json anymore
{fifth line}
{sixth line}

This issue happened along with remote disk shortly disconnect. It happens rarely like every couple of months. But we have several downstream services highly depend on those logs.

**Comment by repeatedly** [comment]
Does anyone know how to handle this problem?
The problem seems to happen the outside of fluentd/glibc runtime.
fluentd/glibc function tries to append the data to the end of file but remote disk's file(or metadata?) is broken by disconnect.

**Comment by shenmuxiaosen** [comment]
Any updates on this issue?
