### ISSUE TITLE
Unknown escape character issue or extra character being added after parsing the logs

### ISSUE THREAD

**Issue by sumit2904** [fluent/fluentd#3164]
**Describe the bug**

I am trying to use fluentd log driver from aws ecs. and I have set up a fluentd on a docker in an ec2 machine which basically puts all the data to elasticsearch, however, I am seeing some extra escape character, or is it some encoding or parsing issue from the fluentd.

**To Reproduce**

At first I thought this issue is something specific to aws ecs. but when I ran the service manually on docker on an ec2 machine and used the same fluentd log driver I faced the same issue.

I have used this docker image "fluent/fluentd:v1.6-debian-1" and following is my Dockerfile to create the image.

```
# fluentd/Dockerfile
FROM fluent/fluentd:v1.6-debian-1
USER root
RUN ["gem", "install", "fluent-plugin-elasticsearch", "--no-document", "--version", "3.5.2"]
USER fluent
```

Here I mount the following "fluent.conf" file  to the "/fluentd/etc" directory of this docker container.

```
# fluentd/conf/fluent.conf

<source>
  @type forward
  port 24224
  bind 0.0.0.0
</source>
<match *.**>
  @type copy
  <store>
    @type elasticsearch
    hosts IPaddressof-elasticsearch
    port 9200
    user username
    password password_of_es
    #logstash_format true
    #logstash_prefix fluentd
    logstash_dateformat %Y%m%d
    include_tag_key true
    type_name access_log
    tag_key @log_name
    #flush_interval 10s
    include_timestamp true
    index_name fluentd
  </store>
  <store>
    @type stdout
  </store>
  <buffer tag>
    @type memory # or file
    flush_interval 1
    chunk_limit_size 1m
    flush_thread_interval 0.1
    flush_thread_burst_interval 0.01
    flush_thread_count 15
    total_limit_size 2GB
  </buffer>
</match>
```

I have even tried with simple fluentd conf as given below but the issue which I am facing is same the logs looks same like it is mentioned below.

```
 <source>
   @type forward
 </source>

 <match *>
   @type stdout
 </match>
```

**What is happening**
Basically, the log should be clear and readable however I see the logs like this.

```
2020-11-11 10:00:57 +0000 truck-service: {"container_id":"909d01f69e2323b2d436d907d11f22424d990fc3fc8b57e52ad2936470abc096","container_name":"/condescending_agnesi","source":"stdout","log":"\u001b[37m2020-11-11T10:00:57.046+0000\u001b[0;39m \u001b[34mINFO \u001b[0;39m \u001b[34m\u001b[0;39m \u001b[34mcab8b866bfac6852\u001b[0;39m \u001b[34mcab8b866bfac6852\u001b[0;39m [\u001b[32mhttp-nio-8080-exec-9\u001b[0;39m] \u001b[33mc.b.o.t.s.TruckInventoryDataAggregatorService\u001b[0;39m::\u001b[35m318\u001b[0;39m: - { 106 : 1.2 }"}
```

If you see the "log" part I am seeing some extra character being added like "\u001b" or "37m" etc.

**Your Environment**

- Fluentd or td-agent version: `fluentd --version` or `td-agent --version`
For docker i used this image : fluent/fluentd:v1.6-debian-1
I also tried with td-agent 0.12.40

- Operating system: `cat /etc/os-release`
DISTRIB_DESCRIPTION="Ubuntu 20.04.1 LTS"

- Kernel version: `uname -r`
 uname -r
5.4.0-1029-aws

**Comment by kenhys** [comment]
@sumit2904 

Hi,

GitHub issue is not appropriate for asking questions like above.
Please use https://groups.google.com/forum/#!forum/fluentd instead.
It could be get feedback from mailing list users.

By the way, using https://github.com/mattheworiordan/fluent-plugin-color-stripper may solve your trouble (incoming terminal escape sequence log) in such a purpose.

I hope it will help you.

**Comment by sumit2904** [comment]
@kenhys thanks a lot for the response. that was the issue. 

And sure I will post my questions on google groups in the future.
