### ISSUE TITLE
Support JRuby

### ISSUE THREAD

**Issue by repeatedly** [fluent/fluentd#317]
Fluentd doesn't now work on JRuby because dependent gems don't work.
But I think time to support JRuby because Cool.io starts to support JRuby

Here are the tasks:

- Cool.io: https://github.com/tarcieri/cool.io/issues/32
- msgpack-jruby: I'm not sure how to support msgpack-jruby seamlessly
  - Revived this issue > https://github.com/msgpack/msgpack-ruby/issues/3
- Fix GVL dependent code: Can we use `thread_safe` gem? > https://github.com/headius/thread_safe

If you have any suggestion, please let me know!

**Comment by cyberroadie** [comment]
Is the support_jruby tree working with JRuby or does it need additional work?

**Comment by repeatedly** [comment]
@cyberroadie Maybe, super α version with experimental JRuby support Cool.io.

@taichi How about the progress? And we are now developing v0.14 with new plugin mechanizm and etc. If you have any concerns for supporting better JRuby support, please let me or tagomoris know.

**Comment by taichi** [comment]
need many of additional works.
and i don't work for this issue now. because i'm busy.

**Comment by repeatedly** [comment]
No active users.
We will re-open this issue if JRuby support is needed.

**Comment by richardsondx** [comment]
@repeatedly  jRuby support is needed.

**Comment by repeatedly** [comment]
@richardsondx What is the your case?

**Comment by gumho** [comment]
We have some transformation jars written in Java that would be nice to run in fluent plugins.

**Comment by TaLoN1x** [comment]
up, looking forward for jruby support also.

**Comment by cmrust** [comment]
I'd like to see JRuby support, purely for the performance opportunities.

**Comment by jstaffans** [comment]
I agree it would be cool to implement this for performance reasons, @repeatedly!

**Comment by cmrust** [comment]
I assume the task lists above are invalid, given they're almost 5 years old. If anyone's got any more up to date info, I'd love to hear it. Might try to poke at this soon if I can find some time.

**Comment by repeatedly** [comment]
msgpack-ruby has already supported jruby so task2 is resolved.
We don't know how to migrate cool.io/GVL related code into JRuby.
I'm not sure which is lower cost, supporting native JRuby or TruffleRuby.

**Comment by llimon** [comment]
I think fluentd + JRuby will help in environments where high log capacity is needed. Removing GIL should improve scaling up.

**Comment by case-k-git** [comment]
Hi I am facing a issue to handle large amount of data.
router.emit_stream is not supported multiple process so need to use multithread process.
but there are GIL problem as well.
inside of router.emit_stream buffer.write has been called and this is too slow to handle large amount of data

https://github.com/fluent/fluentd/blob/d6710439a4eaa268a062b6619458b5875660aba2/lib/fluent/event_router.rb#L114

**Comment by cosmo0920** [comment]
Hi, preliminary JRuby support via truffleruby is already included in master:
https://github.com/fluent/fluentd/issues/3375 

Does anyone want to test it?
TruffleRuby is the another Ruby implementation which works on JVM:
https://github.com/oracle/truffleruby

**Comment by cosmo0920** [comment]
> router.emit_stream is not supported multiple process so need to use multithread process.
> but there are GIL problem and can not improve performance

I'm not sure what you are trying to say. You mean that `router.emit_stream` is not workable at parallel on multiprocess, right?
Fluentd already supports multi-worker feature which uses spawn model:
https://docs.fluentd.org/deployment/multi-process-workers

Does this feature not working well on your environment?

**Comment by case-k-git** [comment]
HI, thank you for your reply.

>Does anyone want to test it?
>TruffleRuby is another Ruby implementation which works on JVM:
> https://github.com/oracle/truffleruby
thank you for the information. I see. I am interested in about TruffleRuby.

>I'm not sure what you are trying to say. You mean that router.emit_stream is not workable at parallel on multiprocess, right?
>Fluentd already supports multi-worker feature which uses spawn model:

thank you for your suggestion. I know that I can use multiprocess from config . 
what I want to do is fetch the updated record from database and send the query results to cloud pub/sub.
to send the query results as soon as possible. need to send the query results using multiprocess or multithread inside from input-plugin not  config file.
