### ISSUE TITLE
Fluentd filtering json

### ISSUE THREAD

**Issue by Transformer-cloud** [fluent/fluentd#3172]
**Describe the bug**
I have problem filtering my log with the parser type of regex (need to strip color to and the plugin doesent work)
my log is : 
`{"new_log":"\u001b[92m[my-app]\u001b[39m \u001b[33mInfo\u001b[39m\t11/17/2020, 3:58:00 PM \u001b[33m[CheckerService]\u001b[39m \u001b[92mRunning delta checks\u001b[39m - {}"}`

**To Reproduce**
bitnami fluentd image with this specific log and configuration

**Expected behavior**
```
{
"app_name": "[my-app]",
"loglevel":"info",
"context": "[CheckerService]"
"message":"Running delta checks",
"payload": "{}"
}
```
***my env***:

- Fluentd or td-agent version: 1.11.5
- Operating system: 
`PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/`
- Kernel version: `4.15.0-1096-azure`

**Your Configuration**

```
   <source>
       @type tail
       @label @COLOR
        tag my-app-ongoing
       path /var/log/containers/my-app-ongoing*.log
       pos_file /opt/bitnami/fluentd/logs/buffers/my-app-ongoing.pos
        <parse>
          @type json
        </parse>
     </source>

     # Test removing color
     <label @COLOR>
    <filter>
        @type parser
        key_name log
        <parse>
          @type regexp
          expression (?<new_log>.*)
        </parse>
       </filter>
        <filter>
                @type parser
                key_name new_log
                <parse>
                  @type regexp
                  expression \\u\d+[^m]*m(?<appname>\[[^\\]+)\\u\d+[^m]*m\s+\\u\d+[^m]*m(?<loglevel>[A-Za-z]*)\\u\d+[^m]*m\\[t](?<entrytime>[^\[]*)\\u\d+[^m]*m(?<context>\[[^\\]+)\\u\d+[^m]*m\s\\u\d+[^m]*m(?<message>[A-Za-z\s]*)\\u\d+[^m]*m\s-\s(?<payload>.*)
                  time_format %d/%b/%Y:%H:%M:%S %z
                </parse>
               </filter>
     <match **>
      @type stdout
      </match>
     </label>


    # Forward all logs to the aggregators
    <match **>
      @type forward
      <server>
        host logging-fluentd-headless.logging.svc.cluster.local
        port 24224
      </server>

      <buffer>
        @type file
        path /opt/bitnami/fluentd/logs/buffers/logs.buffer
        flush_thread_count 2
        flush_interval 5s
      </buffer>
    </match>

```

***Error log***

```
2020-11-17T16:07:00.833752437Z 2020-11-17 16:07:00 +0000 [warn]: #0 dump an error event: error_class=Fluent::Plugin::Parser::ParserError error="pattern not matched with data '\e[92m[my-app]\e[39m \e[33mInfo\e[39m\t11/17/2020, 4:07:00 PM \e[33m[CheckerService]\e[39m \e[92mRunning delta checks\e[39m - {}'" location=nil tag="my-app-ongoing" time=2020-11-17 16:07:00.833415835 +0000 record={"new_log"=>"\e[92m[my-app]\e[39m \e[33mInfo\e[39m\t11/17/2020, 4:07:00 PM \e[33m[CheckerService]\e[39m \e[92mRunning delta checks\e[39m - {}"}
```
Any suggestion ?

**Comment by kenhys** [comment]
@Transformer-cloud 

Hi, 

GitHub issue is not appropriate for asking questions like above.
Please use https://groups.google.com/forum/#!forum/fluentd instead.
It could be get feedback from mailing list users.

By the way, using https://github.com/mattheworiordan/fluent-plugin-color-stripper may solve your trouble in such a purpose.

I hope it will help you.
