### ISSUE TITLE
reprocess failed logs from secondary path

### ISSUE THREAD

**Issue by vermachandra** [fluent/fluentd#3183]
**Is your feature request related to a problem? Please describe.**
No .

**Describe the solution you'd like**
Very often data appears in secondary path , like when ES is down and fluentd could not connect to it , after retry completion logs are stored in secondary path , a solution is needed to resend it to ES.

**Describe alternatives you've considered**

**Additional context**

**Comment by cosmo0920** [comment]
Read the guideline:
https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md

Thanks!!!!
