### ISSUE TITLE
Add support for query params in in_http input plugin

### ISSUE THREAD

**Issue by omerlh** [fluent/fluentd#3188]
Check [CONTRIBUTING guideline](https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md) first and here is the list to help us investigate the problem.

**Is your feature request related to a problem? Please describe.**

I am using fluentd to collect CSP violation report, I would like to add query params, like the website version to help us quickly spot issues related to a release.

**Describe the solution you'd like**

Add a property like `add_query_params`, that when set will parse the query params and add them to the record.
 
**Describe alternatives you've considered**

Passing it using a path and parsing the path with regex

**Additional context**

I'm willing to open a PR if the solution is acceptable

**Comment by repeatedly** [comment]
LGTM. Patches are welcome 👍

**Comment by omerlh** [comment]
Awesome!  Opened a PR to add it...
