### ISSUE TITLE
Buffer file name pattern

### ISSUE THREAD

**Issue by shenmuxiaosen** [fluent/fluentd#3205]
Check [CONTRIBUTING guideline](https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md) first and here is the list to help us investigate the problem.

**Describe the bug**
When using the file buffer for file output plugin. We have a monitor against the buffer file directory. Usually those buffer files will be named as buffer.b5b6b16c43e4a48682199a7b607xxxxxxx.log. However, right before it got flushed, a new buffer file will be created with name buffer.**d**5b6b16c43e4a48682199a7b607xxxxxxx.log with exactly the same content. Then deleted quickly. Is this a designed behavior? Is there a way that we can stop copying buffer files before flushed? 

**To Reproduce**
Use file buffer for file output plugin. 

**Expected behavior**
Create just one buffer file instead of making a copy right before flushed. 

**Your Environment**

- Fluentd or td-agent version: `1.11.1`
- Operating system: `Ubuntu 16.04.7 LTS`
- Kernel version: `5.4.0-1026-azure`

If you hit the problem with older fluentd version, try latest version first.

**Your Configuration**

```
<!-- Write your configuration here -->
<match debug.**>
  @type file
  path "/var/log/td-agent/notification"
  <format>
    @type json
  </format>
  <buffer>
    @type file
    path /var/log/notification/buffer/
    chunk_limit_size 2g
    timekey_wait 1m
    timekey 60
  </buffer>
</match>

**Your Error Log**

```

```

**Additional context**

<!-- Add any other context about the problem here. -->

**Comment by repeatedly** [comment]
>  Is this a designed behavior? 

Yes. This is designed behavior. 

> Is there a way that we can stop copying buffer files before flushed?

No, file buffer doesn't copy files. file buffer renames files from bxxxx(this means staged file. buffer stores incoming data from input) to qxxxx(this means queued files. No more update), not copy.

**Comment by shenmuxiaosen** [comment]
> > Is this a designed behavior?
> 
> Yes. This is designed behavior.
> 
> > Is there a way that we can stop copying buffer files before flushed?
> 
> No, file buffer doesn't copy files. file buffer renames files from bxxxx(this means staged file. buffer stores incoming data from input) to qxxxx(this means queued files. No more update), not copy.

Thanks for the quick reply. Is this rename (from b to q) behavior consistent we can rely on or internal implementation that may be changed anytime?

**Comment by repeatedly** [comment]
>  Is this rename (from b to q) behavior consistent we can rely on or internal implementation that may be changed anytime?

This rename depends on system's `rename` feature, e.g. `rename` in C runtime. Fluentd doesn't change anything.
