### ISSUE TITLE
fail to add a new field according to an existing key name

### ISSUE THREAD

**Issue by zffocussss** [fluent/fluentd#3212]
Check [CONTRIBUTING guideline](https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md) first and here is the list to help us investigate the problem.

**Describe the bug**

I have a key named "kubernetes.container_name",
I want to use this value of "kubernetes.container_name"

**To Reproduce**

it get an empty value whatever I changed the conf

**Expected behavior**

value of key "kubernetes.container_name" should be used

**Your Environment**
docker.io/bitnami/fluentd:1.11.5-debian-10-r33

**Your Configuration**

```
    <filter kubernetes.**>
      @type record_transformer
      #enable_ruby true
      <record>
        original_tag ${tag}
      </record>
      <record>
        #app $."kubernetes.container_name"
        app ${record["kubernetes.container_name"]}
        #app $.kubernetes.container_name
        #app $['kubernetes.container_name']
        app "$['kubernetes.container_name']"
      </record>
    </filter>


```

**Additional context**

**Comment by repeatedly** [comment]
I can't reproduce the problem.

- conf

```
<source>
  @type forward
</source>
<filter kubernetes.**>
  @type record_transformer
  <record>
    original_tag ${tag}
    app ${record["kubernetes.container_name"]}
  </record>
</filter>
<match kubernetes.**>
  @type stdout
</match>
```

- send record

```
echo '{"msg":"hi","kubernetes.container_name":"test"}' | fluent-cat kubernetes.test
```

- result

```
2020-12-23 04:48:16.829295000 +0900 kubernetes.test: {"msg":"hi","kubernetes.container_name":"test","original_tag":"kubernetes.test","app":"test"}
```

In addition, use mailing list instead of github issue first.
