### ISSUE TITLE
out_http self-signed certificate error

### ISSUE THREAD

**Issue by a-b-v** [fluent/fluentd#3214]
**Describe the bug**

With this config

>     <match **>
>       @type http
>       endpoint_url https://xxx.xxx.xxx.xxx:xxxx/
>       tls_verify_mode none
>     </match>

Error arrear:
Net::HTTP.Post raises exception: OpenSSL::SSL::SSLError, 'SSL_connect returned=1 errno=0 state=error: certificate verify failed (self signed certificate)' 

**Expected behavior**

Self-signed certificate check is disabled

**Your Environment**
- Fluentd or td-agent version: `fluentd --version` or `td-agent --version`
 fluentd 1.9.1
- Operating system: `cat /etc/os-release`
NAME="VMware Photon OS"
VERSION="3.0"
(k8s)
- Kernel version: `uname -r`
5.8.7-1.el7.elrepo.x86_64

**Comment by kenhys** [comment]
OT. It seems that `endpoint` is correct. 
ref .https://docs.fluentd.org/output/http#endpoint

**Comment by a-b-v** [comment]
Yes, i use https://github.com/vmware/kube-fluentd-operator with https://github.com/fluent-plugins-nursery/fluent-plugin-out-http. It syntax differ from the standard plugin
