### ISSUE TITLE
Duplicate read for tail

### ISSUE THREAD

**Issue by shenmuxiaosen** [fluent/fluentd#3226]
**Describe the bug**
Under some hardware disk problem, we noticed that Fluentd re-read logs from files that had been processed already. Looks like it lost its position track. The hardware issue can recovered itself and all files in disk persisted. Is there any trace for Fluentd position files that we can dump to debug? In this case, we assume either the position file was evicted or corrupted such that after Fluentd restarted, it read all files again from beginning. 

**To Reproduce**
Not possible as it will be trigger by hardware issue. 

**Expected behavior**
Fluentd should persist its position. 

**Your Environment**

- Fluentd or td-agent version: `1.11.1`
- Operating system: `Ubuntu 16.04.7 LTS`
- Kernel version: `5.4.0-1026-azure`

**Your Configuration**

```
<source>
  @type tail
  path /var/log/containers/*.log
  pos_file /var/log/fluentd-containers.log.pos
  time_key @timestamp
  tag kubernetes.*
  format json
  read_from_head true
</source>
```

**Your Error Log**

```
2021-01-09 01:07:41 +0000 [error]: #0 found broken chunk file during resume. Deleted corresponding files: path="/var/log/td-agent/buffer/out_k8scontainers*.buffer/buffer.b5b86d3526bd7c12640fc5ba40c87d12d.log" mode=:staged err_msg="staged file chunk is empty"
2021-01-09 01:07:41 +0000 [error]: #0 found broken chunk file during resume. Deleted corresponding files: path="/var/log/td-agent/buffer/out_azconfig*.buffer/buffer.q5b86d34bbf0a531bf3e347ffe921b463.log" mode=:queued err_msg="enqueued file chunk is empty"
```

**Additional context**

From Fluentd trace logs, we did see two errors about out buffers. We don't directly use these two buffer files and are they used internally to track out buffer plugin progress? In addition to the duplicate read, we also saw corrupted lines in our own out buffer files. Something like below:
{json line 1}
{json line 2}
{json line {json line 4}}
{json line 5}

**Comment by kenhys** [comment]
> Is there any trace for Fluentd position files that we can dump to debug?

/var/log/fluentd-containers.log.pos file should contain the following line:

```
(FILE_NAME) (OFFSET) (INODE_IN_HEX)
```

If .pos file was corrupted, `OFFSET` may be wrong.
