### ISSUE TITLE
exec input plugin connect_mode read_with_stderr option not keeping stderr

### ISSUE THREAD

**Issue by estebanes22** [fluent/fluentd#3232]
Check [CONTRIBUTING guideline](https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md) first and here is the list to help us investigate the problem.

**Describe the bug**
Using a simple exec input plugin but getting:
"#0 Executing command title=:exec_input spawn=[{}, "echo This message goes to stderr >&2"] mode=[:read_with_stderr] **stderr=:discard**"

**To Reproduce**
Just use the below configuration with any output plugin

**Expected behavior**
I expect fluentd to also collect from stderr

**Your Environment**

- Fluentd or td-agent version: `fluentd container image v1.12.0-1.0 ()` (https://github.com/fluent/fluentd-docker-image/blob/master/v1.10/alpine/Dockerfile)
- Operating system: alpine:3.9
- Kernel version: linux-4.19.26 

If you hit the problem with older fluentd version, try latest version first.

**Your Configuration**

```
<source>
  @type exec
  tag fr
  command "echo This message goes to stderr >&2"
  <parse>
    @type json
  </parse>
  connect_mode read_with_stderr
</source>

```

**Your Error Log**

```
[debug]: #0 Executing command title=:exec_input spawn=[{}, "node /opt/tail.js"] mode=[:read_with_stderr] stderr=:discard
```

**Additional context**

**Comment by kenhys** [comment]
I can't reproduce the same message, but it seems that `@type` is better to use `none` in this case.

```
<source>
  @type exec
  tag fr
  command "echo This message goes to stderr >&2"
  <parse>
    @type none
  </parse>
  connect_mode read_with_stderr
</source>

```

Then, 

```
2021-01-20 10:43:33 +0900 [info]: #0 fluentd worker is now running worker=0
2021-01-20 10:43:33.633325896 +0900 fr: {"message":"This message goes to stderr"}
2021-01-20 10:43:33.632212049 +0900 fluent.info: {"pid":25936,"ppid":25929,"worker":0,"message":"starting fluentd worker pid=25936 ppid=25929 worker=0"}
2021-01-20 10:43:33.632889422 +0900 fluent.info: {"worker":0,"message":"fluentd worker is now running worker=0"}
```

**Comment by repeatedly** [comment]
Maybe, the issue author thinks debug message should be not `discard`?

**Comment by estebanes22** [comment]
Correct - it says discard and also I don't see any stderr logs picked up by fluentd.
