### ISSUE TITLE
Keys with forward slash are not accessible 

### ISSUE THREAD

**Issue by 123BLiN** [fluent/fluentd#3235]
**Describe the bug**
Key names that has forward slash inside are not accessible from fluentd plugins and methods
exmaple key: `kubernetes.labels.app-kubernetes-io/name` (after dedot) or `kubernetes.labels.app.kubernetes.io/name`
and any other kubernetes labels, this makes it hard to use kubernetes metadata in log forwarding and routing, escpecially when one try to use https://github.com/uken/fluent-plugin-elasticsearch#dynamic-configuration based on kube app name.

**To Reproduce**
try to use key with forward slash with any plugin or maybe even core functionality

**Expected behavior**
Keys should be accessible as any others 

**Your Environment**

- Fluentd or td-agent version: `fluentd 1.11.4`
- Operating system: `docker`
- Kernel version: `5.3.0-1032-aws`

If you hit the problem with older fluentd version, try latest version first.

**Your Configuration**

```
  <filter **>
    @type record_transformer
    @id clusterflow:logging:traefik-flow:3
    <record>
      kubernetes.labels.app_name record["kubernetes"]["labels"]["app-kubernetes-io/name"]
    </record>
  </filter>
```
or 
```
  <match kubernetes.**>
    @type tag_normaliser
    @id clusterflow:logging:traefik-flow:0
    format ${namespace_name}.${labels.app.kubernetes.io/name}
  </match>

```

**Your Error Log**

None, it just does not work as expected

**Additional context**

https://github.com/banzaicloud/fluent-plugin-tag-normaliser/issues/2

**Comment by repeatedly** [comment]
Your `record_transformer` is wrong. You need to use `${}` for accessing `record` and need to use `enable_ruby true` for nesting access.

See https://docs.fluentd.org/filter/record_transformer#less-than-record-greater-than-directive and https://docs.fluentd.org/filter/record_transformer#enable_ruby

I tested following configuration and it works.

```
# record_transformer version
<filter test.**>
  @type record_transformer
  enable_ruby true
  <record>
    kubernetes.labels.app_name1 ${record["kubernetes"]["labels"]["app-kubernetes-io/name"]}
  </record>
</filter>

# record_modifier version
<filter test.**>
  @type record_modifier
  <record>
    kubernetes.labels.app_name2 ${record["kubernetes"]["labels"]["app-kubernetes-io/name"]}
  </record>  
</filter>
```

`tag-normaliser` is 3rd party plugin so it is outside scope of this repository. Closed.

**Comment by 123BLiN** [comment]
@repeatedly thank you!! I spent two days crawling trough issues and docs to find a way to address nested records, follow up question - does `enable_ruby` brings any performance hit?
