### ISSUE TITLE
Td-agent sending weird characters to fluentd through forward

### ISSUE THREAD

**Issue by tliuzhi** [fluent/fluentd#3242]
Check [CONTRIBUTING guideline](https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md) first and here is the list to help us investigate the problem.

**Describe the bug**
I am facing a situation where i am seeing weird characters in fluentd stdout at log aggreggator after forwarding. I have a log forwarding sending system logs through ELB to a log aggregator. I am able to send and receive the logs at the host (log aggregator) but i am seeing the logs becoming

2021-02-03 02:53:34.108878888 +0000 syslog.tcp: {"syslog_message":"��testlogs�\u0000\u0000\u0002�
 2:53:29:291 UTC] 00000092 WebContainer  E com.ibm.ws.xx.xx.WebContainer handleRequest SRVE02
gin/homepage has not been defined.��\u0000`\u0012��",
![image](https://user-images.githubusercontent.com/44491585/106699147-41dcb480-661d-11eb-8347-cf00aedf58a8.png)

The logs through stdout at the log forwarder looks perfectly fine without these weird characters so could anyone help to explain on why are there these weird characters showing.

would appreciate if anyone can help me on this. Thank you.

**Your environment**
td-agent 1.10.2

**Your configuration**
```
<source>
  @type tail 
  path /opt/IBM/WebSphere/AppServer/xx/logtest
  pos_file /opt/IBM/WebSphere/AppServer/xx/logtest.pos
 tag testlogs
 <parse>
  @type none
 </parse>
 <match testlogs**>
   @type forward
    <server>
       host xxx.elb.xxx.xxx.amazonaws.com
       port xxx
    </server>
</match>
```

**Comment by kenhys** [comment]
It seems that the logging message and your configuration do not match for the forwarder.
Then there is no aggregator configuration.

**Comment by tliuzhi** [comment]
Hi, the image attached is a reference. I’m able to see the logs from the
aggregator side but there are weird characters showing up. I would like to
seek help on why are the weird characters showing. Thank you.

**Comment by tliuzhi** [comment]
> It seems that the logging message and your configuration do not match for the forwarder.
> Then there is no aggregator configuration.
 
my aggregator configuration is 


```
<source>
  @type tcp
  port xxx
  bind 0.0.0.0
  tag syslog.tcp
  <parse>
   @type none
   message_key syslog_message
  </parse>
</source>
<match syslog.tcp>
  @type stdout
</match>

```

**Comment by kenhys** [comment]
Forwarder configuration:
encoding option may help [1]
https://docs.fluentd.org/input/tail#encoding-from_encoding

Aggregator configuration:

(A bit off topic) @type forward is recommended [2]
https://docs.fluentd.org/input/forward

**Comment by tliuzhi** [comment]
> Forwarder configuration:
> encoding option may help [1]
> https://docs.fluentd.org/input/tail#encoding-from_encoding
> 
> Aggregator configuration:
> 
> (A bit off topic) @type forward is recommended [2]
> https://docs.fluentd.org/input/forward

hey thank you, i managed to solve it by using @type forward, but may i know why does @type tcp doesnt work the same?

**Comment by repeatedly** [comment]
forward output/input uses own protocol. See https://docs.fluentd.org/input/forward

in_tcp doesn't design for forward protocol.

**Comment by kenhys** [comment]
The issue was resolved.
