### ISSUE TITLE
RPC Signal SIGUSR2 unreloadable 

### ISSUE THREAD

**Issue by toan-hf** [fluent/fluentd#3244]
**Describe the bug**
I am using the latest FluentD (1.12) through the docker image [Debian-GrayLog](https://github.com/fluent/fluentd-kubernetes-daemonset/tree/master/docker-image/v1.12/debian-graylog)

Enabled RPC with the hope to bring more resilient for the FluentD configuration. However when i used the SIGUSR2 to reload the process when the new configuration added, i got the error

```
2021-02-03 06:56:59 +0000 [error]: Failed to reload config file: Unreloadable plugin plugin: gelf, plugin_id: object:3fd25a43ab90, class_name: Fluent::GELFOutput)
```
The process could not reload properly.

I am not sure this error 100% relates to SIGUSR2 FluentD Signal itself or It was a apart for [GELF OutPut plugin](https://github.com/hotschedules/fluent-plugin-gelf-hs) which i am using 

what is the best way to fix the issue ?

**To Reproduce**

- Use the latest docker image `fluentd-kubernetes-daemonset:v1.12-debian-graylog-1`
- Enable RPC in <system> 
- Use Curl to hit into the endpoint `/api/config.gracefulReload`
- Kubectl logs to see the error 

**Expected behavior**
It should be reloaded successfully 

**Your Environment**

```
fluentd --version
fluentd 1.12.0
```

```EKS Kubernetes 1.18.9```

**Your Configuration**

```
system>
  workers 2
  rpc_endpoint 127.0.0.1:24724
  ignore_same_log_interval 60s
  ignore_repeated_log_interval 60s
</system>
```

**Your Error Log**

```
2021-02-03 06:56:59 +0000 [error]: Failed to reload config file: Unreloadable plugin plugin: gelf, plugin_id: object:3fd25a43ab90, class_name: Fluent::GELFOutput)
```

**Comment by kenhys** [comment]
It is reproducible without fluentd-kubernetes-daemonset image:

```
$ docker run --name mongo -d mongo:4.2
$ docker run --name elasticsearch \
    -e "http.host=0.0.0.0" \
    -e "discovery.type=single-node" \
    -e "ES_JAVA_OPTS=-Xms512m -Xmx512m" \
    -d docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.0
$ docker run --name graylog --link mongo --link elasticsearch \
    -p 9000:9000 -p 12201:12201 -p 1514:1514 \
    -e GRAYLOG_HTTP_EXTERNAL_URI="http://127.0.0.1:9000/" \
    -d graylog/graylog:4.0
$ fluentd -c fluent.conf
```

fluent.conf:

```
<system>
  workers 1
  rpc_endpoint 0.0.0.0:24724
  ignore_same_log_interval 60s
  ignore_repeated_log_interval 60s
  log_level debug
</system>

<worker 0>
  <source>
    @type tail
    path sample.json
    <parse>
      @type json
    </parse>
    tag sample
  </source>
</worker>

<match **>
  @type gelf
  host localhost
  port 12201
</match>
```

**Comment by kenhys** [comment]
It seems that https://github.com/hotschedules/fluent-plugin-gelf-hs is not reloadable plugin.

**Comment by toan-hf** [comment]
@kenhys can you please point ne an example plugin which is supporting reloadable, i can create the upstream following them

**Comment by kenhys** [comment]
I don't know a good example of reloadable plugin.

FYI: It depends on `reloadable_plugin?`
https://github.com/fluent/fluentd/blob/master/lib/fluent/plugin/base.rb#L191-L194

So, it may be able to make it reloadable by overriding `reloadable_plugin?`, but I'm not sure it works as expected.

**Comment by repeatedly** [comment]
For new features, plugins should use v1 plugin API.
fluent-plugin-gelf-hs still uses v0.12 plugin API.

**Comment by kenhys** [comment]
As this is a plugin issue, I'll close it.

(I want to forward the issue, but it seems upstream explicitly disables it :disappointed: )
