### ISSUE TITLE
HTTP output plugin doesn't honor some HTTP response codes as retryable

### ISSUE THREAD

**Issue by mgcdeltarisk** [fluent/fluentd#3245]
Check [CONTRIBUTING guideline](https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md) first and here is the list to help us investigate the problem.

**Describe the bug**
When specifying `retryable_reponse_codes` for the HTTP output plugin, some response codes are not retried but fail permanently.  The ones we observed with this behavior were `404` and `500`.

**To Reproduce**
Set `retryable_response_codes = [404, 500, 502, 503, 504]` in the fluent.conf. Have the HTTP server return a `404` or `500`.

**Expected behavior**
All specified response codes should be retried

**Your Environment**

- Fluentd or td-agent version:
```
/ # fluentd --version
fluentd 1.12.0
```

- Operating system: 
```
# cat /etc/os-release 
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.12.3
PRETTY_NAME="Alpine Linux v3.12"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://bugs.alpinelinux.org/"
```

- Kernel version: `uname -r`
```
/ # uname -r
4.19.0-13-amd64
```

If you hit the problem with older fluentd version, try latest version first.

**Your Configuration**

```
<match my.events>
  @type http

  endpoint "https://url.com/v1?<redacted>=<redacted>"
  http_method post

  content_type json(json_array: false)
#Unfortunately 404 and 500 codes are not retried but immediately dumped to the secondary file
  retryable_response_codes = [404, 500, 502, 503, 504]
  retry_forever true

<secondary>
  @type secondary_file
  directory /shared/logs_1/error
  basename dump.${chunk_id}
</secondary>

  # every 10 minutes or every 1 Megs
  <buffer time>
    @type file
    path /shared/logs_1/buffer/fake_dir_name
    timekey 10m
    timekey_wait 0m
    timekey_use_utc true
    chunk_limit_size 75k
    compress gzip
    total_limit_size 90GB
    overflow_action drop_oldest_chunk
  </buffer>

  <format>
    @type json
    add_newline true
  </format>
</match>
```

**Your Error Log**

```
2021-02-01 21:00:01 +0000 [warn]: #0 got unrecoverable error in primary. Skip retry and flush chunk to secondary error_class=Fluent::UnrecoverableError error="500 Internal Server Error POST request for /"
2021-02-02 18:40:00 +0000 [warn]: #0 got unrecoverable error in primary. Skip retry and flush chunk to secondary error_class=Fluent::UnrecoverableError error="404 Not Found POST request for /"
```

**Additional context**

**Comment by repeatedly** [comment]
`retryable_response_codes = [404, 500, 502, 503, 504]` is typo?
`retryable_response_codes [404, 500, 502, 503, 504]` is right format.
