### ISSUE TITLE
Dynamic credentials for a fluentd http output plugin

### ISSUE THREAD

**Issue by guru1306** [fluent/fluentd#3249]
Check [CONTRIBUTING guideline](https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md) first and here is the list to help us investigate the problem.

**Is your feature request related to a problem? Please describe.**
The credentials for the HTTP server changes every 24 hours. The credentials can be fetched from another service running in the same Kubernetes cluster.  As of now, the fluentd http plugin supports only static credentials

**Describe the solution you'd like**

Change the HTTP output plugin to query and get the token from the external endpoint and use it while sending the logs to the  HTTP server.

**Describe alternatives you've considered**

I have modified the code of fluentd out plugin to deploy the same. Do you think it's a valid requirement? If so, I can contribute the code to fluentd plugin

**Comment by kenhys** [comment]
It is a good thing to try to contribute code. 
How about publishing as fluent-plugin-xxx for the moment?
If the plugin is ready to contribute (good enough test case and got popularity), then you can send PR as a next step.

**Comment by guru1306** [comment]
Thanks. I will publish it as a separate plugin.

**Comment by hafkaM** [comment]
Hello. Will this feature be part of the http plugin?
Thanks.
