### ISSUE TITLE
Duplicate data is stored in when transferring from csv records to mongodb

### ISSUE THREAD

**Issue by amartyarooney** [fluent/fluentd#3254]
**Describe the bug**
Duplicate data is stored when transferring from csv records to MongoDB whenever the csv file is updated

**To Reproduce**

**Expected behavior**
As I used ```follow_inodes true`` command to avoid log duplication by log rotation. it still is getting the same error
**Your Environment**

- Fluentd or td-agent version: td-agent .11.1`
- Operating system: mac os catalina
- Kernel version: 10.15.6

**Your Configuration**

```
<!-- <source>
  @type tail
  path  /var/log/pmta_logs/pmta.*/acct*
  pos_file /var/log/pmta_logs/pmta.pos
  tag mtag.pmta
  follow_inodes true
  <parse>
    @type csv
    keys type, timeLogged, name , class , subject
    time_key timeLogged
  </parse>
</source>


<match mtag.pmta>
  @type mongo
  database smtp
  collection temp
  user jonas
  password 123456
</match>
 -->
```

**Your Error Log**

```
<!-- Write your **ALL** error log here -->
```

**Additional context**

**Comment by repeatedly** [comment]
`follow_inode` is supported since v1.12.0: https://github.com/fluent/fluentd/blob/master/CHANGELOG.md#release-v1120---20210105
Please upgrade your fluentd to latest.

**Comment by amartyarooney** [comment]
> `follow_inode` is supported since v1.12.0: https://github.com/fluent/fluentd/blob/master/CHANGELOG.md#release-v1120---20210105
> Please upgrade your fluentd to latest version.
i updated my td-agent with command `yum update td-agent` but `version 1.11.5` got installed instead of 1.12
