### ISSUE TITLE
The log collected by Fluentd is not the original log of POD and cannot be queriednormally in Kibana ？？

### ISSUE THREAD

**Issue by zhangdaopin** [fluent/fluentd#3280]
Check [CONTRIBUTING guideline](https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md) first and here is the list to help us investigate the problem.

**Describe the bug**

When we visited the Kibana console, we found that the log presentation was not what we expected;What we want is some of the logs selected in the screenshot, but they seem to be included in the log key field and cannot be shown separately 
 
**To Reproduce**

![image](https://user-images.githubusercontent.com/24818052/110058665-b4b48900-7d9d-11eb-97a2-2ecd4ddaea57.png)

**Expected behavior**

I want to filter the above JSON format log by fluentd configuration, take out the value of 'log' field, and push it to ES to DE on Kibana

**Your Environment**

```yaml
apiVersion: v1
appVersion: 1.9.2
description: A Fluentd Helm chart for Kubernetes
keywords:
  - fluentd
  - data
  - log
maintainers:
name: belk-fluentd
version: 4.6.1
```
 
**Your Configuration**

```aconf
# read logs from k8s containers
<source>
  @type tail
  path /var/log/containers/*.log
  read_from_head true
  pos_file /var/log/fluentd-container-log.pos
  time_format %Y-%m-%dT%H:%M:%S
  tag kubernetes.*
  format json
</source>

# rewrite_tag_filter does not support nested fields like
# kubernetes.container_name, so this exists to flatten the fields
# and use them in rewrite_tag_filter
<filter kubernetes.**>
  @type record_transformer
  enable_ruby true
  <record>
    pod-name ${record["kubernetes"]["pod_name"]}
    namespace ${record["kubernetes"]["namespace_name"]}
    tenant_msgtype ${record["kubernetes"]["namespace_name"]}.${record["type"]}
    test_name1 ${["AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"]}
    test_name2 ${record["log"]}.${"message"}
  </record>
</filter>
 
```

**Your Error Log**

```
Our configuration of Fluentd;（Or do we need to modify the relevant configuration of Fluentd to fix this problem?）
I tried to modify part of the configuration information of fluentd, but it did not work. I wonder if there is something wrong with the syntax...
```

**Additional context**

Fluentd collects the log files as follows:

```
{
    "log": "
{\"thread\":\"cluster1-nio-worker-0\",\"level\":\"DEBUG\",\"loggerName\":\"com.datastax.driver.core.Connection\",**\"message\":\"Connection[/xxx.xx.xx.xxx:9042-1, inFlight=0, closed=false] heartbeat query succeeded\"**,\"endOfBatch\":false,\"loggerFqcn\":\"org.apache.logging.slf4j.Log4jLogger\",\"instant\":
{\"epochSecond\":1614820748,\"nanoOfSecond\":794000000}
,\"contextMap\":{},\"threadId\":11,\"threadPriority\":5,\"timestamp\":\"2021-03-04 01:19:08.794\",\"host\":\"ip-xxx.xx.xx.xxx\",\"system\":\"zzz-server\",\"systemid\":\"zzzserver-r4hxm\"}\r\n",
    "stream": "stdout",
    "time": "2021-03-04T01:19:08.794491974Z"
}
```

**Comment by kenhys** [comment]
I'm not sure what expected well, but does it work for you to extract `message` field?

```
<filter kubernetes.**>
  @type record_transformer
  enable_ruby true
  <record>
    test_name2 ${JSON.parse(record['log'])['message']}
  </record>
</filter>
```

**Comment by cosmo0920** [comment]
> **\"message\":\"Connection[/xxx.xx.xx.xxx:9042-1, inFlight=0, closed=false] heartbeat query succeeded\"**

"message" field seems to be used custom format not JSON.
You need to write down some custom parser to handle this custom format.

**Comment by cosmo0920** [comment]
`message` field can be handled with the following parser:

```ruby
require 'fluent/plugin/parser'

module Fluent
  module Plugin
    class CustomParser < Parser
      Plugin.register_parser('custom', self)

      REGEXP = /^(?<header>.*)\[(?<ipaddress>[^ ]*), (?<inflight>[^ ]*), (?<closed>[^ ]*)\] (?<message>.*)$/
      def initialize
        super
      end

      def configure(conf)
        super
      end

      def patterns
        {'format' => REGEXP}
      end

      def parse(text)
        m = REGEXP.match(text)
        unless m
          yield nil, nil
          return
        end

        header = m['header']
        ipaddress = m['ipaddress']
        inflight = m['inflight'].split('=').last
        closed = m['closed'].split('=').last

        record = {}
        record[header] = {
          "ipaddress" => ipaddress,
          "inflight" => inflight,
          "closed" => closed,
        }

        yield Fluent::Engine.now, record
      end
    end
  end
end
```

And then, message field should be parsed with the following configuration:

```aconf
<filter kubernetes.**>
  @type parser
  key_name log
  <parse>
    @type json
  </parse>
</filter>
<filter kubernetes.**>
  @type parser
  key_name message
  reserve_data true
  <parse>
    @type custom
  </parse>
</filter>
<filter kubernetes.**>
  @type record_transformer
  remove_keys message
</filter>
```

Then, the sample log:

```log
{
    "log": "
{\"thread\":\"cluster1-nio-worker-0\",\"level\":\"DEBUG\",\"loggerName\":\"com.datastax.driver.core.Connection\",**\"message\":\"Connection[/xxx.xx.xx.xxx:9042-1, inFlight=0, closed=false] heartbeat query succeeded\"**,\"endOfBatch\":false,\"loggerFqcn\":\"org.apache.logging.slf4j.Log4jLogger\",\"instant\":
{\"epochSecond\":1614820748,\"nanoOfSecond\":794000000}
,\"contextMap\":{},\"threadId\":11,\"threadPriority\":5,\"timestamp\":\"2021-03-04 01:19:08.794\",\"host\":\"ip-xxx.xx.xx.xxx\",\"system\":\"zzz-server\",\"systemid\":\"zzzserver-r4hxm\"}\r\n",
    "stream": "stdout",
    "time": "2021-03-04T01:19:08.794491974Z"
}
```

will be parsed as follows:

```json
{"thread":"cluster1-nio-worker-0","level":"DEBUG","loggerName":"com.datastax.driver.core.Connection","endOfBatch":false,"loggerFqcn":"org.apache.logging.slf4j.Log4jLogger","instant":{"epochSecond":1614820748,"nanoOfSecond":794000000},"contextMap":{},"threadId":11,"threadPriority":5,"timestamp":"2021-03-04 01:19:08.794","host":"ip-xxx.xx.xx.xxx","system":"zzz-server","systemid":"zzzserver-r4hxm","Connection":{"ipaddress":"/xxx.xx.xx.xxx:9042-1","inflight":"0","closed":"false"}}
```

**Comment by zhangdaopin** [comment]
> I'm not sure what expected well, but does it work for you to extract `message` field?

Yes, we want to extract the message field from the log, present it in the Kibana interface and make it easier for us to query and locate the problem

**Comment by zhangdaopin** [comment]
@cosmo0920 Sorry ... I'm not quite sure where or in which directory should the configuration file of this part of the resolution be placed?
`require 'fluent/plugin/parser'

module Fluent
  module Plugin
    class CustomParser < Parser
      Plugin.register_parser('custom', self)

      REGEXP = /^(?<header>.*)\[(?<ipaddress>[^ ]*), (?<inflight>[^ ]*), (?<closed>[^ ]*)\] (?<message>.*)$/
      def initialize
        super
      end

      def configure(conf)
        super
      end

      def patterns
        {'format' => REGEXP}
      end

      def parse(text)
        m = REGEXP.match(text)
        unless m
          yield nil, nil
          return
        end

        header = m['header']
        ipaddress = m['ipaddress']
        inflight = m['inflight'].split('=').last
        closed = m['closed'].split('=').last

        record = {}
        record[header] = {
          "ipaddress" => ipaddress,
          "inflight" => inflight,
          "closed" => closed,
        }

        yield Fluent::Engine.now, record
      end
    end
  end
end`

**Comment by kenhys** [comment]
put `.rb` under PATH_TO_FLUENTD_GEM_DIR/lib/fluent/plugin.

**Comment by kenhys** [comment]
I'll close this issue because it will be resolved by the custom parser.
