### ISSUE TITLE
Environment variable not evaluated when using `@include` directive

### ISSUE THREAD

**Issue by sgohl** [fluent/fluentd#3284]
**Describe the bug**

I need different fluent configurations per different environments and want to set the config to be included by setting an environment variable while all sharing the same source config to prevent code duplication:

```
<source>
  @type forward
  port 24224
</source>

@include /fluentd/config.d/"#{ENV['ENVIRONMENT']}".conf
```

Fluent logs on startup:

```
/usr/lib/ruby/2.5.0/uri/rfc3986_parser.rb:67:in `split': bad URI(is not URI?): /fluentd/config.d/"#{ENV['ENVIRONMENT']}".conf (URI::InvalidURIError)
```

**Expected behavior**

variable to be evaluated as used to

**Your Environment**

- docker.io/fluent:latest

**Comment by cosmo0920** [comment]
You should quote entire string after `@include`.

```aconf
<source>
  @type forward
  port 24224
</source>

@include "/fluentd/config.d/#{ENV['ENVIRONMENT']}.conf"
```

Otherwise, environment variable interpolation is failed.
