### ISSUE TITLE
Fluentd does not start after installing plugins (Linux bare metal)

### ISSUE THREAD

**Issue by wirowka** [fluent/fluentd#3293]
Check [CONTRIBUTING guideline](https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md) first and here is the list to help us investigate the problem.

**Describe the bug**
After installing plugins (any) using fluent-gem, e.g.:
./fluent-gem install fluent-plugin-out-http
fluentd does not start (configured as Linux service) and writes:

Mar 15 08:09:17 l-pdtmon-t01 systemd[1]: td-agent.service holdoff time over, scheduling restart.
Mar 15 08:09:17 l-pdtmon-t01 systemd[1]: Stopped td-agent: Fluentd based data collector for Treasure Data.
Mar 15 08:09:17 l-pdtmon-t01 systemd[1]: Starting td-agent: Fluentd based data collector for Treasure Data...
Mar 15 08:09:17 l-pdtmon-t01 fluentd[22717]: [22717, #<Thread:0x00007f923679edf0 run>, #<Errno::EACCES: Permission denied @ rb_sysopen - /opt/td-agent/lib/ruby/gems/2.7.0/specifications/fluent-plugin-out-http-1.3.3.gemspec>, ["/opt/td-ag
Mar 15 08:09:17 l-pdtmon-t01 systemd[1]: td-agent.service: control process exited, code=exited status=1
Mar 15 08:09:17 l-pdtmon-t01 systemd[1]: Failed to start td-agent: Fluentd based data collector for Treasure Data.
Mar 15 08:09:17 l-pdtmon-t01 systemd[1]: Unit td-agent.service entered failed state.
Mar 15 08:09:17 l-pdtmon-t01 systemd[1]: td-agent.service failed.
Mar 15 08:09:17 l-pdtmon-t01 systemd[1]: td-agent.service holdoff time over, scheduling restart.
Mar 15 08:09:17 l-pdtmon-t01 systemd[1]: Stopped td-agent: Fluentd based data collector for Treasure Data.
Mar 15 08:09:17 l-pdtmon-t01 systemd[1]: start request repeated too quickly for td-agent.service
Mar 15 08:09:17 l-pdtmon-t01 systemd[1]: Failed to start td-agent: Fluentd based data collector for Treasure Data.
Mar 15 08:09:17 l-pdtmon-t01 systemd[1]: Unit td-agent.service entered failed state.
Mar 15 08:09:17 l-pdtmon-t01 systemd[1]: td-agent.service failed.
[
**To Reproduce**
Install a plugin and attempt to start the Linux service.
./fluent-gem install fluent-plugin-out-http
systemctl start td-agent

**Expected behavior**
Fluentd shall start without any issue.
After changing ownership of everything under /opt/td-agent/:
chown -R td-agent:td-agent *
Fluentd starts successfully.

**Your Environment**
td-agent-4.1.0-1.el7.x86_64
[root@l-pdtmon-t01 td-agent]# uname -r
3.10.0-1160.15.2.el7.x86_64
[root@l-pdtmon-t01 td-agent]# cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.9 (Maipo)

**Comment by kenhys** [comment]
```
$ sudo ./fluent-gem install fluent-plugin-out-http
```

it installs gem under `/opt/td-agent/lib/ruby/gems/2.7.0/gems/fluent-plugin-out-http-1.3.3/` with root:root but it does not
affects to start fluent.
