### ISSUE TITLE
fluentd can't access /var/log/audit/audit.log as non-root user

### ISSUE THREAD

**Issue by IronSideSec** [fluent/fluentd#3301]
Check [CONTRIBUTING guideline](https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md) first and here is the list to help us investigate the problem.

**Describe the bug**
fluentd can't access /var/log/audit/audit.log as non-root user

**To Reproduce**
Attempt to read audit.log as non-root user using the provided config

**Expected behavior**
fluentd being able to access logs

**Your Environment**

- Fluentd or td-agent version: `td-agent 1.11.5`
- Operating system: `Red Hat Enterprise Linux 8.2 (Ootpa)`
- Kernel version: `4.18.0-193.47.1.el8_2.x86_64`

If you hit the problem with older fluentd version, try latest version first.

**Your Configuration**

```
<source>
  @type tail
  path /var/log/audit/audit.log
  pos_file /var/log/td-agent/audit.pos
  tag syslog.audit
  <parse>
    @type none 
  </parse>
</source>

<MATCH SENTINEL.**>
    @TYPE AZURE-LOGANALYTICS
    CUSTOMER_ID  # my ID
    SHARED_KEY # my key 
    LOG_TYPE syslog.audit
</MATCH> 
```

**Your Error Log**

```
[error]: #0 unexpected error error_class=Errno::EACCES error="Permission denied @ rb_file_s_stat - /var/log/audit/audit.log"
```

**Comment by ashie** [comment]
It's not a bug. 
You need to tune the permission.
e.g.) Modify `log_group` in /etc/audit/auditd.conf

**Comment by ashie** [comment]
BTW fluentd has Linux's Capability support as of v1.12.0.

**Comment by cosmo0920** [comment]
Attach Linux's capability: `CAP_DAC_READ_SEARCH` or `CAP_DAC_OVERRIDE` is one approach.
