### ISSUE TITLE
Unable to install td-agend v4.1.0 on non-English Windows machine without workaround

### ISSUE THREAD

**Issue by joweich** [fluent/fluentd#3322]
**Describe the bug**
When installing td-agent v4.1.0 on my Windows 10 machine via td-agent-4.1.0-x64.msi setup file, i ran into following error:

_"An Error occurred while applying security settings. Users is not a valid user or group. This could be a problem with the package, or a problem connecting to a domain controller on the network. Check your network connection and click Retry, or Cancel to end the install."_

Refering to [Link](https://support.gaaiho.com/hc/en-us/articles/201023667-Error-1609-while-applying-security-settings-Users-is-not-valid-group-), i was able to identify the cause of the problem as my systems language is non-English. Creating 3 Windows subgroups named _Administrators_, _Users_ and _CREATOR OWNER_ solved the installation issue for me.

Another workaround is to install td-agent v4.0.1, which doesn't seem to cause this problem.

**To Reproduce**
Try to install td-agent v4.1.0 via td-agent-4.1.0-x64.msi on non-English/German Windows 10 system.

**Expected behavior**
Successfull installation without using the workaround described.

**Your Environment**

- td-agent setup file: td-agent-4.1.0-x64.msi
- Windows 10.0.18363 Build 18363
- Locale: Germany

**Comment by kenhys** [comment]
> Another workaround is to install td-agent v4.0.1, which doesn't seem to cause this problem.

This was caused by this commit https://github.com/fluent-plugins-nursery/td-agent-builder/commit/6f9cb6393392d62caa99907c0ebbcbab6b94a3f1, using sid may be better. I'll try.

**Comment by kenhys** [comment]
Hi, @joweich 
Does it work without using the workaround? 
https://github.com/kenhys/td-agent-builder/releases/download/fluentd-3322-rc1/td-agent-4.1.0-x64.msi

I want to know  whether https://github.com/fluent-plugins-nursery/td-agent-builder/pull/289 is the right fix or not.

**Comment by joweich** [comment]
Hi @kenhys, 
after removing the previous installation and the created windows groups, this does indeed fix the issue for me.
Thank you very much!

**Comment by kenhys** [comment]
@joweich Thanks for testing!

**Comment by kenhys** [comment]
@joweich 

FYI: It is not determined yet, but it will be merged  to td-agent 4.1.1  (if test pass)

**Comment by ashie** [comment]
The fix is merged in td-agent 4.1.1
