### ISSUE TITLE
Unrecognized log date

### ISSUE THREAD

**Issue by Hello-Linux** [fluent/fluentd#3326]
**Describe the bug**
My log is below
```
[12/Apr/2021:15:30:20 +0800] 1618212620 100.97.166.76 28754
```
and I capture the date field "12/Apr/2021:15:30:20 +0800" for logtime，but kibana show his type is text, Why not time type ?
Does fluentd support this date format? 

**Your Environment**

- td-agent version: 4.1
- Operating system: centos7.6
- Kernel version: 3.10

**Your Configuration**
my parse config is below 
```
<parse>
    @type multiline
    format_firstline /^---\w{8}---A--/
    format1 /---(?<mod_id>\w{8})---A--.*\[(?<logtime>.*0800)\](?<content>.*)/
    keep_time_key true
    time_key logtime
    localtime true
    time_type string
    timezone "+0800"
    time_format "%d/%b/%Y:%H:%M:%S %z"
  </parse>
```

**Additional context**

And I open kibana, the logtime field not time type but text type.
the picture is show this
![2021-04-12 16-46-18 的屏幕截图](https://user-images.githubusercontent.com/17851645/114368090-aa14bd00-9baf-11eb-9c95-a5cc252dac28.png)

![2021-04-12 16-47-02 的屏幕截图](https://user-images.githubusercontent.com/17851645/114368067-a4b77280-9baf-11eb-9f82-23a257cd0427.png)

**Comment by repeatedly** [comment]
It is expected behavior because you use `keep_time_key true`.
The problem is you don't specify proper date format in elasticsearch mapping.
Check ES document first: https://www.elastic.co/guide/en/elasticsearch/reference/current/date.html
