### ISSUE TITLE
[Windows] Fluentd lock log files on EKS

### ISSUE THREAD

**Issue by dotsuber** [fluent/fluentd#3334]
Hi,
I'm using Fluentd version 1.12.2 and sometimes I experience pods stuck on "terminating" status for a while in EKS on Windows VMs. The root cause is a failure in deletion of log file.
I found that [thread](https://github.com/fluent/fluent-bit/issues/2133) which describes a bug in Fluent-bit which locks the log files.
I checked if that is the same root cause in my case, and it is: when I delete the Fluentd pod, the "terminating" pod, successfully deleted.
Is there same fix for Fluentd like in Fluent-bit? If so, what version should I use? If there isn't, can we have one please?
Thanks a lot!

**Comment by smil2k** [comment]
fyi. https://github.com/fluent/fluent-bit/issues/4523
