### ISSUE TITLE
Presence of trace.id and newrelic.guids in logs causes duplicate NR service being created upon fluent-bit modification

### ISSUE THREAD

**Issue by ostrolucky** [fluent/fluentd#3349]
**Describe the bug**
Please see following screenshots:

<table>
<tr>
<td>
<a href="https://user-images.githubusercontent.com/496233/115865868-2ffaf880-a439-11eb-82aa-6d0b3362f60f.png">
<img src="https://user-images.githubusercontent.com/496233/115865868-2ffaf880-a439-11eb-82aa-6d0b3362f60f.png" width=200></a>
</td>
<td>
<a href="https://user-images.githubusercontent.com/496233/115865884-338e7f80-a439-11eb-82a1-9ec18bc786a3.pn">
<img src="https://user-images.githubusercontent.com/496233/115865868-2ffaf880-a439-11eb-82aa-6d0b3362f60f.png" width=200></a>
</td>
<td>
<a href="https://user-images.githubusercontent.com/496233/115865900-3a1cf700-a439-11eb-97fe-272dd0039744.png">
<img src="https://user-images.githubusercontent.com/496233/115865900-3a1cf700-a439-11eb-97fe-272dd0039744.png" width=200></a>
</td>
</tr>
</table>

Fluent-bit is creating duplicate, "Integration-reported services" (instead of "Service" being reused).

**To Reproduce**
This happens in various scenarious involving `newrelic.guids. I reproduced this so far in following scenarios:
- When log entry contains both newrelic.guids  and trace.id
  - If fluent-bit is configured to add `service_name`
  - Or if fluent-bit is configured to set `newrelic.guids`
- When log entry contains `trace.id` only
  - If fluent-bit is configured to add `newrelic.guids`.

**Expected behavior**
"Integration-reported services" should not have been created.

**Your Environment**

- Fluentd or td-agent version: `Fluent Bit v1.7.2`
- Operating system: `Debian GNU/Linux 10 (buster)`
- Kernel version: `4.19.0-14-amd64`

**Your Configuration**

```
[INPUT]
    Name     tail
    Tag      app.backoffice-customer
    Path     /home/backoffice-customer/deployer/current/var/log/*.log
    Exclude_Path *_slow.log,*dev.log
    Path_Key Logfile
    Db       /opt/td-agent-bit/backoffice-customer.db
    Skip_Long_Lines On

[FILTER]
    Name  modify
    Match app.backoffice-customer
    Add entity.guid MzA4NjkzMXxBUE18QVBQTElDQVRJT058NjY5NjM2NTEy
```

**Your Log**

```
{"message":"Command \"{command}\" exited with code \"{code}\"","context":{"command":"app:orders:import","code":401},"level":100,"level_name":"DEBUG","channel":"console","datetime":{"date":"2021-04-23 13:40:01.978478","timezone_type":3,"timezone":"Europe/Berlin"},"extra":{"uid":"cf428a8"},"trace.id":"a0ce17a1cead3d45"}
```

**Comment by cosmo0920** [comment]
This issue should be for fluent-bit. This repository is FLUENTD not FLUENT BIT.
Closing this for now.
