### ISSUE TITLE
Dynamically set CSV keys

### ISSUE THREAD

**Issue by Nessumsar** [fluent/fluentd#3370]
**Is your feature request related to a problem? Please describe.**
I would request a possibility to inject CSV keys dynamically. I'm all up for trying some other way if you know some way to do this. I've looked in slack, discussion forum, stackoverflow, GH issues here etc. with no results.
I attempted to send a list of keys through a HTTP header since this is the way I pass data to transform my records. I don't want to hardcode my keys since that would result in having a huge amount of endpoints for different CSV types. Maybe this is a bit out of the scope of fluentd but I thought I'd give it a shot.
This is my config.

```
<source transform.csv>
  @type http
  @id http_csv_transform
  port 8889
  add_http_headers true
  <parse>
    @type csv
    keys ${record["HTTP_X_COLUMNS"]}
    delimiter ;
  </parse>
</source>
<filter transform.csv>
  @type record_transformer
  enable_ruby true
  <record>
    docType ${record["HTTP_X_DOCTYPE"]}
    baseType ${record["HTTP_X_BASETYPE"]}
    type ${record["HTTP_X_TYPE"]}
    source ${record["HTTP_X_SOURCE"]}
    sourceType ${record["HTTP_X_SOURCETYPE"]}
    version ${record["HTTP_X_VERSION"]}
    time ${time} UTC
  </record>
  remove_keys <all http headers recived>
</filter>
 <match transform.csv>
    @type stdout
  </match>
```

And the result of that config is this:
2021-05-12 06:46:59.159019122 +0000 transform.csv: {"${record["HTTP_X_COLUMNS"]}":"Stockholm","docType":"doc","baseType":"base","type":"place","source":"curl","sourceType":"curl","version":"v1","time":"2021-05-12 06:46:59 +0000 UTC"}

**Describe the solution you'd like**
The best solution for me personally would be to allow CSV keys to be set dynamically through a HTTP-header.
If there's a way to do this without writing a plugin (or adding a new feature), I would be delighted to try it.

**Describe alternatives you've considered**
I guess (?) this is possible by writing a plugin of your own but I haven't been able to try that yet.

**Additional context**
N/A

**Comment by kenhys** [comment]
Hmm, it seems that [`@type csv` doesn't support dynamic keys](https://github.com/fluent/fluentd/blob/master/lib/fluent/plugin/parser_csv.rb#L50)

I'm not sure but record modifier may work.
https://github.com/repeatedly/fluent-plugin-record-modifier#ruby-code-trick-for-complex-logic

**Comment by kenhys** [comment]
I mean the following workaround:

```
<source transform.csv>
  @type http
  port 8889
  add_http_headers true
  <parse>
    @type none
  </parse>
</source>

# need to filter the following event
2021-05-13 10:40:20.392216939 +0900 transform.csv: {"message":"value1;value2","HTTP_HOST":"localhost:8889","HTTP_USER_AGENT":"curl/7.74.0","HTTP_ACCEPT":"*/*","HTTP_X_COLUMNS":"foo,bar","HTTP_CONTENT_LENGTH":"13","HTTP_CONTENT_TYPE":"application/x-www-form-urlencoded"}

<filter transform.csv>
  @type record_modifier
  remove_keys _dummy_,message,HTTP_USER_AGENT,HTTP_HOST,HTTP_ACCEPT,HTTP_X_COLUMNS,HTTP_CONTENT_LENGTH,HTTP_CONTENT_TYPE
  <record>
    _dummy_ ${record["HTTP_X_COLUMNS"].split(",").each_with_index do |key, index| record[key] = record["message"].split(";")[index] ; end; nil}
  </record>
</filter>

<match transform.csv>
  @type stdout
</match>
```

Then, post data for fluentd.

```
$ curl -X POST -H "X_COLUMNS:foo,bar" -d 'value1;value2' http://localhost:8889/transform.csv
```

As a result you can get the following event.

```
2021-05-13 10:42:33.452748211 +0900 transform.csv: {"foo":"value1","bar":"value2"}
```

**Comment by Nessumsar** [comment]
@kenhys Thanks a ton!! It worked, I just had to modify your config a bit to match the purpose of mine better. My current config looks like this.

`  
<source transform.csv>
    @type http
    port 8889
    add_http_headers true
    <parse>
      @type "none"
    </parse>
  </source>
  <filter transform.csv>
    @type record_modifier
    remove_keys "_dummy_,message,HTTP_USER_AGENT,HTTP_HOST,HTTP_ACCEPT,HTTP_X_COLUMNS,HTTP_CONTENT_LENGTH,HTTP_CONTENT_TYPE,HTTP_X_SOURCE, HTTP_X_SOURCETYPE, HTTP_X_VERSION, HTTP_X_DOCTYPE, HTTP_X_BASETYPE, HTTP_X_TYPE"
    <record>
      _dummy_ ${record["HTTP_X_COLUMNS"].split(",").each_with_index do |key, index| record[key] = record["message"].split(";")[index] ; end; nil}
      docType ${record["HTTP_X_DOCTYPE"]}
      baseType ${record["HTTP_X_BASETYPE"]}
      type ${record["HTTP_X_TYPE"]}
      source ${record["HTTP_X_SOURCE"]}
      sourceType ${record["HTTP_X_SOURCETYPE"]}
      version ${record["HTTP_X_VERSION"]}
    </record>
  </filter>
  <match transform.csv>
    @type http
    endpoint "http://avsolr:8983/solr/node_core/update?commit=true"
    json_array true
    <format>
      @type "json"
    </format>
    <buffer>
      timekey 10
      timekey_wait 5
    </buffer>
  </match>
`

and the curl I use:

`cat out.csv | xargs -I % curl -H "X_COLUMNS:alias1,alias2,name,fullname,docId,status,places,docType,baseType,type,source,sourceType,version" -H "X_SOURCE: currrl" -H "X_DOCTYPE: doc" -H "X_BASETYPE: BASE" -H "X_VERSION: V111" -H "X_SOURCETYPE: ST" -H "X_TYPE: type" -d "%" http://localhost:8889/transform.csv`

This way I can transform it with extra fields and still keep the data I'm passing in from "out.csv". 
Thanks a lot once again!
