### ISSUE TITLE
http_in plugin respond with 200 OK to GET /

### ISSUE THREAD

**Issue by JoshKeegan** [fluent/fluentd#3372]
**Is your feature request related to a problem? Please describe.**
I am trying to run Fluentd by deploying a docker container to an Azure App Service. App Service is designed for running HTTP APIs and websites and expects an application to respond with HTTP 200 to GET / before it will route any requests to it.

**Describe the solution you'd like**
I would like to have http_in respond with 200 OK to a GET / request.

**Describe alternatives you've considered**
Running the http_in plugin behind nginx within the same container andn having nginx handle GET /. This isn't preferred for a few reasons though.

**Additional context**
N/A

Is this reasonable? I am happy to work on it & open a PR.

**Comment by fujimotos** [comment]
> I would like to have http_in respond with 200 OK to a GET / request.

@JoshKeegan Should be fixed by #3373.

**Comment by JoshKeegan** [comment]
> 
> 
> > I would like to have http_in respond with 200 OK to a GET / request.
> 
> @JoshKeegan Should be fixed by #3373.

Thankyou for the quick response & PR!
