### ISSUE TITLE
Add s390x architecture support for gitlab CI

### ISSUE THREAD

**Issue by sid226** [fluent/fluentd#3384]
**Is your feature request related to a problem? Please describe.**
This feature request is not related to a problem. 
We are looking to add s390x support to the existing Gitlab CI to allow testing of the latest build on s390x architecture.
Need some pointers to proceed. Hardware/VM access can be provided if needed. Happy to discuss. Thanks!

**Describe the solution you'd like**
NA

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by ashie** [comment]
IMHO we can't maintain it, because even Arm architectures aren't maintained enough.
