### ISSUE TITLE
Need forward the logs faster in some scenario. Thanks.

### ISSUE THREAD

**Issue by johnzheng1975** [fluent/fluentd#3385]
Check [CONTRIBUTING guideline](https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md) first and here is the list to help us investigate the problem.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

I am forwarding logs to cloudwtach, with fluent-plugin-cloudwatch-logs.
I want to forward the logs as fast as possible, for an important demo.
But still need 2 minutes to forward the logs. **Is there anyway to improve**? Thanks a lot.
Here is my conf:
```
<source>
      @type tail
      enable_stat_watcher false
      refresh_interval 1 
      read_from_head true
      rotate_wait 3
      enable_watch_timer true
      open_on_every_update false
      path /var/log/containers/*.log
      pos_file /var/log/fluentd-containers.log.pos
      time_format %Y-%m-%dT%H:%M:%S.%NZ
      tag kubernetes.*
      format json
      read_from_head true
    </source>
 ......
    <match **_istio-proxy-**>
      @type cloudwatch_logs
      log_group_name "#{ENV['LOG_GROUP_NAME']}"
      auto_create_stream true
      use_tag_as_stream true
      fetch_interval 1
      max_events_per_batch 1000
      <buffer>
        flush_at_shutdown true
        flush_mode immediate
        flush_thread_count 8
        flush_thread_interval 1
        flush_thread_burst_interval 1
        retry_forever true
        retry_type exponential_backoff
      </buffer>
    </match>
```

**Comment by johnzheng1975** [comment]
![Uploading image.png…]()

**Comment by ashie** [comment]
It's not fluetnd's issue.
It's fluent-plugin-cloudwatch-logs or AWS's issue.
You should ask it at user's forum, and already did it at [Slack](https://app.slack.com/client/T0CSKNZLK/C0CTT63EE/thread/C0CTT63EE-1621609775.024700).
So I close this.
