### ISSUE TITLE
working with multiple records per chunk

### ISSUE THREAD

**Issue by lazycoder-20222** [fluent/fluentd#3397]
**Describe the bug**

I am using a fluentd configuration to tail log files, format them into json records and publish them via http plugin.
It works fine when I use chunk_limit_records = 1 where every chunk only contains 1 record. However, it opens way too many files on system under the load and is not scalable.

When I increase chunk_limit_records to 1000, it starts appending all the records in the same buffer file until it reaches 1000. However, the problem is that it looks to publish all 1000 records in a single request via http plugin. The buffer file looks something like this:

{"field1":"value1"}{"field2":"value2"}{"field3":"value3"}{"field4":"value4"}

Note that each {"fieldX":"valueX"} is a separate record that should be sent via a separate http request but it just looks to send above chunk in a single request to http destination. How can I ensure that chunk can have multiple records to reduce the number of open files for fluentd process while making sure that records in the chunk are read back one by one before sending to http output?

**To Reproduce**

**Expected behavior**

I expect that I can store 1000 records in a file buffer chunk and each of them are read back and sent via http plugin separately instead of sending all records in the chunk in a single request.

**Your Environment**
fluentd 1.12.4
OS: Amazon Linux AMI rhel fedora
Kernel: 4.14.225-121.362.amzn1.x86_64

If you hit the problem with older fluentd version, try latest version first.
I hit this problem will all versions old or latest.

**Your Configuration**
buffer config
```
    total_limit_size    4g
    chunk_limit_records 100
```

```

**Your Error Log**
No errors
```

```

**Additional context**

<!-- Add any other context about the problem here. -->

**Comment by kenhys** [comment]
AFAIK, "sending all records in the chunk in a single request" seems usual behavior.
There is no such a option to send it separately. (It seems that reducing redundant requests are reasonable design, IMHO)

**Comment by lazycoder-20222** [comment]
@kenhys I am not sure if I explained it properly.

> It seems that reducing redundant requests are reasonable design, IMHO

Well, these are not structured records stored by fluentd in the single file and events are just appended one after the other.
`{"field1":"value1"}{"field2":"value2"}{"field3":"value3"}{"field4":"value4"}`

There should be some way to read events back from the buffer chunk and let them be passed to the destination? 
Especially if the destination only supports API that accepts a single event?

**Comment by kenhys** [comment]
I am not sure if I understand what you mean...
How fluentd stores records have nothing to do with it, doesn't it?

The problem is https://docs.fluentd.org/output/http plugin does not support sending events in every single one?
so, it seems better to implement your own custom output plugin or implement such a feature in https://github.com/fluent-plugins-nursery/fluent-plugin-out-http in this case.
