### ISSUE TITLE
In tail plugin fluentd is not passing log line until new line comes in

### ISSUE THREAD

**Issue by gagansingh355** [fluent/fluentd#3439]
Check [CONTRIBUTING guideline](https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md) first and here is the list to help us investigate the problem.

**Describe the bug**
I am tailing a file. Whenever first line gets added it is parsed only when the next line comes in log file. In other words the file is being tailed till second last line of log file.

**To Reproduce**
I am running this setup in AWS WIndows EC2.

**Expected behavior**
The tail should work properly and not tail upto second last line rather it should go till last line.

**Your Environment**
AWS Windows EC2.
fluentd version: fluentd 1.13.1

**Your Configuration**

```
<source>
  @type tail
  path C:/Users/Administrator/Desktop/test.log
  pos_file C:/Users/Administrator/Desktop/test_pos.pos
  tag lm.log
  <parse>
    @type none
  </parse>
  open_on_every_update true
</source>
<match lm.**>
  @type stdout
</match>
```

**Your Error Log**

```
<!-- Write your **ALL** error log here -->
```

**Additional context**

**Comment by ashie** [comment]
I can't reproduce it by adding a new line with the following command `echo newline >> test.log`.
But I reproduced it when I add a new line without a trailing line break (e.g. editing it by notepad.exe).
On this case, fluentd waits a new line break, it's not a bug.

Could you tell me how did you adding new lines?
In addition, please provide your sample test.log if you can.

**Comment by gagansingh355** [comment]
Actually I am using a software which is creating a log file, it is more close the editing format of editing the notepad file(line break doesn't happens after addition of a new line).

After this I had created a notepad file in which I was adding line one by one and I was expecting to parse the last line.

**Comment by ashie** [comment]
Fluentd requires a line break (LF: `\n`) to parse a line, otherwise fluentd cannot distinguish whether remaining of the line data isn't arrived yet.
