### ISSUE TITLE
Missing images linked in README

### ISSUE THREAD

**Issue by pombredanne** [fluent/fluentd#3454]
### Describe the bug

See https://github.com/fluent/fluentd/blob/4089231926d9e2343303443f3aeef79a41a840ad/README.md
![Screenshot from 2021-07-09 21-36-24](https://user-images.githubusercontent.com/675997/125128085-cae0a600-e0fd-11eb-8c4f-7ed8871e7c1a.png)

### To Reproduce

See https://github.com/fluent/fluentd/blob/4089231926d9e2343303443f3aeef79a41a840ad/README.md

### Expected behavior

No broken images

### Your Environment

```markdown
See https://github.com/fluent/fluentd/blob/4089231926d9e2343303443f3aeef79a41a840ad/README.md
```

### Your Configuration

See https://github.com/fluent/fluentd/blob/4089231926d9e2343303443f3aeef79a41a840ad/README.md

### Your Error Log

```shell
See https://github.com/fluent/fluentd/blob/4089231926d9e2343303443f3aeef79a41a840ad/README.md
```

**Comment by ashie** [comment]
Thanks for your report!
We've fixed it.
