### ISSUE TITLE
input plugin http basic auth

### ISSUE THREAD

**Issue by jinnery** [fluent/fluentd#3461]
### Is your feature request related to a problem? Please describe.

I'm trying to use the http input plugin to collect logs from a client web app。
At present, input plugin HTTP does not support authentication。
Will it be supported in the future。

### Describe the solution you'd like

Modifying plug-ins to support HTTP authentication

### Describe alternatives you've considered

Write a plug-in

**Comment by kenhys** [comment]
duplicated issue: https://github.com/fluent/fluentd/issues/3193
