### ISSUE TITLE
Data process delay for ```copy``` output plugin

### ISSUE THREAD

**Issue by shenmuxiaosen** [fluent/fluentd#3494]
### Describe the bug

We are using ```copy``` to process logs to two different destinations, local files and a customized output plugin called (mdsd). For file output, we choose to use file buffer instead of memory. We do hold the buffer files for a while and have an app to periodically read from them. Then we have observed that data are not processed according to the event timestamp. 

Example of the buffer file content:

{log1, "Timestamp":"2021-08-30T21:00:52.2427594+00:00"}
{log2, "Timestamp":"2021-08-30T21:00:53.2427594+00:00"}
...
{log10, "Timestamp":"2021-08-30T21:12:27.2427594+00:00"}
{log11, "Timestamp":"2021-08-30T**21:00:00**.2427594+00:00"}       <=  older logs populated
{log12, "Timestamp":"2021-08-30T21:00:01.3725321+00:00"}
...
{log20, "Timestamp":"2021-08-30T21:00:05.2332527+00:00"}         
{log21, "Timestamp":"2021-08-30T**21:12:24**.9585152+00:00"}       
...

From the example above, log11 till log20 are something happened earlier but processed later (more than 10mins).  Then from log21 new logs start to come in. And this pattern keeps happening. We do check that there is no duplication. 

It looks like there are multiple instances doing the work and some may experience some delay. Not sure if this is related with the ```copy_mode```, which we don't specify.  

### To Reproduce

Output to two destinations and check the output buffer file for ```file``` plugin.

### Expected behavior

Logs should be process sequentially. 

### Your Environment

```markdown
- Fluentd version: 1.12.4
- TD Agent version: td-agent 4.1.1
- Operating system: 18.04.5 LTS (Bionic Beaver)
- Kernel version: 5.4.0-1051-azure
```

### Your Configuration

```
# This file collects and filters all Kubernetes container logs.

# Do not directly collect fluentd's own logs to avoid infinite loops.
<match fluent.**>
  @type null
</match>

<source>
  @type tail
  path /var/log/containers/*.log
  pos_file /var/log/fluentd-containers.log.pos
  tag kubernetes.*
  read_from_head true
  follow_inodes true
  <parse>
    @type multi_format
    # Read logs in JSON format for Kubernetes v1.18-
    <pattern>
      format json
      time_format "%Y-%m-%dT%H:%M:%S.%NZ"
      keep_time_key true
    </pattern>
    # Reads logs in CRI format for Kubernetes v1.19+
    # The CRI format is documented here: https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node/kubelet-cri-logging.md
    <pattern>
      format regexp
      expression /^(?<time>.+) (?<stream>stdout|stderr)( (?<logtag>.))? (?<log>.*)$/
      time_format '%Y-%m-%dT%H:%M:%S.%N%:z'
      keep_time_key true
    </pattern>
  </parse>
</source>

# Retag appconfig services' logs to notification based on method
<match **.kubernetes.var.log.containers.**appconfigservice**.log>
  @type copy
  <store>
    @type rewrite_tag_filter
    <rule>
      key     Method
      pattern ^(DELETE|PUT|GET|HEAD)$
      tag     notification
    </rule>
  </store>
  <store>
    @type rewrite_tag_filter
    <rule>
      key     Type
      pattern ^(.+)$
      tag     azconfig.$1
    </rule>
  </store>
</match>

# Send notification events to files
<match notification>
  @type file
  path /var/log/td-agent/notification
  append true
  buffer_type file
  time_slice_wait 12h
  buffer_path /var/log/notification/buffer
  buffer_chunk_limit 2g
  time_slice_format %Y%m%d%H
  format json
</match>

# Send azconfig.{Type} events to MDSD
<match azconfig.**>
  @type mdsd
  djsonsocket /var/run/mdsd/default_djson.socket  # Full path to mdsd dynamic json socket file
  acktimeoutms 5000  # max time in milliseconds to wait for mdsd acknowledge response. If 0, no wait.
  mdsd_tag_regex_patterns ["\\w+$"] # fluentd tag patterns whose match will be used as mdsd source name, eg, azconfig.Trace => Trace
  convert_hash_to_json true
  num_threads 1
  buffer_chunk_limit 1000k
  buffer_type file
  buffer_path /var/log/td-agent/buffer/out_azconfig*.buffer
  buffer_queue_limit 128
  flush_interval 10s
  retry_limit 3
  retry_wait 10s
</match>
```

### Your Error Log

```shell
No error log found. 
Some warning logs looks unrelated. 

2021-08-30T18:03:44.9984170Z: warn DataReader.cc:230 tag '93312605' is not found in backup cache
```

**Comment by kenhys** [comment]
Is delay observed at /var/log/td-agent/notification.log?
Without copy, is it still observed?

**Comment by shenmuxiaosen** [comment]
> Is delay observed at /var/log/td-agent/notification.log?
> Without copy, is it still observed?

The delay was observed at the buffer files:  /var/log/notification/buffer/buffer.bxxxxxx.log then /var/log/td-agent/notification.log after buffer flushed. 
With ```copy``` we send logs to two destinations (file and mdsd). No delay was found in mdsd. So I am assuming it only happens for file output plugin.

**Comment by shenmuxiaosen** [comment]
@kenhys Any updates on this issue?
