### ISSUE TITLE
Insecure download links on website. Blocked by Chrome

### ISSUE THREAD

**Issue by Dynatrace-Adam-Gardner** [fluent/fluentd#3497]
### Describe the bug

Fluentd downloads are served via `http://packages.treasuredata.com.s3.amazonaws.com/4/windows/td-agent-4.2.0-x64.msi`

Chrome blocks this because the repo URL is served via HTTPS but the file download link is insecure.

### To Reproduce

1. Go to https://www.fluentd.org/download
2. Click on windows msi
3. Try to download a file
4. Chrome blocks it and nothing visual happens
5. Open dev tools and see the warning

### Expected behavior

Fluentd binaries are served securely and downloadable

### Your Environment

```markdown
- Fluentd version: N/A
- TD Agent version: N/A
- Operating system: N/A
- Kernel version: N/A
```

### Your Configuration

N/A

### Your Error Log

```shell
Mixed Content: The site at 'https://td-agent-package-browser.herokuapp.com/' was loaded over a secure connection, but the file at 'http://packages.treasuredata.com.s3.amazonaws.com/4/windows/td-agent-4.2.0-x64.msi' was loaded over an insecure connection. This file should be served over HTTPS. This download has been blocked. See https://blog.chromium.org/2020/02/protecting-users-from-insecure.html for more details.
```

### Additional context

N/A

**Comment by kenhys** [comment]
Hmm, it may be missing `BUCKET_URL_PREFIX` (http://) and there is a mismatch cert.

https://github.com/powdahound/s3browser/blob/master/www/config.php#L32

**Comment by kenhys** [comment]
I've forwarded it to the maintainer.

**Comment by toru-takahashi** [comment]
I've changed the download link to path style from virtual host style. Because the bucket name includes dot, and it caused the certification issue. Could you please check if the issue has been resolved on your end?

**Comment by ashie** [comment]
Thanks! The issue seems be resolved.

**Comment by Dynatrace-Adam-Gardner** [comment]
Yes, this is fixed now.
