### ISSUE TITLE
sending '@timestamp' and '_id' to Fluentd Endpoint

### ISSUE THREAD

**Issue by triptesh1212** [fluent/fluentd#3498]
### Describe the bug

I have written a sample python script to send message at Kibana Dashboard of EFK stack. I am sending message from python script to Fluentd Endpoint.

### To Reproduce

The script is the following:

```
import requests
import json
from datetime import datetime

username = "abc"
password = "xyz"

url = "https://fluentd-aaaaa-bbbb.com"

r = requests.post(url, auth=(username, password), json={"msg":"random testing"})

print(r.status_code)
```

### Expected behavior

At Kibana Dashboard of EFK stack, I got the following.

```
Sep 1, 2021 @ 21:32:48.258  msg:random testing @timestamp:Sep 1, 2021 @ 21:32:48.258 _id:4rVKrHsBWfzSb5RDi6m7 _type:_doc 
                            _index:logs-json-2021.09.01 _score: -
```

### Your Environment

```markdown
- TD Agent version: 4
- Operating system: Amazon Linux 2 (centos)
```

### Your Configuration

---

### Your Error Log

```shell
---
```

### Additional context

Is there any way to send '@timestamp' and '_id' from python script to Fluentd Endpoit ?

If we send at Elasticsearch Endpoint from Python script using elasticsearch API, we can set '@timestamp' and '_id' at the Python script. I am trying to find out if there is any way for Fluentd Endpoint.

I have tried something like this but it does not work.

```
date_time = datetime.now().__str__()
r = requests.post(url, auth=(username, password), json={"msg":"random testing", "@timestamp":date_time})
```

**Comment by ashie** [comment]
Here isn't a user forum, please send your question to https://discuss.fluentd.org/
For timestamp, probably you need to read the following articles:

* https://docs.fluentd.org/input/http#basic-usage
* https://docs.fluentd.org/configuration/parse-section#time-parameters
