### ISSUE TITLE
Add parameter in fluentd parser for remaining another field even reserve_data is false

### ISSUE THREAD

**Issue by chikinchoi** [fluent/fluentd#3505]
### Is your feature request related to a problem? Please describe.

We can use the fluentd parser to parse a field to JSON and also we could set the reserve_data as false to remove all other fields if the parsing success. However, we might need to create some exception to remain another field for other purpose. 
In my scenario, I am using the gsub function in record_modifier to create a new field "taskDef", then use the parser to parse the filed "log" to JSON. If I set the reserve_data as false, it will delete my new created field "taskDef". That's why I would like to request for a new feature request.

```
<filter **firelens**>
  @type record_modifier
  <record>
    taskDef ${record["ecs_task_definition"].gsub(/:.*/, '')}
  </record>
</filter>

<filter **firelens**>
  @type parser
  key_name log
  reserve_data false
  emit_invalid_record_to_error false
  <parse>
  @type json
  </parse>
</filter>

```

### Describe the solution you'd like

I would like to add a new parameter to add exception for another filed. For example "exception_field taskDef", it will let the parser not remove the taskDef even the reserve_data is false.

### Describe alternatives you've considered

In my scenario, I have tried to use the parser first, and then use the record_modifier gsub.
However, the "reserve_data false" will remove all other the field but the "log" field, then the gsub function will return null error as it is looking at the field "ecs_task_definition"
```
<filter **firelens**>
  @type parser
  key_name log
  reserve_data false
  emit_invalid_record_to_error false
  <parse>
  @type json
  </parse>
</filter>

<filter **firelens**>
  @type record_modifier
  <record>
    taskDef ${record["ecs_task_definition"].gsub(/:.*/, '')}
  </record>
</filter>
```

**Comment by renegaderyu** [comment]
@chikinchoi I'm not 100% sure but I think you can set `reserve_data true` and add `remove_key_name_field true` to the parse to accomplish what you want. As I understand [the parse doc page here](https://docs.fluentd.org/filter/parser), `reserve_data` should only determine if the field in `key_name` should be kept after successful parse (in your case `log`) so I'm not sure I understand whats going wrong. 

Also, I think you have [remove_keys](https://github.com/repeatedly/fluent-plugin-record-modifier#remove_keys) and [whitelist_keys](https://github.com/repeatedly/fluent-plugin-record-modifier#whitelist_keys) options available so you could try something like parse json -> add taskDef -> drop/allow specific fields

**Comment by ashie** [comment]
@chikinchoi Please let us know whether @renegaderyu's idea satisfies your requirements.

**Comment by chikinchoi** [comment]
@ashie @renegaderyu 's idea is good. Thank you very much!

**Comment by kenhys** [comment]
The issue seems resovled.
