### ISSUE TITLE
Receive Binary data via in_udp without parsing to JSON

### ISSUE THREAD

**Issue by jayaraj-selvaraj** [fluent/fluentd#3514]
### Describe the bug

We have a requirement to listen binary packets data via UDP listening AS-IS ,collect them in files without parsing or modifying. 
Current in_udp plugin is not allowing me to that as parse section is mandatory and it expect a at least one json key.
I tried using regex like below
<parse>
                type regexp
                expression /^(.*)$/
</parse>

But it is not allowing me to use this.

this is the one we are using now, but consumers are not happy as we are parsing them in to JSON key "event". they need the data AS-IS in binary format.

        <parse>
                type regexp
                expression /^(?<event>.*)$/
        </parse>

### To Reproduce

Use in_udp plugin and try to use a regex like below
<parse>
                type regexp
                expression /^(.*)$/
</parse>

It is failing to listen the message AS-IS without parsing.

### Expected behavior

Need a facility/option to allow the in_udp listener to listen the message as RAW AS-IS without any parsing.

### Your Environment

```markdown
- Fluentd version: fluentd 1.12.3 
- TD Agent version: td-agent 4.1.1
- Operating system: Red Hat Enterprise Linux Server 7.9
- Kernel version: 3.10.0-1160.36.2.el7.x86_64
```

### Your Configuration

<source>
        type udp
        tag inudp.5541
        <parse>
                type regexp
                expression /^(.*)$/
        </parse>

        port 5541
        bind 0.0.0.0
        remove_newline false
        source_hostname_key host
</source>

<match inudp.5541>
        type file
        path /var/lib/td-agent/LB/udp.5541

        <buffer>
               timekey 5m
               timekey_wait 10s
        </buffer>
</match>

### Your Error Log

```shell
2021-09-23 11:38:02 +0100 [error]: config error file="/etc/td-agent/td-agent.conf" error_class=Fluent::ConfigError error="No named captures in 'expression' parameter. The regexp must have at least one named capture"
```

**Comment by kenhys** [comment]
Even though it requires `messsage_key` as mandatory, how about using `none` parser? Is it acceptable?
https://docs.fluentd.org/parser/none
