### ISSUE TITLE
splunkhec plugin completely breaks fluentd graceful reload - Failed to reload config file: expected end of line

### ISSUE THREAD

**Issue by alex-vmw** [fluent/fluentd#3530]
### Describe the bug

Trying to gracefully reload fluentd with a super simple configuration that is using splunkhec plugin and getting a syntax error, while there is no visible errors in the syntax.

### To Reproduce

Try to gracefully reload (https://docs.fluentd.org/deployment/signals#sigusr2) fluentd with the simple config I have provided.

### Expected behavior

fluentd shouldn't generate a config syntax error where it doesn't exist.

### Your Environment

```markdown
- Fluentd version: v1.14.1
- Operating system: Ubuntu 20.04
- Kernel version: 5.4.0-42-generic
```

### Your Configuration
```
<system>
  log_level info
  rpc_endpoint 127.0.0.1:24444
</system>
<source>
  @type systemd
  @id in_systemd_kubelet
  matches [{ "_SYSTEMD_UNIT": "kubelet.service" }]
  <storage>
    @type local
    persistent true
    path /var/log/kube-fluentd-operator-fluentd-journald-kubelet-cursor.json
  </storage>
  <entry>
    fields_strip_underscores true
  </entry>
  read_from_head true
  tag kubelet
</source>
<match kube.example.**>
  @type splunkhec
  host splunk.example.com
  token BAB747F3-744E-41BA
</match>
```

### Your Error Log

```shell
2021-10-13 00:07:50 +0000 [info]: Reloading new config
2021-10-13 00:07:50 +0000 [error]: Failed to reload config file: expected end of line at fluent.conf line 8,12
  7:   @id in_systemd_kubelet
  8:   matches [{ "_SYSTEMD_UNIT": "kubelet.service" }]

     ------------^
  9:   <storage>
```
```


### Additional context
Using splunkhec 2.0 plugin (https://rubygems.org/gems/fluent-plugin-splunkhec/versions/2.0).

**Comment by alex-vmw** [comment]
Ignore this ticket for now. I am also working with kube-fluentd-operator devs and they now believe that the issue might be related to the newer `gelf` package being used in the KFO image (https://github.com/vmware/kube-fluentd-operator/pull/269).

**Comment by alex-vmw** [comment]
Finally were able to root cause this issue to using splunkhec 2.0 plugin. As soon as splunkhec loads once, fluentd reloads break completely until fluentd is restarted!

**Comment by cosmo0920** [comment]
> I filed [cmeerbeek/fluent-plugin-splunkhec#27](https://github.com/cmeerbeek/fluent-plugin-splunkhec/issues/27), but I have a feeling that splunkhec plugin is not really supported anymore.

How about using the official [fluent-plugin-splunk-hec](https://github.com/splunk/fluent-plugin-splunk-hec) plugin? Your issue is also reproducible with this official plugin?

**Comment by alex-vmw** [comment]
> > I filed [cmeerbeek/fluent-plugin-splunkhec#27](https://github.com/cmeerbeek/fluent-plugin-splunkhec/issues/27), but I have a feeling that splunkhec plugin is not really supported anymore.
> 
> How about using the official [fluent-plugin-splunk-hec](https://github.com/splunk/fluent-plugin-splunk-hec) plugin? Your issue is also reproducible with this official plugin?

@cosmo0920 Unfortunately, https://github.com/splunk/fluent-plugin-splunk-hec is also broken, but in a different way. Please, see https://github.com/splunk/fluent-plugin-splunk-hec/issues/187 that I filed against it.

**Comment by ashie** [comment]
Not so surprising. That's plug-in mechanism, and that's Lightweight Language.
Generally speaking, plug-in mechanism can break core functionality not only Fluentd but also in most other software.
We shouldn't use unreliable plugins in any software.
Or we should ensure to fix such faults in plugins, that's OSS :wink:

**Comment by ashie** [comment]
Thanks for you advise :+1: 
We've added the notice for it: https://github.com/fluent/fluentd-docs-gitbook/pull/375
