### ISSUE TITLE
Healthcheck/metics port slow to start

### ISSUE THREAD

**Issue by Xartos** [fluent/fluentd#3539]
### Describe the bug

When restarting fluentd it seems to start by do some cleanup (like trying to flush the buffer etc.) 
While this is ongoing, neither the healthcheck nor the prometheus plugin is listening on the ports. Since it can quite some time for fluentd to complete this cleanup (could take up to 30 min in my environments) it's hard to predict the time for the healthcheck to start.
This is especially frustrating in a kubernetes environment where the liveness/readiness probes rely on the healthcheck to work in order for it to not be restarted again and the whole process restarts.

### To Reproduce

* Have fluentd running for a while
* Restart a running fluentd process
* Make sure it has started and are cleaning up the buffer etc.
* Check that the process isn't listening on the healthcheck or the metrics port
* Wait until it has flushed the buffer completly
* Check that the process has started to listening on the healthcheck and the metrics port

### Expected behavior

The metrics port should be available as soon as the process is started to be able to debug the application.

The healthcheck port should be available as soon as the process has started, has restored the buffer and are sending logs to the backend. It should at least not wait for the whole buffer to be flushed before start to listen.
 

### Your Environment

```markdown
- Fluentd version: 1.11.5
- TD Agent version: N/A
- Operating system: Debian GNU/Linux 10 (buster)
- Kernel version: 5.4.0-80-generic
- Docker image: docker.io/bitnami/fluentd:1.11.5-debian-10-r57
```

### Your Configuration

```apache
<source>
  @id prometheus
  @type prometheus
  bind 0.0.0.0
  port 24231
</source>

<source>
  @id prometheus_monitor
  @type prometheus_monitor
  <labels>
    host ${hostname}
  </labels>
</source>

<source>
  @id prometheus_output_monitor
  @type prometheus_output_monitor
  <labels>
    host ${hostname}
  </labels>
</source>

<match fluentd.healthcheck>
  @type stdout
</match>

<source>
  @type http
  bind 0.0.0.0
  port 9880
</source>

<system>
  root_dir /tmp/fluentd-buffers/
  <log>
    format json
  </log>
</system>

<source>
  @id kube-audit
  @type tail
  path /var/log/kube-audit/kube-apiserver.log,/var/log/kubernetes/audit/kube-apiserver-audit.log
  pos_file /var/log/audit/fluentd-kube-apiserver.pos
  tag kubeaudit.*
  read_from_head true
  <parse>
    @type multi_format
    <pattern>
      format json
      time_key time
      time_format %Y-%m-%dT%H:%M:%S.%NZ
    </pattern>
  </parse>
</source>

<filter kubeaudit.**>
  @id kube_api_audit_normalize
  @type record_transformer
  remove_keys responseObject,requestObject
</filter>

<source>
  @id fluentd-containers.log
  @type tail
  path /var/log/containers/*.log
  pos_file /var/log/containers.log.pos
  tag raw.kubernetes.*
  read_from_head true
  <parse>
    @type multi_format
    <pattern>
      format json
      time_key time
      time_format %Y-%m-%dT%H:%M:%S.%NZ
    </pattern>
    <pattern>
      format /^(?<time>.+) (?<stream>stdout|stderr) [^ ]* (?<log>.*)$/
      time_format %Y-%m-%dT%H:%M:%S.%N%:z
    </pattern>
  </parse>
</source>

<match raw.kubernetes.**>
  @id raw.kubernetes
  @type detect_exceptions
  remove_tag_prefix raw
  message log
  stream stream
  multiline_flush_interval 5
  max_bytes 500000
  max_lines 1000
</match>

<filter **>
  @id filter_concat
  @type concat
  key message
  multiline_end_regexp /\n$/
  separator ""
</filter>

<filter kubernetes.**>
  @id filter_kubernetes_metadata
  @type kubernetes_metadata
</filter>

<filter kubernetes.**>
  @id filter_parser
  @type parser
  key_name log
  reserve_data true
  reserve_time true
  remove_key_name_field true
  <parse>
    @type multi_format
    <pattern>
      format json
    </pattern>
    <pattern>
      format none
    </pattern>
  </parse>
</filter>

<match **>
  @id output-forwarding
  @type forward
  send_timeout 60s
  recover_wait 10s
  hard_timeout 60s
  <server>
    name aggregator
    host  fluentd-aggregator
    port 24224
    weight 60
  </server>
  <buffer>
    @type file
    path  /var/log/fluentd-buffers
    flush_mode interval
    retry_type exponential_backoff
    flush_thread_count 8
    flush_interval 5s
    retry_forever
    retry_max_interval 30
    chunk_limit_size 256M
    total_limit_size 20G
    overflow_action block
  </buffer>
</match>
```

### Your Error Log

```shell
No error occuring
```

**Comment by kenhys** [comment]
>  so the main negative effects are only that the watch list might be out of sync a couple of minutes until it's refreshed?

Yes.

Then, how about using `read_bytes_limit_per_second` https://docs.fluentd.org/input/tail#read_bytes_limit_per_second?
It may require tweaking appropriate value. (It depends on your environment)
Instead of postpone the refresh process, control log throttling may be sufficient. :thinking:

**Comment by Xartos** [comment]
Thanks a lot! it seems like setting this solved it! Then I would say that this is a non-issue anymore, so I'll close it
