### ISSUE TITLE
Td-Agent Prometheus Issue with Public IP

### ISSUE THREAD

**Issue by triptesh1212** [fluent/fluentd#3546]
### Describe the bug

Hi, We are trying to monitor Td-Agent via Prometheus 

Prometheus Configuration at td-agent.conf is the following.

```
<filter something>
  @type prometheus
  <metric>
    name fluentd_input_status_num_records_total
    type counter
    desc The total number of incoming records
    <labels>
      tag ${tag}
      hostname ${hostname}
    </labels>
  </metric>
</filter>

<source>
  @type prometheus
  bind 0.0.0.0
  port 24231
  metrics_path /metrics
</source>
<source>
  @type prometheus_output_monitor
  interval 10
  <labels>
    hostname ${hostname}
  </labels>
</source>
```
We are using AWS ec2 VM.

When we curl with localhost or Private IP of VM, we get some results.
`curl http://localhost:24231/metrics`
But we do curl with Public IP of VM, it does not work.

Can anyone help to figure out this ?
Thanks.

### To Reproduce

--

### Expected behavior

--

### Your Environment

```markdown
- TD Agent version: 4
- Operating system: Linux AWS ec2
```

### Your Configuration

```apache
--
```

### Your Error Log

```shell
--
```

**Comment by fujimotos** [comment]
> When we curl with localhost or Private IP of VM, we get some results.
> curl http://localhost:24231/metrics
> But we do curl with Public IP of VM, it does not work.

My psychic guess is that you didn't opned the 24231 port in EC2's
security group settings (rather than Fluentd's issue).

Open AWS Consoel >  EC2 > Security Group, and then confirm
that the port 24231 is allowed in Inbound traffic.
