### ISSUE TITLE
multi-worker with tail input + wildcard `path`

### ISSUE THREAD

**Issue by brsolomon-deloitte** [fluent/fluentd#3548]
### Is your feature request related to a problem? Please describe.

There is no easy way to use 1-worker per tail'd file when a wildcard is used for `path`.

### Describe the solution you'd like

```
<system>
  workers 20
</system>

<worker 0-19>
  <source>
    @type tail
    path /var/log/zeek/*.log
    pos_file /var/log/td-agent/buffer/zeek.pos
    read_from_head true
    tag zeek.*
    path_key tailed_path
    <parse>
      @type json
    </parse>
  </source>
</worker>
```

(With the assumption and knowledge that there will be 20 log files matched by that wildcard, no more and no less.

### Describe alternatives you've considered

Writing out each file, which is easily doable through something like Ansible, just not pretty at all.

**Comment by ashie** [comment]
Sorry, but I don't understand what you want.
e.g. Do you want regular expression to express `path`?
