### ISSUE TITLE
TD Agent Large Logs with Syslog Source 

### ISSUE THREAD

**Issue by triptesh1212** [fluent/fluentd#3559]
### Describe the bug

Hi, I am using TD Agent with the following source configuration.

```
<source>
  @type syslog
  port 5140
  bind 0.0.0.0
  tag system
  message_length_limit 4096
  protocol_type tcp
  <parse>
    message_format auto
    keep_time_key true
  </parse>
</source>
```
If I send the log message of size ~ 8 kb, it still works.
Can anyone please help, How to configure the source so that log of larger size drops at the source ?

### To Reproduce

-

### Expected behavior

-

### Your Environment

```markdown
- TD Agent version: 4
- Operating system: Linux AWS ec2
```

### Your Configuration

```apache
-
```

### Your Error Log

```shell
-
```

### Additional context

-

**Comment by kenhys** [comment]
Maybe using [filter plugin]( https://docs.fluentd.org/filter) might help.
(For example, count message length by `record_transforme` filter and filter longer message by `grep` filter and so on)

**Comment by kenhys** [comment]
It seems that it is neither a bug nor a feature request. I'll close this issue.
