### ISSUE TITLE
Fluentd intermediately stops sending logs to destination

### ISSUE THREAD

**Issue by dhineshbabuelango** [fluent/fluentd#3566]
### Describe the bug

Hi Team,
We have fluentd pods running in EKS cluster with destination as elastic search. We are using grok parser, most of the logs send to elastic search are our application logs. Sometimes fluentd all of a sudden stops sending the logs, we dont see any error in the fluentd pod logs. All we need to do is to delete and recreate the same config map(**without any change**) then fluentd works fine.  I checked in the reloader container as well no issues.

### To Reproduce

There is absolutely no pattern it suddenly stops sending the logs and then all we need to do is to recreate the config map

### Expected behavior

Fluentd should always send the logs to destination

### Your Environment

```markdown
- Fluentd version:
- TD Agent version:
- Operating system:
- Kernel version:
```

### Your Configuration

```apache
Normal parsing conf
```

### Your Error Log

```shell
No errors
```

**Comment by ashie** [comment]
We can't do anything due to too few information, so I close this.
If more information is provided by users, we'll reopen this.
