### ISSUE TITLE
Installing fluentd on Solaris 10 via Ruby gems having "gmkdir: Bad file number error"

### ISSUE THREAD

**Issue by dmitriklein** [fluent/fluentd#3578]
### Describe the bug

Installing fluentd on Solaris 10 via Ruby gems..

# gem install fluentd-0.12.43.gem --no-doc
Building native extensions.  This could take a while...
ERROR:  Error installing fluentd-0.12.43.gem:
        ERROR: Failed to build gem native extension.

==== below issue has been resolved:

Installing fluentd on Solaris 10 via Ruby gems..  # gem install fluentd-0.12.43.gem
    Unable to resolve dependencies: fluentd requires msgpack (< 2, >= 0.5.11), http_parser.rb (< 0.7.0, >= 0.5.1), string-scrub (<= 0.0.5, >= 0.0.3)
#  - which is OK.. but 
gem install http_parser.rb-0.8.0.gem

gives
mksh: Fatal error: Cannot load command `/opt/csw/bin/gmkdir': Bad file number

The following command caused the error:
/opt/csw/bin/gmkdir -p ./.gem.20211220-23575-qnlufa

Please help! Thank you.

### To Reproduce

n/a

### Expected behavior

n/a

### Your Environment

```markdown
- Fluentd version:
- TD Agent version:
- Operating system:
- Kernel version:
```

### Your Configuration

```apache
n/a
```

### Your Error Log

```shell
# gem install http_parser.rb-0.8.0.gem
Building native extensions.  This could take a while...
ERROR:  Error installing http_parser.rb-0.8.0.gem:
        ERROR: Failed to build gem native extension.

    /opt/csw/bin/ruby2.0 extconf.rb
creating Makefile

make "DESTDIR="
compiling ruby_http_parser.c
"ruby_http_parser.c", line 324: warning: implicit function declaration: rb_get_kwargs
"ruby_http_parser.c", line 481: warning: syntax error:  empty declaration
"ruby_http_parser.c", line 482: warning: syntax error:  empty declaration
"ruby_http_parser.c", line 483: warning: syntax error:  empty declaration
"ruby_http_parser.c", line 484: warning: syntax error:  empty declaration
"ruby_http_parser.c", line 485: warning: syntax error:  empty declaration
compiling ryah_http_parser.c
linking shared-object ruby_http_parser.so

make "DESTDIR=" install
mksh: Fatal error: Cannot load command `/opt/csw/bin/gmkdir': Bad file number
Current working directory: /opt/csw/lib/ruby/gems/2.0.0/gems/http_parser.rb-0.8.0/ext/ruby_http_parser
*** Error code 1
The following command caused the error:
/opt/csw/bin/gmkdir -p ./.gem.20211220-25755-1drkops
make: Fatal error: Command failed for target `.RUBYARCHDIR.time'


Gem files will remain installed in /opt/csw/lib/ruby/gems/2.0.0/gems/http_parser.rb-0.8.0 for inspection.
Results logged to /opt/csw/lib/ruby/gems/2.0.0/gems/http_parser.rb-0.8.0/ext/ruby_http_parser/gem_make.out
#
```

**Comment by dmitriklein** [comment]
Fixed by installing package CSWcoreutils on Solaris 10

**Comment by dmitriklein** [comment]
but now we have an other issue: 

# gem install fluentd-0.12.43.gem --no-doc
Building native extensions.  This could take a while...
ERROR:  Error installing fluentd-0.12.43.gem:
        ERROR: Failed to build gem native extension.

    /opt/csw/bin/ruby2.0 extconf.rb
checking for ruby/st.h... yes
checking for st.h... yes
checking for rb_str_replace() in ruby.h... yes
checking for rb_intern_str() in ruby.h... yes
checking for rb_sym2str() in ruby.h... no
checking for rb_str_intern() in ruby.h... yes
checking for rb_block_lambda() in ruby.h... yes
checking for rb_hash_dup() in ruby.h... yes
checking for rb_hash_clear() in ruby.h... yes
creating Makefile

make "DESTDIR="
compiling buffer.c
cc: -W option with unknown program all
*** Error code 1
The following command caused the error:
/opt/SUNWspro/bin/cc -I. -I/opt/csw/include/ruby-2.0.0/i386-solaris2.10 -I/opt/csw/include/ruby-2.0.0/ruby/backward -I/opt/csw/include/ruby-2.0.0 -I. -DHAVE_RUBY_ST_H -DHAVE_ST_H -DHAVE_RB_STR_REPLACE -DHAVE_RB_INTERN_STR -DHAVE_RB_STR_INTERN -DHAVE_RB_BLOCK_LAMBDA -DHAVE_RB_HASH_DUP -DHAVE_RB_HASH_CLEAR -I/opt/csw/include -D_FILE_OFFSET_BITS=64  -KPIC -xO3 -xarch=pentium_pro -xchip=pentium_pro  -KPIC -I.. -Wall -O3 -g -std=gnu99 -m32 -o buffer.o -c buffer.c
make: Fatal error: Command failed for target `buffer.o'


Gem files will remain installed in /opt/csw/lib/ruby/gems/2.0.0/gems/msgpack-1.3.3 for inspection.
Results logged to /opt/csw/lib/ruby/gems/2.0.0/gems/msgpack-1.3.3/ext/msgpack/gem_make.out
#

**Comment by dmitriklein** [comment]
P.S. Installed gems are : 

# gem list --local

*** LOCAL GEMS ***

bigdecimal (1.2.0)
bundler (1.17.3)
concurrent-ruby (1.1.9)
cool.io (1.7.1)
http_parser.rb (0.8.0, 0.6.0)
io-console (0.4.2)
json (2.5.0, 1.7.7)
minitest (4.3.2)
psych (2.0.0)
rake (0.9.6)
rake-compiler (1.1.6)
rdoc (4.0.0)
serverengine (1.6.4)
sigdump (0.2.4)
string-scrub (0.0.4)
test-unit (2.0.0.0)
tzinfo (2.0.4)
tzinfo-data (1.2021.5)
#

**Comment by ashie** [comment]
We don't support Solaris 10 officially.
Please continue discussion about it at https://discuss.fluentd.org/t/installing-fluentd-by-ruby-gems-on-solaris-10/358
