### ISSUE TITLE
in_http should support batch extraction also for parser_none - parser_none should support batch mode

### ISSUE THREAD

**Issue by 1tft** [fluent/fluentd#3581]
### Is your feature request related to a problem? Please describe.

You can not split configuration in different sections (input, filter, output) without using parser "[none](https://docs.fluentd.org/parser/none)".
You can not check logevents before parsing (its meaningfull not to parse any event, e.g. only parse events which have valid credential field etc.)
Currently parser "none" does not support batch mode (array of json - https://docs.fluentd.org/input/http#handle-large-data-with-batch-mode).

With this configuration
```
<source>
  @type http
  port 8887
  <parse>
    @type none
    message_key log
  </parse>
</source>

<filter **>
      @type parser
      key_name log
      remove_key_name_field true
    <parse>
      @type json
   </parse>
</filter>
[ ... further processing ... ]
```

`$ curl -d '[{"time":1514736000,"key":"foo"},{"time":1514736000,"key":"foo2"}]' http://localhost:8887/`

You get an fluentd error like: "Error trying to serialize" (when using record_transformer you get undefined method merge error).

### Describe the solution you'd like

Parser none should support batch mode (https://docs.fluentd.org/input/http#handle-large-data-with-batch-mode).

### Describe alternatives you've considered

Dont use none parser or dont use batch mode.

**Comment by fujimotos** [comment]
> CYou can not split configuration in different sections (input, filter, output) without using parser "none".
> Currently parser "none" does not support batch mode (array of json - https://docs.fluentd.org/input/http#handle-large-data-with-batch-mode).

I don't think this is possible. In your configuration, `parser_none`
is producing entries like this:

```json
{"log":"[{\"time\":1514736000,\"key\":\"foo\"},{\"time\":1514736000,\"key\":\"foo2\"}]"}
```

... and I guess that what you want  is something like below:

```json
{"log":"{\"time\":1514736000,\"key\":\"foo\"}"}
{"log":"{\"time\":1514736000,\"key\":\"foo2\"}"}
```

... which basically demands `parser_none` to 1) parses the JSON payload, 2) split
it into separate events, and 3) then seriaize each event using JSON again. This is
just too much to expect for "none" parser to perform.

I believe you'd be probably better to just use `json` parser here.

**Comment by 1tft** [comment]
Thank you @fujimotos for your answer!
I checked this issue again, with this config:

```
<source>
  @type http
  port 8887
  bind 0.0.0.0
  @label @OUT_FILE
  <parse>
    @type none
    message_key log
  </parse>
</source>

<label @OUT_FILE>
<match **>
  @type copy
  <store>
    @type file
    path /opt/td-agent/tmp/output_debug
    <buffer>
      @type memory
      total_limit_size 50MB
      flush_interval 30
      flush_mode interval
    </buffer>
  </store>
</match>
</label>

```

everything is working fine (as specified). I see at output file including following entry:
`{"log":"[{\"time\":1514736000,\"key\":\"foo\"},{\"time\":1514736000,\"key\":\"foo2\"}]"}`


But with this config:
```
<source>
  @type http
  port 8887
  bind 0.0.0.0
  @label @MY_TEST
  <parse>
    @type none
    message_key log
  </parse>
</source>

<label @MY_TEST>

#because of this docu https://docs.fluentd.org/input/http#handle-large-data-with-batch-mode you have to prefix with "json=" if using "batches"
 <filter **>
  @type record_transformer
  <record>
    log json=${record["log"]}
  </record>
 </filter>

<filter **>
      @type parser
      key_name log
      remove_key_name_field true
    <parse>
      @type json
   </parse>
</filter>

<match **>
    @type copy
    <store>
      @type relabel
      @label @OUT_FILE
    </store>
  </match>
</label>

<label @OUT_FILE>
<match **>
  @type copy
  <store>
    @type file
    path /opt/td-agent/tmp/output_debug
    <buffer>
      @type memory
      total_limit_size 50MB
      flush_interval 30
      flush_mode interval
    </buffer>
  </store>
</match>
</label>
```

I get error, like
```
dump an error event: error_class=Fluent::Plugin::Parser::ParserError error="pattern not matched with data 'json=[{\"time\":1641982749,\"key\":\"foo\"},{\"time\":1514736000,\"key\":\"foo2\"}]'" location=nil tag="" time=2022-01-12 11:50:03.146679848 +0100 record={"log"=>"json=[{\"time\":1641982749,\"key\":\"foo\"},{\"time\":1514736000,\"key\":\"foo2\"}]"}

```

So I think issue is not related to parser_none but json_parser. json_parser does not accept "batch" on this way. Do you know why? I also tested without prefix "json=" which produces other errors.

**Comment by fujimotos** [comment]
> So I think issue is not related to parser_none but json_parser. json_parser does not accept "batch" on this way. Do you know why?

@1tft  Basically Fluentd's filter plugins assumes that incoming events are
objects (such as `{"foo": "bar"}`). Since it receives an array in this case,
it results in an error trying to handle it an object.

This is basically what the following paragraph in the documentation
is trying to say:

>> NOTE: Some parser plugins do not support the batch mode
>> So, if you want to use bulk insertion for handling a large data set, please consider keeping the default JSON (or MessagePack) format or write batch mode supported parser (return array object).
>> https://docs.fluentd.org/input/http

So you specifically need to write a plugin that support batch mode, or
you should just let `in_http` to handle data in batch mode.

**Comment by 1tft** [comment]
Following config is working with input like:
`$ curl -d '[{"time":1514736000,"key":"foo"},{"time":1514736000,"key":"foo2"}]' http://localhost:8887/`

```
<source>
  @type http
  port 8887
  bind 0.0.0.0
  @label @MY_TEST
  <parse>
    @type json
  </parse>
</source>

<label @MY_TEST>

<match **>
    @type copy
    <store>
      @type relabel
      @label @OUT_FILE
    </store>
</match>

</label>

<label @OUT_FILE>
<match **>
  @type copy
  <store>
    @type file
    path /opt/td-agent/tmp/output_debug
    <buffer>
      @type memory
      total_limit_size 50MB
      flush_interval 30
      flush_mode interval
    </buffer>
  </store>
</match>
</label>
```


But following config is not working:

```
<source>
  @type http
  port 8887
  bind 0.0.0.0
  @label @MY_TEST
  <parse>
    @type none
	message_key log
  </parse>
</source>

<label @MY_TEST>

<filter **>
      @type parser
      key_name log
      remove_key_name_field true
    <parse>
      @type json
   </parse>
</filter>

<match **>
    @type copy
    <store>
      @type relabel
      @label @OUT_FILE
    </store>
  </match>
</label>

<label @OUT_FILE>
<match **>
  @type copy
  <store>
    @type file
    path /opt/td-agent/tmp/output_debug
    <buffer>
      @type memory
      total_limit_size 50MB
      flush_interval 30
      flush_mode interval
    </buffer>
  </store>
</match>
</label>
```

In both cases I use `in_http`. I dont know why `in_http `produces (with same batch input) single events when using direct json parsing but does not give these single events to `parser_none`?
`parser_none `  gets only one (batch) event `[{"time":1514736000,"key":"foo"},{"time":1514736000,"key":"foo2"}]`
json parser can not work on this this input, as you described.

**Comment by fujimotos** [comment]
> In both cases I use in_http. I dont know why in_http produces (with same batch input) single events when using direct json parsing but does not give these single events to parser_none?

Because `in_http` contains a special logic that handle an array.

https://github.com/fluent/fluentd/blob/master/lib/fluent/plugin/in_http.rb#L224-L241

This logic does not apply when you're using `parser_none`. This is
because the "none" parser produces an object like this:

```json
{"log":"[{\"time\":1514736000,\"key\":\"foo\"},{\"time\":1514736000,\"key\":\"foo2\"}]"}
```

while "json" parser would actually decode the content and produce something like this:

```json
[{"time":1514736000,"key":"foo"}, {"time":1514736000,"key":"foo2"}]
```

**Comment by 1tft** [comment]
Thank you for that explanation. So when you say `in_http` does array extraction/splitting logic only if it detects "default_parsers" (json/msgpack) do you see any chance to add "parser_none" here too: https://github.com/fluent/fluentd/blob/a392e101a3e1b896bd6fe00a01b6fc070ca35cf2/lib/fluent/plugin/in_http.rb#L103 
I know `parser_none` should also prepared to recognize such array events.

So correct title of this github feature request should be: in_http should support batch extraction also for parser_none
Any chance for such a code modification/feature request?
