### ISSUE TITLE
Installing fluentd on Solaris 10 by Ruby gems with error message: "ERROR: Failed to build gem native extension"

### ISSUE THREAD

**Issue by dmitriklein** [fluent/fluentd#3583]
### Describe the bug

Installing fluentd on Solaris 10 by Ruby gems with error message: "ERROR: Failed to build gem native extension"

### To Reproduce

# gem install fluentd -v '0.12.43'
Building native extensions.  This could take a while...
ERROR:  Error installing fluentd:
        ERROR: Failed to build gem native extension.

    /opt/csw/bin/ruby2.0 extconf.rb
checking for ruby/st.h... yes
checking for st.h... yes
checking for rb_str_replace() in ruby.h... yes
checking for rb_intern_str() in ruby.h... yes
checking for rb_sym2str() in ruby.h... no
checking for rb_str_intern() in ruby.h... yes
checking for rb_block_lambda() in ruby.h... yes
checking for rb_hash_dup() in ruby.h... yes
checking for rb_hash_clear() in ruby.h... yes
creating Makefile

make "DESTDIR="
compiling buffer.c
cc: -W option with unknown program all
*** Error code 1
The following command caused the error:
/opt/SUNWspro/bin/cc -I. -I/opt/csw/include/ruby-2.0.0/i386-solaris2.10 -I/opt/csw/include/ruby-2.0.0/ruby/backward -I/opt/csw/include/ruby-2.0.0 -I. -DHAVE_RUBY_ST_H -DHAVE_ST_H -DHAVE_RB_STR_REPLACE -DHAVE_RB_INTERN_STR -DHAVE_RB_STR_INTERN -DHAVE_RB_BLOCK_LAMBDA -DHAVE_RB_HASH_DUP -DHAVE_RB_HASH_CLEAR -I/opt/csw/include -D_FILE_OFFSET_BITS=64  -KPIC -xO3 -xarch=pentium_pro -xchip=pentium_pro  -KPIC -I.. -Wall -O3 -g -std=gnu99 -m32 -o buffer.o -c buffer.c
make: Fatal error: Command failed for target `buffer.o'

Gem files will remain installed in /opt/csw/lib/ruby/gems/2.0.0/gems/msgpack-1.3.3 for inspection.
Results logged to /opt/csw/lib/ruby/gems/2.0.0/gems/msgpack-1.3.3/ext/msgpack/gem_make.out
# 

### Expected behavior

gem install fluentd -v '0.12.43'
Successfully installed fluentd-0.12.43

### Your Environment

```markdown
- Fluentd version:
- TD Agent version:
- Operating system:
- Kernel version:
```

### Your Configuration

```apache
# ruby --version
ruby 2.0.0p598 (2014-11-13 revision 48408) [i386-solaris2.10]
# 
ruby20-2.0.0p598,REV=2016.03.07-SunOS5.10-i386-CSW.pkg
fluentd-0.12.43.gem                                             
ruby20_dev-2.0.0p598,REV=2016.03.07-SunOS5.10-i386-CSW.pkg

# gem list --local

*** LOCAL GEMS ***

bigdecimal (1.2.0)
bundler (1.17.3)
concurrent-ruby (1.1.9)
cool.io (1.7.1)
http_parser.rb (0.8.0, 0.6.0)
io-console (0.4.2)
json (2.5.0, 1.7.7)
minitest (4.3.2)
psych (2.0.0)
rake (0.9.6)
rake-compiler (1.1.6)
rdoc (4.0.0)
rubygems-update (2.7.11)
serverengine (1.6.4)
sigdump (0.2.4)
string-scrub (0.0.4)
strptime (0.2.5)
test-unit (2.0.0.0)
tzinfo (2.0.4)
tzinfo-data (1.2021.5)
#
```

### Your Error Log

```shell
# gem install fluentd -v '0.12.43'
Building native extensions.  This could take a while...
ERROR:  Error installing fluentd:
        ERROR: Failed to build gem native extension.

    /opt/csw/bin/ruby2.0 extconf.rb
checking for ruby/st.h... yes
checking for st.h... yes
checking for rb_str_replace() in ruby.h... yes
checking for rb_intern_str() in ruby.h... yes
checking for rb_sym2str() in ruby.h... no
checking for rb_str_intern() in ruby.h... yes
checking for rb_block_lambda() in ruby.h... yes
checking for rb_hash_dup() in ruby.h... yes
checking for rb_hash_clear() in ruby.h... yes
creating Makefile

make "DESTDIR="
compiling buffer.c
cc: -W option with unknown program all
*** Error code 1
The following command caused the error:
/opt/SUNWspro/bin/cc -I. -I/opt/csw/include/ruby-2.0.0/i386-solaris2.10 -I/opt/csw/include/ruby-2.0.0/ruby/backward -I/opt/csw/include/ruby-2.0.0 -I. -DHAVE_RUBY_ST_H -DHAVE_ST_H -DHAVE_RB_STR_REPLACE -DHAVE_RB_INTERN_STR -DHAVE_RB_STR_INTERN -DHAVE_RB_BLOCK_LAMBDA -DHAVE_RB_HASH_DUP -DHAVE_RB_HASH_CLEAR -I/opt/csw/include -D_FILE_OFFSET_BITS=64  -KPIC -xO3 -xarch=pentium_pro -xchip=pentium_pro  -KPIC -I.. -Wall -O3 -g -std=gnu99 -m32 -o buffer.o -c buffer.c
make: Fatal error: Command failed for target `buffer.o'


Gem files will remain installed in /opt/csw/lib/ruby/gems/2.0.0/gems/msgpack-1.3.3 for inspection.
Results logged to /opt/csw/lib/ruby/gems/2.0.0/gems/msgpack-1.3.3/ext/msgpack/gem_make.out
# 

# gem install msgpack -v '1.3.3'
Building native extensions.  This could take a while...
ERROR:  Error installing msgpack:
        ERROR: Failed to build gem native extension.

    /opt/csw/bin/ruby2.0 extconf.rb
checking for ruby/st.h... yes
checking for st.h... yes
checking for rb_str_replace() in ruby.h... yes
checking for rb_intern_str() in ruby.h... yes
checking for rb_sym2str() in ruby.h... no
checking for rb_str_intern() in ruby.h... yes
checking for rb_block_lambda() in ruby.h... yes
checking for rb_hash_dup() in ruby.h... yes
checking for rb_hash_clear() in ruby.h... yes
creating Makefile

make "DESTDIR="
compiling buffer.c
cc: -W option with unknown program all
*** Error code 1
The following command caused the error:
/opt/SUNWspro/bin/cc -I. -I/opt/csw/include/ruby-2.0.0/i386-solaris2.10 -I/opt/csw/include/ruby-2.0.0/ruby/backward -I/opt/csw/include/ruby-2.0.0 -I. -DHAVE_RUBY_ST_H -DHAVE_ST_H -DHAVE_RB_STR_REPLACE -DHAVE_RB_INTERN_STR -DHAVE_RB_STR_INTERN -DHAVE_RB_BLOCK_LAMBDA -DHAVE_RB_HASH_DUP -DHAVE_RB_HASH_CLEAR -I/opt/csw/include -D_FILE_OFFSET_BITS=64  -KPIC -xO3 -xarch=pentium_pro -xchip=pentium_pro  -KPIC -I.. -Wall -O3 -g -std=gnu99 -m32 -o buffer.o -c buffer.c
make: Fatal error: Command failed for target `buffer.o'


Gem files will remain installed in /opt/csw/lib/ruby/gems/2.0.0/gems/msgpack-1.3.3 for inspection.
Results logged to /opt/csw/lib/ruby/gems/2.0.0/gems/msgpack-1.3.3/ext/msgpack/gem_make.out
```

**Comment by dmitriklein** [comment]
# gem install fluentd -v '0.12.43' --debug
....
Exception `NoMethodError' at /opt/csw/lib/ruby/2.0.0/rubygems/package.rb:551 - undefined method `readpartial' for #<Gem::Package::TarReader::Entry:0x8547948>
....
Exception `Errno::ENOENT' at /opt/csw/lib/ruby/2.0.0/fileutils.rb:1319 - No such file or directory - /opt/csw/lib/ruby/gems/2.0.0/gems/msgpack-1.3.3/lib/msgpack.rb
...

**Comment by ashie** [comment]
We don't support Solaris 10 officially.
Please continue discussion about it at https://discuss.fluentd.org/t/installing-fluentd-by-ruby-gems-on-solaris-10/358
