### ISSUE TITLE
"tlsv1 alert internal error" when tls_verify_hostname set to true

### ISSUE THREAD

**Issue by LukasJerabek** [fluent/fluentd#3584]
### Describe the bug

Everything goes good if I use tls_verify_hostname false. Once I switch to tls_verify_hostname true, I get errors below and I dont see the logs in the destination. 

How I issue a certificate:
`openssl req -nodes -new -x509 -sha256 -newkey rsa:4096 -keyout server_priv.key -out server_pub.crt`
And I put the result of `hostname --fqdn` for CN field.

If I issue on the server:
`openssl x509 -noout -subject -in server_pub.crt `
I get:
`subject=C = XX, L = Default City, O = Default Company Ltd, CN = <same_as_below>`

If I issue on the server:
`hostname --fqdn`
I get:
`<same_as_above>`

### To Reproduce

Use my configs below, add some source for client side, for example:
```
<source>
  @type tail
  path ~/test.log
  pos_file ~/test.log.pos
  pos_file_compaction_interval 72h
  tag nginx.access_log.test
  <parse>
    @type none
  </parse>
</source>
```
restart fluentd
open ~/test.log in vim, add a line, save and close

### Expected behavior

Hostname verification passes.

### Your Environment

```markdown
client_side:
- Fluentd version: 1.14.2
- Operating system: Centos 7
- Kernel version: 3.10.0
- installed as gem
- is my personal

server side:
- Fluentd version: 1.14.2
- Operating system: Rocky Linux 8
- Kernel version: 4.18.0
- installed as gem
- is VPS
```

### Your Configuration

client side:

```
  <match nginx.access_log.*>
    @type forward
    transport tls
    tls_client_cert_path ~/certs/fluentd/client_pub.crt
    tls_client_private_key_path ~/certs/fluentd/client_priv.key
    tls_cert_path ~/certs/fluentd/server_pub.crt
    tls_verify_hostname true
    <server>
      name monitoring
      host {real_server_ip}
      port {real_server_opened_port}
      weight 60
    </server>
    <buffer tag>
      @type memory
      flush_mode immediate
    </buffer>
  </match>
```

server side:

```
<source>
  @type forward
  port {real_server_opened_port}
  bind 0.0.0.0
  <transport tls>
    cert_path ~/certs/fluentd/server_pub.crt
    private_key_path ~/certs/fluentd/server_priv.key
    client_cert_auth true
    ca_path ~/certs/fluentd/client_pub.crt
  </transport>
</source>

<match nginx.**>
  @type stdout
</match>
```

### Your Error Log

client side logs:

`2021-12-22 15:43:18 +0100 [warn]: #0 failed to flush the buffer. retry_times=5 next_retry_time=2021-12-22 15:43:36 +0100 chunk="5d3bd237b065401edaf6f971ad0a60f9" error_class=OpenSSL::SSL::SSLError error="SSL_connect returned=1 errno=0 state=error: certificate verify failed (error number 1)"`

server side logs:

`2021-12-22 15:29:00 +0100 [warn]: #0 fluent/log.rb:351:warn: unexpected error before accepting TLS connection by OpenSSL addr="37.44.19.66" host="37.44.19.66" port=34454 error_class=OpenSSL::SSL::SSLError error="SSL_accept returned=1 errno=0 state=error: tlsv1 alert internal error"`

**Comment by fujimotos** [comment]
> Everything goes good if I use tls_verify_hostname false. Once I switch to tls_verify_hostname true, I get errors below and I dont see the logs in the destination.

This is probably because you're connecting to the server using an IP address,
not a hostname.

A TLS/SSL connection verifies the certificate against the host name specified
for the connection, so if you don't use the fqdn to connect to the server, you
will end up getting that error.

**Comment by LukasJerabek** [comment]
Yes that may be that, I was not sure how that works, but this makes sense in the end. I was confused by "true" being a default value and having all examples in documentation with IP: [here](https://docs.fluentd.org/output/forward#how-to-connect-to-a-tls-ssl-enabled-server) and [here](https://docs.fluentd.org/output/forward#how-to-connect-to-a-tls-ssl-enabled-server-with-windows-certstore-certificate). Also getting log messages saying something like "tls_verify_hostname is not used, it is highly recommended". So maybe it would be useful to improve documentation on this?

**Comment by fujimotos** [comment]
>  So maybe it would be useful to improve documentation on this?

@LukasJerabek I think your suggestion is reasonable, so I just took some
moments to fix that part (see https://github.com/fluent/fluentd-docs-gitbook/commit/334324044091809f6c01cb3d87ef455120ab395f).

I'm gonna close this ticket as fixed now.
