### ISSUE TITLE
Fluentd on Solaris test with error: wrong number of arguments (1 for 0)

### ISSUE THREAD

**Issue by dmitriklein** [fluent/fluentd#3590]
### Describe the bug

Recommended test doesn't work:

# echo '{"message":"hello"}' | fluent-cat debug.log
wrong number of arguments (1 for 0)

### To Reproduce

Recommended test doesn't work:

# echo '{"message":"hello"}' | fluent-cat debug.log
wrong number of arguments (1 for 0)

### Expected behavior

Recommended test doesn't work:

# echo '{"message":"hello"}' | fluent-cat debug.log
wrong number of arguments (1 for 0)

Expected:

2011-07-10 16:49:50 +0900 debug.test: {"json":"message"}

### Your Environment

```markdown
n/a
```

### Your Configuration

```apache
n/a
```

### Your Error Log

```shell
n/a
```

### Additional context

n/a

**Comment by fujimotos** [comment]
I think the main point is that Fluentd does not support Solaris at all. It's not
apparent to me how we can add support for that platform -- after all, we don't
even any Solaris machine usable for development.

So I close this ticket as "not in our current scope" for now.

**Comment by fujimotos** [comment]
I think the main point is that Fluentd does not support Solaris in the first place.
It's not apparent to me how we can add support for that platform -- after all,
we don't even have an access to Solaris machines.

So I close this ticket as "not in the product scope" for now.
