### ISSUE TITLE
Add support placeholder for include directive

### ISSUE THREAD

**Issue by y-ken** [fluent/fluentd#360]
Hi @repeatedly 

How about to support hostname or short hostname placeholder in include directive?
This  feature would bring us more flexible configuration management!

## specification

* '/etc/td-agent' directory files are same in all servers.
* to select load file on startup fluentd, it uses hostname

## use case

It is a way to switch behavior even though these are same configuration.

* [use case 1] fetch configuration from provisioning http server on startup.
* [use case 2] keep all server configuration as static file at '/etc/td-agent' directory from git repository.

#### sample configuration of use case 1

```
$ cat /etc/td-agent/td-agent.conf

include http://my-provisioning-server:8080/fluent/#{hostname}.conf
```

OR

```
$ cat /etc/td-agent/td-agent.rb

include {
  http://my-provisioning-server:8080/fluent/#{Socket.gethostname}.conf
}
```

#### sample configuration of use case 2

```
$ ls /etc/td-agent/
td-agent.conf
vms3021.conf
vms3022.conf
vms3023.conf
vms3024.conf
...snip...
```

```
$ cat /etc/td-agent/td-agent.conf

include /etc/td-agent/#{short_hostname}.conf
```

OR

```
$ cat /etc/td-agent/td-agent.rb

include {
  /etc/td-agent/#{Socket.gethostname.split('.')[0]}.conf
}
```

Thanks.

**Comment by tagomoris** [comment]
Configuration DSL now supports `include` at master.
