### ISSUE TITLE
sigdump support for Windows

### ISSUE THREAD

**Issue by ashie** [fluent/fluentd#3600]
### Is your feature request related to a problem? Please describe.

https://github.com/fluent/fluentd/pull/3131#issuecomment-1007690885
There is no way to trigger `Sigdump.dump` on Windows.

### Describe the solution you'd like

Add a new win32 event for it like #3131.

### Describe alternatives you've considered

none.

**Comment by daipom** [comment]
@fujimotos and I have released `fluent-plugin-sigdump`.

https://github.com/fluent-plugins-nursery/fluent-plugin-sigdump

This is one way to get sigdump in Windows.

In addition, I will try to improve `fluent-ctl`.
