### ISSUE TITLE
Failed TLS connection.  Unexpected error before accepting TLS connection by OpenSSL addr="20.36.161.56" host="20.36.161.56" port=34680 error_class=OpenSSL::SSL::SSLError error="SSL_accept SYSCALL returned=5 errno=0 state=before SSL initialization"

### ISSUE THREAD

**Issue by gabrielnecula** [fluent/fluentd#3606]
### Describe the bug

I am receiving unexpected error before accepting TLS connection.

-- Using transport encryption for the input TCP plugin.
-- Using letsencrypt certificate.
-- I am using the FQDN to reach the Fluentd server.

### To Reproduce

1. Create a letsencrypt certificate.
2. Add it to the stores and in the config file.
3. Send inbound traffic to it.

### Expected behavior

Expecting it to not throw any errors

### Your Environment

```markdown
- Fluentd version: 14.4.4
- TD Agent version: td-agent 4.3.0 fluentd 1.14.3 
- Operating system: VERSION="20.04.3 LTS (Focal Fossa)"
- Kernel version: 5.11.0-1025-azure
```

### Your Configuration

```apache
<source>
  @type tcp
  tag tcp.events # required
  <parse>
    @type json
  </parse>
  port 9111   # optional. 5170 by default
  bind 0.0.0.0 # optional. 0.0.0.0 by default
  <transport tls>
    cert_path /etc/td-agent/certs/fullchain.pem
    private_key_path /etc/td-agent/certs/privkey.pem
  </transport>
  delimiter "\n" # optional. "\n" (newline) by default
</source>
```

### Your Error Log

```shell
2022-01-19 22:16:24 +0000 [warn]: #0 unexpected error before accepting TLS connection by OpenSSL addr="SANITIZED" host="SANITIZED" port=34680 error_class=OpenSSL::SSL::SSLError error="SSL_accept SYSCALL returned=5 errno=0 state=before SSL initialization"
```

**Comment by ashie** [comment]
Could you describe the detail of the client side?

> `SSL_accept SYSCALL returned=5 errno=0 state=before SSL initialization`

A typical cause of this error is non-TLS client is reached to this port.
See also #2952
