### ISSUE TITLE
min_version parameter is not used

### ISSUE THREAD

**Issue by PinkFloydVN** [fluent/fluentd#3607]
### Describe the bug

Hi Team,
As the docs describing the Fluentd configuration for version 1.0 or above https://docs.fluentd.org/configuration/transport-section,
**min_version** is a parameter to accept the lowest TLS version. However, we when I included in my template

```
 <transport tls>
    min_version TLS1_2
    cert_path        /my/cert_path/
    private_key_path /my/private_key_path/
    private_key_passphrase xxxxxxxxx
    ciphers ABCD-SHA: EFGH-SHA
 </transport>

```
then I restarted td-agent service. The td-agent log showed

```
2022-01-20 08:20:17 +0000 [warn]: parameter 'min_version' in <transport tls>
  min_version TLS1_2
  cert_path "/my/cert_path/"
  private_key_path "/my/private_key_path/"
  private_key_passphrase xxxxxxxxx
  ciphers "ABCD-SHA: EFGH-SHA"
</transport> is not used.

```
I am using td-agent 1.2.6. Please help me to check this min_version parameter.
Thank you

### To Reproduce

Include min_version in <transport tls></transport>

### Expected behavior

I expected min_version should work.

### Your Environment

```markdown
- TD Agent version:
td-agent 1.2.6

- Operating system:
NAME="Ubuntu"
VERSION="18.04.6 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.6 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

- Kernel version: 
5.4.0-92-generic
```

### Your Configuration

```apache
<transport tls>
    min_version TLS1_2
    cert_path        /my/cert_path/
    private_key_path /my/private_key_path/
    private_key_passphrase xxxxxxxxx
    ciphers ABCD-SHA: EFGH-SHA
 </transport>
```

### Your Error Log

```shell
2022-01-20 08:20:17 +0000 [warn]: parameter 'min_version' in <transport tls>
  min_version TLS1_2
  cert_path "/my/cert_path/"
  private_key_path "/my/private_key_path/"
  private_key_passphrase xxxxxxxxx
  ciphers "ABCD-SHA: EFGH-SHA"
</transport> is not used.
```

**Comment by ashie** [comment]
> - TD Agent version:
> td-agent 1.2.6

It's fluentd's version.
The td-agent version which bundles fluentd-1.2.6 is td-agent-3.2.1.

This version doesn't support `min_version` due to bundled OpenSSL version.
(I'll describe the detail of it later.)

And td-agent 3 isn't supported anymore: https://www.fluentd.org/blog/schedule-for-td-agent-3-eol
Please use latest td-agent.

**Comment by ashie** [comment]
td-agent uses Ruby2.4, but Ruby 2.4 doesn't support `min_version`/`max_version`:
https://github.com/fluent/fluentd/blob/a60603346483da721799ccb3faebcbdd757c5f16/lib/fluent/tls.rb#L42-L49

So please use `version` instead.

**Comment by PinkFloydVN** [comment]
Hi @ashie 
Thank you for your reply.
So is there anything similar parameter or something that we could use to set min version of TLS in the latest td-agent version?

**Comment by ashie** [comment]
td-agent 4 bundles Ruby 2.7 so that it supports `min_version`.

**Comment by PinkFloydVN** [comment]
Thanks @ashie, Let me try it.
