### ISSUE TITLE
emit_count_metrics has wrong name

### ISSUE THREAD

**Issue by danielhoherd** [fluent/fluentd#3628]
### Describe the bug

While digging through code I think I found a bug where emit_count_metrics has the wrong metrics_create name.

https://github.com/fluent/fluentd/blob/b28f7d70dac657cb390aabc56dcfee8857975b4b/lib/fluent/plugin/bare_output.rb#L73-L74

Both emit_count_metrics and emit_records_metrics call `metrics_create(namespace: "fluentd", subsystem: "bare_output", name: "emit_records")` with just different help_text. It seems like `emit_count_metrics` should have the name `emit_count`.

### To Reproduce

Look at https://github.com/fluent/fluentd/blob/b28f7d70dac657cb390aabc56dcfee8857975b4b/lib/fluent/plugin/bare_output.rb#L73-L74

This also shows up in a few more places.

### Expected behavior

Honestly, I expected fluentd_output_status_emit_count and fluentd_output_status_emit_records from the prometheus plugin to not look identical, which took me down a rabbit hole and led me here.

### Your Environment

```markdown
N/A, just digging through code
```

### Your Configuration

```apache
k8s 1.21 in GKE
```

### Your Error Log

```shell
N/A
```

**Comment by kenhys** [comment]
@danielhoherd thank you for reporting!

Fixed via #3630
