### ISSUE TITLE
Using td-agent @tail file reports Permission denied @ rb_file_s_stat

### ISSUE THREAD

**Issue by dmitriklein** [fluent/fluentd#3642]
### Describe the bug

Using td-agent @tail file reports 2022-02-22 09:17:21 -0800 [error]: #0 unexpected error error_class=Errno::EACCES error="Permission denied @ rb_file_s_stat - /var/log/audit/audit.log" on CentOS Linux.

td-agent is a member of "root" and "adm" groups. Read permissions are granted on /var/log/audit/ directory and audit.log file. Nevertheless td-agent can't tail /var/log/audit/audit.log file!

### To Reproduce

<source>
  @type tail
  @id input_tail
  <parse>
    @type syslog
  </parse>
  path /var/log/audit/audit.log
  pos_file /var/log/td-agent/audit.pos
  tag audit
</source>

# systemctl restart td-agent.service

### Expected behavior

tailed file must be readable by td-agent!

### Your Environment

```markdown
- Fluentd version: -
- TD Agent version: td-agent 1.11.5
- Operating system: CentOS Linux 7
- Kernel version: 3.10.0-693.el7.x86_64
```

### Your Configuration

```apache
<source>
  @type tail
  @id input_tail
  <parse>
    @type syslog
  </parse>
  path /var/log/audit/audit.log
  pos_file /var/log/td-agent/audit.pos
  tag audit
</source>
```

### Your Error Log

```shell
2022-02-22 09:17:21 -0800 [error]: #0 unexpected error error_class=Errno::EACCES error="Permission denied @ rb_file_s_stat - /var/log/audit/audit.log"
```

**Comment by dmitriklein** [comment]
This config generates same error..

<source>
  @type tail
  @id input_tail
  <parse>
    @type none
  </parse>
  path /var/log/audit/*
  pos_file /var/log/td-agent/logs.pos
  path_key filename
  tag logs
</source>

====

2022-02-23 14:32:57 -0800 [error]: #0 unexpected error error_class=Errno::EACCES error="Permission denied @ rb_file_s_stat - /var/log/audit/audit.log"

**Comment by ashie** [comment]
> - TD Agent version: td-agent 1.11.5

Probably your td-agent is 3.8, right? (1.11.5 is bundled Fluentd version)

How did you change the user ID?
Did you confirm it's really changed? Please check it by `ps axo user,group,command | grep td-agent`

Probably you failed to change uid/gid of td-agent.
Please edit `User` and `Group` in /lib/systemd/system/td-agent.service, not /etc/init.d/td-agent.

**Comment by dmitriklein** [comment]
# fluentd --version
-bash: fluentd: command not found
# td-agent --version
td-agent 1.11.5
#

**Comment by dmitriklein** [comment]
# cat /lib/systemd/system/td-agent.service
[Unit]
Description=td-agent: Fluentd based data collector for Treasure Data
Documentation=https://docs.treasuredata.com/articles/td-agent
After=network-online.target
Wants=network-online.target

[Service]
User=td-agent
Group=td-agent
LimitNOFILE=65536
Environment=LD_PRELOAD=/opt/td-agent/embedded/lib/libjemalloc.so
Environment=GEM_HOME=/opt/td-agent/embedded/lib/ruby/gems/2.4.0/
Environment=GEM_PATH=/opt/td-agent/embedded/lib/ruby/gems/2.4.0/
Environment=FLUENT_CONF=/etc/td-agent/td-agent.conf
Environment=FLUENT_PLUGIN=/etc/td-agent/plugin
Environment=FLUENT_SOCKET=/var/run/td-agent/td-agent.sock
Environment=TD_AGENT_LOG_FILE=/var/log/td-agent/td-agent.log
Environment=TD_AGENT_OPTIONS=
EnvironmentFile=-/etc/sysconfig/td-agent
PIDFile=/var/run/td-agent/td-agent.pid
RuntimeDirectory=td-agent
Type=forking
ExecStart=/opt/td-agent/embedded/bin/fluentd --log $TD_AGENT_LOG_FILE --daemon /var/run/td-agent/td-agent.pid $TD_AGENT_OPTIONS
ExecStop=/bin/kill -TERM ${MAINPID}
ExecReload=/bin/kill -HUP ${MAINPID}
Restart=always
TimeoutStopSec=120

[Install]
WantedBy=multi-user.target
#
