### ISSUE TITLE
hope "monitor_agent" support fluent-plugin-clickhouse

### ISSUE THREAD

**Issue by wangchaoforever** [fluent/fluentd#3643]
### Is your feature request related to a problem? Please describe.

when i use "monitor_agent" in my config file, if i use  "@type clickhouse" in match range, it throw an error: 
**# curl http://192.168.0.192:24220/api/plugins.json
Internal Server Error**

### Describe the solution you'd like

I hope "monitor_agent" support fluent-plugin-clickhouse, I need to monitor "retry_count" of output to clickhouse 

### Describe alternatives you've considered

I have no alternatives now.

**Comment by ashie** [comment]
Error message:
```
2022-02-24 22:19:35 +0900 [error]: #0 [monitor_agent_input] undefined method `to_masked_element' for {}:Hash
```

It causes at:
https://github.com/fluent/fluentd/blob/296f02180749bee4c22605474cd95194b04012d8/lib/fluent/configurable.rb#L107

`@config` is overridden by the plugin:

https://github.com/kumagi/fluent-plugin-clickhouse/blob/25a66a10c2fa60b653a0e3532148949c0e5226ad/lib/fluent/plugin/out_clickhouse.rb#L37
```ruby
      @config = {}
```

It's fluent-plugin-clickhouse's problem, please report it to the project.
