### ISSUE TITLE
SSL Certificate for https://packages.fluentbit.io/ expired 01.05.2022

### ISSUE THREAD

**Issue by Prisma-Ralf-T** [fluent/fluentd#3726]
### Describe the bug

Hello,

https://packages.fluentbit.io/

Websites prove their identity via certificates, which are valid for a set time period. The certificate for packages.fluentbit.io expired on 5/1/2022.

Error code: SEC_ERROR_EXPIRED_CERTIFICATE

### To Reproduce

$ curl https://packages.fluentbit.io/fluentbit.key
curl: (60) SSL certificate problem: certificate has expired

### Expected behavior

Please renew the certificate.

### Your Environment

```markdown
- Fluentd version:
- TD Agent version:
- Operating system:
- Kernel version:
.
```

### Your Configuration

```apache
.
```

### Your Error Log

```shell
.
```

### Additional context

.

**Comment by ashie** [comment]
https://github.com/fluent/fluent-bit/issues/5389
