### ISSUE TITLE
Priority field is missing after fluentd parses the syslog

### ISSUE THREAD

**Issue by chetaksirsat** [fluent/fluentd#3819]
### Describe the bug

The fluentd parser eats away the priority field from the RFC5424 syslog message

The BEFORE: Original RFC5424 compliant format message
<99> 1 2022-06-15T11:11:38.313536+00:00 vc vapi-endpoint-access - - - 2022-06-15T11:11:38.313Z | jetty-default-497413 | Invoking operation get from service com.vmware.cis.tagging.tag with id bbfe266d-d31e-4374-9df5-ab261d2bf074

AFTER: Parsed syslog message using Fluentd
1 2022-06-15T11:11:38.313536+00:00 vc vapi-endpoint-access - - - 2022-06-15T11:11:38.313Z | jetty-default-497413 | Invoking operation get from service com.vmware.cis.tagging.tag with id bbfe266d-d31e-4374-9df5-ab261d2bf074

### To Reproduce

Pass in a valid RFC5424 syslog with the fluentd configuration below

### Expected behavior

the message field still contains the <priority> field. It looks like this is converted to facility and severity

### Your Environment

```markdown
- Fluentd version: v0.12
- TD Agent version: v2
- Operating system: Ubuntu 18.04.6 LTS, Bionic
- Kernel version:
```

### Your Configuration

```apache
<source>
  @type syslog

  <parse>
   @type multi_format

   <pattern>
    format regexp
    expression /(?<external>.{0})(?<message>.*)/
   </pattern>
  </parse>

  @log_level info
  format none
  port 514
  tag selector

  severity_key severity
  facility_key facility
</source>
```

### Your Error Log

```shell
The message does not contain <x> field. Which is the priority field.
```

**Comment by ashie** [comment]
> - Fluentd version: v0.12
> - TD Agent version: v2

Could you try latest Fluentd?
v0.12 series is  no longer maintained.
