### ISSUE TITLE
input tail plugin stops working after file rotation

### ISSUE THREAD

**Issue by bertpassek** [fluent/fluentd#3838]
### Describe the bug

We use the input tail plugin for processing tracking data and we are struggling with missing data after file rotation. What happens ist, file gets rotated and fluentd does not recognize the new file after rotation. Data is written to the new file and will not be processed until next rotation happens. Unfortunately, it's rare and it just happens sometimes.

### To Reproduce

not reproducible

### Expected behavior

data gets processed after file rotation

### Your Environment

```markdown
- Fluentd version: 1.15.1
- TD Agent version:
- Operating system: Ubuntu 20.04.4 LTS
- Kernel version: 5.13.0-1031-aws
```

### Your Configuration

```apache
-
```

### Your Error Log

```shell
no error logs
```

**Comment by ashie** [comment]
Same issue with #3838
At v1.15.1 we added a log message like the following to investigate this issue:
```
2022-08-01 17:57:19 +0900 [warn]: #0 Skip update_watcher because watcher has been already updated by other inotify event path="logs/hige.log" inode=59511737 inode_in_pos_file=0
```
If you see such log message, please report it.

**Comment by bertpassek** [comment]
just update the input tail config, we will try to set enable_stat_watcher = false
