### ISSUE TITLE
Chunk_Size_limit is ignored

### ISSUE THREAD

**Issue by Joshua-Igoni** [fluent/fluentd#3863]
### Describe the bug

file size is in the range of 4kb-12kb instead of 32M as specified on custom config file, multiple files being created causing excessive files in directory stated in config.

### To Reproduce

I am running a microservice software, which is a stack of containerized images that work together, i deploy with docker-compose with fluentd included as a service in compose file. i am using the tail input plugin and file output plugin with buffer section as seen in the config below.

### Expected behavior

to many files are not to be created and file sizes should atleast be close to 32MB, or looking at it in terms of flush_interval which is 60 seconds by default, the file size should still be close to 32MB.

### Your Environment

```markdown
- Fluentd version: fluentd:v1.14-1
- Operating system:LINUX/UBUNTU (DEBIAN)
- Kernel version:5.15.0-1011-aws
```

### Your Configuration

```apache
# fluentd/conf/fluent.conf
<source>
  @type tail
  format json
  read_from_head true
  tag iotc.log
  path /fluentd/log/containers/*/*-json.log
  pos_file /tmp/container-logs.pos
</source>

<filter iotc.log>
  @type grep
    <regexp>
      key log
      pattern /WARNING|ERROR/
    </regexp>
</filter>

<match iotc.log>
  @type file
  path /outputs/iotc.log
  <buffer time>
    flush_at_shutdown true
    chunk_limit_size 32M
  </buffer>
</match>
```

### Your Error Log

```shell
ubuntu@ip-172-31-32-162:~/folder/deploy/local_deployment/logs$ du -ha
4.0K    ./iotc.log.1970010100_22.log
4.0K    ./iotc.log.1970010100_17.log
4.0K    ./iotc.log.1970010100_15.log
4.0K    ./iotc.log.1970010100_7.log
4.0K    ./iotc.log.1970010100_39.log
4.0K    ./iotc.log.1970010100_35.log
4.0K    ./iotc.log.1970010100_37.log
4.0K    ./iotc.log.1970010100_12.log
4.0K    ./iotc.log.1970010100_19.log
4.0K    ./iotc.log.1970010100_23.log
4.0K    ./iotc.log.1970010100_2.log
4.0K    ./iotc.log.1970010100_28.log
4.0K    ./iotc.log.1970010100_40.log
4.0K    ./iotc.log.1970010100_32.log
4.0K    ./iotc.log.1970010100_33.log
4.0K    ./iotc.log.1970010100_29.log
4.0K    ./iotc.log.1970010100_5.log
4.0K    ./iotc.log.1970010100_18.log
4.0K    ./iotc.log
12K     ./iotc.log.1970010100_1.log
4.0K    ./iotc.log.1970010100_13.log
4.0K    ./iotc.log.1970010100_38.log
4.0K    ./iotc.log.1970010100_0.log
4.0K    ./iotc.log.1970010100_4.log
4.0K    ./iotc.log.1970010100_30.log
4.0K    ./iotc.log.1970010100_8.log
4.0K    ./iotc.log.1970010100_14.log
4.0K    ./iotc.log.1970010100_10.log
4.0K    ./iotc.log.1970010100_34.log
4.0K    ./iotc.log.1970010100_9.log
4.0K    ./iotc.log.1970010100_24.log
4.0K    ./iotc.log.1970010100_25.log
4.0K    ./iotc.log.1970010100_3.log
4.0K    ./iotc.log.1970010100_16.log
4.0K    ./iotc.log.1970010100_36.log
4.0K    ./iotc.log.1970010100_31.log
4.0K    ./iotc.log.1970010100_27.log
4.0K    ./iotc.log.1970010100_11.log
4.0K    ./iotc.log.1970010100_21.log
4.0K    ./iotc.log.1970010100_6.log
4.0K    ./iotc.log.1970010100_20.log
4.0K    ./iotc.log.1970010100_26.log
```

### Additional context

I would like to know if there is a better way to do this, or the exact factors that maybe influence the file size behavior, because if i cat the contents of each of the log file, there is large variations which i believe stems from the buffer it self, maybe i am missing a configuration. please help out. 

Thanks.

**Comment by daipom** [comment]
Hmm, it doesn't look to me like the setup is wrong.

I'm concerned about the date and time of the file: `1970010100`.

```xml
  <buffer time>
    flush_at_shutdown true
    chunk_limit_size 32M
  </buffer>
```

Do you need `time` key?
If don't, please try to use the buffer without keys.

```xml
  <buffer []>
    flush_at_shutdown true
    chunk_limit_size 32M
  </buffer>
```

By this, `flush_mode` becomes `interval`, and `flush_interval` value (default: `60s`) is applied.
You can adjust this option to manage each file size.

* https://docs.fluentd.org/configuration/buffer-section#flushing-parameters

**Comment by Joshua-Igoni** [comment]
Thanks for your answer @daipom 
I updated the config file to the one below;

```
# fluentd/conf/fluent.conf
<source>
  @type tail
  read_from_head true
  tag iotc.log
  path /fluentd/log/containers/*/*-json.log
  pos_file /tmp/container-logs.pos
  <parse>
    @type json
    time_type mixed
    time_format %Y-%m-%dT%H:%M:%S
    time_format_fallbacks float
  </parse>
</source>

<filter iotc.log>
  @type grep
    <regexp>
      key log
      pattern /WARNING|ERROR/
    </regexp>
</filter>

<match iotc.log>
  @type file
  path /outputs/iotc.log
  compress gzip
  <buffer>
    @type file
    flush_at_shutdown true
    chunk_limit_size 250KB
  </buffer>
</match>
```
fluentd now respects my chunk_limit_size.
Thanks for the help.
