### ISSUE TITLE
fluentd plugin for IBM z/OS

### ISSUE THREAD

**Issue by dilippanwar1** [fluent/fluentd#3886]
### Is your feature request related to a problem? Please describe.

We want to use fluentd with our product which will be installed on IBM z/OS(Mainframe). However, fluentd installer is not available for z/OS

### Describe the solution you'd like

I want a fluentd installer which should work on IBM z/OS 

### Describe alternatives you've considered

I will check if I can recompile the source to make it working with z/OS but we are not sure if that approach will work

**Comment by ashie** [comment]
Sorry, it's hard to support for us, we can't prepare IBM z/OS environment.
