### ISSUE TITLE
Provide option to ignore SIGCONT

### ISSUE THREAD

**Issue by jregovic** [fluent/fluentd#3932]
### Is your feature request related to a problem? Please describe.

When running under systemd, fluentd will produce a sigdump file even when a normal exit occurs.

Systemd sends a SIGCONT tot he process after the SIGTERM, which causes the sigdump file to be generated, putting unnecessary files in /tmp

### Describe the solution you'd like

An option in the fluentd config file to disable producing sigdump files

### Describe alternatives you've considered

We have adjusted settings for our systemd unit file, but systemd always sends the sigcont.

**Comment by abetomo** [comment]
I think disabling SIGCONT handler after SIGTERM will solve the problem.
(Suggested changes: #4034)

1. Add option to disable sigdump
2. Disable SIGCONT handler after SIGTERM
3. Both 1 and 2

Which is better: 1, 2, or 3?

**Comment by ashie** [comment]
Thanks for the fix!
I think 2 is enough for addressing the issue.

We'll consider adding 1 if someone really requires it, but I think it's not needed for now.

**Comment by daipom** [comment]
Thanks for the fix!
I will see it soon!

**Comment by daipom** [comment]
Note

https://www.freedesktop.org/software/systemd/man/systemd.kill.html#KillSignal=

> right after sending the signal specified in this setting, systemd will always send SIGCONT, to ensure that even suspended tasks can be terminated cleanly.

So, for example, in td-agent, SIGCONT is sent after SIGTERM when stopping.

https://github.com/fluent/fluent-package-builder/blob/v4.4.2/td-agent/templates/etc/systemd/td-agent.service.erb#L28
