### ISSUE TITLE
TCP keepalive support for tcp_in plugin

### ISSUE THREAD

**Issue by dimitarKiryakov** [fluent/fluentd#3960]
### Is your feature request related to a problem? Please describe.

Hi,

My setup consists in hundreds (and probably thousands soon) of tcp clients which push their events to two Fluentd instances. The fluentd instances have been configured to use tcp_in plugin with TLS support enabled.

I'm very happy with this setup, but I have noticed there is a lot of dead TCP connections on Fluentd side. The issue is there's a firewall between syslog clients and Fluentd instances, and it kills idle TCP connections. I could have increased the TCP session TTL on the firewall side to workaround this issue, but syslog clients can stay for a very long time without sending events (in some cases, more than a day).

### Describe the solution you'd like

I'd like to use TCP keepalive to prevent half-opened TCP connections.

### Describe alternatives you've considered

N/A

**Comment by fujimotos** [comment]
Fixed by #3960.
