### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by dongrr4** [fluent/fluentd#3979]
### Describe the bug

Hi Team
I am trying to install Fluentd software on Centos server and I get the error below:

Building native extensions. This could take a while...
ERROR:  Error installing fluentd:
        ERROR: Failed to build gem native extension.

    current directory: /opt/rh/rh-ruby26/root/usr/local/share/gems/gems/msgpack-1.6.0/ext/msgpack
/opt/rh/rh-ruby26/root/usr/bin/ruby -I /opt/rh/rh-ruby26/root/usr/share/rubygems -r ./siteconf20221204-2069-z0rswh.rb extconf.rb
mkmf.rb can't find header files for ruby at /opt/rh/rh-ruby26/root/usr/share/include/ruby.h

You might have to install separate package for the ruby development
environment, ruby-dev or ruby-devel for example.

extconf failed, exit code 1

When I tried to revert my changes, I got the attached screenshot (the current status)
![212](https://user-images.githubusercontent.com/119857596/205624400-94c23f0e-fa42-47cd-80f4-b788953b7575.png)

Can you assist me please?

### To Reproduce

empty

### Expected behavior

Install the software on Centos 

### Your Environment

```markdown
- Fluentd version:
- TD Agent version:
- Operating system:
- Kernel version:
```

### Your Configuration

```apache
The same conf file
```

### Your Error Log

```shell
Attached in description
```

**Comment by fujimotos** [comment]
For details, please refer to: https://www.centos.org/about/
