### ISSUE TITLE
Support for elasticsearch 8.x

### ISSUE THREAD

**Issue by peterbosalliandercom** [fluent/fluentd#3982]
### Describe the bug

When running fluentd with the elastic plugin and sending logs to an Elastic cluster above 8.x it appears that elastic does not support mapping types anymore and results in the following error :"error_class=Fluent::Plugin::ElasticsearchOutput::RecoverableRequestFailure error="could not push logs to Elasticsearch cluster ({:host=>\"xxxxxxx.eu-central-1.aws.cloud.es.io\", :port=>443, :scheme=>\"https\", :user=>\"xxxxx\", :password=>\"obfuscated\"}): [400] {\"error\":{\"root_cause\":[{\"type\":\"illegal_argument_exception\",\"reason\":\"Action/metadata line [1] contains an unknown parameter [_type]\"}],\"type\":\"illegal_argument_exception\",\"reason\":\"Action/metadata line [1] contains an unknown parameter [_type]\"},\"status\":400}"
"

### To Reproduce

run fluentd and send logs to elastic 8.x 

### Expected behavior

it should be able to write logs to elastic. (_type should be removed if es 8.x is detected, this is also implemented in logstash by the way)

### Your Environment

```markdown
- Fluentd version: ALL
- TD Agent version:
- Operating system:
- Kernel version:
```

### Your Configuration

```apache
---
```

### Your Error Log

```shell
:"error_class=Fluent::Plugin::ElasticsearchOutput::RecoverableRequestFailure error="could not push logs to Elasticsearch cluster ({:host=>\"xxxxxxx.eu-central-1.aws.cloud.es.io\", :port=>443, :scheme=>\"https\", :user=>\"xxxxx\", :password=>\"obfuscated\"}): [400] {\"error\":{\"root_cause\":[{\"type\":\"illegal_argument_exception\",\"reason\":\"Action/metadata line [1] contains an unknown parameter [_type]\"}],\"type\":\"illegal_argument_exception\",\"reason\":\"Action/metadata line [1] contains an unknown parameter [_type]\"},\"status\":400}"
```

**Comment by kenhys** [comment]
Please forward the issue to https://github.com/uken/fluent-plugin-elasticsearch
