### ISSUE TITLE
add tenant_id_key support in loki output

### ISSUE THREAD

**Issue by atamgp** [fluent/fluentd#3992]
### Is your feature request related to a problem? Please describe.

no

### Describe the solution you'd like

I need to dynamically set the loki **tenant id**.

Fluentbit supports this already, but banzai logging framework uses fluentd

See **tenant_id_key** here:
[https://docs.fluentbit.io/manual/v/1.8/pipeline/outputs/loki](https://docs.fluentbit.io/manual/v/1.8/pipeline/outputs/loki)
Implementation:
https://github.com/fluent/fluent-bit/pull/3260/files

### Describe alternatives you've considered

Fluentbit without banzai logging framework

**Comment by aslafy-z** [comment]
I believe this is already supported by the fluentd loki plugin, see https://grafana.com/docs/loki/latest/clients/fluentd/#tenant. 

> The tenant field also supports placeholders, so it can dynamically change based on tag and record fields. Each placeholder must be added as a buffer chunk key. The following is an example of setting the tenant based on a k8s pod label:
> 
> ```
> <match **>
>   @type loki
>   url "https://logs-prod-us-central1.grafana.net"
>   tenant ${$.kubernetes.labels.tenant}
>   # ...
>   <buffer $.kubernetes.labels.tenant>
>     @type memory
>     flush_interval 5s
>   </buffer>
> </match>
> ```

**Comment by ashie** [comment]
@aslafy-z Thanks for the answer :+1:
