### ISSUE TITLE
Unable to run two different input plugins using two matches for the same output plugin in Windows

### ISSUE THREAD

**Issue by jatakiajanvi12** [fluent/fluentd#4041]
### Describe the bug

Running two of our internal input plugins using the stdout output plugin. After some time, only one of the input plugins seem to be running. I have also tried this with our internal output plugin and I get the same pattern. Is there a fluentd ongoing or known bug/issue with Windows? Any workaround he same?

### To Reproduce

The config file looks like this: 

  <source>
    @type containerinventory
    tag oneagent.containerInsights.CONTAINER_INVENTORY_BLOB
    run_interval 60
    @log_level trace
  </source>

  <match **CONTAINER_INVENTORY_BLOB**>
    @type stdout
    @log_level trace
  </match>

  <source>
    @type win_cadvisor_perf
    tag oneagent.containerInsights.LINUX_PERF_BLOB
    run_interval 60
    @log_level trace
  </source>

  <match **LINUX_PERF_BLOB**>
    @type stdout
    @log_level trace
 </match

### Expected behavior

Expected behaviour is to see both the input plugins to run and send data to the stdout plugin. Both the plugins are working individually. But in the same fluentd process and config only one of the plugins prevail. 

### Your Environment

```markdown
- Fluentd version: fluentd 1.14.6
- Operating system: Windows server 2022
```

### Your Configuration

```apache
<source>
    @type containerinventory
    tag oneagent.containerInsights.CONTAINER_INVENTORY_BLOB
    run_interval 60
    @log_level trace
  </source>

  <match **CONTAINER_INVENTORY_BLOB**>
    @type stdout
    @log_level trace
  </match>

  <source>
    @type win_cadvisor_perf
    tag oneagent.containerInsights.LINUX_PERF_BLOB
    run_interval 60
    @log_level trace
  </source>

  <match **LINUX_PERF_BLOB**>
    @type stdout
    @log_level trace
 </match
```

### Your Error Log

```shell
Don't see any error. Just that the one of the plugins is not running. No output in the log file as well from this input/output plugin.
```

**Comment by daipom** [comment]
I can't reproduce it.

```xml
<source>
  @type sample
  tag oneagent.containerInsights.CONTAINER_INVENTORY_BLOB
  sample {"message": "This is the FIRST input plugin."}
</source>

<match **CONTAINER_INVENTORY_BLOB**>
  @type stdout
</match>

<source>
  @type sample
  tag oneagent.containerInsights.LINUX_PERF_BLOB
  sample {"message": "This is the SECOND input plugin."}
</source>

<match **LINUX_PERF_BLOB**>
  @type stdout
</match>
```

This config works in my environment as expected.

* Ubuntu 20.04, Windows10
* Fluentd v1.14.6, 1.15.3

```
{time} [info]: #0 fluent/log.rb:330:info: fluentd worker is now running worker=0
{time} oneagent.containerInsights.CONTAINER_INVENTORY_BLOB: {"message":"This is the FIRST input plugin."}
{time} oneagent.containerInsights.LINUX_PERF_BLOB: {"message":"This is the SECOND input plugin."}
{time} oneagent.containerInsights.CONTAINER_INVENTORY_BLOB: {"message":"This is the FIRST input plugin."}
{time} oneagent.containerInsights.LINUX_PERF_BLOB: {"message":"This is the SECOND input plugin."}
...
```

Could it be a problem with the input plugin you are using?

**Comment by jatakiajanvi12** [comment]
Hey @ashie, I fixed some issue on the input plugin side and got this to work. But my end goal is to use a custom named pipe plugin: https://github.com/microsoft/Docker-Provider/blob/jajatakia/win_ama_containerinventory/source/plugins/ruby/out_named_pipe.rb 

What I see now is when I use two input plugins with this plugin, then after a while all the fluentd plugins are sort of unloaded and I see no fluentd activity (even the plugins not related to this output are stopped. ) Also there are no errors at all in the fluentd log. Is this a fluentd functionality that causes the plugins to stop in some scenarios?

**Comment by daipom** [comment]
@jatakiajanvi12
Even if some unexpected error occurs and the worker process stops, the Fluentd supervisor process automatically restores the worker process, so it is difficult to imagine such a behavior.

I need your help to reproduce it.
Can you please find out the simple conditions as possible to reproduce and tell me?

I would like to know especially the following points:

* Fluentd config
* Fluentd log
* Whether it depends on the data to be read
* How often it reproduces, or how long do we need to run Fluentd before it reproduces?

**Comment by jatakiajanvi12** [comment]
So, I am using my own output plugin that writes to a named pipe: 


`require 'fluent/plugin/output'

module Fluent::Plugin
  class NamedPipeOutput < Output
    @@semaphore = Mutex.new
    Fluent::Plugin.register_output('named_pipe', self)

    helpers :formatter

    config_param :datatype, :string

    def initialize
        super
        require_relative "extension_utils"
    end

    def configure(conf)
      super

      @formatter = formatter_create(usage: 'msgpack_formatter', type: 'msgpack' )
    end

    def start
      super
    end

    def format(tag, time, record)
      if record != {}
        return [tag, [[time, record]]].to_msgpack
      else
        return ""
      end
    end

    def write(chunk)
      begin
          pipe_suffix = ExtensionUtils.getOutputNamedPipe(@datatype) #Internal function to get the name of named pipe
          if !pipe_suffix.nil? && !pipe_suffix.empty?
            pipe_name = "\\\\.\\pipe\\" + pipe_suffix
            @log.info "Named pipe: #{pipe_name}"
            @@semaphore.synchronize {
              File.open(pipe_name, File::WRONLY) do |f|
                chunk.write_to(f)
              end
            }
          else
            @log.error "Couldn't get pipe name from extension config. will be retried."
          end
      rescue Exception => e
        @log.info "Exception when writing to named pipe: #{e}"
        raise e
      end
    end

  end
end`

I dont think it depends on the input plugin because I was able to reproduce with the sample input plugin as well. The fluent config looks like this: 
`<source>
  @type sample
  sample {"hello":"world"}
  tag CONTAINER_INVENTORY_BLOB
</source>

<source>
  @type sample
  sample {"hello":"world"}
  tag LINUX_PERF_BLOB
</source>

<match **CONTAINER_INVENTORY_BLOB**>
  @type named_pipe
  @log_level debug
  datatype CONTAINER_INVENTORY_BLOB
  <format>
  @type msgpack
  </format>
  <buffer tag>
    @type file
    path /etc/amalogswindows/out_namedpipe_containerinventory.buffer
    overflow_action drop_oldest_chunk
    chunk_limit_size 4m
    queue_limit_length 20
    flush_interval 20s
    retry_max_times 10
    retry_wait 5s
    retry_max_interval 5m
    flush_thread_count 1
  </buffer>
</match>

<match **LINUX_PERF_BLOB**>
  @type named_pipe
  @log_level debug
  datatype LINUX_PERF_BLOB
  <format>
    @type msgpack
  </format>
  <buffer tag>
    @type file
    path /etc/amalogswindows/out_namedpipe_linuxperfblob.buffer
    overflow_action drop_oldest_chunk
    chunk_limit_size 4m
    queue_limit_length 20
    flush_interval 20s
    retry_max_times 10
    retry_wait 5s
    retry_max_interval 5m
    flush_thread_count 1
  </buffer>
</match>`

It took around 5-10min to reproduce this.

**Comment by daipom** [comment]
Thanks for the information! I will try to reproduce this.

**Comment by daipom** [comment]
@jatakiajanvi12 

> When this happens and I try to dump threads using fluent-ctl only the supervisor process threads are dumped.
> So, I am using my own output plugin that writes to a named pipe:

> I dont think it depends on the input plugin because I was able to reproduce with the sample input plugin as well.

Sorry, I just noticed the config using your own output plugin `named_pipe`.
And that plugin uses `extension_utils` library, which I don't know.

If there is a problem with Fluentd itself, I want to fix it, but it could also be a problem with its plugins or libraries.
And it is difficult to investigate it with the current information.

Can you please check if the official plugins reproduce this issue?

https://docs.fluentd.org/output

For example, [out_file](https://docs.fluentd.org/output/file) or [out_stdout](https://docs.fluentd.org/output/stdout).

**Comment by daipom** [comment]
@jatakiajanvi12 Maybe you are using the same buffer path. Please set the different path to each 'out_file' plugin. If there is a problem, please share the config.

**Comment by daipom** [comment]
If you still encounter any problems, please reopen this.
