### ISSUE TITLE
make default plugins dynamically loaded libraries

### ISSUE THREAD

**Issue by douglasawh** [fluent/fluentd#4046]
### Is your feature request related to a problem? Please describe.

We wanted to remove disk metrics from our config on some Fluentbit clients, as it is causing issues on the collector end because of the thousands of SAN luns that may be available on a single server.

### Describe the solution you'd like

We think it would have been better if implemented as a dynamically loaded library…reference it in config file (like: load diskstats), then it dynamically loads with dlopen() and finds the ne_diskstats_init() and exit() functions using dlsym(), then calls them.

It is also confusing as to why there are init and exit function for those submodules…

It seems like dynamically loaded modules were partially implemented, then dropped.

### Describe alternatives you've considered

We were going to just compile that out, but so far have run into some difficulty. Currently working on this.

**Comment by daipom** [comment]
> We wanted to remove disk metrics from our config on some Fluentbit clients

Sorry, can you please explain this a little more concretely?
Do you mean the Fluentd feature, not Fluent-bit?

**Comment by ashie** [comment]
It seems Fluent Bit's issue.
Please forward your issue to https://github.com/fluent/fluent-bit/issues

**Comment by douglasawh** [comment]
here's the fluent-bit issue: https://github.com/fluent/fluent-bit/issues/6827
