### ISSUE TITLE
Files used in unit tests remain in `/tmp`

### ISSUE THREAD

**Issue by abetomo** [fluent/fluentd#4048]
### Describe the bug

After `rake test`, the following files remained in `/tmp`.

* `/tmp/SERVERENGINE_SOCKETMANAGER_*`
* `/tmp/fluentd-lock-*`
* `/tmp/fluent/`

### To Reproduce

1. `rake test`
2. `ls /tmp`

### Expected behavior

Files created by tests should be deleted.

### Your Environment

```markdown
- Fluentd version: 1.15.3
- Operating system: Ubuntu 22.04
- Kernel version: 5.15.0-58-generic
```

### Your Configuration

```apache
-
```

### Your Error Log

```shell
-
```

**Comment by daipom** [comment]
Thanks for your report!

I ran a few tests first, but no temporary files were left.

```console
$ bundle exec rake test TESTOPTS="-t'SupervisorTest'"
$ bundle exec rake test TESTOPTS="-t'FileOutputTest'"
```

Some specific tests may be the cause.
I am concerned that it may be difficult to identify which test is the cause...

I am running all tests in my local environment now.

**Comment by abetomo** [comment]
I have been able to identify a few causes.

#4050
This fix removes several files.

**Comment by daipom** [comment]
Wow! Thanks!

I can confirm those files are left in `/tmp/` after running all tests.

We might also consider the idea that since it is in `/tmp/`, it is not a problem if it remains to some extent.

If there is a test where we obviously forget something, it would be nice to fix it.
