### ISSUE TITLE
Dependency: Update Webrick version limitation

### ISSUE THREAD

**Issue by daipom** [fluent/fluentd#4060]
### Is your feature request related to a problem? Please describe.

Currently, the version of `Webrick` is limited as follows.

* #3257 
* https://github.com/fluent/fluentd/blob/34f2c559e41aa7f4b760f55c9ac60a124de4c139/fluentd.gemspec#L31

Recently, `Webrick` v1.8 is released:

https://github.com/ruby/webrick/releases

So we need to check if we can update the current version limitation.

As it is, plugins using the latest version of `Webrick` tries to bundle the Fluentd v1.12.1.

* https://github.com/fluent-plugins-nursery/fluent-plugin-utmpx/issues/6

### Describe the solution you'd like

Fix as follows on the feature branch and check the CI.

```diff
-  gem.add_runtime_dependency("webrick", [">= 1.4.2", "< 1.8.0"])
+  gem.add_runtime_dependency("webrick", [">= 1.4.2"])
```

or

```diff
-  gem.add_runtime_dependency("webrick", [">= 1.4.2", "< 1.8.0"])
+  gem.add_runtime_dependency("webrick", [">= 1.4.2", "< 1.9.0"])
```

If there is no problem, we merge it.

### Describe alternatives you've considered

All plugins using `Webrick` also limits the version in the same way as Fluentd.

**Comment by daipom** [comment]
If this looks OK, I will do this.

> Fix as follows on the feature branch and check the CI.

**Comment by ashie** [comment]
> ```diff
> -  gem.add_runtime_dependency("webrick", [">= 1.4.2", "< 1.8.0"])
> +  gem.add_runtime_dependency("webrick", [">= 1.4.2", "< 1.9.0"])
> ```

I think `~> 1.4` or `< 2.0` is enough for this.

**Comment by daipom** [comment]
Thanks for the comment! I will do this.

You mean

```rb
gem.add_runtime_dependency("webrick", ["~= 1.4"])
```

or 

```rb
gem.add_runtime_dependency("webrick", ["< 2.0"])
```

?

If so, I'd prefer the latter.

**Comment by kenhys** [comment]
`~> 1.4`  bounds to 1.4, 1.5, 1.6 .... 1.9 and so on.  thus it is almost equal to `< 2.0` practically. (`< 2.0` may contain 1.3 or lower)

**Comment by daipom** [comment]
Sorry, I misunderstood the operator `~>`.
I thought `~> 1.4` is almost `>= 1.4 and < 1.5`, but it was wrong.

https://thoughtbot.com/blog/rubys-pessimistic-operator

Thanks for the advise! I will use `~> 1.4`!
