### ISSUE TITLE
GPG Certificate Expired for td-agent

### ISSUE THREAD

**Issue by bennettfalkenberg** [fluent/fluentd#4089]
### Describe the bug

Getting GPG certificate expired when trying to fetch GPG key: https://toolbelt.treasuredata.com/sh/install-redhat-td-agent4.sh

### To Reproduce

curl -L https://toolbelt.treasuredata.com/sh/install-redhat-td-agent4.sh | sh

Retrieving key from https://packages.treasuredata.com/GPG-KEY-td-agent

GPG key retrieval failed: [Errno 14] curl#60 - "Peer's Certificate has expired."

### Expected behavior

GPG Key is retrieved

### Your Environment

```markdown
- TD Agent version: 4
- Operating system: Centos7
```

### Your Configuration

```apache
N/A
```

### Your Error Log

```shell
Retrieving key from https://packages.treasuredata.com/GPG-KEY-td-agent


GPG key retrieval failed: [Errno 14] curl#60 - "Peer's Certificate has expired."
```

**Comment by ashie** [comment]
I can't reproduce it, and the certificate of packages.treasuredata.com doesn't seem expired:
```
$ openssl s_client -connect packages.treasuredata.com:443 < /dev/null 2> /dev/null | openssl x509 -noout -dates
notBefore=Feb 21 00:00:00 2023 GMT
notAfter=Sep 16 23:59:59 2023 GMT
```

Could you check your host's date?
