### ISSUE TITLE
Integrate RuboCop Performance

### ISSUE THREAD

**Issue by Garfield96** [fluent/fluentd#4099]
### Is your feature request related to a problem? Please describe.

There are a few code fragments that could be improved in terms of performance and readability. E.g. some tests use `select...size` instead of just `count` or `select...first` instead of `find`. Many of these issues can be automatically detected and often even fixed by [RuboCop Performance](https://github.com/rubocop/rubocop-performance) (extension of [Rubocop](https://github.com/rubocop/rubocop)). 

### Describe the solution you'd like

Fix all issues discovered by RuboCop Performance and integrate it into the CI. It most likely is not favorable to run RuboCop with all checks enabled since the style checks would require a complete linting of the project which breaks `git blame`. Running only the performance checks ensures that the number of changes is manageable (~180 changes).

### Describe alternatives you've considered

There are other linters with a focus on performance, e.g. [fasterer](https://github.com/DamirSvrtan/fasterer), but RuboCop Performance provides the advantage that it can automatically correct many issues.

### Additional context

I can take over this task, if it gets accepted.

**Comment by Garfield96** [comment]
Hi @ashie,
What is your opinion on this? Shall I implement it?

**Comment by kenhys** [comment]
Starting with a minimal cop may be useful, but I don't know whether the improvements may vary on supported ruby-version.
Instead of integrating CI directly, creating effective proven PR may be reasonable. (only fixing Performance/Count in one PR or so)
