### ISSUE TITLE
Looks like v1.16.0 was created as a branch instead of a tag by mistake

### ISSUE THREAD

**Issue by orgads** [fluent/fluentd#4112]
### Describe the bug

The repository has a branch named v1.16.0, while this naming convention is typically used for tags (also in this repo), and not for branches.

This looks like a mistake.

I can't find any public release of 1.16 though.

**Comment by daipom** [comment]
This is not a mistake.
V1.16.0 is not released yet.
That branch is for preparing it.

**Comment by orgads** [comment]
Ok, thanks :)
