### ISSUE TITLE
high kernel memory usage in Fluend Cgroup

### ISSUE THREAD

**Issue by 21kyu** [fluent/fluentd#4121]
### Describe the bug

Ever since I updateded Fluentd to version 1.15.3, the kernel memory usage has been consistently high and reaching the memory limit.

The screenshot below visualizes the memory metrics of the fluentd container.

![Screenshot from 2023-03-31 14-36-22](https://user-images.githubusercontent.com/8033707/229032546-35e2f50a-dda9-445c-9d48-e1cce454d479.png)
The point at which kernel memory was increased was when fluentd was versioned up.
- blue: usage / light blue: kernel memory / orange: rss / purple: cache

### To Reproduce

Monitor memory-releated metrics after upgrading fluentd to version 1.15.3.

### Expected behavior

Kernel memory should not continue to grow, which can result in an OOM when the container's working set bytes reaches its limit.

### Your Environment

```markdown
- Fluentd version: 1.15.3
- TD Agent version: -
- Operating system: Debian GNU/Linux 11 (bullseye)
- Kernel version: 5.4.231-137.341.amzn2.x86_64
```

### Your Configuration

```apache
We are using 2 in_tail plugins, 1 in_monitor_agent plugin, 2 prometheus plugins, and 3 kinesis_stream plugins.
```

### Your Error Log

```shell
There is no error log.
```

### Additional context

The number of TCP sockets or file descriptors does not appear to be abnormal.

We also have fluentbit installed and using it via aws-for-fluentbit. After upgrading to version 2.29.1, we are experiencing similar kernel memory issues.
Is it possible to create a single plugin to customize the interfaces for both fluentd and fluentbit?
If so, is it possible that we are experiencing the issue on both platforms at the same time because we are using a specific version of the tail plugin or kinesis plugin that is causing the memory leak?

**Comment by daipom** [comment]
What is `kernel memory`?

**Comment by 21kyu** [comment]
@daipom Among the types of memory reported by cgroups' memory controller is kernel memory.
It will be written to memory.kmem.usage_in_bytes. this value shows how much kernel memory is currently allocated within cgroups.

**Comment by 21kyu** [comment]
I noticed that when I upgraded fluentd, I also changed the flush interval to be shorter, so I think that might have had an impact.
https://github.com/awslabs/aws-fluent-plugin-kinesis#for-better-throughput

**Comment by daipom** [comment]
> When fluentd was upgraded, I noticed that fluentd's flush interval was also changed to be shorter.
> 
> I think this is affected by this fix.
> 
> https://github.com/awslabs/aws-fluent-plugin-kinesis#for-better-throughput

Could you confirm if it reproduces or not after downgrading fluent-plugin-kinesis?

We need to specify which plugin is the cause.

**Comment by 21kyu** [comment]
It looks like an issue with the kinesis plugin - we've already changed its settings to flush more leisurely, and have since confirmed that kernel memory is no longer growing rapidly.
Thank you!
