### ISSUE TITLE
Large Memory Consumption when ignore_same_log_interval

### ISSUE THREAD

**Issue by yangjiel** [fluent/fluentd#4174]
### Describe the bug

My colleague Lester Lu and I found the issue related to https://github.com/fluent/fluentd/issues/3401

The abnormal increasing memory usage is because of the ignore repeated log feature. 
The current implementation uses dictionary to store the message as key. However, depends on the plugin implementation, the message could be the actual log that being send out. For example in azure-loganalytics, the log message is like `log.fatal "Exception occured in posting to DataCollector API: " + "'#{ex}', data=>" + Yajl.dump(records)`. The records/log could be large like 1k bytes per log and never repeat.

It leads to the dictionary `cached_log` keep growing and the memory will never be released, therefore can observe significant memory usage for some plugins.

https://github.com/fluent/fluentd/blob/0a6d706a9cee5882d751b2cc6169696709df0134/lib/fluent/log.rb#L480

### To Reproduce

Use plugin azure-loganalytics, config with an invalid account so that the log will not be send out, with large traffic 3k log/s, with ignore_same_log_interval 60s, observed memory usage keep increasing.

### Expected behavior

Memory should not increase infinitely. The `cached_log` need to be freed once a while.

### Your Environment

```markdown
- Fluentd version: 1.15.2
- TD Agent version: 4.4.1
- Operating system: Ubuntu
- Kernel version:
```

### Your Configuration

```apache
<system>
  log_level      info
  ignore_repeated_log_interval   60s
  ignore_same_log_interval       60s
</system>

<match **>
    @type azure-loganalytics
    customer_id invalidid
    shared_key anykeyshouldbefine
    log_type ApacheAccessLog
<buffer tag>
	@type                      memory
	chunk_limit_size           10M
	total_limit_size           50M
	flush_at_shutdown          true
	overflow_action            block
	retry_forever              true
	disable_chunk_backup       true
</buffer>
</match>
```

### Your Error Log

```shell
No error, abnormal memory usage.
```

**Comment by ashie** [comment]
Thanks for your report!
Yep, we need to purge old logs.

https://github.com/fluent/fluentd/blob/0a6d706a9cee5882d751b2cc6169696709df0134/lib/fluent/log.rb#L464-L483

**Comment by daipom** [comment]
Wow, indeed.

**Comment by yangjiel** [comment]
May also relate to https://github.com/fluent/fluentd/issues/1657

**Comment by daipom** [comment]
I have created PR to fix this!

* #4229 

Is it correct that this only occurs when using `ignore_same_log_interval`?

**Comment by yangjiel** [comment]
Yes correct. Thanks!

**Comment by daipom** [comment]
I modified the title a bit!
Thanks for your valuable report @yangjiel !
