### ISSUE TITLE
Cant receive record via forward source

### ISSUE THREAD

**Issue by DmitryShonin** [fluent/fluentd#4206]
### Describe the bug

Hello,
following [documentation](https://docs.fluentd.org/input/forward) describe fluent-bit -> fluentd  interaction via forward output/input.
So, using configuration from that example I'm not able to get records from fluent-bit on the fluentd side.
Getting only such kind of messages
`2023-06-20 14:03:35 +0000 [warn]: #0 no patterns matched tag="cpu.0"`
At first I assume I forgot to set `tag` in fluent-bit configuration, but when I assign `tag` explicitly, for example fluent-bit output has `tag` `test` and fluend source has `tag` `test` it's still returns
`2023-06-20 14:21:30 +0000 [warn]: #0 no patterns matched tag="test"`

### To Reproduce

run following command with corresponding configuration files:

`docker network create fnet`

`docker run --name fld --rm -i --network fnet -v /tmp/fluentd.conf:/tmp/fld.conf  fluent/fluentd:v1.16-debian-1 fluentd -c /tmp/fld.conf `

`docker run --name flb --rm -i --network fnet -v /tmp/fluent-bit.conf:/tmp/flb.conf  cr.fluentbit.io/fluent/fluent-bit:2.0.9 fluent-bit -c /tmp/flb.conf`

### Expected behavior

viewing records in stdout

### Your Environment

```markdown
- Fluentd version: fluentd 1.16.1
- TD Agent version: 
- Operating system: Ubuntu 22.04.2 LTS (Jammy Jellyfish)
- Kernel version: 5.19.0-43-generic
```

### Your Configuration

```apache
fluentd,conf

 <source>
   @type forward
   @id test
   @log_level trace 
   bind 0.0.0.0
   port 24224 
   tag test
 </source>

<label @OUTPUT>
  <match **>
    @type stdout
  </match>
</label>


fluent-bit.conf

[SERVICE]
    Flush      5
    Daemon     off
    Log_Level  trace 

[INPUT]
    Name       cpu
    tag        test

[OUTPUT]
    Name          forward
    Match         *
    Host          fld
    Port          24224
    tls           off
    tls.verify    off

```

### Your Error Log

```shell
There's no errors in logs, only warns like
`2023-06-20 14:32:05 +0000 [warn]: #0 no patterns matched tag="test"`
where tag has been set in both configuration files.
```

### Additional context

If tag bind to output there's still same message, but not actual record on the fluend side

fluent-bit.conf

[SERVICE]
    Flush      5
    Daemon     off
    Log_Level  trace 

[INPUT]
    Name       cpu

[OUTPUT]
    Name          forward
    Match         *
    Host          fld
    Port          24224
    Tag          test
    tls           off
    tls.verify    off

reproducing locally running within the docker container, as well running on the EKS cluster

**Comment by Garfield96** [comment]
I haven't tried the provided configuration, but I assume the problem arises from the usage of `<label>` around the `stdout` output plugin. Since the logs don't have a label, they never reach the output plugin. You can either set a label in the `forward` input or remove the label selector around the output plugin.

**Comment by DmitryShonin** [comment]
Hello,
thanks for response, @Garfield96.
You are right, with no label around `stdout` it works as expected, seems I misunderstood  use case of label.
Thank you.

**Comment by daipom** [comment]
Thanks, @Garfield96!
