### ISSUE TITLE
Record transformer cannot parse json object named as "time"

### ISSUE THREAD

**Issue by yemreavci** [fluent/fluentd#4209]
### Record transformer cannot parse json object named as "time"

Tried to parse the time object of  json , but unable to do it.
With given input : 
{\"log\":{\"msg\":\"Local Cache Cleared\"},\"stream\":\"stdout\",\"time\":\"2023-06-19T08:10:50.063648794Z\"}

I used this record transformation:

```
<filter diagnostic_event>
  @type record_transformer
  enable_ruby true
  <record>
    message ${record['time']}|${record["log"]["msg"]}
  </record>
</filter> 
```

When I print record to stdout, I got following result:

diagnostic_event: {"log":{"msg":"Local Cache Cleared"},"stream":"stdout","message"**:"|Local Cache Cleared"**}
 
It seems to  ${record['time']} return as null. 

Is time keyword have special meaning? And "time" keyword should not contains in the inputs.

### To Reproduce

input for the source plugin:
echo "{\"log\":{\"msg\":\"Local Cache Cleared\"},\"stream\":\"stdout\",\"time\":\"2023-06-19T08:10:50.063648794Z\"}" >> /var/log/1.log

### Expected behavior

Stdout should print result as 

2023-06-19T08:10:50.063648794Z|Local Cache Cleared

### Your Environment

```markdown
- Fluentd version: fluentd:v1.15.3
- TD Agent version:
- Operating system: linux
- Kernel version: 5.15.0-73-generic
```

### Your Configuration

```apache
<source>
  @type tail
  path /var/log/*.log
  pos_file /var/log/td-agent/httpd-access-debug.log.pos
  tag diagnostic_event
  <parse>
    @type json
  </parse>
</source>

<filter diagnostic_event>
  @type record_transformer
  enable_ruby true
  <record>
  
    message ${record['time']}${record["log"]["msg"]}
  </record>
</filter>
<match diagnostic_event>
  @type copy
  <store>
    @type stdout
  </store>
</match>
```

### Your Error Log

```shell
No error log, Unexpected behavior.
```

**Comment by daipom** [comment]
@yemreavci This is not a bug.
You are using parser_json, and it parses `time` key as the time of record by default.
If you still need `time` key value of record after parsing, you can set `keep_time_key true` to the parser setting.

```diff
<source>
  @type tail
  path /var/log/*.log
  pos_file /var/log/td-agent/httpd-access-debug.log.pos
  tag diagnostic_event
  <parse>
    @type json
+   keep_time_key true
  </parse>
</source>
```

For details, please refer https://docs.fluentd.org/configuration/parse-section#parse-parameters.

**Comment by daipom** [comment]
Sorry, in this case, perhaps you should use `time` key of the event directly.
You don't need to use `keep_time_key` of the parser.

```xml
<filter diagnostic_event>
  @type record_transformer
  enable_ruby true
  <record>
    message ${time}${record["log"]["msg"]}
  </record>
</filter>
```

**Comment by yemreavci** [comment]
Thanks a lot.

**Comment by rhqudco** [comment]
If i apply the `keep_time_key true` option in the `<source>`, the date will be `example.19700101.json` when extracted as a file via match.
How can I solve this problem?

**Comment by daipom** [comment]
Note #4240
