### ISSUE TITLE
ABRT reports fluentd protection fault

### ISSUE THREAD

**Issue by PeterP55P** [fluent/fluentd#4219]
### Describe the bug

We are running fluentd as part of Oracle unified agent on Oracle Linux 7.9. After recent yum update (June 21st 2023) fluentd keeps crashing with following error. 

reason:         traps: fluentd[21636] general protection fault ip:7f1f487b9aab sp:7ffc5acefcd0 error:0 in libc-2.17.so[7f1f486a5000+1c4000]

### To Reproduce

Fluentd simply keeps crashing since last yum update. I can only provide list of packages that have been involved in recent patching since when fluentd has started crashing.

Transaction performed with:
    Installed     rpm-4.11.3-48.el7_9.x86_64   @ol7_latest/7.9
    Updated       yum-3.4.3-168.0.3.el7.noarch @anaconda/7.9
Packages Altered:
    Updated biosdevname-0.7.3-2.el7.x86_64                            @anaconda/7.9
    Update              0.7.3-2.0.1.el7.x86_64                        @ol7_latest
    Updated bpftool-3.10.0-1160.90.1.0.2.el7.x86_64                   @ol7_MODRHCK
    Update          3.10.0-1160.92.1.0.2.el7.x86_64                   @ol7_MODRHCK
    Updated cloud-init-19.4-7.0.3.el7_9.6.x86_64                      @ol7_latest
    Update             19.4-7.0.5.el7_9.6.x86_64                      @ol7_latest
    Updated emacs-filesystem-1:24.3-23.el7.noarch                     @anaconda/7.9
    Update                   1:24.3-23.el7_9.1.noarch                 @ol7_latest
    Updated geoipupdate-2.5.0-1.el7.x86_64                            @anaconda/7.9
    Update              2.5.0-2.el7.x86_64                            @ol7_latest
    Updated glibc-2.17-326.0.3.el7_9.x86_64                           @ol7_latest
    Update        2.17-326.0.5.el7_9.x86_64                           @ol7_latest
    Updated glibc-common-2.17-326.0.3.el7_9.x86_64                    @ol7_latest
    Update               2.17-326.0.5.el7_9.x86_64                    @ol7_latest
    Updated glibc-devel-2.17-326.0.3.el7_9.x86_64                     @ol7_latest
    Update              2.17-326.0.5.el7_9.x86_64                     @ol7_latest
    Updated glibc-headers-2.17-326.0.3.el7_9.x86_64                   @ol7_latest
    Update                2.17-326.0.5.el7_9.x86_64                   @ol7_latest
    Updated grub2-1:2.02-0.87.0.23.el7_9.9.x86_64                     @ol7_latest
    Update        1:2.02-0.87.0.24.el7_9.9.x86_64                     @ol7_latest
    Updated grub2-common-1:2.02-0.87.0.23.el7_9.9.noarch              @ol7_latest
    Update               1:2.02-0.87.0.24.el7_9.9.noarch              @ol7_latest
    Updated grub2-efi-x64-1:2.02-0.87.0.23.el7_9.9.x86_64             @ol7_latest
    Update                1:2.02-0.87.0.24.el7_9.9.x86_64             @ol7_latest
    Updated grub2-pc-1:2.02-0.87.0.23.el7_9.9.x86_64                  @ol7_latest
    Update           1:2.02-0.87.0.24.el7_9.9.x86_64                  @ol7_latest
    Updated grub2-pc-modules-1:2.02-0.87.0.23.el7_9.9.noarch          @ol7_latest
    Update                   1:2.02-0.87.0.24.el7_9.9.noarch          @ol7_latest
    Updated grub2-tools-1:2.02-0.87.0.23.el7_9.9.x86_64               @ol7_latest
    Update              1:2.02-0.87.0.24.el7_9.9.x86_64               @ol7_latest
    Updated grub2-tools-extra-1:2.02-0.87.0.23.el7_9.9.x86_64         @ol7_latest
    Update                    1:2.02-0.87.0.24.el7_9.9.x86_64         @ol7_latest
    Updated grub2-tools-minimal-1:2.02-0.87.0.23.el7_9.9.x86_64       @ol7_latest
    Update                      1:2.02-0.87.0.24.el7_9.9.x86_64       @ol7_latest
    Updated irqbalance-3:1.0.8-3.el7.x86_64                           @ol7_latest
    Update             3:1.0.8-3.0.1.el7.x86_64                       @ol7_latest
    Updated iwl100-firmware-999:39.31.5.1-999.18.el7.noarch           @ol7_latest
    Update                  999:39.31.5.1-999.19.el7.noarch           @ol7_latest
    Updated iwl1000-firmware-999:39.31.5.1-999.18.el7.noarch          @ol7_latest
    Update                   999:39.31.5.1-999.19.el7.noarch          @ol7_latest
    Updated iwl105-firmware-999:18.168.6.1-999.18.el7.noarch          @ol7_latest
    Update                  999:18.168.6.1-999.19.el7.noarch          @ol7_latest
    Updated iwl135-firmware-999:18.168.6.1-999.18.el7.noarch          @ol7_latest
    Update                  999:18.168.6.1-999.19.el7.noarch          @ol7_latest
    Updated iwl2000-firmware-999:18.168.6.1-999.18.el7.noarch         @ol7_latest
    Update                   999:18.168.6.1-999.19.el7.noarch         @ol7_latest
    Updated iwl2030-firmware-999:18.168.6.1-999.18.el7.noarch         @ol7_latest
    Update                   999:18.168.6.1-999.19.el7.noarch         @ol7_latest
    Updated iwl3160-firmware-999:22.0.7.0-999.18.el7.noarch           @ol7_latest
    Update                   999:22.0.7.0-999.19.el7.noarch           @ol7_latest
    Updated iwl3945-firmware-999:15.32.2.9-999.18.el7.noarch          @ol7_latest
    Update                   999:15.32.2.9-999.19.el7.noarch          @ol7_latest
    Updated iwl4965-firmware-999:228.61.2.24-999.18.el7.noarch        @ol7_latest
    Update                   999:228.61.2.24-999.19.el7.noarch        @ol7_latest
    Updated iwl5000-firmware-999:8.83.5.1_1-999.18.el7.noarch         @ol7_latest
    Update                   999:8.83.5.1_1-999.19.el7.noarch         @ol7_latest
    Updated iwl5150-firmware-999:8.24.2.2-999.18.el7.noarch           @ol7_latest
    Update                   999:8.24.2.2-999.19.el7.noarch           @ol7_latest
    Updated iwl6000-firmware-999:9.221.4.1-999.18.el7.noarch          @ol7_latest
    Update                   999:9.221.4.1-999.19.el7.noarch          @ol7_latest
    Updated iwl6000g2a-firmware-999:17.168.5.3-999.18.el7.noarch      @ol7_latest
    Update                      999:17.168.5.3-999.19.el7.noarch      @ol7_latest
    Updated iwl6000g2b-firmware-999:17.168.5.2-999.18.el7.noarch      @ol7_latest
    Update                      999:17.168.5.2-999.19.el7.noarch      @ol7_latest
    Updated iwl6050-firmware-999:41.28.5.1-999.18.el7.noarch          @ol7_latest
    Update                   999:41.28.5.1-999.19.el7.noarch          @ol7_latest
    Updated iwl7260-firmware-999:22.0.7.0-999.18.el7.noarch           @ol7_latest
    Update                   999:22.0.7.0-999.19.el7.noarch           @ol7_latest
    Updated iwlax2xx-firmware-999:20230315-999.18.el7.noarch          @ol7_latest
    Update                    999:20230516-999.19.el7.noarch          @ol7_latest
    Erase   kernel-3.10.0-1160.83.1.0.2.el7.x86_64                    @ol7_MODRHCK
    Install kernel-3.10.0-1160.92.1.0.2.el7.x86_64                    @ol7_MODRHCK
    Updated kernel-debug-devel-3.10.0-1160.90.1.0.2.el7.x86_64        @ol7_MODRHCK
    Update                     3.10.0-1160.92.1.0.2.el7.x86_64        @ol7_MODRHCK
    Updated kernel-headers-3.10.0-1160.90.1.0.2.el7.x86_64            @ol7_MODRHCK
    Update                 3.10.0-1160.92.1.0.2.el7.x86_64            @ol7_MODRHCK
    Updated kernel-tools-3.10.0-1160.90.1.0.2.el7.x86_64              @ol7_MODRHCK
    Update               3.10.0-1160.92.1.0.2.el7.x86_64              @ol7_MODRHCK
    Updated kernel-tools-libs-3.10.0-1160.90.1.0.2.el7.x86_64         @ol7_MODRHCK
    Update                    3.10.0-1160.92.1.0.2.el7.x86_64         @ol7_MODRHCK
    Erase   kernel-uek-5.4.17-2136.318.4.el7uek.x86_64                @ol7_developer_UEKR6
    Install kernel-uek-5.4.17-2136.321.2.el7uek.x86_64                @ol7_developer_UEKR6
    Erase   kernel-uek-devel-5.4.17-2136.318.4.el7uek.x86_64          @ol7_developer_UEKR6
    Install kernel-uek-devel-5.4.17-2136.321.2.el7uek.x86_64          @ol7_developer_UEKR6
    Updated kexec-tools-2.0.15-51.0.3.el7_9.3.x86_64                  @ol7_latest/7.9
    Update              2.0.15-51.0.5.el7_9.3.x86_64                  @ol7_latest
    Updated linux-firmware-999:20230315-999.18.gitc761dbe8.el7.noarch @ol7_latest
    Update                 999:20230516-999.19.git6c9e0ed5.el7.noarch @ol7_latest
    Updated nss-pem-1.0.3-7.el7.x86_64                                @anaconda/7.9
    Update          1.0.3-7.el7_9.1.x86_64                            @ol7_latest
    Updated oraclelinux-release-7:7.9-1.0.9.el7.x86_64                @anaconda/7.9
    Update                      7:7.9-1.0.11.el7.x86_64               @ol7_latest
    Updated perf-3.10.0-1160.90.1.0.2.el7.x86_64                      @ol7_MODRHCK
    Update       3.10.0-1160.92.1.0.2.el7.x86_64                      @ol7_MODRHCK
    Updated python-2.7.5-92.0.1.el7_9.x86_64                          @ol7_latest
    Update         2.7.5-93.0.1.el7_9.x86_64                          @ol7_latest
    Updated python-libs-2.7.5-92.0.1.el7_9.x86_64                     @ol7_latest
    Update              2.7.5-93.0.1.el7_9.x86_64                     @ol7_latest
    Updated python-perf-3.10.0-1160.90.1.0.2.el7.x86_64               @ol7_MODRHCK
    Update              3.10.0-1160.92.1.0.2.el7.x86_64               @ol7_MODRHCK
    Updated python2-tracer-0.7.8-1.el7.noarch                         @ol7_developer_EPEL
    Update                 0.7.10-1.el7.noarch                        @epel-neos
    Updated python3-3.6.8-18.0.5.el7.x86_64                           @ol7_latest
    Update          3.6.8-19.0.1.el7_9.x86_64                         @ol7_latest
    Updated python3-libs-3.6.8-18.0.5.el7.x86_64                      @ol7_latest
    Update               3.6.8-19.0.1.el7_9.x86_64                    @ol7_latest
    Updated selinux-policy-3.13.1-268.0.15.el7_9.2.noarch             @ol7_latest
    Update                 3.13.1-268.0.17.el7_9.2.noarch             @ol7_latest
    Updated selinux-policy-targeted-3.13.1-268.0.15.el7_9.2.noarch    @ol7_latest
    Update                          3.13.1-268.0.17.el7_9.2.noarch    @ol7_latest
    Updated tracer-common-0.7.8-1.el7.noarch                          @ol7_developer_EPEL
    Update                0.7.10-1.el7.noarch                         @epel-neos
    Updated yum-3.4.3-168.0.3.el7.noarch                              @anaconda/7.9
    Update      3.4.3-168.0.5.el7.noarch                              @ol7_latest

### Expected behavior

It is expected that flunetd will not crash.

### Your Environment

```markdown
- Fluentd version: fluentd 1.13.3
- TD Agent version:
- Operating system: Oracle Linux Server 7.9
- Kernel version: 5.4.17-2136.321.2.el7uek.x86_64
```

### Your Configuration

```apache
<source>
        @type tail
        tag 687971.LogSecure
        path  /var/log/secure
        pos_file  /etc/unifiedmonitoringagent/pos/687971-LogSecure.pos
        path_key  tailed_path
        <parse>
            @type syslog
        </parse>
    </source>

    <source>
        @type tail
        tag 687971.LogDBWallet
        path  /tmp/splunk/walletPRD.out,/tmp/splunk/walletPRDLGH.out
        pos_file  /etc/unifiedmonitoringagent/pos/687971-LogDBWallet.pos
        path_key  tailed_path
        <parse>
            @type auditdlog
        </parse>
    </source>

    <match 687971.**>
        @type oci_logging
        log_object_id  ocid1.log.oc1.eu-frankfurt-1.ama...
        <buffer tag>
            @type file
            retry_timeout  3h
            path  /opt/unifiedmonitoringagent/run/buffer/687971
            disable_chunk_backup  true
            chunk_limit_size  5MB
            flush_interval  180s
            total_limit_size  1GB
            overflow_action  throw_exception
            retry_type  exponential_backoff
        </buffer>
    </match>
```

### Your Error Log

```shell
id 37ca0df03cec05e7c2ab5d73eb24ead27075d01c
reason:         traps: fluentd[21636] general protection fault ip:7f1f487b9aab sp:7ffc5acefcd0 error:0 in libc-2.17.so[7f1f486a5000+1c4000]
time:           Tue 27 Jun 2023 01:37:35 PM UTC
cmdline:        BOOT_IMAGE=/boot/vmlinuz-5.4.17-2136.321.2.el7uek.x86_64 root=UUID=daec0eb0-26cf-43cb-bcb1-896cdc193242 ro crashkernel=auto LANG=en_US.UTF-8 console=tty0 console=ttyS0,115200 rd.luks=0 rd.lvm=0 rd.md=0 rd.dm=0 rd.iscsi.bypass=1 netroot=iscsi:169.254.0.2:::1:iqn.2015-02.oracle.boot:uefi iscsi_param=node.session.timeo.replacement_timeout=6000 net.ifnames=1 nvme_core.shutdown_timeout=10 ipmi_si.tryacpi=0 ipmi_si.trydmi=0 libiscsi.debug_libiscsi_eh=1 loglevel=4 ip=single-dhcp crash_kexec_post_notifiers crashkernel=auto LANG=en_US.UTF-8 console=tty0 console=ttyS0,115200 rd.luks=0 rd.lvm=0 rd.md=0 rd.dm=0 rd.iscsi.bypass=1 netroot=iscsi:169.254.0.2:::1:iqn.2015-02.oracle.boot:uefi iscsi_param=node.session.timeo.replacement_timeout=6000 net.ifnames=1 nvme_core.shutdown_timeout=10 ipmi_si.tryacpi=0 ipmi_si.trydmi=0 libiscsi.debug_libiscsi_eh=1 loglevel=4 ip=single-dhcp crash_kexec_post_notifiers ipv6.disable=1
uid:            0
Directory:      /var/spool/abrt/oops-2023-06-27-13:37:35-21647-0

id 2975e33d6068ce1bc65ba35d9d824f92c46eb560
reason:         ruby killed by SIGSEGV
time:           Tue 27 Jun 2023 01:37:34 PM UTC
cmdline:        /opt/unified-monitoring-agent/embedded/bin/ruby /opt/unified-monitoring-agent/embedded/bin/fluentd --log /var/log/unified-monitoring-agent/unified-monitoring-agent.log --log-rotate-size 1048576 --log-rotate-age 10
uid:            0
Directory:      /var/spool/abrt/ccpp-2023-06-27-13:37:34-21636
```

**Comment by PeterP55P** [comment]
Hi meantime I fond out that the problem is caused by glibc packages in version 2.17-326.0.**5**.el7_9.x86_64. I did several tests and the problem occurs only when this version of glibc is being used.

**Comment by daipom** [comment]
Thanks for your report!
