### ISSUE TITLE
Shared library not found

### ISSUE THREAD

**Issue by mixmind** [fluent/fluentd#4235]
### Describe the bug

Installing td-agent on ubuntu 22 I found that there is missed shared library:
```markdown
ldd /opt/td-agent/lib/ruby/3.1.0/x86_64-linux/enc/cesu_8.so
	linux-vdso.so.1 (0x00007ffe671dc000)
	libruby.so.3.1 => not found
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f72484bd000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f7248295000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f72485ae000)
```

There are more files with same problem, showed one for example

### To Reproduce

```
docker run -it --rm ubuntu:22.04 bash
apt update && apt install curl sudo -y
curl -L https://toolbelt.treasuredata.com/sh/install-ubuntu-jammy-td-agent4.sh | sh
ldd /opt/td-agent/lib/ruby/3.1.0/x86_64-linux/enc/cesu_8.so

```

### Expected behavior

*.so files are finding libruby.so.3.1

### Your Environment

```markdown
- Fluentd version: 1.16.1
- TD Agent version: 4.5.0
- Operating system: ubuntu 22.04
- Kernel version: 5.19.0-45-generic
```

### Your Configuration

```apache
No need
```

### Your Error Log

```shell
No need
```

### Additional context

Actually, I have solved it with env variable 
`LD_LIBRARY_PATH=/usr/local/lib:/usr/lib:/opt/td-agent/lib`
but I think it should work without it

**Comment by mixmind** [comment]
so there is no need in something that I should add, just use td-agent as usual?

**Comment by ashie** [comment]
That's right.

**Comment by mixmind** [comment]
Thank you for explanation and sorry for wasting your time
