### ISSUE TITLE
Raise min. required Ruby version

### ISSUE THREAD

**Issue by Garfield96** [fluent/fluentd#4242]
### Is your feature request related to a problem? Please describe.

Currently, the minimum required Ruby version for Fluentd is 2.4, which reached EOL on 2020-03-31. The oldest Ruby version tested in CI runs is 2.7, which reached EOL on 2023-03-31. Supporting these versions not only endorses users to run outdated, potentially even vulnerable systems but also makes it difficult to use new language features (e.g. ractors).

### Describe the solution you'd like

Drop support for Ruby 2.x or at least raise the min. required version to 2.7. In addition, the min. required version should not be based on arbitrary value, but instead, there should be a clear rule, like "Fluentd supports all maintained Ruby versions". 

### Describe alternatives you've considered

I don't think there is an alternative in the long run.

### Additional context

Ruby version overview: https://www.ruby-lang.org/en/downloads/branches/

**Comment by daipom** [comment]
Thanks for your report!
The Fluent Package (we will change the name from td-agent), which we are about to release soon, will embed Ruby 3.
We also need to consider that min version in Fluentd itself.

https://github.com/fluent/fluentd/blob/d5685ada81ac89a35a79965f1e94bbe5952a5d3a/fluentd.gemspec#L19

**Comment by arminru** [comment]
I think this has been addressed with https://github.com/fluent/fluentd/pull/4288 so the issue could be closed.

**Comment by ashie** [comment]
Fixed in #4288
Thanks for your report!
