### ISSUE TITLE
Have issues with timestamp with OCI logging analytics logs using td-agent version 4

### ISSUE THREAD

**Issue by karthikpb88** [fluent/fluentd#4259]
### Describe the bug

I'm using centos 7.
Installed td-agent version 4.
My VM timezone is PDT but when logs are pushed to OCI
I see the timestamp difference which is 7 hours behind.
Meaning, I need to query logs in OCI with 8 hours or more to see the current logs coming up.

### To Reproduce

N/A

### Expected behavior

To see current logs by query with 15,30 and 60 mins in Oracle Logging Analytics

### Your Environment

```markdown
- Fluentd version:
- TD Agent version:
- Operating system:
- Kernel version:
```

### Your Configuration

```apache
- TD Agent version:td-agent version 4
- Operating system: centos 7
- Kernel version: 5.4.17-2136.314.6.3.el7uek.x86_64
```

### Your Error Log

```shell
N/A
```

**Comment by daipom** [comment]
Please follow our guideline.
With this information, we can't judge if this is a bug.

If you need to question how to convert the timezone, please use Discussions.
