### ISSUE TITLE
Dependency tree broken for Ubuntu 22.04

### ISSUE THREAD

**Issue by sagarsaini1** [fluent/fluentd#4260]
### Is your feature request related to a problem? Please describe.

dependency tree is broken for ubuntu 22.04; unable to install

### Describe the solution you'd like

this broken dependency issue to be resolved.

### Describe alternatives you've considered

tried solving the issue with installing the dependency libraries manually but that didn't work.

### Additional context

this is the error I'm facing: 
`Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 td-agent : Depends: libssl1.1 (>= 1.1.1) but it is not installable
E: Unable to correct problems, you have held broken packages.`

**Comment by ashie** [comment]
Which version of td-agent (or any other package?) did you attempt to install?
We already provide td-agent that support Ubuntu 22.04 (jammy):
https://td-agent-package-browser.herokuapp.com/4/ubuntu/jammy/pool/contrib/t/td-agent

Please follow the instruction steps of `Ubuntu Jammy`:
https://docs.fluentd.org/installation/install-by-deb#step-1-install-from-apt-repository
