### ISSUE TITLE
enable multiline parsing when source is an  S3 file

### ISSUE THREAD

**Issue by valentinacala** [fluent/fluentd#4265]
### Is your feature request related to a problem? Please describe.

I noticed me and many users are wondering to be able to recognize logs that are on many lines. 

Currently any plugin seemes to satisfy the thing, because:
- the fluentd multiline parsers applys on in_tail input only
- the [fluent-plugin-concat](https://github.com/fluent-plugins-nursery/fluent-plugin-concat) plugin works only if the numeber of lines is well defined

### Describe the solution you'd like

I propose to enable the parser multiline even if the source is S3

### Describe alternatives you've considered

It could be addressed within the plugin [fluent-plugin-s3](https://github.com/fluent/fluent-plugin-s3).
Otherwise, I need to create a layer that brings files from S3 to a file system, pouring the performances and increasing the architecture complexity

**Comment by kenhys** [comment]
It seems that S3 input plugin accepts multiline parser, does not fit for you?
