### ISSUE TITLE
Missing logs at the beginning of files

### ISSUE THREAD

**Issue by samkyuseo** [fluent/fluentd#4278]
### Describe the bug

I'm running a fluentd daemonset on a kubernetes cluster. Throughput is relatively low at around 200 lines per minute per node. When I delete a pod, I'm missing the first few log lines for the pod (~30-40 seconds worth). 

### To Reproduce

Run the fluentd daemonset on your kubernetes cluster. Write a service that generates logs pretty quickly on startup and deploy as a pod. Restart the pod using `kubectl delete pod <pod_name>`.  Notice that the first few log lines aren't sent to the destination.

### Expected behavior

I expect the logs in the beginning of the pod logs to be sent as well. 

### Your Environment

```markdown
- Fluentd version: fluentd-kubernetes-daemonset:v1.15-debian-elasticsearch7-1
- TD Agent version: 
- Operating system: Ubuntu 20.04.4 LTS
- Kernel version: Linux 5.15.0-79-generic
```

### Your Configuration

```apache
pods-fluent.conf: |-
    <source>
      @type tail
      read_from_head true
      tag kubernetes.*
      path /var/log/containers/*.log
      pos_file /var/log/fluentd-containers.log.pos
      exclude_path []
      <parse>
        @type kubernetes
        @type json
        time_format %Y-%m-%dT%H:%M:%S.%NZ
      </parse>
    </source>
    <filter kubernetes.**>
      @type kubernetes_metadata
      skip_labels true
      skip_container_metadata true
      skip_master_url true
      skip_namespace_metadata true
    </filter>
    <filter kubernetes.**>
      @type record_transformer
      enable_ruby
      <record>
        event ${record}
        time ${time.to_i}
      </record>
      remove_keys docker,$.kubernetes.pod_id,$.kubernetes.pod_ip,log,stream,kubernetes
    </filter>
```

### Your Error Log

```shell
No error logs. Logs are simply not being sent.
```

**Comment by kenhys** [comment]
How about trying to use `flush_at_shutdown`?

https://docs.fluentd.org/configuration/buffer-section#flushing-parameters
