### ISSUE TITLE
 When using http input plugin without the content header,  the character ; causes fluentd to split the json document 

### ISSUE THREAD

**Issue by DavidRomao** [fluent/fluentd#4293]
### Describe the bug

When sending an event to fluentd through the HTTP input plugin without setting the Content-Type header, I observed that if I the JSON document contains the character **;** fluentd splits the document and treats it as two separate events, causing it to fail to parse the event since after splitting it stops being a valid JSON document.

However If I set the Content-Type header and remove the prefix `json=`  from the body, it works as expected. 

### To Reproduce

Send the following request

```shell
curl -X POST --location "http://localhost:9880/tag.value" \
        -d "json=[{\"log\":\"message ; remaining message\"}]"
```

The logs show now show the following error: 
> incoming event is invalid: path=/jenkins.jobs params={"json":"{\"log\":\"message "," remaining message\"}"

### Expected behavior

On the error message it says the JSON field is `{\"log\":\"message "," remaining message\"}` 

It should be `{\"log\":\"message ; remaining message\"}` 

Here's a diff that hopefully makes the difference clearer
```diff
- {\"log\":\"message "," remaining message\"}
+ {\"log\":\"message ; remaining message\"}
```

I'd expect the same behavior when specifying the content type, as done in this request :
```shell
curl -X POST --location "http://localhost:39880/tag.value" \
        -H "Content-Type: application/json" \
        -d "{\"log\":\"message ; remaining message\"}"
```
Which correctly logs the event 
```shell
2023-09-08T13:48:59.494183445Z 2023-09-08 13:48:59.492883945 +0000 tag.value: {"log":"message ; reamining message"}
```

### Your Environment

```markdown
I tested with the docker image `fluent/fluentd:v1.16.2-1.0`

- Fluentd version: 1.16.2-1.0
```

### Your Configuration

```apache
<system>
  log_level debug
</system>

<source>
  @type http
  port 9880
  bind 0.0.0.0
  body_size_limit 32m
  keepalive_timeout 10s
</source>

<match **>
  @type stdout
</match>
```

### Your Error Log

```shell
2023-09-08 14:02:40 +0000 [debug]: #0 fluent/log.rb:341:debug: incoming event is invalid: path=/tag.value params={"json":"{\"log\":\"message "," remaining message\"}":"","HTTP_HOST":"localhost:39880","HTTP_USER_AGENT":"curl/7.81.0","HTTP_ACCEPT":"*/*","HTTP_CONTENT_LENGTH":"42","HTTP_CONTENT_TYPE":"application/x-www-form-urlencoded","REMOTE_ADDR":"172.19.0.1"}
2023-09-08T14:02:40.937766828Z 2023-09-08 14:02:40.937349433 +0000 fluent.debug: {"message":"incoming event is invalid: path=/tag.value params={\"json\":\"{\\\"log\\\":\\\"message \",\" remaining message\\\"}\":\"\",\"HTTP_HOST\":\"localhost:39880\",\"HTTP_USER_AGENT\":\"curl/7.81.0\",\"HTTP_ACCEPT\":\"*/*\",\"HTTP_CONTENT_LENGTH\":\"42\",\"HTTP_CONTENT_TYPE\":\"application/x-www-form-urlencoded\",\"REMOTE_ADDR\":\"172.19.0.1\"}"}
```

**Comment by daipom** [comment]
Thanks for your report, but this is not a bug. This is the expected behavior.

`curl` command seems to send the data with `x-www-form-urlencoded` Content-type by default.
So `in_http` tries to parse the received data as a URL.
This is the expected behavior.

As you notice, you need to specify `-H "Content-Type: application/json"`.

**Comment by daipom** [comment]
> Then I suggest the documentation ( https://docs.fluentd.org/input/http#basic-usage ) is updated to mention the `Content-Type` which needs to be sent if we want to use the syntax with the prefix like `json=` . I'll gladly open a PR for that if you agree

Thanks @DavidRomao!
I agree! Certainly, this documentation is confusing. We should improve it.
Of course, we welcome a PR :)

Those examples seem to assume Content-Type `x-www-form-urlencoded`.
It would be better to specify that the data is parsed as a URL in this way.
Also, adding an example of `-H "Content-Type: application/json"` would make it clearer.
