### ISSUE TITLE
Fluentd sending warn logs to elasticsearch which shouldn't be sent as per config

### ISSUE THREAD

**Issue by SoodPrerit** [fluent/fluentd#4308]
### Describe the bug

I am facing an issue where fluentd floods a lot of logs when elasticsearch memory utilization is more. Below are the log lines which shouldn't be pushed to elasticsearch but are getting pushed and in millions

[warn]: [elasticsearch] failed to flush the buffer. retry_times=125 next_retry_time=2023-09-05 12:29:07 +0000 chunk="604972dd0d1868f9a5a037f5bbe60c81" error_class=Fluent::Plugin::ElasticsearchOutput::RecoverableRequestFailure error="could not push logs to Elasticsearch cluster ({:host=>"vpc-XXXXXXXXXXXXXXXXXXXXXXXX.eu-XXXXX.es.amazonaws.com", :port=>443, :scheme=>"https", :user=>"xxxxxxxx", :password=>"XXXXXX"}): request timed out"

In my fluentd config I have already excluded the logs for fluentd to be sent to elastcisearch using below config

```yaml
    <label @FLUENT_LOG> 
      <match fluent.**> 
        @type null 
        @id ignore_fluent_logs 
      </match> 
    </label>
```

I am not sure why even after with above config, fluentd is sending these log lines to the elasticsearch index ??? Please help answering this question. 

### To Reproduce

- Run fluentd container setup in kubernetes 
- Use above mentioned configuration to exclude fluentd's own logs
- When elasticsearch memory is exhausted. Above log lines are pushed to elastic search.

### Expected behavior

Below logs should not be pushed to elasticsearch since these are excluded in configmap

[warn]: [elasticsearch] failed to flush the buffer. retry_times=125 next_retry_time=2023-09-05 12:29:07 +0000 chunk="604972dd0d1868f9a5a037f5bbe60c81" error_class=Fluent::Plugin::ElasticsearchOutput::RecoverableRequestFailure error="could not push logs to Elasticsearch cluster ({:host=>"vpc-XXXXXXXXXXXXXXXXXXXXXXXX.eu-XXXXX.es.amazonaws.com", :port=>443, :scheme=>"https", :user=>"xxxxxxxx", :password=>"XXXXXX"}): request timed out"

### Your Environment

```markdown
- Fluentd version:
- TD Agent version:
- Operating system: EKS(k8s-1.25)
- Kernel version:
```

### Your Configuration

```apache
<label @FLUENT_LOG> 
      <match fluent.**> 
        @type null 
        @id ignore_fluent_logs 
      </match> 
    </label>
```

### Your Error Log

```shell
NA
```

**Comment by daipom** [comment]
Thanks for your report.

Do you mean some Fluentd's logs are sent to Elasticsearch and some are not?
And it occurs only when Elasticsearch's memory is exhausted?

**Comment by Shivam0609** [comment]
@daipom , any idea about what could be causing this issue ?

This has been bugging us from quite a long time now and we are getting millions of logs pushed to elasticsearch which are not relevant.

**Comment by daipom** [comment]
Sorry. I don't have time this week to check the details.
I'll check it next week if I can.
Could you please share the whole setting as much as possible?
