### ISSUE TITLE
All outputs in copy plugin are affected even when any one of the outputs in copy is in error

### ISSUE THREAD

**Issue by brucelee138** [fluent/fluentd#4337]
### Describe the bug

We are using the copy plugin of fluentd to stream logs in a k8s cluster to multiple rsyslog servers (using [syslog-tls](https://github.com/zarqman/fluent-plugin-syslog-tls) plugin).
We observed that when any 1 of the rsyslog server becomes reachable, log streaming is affected for all the rsyslog servers streamed with fluentd pods throwing socket timeout errors (full logs in error logs section).

We tried using the "ignore_error" option in <store> section, but we still see the same issue. 

### To Reproduce

Configure multiple outputs in copy plugin of type rsyslog_tls plugin with 1 of the output host unreachable.

### Expected behavior

Error/Exception in any of the outputs of the copy plugin should not affect the other outputs present in it.

### Your Environment

```markdown
- Fluentd version: 1.16.2
- TD Agent version:
- Operating system: SUSE linux
- Kernel version: 5.14.21
```

### Your Configuration

```apache
<match {kube.var.log.containers.**}>
      @type copy
      <store ignore_error>
        @type http
        endpoint https://<unreachable ip>:9000/api
        open_timeout 2
        <format>
          @type json
        </format>
      </store>
      <store ignore_error>
        @type syslog_tls
        host <unreachable ip>
        port 515
        ca_cert /fluentd-out/ssl/ca.crt
        client_cert /fluentd-out/ssl/tls.crt
        client_key /fluentd-out/ssl/tls.key
        verify_cert_name true
        hostname_key nodename
        facility AUTH
        severity_key severity
        format json
      </store>
      <store ignore_error>
        @type syslog_tls
        host <reachable ip>
        port 514
        ca_cert /fluentd-out/ssl/ca.crt
        client_cert /fluentd-out/ssl/tls.crt
        client_key /fluentd-out/ssl/tls.key
        verify_cert_name true
        hostname_key nodename
        facility AUTH
        severity_key severity
        format json
      </store>
    </match>
```

### Your Error Log

```shell
2023-11-02 04:15:16 +0000 [debug]: #0 [in_prometheus]    19m: Async::HTTP::Server
      | Incoming connnection from #<Addrinfo: [::ffff:10.0.10.10]:59160 TCP> to Async::HTTP::Protocol::HTTP1
2023-11-02 04:15:17 +0000 [trace]: #0 fluent/log.rb:319:trace: enqueueing all chunks in buffer instance=70080484621300
2023-11-02 04:15:22 +0000 [trace]: #0 fluent/log.rb:319:trace: enqueueing all chunks in buffer instance=70080484621300
2023-11-02 04:15:23 +0000 [error]: #0 fluent/log.rb:404:error: Socket timeout during connect_write
2023-11-02 04:15:23 +0000 [trace]: #0 fluent/log.rb:319:trace: writing events into buffer instance=70080484621300 metadata_size=1
2023-11-02 04:15:26 +0000 [debug]: #0 [in_prometheus]    19m: Async::HTTP::Server
      | Incoming connnection from #<Addrinfo: [::ffff:10.0.10.10]:63408 TCP> to Async::HTTP::Protocol::HTTP1
2023-11-02 04:15:26 +0000 [debug]: #0 [in_prometheus]    19m: Async::HTTP::Server
      | Incoming connnection from #<Addrinfo: [::ffff:10.0.10.10]:63420 TCP> to Async::HTTP::Protocol::HTTP1
2023-11-02 04:15:28 +0000 [trace]: #0 fluent/log.rb:319:trace: enqueueing all chunks in buffer instance=70080484621300
2023-11-02 04:15:33 +0000 [trace]: #0 fluent/log.rb:319:trace: enqueueing all chunks in buffer instance=70080484621300
2023-11-02 04:15:33 +0000 [error]: #0 fluent/log.rb:404:error: Socket timeout during connect_write
```

**Comment by ashie** [comment]
> We observed that when any 1 of the rsyslog server becomes reachable,

typo?
```diff
- We observed that when any 1 of the rsyslog server becomes reachable,
+ We observed that when any 1 of the rsyslog server becomes unreachable,
```

> log streaming is affected for all the rsyslog servers streamed with fluentd pods throwing socket timeout errors (full logs in error logs section).

What do you mean `affected`?
Do you mean transferring logs to `<reachable ip>` is delayed until `timeout` is occurred?
Is so, it's expected behaviour with `syslog_tls` plugin.

syslog_tls blocks any trailing processes until connections is established:
https://github.com/zarqman/fluent-plugin-syslog-tls/blob/676846faae646548aa9795f63773d7c3a4cce899/lib/syslog_tls/ssl_transport.rb#L45-L59
https://github.com/zarqman/fluent-plugin-syslog-tls/blob/676846faae646548aa9795f63773d7c3a4cce899/lib/fluent/plugin/out_syslog_tls.rb#L137-L146

**Comment by brucelee138** [comment]
@ashie Thanks for checking this. 
Sorry for the typo, yes, I had meant when any 1 of the rsyslog server becomes **unreachable**
Yes, we meant the log streaming to <reachable-ip> is paused till the timeout is reached and even after the delay only very few logs are streamed.
Thanks for pointing me to syslog_tls behaviour, I would check this and come back.

**Comment by brucelee138** [comment]
@ashie Is there a way to ensure that copy plugin copies the outputs to the "stores" parallelly instead of sequentially so that blocking in processing of 1 of the store affects the others?

**Comment by ashie** [comment]
Buffered plugin doesn't block there, but syslog_tls plugin isn't buffered plugin.
