### ISSUE TITLE
tail plugin stops tailing the log files which are rotated based on file size.

### ISSUE THREAD

**Issue by deepaksb2** [fluent/fluentd#4362]
### Describe the bug

The application log rotation policy is defined based on log file size to limit the disk space consumption.
It is observed after some days fluentd tail plugin skip the file rotation and entire file contents are lost. 

The log files are generated in below format and each log file size is limit to 4096MB

applog.log
applog.log.1
applog.log.2
applog.log.3
and so on to max 10

### To Reproduce

Tail the files which is rotated based on size (let's say 9 MB).

applog.log
applog.log.1
applog.log.2
applog.log.3
and so on (upto 12 files)

### Expected behavior

The rotating files must not be skipped which cause data loss of entire rotated file contents

### Your Environment

```markdown
- Fluentd version: 1.16.1
- TD Agent version: 
- Operating system: RHEL 8
- Kernel version:4.18.0-477.13.1.el8_8.x86_64
```

### Your Configuration

```apache
I have the below tail plugin configuration and I observed the tail plugin stops reading the data from the log file which is writing new logs of application.

<source>
@type tail path /opt/appxyz/logs/applog.log
tag xyzApplogingest
read_from_head false 
pos_file /opt/td-agent/fluentd/file-tail.log.pos 
follow_inodes true 
refresh_interval 2 
skip_refresh_on_startup true 
enable_stat_watcher false 
from_encoding UTF-8 
encoding UTF-8 
exclude_path [""] 
multiline_flush_interval 5s 
<parse>
    @type none
  </parse>
</source>
```

### Your Error Log

```shell
No errors in log but observing log statement difference between working on not working (when file is skipped) when file is rotated 
Working logs:
2023-12-11 12:11:32 -0500 [info]: #7 following tail of /opt/appxyz/logs/applog.log
	Line  6110: 2023-12-11 12:11:32 -0500 [info]: #7 detected rotation of /opt/appxyz/logs/applog.log; waiting 5 seconds

Non Working: (log related to "detected rotation of .... " is missing" 
2023-12-11 13:25:16 -0500 [info]: #7 following tail of /opt/appxyz/logs/applog.log
```

### Additional context

Looks like fluentd tail plugin fails to detect log rotation.

**Comment by ashie** [comment]
Could you try fluentd v1.16.2 or later?
v1.16.2 and v1.16.3 fixes known in_tail stop issues:
* [v1.16.2](https://github.com/fluent/fluentd/blob/master/CHANGELOG.md#release-v1162---20230714)
* [v1.16.3](https://github.com/fluent/fluentd/blob/master/CHANGELOG.md#release-v1163---20231114)

**Comment by deepaksb2** [comment]
> Could you try fluentd v1.16.2 or later? v1.16.2 and v1.16.3 fixes known in_tail stop issues:
> 
> * [v1.16.2](https://github.com/fluent/fluentd/blob/master/CHANGELOG.md#release-v1162---20230714)
> * [v1.16.3](https://github.com/fluent/fluentd/blob/master/CHANGELOG.md#release-v1163---20231114)

Thanks for the response, I will try with 1.16.3 .

**Comment by deepaksb2** [comment]
Will try with latest version and update.
Closing for now.
