### ISSUE TITLE
@type stdout not working if redirect fluentd logs to a file using -o "filepath"

### ISSUE THREAD

**Issue by pratikshavyas** [fluent/fluentd#4366]
### Describe the bug

Hi,

I have a use case to redirect fluentd's own logs to a file which is done by the below option:
fluentd -o /path/to/log_file

I have another requirement where I need to read logs from a different file and send it to stdout. I have used below config to achieve this by having a source section to read from the file and then a match section with stdout type.
\<source\> @type tail path /tmp/*.log pos_file /tmp/td-agent.pos read_from_head true tag test \<parse\> @type json \</parse\> \</source\> \<match test\> @type stdout \<format\> @type json \</format\> \</match\>

However, I observe that even logs from this file path is also going to the redirected log file only and not coming to stdout.
Please suggest some way to achieve the above explained use case.
Thanks in advance.

### To Reproduce

Redirect fluentd logs to a file during startup
/usr/sbin/fluentd -o logfile_path
and provide below configuration to fluentd
<source\> @type tail path /tmp/*.log pos_file /tmp/td-agent.pos read_from_head true tag test \<parse\> @type json \</parse\> \</source\> \<match test\> @type stdout \<format\> @type json \</format\> \</match\>

### Expected behavior

Logs read from source file should be outputted to stdout and should not go to redirected log file path.

### Your Environment

```markdown
- Fluentd version:1.16.2
```

### Your Configuration

```apache
<source\> @type tail path /tmp/*.log pos_file /tmp/td-agent.pos read_from_head true tag test \<parse\> @type json \</parse\> \</source\> \<match test\> @type stdout \<format\> @type json \</format\> \</match\>
```

### Your Error Log

```shell
There is no error. Logs read from source file are not coming on stdout and getting redirected to file
```

**Comment by kenhys** [comment]
`@type stdout` is affected by `-o` option.
So, there is no wonder that matched event will be logged into redirected to file.

**Comment by daipom** [comment]
> `@type stdout` is affected by `-o` option. So, there is no wonder that matched event will be logged into redirected to file.

So, this is the current specification of Fluentd.
