### ISSUE TITLE
in_windows_eventlog documentation and module issues.

### ISSUE THREAD

**Issue by gawainXX** [fluent/fluentd#4388]
### Describe the bug

Greetings, I see in the logs that windows_eventlog is marked for deprecation. I could not find an appearant replacement in the documentation for in_windows_eventlog , Is there a replacement module ready or planned for it?

Additionally, I'm having difficulty collecting Security and System events, Application works fine though, any advice?

### To Reproduce

See attached XML

### Expected behavior

Lifecycle status such as discontinuation of support or replacement is clearly documented for in_windows_eventlog,

### Your Environment

```markdown
- Fluentd version: latest
- TD Agent version: ?
- Operating system: Windows Server 2022 (Desktop Experience)
- Kernel version: ??
```

### Your Configuration

```apache
<source>
  @type windows_eventlog
  @id windows_eventlog_system
  channels System
  tag winevent_system
  <storage>
    @type local
    persistent true
    path C:\opt\fluent\pos\winevt_system.pos
  </storage>
</source>

<source>
  @type windows_eventlog
  @id windows_eventlog_auth
  channels Security
  tag winevent_auth
  <storage>
    @type local
    persistent true
    path C:\opt\fluent\pos\winevt_auth.pos
  </storage>
</source>

<source>
  @type windows_eventlog
  @id windows_eventlog_application
  channels Application
  tag winevent_application
  <storage>
    @type local
    persistent true
    path C:\opt\fluent\pos\winevt_application.pos
  </storage>
</source>

<source>
  @type tail
  path "C:\\ProgramData\\Quest\\KACE\\user\\KAgent.log"
  pos_file "C:\\opt\\fluent\\pos\\KAgent.log.pos"
  tag "kace.log"
  format none
</source>

<match winevent_system>
  @type remote_syslog
  host REDACTED
  port 514
  protocol udp
  severity info
  facility Daemon
</match>

<match winevent_security>
  @type remote_syslog
  host REDACTED
  port 514
  protocol udp
  severity info
  facility Auth
</match>

<match winevent_application>
  @type remote_syslog
  host REDACTED
  port 514
  protocol udp
  severity info
  facility local7
</match>

<match kace.log>
  @type remote_syslog
  host REDACTED
  port 514
  protocol udp
  severity info
  facility local0
</match>

<label @FLUENT_LOG>
  <match **>
    @type remote_syslog
    host REDACTED
    port 514
    protocol udp
    severity info
    facility syslog
  </match>
</label>
```
```


### Your Error Log

```shell
REDACTED due to sensitive info, can provide upon request.
```

**Comment by ashie** [comment]
Please use in_windows_eventlog2 instead.
It's bundled in latest fluent-plugin-windows-eventlog so probably it's already installed in your system with windows_eventlog.
https://github.com/fluent/fluent-plugin-windows-eventlog

**Comment by gawainXX** [comment]
Thank you, can you please update the documentation for windows event log to
mention it's deprecated status and link to it's successor?

**Comment by ashie** [comment]
Ah sorry, I didn't understand which `document` you were pointing to.
Now I've noticed you pointed out about this log:
https://github.com/fluent/fluent-plugin-windows-eventlog/blob/b34901a9d429dc1a99b67259daf1f85e0f1eb567/lib/fluent/plugin/in_windows_eventlog.rb#L52
```ruby
      log.warn "in_windows_eventlog is deprecated. It will be removed in the future version."
```

Thanks notifying it, I'll fix it.
