### ISSUE TITLE
Td-agent windows fluentd connector log file is not getting rolled over (only td-agent.log file) 

### ISSUE THREAD

**Issue by deepaksb2** [fluent/fluentd#4390]
### Describe the bug

We have installed td-agent on windows 2019 server (or any version) and observed the td-agent.log file is not getting rolled over when log file size is  reached to specified --log-rotate-size.

td-agent is installed using CLI  with below command

call "%FLUENTD_EXECUTABLE%" --reg-winsvc i --winsvc-name %CONNECTOR_NAME% --winsvc-display-name %CONNECTOR_NAME%  --winsvc-desc "FluentD log collection"  --reg-winsvc-fluentdopt '-c %ETC_TD_AGENT_DIR%/td-agent.conf -p %ETC_TD_AGENT_DIR%/plugin --log %TD_AGENT_DIR%/td-agent.log  --log-rotate-age 10 --log-rotate-size 100000' 

The worker thread log files are rolling over as expected
 

### To Reproduce

Install the td-agent with command line arguments and td-agent.log file is not rolling over after it reached to log-rotate-size

### Expected behavior

The td-agent log file should be rolled over 

### Your Environment

```markdown
- Fluentd version:fluentd 1.16.3 
- TD Agent version: td-agent 4.5.2 
- Operating system: Windows 2019
- Kernel version:
```

### Your Configuration

```apache
Any configuration with default values
```

### Your Error Log

```shell
No error seen
```

### Additional context

This only happens in windows fluentd and not on linux environment

**Comment by daipom** [comment]
Thanks for your report.

> Install the td-agent with command line arguments and td-agent.log file is not rolling over after it reached to log-rotate-size

Do you mean that you installed td-agent by the msi installer, and deleted the default td-agent Service, and registered your own Windows Service by the command?

**Comment by deepaksb2** [comment]
> Thanks for your report.
> 
> > Install the td-agent with command line arguments and td-agent.log file is not rolling over after it reached to log-rotate-size
> 
> Do you mean that you installed td-agent by the msi installer, and deleted the default td-agent Service, and registered your own Windows Service by the command?

I installed td-agent by msi installer, took the entire exploded package folder, uninstalled the td-agent , and then installed from CLI with customizations.

**Comment by kenhys** [comment]
I guess that registry is not correctly updated.

Anyway, td-agent 4 was already reached EOL, so close it.
