### ISSUE TITLE
fluent/lib/ruby/3.2.0/win32/registry.rb:910:in `encode': U+767E to ASCII-8BIT in conversion from UTF-16LE to UTF-8 to ASCII-8BIT (Encoding::UndefinedConversionError)

### ISSUE THREAD

**Issue by Sic9527** [fluent/fluentd#4414]
### Describe the bug

Windows 11  run fluentd  error：
D:/opt/fluent/lib/ruby/3.2.0/rubygems.rb:1342:in `rescue in <top (required)>': U+767E to ASCII-8BIT in conversion from UTF-16LE to UTF-8 to ASCII-8BIT (Encoding::UndefinedConversionError)
Loading the D:/opt/fluent/lib/ruby/3.2.0/rubygems/defaults/operating_system.rb file caused an error. This file is owned by your OS, not by rubygems upstream. Please find out which OS package this file belongs to and follow the guidelines from your OS to report the problem and ask for help.
        from D:/opt/fluent/lib/ruby/3.2.0/rubygems.rb:1328:in `<top (required)>'
        from <internal:gem_prelude>:2:in `require'
        from <internal:gem_prelude>:2:in `<internal:gem_prelude>'
D:/opt/fluent/lib/ruby/3.2.0/win32/registry.rb:910:in `encode': U+767E to ASCII-8BIT in conversion from UTF-16LE to UTF-8 to ASCII-8BIT (Encoding::UndefinedConversionError)
        from D:/opt/fluent/lib/ruby/3.2.0/win32/registry.rb:910:in `export_string'
        from D:/opt/fluent/lib/ruby/3.2.0/win32/registry.rb:611:in `each_key'
        from D:/opt/fluent/lib/ruby/site_ruby/3.2.0/ruby_installer/runtime/msys2_installation.rb:71:in `block (2 levels) in iterate_msys_paths'
        from D:/opt/fluent/lib/ruby/3.2.0/win32/registry.rb:435:in `open'
        from D:/opt/fluent/lib/ruby/3.2.0/win32/registry.rb:542:in `open'
        from D:/opt/fluent/lib/ruby/site_ruby/3.2.0/ruby_installer/runtime/msys2_installation.rb:70:in `block in iterate_msys_paths'
        from D:/opt/fluent/lib/ruby/site_ruby/3.2.0/ruby_installer/runtime/msys2_installation.rb:68:in `each'
        from D:/opt/fluent/lib/ruby/site_ruby/3.2.0/ruby_installer/runtime/msys2_installation.rb:68:in `iterate_msys_paths'
        from D:/opt/fluent/lib/ruby/site_ruby/3.2.0/ruby_installer/runtime/msys2_installation.rb:102:in `msys_path'
        from D:/opt/fluent/lib/ruby/site_ruby/3.2.0/ruby_installer/runtime/msys2_installation.rb:115:in `mingw_bin_path'
        from D:/opt/fluent/lib/ruby/site_ruby/3.2.0/ruby_installer/runtime/msys2_installation.rb:125:in `enable_dll_search_paths'
        from D:/opt/fluent/lib/ruby/site_ruby/3.2.0/ruby_installer/runtime/singleton.rb:27:in `enable_dll_search_paths'
        from D:/opt/fluent/lib/ruby/3.2.0/rubygems/defaults/operating_system.rb:24:in `<top (required)>'
        from D:/opt/fluent/lib/ruby/3.2.0/rubygems.rb:1332:in `require'
        from D:/opt/fluent/lib/ruby/3.2.0/rubygems.rb:1332:in `<top (required)>'
        from <internal:gem_prelude>:2:in `require'
        from <internal:gem_prelude>:2:in `<internal:gem_prelude>'
2024-02-28 14:24:25 +0800 [error]: Worker 0 exited unexpectedly with status 1
D:/opt/fluent/lib/ruby/3.2.0/rubygems/specification.rb:10:in `require_relative': Interrupt
        from D:/opt/fluent/lib/ruby/3.2.0/rubygems/specification.rb:10:in `<top (required)>'
        from D:/opt/fluent/lib/ruby/3.2.0/rubygems.rb:1325:in `require_relative'
        from D:/opt/fluent/lib/ruby/3.2.0/rubygems.rb:1325:in `<top (required)>'
        from <internal:gem_prelude>:2:in `require'
        from <internal:gem_prelude>:2:in `<internal:gem_prelude>'

### To Reproduce

Initial installation

### Expected behavior

normal running load

### Your Environment

```markdown
2024-02-28 14:34:34 +0800 [info]: fluent/log.rb:362:info: init supervisor logger path=nil rotate_age=30 rotate_size=nil
2024-02-28 14:34:34 +0800 [info]: fluent/log.rb:362:info: parsing config file is succeeded path="D:/opt/fluent//etc/fluent/fluentd.conf"
2024-02-28 14:34:34 +0800 [info]: fluent/log.rb:362:info: gem 'fluentd' version '1.16.3'
2024-02-28 14:34:34 +0800 [info]: fluent/log.rb:362:info: gem 'fluent-plugin-calyptia-monitoring' version '0.1.3'
2024-02-28 14:34:34 +0800 [info]: fluent/log.rb:362:info: gem 'fluent-plugin-elasticsearch' version '5.4.0'
```

### Your Configuration

```apache
<source>
  @type windows_eventlog2
  @id windows_eventlog2
  channels application
  read_existing_events false
  tag winevt.raw
  rate_limit 200
  <storage>
    @type local
    persistent true
    path D:\opt\fluent\winlog.json
  </storage>
</source>

<match winevt.raw>
  @type stdout
</match>
```

### Your Error Log

```shell
D:/opt/fluent/lib/ruby/3.2.0/rubygems.rb:1342:in `rescue in <top (required)>': U+767E to ASCII-8BIT in conversion from UTF-16LE to UTF-8 to ASCII-8BIT (Encoding::UndefinedConversionError)
Loading the D:/opt/fluent/lib/ruby/3.2.0/rubygems/defaults/operating_system.rb file caused an error. This file is owned by your OS, not by rubygems upstream. Please find out which OS package this file belongs to and follow the guidelines from your OS to report the problem and ask for help.
        from D:/opt/fluent/lib/ruby/3.2.0/rubygems.rb:1328:in `<top (required)>'
        from <internal:gem_prelude>:2:in `require'
        from <internal:gem_prelude>:2:in `<internal:gem_prelude>'
D:/opt/fluent/lib/ruby/3.2.0/win32/registry.rb:910:in `encode': U+767E to ASCII-8BIT in conversion from UTF-16LE to UTF-8 to ASCII-8BIT (Encoding::UndefinedConversionError)
        from D:/opt/fluent/lib/ruby/3.2.0/win32/registry.rb:910:in `export_string'
        from D:/opt/fluent/lib/ruby/3.2.0/win32/registry.rb:611:in `each_key'
        from D:/opt/fluent/lib/ruby/site_ruby/3.2.0/ruby_installer/runtime/msys2_installation.rb:71:in `block (2 levels) in iterate_msys_paths'
        from D:/opt/fluent/lib/ruby/3.2.0/win32/registry.rb:435:in `open'
        from D:/opt/fluent/lib/ruby/3.2.0/win32/registry.rb:542:in `open'
        from D:/opt/fluent/lib/ruby/site_ruby/3.2.0/ruby_installer/runtime/msys2_installation.rb:70:in `block in iterate_msys_paths'
        from D:/opt/fluent/lib/ruby/site_ruby/3.2.0/ruby_installer/runtime/msys2_installation.rb:68:in `each'
        from D:/opt/fluent/lib/ruby/site_ruby/3.2.0/ruby_installer/runtime/msys2_installation.rb:68:in `iterate_msys_paths'
        from D:/opt/fluent/lib/ruby/site_ruby/3.2.0/ruby_installer/runtime/msys2_installation.rb:102:in `msys_path'
        from D:/opt/fluent/lib/ruby/site_ruby/3.2.0/ruby_installer/runtime/msys2_installation.rb:115:in `mingw_bin_path'
        from D:/opt/fluent/lib/ruby/site_ruby/3.2.0/ruby_installer/runtime/msys2_installation.rb:125:in `enable_dll_search_paths'
        from D:/opt/fluent/lib/ruby/site_ruby/3.2.0/ruby_installer/runtime/singleton.rb:27:in `enable_dll_search_paths'
        from D:/opt/fluent/lib/ruby/3.2.0/rubygems/defaults/operating_system.rb:24:in `<top (required)>'
        from D:/opt/fluent/lib/ruby/3.2.0/rubygems.rb:1332:in `require'
        from D:/opt/fluent/lib/ruby/3.2.0/rubygems.rb:1332:in `<top (required)>'
        from <internal:gem_prelude>:2:in `require'
        from <internal:gem_prelude>:2:in `<internal:gem_prelude>'
2024-02-28 14:24:25 +0800 [error]: Worker 0 exited unexpectedly with status 1
D:/opt/fluent/lib/ruby/3.2.0/rubygems/specification.rb:10:in `require_relative': Interrupt
        from D:/opt/fluent/lib/ruby/3.2.0/rubygems/specification.rb:10:in `<top (required)>'
        from D:/opt/fluent/lib/ruby/3.2.0/rubygems.rb:1325:in `require_relative'
        from D:/opt/fluent/lib/ruby/3.2.0/rubygems.rb:1325:in `<top (required)>'
        from <internal:gem_prelude>:2:in `require'
        from <internal:gem_prelude>:2:in `<internal:gem_prelude>'
```

**Comment by ashie** [comment]
It's known issue.
Please see https://github.com/fluent/fluent-package-builder/issues/616#issuecomment-1940324078 for the work around.
