### ISSUE TITLE
Out_file short flush interval with timekey 1h in buffer

### ISSUE THREAD

**Issue by hoooli** [fluent/fluentd#4423]
### Describe the bug

I'm trying to eliminate the forest plugin that I used before for dynamically generating paths for file output. I need to have files in the format app.2024020813-0.log, where '0' represents the worker_id. 

Because of the 1h timekey in my conf the flush interval is ignored - it takes really long time to flush the buffer to the logfile. How can I change the setting to flush every 3s (I want to see actual logs) and have the file in format "app.%Y%m%d%H-#{worker_id}.log"? I tried time_slice_format and time_format, but the output file format needs the timekey (without timekey the dateformat has incorrect hours - it looks like 2024020800-0 even at 11am). Is there any workaround?

Thank you

### To Reproduce

Just use timekey 1h with flush interval - the flush interval is ignored

### Expected behavior

correct format of file and flush interval together

### Your Environment

```markdown
- Fluentd version: 1.16.3-2.0
```

### Your Configuration

```apache
<match **> #tag cluster.namespace.app
   @type file
   @id "save-#{worker_id}"
   path "fluentd/log/${path_cluster}/${path_namespace}/${path_app}/${path_app}.*-#{worker_id}.log"
   append true
   <buffer path_cluster,path_namespace,path_app,time>
      @type file
      timekey 1h
      flush_mode interval
      flush_interval 3s
      flush_at_shutdown true
   </buffer>
      <format>
       @type single_value
       message_key log
      </format>
  </match>
```

### Your Error Log

```shell
no errors
```

**Comment by daipom** [comment]
@hoooli

> Just use timekey 1h with flush interval - the flush interval is ignored

I can't reproduce it.
If you use both `timekey` and `flush_interval` at the same time, both should be in effect.
You can confirm it with the following sample config.

```xml
<source>
  @type sample
  tag test
</source>

<match test>
  @type file
  path "/test/fluentd/output/result/app.*-#{worker_id}"
  append true
  <buffer time>
    @type file
    timekey 1h
    flush_mode interval
    flush_interval 3s
  </buffer>
</match>
```

So, your `out_file` setting seems to be correct.
It can be caused by other factors.

Please use this `sample` source and check if it is really the issue of your `out_file` setting.

```xml
<source>
  @type sample
  tag test
</source>
```

**Comment by hoooli** [comment]
@daipom 
Thank you for your response. I've tested using the source dummy, and it seems that messages appear in stdout immediately, but they show up in the file later. I have set the flush_interval to 3s - the modification time of the output file is updated after 3s, but the actual message in the file appears after more than 6-10 seconds, sometimes even later.

On another VM, I don't encounter this issue, so it may not be a configuration problem. Do you have any suggestions on which direction to investigate? The machine doesn't have a high load, which is why this surprises me.

**Comment by daipom** [comment]
> the modification time of the output file is updated after 3s, but the actual message in the file appears after more than 6-10 seconds, sometimes even later.

> On another VM, I don't encounter this issue, so it may not be a configuration problem. 

I think so too.
It could be an environmental issue, such as slow disk processing.

> Do you have any suggestions on which direction to investigate? 

Sorry, I don't know much about it. :cry:
