### ISSUE TITLE
Fluentd logs

### ISSUE THREAD

**Issue by govindagopi** [fluent/fluentd#4442]
### Is your feature request related to a problem? Please describe.

i applied the filter condition in fluentd config yaml file in order to filter the particular field to be removed "data.involvedObject.labels.app" while fluentd logs are pushing to kibana. But the filter condition doesn't filtering it out.

```xml
<filter kubernetes.var.log.containers.events>
@type parser

@type json
json_parser json

replace_invalid_sequence true
emit_invalid_record_to_error false
key_name log
inject_key_prefix data.
@type record_tranformer
remove_keys $.data.involvedObject.labels.app, data.involvedObject.labels.app
reserve_data true
```

### Describe the solution you'd like

i applied the filter condition in fluentd config yaml file in order to filter the particular field to be removed "data.involvedObject.labels.app" while fluentd logs are pushing to kibana. But the filter condition doesn't filtering it out.

```xml
<filter kubernetes.var.log.containers.events>
@type parser

@type json
json_parser json

replace_invalid_sequence true
emit_invalid_record_to_error false
key_name log
inject_key_prefix data.
@type record_tranformer
remove_keys $.data.involvedObject.labels.app, data.involvedObject.labels.app
reserve_data true
```

### Describe alternatives you've considered

NA

**Comment by daipom** [comment]
> ## Describe the solution you'd like
> i applied the filter condition in fluentd config yaml file in order to filter the particular field to be removed "data.involvedObject.labels.app" while fluentd logs are pushing to kibana. But the filter condition doesn't filtering it out.

We should discuss this problem in #4441 because this is not about the `the solution`.
