### ISSUE TITLE
Change default out_forward heartbeat type to TCP

### ISSUE THREAD

**Issue by repeatedly** [fluent/fluentd#450]
`in_forward` / `out_forward` now use UDP for heartbeat type by default.
It means the user needs to open UDP port by default on related servers.
For reducing this extra cost, changing default heartbeat type to TCP is better.

Pros:

- Easy setup

Cons:

- Increase traffic

Maybe, increasing traffic is no problem on almost users.
Default configuration should be easy so TCP is better.
If you are on high-traffic environment, you can use 'heartbeat_type udp' to reduce traffic.

**Comment by aki017** [comment]
+1
