### ISSUE TITLE
LTS poliocy needs overlap to allow organizations fallback in case of problems

### ISSUE THREAD

**Issue by douglasawh** [fluent/fluentd#4739]
### Is your feature request related to a problem? Please describe.

The LTS policy here does not seem appropriate: https://www.fluentd.org/blog/fluent-package-scheduled-lifecycle

At best, a month is not a long time, but there is not a lot of guidance about what "March" means. The way it reads, 5.x is getting dropped when 6.0 comes out. If someone has a problem upgrading, are they still going to get help with 5.x? Sounds like no.

### Describe the solution you'd like

There should be some overlap in the LTS offerings. Organizations often do upgrades quarterly, so maybe 3 or 4 months?

### Describe alternatives you've considered

The alternative is really going to be the matter of time of the overlap.

**Comment by daipom** [comment]
@douglasawh 
> The LTS policy here does not seem appropriate: https://www.fluentd.org/blog/fluent-package-scheduled-lifecycle

Sorry, the information in this article is outdated. We will fix it later.

For the latest release schedule, please check this announcement.

* https://www.fluentd.org/blog/fluent-package-v6-scheduled-lifecycle

We will support fluent-package v5 LTS and Fluentd v1.16.x until Dec 2025.
fluent-package v6 LTS will be released on Aug 2025.
So, there is an overlap time of 4 months!

**Comment by kenhys** [comment]
It will be fixed by  https://github.com/fluent/fluentd-website/pull/341
