### ISSUE TITLE
Incompatibility issue of v1-config because of multilined array/hash format

### ISSUE THREAD

**Issue by sonots** [fluent/fluentd#493]
In v1-config, we support multilined parameters for JSON array or hash format like:

```
param_array [
  "a",
  "b"
]
param_hash {
  "a":"a",
  "b":"b"
}
```

which is implemented at https://github.com/fluent/fluentd/blob/b20602b84e3eabc6cf97597bf2fff1916ec9df0a/lib/fluent/config/literal_parser.rb#L56-L59. 

Yes, this is useful, but the new syntax makes plugins listed followings be broken (I looked all plugins at http://www.fluentd.org/plugins) because they use their own syntax starting by `{` or `[` chars. 

* https://github.com/ephemeralsnow/fluent-plugin-eval-filter
* https://github.com/y-ken/fluent-plugin-geoip
* https://github.com/fukuiretu/fluent-plugin-json-nest2flat
* https://github.com/haracane/fluent-plugin-pgdist
* https://github.com/tomity/fluent-plugin-map (Added)

**Comment by Seraf** [comment]
Hello,

Sorry to re-open this issue, but I don't know if it's only related to geoip plugin, or if there is a fix somewhere ?

Anyway, I'm still having an issue with it : https://github.com/y-ken/fluent-plugin-geoip/issues/16#issuecomment-103177819

I tried to put {...} but it fails to parse the json, and quoting or trying to escape doesn't work too.
I'm using td-agent 2.2.0.

Thanks

**Comment by repeatedly** [comment]
I commented on geoip issue and this case is your configuration uses wrong quote for json string.
