### ISSUE TITLE
support the compressing stream in forward and secure forward

### ISSUE THREAD

**Issue by haroboro** [fluent/fluentd#504]
It's to save the bandwidth across the data centers, also accelerate the transfer speed and save the time.

**Comment by repeatedly** [comment]
We will consider supporting compression in v0.14's new APIs: https://github.com/fluent/fluentd/issues/309#issuecomment-83390980

**Comment by cswilliams** [comment]
+1, this would be a great feature to help reduce our bandwidth charges on AWS

**Comment by deitch** [comment]
Yes, I was just looking for this. You would need to support it in `out_forward` as well, so the receiver can decompress it.

I have a use case where the compressed logs are ~10% of the uncompressed logs. For LAN, that doesn't matter, but for shipping inter-DC or to the cloud, that is a huge deal.

+1

**Comment by repeatedly** [comment]
@deitch Do you use Gzip or Snappy like compression?

**Comment by deitch** [comment]
Don't actually care. We have gotten similar results with gzip and plain zip. But as long as in_forward / in_secure_forward and out_forward both support it, I can put a fluentd on each host to collect and forward, and have another cluster of them in the cloud, and everyone is happy.

**Comment by tsailiming** [comment]
+1

**Comment by repeatedly** [comment]
Does someone try this patch?

https://github.com/fluent/fluentd/pull/637

**Comment by Manikantan22** [comment]
I am looking for a option to compress a message during out_forward. Could someone help me?

**Comment by tagomoris** [comment]
refer #1179
