### ISSUE TITLE
Allow non-string values for record_transformer

### ISSUE THREAD

**Issue by kiyoto** [fluent/fluentd#521]
[This StackOverflow question](http://stackoverflow.com/questions/27523945/modify-fluentd-json-output) + the new support for array/hash data types led me to believe it's a good idea to support non-string values for record_transformer.

Currently, the value is always serialized. So, if your config looks like

```aconf
<source>
  @type dummy
  dummy {"remote":"hogehoge","city":"tokyo"}
  tag test
</source>

<filter test.**>
  @type record_transformer
  <record>
    geoip {"remote":"${remote}","city":"${city}"}
  </record>
  remove_keys remote,city
</filter>

<match test.**>
  type stdout
</match>
```

The output looks like

```shell
2014-12-18 01:15:06 +0000 test: {"geoip":"{\"remote\":\"hogehoge\",\"city\":\"tokyo\"}"}
```

We can support more use cases if it returned the following:

```
2014-12-18 01:15:06 +0000 test: {"geoip":"{"remote":"hogehoge","city":"tokyo"}}
```

(@sonots, I believe the predecessor, record_reformer, was designed when we lacked JSON array/hash support in Fluentd's config)

I am more than happy to provide the code.

**Comment by ezra-at-lumedic** [comment]
This doesn't appear to be working
