### ISSUE TITLE
Improve identification of output plugins with the same type in monitor agent output

### ISSUE THREAD

**Issue by banderas07** [fluent/fluentd#534]
If having two output plugins with the same type, in the monitoring agent output you can differentiate between them by "plugin_id". But "plugin_id" changes after restart and is not very user friendly either.
Possible solutions for better distinguishing between plugins with the same type:
- add "match" pattern as a new field in monitoring_agent output for each output plugin
- make the "plugin_id" user configurable and persistent across restarts

**Comment by sonots** [comment]
plugin_id is configurable like

```
<match **>
  @type forward
  @id forward1
</source>
```

**Comment by banderas07** [comment]
Yes, you're right, since v0.12, I was using v0.10.58. Then I guess you can delete this issue. Thank you! :)

**Comment by repeatedly** [comment]
`id` is available since v0.10.33.
Adding `@` prefix is since v0.12.0.

**Comment by banderas07** [comment]
:) And it works ! Sorry for the issue but I couldn't find the 'id' parameter in documentation.

**Comment by repeatedly** [comment]
No problem. It's our fault.
I just added common parameter section to config article.

http://docs.fluentd.org/articles/config-file#common-plugin-parameter
