### ISSUE TITLE
in_tail and regex format

### ISSUE THREAD

**Issue by florentvaldelievre** [fluent/fluentd#546]
Hello,

My regex is not being recognized by fluentd 
td-agent 0.10.58
ruby 2.1.5p273 (2014-11-13) [x86_64-linux-gnu]

It works well with fluentular tool: <a href="http://fluentular.herokuapp.com/parse?regexp=%28%3F%3Ctime%3E%5B%5E+%5D*+%5B%5E+%5D*+%29+%28%3F%3Cclass%3E%5B%5E+%5D%2B%29+*%28%3F%3Clevel%3E%5B%5E+%5D%2B%29.*-+%28%3F%3Cmessage%3E%28%3F%3A%28%3F%21%5Cn%5Cd%7B4%7D%28%3F%3A-%5Cd%7B2%7D%29%7B2%7D%29%5B%5Cs%5CS%5D%29*%29&input=2015-01-28+18%3A48%3A37%2C809++proxy.pojo.javassist.JavassistLazyInitializer+++++++ERROR++-+HHH000142%3A+Javassist+Enhancement+failed%3A+hibe.core.communication.feed.Post%0D%0Ajava.lang.RuntimeException%3A+duplicate+method%3A+attach+in+hibe.core.communication.feed.Post_%24%24_javassist_64%0D%0A++++++++at+javassist.util.proxy.ProxyFactory.createClass3%28ProxyFactory.java%3A509%29%0D%0A++++++++at+javassist.util.proxy.ProxyFactory.createClass2%28ProxyFactory.java%3A486%29%0D%0A++++at+java.util.concurrent.ThreadPoolExecutor.runWorker%28ThreadPoolExecutor.java%3A1142%29%0D%0A++++++++at+java.util.concurrent.ThreadPoolExecutor%24Worker.run%28ThreadPoolExecutor.java%3A617%29%0D%0A++++++++at+java.lang.Thread.run%28Thread.java%3A745%29%0D%0ACaused+by%3A+javassist.bytecode.DuplicateMemberException%3A+duplicate+method%3A+attach+in+hibe.core.communication.feed.Post_%24%24_javassist_64%0D%0A++++++++at+javassist.bytecode.ClassFile.testExistingMethod%28ClassFile.java%3A637%29%0D%0A++++++++at+javassist.util.proxy.ProxyFactory.createClass3%28ProxyFactory.java%3A497%29%0D%0A++++++++...+80+more%0D%0A2015-01-28+18%3A48%3A37%2C823++hibernate.proxy.pojo.BasicLazyInitializer+++++++++++ERROR++-+Javassist+Enhancement+failed%3A+hibe.core.communication.feed.Post%0D%0Ajava.lang.RuntimeException%3A+duplicate+method%3A+attach+in+hibe.core.communication.feed.Post_%24%24_javassist_65%0D%0A++++++++at+javassist.util.proxy.ProxyFactory.createClass3%28ProxyFactory.java%3A509%29%0D%0A++++++++at+javassist.util.proxy.ProxyFactory.createClass2%28ProxyFactory.java%3A486%29%0D%0A++++++++at+java.util.concurrent.ThreadPoolExecutor%24Worker.run%28ThreadPoolExecutor.java%3A617%29&time_format=%25Y-%25m-%25d+%25H%3A%25M%3A%25S%2C%25L">fluentular demo link</a>
It also works well with Rubular: <a href="http://www.rubular.com/r/GrL3XQSg8o">rubular demo link</a>

td-agent.log returns:
````
2015-01-30 09:46:00 +0000 fluent.warn: {"message":"pattern not match: \"java.lang.RuntimeException: duplicate method: attach in hibe.core.communication.feed.Post_$$_javassist_64\""}
2015-01-30 09:46:00 +0000 fluent.warn: {"message":"pattern not match: \"        at javassist.util.proxy.ProxyFactory.createClass3(ProxyFactory.java:509)\""}
2015-01-30 09:46:00 +0000 fluent.warn: {"message":"pattern not match: \"        at javassist.util.proxy.ProxyFactory.createClass2(ProxyFactory.java:486)\""}
...
````

My setup is the following:

````
<source>
 type tail
 path  /var/log/tomcat7/hibe-webapp.log
 pos_file /tmp/tomcat.pos
 tag tomcat.catalina.log
 refresh_interval 5
 format /(?<time>[^ ]* [^ ]* ) (?<class>[^ ]+) *(?<level>[^ ]+).*- (?<message>(?:(?!\n\d{4}(?:-\d{2}){2})[\s\S])*)/
 time_format %Y-%m-%d %H:%M:%S,%L
</source>

<match **>
type stdout
</match>
````

Do you have a clue ?

Many thanks

**Comment by repeatedly** [comment]
Your logs have multiline stacktrace but your configuration is only for single line.
in_tail tries to match regex at each line unlike fluentular / rubular.
So you should multiline mode instead. See multiline section: http://docs.fluentd.org/articles/in_tail

Lastly, if you have a question, please use ML first :) https://groups.google.com/d/forum/fluentd
