### ISSUE TITLE
Documentation error in in_tail

### ISSUE THREAD

**Issue by dsociative** [fluent/fluentd#557]
```
If you use tsv or csv format, please also specify the keys parameter.

format tsv
keys key1, key2, key3
time_key key2
```

In this case, we get something like this **{"key1": null, " key2": null, " key3": null}**
But if we define keys with no spaces after comma will get the correct keys.

[link to documentation](http://docs.fluentd.org/articles/in_tail)

**Comment by repeatedly** [comment]
Thanks for pointing this out! Just updated.

BTW, if you found the documentation error, please file a bug in fluentd-docs repository.
https://github.com/fluent/fluentd-docs
