### ISSUE TITLE
[PROPOSAL] Supported Ruby versions: 2.1 or later

### ISSUE THREAD

**Issue by tagomoris** [fluent/fluentd#563]
I propose that we should be going to define **Supported Ruby Versions** explicitly, and to decide it for v0.14 as **Ruby 2.1 or later**.

Pros:
* Ruby 2.0 requires default value for method keyword arguments
  * This specification requires programmers to check method values are specified or not in all methods
  * This requirements brings many terrible code and bugs
  * Ruby 2.1 allows to use keyword arguments without default values (and raises ArgumentError if not specified)
* At Ruby 2.1, `def` returns symbol
  * This allows to write `private def private_method_name()`, and this method signature makes code clear
* Ruby 2.1 `String` has `#scrub`
  * Invalid bytes of UTF-8 brings tons of clashes
* Ruby 2.1 `Socket#getifaddrs`
  * Networking is very important for fluentd, and this method make it better

Cons:
* Supported versions of ruby is Ruby2.0 in both of RHEL/CentOS7 and Ubuntu LTS
  * But these ruby packages has dead-lock bug of `require`
  * Many fluentd users don't use system ruby for fluentd now

Today (March 2015), Ruby 1.9.x is not maintained. So we don't support Fluentd on ruby 1.9.x even in Fluentd v0.12.

**Comment by sorah** [comment]
+1

**Comment by repeatedly** [comment]
From td-agent view, td-agent 2 already uses Ruby 2.1.
Older td-agent 1 uses Ruby 1.9 and td-agent 1 never update Ruby and Fluentd major versions.
So dropping Ruby 2.0 is no impact in td-agent world.

**Comment by sonots** [comment]
:+1:

**Comment by tagomoris** [comment]
I found one more reason:
Ruby 2.1 or later have `OpenSSL::SSL::SSLErrorWaitReadable` and others.
This means that errors on non-blocking I/O for SSLSocket are different on ruby 2.1 from 2.0.

**Comment by repeatedly** [comment]
Close this issue.
Let's go with Ruby 2.1!

**Comment by tagomoris** [comment]
:+1:
