### ISSUE TITLE
[PROPOSAL] Support delimiter in plugin in_tail

### ISSUE THREAD

**Issue by nevill** [fluent/fluentd#565]
I've noticed PR #489 has a support on customized delimiter, why we don't support it in `in_tail`.

I propose to have config like
```
<source>
  @type tail
  format csv
  delimiter |   # <------ the key part
  keys id,ip
  path /var/log/fluentd/sample.log
  pos_file /var/log/fluentd/sample.log.pos
  tag sample
</source>
<match **>
  type stdout
</match>
```
Suppose we have one line in sample.log
```
2|192.168.1.10
```
Expected output will be
```
2015-03-25 12:14:45 +0800 sample: {"id":"2","ip":"192.168.1.10"}
```

**Comment by repeatedly** [comment]
It seems reasonable.
Currently, `tsv` parser has `delimiter` option.
If you need the delimiter option ASAP, please consider tsv format instead.

**Comment by nevill** [comment]
@repeatedly Thank you, it works.
Then, why we have both `tsv` and `csv`, seems they can be combined.

**Comment by repeatedly** [comment]
@nevill I agree.
It is historical reason. I think TSV should use CSV parser and `format tsv` should become an alias of CSV parser with `\t` configuration.

**Comment by repeatedly** [comment]
Close this issue.
Issue of merging TSV and CSV should be separated.
