### ISSUE TITLE
Passing labels over forward protocol

### ISSUE THREAD

**Issue by tagomoris** [fluent/fluentd#566]
Using opts (possibly v0.12)

**Comment by sonots** [comment]
In my understating, `label` was for internal routing as its design concept. If it can be passed over forward protocol, it will become external routing like `tag`. The difference between `tag` and `label` will be ambiguous. What are you aiming with this enhancement?

**Comment by sonots** [comment]
Just guess. Are you aiming, `label` to be **routing** and `tag` to be **data source**, rather than internal routing and external routing?

**Comment by tagomoris** [comment]
I think that forwarding messages is a kind of routing. These 2 cases below has no difference except for data source and final output are in different processes.
```
1) events -> (any inputs) -> [process A] -> (any outputs) -> data
2) events -> (any inputs) -> [process A] -> (out_forward) ------> (in_forward) -> [process B] -> (any outputs) -> data
```

Passing labels over forward protocol makes us to be able to extend fluentd message passing from a process to fluentd network/cluster without any tag modifications.

Pros:
* Users can create fluentd network w/o tag modification if event stream become bigger than one fluentd process can handle

Cons:
* Users cannot determine statically how a `<source>` tag labels on its events from configuration file

**Comment by tagomoris** [comment]
Now, I'm thinking that labels should be determined by configuration file, not data themselves.
