### ISSUE TITLE
RPC for instance management

### ISSUE THREAD

**Issue by repeatedly** [fluent/fluentd#575]
We have a plan to add RPC feature to v0.14 but this is an independent from v0.14 features so it can be implemented at v0.12.
The merit is using RPC is better than signal on several environment, e.g. JRuby and Windows.

## Features

JSON + HTTP API is better because user can call APIs via command line tools like curl.

- Change fluentd state at runtime like `--without-source`
  - `POST /plugins/stop_sources`
- Send actions instead of singal. This is needed for JRuby / Windows support
  - `POST /buffers/flush` or `/signal/hup`? Former is readable.
- Integrate monitor_agent (needed?)
- misc

## Configuration

If set `rpc_port` in `<system>`, fluentd launches RPC server.

What do you think?

**Comment by tagomoris** [comment]
All switches should be toggled, like below:
* `POST /plugins/sources/on` & `POST /plugins/sources/off` or so

Readable path is better, but path consistency is also important: `POST /plugins/buffers/flush`

**Comment by sonots** [comment]
Just an idea, but what about to provide API interfaces for plugins liks

    POST /plugins/out_grep/:plugin_id
    {
       "tag":"foo"
    }

which enables post any json to plugin instance.

This would call new plugin API like

    def rpc(params)
    end

so that plugin authors freely define its behaviors.

**Comment by repeatedly** [comment]
Implemented
