### ISSUE TITLE
Erro install plugin with td-agent-gem

### ISSUE THREAD

**Issue by chipx** [fluent/fluentd#581]
I\`m install the plugin ``td-agent-gem install fluent-plugin-hipchat`` and get:

    WARN: Unresolved specs during Gem::Specification.reset:
       json (>= 1.4.3)
    WARN: Clearing out unresolved specs.
    Please report a bug if this causes problems.
    ERROR:  While executing gem ... (Gem::CommandLineError)
      Please specify at least one gem name (e.g. gem build GEMNAME)
Fluentd installed from the deb package, downloaded from the official site.

Environment

    Ubuntu 14.10
    td-agent 0.12.7
    ruby 2.1.2p95 (2014-05-08) [x86_64-linux-gnu]
    gem 2.2.2

**Comment by repeatedly** [comment]
I can install hipchat plugin without errors.

```
$ sudo /usr/sbin/td-agent-gem install fluent-plugin-hipchat --no-document
WARN: Unresolved specs during Gem::Specification.reset:
      json (>= 1.4.3)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
Fetching: multi_xml-0.5.5.gem (100%)
Successfully installed multi_xml-0.5.5
Fetching: httparty-0.13.3.gem (100%)
When you HTTParty, you must party hard!
Successfully installed httparty-0.13.3
Fetching: hipchat-api-1.0.6.gem (100%)
Successfully installed hipchat-api-1.0.6
Fetching: fluent-plugin-hipchat-0.1.6.gem (100%)
Successfully installed fluent-plugin-hipchat-0.1.6
4 gems installed
```

Could you show me your entire command?

**Comment by chipx** [comment]
Now establish normal. Sorry to trouble you.
