### ISSUE TITLE
Preceeding space gets added to key

### ISSUE THREAD

**Issue by dmfenton** [fluent/fluentd#590]
This bug was messing me up with trying to index some CSVs into Elasticsearch. Every time I would start indexing, what looked like duplicate mappings were being created.

The reason was that a set of keys like: "key1, key2, key3" was turned into "key1", " key2", " key3". This was really hard to ferret out. At a minimum there should be docs about this in big bold letters, or better yet, detect and ignore the spaces between keys.

Here's a GIST that shows the consequences of this bug:
https://gist.github.com/dmfenton/23197b0729b6735f47ab

**Comment by repeatedly** [comment]
I heard this before but we keep this behaviour because few users go with this behaviour.
Yeah, this is error prone...

`,` separated approach is the legacy of old configuration format.
We have a plan to support array based parameter, `keys ["key1", "key2"]`.

**Comment by dmfenton** [comment]
So maybe some big red letters in your documentation would be useful until there is a new configuration format available?

**Comment by repeatedly** [comment]
I just added NOTE message to csv / tsv section.

http://docs.fluentd.org/articles/in_tail

I will add json array support later.

**Comment by repeatedly** [comment]
PR are merged. v0.12.9 ship with json array parameter.
