### ISSUE TITLE
out_file no longer creates directories

### ISSUE THREAD

**Issue by hfwang** [fluent/fluentd#594]
After fd1b901cdc01e411c090e145591ed990b4532925 the `out_file` plugin no longer creates directories due to the call to `::Fluent::FileUtil.writable?`

(There is still a call to `mkdir_p` in https://github.com/fluent/fluentd/blob/1bd35e8a0f7d072bb7d88c8333773cfcea81ce36/lib/fluent/plugin/out_file.rb#L82 so, I'm not sure what the intended behavior for out_file was... for example if you want to say bucket files into date subdirectories)

We use the forest plugin and this change means we need to create a new directory before emitting events for a new tag.

**Comment by repeatedly** [comment]
@sonots Could you handle this?

**Comment by cswilliams** [comment]
I also just ran into this problem.  I believe the issue is due to this change:
https://github.com/fluent/fluentd/pull/401

I commented out the :Fluent::FileUtil.writable?(test_path) check in plugin/out_file.rb and now it creates directories again.

**Comment by sonots** [comment]
I will fix to recursively follow File.dirname until dir exists and, then check its permission.

**Comment by cswilliams** [comment]
that sounds like a good fix. Many thanks!

**Comment by repeatedly** [comment]
After fixed this issue, I will release new v0.12.

**Comment by repeatedly** [comment]
@hfwang @cswilliams Could you check https://github.com/fluent/fluentd/pull/595 patch on your environment?

**Comment by cswilliams** [comment]
I tested it.  Everything works and it creates new directories now without any errors.

**Comment by repeatedly** [comment]
@cswilliams Thanks!

@hfwang Is above patch working? If you okay, I will merge it and release new version.

**Comment by hfwang** [comment]
Just tested it as well, looks good to me! :+1:
