### ISSUE TITLE
Fluentd Elasticsearch output stops sending data

### ISSUE THREAD

**Issue by yusufcan141** [fluent/fluentd#596]
I'm using elasticsearch output. Every morning at 6.30, all machines stop sending data to elasticsearch and S3. I'm using fluent-plugin-forest also. Here is the error:

2015-05-14 20:05:14 +0300 [error]: Cannot output messages with tag 'elasticsearch.esData.events_2015_05_01.file.log'
2015-05-14 20:05:14 +0300 [error]: failed to configure/start sub output elasticsearch: can't create Thread: Resource temporarily unavailable
2015-05-14 20:05:14 +0300 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/output.rb:110:in `initialize'
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/output.rb:110:in `new'
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/output.rb:110:in `start'
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/output.rb:237:in `block in start'
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/output.rb:237:in `each'
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/output.rb:237:in `start'
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-elasticsearch-0.8.0/lib/fluent/plugin/out_elasticsearch.rb:44:in `start'
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-forest-0.3.0/lib/fluent/plugin/out_forest.rb:133:in `block in plant'
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-forest-0.3.0/lib/fluent/plugin/out_forest.rb:128:in `synchronize'
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-forest-0.3.0/lib/fluent/plugin/out_forest.rb:128:in `plant'
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-forest-0.3.0/lib/fluent/plugin/out_forest.rb:168:in `emit'
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/output.rb:32:in `next'
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/buffer.rb:184:in `block in emit'
/opt/td-agent/embedded/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'

**Comment by repeatedly** [comment]
>  can't create Thread: Resource temporarily unavailable

From this message, your machine seems to lack resources.
How many tags do you have?

**Comment by yusufcan141** [comment]
I have almost 500 tags. But the strange thing is: i'm running fluentd on 3 machines and all of them stops near at 6.30 every day and when i restart td-agent, it continues to send data.

**Comment by repeatedly** [comment]
Hm. What the thread limit on your environment?
`cat /proc/sys/kernel/threads-max` command gets its value.

**Comment by yusufcan141** [comment]
It's 239426

**Comment by yusufcan141** [comment]
ruby -e 'loop { Thread.new { sleep } rescue puts "Error at count
> #{Thread.list.size} : #{$!} // RUBY-#{RUBY_VERSION}" }'
Error at count
3968 : can't create Thread (11) // RUBY-1.9.3

Ruby can create 3968 thread max on my machine but is it not enough?

**Comment by yusufcan141** [comment]
@repeatedly Do you have any idea?

**Comment by repeatedly** [comment]
Could you also check `ulimit -u`?
If it is larger than 1024, the problem may be lack of machine resources.

**Comment by yusufcan141** [comment]
Yes, ulimit -u gives 119713. What should i do? Many nginx processes also work on these machines and they write data to many files at the same time when fluentd reads them.

**Comment by repeatedly** [comment]
Hm... I'm not sure why the number of tags are 500. If you tail only the log of nginx processes, the number of tags seems to be small.

**Comment by yusufcan141** [comment]
No, sorry i could not tell it clear. We send user events data to elasticsearch, that's why we keep 300-500 tags. But also on the machines where fluentd works, there is nginx and php5 which writes these log files. So, we dont tail log of nginx processes, we tail user events.

**Comment by yusufcan141** [comment]
I checked it now, i have 250 Tag in total .

**Comment by repeatedly** [comment]
In popular linux distribution, default thread stack size is 4MB or 8MB or 10MB.
If you have 250 tag in total, 2G or 4G or 5GB memory are consumed by forest related threads.

There are several approaches to avoid this.
- setup rich aggregation server
- reduce the number of tags
- remove useless forest configuration. But I'm not sure how to use forest in your configuration...

**Comment by yusufcan141** [comment]
Hi @repeatedly , thanks for your reply. It's very hard for me to reduce number of tags. Here is my configuration, do you have any suggestion?

<source>
  type tail
  path /esData/*/*/%Y-%m-%d-%H.log
  pos_file /mnt/log/td-agent/esData-position.pos
  format json
  tag elasticsearch.*
</source>

<match elasticsearch.**>
  type copy
  <store>
    type s3
    aws_key_id ###
    aws_sec_key ###
    s3_bucket ###
    path ###
    s3_region eu-west-1
    store_as json
    format json
    use_ssl false
    buffer_type file
    buffer_path /var/log/fluent/s3
  </store>
  <store>
    type forest
    subtype elasticsearch
    <template>
      host ###
      port 9200
      index_name ${tag_parts[2]}
      type_name ${tag_parts[3]}
      include_tag_key false
      flush_interval 10s
    </template>
    <case elasticsearch.*.##.**>
      id_key doc_id
    </case>
    <case elasticsearch.*.##.**>
      id_key doc_id
    </case>
    <case elasticsearch.*.*.*##.**>
      id_key doc_id
    </case>
    <case elasticsearch.*.*.*##.**>
      id_key doc_id
    </case>
  </store>
</match>

**Comment by repeatedly** [comment]
Sorry for the delay. https://github.com/uken/fluent-plugin-elasticsearch/pull/116 PR may help this problem.

**Comment by repeatedly** [comment]
fluent-plugin-elasticsearch now has `elasticsearch_dynamic` plugin.
It may resolve this problem.
If you have further problem, please reopen it.
