### ISSUE TITLE
config parameter type `enum`

### ISSUE THREAD

**Issue by tagomoris** [fluent/fluentd#599]
Enum -like configuration parameters are used in many places.
Now many plugin implement it with `config_param` with blocks, but it's troublesome.

This issue propose new `config_param` type `enum` like this:

```ruby
config_param :heartbeat_type, :enum, list: [:tcp, :udp], default: :tcp
```

This is easy to understand for both of developer and users, and reduces number of use of `config_param` with blocks, so it is helpful for #584.

**Comment by repeatedly** [comment]
:+1:
