### ISSUE TITLE
log number of messages dropped when there is a queue limit warning

### ISSUE THREAD

**Issue by LanceNorskog** [fluent/fluentd#601]
Fluentd prints a warning when it drops messages due to a Queue limit overrun, but it does not print the number of messages or number of bytes dropped.

We recently had a chronic overrun problem for a few hours and it would be nice to know how many logs we lost.

Cheers!

**Comment by tagomoris** [comment]
memo: #309

**Comment by tagomoris** [comment]
v0.14 will show the number of records for such case:
https://github.com/fluent/fluentd/blob/master/lib/fluent/plugin/output.rb#L790
