### ISSUE TITLE
Feature request: MessagePackParser

### ISSUE THREAD

**Issue by kawanet** [fluent/fluentd#605]
The option `format` now accepts `msgpack` for output plugins via MessagePackFormatter at #479. In the opposite direction, it doesn't seems that it accepts `msgpack` for most of input plugins. The pair of MessagePackParser and MessagePackFormatter would show a clean symmetry for both input and output plugins. In_forward, in_exec and in_http do implement it, respectively.

The `msgpack` parser allows for users to send a compact log with time and tag claimed by the source. I'd like to send a log via UDP which is simple, in my case. It'd be great when in_udp could accept `msgpack` format as well as in_forward does. On another case, in_tail could import log files dumped by MessagePackFormatter.

I'm not sure that it's possible to implement the MessagePackParser as the current parses might request source as a string but not a binary, however.

**Comment by repeatedly** [comment]
> I'm not sure that it's possible to implement the MessagePackParser as the current parses might request source as a string but not a binary, however.

Yes, this point is difficult problem. Current Parser is used with text based protocol.
For example, in_tail, in_udp and in_tcp assumes incoming events are separated by `\n`.
If we support msgpack format, we should change input plugins to support binary protocol before.

**Comment by kawanet** [comment]
Thank you for your reply.

I'm closing this request as I misunderstood about MessagePackFormatter. It dumps only `record` but not the trio of `[tag, time, record]`. It could not dump (or journal) the whole stream  of events, then.

I found a simple workaround to import a log file dumped by MessagePackFormatter, anyway. The fluent-cat looks to accept the same format of series of multiple records. 

```sh
fluent-cat tag --msgpack < dump.log
```

I guess fluent-cat above is enough in most cases to import a dumped log. The original tag and time of events should be included within the records before dumped and restored after imported.

> I'd like to send a log via UDP which is simple, in my case.

I'll use JSON on UDP, then. A UDP packet still has a limit for size of its payload. It does not work with a long event stream dumped. JSON on UDP could be enough for a single event.
