### ISSUE TITLE
Nginx log format configuration

### ISSUE THREAD

**Issue by reachgopal** [fluent/fluentd#608]
Hello:

I am using default Nginx log format provided as below: (mentioned in fluentd site http://docs.fluentd.org/articles/in_tail). 

```
format /^(?<remote>[^ ]*) (?<host>[^ ]*) (?<user>[^ ]*) \[(?<time>[^\]]*)\] "(?<method>\S+)(?: +(?<path>[^\"]*) +\S*)?" (?<code>[^ ]*) (?<size>[^ ]*)(?: "(?<referer>[^\"]*)" "(?<agent>[^\"]*)")?$/
time_format %d/%b/%Y:%H:%M:%S %z
```

I use standard nginx docker container and try to access the site and found that the format mentioned but it does not cover the gzip ratio as mentioned below.

```
^(?<remote>[^ ]*) (?<host>[^ ]*) (?<user>[^ ]*) \[(?<time>[^\]]*)\] "(?<method>\S+)(?: +(?<path>[^\"]*) +\S*)?" (?<code>[^ ]*) (?<size>[^ ]*)(?: "(?<referer>[^\"]*)" "(?<agent>[^\"]*)" "(?<gzip_ratio>[^\"]*)")?$
```

Is the format not updated in the portal as default format? Please advice.

Thanks.

**Comment by repeatedly** [comment]
Sorry I don't have a log including gzip ratio part.
Could you paste actual log example here?

**Comment by repeatedly** [comment]
ping?

**Comment by repeatedly** [comment]
ping?
We need actual log to check and fix this issue.

**Comment by repeatedly** [comment]
There is no response.
Please reopen it if you have actual logs.
