### ISSUE TITLE
in_exec json streams does not work as expected

### ISSUE THREAD

**Issue by serbaut** [fluent/fluentd#609]
ruby-yajl reads 8k from the input stream before parsing so input is delayed until the buffer is full (which can take forever if no new input is generated).

This can be reproduced with the following config:

    <source>
      type exec
      format tsv
      command while sleep 1; do date; done
      keys tsv_date
      tag all
    </source>

    <source>
      type exec
      format json
      command while sleep 1; do echo '{"json_date": "'$(date)'"}'; done
      tag all
    </source>

    <match all>
      type stdout
    </match>

tsv_date is emitted each time but json_date is not emitted until the buffer is full (~5 minutes in this case).

I have created a workaround https://github.com/serbaut/fluentd/commit/c99bcf47a3695cd39aa211ccb2b0bd8bac5a704c that parses line by line but in the end ruby-yajl has to be fixed so is parses one json document at a time.

**Comment by repeatedly** [comment]
You are right. We wrote this note for out_exec_filter but we forgot to add same note to in_exec.
I will update the article later.

http://docs.fluentd.org/articles/out_exec_filter

**Comment by repeatedly** [comment]
I have already added json note to in_exec article.

**Comment by tagomoris** [comment]
It's documentation issue which is already solved.

**Comment by matt-deboer** [comment]
Could you clarify the resolution for this? I'm still unclear how to resolve this for the streaming json example  in v 0.14.13...
