### ISSUE TITLE
Need a way to disable logging fluent.conf content

### ISSUE THREAD

**Issue by Jackyjjc** [fluent/fluentd#618]
Currently when fluentd starts up, it will print out the content of the config file it use. However, when using the s3 plugin (https://github.com/fluent/fluent-plugin-s3) or the kinesis plugin (https://github.com/awslabs/aws-fluent-plugin-kinesis), it will print out the aws_access_key and the aws_access_secret_key as a result even though i read them from environment variables.

**Comment by repeatedly** [comment]
Please use `--suppress-config-dump` option.

https://github.com/fluent/fluentd/blob/d3ae305b6e7521fafac6ad30c6b0a8763c363b65/lib/fluent/command/fluentd.rb#L106

**Comment by repeatedly** [comment]
In addition, latest fluentd and fluent-plugin-s3 combination doesn't print actual key values > https://github.com/fluent/fluent-plugin-s3/commit/a678d899fab871e97a86e9b621ef2d1a523ef17b

**Comment by Jackyjjc** [comment]
Thank you, I was looking at the documentation and didn't find the option :)

**Comment by Jackyjjc** [comment]
I've created a pull request for the kinesis plugin to do the same thing as your s3 plugin: https://github.com/awslabs/aws-fluent-plugin-kinesis/pull/21

**Comment by repeatedly** [comment]
Oops. I will add command line option article on docs.
And I recommend to use `<system>` in configuration file instead of command line option.

http://docs.fluentd.org/articles/config-file#4-set-system-wide-configuration-the-ldquosystemrdquo-directive
