### ISSUE TITLE
WARN: Unresolved specs during Gem::Specification.reset:

### ISSUE THREAD

**Issue by my-dev** [fluent/fluentd#624]
Hi! fluentd develop members...

In td-agent 0.12.12, I do command for example [ td-agent-gem list ]...

We view below
\------------------------------------------------------------
WARN: Unresolved specs during Gem::Specification.reset:
      json (>= 1.4.3)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.

*** LOCAL GEMS ***
\------------------------------------------------------------

because of this is [ warn ], this is no big problem, i see...
but this message is displayed from [ td-agent 0.12.7 ]...

this issue is different from [ closed issue #581 ], maybe.

If you can do, please support me...
thank you.

**Comment by repeatedly** [comment]
I already mentioned this on release announcement.
This will be resolved in the next release.

https://groups.google.com/d/msg/fluentd/q3eox3pmcVc/gYOiEMHItA8J

And this problem is td-agent, not fluentd. Closed.

**Comment by my-dev** [comment]
Thank you your support.

I understood your advise.
I wait for next td-agent version...

See You
