### ISSUE TITLE
out_forword not support unix domain socket

### ISSUE THREAD

**Issue by pierce300** [fluent/fluentd#627]
HI ALL
    how to out_forward pluginss support unix domain socket

**Comment by repeatedly** [comment]
Maybe, overwriting `connect` and `send_data` methonds is enough.
https://github.com/fluent/fluentd/blob/cbfa7438cd052c54b18b1fc3d0d3c28427b086bb/lib/fluent/plugin/out_forward.rb#L257
https://github.com/fluent/fluentd/blob/cbfa7438cd052c54b18b1fc3d0d3c28427b086bb/lib/fluent/plugin/out_forward.rb#L335

**Comment by pierce300** [comment]
OK Thanks
