### ISSUE TITLE
Dump configuration in memory by signal or rpc

### ISSUE THREAD

**Issue by tagomoris** [fluent/fluentd#633]
Long running fluentd process may have configuration, which is different from configuration file on local filesystem.
Something to dump configuration tree in memory may help to shoot troubles.
* Adding RPC method
* Signal?

**Comment by cosmo0920** [comment]
I try to implement this feature in this branch: https://github.com/fluent/fluentd/compare/master...cosmo0920:implement-dump-in-memory-configure

Questions: 

1. Which signal is suitable for? For now, I used `USR2` signal for this purpose.
2. How do we test? Run fluentd and send signal?

**Comment by cosmo0920** [comment]
I'm not sure about signal related unit test....

**Comment by tagomoris** [comment]
@cosmo0920 

1. IMO, signals are very precious to use, and I'm not sure about this feature is enough important to use one of rest of available signals for fluentd. It seems better to implement only as a RPC handler.
2. RPC handlers are tested in current Fluentd code, right? Signal handlers may not be tested, but there's no problem if we don't use signals.

Adding signal handlers later is not so hard. So I think it's good to add RPC handlers only at first.

**Comment by cosmo0920** [comment]
1. OK, thanks.
2. I see. I'll remove signal handler implementation.

> Adding signal handlers later is not so hard. So I think it's good to add RPC handlers only at first.

I'll send PR which contains only rpc handler ASAP.

**Comment by tagomoris** [comment]
Cool!

**Comment by repeatedly** [comment]
PR is merged
