### ISSUE TITLE
out_stdout is not in json format

### ISSUE THREAD

**Issue by Jackyjjc** [fluent/fluentd#638]
The out_stdout allows 'json' format but its output is not in json format as advertised, it is instead in the format: time tag jsonString

The problem of this is that tools like elasticSearch cannot analyse the logs since it is not in json format

**Comment by sonots** [comment]
The format is kept for old version compatibility. Instead, now we have `filter_stdout` and it supports fully json format with `format` option. It is recommended to use `filter_stdout`.

**Comment by sonots** [comment]
See doc for more details for how to use: http://docs.fluentd.org/articles/filter_stdout

**Comment by repeatedly** [comment]
@sonots is right.
`stdout` output is debug purpose and we now have `stdout` filter.
Please use `stdout` filter instead.

**Comment by Jackyjjc** [comment]
@sonots @repeatedly thank you! :)
