### ISSUE TITLE
Strange "pattern not match" error on fluentd.

### ISSUE THREAD

**Issue by papiveron** [fluent/fluentd#644]
Hi,

Can someone tell if its normal that fluentd raise this error in **td-agent.log** file?

```
2015-07-31 13:15:19 +0000 [warn]: pattern not match: "- - - [31/Jul/2015:13:15:19 +0000] GET http://172.31.108.218/ HTTP/1.1 200 0 \"-\" \"ELB-HealthChecker/1.0\""
```
While this is a well formated apache2 log :
```
- - - [31/Jul/2015:13:15:19 +0000] GET http://172.31.108.218/ HTTP/1.1 200 0 \"-\" \"ELB-HealthChecker/1.0\"
```
And here is the source configuration :

```
<source>
  type tail
  format apache2
  path /var/log/varnish/varnishncsa.log
  pos_file /var/log/td-agent/tmp/access.log.pos
  tag "apache2.varnish-access"
</source>
```
I can't figure out what's wrong there above.

Thanks.

Regards.

**Comment by papiveron** [comment]
The problem is that these **ELB-HealthChecker** line log has an empty referer ip field. And then the log doesn't match apache2 log format for fluentd.

So the way to fix that is to filter logs with **ELB-HealthChecker** user-ageent.

**Comment by repeatedly** [comment]
If you want to handle normal apache and above incomplete mixed logs in in_tail,
consider fluent-plugin-multi-format-parser: https://github.com/repeatedly/fluent-plugin-multi-format-parser

**Comment by repeatedly** [comment]
I'm not sure this format often appears in apache logs.
If so, fluentd's parser should support this.
If it happens in special configuration, I close this issue.

**Comment by repeatedly** [comment]
Can we close this issue?

**Comment by repeatedly** [comment]
There is no response. Close this issue for now.
