### ISSUE TITLE
time_format can't be used

### ISSUE THREAD

**Issue by vmironenko** [fluent/fluentd#651]
Hi,
I'm using td-agent 2.2.1 and I try to use time_format parametr with in_tail plugun and multiline format. But I get message in  td-agent log file:
"2015-08-06 16:37:06 +0600 [warn]: parameter 'time_format' in <source>
  type tail
  format multiline
  format_firstline /^[A-Z][a-z]{2} \d\d, \d\d\d\d .*/
  format1 /^(?<time>[A-Z][a-z]{2} \d\d, \d\d\d\d [^ ]* [^ ]*)[ ]*(?<class>[^ ]*)[ ]+(?<status>[^ ]*)\n(?<level>[^ ]*)[ ]+(?<message>.*)/
  time_format %b %d, %Y %l:%M:%S %p
  path /var/log/jenkins/jenkins.log
  refresh_interval 10s
  tag fluentd.jenkins
  read_from_head true
  pos_file /var/log/td-agent/pos/jenkins.log.pos
</source> is not used."
How can I solve this issue?

**Comment by repeatedly** [comment]
duplicated: https://github.com/fluent/fluentd/issues/646
