### ISSUE TITLE
secret parameter feature breaks formatter test driver?

### ISSUE THREAD

**Issue by cosmo0920** [fluent/fluentd#652]
I found this issue while developing formatter plugin.

In fluentd 0.12.10, formatter plugin's test passed: https://travis-ci.org/cosmo0920/fluent-plugin-formatter_simple_tsv/jobs/74699342

But, when using fluentd 0.12.11 or later (including 0.12.15!), formatter plugin's test fail with `NoMethodError: undefined method 'corresponding_proxies'` error like this:

```
Error: test_format(SimpleTsvFormatterTest): NoMethodError: undefined method `corresponding_proxies' for {"keys"=>"key1,key2"}:Hash
```
Full log is here: https://travis-ci.org/cosmo0920/fluent-plugin-formatter_simple_tsv/jobs/74699868

**Comment by repeatedly** [comment]
Avoiding this issue, there are several approaches.
- Create Config::Element explicitly in plugin test
- Support auto-conversion in plugin configure

I'm not sure which is the better.

**Comment by cosmo0920** [comment]
> * Create Config::Element explicitly in plugin test

It is simpler solution. 
But this solution needs that plugin developers to know how to treat Config in fluentd internal.

**Comment by cosmo0920** [comment]
FormatterTestDriver is merged into master, now.
This issue is solved.
