### ISSUE TITLE
Output apache logs to fluentd-ui console

### ISSUE THREAD

**Issue by sachintaware** [fluent/fluentd#659]
I am refering the following docs to configure apache logs on fluentd.But I want to view the logs on fluentd console(like fluentd logs are displayed under log and error log tab ) and not send them to s3 http://docs.fluentd.org/articles/apache-to-s3.
I added the source block
```
<source>
  type tail
  format apache2
  path /var/log/apache2/access.log
  pos_file /var/log/td-agent/apache2.access_log.pos
  tag s3.apache.access
</source>
```
The docs dont give a description about this line `pos_file /var/log/td-agent/apache2.access_log.pos`.
which i guess is the location where the apache logs are written for fluentd to read and fetch them.

I ran this for test  `sudo ab -n 100 -c 10 http://localhost/`,which logs 
```
127.0.0.1 - - [19/Aug/2015:09:34:31 +0000] "GET / HTTP/1.0" 200 5922 "-" "ApacheBench/2.3"
127.0.0.1 - - [19/Aug/2015:09:34:31 +0000] "GET / HTTP/1.0" 200 5922 "-" "ApacheBench/2.3"
::1 - - [19/Aug/2015:09:34:32 +0000] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.12 (Ubuntu) (internal dummy connection
)"
::1 - - [19/Aug/2015:09:34:33 +0000] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.12 (Ubuntu) (internal dummy connection
)"
::1 - - [19/Aug/2015:09:34:34 +0000] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.12 (Ubuntu) (internal dummy connection
)"
::1 - - [19/Aug/2015:09:34:35 +0000] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.12 (Ubuntu) (internal dummy connection
)"
::1 - - [19/Aug/2015:09:34:36 +0000] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.12 (Ubuntu) (internal dummy connection
)"
::1 - - [19/Aug/2015:09:34:37 +0000] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.12 (Ubuntu) (internal dummy connection
)"
::1 - - [19/Aug/2015:09:34:38 +0000] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.12 (Ubuntu) (internal dummy connection
)"
```
but nothing is logged to `apache2.access_log.pos`.It also did not get created at first so I created it manually.

<b>How can I modify the config file to output logs to the fluentd-ui instead of S3 and reload them after some duration?</b> Is it possible or not in current version?

**Comment by repeatedly** [comment]
> How can I modify the config file to output logs to the fluentd-ui instead of S3 and reload them after some duration? Is it possible or not in current version?

fluentd-ui doesn't have visualization feature for now.
For adhoc-measure, use stdout output and check fluentd/td-agent log viewer.

**Comment by repeatedly** [comment]
Fluentd-ui doesn't have log visualization in the latest release.
If you want such feature in fluentd-ui, please request it on fluentd-ui repository.

In addition, you can use out_stdout plugin instead of s3 plugin to show logs in fluentd logs.

**Comment by sachintaware** [comment]
@repeatedly Thank you for your response,missed the earlier comment,hence did not reply.
Is there any tutorial or project,you can point me to implementing this ? Do the docs have details about this? I will make a feature request as you mentioned
