### ISSUE TITLE
Default pos_file value

### ISSUE THREAD

**Issue by oytuntez** [fluent/fluentd#662]
Hello,

Thanks for the amazing package. We are just starting deploying fluentd on our servers. We are tailing some of our application logs and we received a warning about the pos_file parameter, which we did not set:

```bash
2015-08-23 16:32:38 +0000 [warn]: 'pos_file PATH' parameter is not set to a 'tail' source.
2015-08-23 16:32:38 +0000 [warn]: this parameter is highly recommended to save the position to resume tailing.
```

I think this value could have a default value, which would be adding `.pos` at the end of the original file path. So if I am tailing `/var/log/httpd/access_log`, default value of `pos_file` would `/var/log/httpd/access_log.pos`. I can opt to use this automatically filled value, let's say, by providing `1` as value or `*.pos`, or `%path%.pos`

The documentation also doesn't say anything in case of multiple files on `path` parameter. But reading the code, it appears we only need to enter [1 pos_file even in case of multiple files](https://github.com/fluent/fluentd/blob/1a95bde27cd7bae918ac03f3f45fc6542da8a72c/lib/fluent/plugin/in_tail.rb#L753).

**Comment by repeatedly** [comment]
> I think this value could have a default value, which would be adding .pos at the end of the original file path.

This is good idea but it is hard because file path is generated dynamically in some cases, e.g.  `%Y%m%d` or `*`.

> The documentation also doesn't say anything in case of multiple files on path parameter. But reading the code, it appears we only need to enter 1 pos_file even in case of multiple files.

Exactly. This is needed in the docs? Exsiting users understood this behaviour. If adding it is better for newbies. I will add it.

**Comment by mr-salty** [comment]
Do users generally care what the pos_file is actually named?

Could we allow the user to configure a pos_file_dir and then auto-enable it and generate the name, rather than having to configure it per-source?

**Comment by oytuntez** [comment]
@mr-salty, I definitely don't. I don't want to configure one more thing that I don't really care about. I would prefer it invisible to me.

@repeatedly, yeah, I think we may need to clarify that on the documentation. pos_file is explained like this:

- This position is recorded in the position file specified by the pos_file parameter.
- This parameter is highly recommended. Fluentd will record the position it last read into this file. `pos_file /var/log/td-agent/tmp/access.log.pos`

With these examples, I wanted to know if the position cursor is going to be overwritten when I have multiple files or what is going to happen to it? pos_file is an important parameter and nobody wants to mingle with the cursor of different files just to get a misaligned log flow :)

**Comment by repeatedly** [comment]
I added note to `pos_file` section in in_tail article.

> Could we allow the user to configure a pos_file_dir and then auto-enable it and generate the name, rather than having to configure it per-source?

Automatic generating the name is hard because plugins don't have unique name across restart.
plugins have `id` parameter but it is not forced.
So specifying pos_file in each source is safer.

**Comment by repeatedly** [comment]
I added explanation to fluentd-docs so I close this issue for now.
If someone has a good idea to handle dynamic path configuration with default value, please reopen it.
