### ISSUE TITLE
Allow in_monitor_agent to emit content to output plugin

### ISSUE THREAD

**Issue by mohit-gupta** [fluent/fluentd#667]
This will enable periodically sending monitoring agent messages to monitoring tools like graphite. 

Something like : 

```
<source>
  type monitor_agent
  period 1m
  tag monitor.metrics
</source>

<match monitor.metrics>
  type graphite
  # ...
</match>
```

**Comment by repeatedly** [comment]
Thanks! I will work on it later.

**Comment by repeatedly** [comment]
I wrote a patch. Check https://github.com/fluent/fluentd/pull/670

**Comment by repeatedly** [comment]
@mohit-gupta ping? patch is ok for your case?

**Comment by mohit-gupta** [comment]
hey, I got stuck in a few things, will check and update by this week.

Thanks

On Wed, Sep 9, 2015 at 1:32 PM, Masahiro Nakagawa <notifications@github.com>
wrote:

> @mohit-gupta <https://github.com/mohit-gupta> ping? patch is ok for your
> case?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fluent/fluentd/issues/667#issuecomment-138818085>.
>



-- 
Best Regards,

Mohit Gupta
