### ISSUE TITLE
Periodic flush on in_tail plugin for multiline format

### ISSUE THREAD

**Issue by Jorge-Rodriguez** [fluent/fluentd#668]
When using the in_tail plugin with multiline format and format_firstline the plugin will not generate an event until the next first line is detected (expected behaviour as we can't know that the multiline event has ended until the next first line shows up) however, it is reasonable to expect that a multiline event will happen on a short period of time so the event could be flushed on either a new first line or a configurable timeout, this is useful on files with low activity where the next first line can take a long time to appear.

Feature request:
- Add a parameter to the in_tail plugin to be able to configure the multiline event timeout.

**Comment by sonots** [comment]
Just an idea. How about having something like define_lastline?

For Rails log, it would be like

    define_lastline /Completed/

**Comment by Jorge-Rodriguez** [comment]
@sonots it wouldn't work for events where the last line is undefined,  e.g. stack traces, which happen to be the main reason for this feature request.

Also, if you can define a last line then you can define a multiline format with a regular expression matching the entire multiline event and not define format_firstline, accomplishing the same result.

**Comment by mparienti** [comment]
+1 on this feature request

I have exactly the same problem when dealing stack traces in log:
1. I have to use the multiline configuration;
2. I can’t define the end of the new log to be send;
3. the error log will not be sent until a new firstline is parsed, which can be very long!

**Comment by kikumoto** [comment]
+1

**Comment by repeatedly** [comment]
Does someone handle this issue?
Yeah, this feature seems good for multiline users.

**Comment by kikumoto** [comment]
I wrote patches for https://github.com/fluent/fluentd/issues/668 - https://github.com/kikumoto/fluentd/commit/396d5a6bc3daf7739a93778c0671b9854c935ce5 .
These patches were forked from v0.12 branch.
I was wondering to decide if I should create pull request or not for this issue because I am not sure how to test it.

**Comment by repeatedly** [comment]
Sending PR is better for users to test your patch.

**Comment by kikumoto** [comment]
OK. I will.
Thanks.

**Comment by repeatedly** [comment]
This is fixed by #775

**Comment by Jorge-Rodriguez** [comment]
@pavel-kolla-kampiki this.
