### ISSUE TITLE
come across some problem when using tail Input Plugin in fluent

### ISSUE THREAD

**Issue by testzlx** [fluent/fluentd#676]
here is the case:I use fluent+influxdb to monitor the nginx accesslog ,when I use tail input Plugin to record the access log ,it only produce one record per second however the log has more than one record in a second ,why? I will appreciate it if you can give me some tips.

**Comment by repeatedly** [comment]
> it only produce one record per second 

What does sentence mean?
Does count logs in influxdb return reduced the result?
You can use `out_copy` and `out_file` plugins to check in_tail plugin works correctly or not.

```aconf
<match test.**>
  type copy
  <store>
    type influxdb
  </store>
  <store>
    type file
  </store>
</match>
```

**Comment by testzlx** [comment]
Thank you,I will try it later

**Comment by testzlx** [comment]
I have tried as you tell me ,here is the configuration file  
<source>
  @type tail
  format  /^(?<time>[^ ]+ [^ ]+) \[(?<log_level>.*)\] (?<pid>\d*).(?<tid>[^:]*): (?<message>.*)$/
  path /var/log/nginx/error.log
  pos_file /var/log/nginx/error.log.pos
  tag error
</source>

<match error>
 type copy
  <store>
  type influxdb
  dbname nginx_gateway
  host 182.92.*.*
  port 8086
  </store>
  <store>
  type file
  path /tmp/error
  </store>
</match>


the result is:   the tmp/error* file is totally the same to the original file(/var/log/nginx/error.log),but  the content in influxdb is incorrect,it only has one record meanwhile  the original file has more than one record .

**Comment by repeatedly** [comment]
Okay. It seems a problem of influxdb itself or influxdb plugin.
Please open it in fluent-plugin-influxdb repository.
