### ISSUE TITLE
Protect against near-zero timestamps resulting from back time_format patterns

### ISSUE THREAD

**Issue by portante** [fluent/fluentd#677]
If one uses a `time_format` parameter that has a bad format, e.g. `%Y:%m:%d %H:%M:%s`, then we don't see any errors and a near zero timestamp is used.

It would be helpful to detect when we are seeing values "near" zero, e.g. 

```
<source>
    @type tail
    path /tmp/python-fluentd.log
    tag python.test
    format /(?<time>[^ ]* [^ ]*) (?<message>.*)/
  time_format %Y-%m-%d %H:%M:%s
</source>
```

**Comment by repeatedly** [comment]
> then we don't see any errors and a near zero timestamp is used.

That's curious. If you use bad format, invalid time format exception should be raised.
Could you paste your actual time value here?

**Comment by portante** [comment]
@repeatedly, here is an example timestamp value that `rsyslog` generates using the template for forwarding, `RSYSLOG_SyslogProtocol23Format`:  `2015-09-26T12:12:08.358897+00:00`

The fluentd config used was:
```
<source>
    type tcp
    port 4001
    bind 0.0.0.0
    tag tcp.rsyslog
    format json
    time_key @timestamp
    time_format %Y-%m-%dT%H:%M:%s
    source_host_key clienthostname
</source>
<match **>
    type stdout
    output_type json
</match>
```

And an example payload (collected via `nc 0.0.0.0 4001`):
```
{"@timestamp":"2015-09-26T12:12:08.358897+00:00","@version":"2015.09.24-0","message":"action 'action 9' resumed (module 'builtin:omfwd') [v8.8.0 try http:\/\/www.rsyslog.com\/e\/2359 ]","hostname":"gandalf.example.com","level":"info","pid":"-","rsyslog": {"facility":"syslog","programname":"rsyslogd-2359","fromhost":"gandalf.example.com","fromhost-ip":"127.0.0.1","timegenerated":"2015-09-26T12:12:08.358897+00:00","protocol-version":"0","structured-data":"-","app-name":"rsyslogd-2359","msgid":"-","inputname":"rsyslogd"} }
```

**Comment by repeatedly** [comment]
Ruby's `strptime` returns broken result and hard to detect in fluentd side.
So you should specify better format like #679 .

**Comment by repeatedly** [comment]
We have a plan to use `strptime` gem(https://github.com/nurse/strptime) instead of `Time.strptime`.
`strptime` gem raises an exception when specify invalid format unlike `Time.strptime`.
So after that, you can notice this problem before received logs.

```rb
irb(main):003:0> parser = Strptime.new('%Y-%m-%dT%H:%M:%s')
ArgumentError: invalid format
```

Closed.

**Comment by portante** [comment]
Is there a PR with this change to use the `strptime` gem?
