### ISSUE TITLE
wrong multiline csv parsing

### ISSUE THREAD

**Issue by nnovikov** [fluent/fluentd#680]
I try configure fluentd for reading postgresql logs:

`<source>`
`  format csv`
`  keys log_time,user_name,database_name,process_id,connection_from,session_id,session_line_num,command_tag,session_start_time,virtual_transaction_id,transaction_id,error_severity,sql_state_code,message,detail,hint,internal_query,internal_query_pos,context,query,query_pos,location,application_name`
`  path /path/to/pg/log.csv`
`  pos_file /var/log/td-agent/pgsql.log.csv.pos`
`  tag file.*`
`  time_key log_time`
`  type tail`
`</source>`

And fluentd can't parse csv multiline. For example:
`2015-10-09 17:25:28.377 UTC,,,47837,,5617f888.badd,1,,2015-10-09 17:25:28 UTC,7/91894775,1242061238,LOG,00000,"automatic vacuum of table ""test_instance.public.test_daemon"": index scans: 0`
`pages: 0 removed, 24674 remain`
`tuples: 0 removed, 10926 remain`
`buffer usage: 7813 hits, 0 misses, 0 dirtied`
`avg read rate: 0.000 MiB/s, avg write rate: 0.000 MiB/s`
`system usage: CPU 0.05s/0.01u sec elapsed 0.07 sec",,,,,,,,"lazy_vacuum_rel, vacuumlazy.c:334",""`

In fluentd log:
`2015-10-09 20:26:24 +0300 [warn]: "2015-10-09 17:25:28.377 UTC,,,47837,,5617f888.badd,1,,2015-10-09 17:25:28 UTC,7/91894775,1242061238,LOG,00000,\"automatic vacuum of table \"\"test_instance.public.test_daemon\"\": index scans: 0" error="Unclosed quoted field on line 1."`
`2015-10-09 20:26:24 +0300 [warn]: "pages: 0 removed, 24674 remain" error="invalid time format: value = pages: 0 removed, error_class = ArgumentError, error = no time information in \"pages: 0 removed\""`
`2015-10-09 20:26:24 +0300 [warn]: "tuples: 0 removed, 10926 remain" error="invalid time format: value = tuples: 0 removed, error_class = ArgumentError, error = no time information in \"tuples: 0 removed\""`
`2015-10-09 20:26:24 +0300 [warn]: "buffer usage: 7813 hits, 0 misses, 0 dirtied" error="invalid time format: value = buffer usage: 7813 hits, error_class = ArgumentError, error = argument out of range"`
`2015-10-09 20:26:24 +0300 [warn]: "avg read rate: 0.000 MiB/s, avg write rate: 0.000 MiB/s" error="invalid time format: value = avg read rate: 0.000 MiB/s, error_class = ArgumentError, error = no time information in \"avg read rate: 0.000 MiB/s\""`
`2015-10-09 20:26:24 +0300 [warn]: "system usage: CPU 0.05s/0.01u sec elapsed 0.07 sec\",,,,,,,,\"lazy_vacuum_rel, vacuumlazy.c:334\",\"\"" error="Illegal quoting in line 1."`

**Comment by repeatedly** [comment]
Default CSV parser doesn't handle multine.
We may reuse this parser > https://github.com/fluent/fluentd/pull/543

**Comment by nnovikov** [comment]
Please reuse. I see no one way for processing postgresql logs in csv format now.

**Comment by repeatedly** [comment]
I'm not sure postgresql CSV logs.
There is no other format in postgresql configuraion?
If so, try above parser or writing postgresql csv parser is better.

**Comment by repeatedly** [comment]
Close. It seems a problem of multiline_csv parser, not fluentd itself.
