### ISSUE TITLE
in_tail with time_format '%Q' with integer value failed

### ISSUE THREAD

**Issue by dieend** [fluent/fluentd#684]
I am using in_tail with json input (log4j2 with json layout), examples of log:
```
{"timeMillis":1444998011395,"thread":"http-nio-5000-exec-5","level":"WARN","loggerName":"org.springframework.web.servlet.PageNotFound","message":"No mapping found for HTTP request with URI [/health] in DispatcherServlet with name 'dispatcherServlet'","endOfBatch":false,"loggerFqcn":"org.apache.commons.logging.impl.SLF4JLocationAwareLog"}
```
I uses in_tail configuration like this:
```
<source>
  type tail
  tag log.*
  format json
  time_key timeMillis
  time_format %Q
  path /var/log/web.log
</source>
```
But it gives error:
```
error="value must be string: 1444998011395"
```
I tried adding ` types timeMillis:string` in configuration but doesn't helps.
```
$> fluentd --version
fluentd 0.12.12
```

Any idea for workaround?

**Comment by repeatedly** [comment]
`format json` doesn't support `types` because `types` for string base parser.
Without `time_format`, `format json` assumes time is integer so it should work.
But your time is millisecond integer so the problem may happen with second assumed plugins.

**Comment by dieend** [comment]
Well. Yeah the problem happens. the timestamp `1444999318195` becomes `47770-11-17T11:36:22+00:00`, 45K years to the future.
Any idea for workaround?

**Comment by repeatedly** [comment]
Use `record_transformer` with `enable_ruby true`.

**Comment by repeatedly** [comment]
There are some workarounds, record_transformer, new parser and etc.
So close this issue.
