### ISSUE TITLE
in_tail plugin; multiline mode; chomp

### ISSUE THREAD

**Issue by reinerRubin** [fluent/fluentd#685]
There is [chomp](https://github.com/fluent/fluentd/blob/5d9eb04a8523ff3ada332e4199aeace1fb7002d6/lib/fluent/plugin/in_tail.rb#L245) in def convert_line_to_event (tail plugin). If we jump from [multiline mode](https://github.com/fluent/fluentd/blob/5d9eb04a8523ff3ada332e4199aeace1fb7002d6/lib/fluent/plugin/in_tail.rb#L245), it can be very confusing get "pattern not match" after first successful match.

Maybe chomp in multiline mode is wrong behaviour?

Sorry for my poor English.

**Comment by repeatedly** [comment]
Hmm... could you show me your example log and configuration?

**Comment by reinerRubin** [comment]
Sorry for my late reply.

Now we are not using multiline mode and I don't have good examples.

I played around recursive regexp: // I know it's wrong and terrible approach but speech is about validation consistency.
```ruby
(?<msg>panic:.+?)$.*?goroutine.+?$\n(?<body>((?<line>^(?!panic:).*?$\n)\g<line>{,3}))
``` 
In first parse statement regexp matches string with \n at the end, but after chomp! regexp does not match. But buffer will be [flush](https://github.com/fluent/fluentd/blob/5d9eb04a8523ff3ada332e4199aeace1fb7002d6/lib/fluent/plugin/in_tail.rb#L291).

Also sorry second link in op must be https://github.com/fluent/fluentd/blob/5d9eb04a8523ff3ada332e4199aeace1fb7002d6/lib/fluent/plugin/in_tail.rb#L291

**Comment by reinerRubin** [comment]
// "comment and close" instead just "comment"

**Comment by tagomoris** [comment]
`convert_line_to_event` chomps the newline at the end of given string, and that does nothing about intermediate newlines in strings which matches `\n` in multiline mode regular expressions.
So the case you reported doesn't occur.
