### ISSUE TITLE
output  forward plugin forward null packets

### ISSUE THREAD

**Issue by zhangchao2015** [fluent/fluentd#686]
the purpose of my project is use one server to accept udp logs and then forward them to the same server but on different ports according to the forwarding weights.
when i use mutiprocess plugin(configured as File1 as listed below),che child processes all started successfully. but when the log events coming,  the process child 1  log "detached forwarding server", and the  process child2 log "pattern not match: "\x00".
Could anybody tell me  where the problem is.? thank you very much in advance.
## File1:   td-agent.conf 
```xml
<source>
  type multiprocess
  <process>
    cmdline -c /etc/td-agent/example_child1.conf --log /var/log/td-agent/fluentd_child1.log
  </process>
  <process>
    cmdline -c /etc/td-agent/example_child2.conf --log /var/log/td-agent/fluentd_child2.log
    sleep_before_shutdown 1s
  </process>
  log_level trace
</source>
```
## File2: example_child1.conf 
```xml
<source>
  type udp
  format json
  tag userlog # required
  port 5140 # optional. 5160 by default
  bind 0.0.0.0 # optional. 0.0.0.0 by default
</source>
<match userlog.**>
  type forward
  log_level trace
  <server>
    host 127.0.0.1
    port 5142
    weight 40
  </server>
  <server>
    host 127.0.0.1
    port 5143
    weight 60
  </server>
</match>
```
## File3: example_child2.conf
```xml 
<source>
  type udp
  format json
  tag userlog # required
  port 5142 # optional. 5160 by default
  bind 0.0.0.0 # optional. 0.0.0.0 by default
</source>

<match **>
  type file
  append false
  format json
  path /home/huangzhe/work/fluent/usermac/access2
  time_slice_format %Y%m%d
  time_slice_wait 10m
  time_format %Y%m%dT%H%M%S%z
  num_threads 1
</match>
```
## File4: fluentd_child1.log
2015-10-22 16:41:36 +0800 [debug]: rebuilding weight array lost_weight=0
2015-10-22 16:42:13 +0800 [warn]: detached forwarding server '127.0.0.1:5142' host="127.0.0.1" port=5142 phi=16.13377186549154
2015-10-22 16:42:13 +0800 [debug]: rebuilding weight array lost_weight=40

## File5: fluentd_child2.log
2015-10-22 17:02:34 +0800 [warn]: pattern not match: "\x00"
2015-10-22 17:02:35 +0800 [warn]: pattern not match: "\x00"
2015-10-22 17:02:36 +0800 [warn]: pattern not match: "\x00"

**Comment by repeatedly** [comment]
Do you try send events from `out_forward` to `in_udp`?
If so, it doesn't work. `in_udp` doesn't care `out_forward` protocol.

**Comment by zhangchao2015** [comment]
yes, i'm trying this.
Do you mean in_udp must not be on the same server as out_forword be ?

**Comment by repeatedly** [comment]
> Do you mean in_udp must not be on the same server as out_forword be ?

`in_forward` and `out_forward` has own protocol on top of TCP so `in_udp` or `in_tcp` with `out_forward` doesn't work.

**Comment by zhangchao2015** [comment]
thank you, I see.
