### ISSUE TITLE
new feature: how to monitor input/output plugin performance

### ISSUE THREAD

**Issue by zhangchao2015** [fluent/fluentd#688]
is there any way to monitor input/output plugin performance? for example , how to know the udp input plugin processing speed for the incoming events and how  about each threads? i think it's very helpful to tune the performance.

**Comment by repeatedly** [comment]
Hard to monitor processing speed because it needs debugger or codeblock in each action.
But you can count received messages by following two plugins.

https://github.com/tagomoris/fluent-plugin-flowcounter
https://github.com/sonots/fluent-plugin-flowcounter-simple

**Comment by repeatedly** [comment]
flowcounter-simple is enough for almost cases.
If someone needs other approach, please re-open it.
