### ISSUE TITLE
in_tail: new settings to ingore some reg expressions

### ISSUE THREAD

**Issue by icy** [fluent/fluentd#695]
The `in_tail` plugin expects all lines from the file to match user's regexp. Is there any way to discard some portion of log file , e.g, to discard all lines that doesn't match some regexp (without generating any warning in `fluentd` logs)?

E.g,

````
<source>
  type        tail
  tag         exim4.mainlog

  format      /^(?<time>[^[:space:]]++ [^[:space:]]+)/
  exclude     /foobar.*/

  time_format "%F %T"
</source>
````

**Comment by repeatedly** [comment]
If you want to simply ignore `pattern not match` logs,
you can use `@log_level` in config > http://docs.fluentd.org/articles/logging#per-plugin-log

**Comment by icy** [comment]
Thanks @repeatedly.  That works quite well.
