### ISSUE TITLE
in_exec does not support regex? 

### ISSUE THREAD

**Issue by pik** [fluent/fluentd#698]
Excuse me if I have misunderstood the correct way to achieve this (the documentation is kind of vague on this point) - but as far as I am given to understand the only way to get the output of a command (short of writing it to a temp file and tailing the temp file) would be using the `in_exec` plugin .e.g 

```
<source>
  type exec
  command heroku "logs -p postgres -t --app my_app"
</source>
```

Unfortunately from the looks of it the `in_exec` plugin does not support regex formatting (https://github.com/fluent/fluentd/blob/master/lib/fluent/plugin/in_exec.rb#L34) as does the [tail plugin where it is documented](http://docs.fluentd.org/articles/parser-plugin-overview).

I'm not sure why the in_exec plugin has it's own custom formatting limitations rather than using already existing support? Or am I on the wrong track here?

**Comment by repeatedly** [comment]
Sorry for the delay. I missed this issue notification...

> I'm not sure why the in_exec plugin has it's own custom formatting limitations rather than using already existing support? 

Because `in_tail` assumes target file is text so `in_tail` doesn't support binary format like msgpack. 
On the other hand, `in_exec` handles TSV / JSON text and msgpack binary.
Maybe, we can share existing parsers but it needs to re-implement parsing mechanizm...

**Comment by repeatedly** [comment]
Hmm... if reuses only text parsers, we may support regex parser without IO code changes.
I will try it later.

**Comment by repeatedly** [comment]
@pik ping?
