### ISSUE TITLE
Invalid regexp

### ISSUE THREAD

**Issue by loveshell** [fluent/fluentd#70]
cat /etc/td-agent/td-agent.conf
<source>
  type tail
  format /^([0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3})\s+\[(._)\]\s+\"(._)\"\s+\"(.*)\"$/
  path /data/logs/www.test.com.log
  tag nginx.access
</source>

<match nginx.access>
  type file
  path /var/log/td-agent/access_log
</match>

[root@nginx ~]# /etc/init.d/td-agent restart
Shutting down td-agent:                                    [FAILED]
Starting td-agent: 2012-09-18 08:18:52 +0800: fluent/supervisor.rb:187:rescue in main_process: config error file="/etc/td-agent/td-agent.conf" error="Invalid regexp '^([0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3})\\s+\\[(._)\\]\\s+\\"(._)\\"\\s+\\"(.*)\\"$': No named captures"
                                                           [FAILED]

Where did we go wrong?

**Comment by nishant-bms** [comment]
hiw
