### ISSUE TITLE
exec plugin usage disallows normal shutdown of server

### ISSUE THREAD

**Issue by jeffaco** [fluent/fluentd#705]
When we use Fluentd exec plugin as a scheduler (i.e. running a task every 20 minutes or something), then Fluentd no longer responds to signals.

End result: You can't reload the server or shut down the server normally, you must issue SIGKILL to bring it down.

I've found this in 0.12.14. Is this a known problem?

**Comment by repeatedly** [comment]
Sorry for the delay.

> I've found this in 0.12.14. Is this a known problem?

Yes. Fluentd uses libev based IO for timer and it waits next call for safety shutdown after receives a signal.
Basically, fluentd focuses on streaming data collecting so 20 minutes interval is not good for fluentd.
It seems batch manner.

**Comment by repeatedly** [comment]
BTW, we can avoid this problem using shorter callback, not direct x minutes interval.

**Comment by repeatedly** [comment]
I will write a patch.

**Comment by repeatedly** [comment]
Fixed by #526
