### ISSUE TITLE
Using two format in one source

### ISSUE THREAD

**Issue by ThibautGery** [fluent/fluentd#711]
Hello,

I'm trying to parse docker container logs using the docker driver. I can parse the Json correctly with the [JSON format](http://docs.fluentd.org/articles/parser-plugin-overview#list-of-built-in-parsers) but I wish to parse the log field

    {"source":"stdout","log":"Hello Fluentd!","container_id":"3fd8678d487e540c7a303e1613101e746c5012f3317434eda93f24351c1928f7","container_name":"/angry_kalam"}

In a real environement, it will be structured logs and I wish to apply the nginx format (or a custom one) on this particular field. Is it possible ?
Then I use the elasticsearch plugin to store everything in elasticsearch to be able to query it with kibana.

	<match docker.**>
	  type elasticsearch
	  hosts http://myes.com
	  logstash_format true
	</match>

Thank you

**Comment by repeatedly** [comment]
If you want to parse a field in the record, use fluent-plugin-parser:

https://github.com/tagomoris/fluent-plugin-parser

If you want to parse multi format mixed logs, use fluent-plugin-multi-format-parser.

https://github.com/repeatedly/fluent-plugin-multi-format-parser

BTW, if you have a question, please use mailing list first.

https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md#got-a-question-or-problem

**Comment by ThibautGery** [comment]
Thanks for your answers.
I will be using the mailing next time. Thanks

**Comment by repeatedly** [comment]
Thank you.
If mix bug reports and questions into one place, users hard to find correct information.
