### ISSUE TITLE
in_tail: symlink issue

### ISSUE THREAD

**Issue by icy** [fluent/fluentd#725]
Can `in_tail` plugin track duplicated files (e.g, because of symlink)? For now, when a path pattern matches multiple files, and one of them is a symlink to another file, `in_tail` plugin will record duplicated events.

Example
````
  <source>
   type tail
   path /var/log/foo/*.log
  </source>
````

If `/var/log/foo/test.log` is a symlink of `/var/log/foo/real.log`, both files are considered as valid sources.

An option to exclude symbolic link is another better way.

**Comment by repeatedly** [comment]
You can use `exclude_path` parameter or use more strict path configuration with prefix matching.
We don't have a plan to add new parameter for such specific case.

**Comment by icy** [comment]
Thanks @repeatedly . Fixing `exclude_path` with strict pattern is the only way at the moment.
