### ISSUE TITLE
in_tail: refresh_interval doesn't work if there is a "permission denied" issue

### ISSUE THREAD

**Issue by icy** [fluent/fluentd#726]
Quoted from http://docs.fluentd.org/articles/in_tail

> * and strftime format can be included to add/remove watch file dynamically. At interval of refresh_interval, Fluentd refreshes the list of watch file.

However, if any file in list has a "permission denied" issue, `fluentd` keeps generating error every second. This will create a hug amount of useless log entries

Example

````
2015-12-01 09:33:43 +0000 [error]: Permission denied @ rb_sysopen - /var/mail/mail
  2015-12-01 09:33:43 +0000 [error]: suppressed same stacktrace
2015-12-01 09:33:43 +0000 [error]: Permission denied @ rb_sysopen - /var/mail/root
  2015-12-01 09:33:43 +0000 [error]: suppressed same stacktrace
2015-12-01 09:33:43 +0000 fluent.error: {"message":"Permission denied @ rb_sysopen - /var/mail/mail","container_id":"bc4cacb9c7f4","ident":"docker"}
2015-12-01 09:33:43 +0000 fluent.error: {"message":"Permission denied @ rb_sysopen - /var/mail/root","container_id":"bc4cacb9c7f4","ident":"docker"}
2015-12-01 09:33:44 +0000 [error]: Permission denied @ rb_sysopen - /var/mail/mail
  2015-12-01 09:33:44 +0000 [error]: suppressed same stacktrace
2015-12-01 09:33:44 +0000 [error]: Permission denied @ rb_sysopen - /var/mail/root
  2015-12-01 09:33:44 +0000 [error]: suppressed same stacktrace
2015-12-01 09:33:44 +0000 fluent.error: {"message":"Permission denied @ rb_sysopen - /var/mail/mail","container_id":"bc4cacb9c7f4","ident":"docker"}
2015-12-01 09:33:44 +0000 fluent.error: {"message":"Permission denied @ rb_sysopen - /var/mail/root","container_id":"bc4cacb9c7f4","ident":"docker"}
````

**Comment by repeatedly** [comment]
You should add right permission or invoke fluentd with correct user.
This is not fluentd problem. Please check your setting.

**Comment by icy** [comment]
There are two problems here

1. File permission issue
2. Fluentd doesn't respect users' setting "refresh_interval", and update the list of files every 1 second

When you start, e.g, MySQL server, the file isn't has a 644 permission by default (in common setup, it's 600 and log files belongs to 640). Exim4 has a similar behavior. That means, it would take some times to fix the issue (often by logrotate script).

**Comment by repeatedly** [comment]
> Fluentd doesn't respect users' setting "refresh_interval", and update the list of files every 1 second

"update the list of files every 1 second" is incorrect. `refresh_interval` is for expanding file list period and it is not related with tracking file mechanizm. The file permission error happens after expands file list.
In your case, sequence is here:

1. in_tail expands file list
2. in_tail launches watcher for each file
3. watcher tries to read logs within 1 second interval but got permission error.

> That means, it would take some minutes / hours to fix the issue (often by logrotate script).

I'm not sure why it takes minutes / hours to change permission. Some users use in_tail for such cases but we didn't receive the report like your problem.

**Comment by icy** [comment]
> "update the list of files every 1 second" is incorrect. refresh_interval is for expanding file list period and it is not related with tracking file mechanizm. The file permission error happens after expands file list.

Thanks for your explanation. 

I take look at the code; `in_tail` uses `Dir.glob` to get list of files; and it accepts all files by default! Should it exclude any unreadable file(s) by default? `in_tail` wouldn't assume that all files are readable IMHO.

> I'm not sure why it takes minutes / hours to change permission. Some users use in_tail for such cases but we didn't receive the report like your problem.

In my setup, it's some logrotate scripts that fix files' permissions. They run once a day (though I can force it to run faster.) We just like to ensure that the problem *would be fixed*.

**Comment by sonots** [comment]
> Should it exclude any unreadable file(s) by default?

Absolutely no. We should tell errors, otherwise users cannot notice.

> In my setup, it's some logrotate scripts that fix files' permissions.

You should chmod a+r on your setup. In your setup way, logs are not read until a log rotation occurs. If fluentd does not tell errors, you cannot notice that you lost logs.

**Comment by icy** [comment]
> Absolutely no. We should tell errors, otherwise users cannot notice.

I agree. But I don't really want to have too many notice (it's *error* in our case.) That means, the expander would get the list, exclude some unreadable files and also send notice to users. The current code just keeps reading the unreadable files, and I don't think that helps for both `fluentd` and sysadmins

> You should chmod a+r on your setup. In your setup way, logs are not read until a log rotation occurs. If fluentd does not tell errors, you cannot notice that you lost logs. 

Well, it's not easy. E.g: On Ubuntu, the init script for MySQL uses `077` umask by default. And if the log files are missing, new files are created with `0600` permissions. When `logrotate` script runs, it will make them `0640` (and also changes uid/gid information from `mysql:mysql` to `mysql:adm`.)

**Comment by icy** [comment]
I've tried to implement this idea in https://github.com/icyfork/fluentd/tree/in_tail-exclude_unreadable_files . You may take a look. Thanks!

**Comment by repeatedly** [comment]
@icy Could you send a PR?

**Comment by icy** [comment]
@repeatedly Yes I've sent. Please take a look. Thanks a lot.
