### ISSUE TITLE
Fluentd does not honor dns cache expiration when hostname is initially unresolvable

### ISSUE THREAD

**Issue by bastichelaar** [fluent/fluentd#731]
Fluentd has an option expire_dns_cache. When the hostname of the Fluentd server is unresolvable, I would expect Fluentd to retry later. Instead, the whole process stops with an exception. This is undesirable.

**Comment by repeatedly** [comment]
You mean fluentd should continue to initialize plugins even if DNS resolution fails?
Hmm... log warning message or providing ignore_dns_failure parameter is acceptable.

**Comment by bastichelaar** [comment]
Yeah, something like that would be great. Our case: we restart our complete environment every night, and the Fluentd server/Elasticsearch cluster is not the first to start up. So every Fluentd client depending on the server to be available will fail.

Providing a flag would be ideal.

**Comment by repeatedly** [comment]
Okay. I will work on it. Please wait.

**Comment by repeatedly** [comment]
v0.14's out_forward now has `ignore_network_errors_at_startup`.
It is hard to backport to v0.12. I'm now working on making v0.14 stable instead.
