### ISSUE TITLE
out_forward causes instability when data cannot be transferred

### ISSUE THREAD

**Issue by dhiltonp** [fluent/fluentd#736]
We are using fluentd over WAN. Sometimes we have network outages, and fluentd's buffers fill up. The unsent data cannot be dropped due to SLAs. The same data is used for real-time system monitoring when possible.

We have been looking at using a combination of writing out_file every second+compressing and copying to destination+in_file from disk outside of fluentd, but improving out_forward and in_forward would be preferred.

Before doing that work, do you have any issues with adding compression and increasing the buffer length of in/out_forward?

**Comment by repeatedly** [comment]
> do you have any issues with adding compression 

Not yet support. See this PR: https://github.com/fluent/fluentd/pull/637

> increasing the buffer length of in/out_forward?

See this article: http://docs.fluentd.org/articles/out_forward#buffered-output-parameters

> The unsent data cannot be dropped due to SLAs.

And using `<secondary>` with small `retry_limit` prevents data loss at long outage situation.
See this section: http://docs.fluentd.org/articles/output-plugin-overview#secondary-output

**Comment by repeatedly** [comment]
The conversation of compression should be kept on PR.
