### ISSUE TITLE
source not using format parameters

### ISSUE THREAD

**Issue by perrin4869** [fluent/fluentd#738]
Using the current `fluentd@0.12.7` gem, I am trying to run the sample Parser plugin from the documentation: http://docs.fluentd.org/articles/plugin-development#parser-plugins

While the plugin works with the default values, whenever I start fluentd I get a warning.

This is my config:

```
<source>
  type tail
  tag cpu
  format time_key_value
  delimiter ,
  path /home/julius/fluentd/time_key.log
  pos_file /home/julius/fluent/time_key.log.pos
</source>
```

The warning I get:

```
2015-12-07 15:46:54 +0900 [warn]: fluent/engine.rb:104:block in run_configure: parameter 'delimiter' in <source>
  type tail
  tag cpu
  format time_key_value
  delimiter ,
  path /home/julius/fluent/time_key.log
  pos_file /home/julius/fluent/time_key.log.pos
</source> is not used.
```

Indeed, the value for delimiter does not get used, which I confirmed by trying to log it inside the plugin.

**Comment by repeatedly** [comment]
It's a documentation bug.
Please add `super` in the top of `configure` method.

**Comment by perrin4869** [comment]
perfect!! Thanks :D

**Comment by repeatedly** [comment]
Updated > http://docs.fluentd.org/articles/plugin-development#parser-plugins

**Comment by buarmin** [comment]
Dear Friend
   I have same problem, But I didn't understand where  I put _SUPER_  keyword ?? 
My Config is `<source>
  @type forward
  port 24224
  bind 0.0.0.0
   format /(?<f1>[^ ]+) (?<f2>[^ ]+) (?<f3>[^ ]+) (?<f4>[^ ]+) (?<f5>[^ ]+) (?<f6>[^ ]+)/
</source>

`
