### ISSUE TITLE
how can fluentd collect logs in docker containers?

### ISSUE THREAD

**Issue by kakalo24** [fluent/fluentd#749]
We know Fluentd can collect logs of docker containers path like this:
/var/lib/docker/containers/0bca52a9608251450762f90be275a24e14365e053f40417d5bfe484369136a2d/0bca52a9608251450762f90be275a24e14365e053f40417d5bfe484369136a2d-json.log

but it can't collect logs that added or modified in docker containers path like this:
/var/lib/docker/aufs/diff/1565d954662e3c01e521a8af4aacff119921d24bfcf56f0fadce5700396d367a/zhoujie111.log

The td-agent.conf:

```
<source>
  type tail
  format none
  path /var/lib/docker/aufs/diff/*/*.log
  pos_file /var/log/td-agent/zhoujie_queue_log.pos
  tag docker.service.*
  refresh_interval 5
  keep_time_key true
</source>

<match docker.service.**>
  type elasticsearch
  host 10.183.163.188
  port 9200
  index_name docker-service
  type_name container
  include_tag_key true
  flush_interval 5s
  buffer_chunk_limit 512K
  disable_retry_limit
</match>
```

**Comment by repeatedly** [comment]
Are there no errors?

**Comment by kakalo24** [comment]
No，there are no errors in log of docker container.
by the way ,i run td-agent by way of the container，
I pull the image from the url:https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/fluentd-elasticsearch/fluentd-es-image

**Comment by kakalo24** [comment]
@repeatedly thank you
I think i have found the reason for the problem.

**Comment by repeatedly** [comment]
Okay.

BTW, please use fluentd ML for asking a question first.
We use github issue for bug report or feature request / discussion: https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md
