### ISSUE TITLE
How can i collect all logs in tail Input plugin include subdirectory 

### ISSUE THREAD

**Issue by kakalo24** [fluent/fluentd#751]
There are many logs in a directory /mnt, and logs have saved at different levels of directory like this:
/mnt/a.log
/mnt/uyer/b.log
/mnt/v1/er/c.log
......
 
How can i config the td-agent.conf with one source that i can collect all logs?

**Comment by repeatedly** [comment]
It means you want to parse several formats in one `in_tail` plugin?

**Comment by kakalo24** [comment]
No,i want to parse all log files in one path that include many subdirectories

**Comment by repeatedly** [comment]
Use `**/*.log`.
