### ISSUE TITLE
Unable to install fluentd on OEL 5

### ISSUE THREAD

**Issue by oazabir** [fluent/fluentd#764]
It tries to download from:

http://packages.treasuredata.com/2/redhat/5Server/x86_64/repodata/repomd.xml

The URL does not exist. 

Also curl is unable to do SSL handshake on this URL:

https://packages.treasuredata.com/GPG-KEY-td-agent

There's SSLv3 error coming up. Thus rpm is unable to download this and install.

**Comment by repeatedly** [comment]
This is why your `$releasever` value has `Server` suffix.
I just added redirect for `5Server`.

> There's SSLv3 error coming up. Thus rpm is unable to download this and install.

You should update your environment to disable SSLv3 access.
SSLv3 is not secure so you should not use SSLv3 anymore.

**Comment by repeatedly** [comment]
BTW, this repository is for fluentd, not td-agent.
If you have td-agent related issue, please open it on here: https://github.com/treasure-data/omnibus-td-agent

**Comment by repeatedly** [comment]
If you get other problem with td-agent CentOS 5 repository, please open new issue in omnibus-td-agent.
