### ISSUE TITLE
Fluentd failed to capture new log file 

### ISSUE THREAD

**Issue by freehan** [fluent/fluentd#767]
Hi 

We use fluentd to capture log files with wildcard matching. But sometimes it fails to capture new log file. I could not find the new log file being recorded into the pos file. Hence I assume fluentd somehow miss it. Here is the source config. 

```aconf
<source>
  type tail
  path /var/log/containers/*.log
  pos_file /var/log/es-containers.log.pos
  time_format %Y-%m-%dT%H:%M:%S
  tag container.*
  format json
  read_from_head true
</source>
```

The new log file stays there but fluentd still did not pick it up. Wonder how to debug this case? Fluentd should have retry right?

**Comment by repeatedly** [comment]
The interval of refresh is 60s: http://docs.fluentd.org/articles/in_tail

> sometimes it fails to capture new log file

Does this happen after 60 seconds passed?

**Comment by freehan** [comment]
@repeatedly Yes. After 60 secs. Even much later...

Here is more information. Those are actually symlinks in the path. The symlinks point to the actual logs somewhere else. This setup works in majority of cases. Not sure if it is related.

**Comment by repeatedly** [comment]
>  Those are actually symlinks in the path.

symlink is re-created? If not, fluentd keep to track old files.

**Comment by repeatedly** [comment]
If you show the actual log generated steps, I can try to reproduce the problem.

**Comment by freehan** [comment]
Sorry for the late response. Here is the timeline:

1. some log lines has been added to a log file. 
2. a symlink pointing to the log file is created in the directory where fluentd is watching.
3. Sometimes no more lines were added to the file. And sometimes there is.

I can reproduce the problem when no more lines were added after symlink was created. Sometimes, fluentd will not pick up the logs.

**Comment by repeatedly** [comment]
> a symlink pointing to the log file is created in the directory where fluentd is watching.

This means symlink and actual log files are in `path` directory at the same time like below?

- conf
```
path /path/to/dir/*
```

- files
```
$ ls /path/to/dir
symlink_file #-> log
log
log.1
log.2
```

**Comment by freehan** [comment]
Nope. The actual log file is in a different directory where fluentd is not watching.

**Comment by freehan** [comment]
I just saw a case where log lines were written shortly after the symlink was created. "Shortly after" means less than 1 sec. And fluentd is not picking up the log. (Still not picking up yet)

BTW, we are getting fluentd agent from here:
/usr/bin/curl -L https://td-toolbelt.herokuapp.com/sh/install-ubuntu-trusty-td-agent2.sh | sh

**Comment by freehan** [comment]
strace the fluentd process output:
`futex(0x14d5054, FUTEX_WAIT_PRIVATE, 928504, NULL) = -1 EAGAIN (Resource temporarily unavailable)
futex(0x14d5054, FUTEX_WAIT_PRIVATE, 928505, NULL`

It looks like the fluentd process is stuck. But its thread is still continuing...

**Comment by freehan** [comment]
Maybe fluentd got stuck during the refresh loop somewhere? 

Can we add a timeout to make sure it won't get stuck?

**Comment by repeatedly** [comment]
> futex(0x14d5054, FUTEX_WAIT_PRIVATE, 928504, NULL) = -1 EAGAIN (Resource temporarily unavailable)
> futex(0x14d5054, FUTEX_WAIT_PRIVATE, 928505, NULL

Interesting... Cool.io uses non-blocking approach so it should not be stuck.
Could you paste more strace result?
I want to know which call is stuck.

**Comment by freehan** [comment]
It is very hard to reproduce. I will try to dig more info when I encounter this case next time. 
Do you have any suggestion on debugging live fluentd process? I tried a few ways. Not very effective.

**Comment by tagomoris** [comment]
It has been long time from last comment. Let me close this now, and please re-open if it occurs again.
