### ISSUE TITLE
Support multiline string in " quoted string

### ISSUE THREAD

**Issue by repeatedly** [fluent/fluentd#772]
`\` is for removing `\n` from the value.

```rb
foo "line1
line2" # => value is "line1
line2"
bar "line1\
line2" # value is "line1line2"
```

**Comment by llby** [comment]
@repeatedly Do you know how to delete 2dfc442(https://github.com/llby/fluentd/tree/2dfc442b237b9c26c00821c14d35df432e2a7aff)?

**Comment by repeatedly** [comment]
I'm not sure but it seems no problem.

**Comment by repeatedly** [comment]
Merged the patch. This will be available in the next version.
