### ISSUE TITLE
install fluent-plugin-fllume success,but report Unknown output plugin 'flume'

### ISSUE THREAD

**Issue by penuel-leo** [fluent/fluentd#779]
use `sudo gem install fluent-plugin-flume` ,got:
> Successfully installed fluent-plugin-flume-0.1.2
> Parsing documentation for fluent-plugin-flume-0.1.2
> Done installing documentation for fluent-plugin-flume after 0 seconds
> 1 gem installed

but reload td-agent conf report
> [error]: dry run failed: Unknown output plugin 'flume'. Run 'gem search -rd fluent-plugin' to find plugins

and use `sudo /opt/td-agent/embedded/bin/fluent-gem install fluent-plugin-flume`,got:
> ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
> Errno::ECONNREFUSED: Connection refused - connect(2) for "your-dns-needs-immediate-attention.dev" port 443 (https://your-dns-needs-immediate-attention.dev/quick/Marshal.4.8/thrift-0.9.3.0.gemspec.rz)

**Comment by repeatedly** [comment]
> ERROR: While executing gem ... (Gem::RemoteFetcher::FetchError)
Errno::ECONNREFUSED: Connection refused - connect(2) for "your-dns-needs-immediate-attention.dev" port 443 (https://your-dns-needs-immediate-attention.dev/quick/Marshal.4.8/thrift-0.9.3.0.gemspec.rz)

This seems not fluentd issue but curious.
System rubygems can connect to `your-dns-needs-immediate-attention.dev` but td-agent's gem cannot...

**Comment by penuel-leo** [comment]
use `sudo gem install fluent-plugin-flume`, i could install ok, and `gem list | grep fluent` got:
> fluent-plugin-flume (0.1.2)
> fluentd (0.12.19)

but can't found out plugin type=flume
Why is that?

**Comment by repeatedly** [comment]
> But still can't find out plugin type=flume

I already said "System rubygems can connect to your-dns-needs-immediate-attention.dev but td-agent's gem cannot..."
td-agent uses own ruby and rubygems to avoid library conflict and ruby version issue.

**Comment by penuel-leo** [comment]
> td-agent uses own ruby and rubygems to avoid library conflict and ruby version issue.

Thank you for replying:) ,  I got it.
Solution: Change the machine name from penuel.dev to penuel.local or something. ".dev" is now a real TLD which screws things up when you try to use it this way.
