### ISSUE TITLE
Fluentd keeps deleted log files open after rotation

### ISSUE THREAD

**Issue by jsravn** [fluent/fluentd#780]
I'm using:

- fluentd 0.12.12
- docker 1.8.3 with `--log-driver=json-file --log-opt max-size=1g --log-opt max-file=2`

Fluentd config:
```
<source>
  type tail
  path /var/log/containers/*.log
  pos_file /var/log/es-containers.log.pos
  time_format %Y-%m-%dT%H:%M:%S
  tag kubernetes.*
  format json
  read_from_head true
</source>
```

`/var/log/containers` contains symbolic links which point to the json logs in /var/lib/docker/containers.

I noticed disk space issues, and lsof shows fluentd holding onto the old rotated logs:

```
# lsof -a +L1
COMMAND    PID USER   FD   TYPE DEVICE   SIZE/OFF NLINK      NODE NAME
td-agent 19733 root   11r   REG  202,1 1000000008     0 486551528 /var/lib/docker/containers/2233caf7c3c21e3a0a553f2a0f9208a7f8d71831e257080217116dddff67a678/2233caf7c3c21e3a0a553f2a0f9208a7f8d71831e257080217116dddff67a678-json.log.1 (deleted)
td-agent 19733 root   12r   REG  202,1 1000000146     0 486551555 /var/lib/docker/containers/2233caf7c3c21e3a0a553f2a0f9208a7f8d71831e257080217116dddff67a678/2233caf7c3c21e3a0a553f2a0f9208a7f8d71831e257080217116dddff67a678-json.log.1 (deleted)
td-agent 19733 root   16r   REG  202,1 1000000006     0 486551554 /var/lib/docker/containers/2233caf7c3c21e3a0a553f2a0f9208a7f8d71831e257080217116dddff67a678/2233caf7c3c21e3a0a553f2a0f9208a7f8d71831e257080217116dddff67a678-json.log.1 (deleted)
...
```

This leads to the problem of running out of disk space.

Is this expected behaviour? It is hard for me to tell from the docs - it seems to imply some options don't work with rotation. It seems like a bug to me. I haven't spent enough time yet looking at `in_tail.rb` to figure it out.

**Comment by repeatedly** [comment]
That's weird.
`in_tail` keeps to track rotated file within configured interval.
After passed its interval, in_tail should stop rotated file tracking...

**Comment by jsravn** [comment]
I will try to dig into it more later. I suspect something odd is going on with the way docker rotates files and the combination of symlinks. I wanted to check if I was doing something wrong in my config first.

**Comment by ssweens** [comment]
I am running into this as well.  No docker, but EC2 Ubuntu 14.04 instance.  fluentd-0.12.19

<source>
  type tail
  format json
  path /var/log/upstart/svc.log
  pos_file /var/log/td-agent/svc.log.pos
  tag svc
  time_key time
  time_format %Y-%m-%dT%H:%M:%S.%LZ
</source>

#lsof | grep deleted
ruby       1214        td-agent   21r      REG              202,1 539203366     263484 /var/log/upstart/svc.log.1 (deleted)
ruby       1214        td-agent   22r      REG              202,1 542489966     263439 /var/log/upstart/svc.log.1 (deleted)
ruby       1214        td-agent   24r      REG              202,1 542489966     263439 /var/log/upstart/svc.log.1 (deleted)
ruby       1214        td-agent   25r      REG              202,1 542126680     263498 /var/log/upstart/svc.log.1 (deleted)

HTH

**Comment by repeatedly** [comment]
Do you use symlink?
Could you teach me your detailed rotation mechanizm?

**Comment by ssweens** [comment]
No, no symlink.  Just the stock Ubuntu logrotate utility.  http://manpages.ubuntu.com/manpages/jaunty/man8/logrotate.8.html
Sorry, I don't know the internals of logrotate to help deeper.

Config here:
/var/log/upstart/*.log {
        daily
        missingok
        rotate 3
        compress
        notifempty
        create 0644 root
        maxsize 500M
}

**Comment by repeatedly** [comment]
Thanks for the info. I will test it on Ubuntu box.

**Comment by repeatedly** [comment]
I tested your configuration on my VMware Ubuntu but no problem.

- fluentd conf

```
<source>
  type tail
  format none
  path /var/log/td-agent/test/test.log
  tag local.test
</source>
```

- logrotate conf

```
/var/log/td-agent/test/test.log {
  hourly
  missingok
  rotate 3
  compress
  notifempty
  create 0644 root
}
```

- lsof result

```
$ sudo lsof | grep deleted
init          1             root   15w      REG                8,1      136     529898 /var/log/upstart/systemd-logind.log.1 (deleted)
dhclient    752             root  txt       REG                8,1  1668160         24 /sbin/dhclient (deleted)
getty       895             root  txt       REG                8,1    32112         14 /sbin/getty (deleted)
getty       897             root  txt       REG                8,1    32112         14 /sbin/getty (deleted)
getty       899             root  txt       REG                8,1    32112         14 /sbin/getty (deleted)
getty       900             root  txt       REG                8,1    32112         14 /sbin/getty (deleted)
getty       902             root  txt       REG                8,1    32112         14 /sbin/getty (deleted)
```

- file list

```
$ ls test/
test.log  test.log.1.gz  test.log.2.gz
```

- version

```
fluentd v0.12.19
logrotate 3.8.7
```

So basically, fluentd's in_tail works well.
I assume there is one corner case between logrotate with compress and in_tail rotation handling.
I continue to try to reproduce the problem.

Could you try `delaycompress` in your logrotate configuration?
This doesn't delete the rotated file so it may be a temporary solution.

**Comment by ssweens** [comment]
It looks like delaycompress or copytruncate will do the trick for me.  It
hasn't occured since the changes shortly after your last note.  Will follow
up if I run into the issue again.  Thanks!

On Fri, Jan 29, 2016 at 2:32 PM, Masahiro Nakagawa <notifications@github.com

**Comment by tagomoris** [comment]
Please reopen this issue when it occurs again.

**Comment by 1mentat** [comment]
Currently seeing this with dropwizard rotation when the tailer input is experience backpressure from output plugin (kinesis in our case). The same case is handled correct w/o backpressure so that seems likely to be the issue. May or may not be the same cause but just throwing this out there. I'm going to review the code for this today.
