### ISSUE TITLE
Fluentd configuration unable to convert the place holder

### ISSUE THREAD

**Issue by Suresh7** [fluent/fluentd#789]
I have a td-agent configuration, which will send syslogs to s3 bucket.
conf:

<source>   
 type config_expander   
 <config>
    type tail
    format none
    path /var/log/messages
    pos_file /var/log/td-agent/tmp/messages.log.pos
    tag sys.messages   
  </config> 
 </source> 
 <match sys.*>   
   type copy

   <store>
    type stdout    
   </store>

   <store>
     type s3
     aws_key_id QQQQQQQQQQQQqqq
     aws_sec_key @@@@@@@@@@@@@@
     s3_region ap-southeast-1
     s3_bucket mybucket.syslogs
     path sys/${hostname}/${tag}/%Y/%m/%d/
     buffer_path /var/log/td-agent/buffer/${tag}/
     time_slice_format %Y-%m-%d_%H
     flush_interval 5m
     buffer_chunk_limit 100m    
    </store> 
 </match>

Problem, here is its not storing mybuket.syslogs/sys/myhostname/sys.messages

All the logs are going into mybuket.syslogs/sys/${hostname}/${tag}

How to solve this? Please Help.

I am using centos 6.

**Comment by repeatedly** [comment]
Close. This queistion is posted on mailing list.
