### ISSUE TITLE
Why agent can stop forwarding messages?

### ISSUE THREAD

**Issue by papiveron** [fluent/fluentd#792]
Hi,

I have a td-agent logs **aggregtor**, and many td-agent logs **forwarders** (agents). The logs aggregator aggregates logs to ElasticSearch.

From time to time I have  no logs aggregated, seems like the agents are no longer forwarding logs to the aggregator.

I've checked on the aggregator (server) and tha agents (forwarders) and everyting seem normal but I would like to know if there a way to troubleshoot fluent log messages processing. 
All processes are running and fine in both the aggregator and forwarders.

I'll continue checking but please give me some helpful idea if you know.

Best regards

**Comment by papiveron** [comment]
Or maybe it's the aggregator which doesn't aggregate logs, because when capturing network packet I can see logs messages exchanged between agents and aggregator.

**Comment by repeatedly** [comment]
I want to know more information.

- Are there no warnings / errors on forwarders and aggregator?
- What the status of each buffer queue? out_forward on forwarders, out_elasticsearch on aggregator. You can get these stat from in_monitor_agent.

> capturing network packet I can see logs messages exchanged between agents and aggregator.
So the situation is forwarders send logs to aggregator but Elasticsearch doesn't store received logs, right?

**Comment by papiveron** [comment]
Hi @repeatedly ,

Yes that is it. ElasticSearch doesn't store received logs or something like that. But I can't see log in the kibana dashboard, and this happens regularly sometime from 1AM to 1AM and for a specific tag.

Thanks.

**Comment by repeatedly** [comment]
https://github.com/tagomoris/fluent-plugin-flowcounter

You can use this and copy plugin combination to check your data traffic.
Please check elasticsearch plugin receives data with specific tag or not.

**Comment by repeatedly** [comment]
No response. We need more information to investigate this issue so temporary closed.
If you hit this problem again, please reopen it.
