### ISSUE TITLE
Idea: Set default encoding to UTF-8

### ISSUE THREAD

**Issue by static-max** [fluent/fluentd#803]
It seems to me that the default internal and external encoding is set to ASCII-8BIT, which causes some problems in my setup, as my unittests use UTF-8 by system default and my extensions fail in production as fluentd uses other encodings.
Is there any reason why fluentd does not use the encoding from the systems locale?
As a workaround I can set

```
Encoding.default_internal = Encoding::UTF_8
Encoding.default_external = Encoding::UTF_8
```
in my plugins, but I don't know if that caueses any problems.

Found in fluentd core:

```
      if defined?(Encoding)
        Encoding.default_internal = 'ASCII-8BIT' if Encoding.respond_to?(:default_internal)
        Encoding.default_external = 'ASCII-8BIT' if Encoding.respond_to?(:default_external)
      end
```

**Comment by repeatedly** [comment]
> Is there any reason why fluentd does not use the encoding from the systems locale?

For unified data handling, same encoding is better.
And for efficient data transfer, use 'ASCII-8BIT' or 'UTF-8' for now.

**Comment by tagomoris** [comment]
Fluentd can handle binary data, which causes Encoding errors if default internal encoding is 'UTF-8'.
