### ISSUE TITLE
Add option to enable source host key for in_forward plugin

### ISSUE THREAD

**Issue by portante** [fluent/fluentd#804]
Like other plugins, it would a really helpful to be able to use "source_host_key" for in_forward as is possible with in_tcp.

**Comment by repeatedly** [comment]
Hmm... in_tcp and in_udp have source_host_key because these plugins are mainly for integrating other systems like syslog.
In this case, adding hostname to event record is hard.

On the other hand, in_forward is for fluent-logger or app local fluentd forwarders.
In this case, adding hostname to event record is easy.
This is why in_forward doesn't have `source_host_key` like option.

**Comment by repeatedly** [comment]
Adding `source_host_key` is easy. Hmm...

**Comment by portante** [comment]
So the use case is simple: the original fluentd forwarder is running in an environment where it gets one hostname, but the central fluentd processor accepting forwarded logs has a different (sometimes more correct) view of the originating host's name.  So I'd like to be able to capture both, one from inside as we do already and one from outside.  This feature is available to both logstash and rsyslog and has proved very helpful in debugging heterogeneous setups.  Thanks!

**Comment by repeatedly** [comment]
I see. Okay, it seems acceptable.
Could you send a PR?
If you are busy, I will make a patch

**Comment by portante** [comment]
I do not have a development environment for fluentd setup right now.  So it will be a while before I could get to that.  If you have the time, that would be great, otherwise I'll get to it when I can.  Thanks!

**Comment by repeatedly** [comment]
I make a patch. Please test it > https://github.com/fluent/fluentd/pull/807

**Comment by portante** [comment]
Great thanks, I'll try this out.

**Comment by portante** [comment]
@repeatedly, okay, this is languishing, as I have not had a chance to try this out yet.  Sorry!

**Comment by tgalyean** [comment]
Any updates as to when this might get merged? Definitely a nice to have..

**Comment by repeatedly** [comment]
I rebased the patch.
I think there is no blocker for merging the patch.

**Comment by tgalyean** [comment]
Thanks! Ill test this out in the next week or so.
