### ISSUE TITLE
fluentd Multiple files

### ISSUE THREAD

**Issue by xdh-ops** [fluent/fluentd#812]
hi,
   I want fluentd A folder log file to a log server, but i don't know how to writ the log file on log server .
I mean, How many files, write how many files, Use only one configuration .
   Thanks .

**Comment by repeatedly** [comment]
It depends on your environment.
in_tail can read multiple files and out_file / out_forest combo can write events to multiple files.

BTW, if you ask the question, please use mailing list first.
https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md#got-a-question-or-problem

**Comment by xdh-ops** [comment]
I'm sorry , thanks , i try out_forest

**Comment by repeatedly** [comment]
np!
If you have a further question, please let me know.

**Comment by xdh-ops** [comment]
Thank you ! The problem is resolved. use the out_forest.
https://github.com/tagomoris/fluent-plugin-forest.git
