### ISSUE TITLE
Cannot set nil value to `flush_interval` in conf file

### ISSUE THREAD

**Issue by joker1007** [fluent/fluentd#814]
a TimeSlicedOutput inherited plugin has `flush_interval` default value.
And I want to revert default behavior of TimeSlicedOutput, I write `flush_interval nil` in conf file.
But I cannot set nil to `flush_interval`.
Because nil is casted to `0.0`.

cf. 
```ruby
# lib/fluent/config/types.rb

    def self.time_value(str)
      case str.to_s
      when /([0-9]+)s/
        $~[1].to_i
      when /([0-9]+)m/
        $~[1].to_i * 60
      when /([0-9]+)h/
        $~[1].to_i * 60 * 60
      when /([0-9]+)d/
        $~[1].to_i * 24 * 60 * 60
      else
        str.to_f
      end
    end
```

Is this spec?

## environment
- fluentd-0.12.20

**Comment by repeatedly** [comment]
Currently spec. From our experience, I first heard "want to set `nil` to `flush_interval`."
Hmm... we may change this limitation since v0.14.

**Comment by joker1007** [comment]
I see.
And so TimeSlicedOuput base plugin should not override `flush_interval` default?

**Comment by repeatedly** [comment]
> TimeSlicedOuput base plugin should not override flush_interval default?

Override should be no problem.

**Comment by tagomoris** [comment]
`flush_mode` of `v0.14` output plugins will solve this problem.

**Comment by tagomoris** [comment]
`flush_mode` was merged into master.
