### ISSUE TITLE
File output formatting

### ISSUE THREAD

**Issue by perrin4869** [fluent/fluentd#840]
I need to output a log file in the following (rather common) format:

```
<timestamp><SPACE>key1=value1<DELIMITER>key2=value2<DELIMITER>key3=value...
```

Using `ltsv` format you can get:

```
key1=value1<DELIMITER>key2=value2<DELIMITER>key3=value...
```

And you can add the timestamp as an additional key-pair value. However, no default way to output the format I mentioned above is available. I am willing to send a pull request with a new format, close to `ltsv`, since I think this should be available by default. Do you have any suggestions how to do this? Thanks!

**Comment by repeatedly** [comment]
> I think this should be available by default. 

I'm not sure your proposed format is popular or not.
Should fluentd support it as a built-in?
Formatter is also pluggable. fluent-plugin-xxx-formatter is not enough?

**Comment by perrin4869** [comment]
The reason I don't think it would be enough is that there is no name to this kind of format, and so other people who could find this useful wouldn't find it because they can't really search for it. If it's built into fluentd, however, and it is part of the documentation, people would be able to find it and use it right away. If there is a reasonable name under which to publish this formatter, however, that'd be enough I think

**Comment by perrin4869** [comment]
By the way, is there a way to achieve log rotation with the `out_file` plugin? Thanks!

**Comment by repeatedly** [comment]
We can search all plugins in plugin list page on fluentd.org: http://www.fluentd.org/plugins/all
So if you have a good name / descrption for your format on description, other users can search it.

**Comment by sonots** [comment]
I do not think the propsed format is well known popular format, so I think we do not need to prepare the format as built-in.

@perrin4869 you can create your own formatter plugin.

**Comment by perrin4869** [comment]
Yeah I guess that's what I'm going to do then. Will try to come up with a good name. Thanks!
