### ISSUE TITLE
Unable to daemonize on fluentd 0.12.21

### ISSUE THREAD

**Issue by bayetovsky** [fluent/fluentd#841]
**Issue description**
Unable to daemonize fluentd on version 0.12.21 due to uninitialized constant Fcntl. Issue seems to be present since this  [commit](https://github.com/fluent/fluentd/commit/7d4baa06b8dc8c89cb05e7ce7950ed867b5c4a98).
I was unable to replicate this on td-agent (fluentd gem version was 0.12.20)

Workaround: Added require 'fluent/load' (or require 'fcntl') to supervisor.rb so we could continue with our tests.

**Setup**:
- fluentd 0.12.21
- ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]
- installed gems:
```
bigdecimal (1.2.8)
cool.io (1.4.3)
did_you_mean (1.0.0)
fluent-mixin-config-placeholders (0.3.1)
fluentd (0.12.21)
http_parser.rb (0.6.0)
io-console (0.4.5)
json (1.8.3)
minitest (5.8.3)
msgpack (0.5.12)
net-telnet (0.1.1)
power_assert (0.2.6)
psych (2.0.17)
rake (10.4.2)
rdoc (4.2.1)
sigdump (0.2.4)
string-scrub (0.0.5)
syslog_protocol (0.9.2)
test-unit (3.1.5)
thread_safe (0.3.5)
tzinfo (1.2.2)
tzinfo-data (1.2016.1)
uuidtools (2.1.5)
yajl-ruby (1.2.1)
```
- Linux 3.8.13-68.el6uek.x86_64 #2 SMP Tue Mar 10 15:26:36 PDT 2015 x86_64 x86_64 x86_64 GNU/Linux
- Configuration file contains only a tail source and a remote buffered syslog match pattern (using remote_syslog plugin)

Ruby was built from source.

**Steps to replicate the issue**
- Build ruby 2.3.0p0 from source with a non-root user (using prefix path to install everything into something such as ~/fluent)
- Install fluentd gem and dependencies locally (machine had no connection to rubygems) - installed gems are presented above;
- Do a simple configuration with 1 source and 1 match.
- Execute: fluentd --daemon /home/cme/fluent/fluent.pid  --config /home/cme/fluent/fluentd/fluent.conf -p /home/cme/fluent/fluentd/plugin/ -vv
- Execution will return:
```
2016-03-09 20:17:48 +0000 [info]: fluent/supervisor.rb:464:read_config: reading config file path="/home/cme/fluent/fluentd/fluent.conf"
/home/cme/fluent/lib/ruby/gems/2.3.0/gems/fluentd-0.12.21/lib/fluent/supervisor.rb:239:in `start_daemonize': uninitialized constant Fluent::Supervisor::Fcntl (NameError)
        from /home/cme/fluent/lib/ruby/gems/2.3.0/gems/fluentd-0.12.21/lib/fluent/supervisor.rb:141:in `start'
        from /home/cme/fluent/lib/ruby/gems/2.3.0/gems/fluentd-0.12.21/lib/fluent/command/fluentd.rb:173:in `<top (required)>'
        from /home/cme/fluent/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /home/cme/fluent/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /home/cme/fluent/lib/ruby/gems/2.3.0/gems/fluentd-0.12.21/bin/fluentd:5:in `<top (required)>'
        from /home/cme/fluent/bin/fluentd:23:in `load'
        from /home/cme/fluent/bin/fluentd:23:in `<main>'
```

**Comment by repeatedly** [comment]
Thanks for the report.
I can reproduce this problem on Ubuntu box.

**Comment by repeatedly** [comment]
Release v0.12.22. Please try!
