### ISSUE TITLE
Resolve all warnings in CI

### ISSUE THREAD

**Issue by tagomoris** [fluent/fluentd#848]
Currently, Fluentd code reports many warnings if it is enabled.
It shows potential errors and troubles in code. So warnings should be resolved basically.

This ticket is blocker for `v0.14.0` release.
1. revert https://github.com/fluent/fluentd/pull/846
2. remove all warnings from fluentd's code
3. remove warnings from dependencies as much as possible

**Comment by okkez** [comment]
See also https://bugs.ruby-lang.org/issues/12026

**Comment by okkez** [comment]
NOTE:

* `lib/fluent/plugin/socket_util.rb:61: warning: instance variable @timeout not initialized`
* https://github.com/fluent/fluentd/blob/master/lib/fluent/plugin/socket_util.rb#L61
* https://github.com/fluent/fluentd/blob/master/lib/fluent/plugin/in_stream.rb#L120

I think we cannot set `@timeout` from outside of the class.
(I think we can replace `@timeout` with `0` or initialize `@timeout` with `0`.)

----

```
lib/fluent/test/input_test.rb:112: warning: method redefined; discarding old emit_stream
lib/fluent/test/input_test.rb:112: warning: previous definition of emit_stream was here
lib/fluent/test/input_test.rb:115: warning: method redefined; discarding old emit_stream
lib/fluent/test/input_test.rb:115: warning: previous definition of emit_stream was here
lib/fluent/test/input_test.rb:112: warning: method redefined; discarding old emit_stream
```

* https://github.com/fluent/fluentd/blob/master/lib/fluent/test/input_test.rb#L110
  * Invoke `Fluent::Test::InputTestDriver#run` multiple times in a process
  * `Fluent::Engine` and `instance.router` is singleton object

**Comment by tagomoris** [comment]
#966 will solve this problem.

**Comment by tagomoris** [comment]
After #966, there are no warning shown in running tests. There are still some warnings in loading scripts, but I think it's not serious blocker for the project.
(For other committers: If it's wrong, please reopen this.)
