### ISSUE TITLE
Initialize config_section even if the section is not specified

### ISSUE THREAD

**Issue by riywo** [fluent/fluentd#850]
## Summary
Like `config_param`, `config_section` would be initialized with default values if the section is not specified in the runtime config.

Related issue: https://github.com/awslabs/aws-fluent-plugin-kinesis/issues/49

## Detail
I use `config_section` for my plugin and its `config_param` has default value, like below:

        config_section :foo do
          config_param :a, :string, default: 'bar'
          config_param :b, :string, default: 'baz'
        end

In my plugin, I'd like to use this section as a kind of configuration object with some default values. If users specify the section, it works.

    <match **>
      type myplugin
      ...other configs
      <foo>
        a aaa
      </foo>
    </match>

    # in the code
    @foo #=> {a: "aaa", b: "baz"}

But if users omit the section to use the default values, it doesn't because the instance variable isn't initialized.

    <match **>
      type myplugin
      ...other configs
      # no sections
    </match>

    # in the code
    @foo #=> nil # actual
    @foo #=> {a: "bar", b: "baz"}   # ideal

https://github.com/fluent/fluentd/blob/master/lib/fluent/config/section.rb#L80 returns `nil`.

I hope it should be added some parameter to behave like this, such as `:initialize`:

    config_section :foo, initialize: true do
    end

## Workaround
Make the section `required` so that users must specify the section like:

    <match **>
      type myplugin
      ...other configs
      <foo>
      </foo>
    </match>

    # in the code
    @foo #=> {a: "bar", b: "baz"}

**Comment by tagomoris** [comment]
IMO the behavior of `initialize: true` looks expected by all developers.
But if we want to instantiate section objects always, we need to raise error if such sections have `config_param` without `default`.
And, `config_section` with `multi: true` should be `[]` if no sections are specified in configuration.

**Comment by riywo** [comment]
Another workaround at plugin side:

````ruby
  def configure(conf)
    if conf.elements.none?{|e|e.name == "section_name"}
      conf.add_element("section_name")
    end
    super
  end
````

**Comment by tagomoris** [comment]
#877 will solve this.
