### ISSUE TITLE
Problem with special timestamp format

### ISSUE THREAD

**Issue by jurgenhaas** [fluent/fluentd#851]
TD-Agent version 0.13.2
OS: Ubuntu 14.04

I'm having a UDP input source from HaProxy which comes with a time format of %d/%B/%Y:%H:%M:%S

My output goes to Elasticsearch and that time is always recognized as string instead of date.

I was looking around and tried time_key and time_format both in source and match definitions, with no luck.

Couldn't find a better place (i.e. Slack link doesn't work) that why I'm asking here, hoping someone would be able to help.

**Comment by repeatedly** [comment]
Could you show your configuration, input example and ES document result?

**Comment by jurgenhaas** [comment]
FluentD config:
```
<source>
  @type udp
  port 20514
  format /^(?<prefix>.+) (?<ps>\w+)\[(?<pid>\d+)\]: (?<c_ip>[\w\.]+):(?<c_port>\d+) \[(?<syslog_time>.+)\] (?<f_end>[\w\.-~]+) (?<b_end>[\w\.-]+)\/(?<b_serv
er>[\w\.-]+) (?<tq>\d+)\/(?<tw>\d+)\/(?<tc>\d+)\/(?<tr>\d+)\/(?<tt>\d+) (?<status_code>\d+) (?<bytes_read>\d+) (?<captured_request_cookie>.+) (?<captured_re
sponse_cookie>.+) (?<termination_state>.+) (?<actconn>\d+)\/(?<feconn>\d+)\/(?<beconn>\d+)\/(?<srv_conn>\d+)\/(?<retries>\d+) (?<srv_queue>\d+)\/(?<backend_
queue>\d+) "(?<http_request>.+)"$/
  tag haproxy.http
</source>
<match haproxy.*>
  @type elasticsearch
  host 127.0.0.1
  port 9200
  time_key syslog_time
  time_key_format %d/%B/%Y:%H:%M:%S
  index_name haproxy
  type_name haproxy
</match>
```

The time key and time key format have been tried in the match and in the source section, with no difference. The result in ES is that all fields are mapped to String and a sample record looks like this:
```
{
  "_index": "haproxy",
  "_type": "haproxy",
  "_id": "AVN2mvNv7smsO7eHZwB7",
  "_score": 1.0,
  "_source": {
    "prefix": "<142>Mar 14 20:28:45",
    "ps": "haproxy",
    "pid": "24798",
    "c_ip": "217.8.58.12",
    "c_port": "47754",
    "syslog_time": "14/Mar/2016:20:28:45.470",
    "f_end": "http_in",
    "b_end": "backend_varnish",
    "b_server": "varnish",
    "tq": "118",
    "tw": "0",
    "tc": "1",
    "tr": "0",
    "tt": "119",
    "status_code": "304",
    "bytes_read": "435",
    "captured_request_cookie": "-",
    "captured_response_cookie": "-",
    "termination_state": "----",
    "actconn": "3",
    "feconn": "1",
    "beconn": "0",
    "srv_conn": "1",
    "retries": "0",
    "srv_queue": "0",
    "backend_queue": "0",
    "http_request": "GET /sites/default/files/css/css_9ebae6cc75e559f623998f01fe082b50.css HTTP/1.1"
  }
}
```

So, not only the date format is not recognized, it's also the integer values that are stored as strings, I guess.

**Comment by repeatedly** [comment]
This seems not fluentd issue.
See this document: https://www.elastic.co/guide/en/elasticsearch/reference/current/date.html

**Comment by jurgenhaas** [comment]
Yes, explicitly setting the format while creating the index and before adding any data is in fact working. However, if there were a way to transform the data in FluentD before pushing that to the backend, that would also be a nice thing and wouldn't require that extra setup step. Is there any way of doing that? I remember something like pre-processing JSON, so I was wondering if other preprocessing was also possible.

**Comment by repeatedly** [comment]
No way for this case because JSON doesn't have date type.
I think this is why Elastic write above document.

**Comment by jurgenhaas** [comment]
OK, little sad but understandable.

**Comment by repeatedly** [comment]
Ah, wait.
If you want to change some field into other type, e.g from string to integer in pid,
you can use `types pid:integer,status_code:integer ` parameter in `<source>`.
Other way, you can use 3rd party `typecast` filter.

**Comment by repeatedly** [comment]
`types` parameter and `typecast` support only json types so
It can't convert string field into date like type.
