### ISSUE TITLE
Agent install scripts points to Trusty repo over plain HTTP

### ISSUE THREAD

**Issue by therc** [fluent/fluentd#857]
If you open `https://td-toolbelt.herokuapp.com/sh/install-ubuntu-trusty-td-agent2.sh` you'll see that it runs curl against an HTTPS URL, but then sets up the APT repo with a plain HTTP URL. Is this intended? I guess the key is protected, so any man-in-the-middle attack could, at worse, only cause denial of service, but these days TLS overhead should be negligible.

**Comment by repeatedly** [comment]
This is fluentd repositoy, not td-agent related repository.
If you open an issue for td-agent, please use omnibus-td-agent repository instead.
