### ISSUE TITLE
fail to simulate sending syslog

### ISSUE THREAD

**Issue by zhaohangbo** [fluent/fluentd#862]
- Environment information: Ubuntu 14.04 trusty.
- My configuration
```
<source>
  type syslog
  port 42185
  bind 0.0.0.0
  tag  syslog
</source>

<match syslogs.**>
  type copy
  <store>
        type file
        path /var/log/td-agent/syslog.data
  </store>
  <store>
        type stdout
  </store>
</match>
```

#### Question

What I did.

I copy one syslog message from  `/var/log/syslog` to a `syslog.sample` file.
**The syslog message is as following:**
`Mar 21 06:41:00 localhost collectd[2320]: rrdtool plugin: rrd_update_r (/var/lib/collectd/rrd/ubuntu/irq/irq-THR.rrd) failed: /var/lib/collectd/rrd/ubuntu/irq/irq-THR.rrd: illegal attempt to update using time 1458567660 when last update time is 1458567660 (minimum one second step)`

Then I use `nc  -4u  -w1  10.132.123.128  42185 < /path/to/syslog.sample` 
to simulate sending syslog from customer

**Why in td-agent.log**
```
[warn]: invalid syslog message data="Mar 21 06:41:00 localhost collectd[2320]: rrdtool plugin: rrd_update_r (/var/lib/collectd/rrd/ubuntu/irq/irq-THR.rrd) failed: /var/lib/collectd/rrd/ubuntu/irq/irq-THR.rrd: illegal attempt to update using time 1458567660 when last update time is 1458567660 (minimum one second step)"
```

**Comment by repeatedly** [comment]
Syslog adds `<1>` like priority header to message over the netrowk.
Please add `<pri>`, pri depends on your message priority, to your syslog.sample.
