### ISSUE TITLE
How to define the regexp format for a certain log

### ISSUE THREAD

**Issue by zhaohangbo** [fluent/fluentd#863]
I am using the syslog input_plugin.

How to define a Regexp for a specific log? 

The syslog I captured is as following:
```
Syslog  96 LOCAL4.CRIT: %ASA-2-321006: System Memory usage reached 90%\n
Syslog 181 LOCAL4.WARNING: %ASA-4-120005: Call-Home license message to http://10.22.183.117:8080/ddce/services/DDCEService was dropped. Reason: CONNECT_FAILED\n
Syslog 175 LOCAL4.ERR: %ASA-3-444303: %SMART_LIC-3-AGENT_REG_FAILED:Smart Agent for Licensing Registration with Cisco licensing cloud failed: 'null'\n
```

**Comment by repeatedly** [comment]
Use fluentd-ui's interactive editor for testing your regex and log pattern.

http://docs.fluentd.org/articles/fluentd-ui#intail-setting

BTW, please follow our guideline > https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md#got-a-question-or-problem
