### ISSUE TITLE
Why doesn't keep_time_key store it/convert it to iso8601?

### ISSUE THREAD

**Issue by larsf** [fluent/fluentd#878]
I am using logstash format to send fluentd output to elasticseach via the elasticsearch plugin. I have a time field that is being parsed -

```aconf
<source>
 type tail
 format multiline
 format_firstline /\d{4}-\d{1,2}-\d{1,2}/
 format1 /^(?<my_event_time>[^ ]* [^ ]*)  .....
 time_format "%Y-%m-%d %H:%M:%S,%L"
 time_key my_event_time
 keep_time_key true
</source>
```

I want to send this to elasticsearch, but it barfs because it receives a string that looks like the time_format above (notice the space between the date and time portion). Elasticsearch wants a 'T' (iso8601) in between. 

The only way I have found to do this is by using the record_transformer to create a new field:

event_time ${(defined?(my_event_time))? Time.at(my_event_time).iso8601(3) : Time.now.iso8601(3)}

and removing the original.

For the elasticsearch plugin I do have:
time_key_format %Y-%m-%dT%H:%M:%S.%L

My goal was to be able to store both @timestamp (which is adhering to the iso8601 format - ignoring the fact that it zeros out the milliseconds ) and event_time in elasticsearch as date types. 

Would like to be able to do this without having to do ruby transformations :-)
It seems to me there has to be a much better way ... I

**Comment by repeatedly** [comment]
keep_time_key is simple. Keep time field in the record instead of deleting time field.
Parser is a general mechanizm, not for Elasticsearch specific.

**Comment by repeatedly** [comment]
If you want to convert time field of the log into iso8601, writing parser plugin or
setting Elasticsearch mapping: https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-date-format.html

I think latter is the proper way.

**Comment by larsf** [comment]
The problem is that ES only allows one date mapping, it defaults to the iso8601 format. Right now @timestamp has the correct iso8601 format, but the kept time key does not, which is why I had to rewrite it using ruby.

**Comment by repeatedly** [comment]
multiple format can be specified by `||`.
Is it not enough?

**Comment by larsf** [comment]
We have this format set in our templates for both @timestamp and the event_time:
"format" : "strict_date_optional_time||epoch_millis"
but again the problem is that @timestamp comes into elasticsearch as a correct iso8601 string like this:
%Y-%m-%dT%H:%M:%S.%L, but the kept time key is sent in as %Y-%m-%d %H:%M:%S (space between date and time) unless I add the ruby code to convert it. I would like to be able to have an option like keep_time_key to specify the format of the kept time key (kept_time_key_format )

**Comment by repeatedly** [comment]
Does `strict_date_optional_time` or `epoch_millis` represent `%Y-%m-%d %H:%M:%S`?

**Comment by larsf** [comment]
It doesn't seem that way:
MapperParsingException[failed to parse [event_time]]; nested: IllegalArgumentException[Invalid format: "2016-04-01 11:46:11,835" is malformed at " 11:46:11,835"];

And joda docs:
http://www.joda.org/joda-time/apidocs/org/joda/time/format/ISODateTimeFormat.html#dateOptionalTimeParser--

**Comment by repeatedly** [comment]
Is this a bug of Elasticsearch or specification?
Maybe, posting it on Elastic forum is better.

BTW, we don't have a plan to add `kept_time_key_format` to parser plugins for now.
It seems rare case and using plugin or writing own parser resolves this problem.

**Comment by larsf** [comment]
Hi,
I don’t think it is an elasticsearch bug (I could be wrong here). Fluentd does the right thing for the @timestamp, so why can’t it do the right thing for other time_keys too? Perhaps that issue is in the elasticsearch plugin… instead of in fluentd proper..

**Comment by repeatedly** [comment]
> I don’t think it is an elasticsearch bug 

I just googled it and I found some multiple date formats examples:

http://stackoverflow.com/questions/34338371/how-can-i-apply-dynamic-date-formats-to-multiple-types-in-elasticsearch
http://stackoverflow.com/questions/29341715/understanding-how-elasticsearch-stores-dates-internally

So if your date pattern is correct, it should work. If doesn't work, it seems a bug of Elasticsearch.

BTW, this is not fluentd core issue.
If you can't work with multiple date formats with fluent-plugin-elasticsearch,
posting a question on Elastic forum or open an issue on fluent-plugin-elasticsearch.
