### ISSUE TITLE
Support conf.d style config directory

### ISSUE THREAD

**Issue by MrMMorris** [fluent/fluentd#886]
Just started using Fluentd and I am loving how easy it is to set up with docker/es/kibana!

I have a question/request. 

I have hosts running different services outside of docker such as Consul and nginx. In order to accommodate configuration files for them all with the current setup, I would either have to: 

1. Build a fluentd docker image for each type of host config. This is cumbersome and not flexible

2. Build one fluentd docker image that contains all possible configuration for all possible hosts it could be run on. This is less cumbersome, but also not very flexible. I also don't yet know if fluentd errors if referenced configuration values do not exist on that host (eg. a nginx conf block when /var/log/nginx doesn't exist)

3. Run a "general" fluentd image with basic conf that is overwritten by a conf specific to that host mounted with docker volumes

The third option seems like the best, but I feel like this could be made easier if something like the nginx conf.d directory were implemented. This would mean you just would put conf files in a specific directory fluentd knows about and it combines all the confs in that directory. This would mean a lot better extensibility. 

Not sure if this was considered, or if it wasn't implemented for a specific reason, but I thought I'd ask 😃 

Any better solutions with the current way things work would also be appreciated 👏

**Comment by repeatedly** [comment]
Fluentd has `@include` directive to read other conf files.
Is this not enough? > http://docs.fluentd.org/articles/config-file#6-re-use-your-config-the-ldquoincluderdquo-directive

**Comment by MrMMorris** [comment]
Ah, I was afraid I didn't RTFM enough!

Thanks for the incredibly timely response!
