### ISSUE TITLE
Fluent::EventTime is serialized as String for JSON

### ISSUE THREAD

**Issue by tagomoris** [fluent/fluentd#897]
```ruby
["tag", Fluent::EventTime.now, {"key" => "value"}].to_json #=> '["tag","1460544188",{"key":"value"}]'
```

This may cause some problems in output plugins.

**Comment by kawanet** [comment]
I guess there are a reason that the nano precision second needs to be serialized as a string to keep its accuracy. It looks, however, it even looses the micro precision, by the way. I mean the bug of `"1460544188"` is the number of digits after the missing decimal point.

**Comment by tagomoris** [comment]
Getting as much accuracy as possible is optional API for EventTime. It behaves as integer for many operations, and provides sub-second value if requested.
I think we should keep this dogma in JSON serialization too.

**Comment by kawanet** [comment]
You mean it should be an Integer but not a **Float** nor String. I see.

----

By the way, just as a digression, I found that JSON spec does not define the specific precision for its number representation. It could deliver Quadruple (128bit) or other extended precision (such as 80bit). Most of JSON parsers would crop it as Double (64bit), however.

![JSON](http://json.org/number.gif)
