### ISSUE TITLE
Fluentd new logo proposal

### ISSUE THREAD

**Issue by frsyuki** [fluent/fluentd#924]
My friend and colleague @johntrabelsi proposed this issue: FLUENTD LOGO IS TOO WEAK.

Here is his proposal:

----

Weak means that it is buried among other logos in a busy page. That is a significant issue as a logo. In a case like this, we can see how the current fluentd logo is weak for general use:

<img src="https://gyazo.com/cd761595a902e3f600c5d6b4c86282e5.png" width="500">

Here is another example that is used in a AWS network diagram:

<img src="https://gyazo.com/3ce590e9f47446f18388bd67cb044bb6.png" width="500">

Note: @johntrabelsi is a designer who has designed http://www.treasuredata.com.

With a strong logo design, visibility improves as following:

<img src="https://gyazo.com/6d2f0b5a46e13d14374138c4bde54346.png" width="500">

<img src="https://gyazo.com/fab1b589a69acafcd3ac93331f973c20.png" width="500">

Especially when the image is simall and letters are omitted, the difference is remarkable.

<img src="https://gyazo.com/714e153204ff9341fa51873636fc7d87.png" width="500">

----

Proposal here is to get a new logo.

An important restriction we should to consider is that the new logo needs to remind the viewer about the current Fluentd logo to minimize confusion. When viewers see new and old logos on slideshare or blog articles, they still should notice that the new logo represents the same thing but just has better looking. And the original motif "a carrier pigeon" should be kept, although many people said that current logo looks like a hummingbird rather than pigeon :-(

With those ideas in mind, here is a logo design:

1: <img src="https://gyazo.com/2f667507b05cd400068dfa6cbf7defab.png" width="500">

The curvy shapes represents the freedom / flexibility of the community / product.
The layering of colors express the multitude of possibilities that fluentd plugin library offers.

2: <img src="https://gyazo.com/3b4571f230a1ce7cfe1a037500469a52.png" width="200">

3: <img src="https://gyazo.com/ede31c0b1721e37c253a4b7567f220ff.png" width="200">

4: <img src="https://gyazo.com/68a4af8af4e4011202638b0ade0e5309.png" width="250">

5: <img src="https://gyazo.com/035cc50e7da25436837bb8f2a896ca5d.png" width="350">

6: <img src="https://gyazo.com/95ea0af34348e24409ed0cd12e088d8d.png" width="350">

7: <img src="https://gyazo.com/12a537522855f37bbc4879785136f96e.png" width="350">

8: <img src="https://gyazo.com/eca92cf5d7dc118fae5b2f88f35a3296.png" width="350">

Here is current logo to compare:

<img src="https://gyazo.com/3dad5009141e59c82cf7bf0242a59ec7.png" width="350">

**Comment by frsyuki** [comment]
I like 1. the best. I think actually his proposal makes sense.

<img src="https://gyazo.com/9abb9bb8c1c0245bcd74c8af33a0f40e.png" width="300">

<img src="https://gyazo.com/f07c3c7eef0824df3e57f425833993e2.png" width="300">

Do you like them?

**Comment by jedisct1** [comment]
I like them!

**Comment by tagomoris** [comment]
I love the current Fluentd logo, but I also think that the current logo is not good in presentation slides, especially for dark background colors. I always use another layer of blight colors: http://www.slideshare.net/tagomoris/fluentd-data-streams-in-ruby-world-rdrc2014/5

Strong/weak difference is also clear and very easy to understand to me.
And I like 1 too.

**Comment by sonots** [comment]
I feel 1. is still weak. Maybe, his head should be larger?

**Comment by nurse** [comment]
1. looks good, but it's felt change the direction to fly.

**Comment by sorah** [comment]
❤️  1

**Comment by hiroyukim** [comment]
1

**Comment by mrkn** [comment]
I like 1, too.
Also, I like 3. It is cool.

**Comment by mrkn** [comment]
> Also, I like 3.

Sorry, not 3, but 4.

**Comment by mururu** [comment]
I like 1.

**Comment by edsiper** [comment]
1

**Comment by tagomoris** [comment]
@sonots competing images are welcome:)

**Comment by sonots** [comment]
+1 for the current logo (keep), then unless better logo is proposed.

**Comment by kiyoto** [comment]
>I feel 1. is still weak. Maybe, his head should be larger?

>+1 for the current logo (keep), then unless better logo is proposed.

@sonots Is your thinking that the new version doesn't improve the logo enough to offset the cost of rebranding? If you can expand on what you mean by "still weak" and "better", that helps us revisit the design.

**Comment by sonots** [comment]
> Is your thinking that the new version doesn't improve the logo enough to offset the cost of rebranding?

right

>  If you can expand on what you mean by "still weak" and "better", that helps us revisit the design.

<img src="https://gyazo.com/714e153204ff9341fa51873636fc7d87.png" width="500">

With the above image, I felt new logo (1) looked like just a blue stuff. I still could not recognize the logo well.

**Comment by johntrabelsi** [comment]
@sonots First thank you so much for your feedback!
My suggestion is to improve a little the colors, not the shape. I think to your point, the light blue is a little "weak" at this size.

Does that make sense?

**Comment by sonots** [comment]
It would make sense, I am not sure, though. I have lack of imagination (sigh

**Comment by johntrabelsi** [comment]
@sonots haha no problem, that's what I'm here for. Translating your emotions into design solutions. :)

**Comment by kiyoto** [comment]
FYI, @johntrabelsi and @frsyuki are iterating on this based on @sonots's feedback. Stay tuned.

**Comment by johntrabelsi** [comment]
Morning everyone!

I wanted first to thank you all for your feedback.
Please find attached the updated version of the logo. What has been done:

1. Bigger neck
2. Smaller wing
3. Tweak a little the colors to look more like a Pigeon neck.

I hope you guys like it, have a great weekend!!
![fluentd_update](https://cloud.githubusercontent.com/assets/15680436/15618962/ebaa2772-2405-11e6-9cb2-b4470c0dad1a.jpg)
![untitled-1](https://cloud.githubusercontent.com/assets/15680436/15618966/f4a12772-2405-11e6-9933-989d23c1ce84.jpg)

**Comment by edsiper** [comment]
:+1:

**Comment by sonots** [comment]
It looks perfect!! It bacame easier to find fluentd in presentation slide. It looks strong. Thank you for your work :)

**Comment by johntrabelsi** [comment]
Sonots, I'm glad to hear that!! 💃

**Comment by kiyoto** [comment]
Bravo. @frsyuki, case closed?

**Comment by GoodDingo** [comment]
**`1`** feels best.

**Comment by hiroru** [comment]
1 looks great! Awesome work

**Comment by frsyuki** [comment]
Great achievement! We go with the last logo @johntrabelsi proposed.
