### ISSUE TITLE
Error installing fluentd due to string-scrub

### ISSUE THREAD

**Issue by rohit01** [fluent/fluentd#932]
- fluentd or td-agent version.
0.12.22

- Environment information, e.g. OS.
Docker - ubuntu:14.04

- Your configuration
NA

- Your problem explanation. If you have an error logs, write it together.

```
# gem install fluentd -v 0.12.22
ERROR:  Error installing fluentd:
	string-scrub requires Ruby version <= 2.0.0, >= 1.9.3.
```

```
# gem -v
2.0.14
# ruby -v
ruby 2.0.0p384 (2014-01-12) [x86_64-linux-gnu]
```

It looks like a recent problem. We created fluentd docker images yesterday without any issue.

**Comment by repeatedly** [comment]
> It looks like a recent problem

What does 'recent' mean?
Yesterday is ok but today had a problem?

**Comment by repeatedly** [comment]
I found the problem by this PR https://github.com/fluent/fluentd/pull/933
Could you try to install string-scrub v0.0.5 before fluentd installation?

**Comment by rohit01** [comment]
Pre-installing string-scrub v0.0.5 works.

```
root@13b7aaa3c12f:/# gem install string-scrub -v 0.0.5
Fetching: string-scrub-0.0.5.gem (100%)
Building native extensions.  This could take a while...
Successfully installed string-scrub-0.0.5
Parsing documentation for string-scrub-0.0.5
unable to convert "\xD8" from ASCII-8BIT to UTF-8 for lib/string/scrub.so, skipping
Installing ri documentation for string-scrub-0.0.5
1 gem installed
root@13b7aaa3c12f:/# gem install fluentd -v 0.12.22
Fetching: fluentd-0.12.22.gem (100%)
Successfully installed fluentd-0.12.22
Parsing documentation for fluentd-0.12.22
Installing ri documentation for fluentd-0.12.22
1 gem installed
```

**Comment by repeatedly** [comment]
Release fluentd v0.12.23.
You don't need to pre string-scrub installation.

**Comment by rohit01** [comment]
Awesome! Thank you so much 💯
