### ISSUE TITLE
handle log file read permission error for in_tail

### ISSUE THREAD

**Issue by larsf** [fluent/fluentd#936]
Currently, in_tail rescues the event raised when fluentd tries to open a non existent log file. Can we please have it handle ENOPERM the same way so fluentd doesn't continuously barf on it

Fluentd's log file filled with:
2016-05-06 10:00:24 -0700 [error]: Permission denied @ rb_sysopen - /var/log/messages
2016-05-06 10:00:24 -0700 [error]: suppressed same stacktrace

rescue Errno::ENOENT is the relevant line

**Comment by repeatedly** [comment]
> Currently, in_tail rescues the event raised when fluentd tries to open a non existent log file

From your logs, the problem is not non-existent file. You should add right permission to your file for fluentd.

**Comment by larsf** [comment]
I would like fluentd to issue one warning for a file it has no permissions to, and go on, just like it it ignores files that it cannot find.

**Comment by repeatedly** [comment]
Similar to https://github.com/fluent/fluentd/issues/903 ?

**Comment by larsf** [comment]
Yes similar. Fluentd behaves very nicely when it encounter a log file it cannot find, I would like to see it do the same for a log file it cannot read - issue one warning and ignore that log file until next restart.

**Comment by repeatedly** [comment]
Can we merge this issue into #903?

**Comment by ashie** [comment]
Fixed by #3378 and #3477
