### ISSUE TITLE
Possible corruption of pos file

### ISSUE THREAD

**Issue by bayetovsky** [fluent/fluentd#947]
While running some tests on fluentd (0.12.22 - daemonized), I've noticed that the pos file on my apache hosts was getting larger than expected. 

The daemon is executed with:
`/opt/fluent/bin/fluentd --daemon /opt/fluent/fluent.pid --config /opt/fluent/config/fluent.conf --log /opt/fluent/log/fluent.log -p /opt/fluent/config/plugin -v
`

The pos file contained the data below: this:
```
$ cat apache.pos
/var/log/httpd/env/access_vhost1_ssl.log.2016-04-02-00_00_00 00000000000154d9        000000000002008f
/var/log/httpd/env/error_vhost1_ssl.log.2016-04-02-00_00_00  0000000000000229        0000000000020090
//var/log/httpd/env/error_vhost2_ssl.log.2016-04-15-00_00_0ffffffffffffffffffff00000000002015/var/log/httpd/env/access_vhost3.log.2016-04-16-00_00_00 000000000000225e        0000000000020159
1//var/log/httpd/env/error_vhost2_ssl.log.2016-04-26-00_00_00       00000000000000d8        00000000000201ce
ar/log/httpd/env/access_vhost3.log.2016-05-02-00_00_00    000000000000213b        000000000002021a
/var/log/httpd/env/access_vhost1_ssl.log.2016-05-09-00_00_00 ffffffffffffffff        00000000000200a9
/var/log/httpd/env/access_vhost1_ssl.log.2016-05-10-00_00_00 ffffffffffffffff        0000000000020249/var/log/httpd/env/access_vhost4.log.2016-05-11-00_00_00      ffffffffffffffffffffff000000202ac
0284
v/var/log/httpd/env/access_vhost1_ssl.log.2016-05-12-00_00_00        0000000000f1a22c        00000000000202/var/var/log/httpd/env/access_vhost2_ssl.log.2016-05-12-00_00_00      0000000000014764     000000000002027f
og/httpd/env/access_vhost3.log.2016-05-12-00_00_00        000000000001a56e        000000000002026f
```

The tail inputs are all configured like this:
```
  <source>
    @type tail
    read_from_head true
    path /var/log/httpd/env/access_vhost3.log.*-00_00_00
    pos_file /opt/fluent/pos_files/apache.pos
    tag access.vhost3
    format none
  </source>

  <source>
    @type tail
    read_from_head true
    path /var/log/httpd/env/error_vhost3.log.*-00_00_00
    pos_file /opt/fluent/pos_files/apache.pos
    tag error.vhost3
    format none
  </source>
```

Is using the same pos_file for multiple sources a mistake?
Even though the file keeps getting updated, isn't there a risk of losing the inode?

**Comment by repeatedly** [comment]
> Is using the same pos_file for multiple sources a mistake?

Yes. See this discussion: https://groups.google.com/forum/#!searchin/fluentd/in_tail/fluentd/ft-U6md5oGc/sUqdFPhSEgAJ
I forgot to update pos_file parameter explanation...

**Comment by bayetovsky** [comment]
Ok thanks for the quick reply once again repeatedly. I was following the documentation directive that stated:
> pos_file handles multiple positions in one file so no need multiple pos_file.

I guess that it should instead read something along the lines of:
> pos_file handles multiple positions in one file so no need for multiple pos_files directives per source.

I guess this issue can be closed then since it was a misconfiguration.

**Comment by repeatedly** [comment]
I updated the document: https://github.com/fluent/fluentd-docs/commit/b9ed143b9f2cc465749acbc8ecb73381b8ac7cc2

**Comment by bayetovsky** [comment]
With the new updated docs, closing this issue since there is no reason to keep it open now.
