### ISSUE TITLE
update to td-agent rpm?

### ISSUE THREAD

**Issue by davgibney1** [fluent/fluentd#958]
Hello,
Just wondering, when you might update the td-agent rpm? Appears last update was in Feb, so it's missing out on new features such as the out_s3 plugin's ability to call the S3 API in order to use SSE-S3

Thanks

**Comment by kakoni** [comment]
As a workaround I tend to rollout my own using https://github.com/treasure-data/omnibus-td-agent

**Comment by repeatedly** [comment]
Ah, I just noticed this issue.

td-agent release cycle is about 3 months except for emercengy release.
If you want to updated rpm quickly, you can build own rpm by using omnibus-td-agent mentioned by kakoni.
Or if you want to update one gem, you can update it via `/usr/sbin/td-agent-gem update fluent-plugin-xxx`.
