### ISSUE TITLE
"An error occurred while installing string-scrub (0.1.1)" during install

### ISSUE THREAD

**Issue by tmontney** [fluent/fluentd#991]
Following this guide: http://qiita.com/nurse/items/8bbb194982c685f1e795

- Ruby 2.2.4 (x64)
- Git-2.8.3 (x64)
- DevKit 64-4.7.2-20130224-1432
- Windows Server 2008 x64 R2 (Build 7601 SP1)

I followed the installation exactly. When I get to _bundle_, everything installs fine except _string-scrub_. The next command, _bundle exec rake build_, fails with 

```
Could not find gem 'parallel_tests (>= 0.15.3) x64-mingw32' in any of the gem so
urces listed in your Gemfile or available on this machine.
```

I'm not sure if this pertains to string-scrub (or the other way around). After that error, it suggests _bundle install_, but fails with the first error.

The only thing I found ambiguous was the second step in DevKit "edit config.yml". I'm assuming you're supposed to confirm the root path points to the Ruby installation directory?

I've noticed other issues similar to mine, but seem to refer to an existing installation.

**Comment by repeatedly** [comment]
If you did "git checkout windows", it was incorrect.
If you want to use windows supported version, you should use master.

@nurse I remember correctly, I asked you update this instruction before. Please update the content.

**Comment by nurse** [comment]
updated!
