### ISSUE TITLE
Fluentd UDP Input stops processing logs and hangs

### ISSUE THREAD

**Issue by KunalAggarwal** [fluent/fluentd#998]
Basic Information

- fluentd v0.12.25
- OS: CentOS 6.6, Ruby: ruby 2.3.1p112, Machine: 2 Core CPU with 8GB RAM
- Configuration File:
```
<source>
        type            udp
        port            5139
        bind            0.0.0.0
        body_size_limit 10KB
        time_format     %d/%b/%Y:%H:%M:%S
        tag             system
        format          /^.*?<\d+>.*?\s+(?<host>[a-z]+-\d+-\d+)\s+(?<source>\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})(?<proxy_chain>(,\s*(.*?|(?:\d+\.){3}\d+))*)((\d+\.){3}\d+) - - \[(?<time>.*?) \+\d+\] "(?<method>[A-Z]+)\s+(?<url>.*?)\s+HTTP/(?<version>[0-9\.]+)"\s+(?<response_code>\d+)\s+(?<response_time>\d+)\s+"(?<referrer>.*?)"\s+"(?<user_agent>.*?)"\s+"(?<cookies>.*?)"\s+(?<response_time_2>\d+)\s+(?<response_size>\d+).*?$/
</source>

<match *.**>
        type                    kafka
        zookeeper               127.0.0.1:2181
        zookeeper_path          /brokers/ids
        default_topic           mylogs
        output_data_type        json
        compression_codec       none
</match>

```

*Issue:*

I start my fluent instance by providing the above configuration file using the following command:

`fluentd -c /etc/fluent/mylog.conf --no-supervisor`

Fluentd starts perfectly with a CPU utilization of 10-15%. Logs get parsed and pumped to Kafka running on localhost. Using a consumer I can see logs getting pushed.

After some random amount of time (can be 30 mins to 8 hrs), fluentd stops processing logs and is stuck. When I press Ctrl + c, to stop fluentd, I see the following line and its stuck there:
```
2016-05-27 23:30:44 +0530 [info]: shutting down fluentd
2016-05-27 23:30:44 +0530 [info]: shutting down input type="udp" plugin_id="object:836be8"
```
 Looks like its stuck on stopping the UDP Port.

Here is the output of top when fluent is stuck, as can be seen CPU utilization is quite high:
```
top - 23:32:04 up 14 days,  8:38,  1 user,  load average: 1.81, 2.62, 3.10
Tasks: 199 total,   2 running, 195 sleeping,   1 stopped,   1 zombie
Cpu(s): 59.6%us,  1.4%sy,  0.0%ni,  4.0%id, 34.7%wa,  0.0%hi,  0.3%si,  0.0%st
Mem:   7927844k total,  6137340k used,  1790504k free,     1632k buffers
Swap:  4194300k total,        0k used,  4194300k free,   130384k cached

  PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND
13305 root      20   0  412m  32m 4876 S 96.7  0.4 224:51.15 ruby
```

I have to send the process to background and kill it. 

Here is fluent startup log:
```
2016-05-27 23:33:11 +0530 [info]: reading config file path="/etc/fluent/mylog.conf"
2016-05-27 23:33:11 +0530 [info]: starting fluentd-0.12.25 without supervision
2016-05-27 23:33:12 +0530 [info]: gem 'fluent-plugin-kafka' version '0.1.4'
2016-05-27 23:33:12 +0530 [info]: gem 'fluentd' version '0.12.25'
2016-05-27 23:33:12 +0530 [info]: adding match pattern="*.**" type="kafka"
2016-05-27 23:33:12 +0530 [info]: adding source type="udp"
2016-05-27 23:33:12 +0530 [info]: using configuration file: <ROOT>
  <source>
    type udp
    port 5139
    bind 0.0.0.0
    body_size_limit 10KB
    time_format %d/%b/%Y:%H:%M:%S
    tag system
    format /^.*?<\d+>.*?\s+(?<host>[a-z]+-\d+-\d+)\s+(?<source>\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})(?<proxy_chain>(,\s*(.*?|(?:\d+\.){3}\d+))*)((\d+\.){3}\d+) - - \[(?<time>.*?) \+\d+\] "(?<method>[A-Z]+)\s+(?<url>.*?)\s+HTTP/(?<version>[0-9\.]+)"\s+(?<response_code>\d+)\s+(?<response_time>\d+)\s+"(?<referrer>.*?)"\s+"(?<user_agent>.*?)"\s+"(?<cookies>.*?)"\s+(?<response_time_2>\d+)\s+(?<response_size>\d+).*?$/
  </source>
  <match *.**>
    type kafka
    zookeeper 127.0.0.1:2181
    zookeeper_path /brokers/ids
    default_topic hotellogs
    output_data_type json
    compression_codec none
  </match>
</ROOT>
2016-05-27 23:33:12 +0530 [info]: brokers has been refreshed via Zookeeper: ["localhost:9092", "localhost:9093", "localhost:9094"]
2016-05-27 23:33:12 +0530 [info]: initialized producer kafka
2016-05-27 23:33:12 +0530 [info]: listening udp socket on 0.0.0.0:5139
```

Fluent gets stuck every few hours. Have tried tweaking all parameters to no success. What is the issue, I can't seem to figure out. Please help. Let me know if any more information is needed, would be happy to share it.

P.S. - The volume of input logs is around 40-50 log lines per second. These are HTTP Access Logs.

**Comment by KunalAggarwal** [comment]
So I have been debugging. Looks like the regex parser gets stuck.

The problem is, for a log line greater than 8KB in size, in UDP and TCP receivers I get 2 messages, one of 8192 bytes and the other of remaining bytes, despite setting the 10KB limit in config. The regex parser hangs up on the first 8192 packet. I am able to replicate the issue. Let me know what all information is needed to debug this issue.

**Comment by repeatedly** [comment]
> in UDP and TCP receivers I get 2 messages, one of 8192 bytes and the other of remaining bytes,

`TCP`? Who listen the TCP protocol?

>  The regex parser hangs up on the first 8192 packet

Fluentd's parser should return "pattern not match" for unmatched log.
Could you test your format and log in raw ruby like below?

```rb
p /your format/.match("your log line")
```

**Comment by tagomoris** [comment]
Are there any more information or comments on it?
Please reopen if exists.

**Comment by KunalAggarwal** [comment]
Okay So I am using the latest fluent version and still encountering the same issue. 

Given below is my Fluent Config:

```
<source>
        type            udp
        port            5120
        bind            0.0.0.0
        body_size_limit 100KB
        time_format     %d/%b/%Y:%H:%M:%S
        tag             system
        format          /^.*?<\d+>.*?\s+(?<host>[a-z]+-\d+-\d+)\s+(?<source>\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})(?<proxy_chain>(,\s*(.*?|(?:\d+\.){3}\d+))*)\s*((\d+\.){3}\d+) - - \[(?<time>.*?) \+\d+\] "(?<method>[A-Z]+)\s+(?<url>.*?)\s+HTTP/(?<version>[0-9\.]+)"\s+(?<response_code>\d+)\s+(?<response_time>(\d+|-))\s+"(?<referrer>.*?)"\s+"(?<user_agent>.*?)"\s+"(?<cookies>.*?)$/
</source>
<match *.**>
        type stdout
</match>
```

Following is the log line (this is a general Apache Log Line in which I have garbled alphabets to mask data):

`<13>Afu 19 13:26:58 10.66.11.18 <13>Age 19 13:26:58 kldg-11-18 203.115.114.234, 203.115.114.234, 10.96.11.220 10.96.109.10 - - [19/Awn/2016:12:52:21 +0530] "GET /juldcrjxrl%7n%22kxyokmcr%22:%22yyf%22,%22epplcowy%22:%22toe%22,%22sfcmogowjyj%22:%22cl%22,%22mlgwvptuiar%22:%22ehxhe%22,%22tuckpii%22:%2220140222162609767%22,%22fgylalxqm%22:1474741800000,%22qmflvqf%22:1475173800000,%22tlrmfufopr%22:5,%22yyfcyekkbj%22:1,%22mmzwxkrvbgcgrhdm%22:3,%22ztscgwekleiiypnxwck%22:0,%22yoqrmgsykdbdcvnlp%22:%223j0a%22,%22ixpcvyhyub%22:%22aeonu%20kxoutwtnu,ffd%22,%22psuyhodu%22:%22ih%22,%22hddgzmsnhix%22:%22zg%22%7p,%22echwwpwrudtdzrjqh%22:%7g%22ungjoqznqjy%22:ewrfe,%22wrxyediygqcrussps%22:0,%22tjukyozoatiaydly%22:0,%22epevckhtybnxtuzhwtn%22:0,%22lqfndfnjpysghjfmkeisgsgpo%22:10.0,%22bnyglnvchvdumrpfmcs%22:aqdf,%22ujtvcijiy%22:odyvt,%22xrmeritskzzqsdboxmgzgr%22:%7v%221%22:%7e%22qzgv%22:%2224%20nmha%20zqpgk-bu%22,%22jhbroldy%22:7%7l,%222%22:%7a%22ztjf%22:%22ehz%22,%22ulbqrqto%22:5%7x,%223%22:%7x%22mpjm%22:%22shwedpnnwz%20ehldaixyzk%22,%22ihmkopxx%22:6%7j,%224%22:%7h%22tyuq%22:%22gnnyhpcip/sektic%20dleo%22,%22btacnuzp%22:3%7m,%225%22:%7v%22lkmw%22:%22mvxycda%22,%22xpjysemn%22:4%7k,%226%22:%7m%22gkwo%22:%22yezckzvpxy%22,%22mfriqqkn%22:2%7g,%227%22:%7v%22vaml%22:%22fecttvrc%20lyss%22,%22lmfkribt%22:1%7f%7t,%22rpdxbexfrs%22:[%7a%22me%22:%2220140222162609767%22,%22gpgqlvtui%22:%22%22,%22yhzh%22:%22xwgmo%20lzwnszobf%22,%22bfkywignjhcvwv%22:%7u%22ndtwk%22:%22ojmxt%20juvbycyps%22,%22vdsybibxt%22:phjih%7r,%22saujlhbiqnwz%22:%22vxdbl%22,%22jiwpvsjl%22:%22ym%22,%22jnjhtubqmbt%22:[%22ahgpr%204.3%20yh%20yvazia%20arxesyxoj%22,%22kblxw%204.4%20kx%205%20sve%20slnhsxbs%22],%22kvppdjv%22:[%7s%22ozbcrht%22:%22sdfbgitkd_frvvna%22,%22fmmdbxtokuc%22:%22ceppsr%22,%22khikycjbemj%22:1,%22dwpha%22:4.3,%22libsxnf%22:%22xjhzf%204.3%20xn%20wnookz%20uppcaniio%22%7a,%7d%22dnofvel%22:%22dlvyxeawbdivf_rclanm%22,%22ihtpldimagq%22:%22bmthqnrj%22,%22xvuzczczqej%22:1,%22cguha%22:4.4,%22rzaqizy%22:%22owflq%204.4%20yo%205%20uct%20kgydqvau%22%7q],%22vwjsuumw%22:ylhoq,%22tcmqimmibggknhw%22:yltk,%22fmvkk%22:%22eiv%2roukycggauxv%2fbhmjwdjf7lnwf4qdl%2g7bwgmeqenl%2daru1a1vh65sdd5w5r1nzedsrvnzcvik1yv2rbayd3hxlb1u1gy5gxcrh4wuhjt85prr9pn%2q5%2kpczpzc2cifl5ylgygrluibgktsoexnbqyayndq%2ghnrv8zqgqfssndhqo567tt7ulz%2efhce3%2xcxyo%2aomhwm%2emizppd808jnbls2pvikbjqba5rsino7ugcfri7fjyqknyre0h0ch1tcajdpnkzlbulijw1wofrgveo2kgbpyxmp1hz%2eo9q5aecclawrpi%2a6kebot6mdaaln45wn%2py5zvjbgvkdsn3o7h58vasjj8bcjome121tdogiwrvv9xp7iw%2ky7qhkxbgl%2jozzjemecz39qqqhrfkn4iz7ndheys1h86l%2ynqgj1eqbqcuigshe7jjezepr3nb%2aonpl97k6%2thqjkgrimii38xq%3p%3o%22,%22rwrfnuxurczhqqllihk%22:xsuyc,%22mtcxzwpbdxmfxgcckm%22:[],%22nujotmwychme%22:hmpqq,%22iobthjlfon%22:%22//xwtvpvnm.ltorky.bye/uihqjre/mzynzk/mcdsms/lhixqrazhiwjmv_1461650955811_kmodtxy.ihf%22,%22llndyjiaubox%22:4.2,%22mohzkserukcjsddn%22:34,%22krztgzvzdbmk%22:4.0,%22dloukcktotiba%22:%221%22,%22wtagxggm%22:%22w%22,%22bhjzqtotnnsxx%22:ooawi,%22tnbzkcgqtx%22:%7a%22ajkk%22:%22fpvkb%22,%22vrvlj%22:3%7d,%22zwklkko%22:%7f%22hozg%22:[%22qhbxk%20smy%22,%22wbhnz%22,%22cwwyi%20zennp%22],%22lkch%22:%22xct%22,%22etma1%22:%22pjtftq%20cebiq%20zprmxgno,%20xmqde%20sewx,%20stwad%22,%22sqfq2%22:%22xwekc%22,%22xxiwo%22:%22oto%22%7i,%22plpuwjiqvek%22:%7q%22holiaibarlpxf%22:[],%22zzxdjkys%22:%2215.277958%22,%22eovcvdbvd%22:%2273.928509%22%7o,%22kubjumiuv%22:%22e%202%20xexw%20yifvxcdo,%20fxzlqv%20ls-oh,%20ktyytl%20ufmo,%20uogevhq%20zimgsr,%20ugbkjrqj%20dpuewx,%20ephv%20iykicfm,%20srcwkat%20tcafmvph%22,%22plkkkqipcitmppzrpal%22:%22/f003ar%20eqyig/r003v///%22htglyhc///%22/s003xjpely%20ouwmjjzna%20gr%20z%202%20zhrd%20szywnqqd,%20oexkagi%20vu%2020.9%20tyz%20arhi%20tmx%20kivfzrnhqqcco%20dmfpfdn,%205.9%20beq%20mytx%20gnesgnk%20xusvkau%20jrjrymg%20ztk%203.8%20jxt%20gprq%20jcdfqd%20iqv%20lsdzdfnw./n003mng/z003o/z003hmx/h003htcl%20jrzjfpwm%20li%20imregyts%20sj%20zbo%20pgrct%20xt%20alebu%20coc,%20kt%20yqdxnpzp%20ftxweacvmnt%20thr%20xvtl-mhkcawcdt%20iclrf%20xefyyvwp%20mina%20dcbydo%20gqzabnumfdei.%20kc%20jvoy%20yfaeidnxn%20ipnjsxr%20vol%20qisrlrgfeiwq,%20smjby%20enhqajdrob,%20hdwwrece%20pqjkaitj,%20frg/kpauky%20xvfss,%20qxasspmlvgsl,%20nbwy%20evk%20ikdcsvd%20zperw%20(pn%20ylcrsiu),%20lrfol%20muhzg,%20domv%20asudqan%20qgzikv,%20kol%20iuuwqlyz%20lxcnvjqxo.%20eqwurtwirh%20fkds%20mkbc%20oht%20kmb%20fhcbobdzr%20jm%20xrkiafewsg%20zpwdz./a003vhg/p003n/a003qcd/v003wlw%20sjrzgn%20bwauthtzdd%20fbpg%20ig%20xp-nq,%20wtkvby%20jfjp,%20vnefbfq%20wmavgv,%20rteickix%20tcmwkp,%20haib%20uwxwpqm%20(8%20op%20er%2010%20kh)%20xxl%20ojxzevt%20mvmmbhap.%20bcgpqv%20qmy%20jmmmt%20xlqglgqxau%20cxpn%20hbdoiehy%20yfaywq,%20trstj%20oaqoop,%20bgwd%20ppclicl,%20ihrumav%20iiabefb/%20pzrltit%20cxwmvqzvw,%20gbikj%20wuwcgxy,%20qnigaww,%20xgdgxrgx%20oi%20bhll%20dms%20zdvbighzjbe%20wf%20ng%20dcjyv%20rskxxz./f003yyx/n003c/m003qlz/o003iphwsne%20biq%20vaptvh%20t%20wabgbz%20cg%20mfcbgt%20xa%20yxi%20lw-qscsu%20xzbbrbvigf%20mnwq%20hgsdmoiq%20bvhuimsy%20zzqruemp.%20zrbq%20is%20vclgrcgqk%20lvhlaosn%20dlz%20pdgweoer%20dnx%20cjles%20avdyzg%20osnr%20fdbpxvldm%20dujl.%20jne%20vjqm%20uwewte%20zcli%20kkpmvmdps%20acs%20rfqokrxuq%20go%20gem%20nplobt%20wsheh%20ocenkc%20mmog%20mnkic%20bqt%20wypaotfp%20sfgxpqul%20ecs%20qlmxhdv%20wr%20kpfjjz%20epc%20fscclfmk./i003fhq/v003z/i003unk/r003egzntl%20rersl%20aqpxfprfs,%20glfeh%20rstm%20nfooxh,%20hzvxberdk%20yjx%20luejc%20mjg%20qx%20bvh%20vkuni.%20nbb%20k%20yjkzgbqf%20rgvxvwbube,%20xewova%20ibw%20jye%20ls%20zoavt%20hjk%20zxtb%20fsncrhyz%20zo%20arqsk%20ws%20qyi%20xttvowdlk./o003vyg/u003b/f003rze/m003zygy%20jeavq%20so%20zmpz%20xc%20cblpe%20mwtgb%20qki%20gxgul%20rut%20ejda%20ryp%20xrjpvqvotov%20kskohfip%20fg%20gwp%20lkyea%20qa%20ioeg%20nljc%20rw%20vaur%20atrmsktruyu%20nhtxdz%20wqbn%20dabocch%20trfmg%20kgswt%20(1.6%20pnf),%20hswexlghcl%20gbzud%20(3.2%20ft),%20crweu%20eifajb%20(4.9%20cv),%20pmldqw%20txawm%20(5.2%20jpy),%20sgb%20o%20updh%20(5.2%20jpk)./o003lci/x003t/q003cru/e003pdbiseemtsa%20kgzmeg%20ier%20wub%20nwceomht%20ftfn%20uce%20nrz%20ocajs%20ensjva%20zy%20idcqa%20oqtbhbydc!/h003s/v/f003a%22,%22yavshsljtscqjge%22:tfgw,%22gzbzwldkmduprhmec%22:[2,5,6],%22vcrmqmnfxrivoq%22:beiuo,%22iojnnfbmqlb%22:%7d%22rijrexmayrp%22:%22j%22,%22vcbxpxfuyovs%22:%7m%22znkik%22:2160.0,%22rteolblguss%22:0,%22mipbwlrxqqbg%22:%7m%22jo%22:%22lrm%22,%22lxobk%22:%22:oipulk%20jpdrb%20%22,%22zlguoycmaycoub%22:1.0,%22cpvhgxufsvpegr%22:%22%22%7i,%22dvuhemhkhgapqhgct%22:2160.0,%22ynkmiqnfjzjsqktklez%22:2160.0,%22jotdgvqjbfvxkgjnp%22:10800.0,%22ddtgbuguviedikglfln%22:10800.0%7u,%22ocwbxadkubxgwmeldhnudptfw%22:%7v%22qytro%22:15300.0,%22mbaztktjlqw%22:0,%22qxslbhbvdfjc%22:%7j%22ra%22:%22vxf%22,%22bftzv%22:%22:ksdrnc%20ojcco%20%22,%22kgsgxtvcsvziri%22:1.0,%22iulykispmskblw%22:%22%22%7a,%22tqaugwbuliigqgwbk%22:15300.0%7y,%22yffskxnsgvvyhnzgfv%22:0.0,%22ihqygdsgwmqqcxpjdsiqnbjuxlxwlh%22:%22%22,%22esctftrikh%22:%7g%22hognt%22:0.0%7m,%22xevommme%22:%22ysa%20mpljqxtsh,qeqji%20qtdfi%22%7r,%22kgflidycgi%22:%7e%22ajrgakxyzxpuksu%22:%7c%22muuzlpepktdiansas%22:lehzy,%22duxamimktcqcod%22:dczkh%7m,%22rhsjzlnuqavcshm%22:0%7r,%22eqgyvhrehjt%22:%221%20eo%22,%22komcyegojumn%22:%2211%20wx%22,%22huihpwreei%22:%22uzjc://veafys.aejchctveg.swd/mgbllqmymj/tspc/gpcgkc/ixcslr?dpyywdj\\j003o20140222162609767\\b0026dlak\\k003hpgo\\v0026zgoyxxr\\l003rtb\\c0026tigxqnauzyeywerch\\z003t3u0j\\f0026uivciey\\m003y09252016\\b0026cbwdkthb\\h003c09302016\\r0026xou\\y003axzjaroaj_zae_yivpqxw%22,%22cskspbcextgi%22:{%22ykepfoqduzwvwullbpke%22:68.6,%22hnmya_eqewn%22:%22v%22,%22sqpjmuksl%22:4.2,%22ninbdnmvxbzet%22:3 HTTP/1.0" 404 134676 "aqbeu://nvgixg.zwlbycbxcp.thn/vqexfgxros/svyo/yspows/dhyjoh?_jffji_axehx=1471591250384&honq=txz&kjhmcrl=rl&jrxqqkt=09252016&rhgmxieu=09302016&fokrjnybiu=&xrkngg=&oviq=&zaplffoxxunwghfjr=3k0f&xzlpiwl=20140222162609767&q=1&vfrect=kbz%2sbneosovboju%2ayozjxdjs7gwok4rkd%2o7lafnulwwt%2hqks1r1pu65mms5p5u1lymmgqpqsnhud1vd2zwuaf3lxsw1j1zl5aotjg4nuofc85dkk9cw%2e5%2asdbrew2ampy5trucbcirurmorfmrfuuwukqwfy%2ihzdd8wpsrykwkraty567ya7pdv%2smkve3%2hcgmt%2hegqbq%2mwcrior808iuyvy2xeeuxurua5lywnc7vmctpy7cvajfpuhk0x0fe1txkjsdclorfmtsvw1qcoqfciy2iwaveegm1la%2zy9m5bccuxttbmm%2d6mjguo6qzfikz45pg%2vk5nzjoeyeknr3a7g58dgtjy8pnrdck121jrfcaepvv9dn7kr%2to7grilkap%2htygqiltsz39drgdslom4wt7sixrdv1j86r%2zbjrl1hqirawwwtqy7ruhtjmb3bc%2bpgza97l6%2bzzlgpuphxv38pp%3j%3t&z=11" "eajxmia/5.0 (dcgdsfo fx 6.1; fu:47.0) jaucs/20100101 gatqaso/47.0" "rdslanbl=24617072-3124-6w65-5277-6e7166322455.1466927153393190; hol=yixs; aagr=jpiqtub#1471591168897-132169#1471593188|ry#1471591168897-132169.22_20#1472800928|rwvkl#jrcm#1471591388; s_hubi=%20d_me%3mympy%3p%20f_ihm%3qrzctrg%25253veprmfcdx%252520dcwcue%25253ubrcmyec%252i98%252l16%252r3024%3y%20f_bw%3drxrnbao%253s%252526plo%25253vqwzoss%2525253jahipaqvs%25252520rerxgq%2525253roolhlyp%252526iqzj%25253o1%252526wju%25253xqtnse%2525253k%2525252p%2525252shqcxrf.zpezlaksha.uqw%2525252mtjldyzijzm%2525252qmhtv%2525252olsyblu%2525252hvrlfcs%2525253x_rfvbf_pgvju%2525253r1471591250384%25252526byex%2525253lagz%25252526ljvp%252526zo%25253rc%3k; m_wuvq=%20t_rwqa%3g1474183176114%2526rr%253w1%7b1474183176114%3b%20c_rlrxv%3r4%7o1471593058648%3f%20q_bv%3r1471591327056%7o1566199327056%3t%20q_cx_j%3ztdgjv%2520funzm%7t1471593127056%3w%20ifr_eh%3igegliv%253wwaxabjip%2520rwfupu%253gfcdaogb%7c1471593127058%3e%20s_flvfjlu%3tzakj%7t1471593127058%3a%20e_kq3650%3x1471591327059-yxk%7m1786951327059%3h%20a_xy30%3w1471591327059-hlw%7p1474183327059%3l%20n_bc120%3d1471591327060-uxs%7v1481959327060%3m%20n_ka7%3b1471591327061-ksj%7u1472196127061%3h; d_sn=[ii]z1|2yey59868548911c-600001044002415z[ed]; kij_ydicge=1471590666358_10979626605004547; zeh_akjizj=%7o%22tgnzuwnaewdacdsr%22%3a71%2s%22qmbhgzmsjmnxcj%22%3d19%2g%22awmazcxpndosipgfxbw%22%3r71%2u%22lfeynywrbm%22%3j5%2z%22uqopwrqupyx%22%3q22%2s%22izyqgghhvjwamwq%22%3l70%2h%22jbomjvcfvxzjmvja%22%3x33%2p%22fdnilbvj%22%3w88%7n; llx2fsuvzt=isj2gsqstp; vxv5ycdt=1124818954.20480.0000; zfuwicsjqfagbxyynm=10.96.102.86; cevtfmads=ckh_9; _fy_lm_ic_oem_=opeo; _yw_mx_edsa_~134106677_=wn1z27p31jen044a46y2d89x6485i7rx10s3627k%7p1471591216030%7pculyc%3o%2h%2pubvbil.xfelgtmokt.dzl%2ekjmzhytoum%2buqyq%2ytkgnps%2cjxijma%3f%7s0%7a5; _yex_g=1; _bzel_a=1471591334151; __nmkaa=11950165436859972402; r_hs=%5q%5cr%5u%5r; f_gw=afws; tvlwaznqldawr=0o61795484g0491k60l75d8cw7h0zg48|p6uh3875-dzp3-41gj-wx2p-8l6vur1xe086" 134689 14110`

Following is the fluent startup output:

```
2016-08-19 15:01:49 +0530 [info]: reading config file path="/etc/fluent/fluent-test.conf"
2016-08-19 15:01:49 +0530 [info]: starting fluentd-0.14.1
2016-08-19 15:01:49 +0530 [info]: spawn command to main: /usr/local/rvm/rubies/ruby-2.3.0-latest/bin/ruby -Eascii-8bit:ascii-8bit /usr/local/rvm/gems/ruby-2.3.0-latest/bin/fluentd -c /etc/fluent/fluent-test.conf --under-supervisor
2016-08-19 15:01:49 +0530 [info]: reading config file path="/etc/fluent/fluent-test.conf"
2016-08-19 15:01:49 +0530 [info]: starting fluentd-0.14.1 without supervision
2016-08-19 15:01:49 +0530 [info]: gem 'fluent-plugin-elasticsearch' version '1.5.0'
2016-08-19 15:01:49 +0530 [info]: gem 'fluent-plugin-kafka' version '0.1.5'
2016-08-19 15:01:49 +0530 [info]: gem 'fluentd' version '0.14.1'
2016-08-19 15:01:49 +0530 [info]: gem 'fluentd' version '0.12.26'
2016-08-19 15:01:49 +0530 [warn]: 'type' is deprecated parameter name. use '@type' instead.
2016-08-19 15:01:49 +0530 [info]: adding match pattern="*.**" type="stdout"
2016-08-19 15:01:49 +0530 [warn]: 'type' is deprecated parameter name. use '@type' instead.
2016-08-19 15:01:49 +0530 [info]: adding source type="udp"
2016-08-19 15:01:49 +0530 [info]: using configuration file: <ROOT>
  <source>
    type udp
    port 5120
    bind "0.0.0.0"
    body_size_limit 100KB
    time_format "%d/%b/%Y:%H:%M:%S"
    tag "system"
    format "/^.*?<\\d+>.*?\\s+(?<host>[a-z]+-\\d+-\\d+)\\s+(?<source>\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3})(?<proxy_chain>(,\\s*(.*?|(?:\\d+\\.){3}\\d+))*)\\s*((\\d+\\.){3}\\d+) - - \\[(?<time>.*?) \\+\\d+\\] \"(?<method>[A-Z]+)\\s+(?<url>.*?)\\s+HTTP/(?<version>[0-9\\.]+)\"\\s+(?<response_code>\\d+)\\s+(?<response_time>(\\d+|-))\\s+\"(?<referrer>.*?)\"\\s+\"(?<user_agent>.*?)\"\\s+\"(?<cookies>.*?)$/"
  </source>
  <match *.**>
    type stdout
  </match>
</ROOT>
2016-08-19 15:01:49 +0530 [info]: listening udp socket on 0.0.0.0:5120
```

As soon as I send this log line using netcat to the UDP Port:

`tail -1 /tmp/httpd-access.log | nc -4u -w1 127.0.0.1 5120`

Fluent gets stuck and stops processing logs. Can anyone let me know why this is happening?

**Comment by KunalAggarwal** [comment]
Any update guys? I am facing this problem quite frequently.

**Comment by repeatedly** [comment]
I want to know in_udp accepts entire log line or not?
udp packet size depends on system setting or tools.
For example, `nc` truncates the data to 1024 by default.
I assume in_udp receive broken data and it causes this CPU issue.

**Comment by repeatedly** [comment]
The problem is in_udp receives truncated logs and it causes regexp explosion issue.
in_udp can change incoming UDP packet size and some users handle 8k+ size logs without problem.
So the problem is outside of fluentd.
